Repository foundryvtt/pf2e, pull requests merged in 2022-09, with the labels that each got.

#3714 Make Thievery Checks on Handcuffs and Manacles rollable
  packs/data/age-of-ashes-bestiary.db/barushak-il-varashma.json
  packs/data/age-of-ashes-bestiary.db/heuberk-thropp.json
  packs/data/age-of-ashes-bestiary.db/ilssrah-embermead.json
  packs/data/age-of-ashes-bestiary.db/kralgurn.json
  packs/data/age-of-ashes-bestiary.db/laslunn.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-agent.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-bruiser.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-enforcer.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-poisoner.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-sneak.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-sniper.json
  packs/data/age-of-ashes-bestiary.db/scarlet-triad-thug.json
  packs/data/age-of-ashes-bestiary.db/uri-zandivar.json
  packs/data/agents-of-edgewatch-bestiary.db/grospek-lavarsus.json
  packs/data/agents-of-edgewatch-bestiary.db/shristi-melipdra.json
  packs/data/equipment.db/handcuffs-average.json
  packs/data/equipment.db/handcuffs-good.json
  packs/data/equipment.db/handcuffs-superior.json
  packs/data/equipment.db/manacles-average.json
  packs/data/equipment.db/manacles-good.json
  packs/data/equipment.db/manacles-poor.json
  packs/data/equipment.db/manacles-simple.json
  packs/data/equipment.db/manacles-superior.json
  packs/data/npc-gallery.db/bounty-hunter.json
  packs/data/npc-gallery.db/harbormaster.json
  packs/data/npc-gallery.db/jailer.json
  packs/data/npc-gallery.db/palace-guard.json
  packs/data/pfs-season-1-bestiary.db/blue-streak-ambushers-5-6.json
  packs/data/pfs-season-1-bestiary.db/guard-pfs-1-17.json
  packs/data/pfs-season-1-bestiary.db/palace-guard-pfs-1-17.json
  packs/data/pfs-season-1-bestiary.db/ptiro-valner-3-4.json
  packs/data/pfs-season-2-bestiary.db/duergar-raider.json
  packs/data/pfs-season-3-bestiary.db/hellbound-jailer-3-4.json
  packs/data/pfs-season-3-bestiary.db/hellbound-jailer-5-6.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-soldier.json
  packs/data/spells.db/maze-of-locked-doors.json
  packs/data/strength-of-thousands-bestiary.db/abendego-jailers.json
  packs/data/strength-of-thousands-bestiary.db/halbrux-far-sight.json
  packs/data/strength-of-thousands-bestiary.db/yonsuu.json
Labels: pr: data update

#3713 Add icon for overridden conditions in token hud
  src/module/canvas/status-effects.ts
  src/styles/ui/_token-hud.scss
Labels: pr: enhancement, ui/ux

#3717 Remove PF2e Journal sheet, fix some tinymce bugs
  src/module/journal-entry/sheet.ts
  src/scripts/register-sheets.ts
  src/styles/mixins/_tinymce.scss
  src/styles/system/journal/_header.scss
  src/styles/system/journal/_index.scss
  src/styles/tinymce.scss
  system.json
  webpack.config.ts
Labels: pr: bugfix

#3718 Search Contents also matches compendium pack names
  src/module/apps/ui/compendium-directory.ts
Labels: pr: enhancement

#3719 Update/remove several canvas-related types for V10
  src/global.d.ts
  src/module/apps/scene-darkness-adjuster.ts
  src/module/canvas/group/effects.ts
  src/module/canvas/index.ts
  src/module/canvas/layer/lighting.ts
  src/scripts/hooks/init.ts
  src/scripts/hooks/lighting-refresh.ts
  types/foundry/client/config.d.ts
  types/foundry/client/documents/token-document.d.ts
  types/foundry/client/pixi/canvas-layer/effects-layer.d.ts
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/groups/index.d.ts
  types/foundry/client/pixi/groups/interface.d.ts
  types/foundry/client/pixi/helpers/point-source-polygon.d.ts
  types/foundry/client/pixi/helpers/point-source/base.d.ts
  types/foundry/client/pixi/helpers/point-source/light-source.d.ts
  types/foundry/client/pixi/helpers/point-source/vision-source.d.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/interface-canvas-group.d.ts
  types/foundry/client/pixi/mask-filter/base.d.ts
  types/foundry/client/pixi/mask-filter/inverse-occlusion-mask-filter.d.ts
  types/foundry/client/pixi/perception/detection-mode.d.ts
  types/foundry/client/pixi/perception/vision-mode.d.ts
  types/foundry/client/pixi/shader/adaptive-background-shader.d.ts
  types/foundry/client/pixi/shader/adaptive-coloration-shader.d.ts
  types/foundry/client/pixi/shader/adaptive-illumination-shader.d.ts
  types/foundry/client/pixi/shader/adaptive-lighting-shader.d.ts
  types/foundry/client/pixi/shader/base.d.ts
  types/foundry/client/pixi/shader/index.d.ts
  types/foundry/client/pixi/shader/pulse-coloration-shader.d.ts
  types/foundry/client/pixi/shader/pulse-illumination-shader.d.ts
  types/foundry/client/pixi/shader/standard-coloration-shader.d.ts
  types/foundry/client/pixi/shader/standard-illumination-shader.d.ts
  types/foundry/client/pixi/shader/torch-coloration-shader.d.ts
  types/foundry/client/pixi/shader/torch-illumination-shader.d.ts
  types/foundry/client/pixi/webgl/base.d.ts
  types/foundry/client/pixi/webgl/index.d.ts
  types/foundry/client/pixi/webgl/shaders/index.d.ts
  types/foundry/client/pixi/webgl/shaders/sampler.d.ts
  types/foundry/common/documents/token.d.ts
  types/foundry/index.d.ts
Labels: pr: foundry v10, pr: types update

#3720 Restore functionality of scene darkness adjuster preview feature
  src/module/apps/scene-darkness-adjuster.ts
  src/module/canvas/group/effects.ts
  src/scripts/hooks/lighting-refresh.ts
  types/foundry/client/documents/scene.d.ts
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/client/pixi/perception/color-manager.d.ts
  types/foundry/client/pixi/perception/index.d.ts
  types/foundry/common/utils/color.d.ts
Labels: pr: foundry v10

#3716 Make skill buttons rollable for Crafting, Perception, and Arcana
  packs/data/agents-of-edgewatch-bestiary.db/arcane-feedback-trap.json
  packs/data/agents-of-edgewatch-bestiary.db/blackfingers-prayer.json
  packs/data/agents-of-edgewatch-bestiary.db/eyeball-tank.json
  packs/data/agents-of-edgewatch-bestiary.db/gref.json
  packs/data/agents-of-edgewatch-bestiary.db/kekker.json
  packs/data/agents-of-edgewatch-bestiary.db/kharnass-lesser-glyph.json
  packs/data/agents-of-edgewatch-bestiary.db/summoning-rune-barbazu-devil.json
  packs/data/book-of-the-dead-bestiary.db/ichor-slinger.json
  packs/data/equipment.db/communication-bangle.json
  packs/data/equipment.db/deck-of-mischief.json
  packs/data/equipment.db/false-death.json
  packs/data/equipment.db/false-manacles.json
  packs/data/equipment.db/fingerprint-kit.json
  packs/data/equipment.db/ghost-ink.json
  packs/data/equipment.db/infiltrators-accessory.json
  packs/data/equipment.db/lovers-ink.json
  packs/data/equipment.db/marked-playing-cards.json
  packs/data/equipment.db/palm-crossbow.json
  packs/data/equipment.db/snake-oil.json
  packs/data/equipment.db/sphere-of-annihilation.json
  packs/data/equipment.db/starless-scope.json
  packs/data/equipment.db/tears-of-the-last-azlanti.json
  packs/data/extinction-curse-bestiary.db/poisoned-secret-door-trap.json
  packs/data/hazards.db/jealous-abjurer.json
  packs/data/pathfinder-bestiary-2.db/froghemoth.json
  packs/data/pfs-season-1-bestiary.db/pile-of-fireworks-3-4.json
  packs/data/pfs-season-1-bestiary.db/pile-of-fireworks-5-6.json
  packs/data/strength-of-thousands-bestiary.db/worknesh.json
  static/lang/en.json
Labels: pr: data update

#3721 Restore token z-cycling
  src/module/canvas/layer/template.ts
  src/module/canvas/layer/token.ts
  types/foundry/client/documents/token-document.d.ts
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/client/pixi/groups/index.d.ts
  types/foundry/client/pixi/groups/primary.d.ts
  types/foundry/client/pixi/placeables-layer/base.d.ts
Labels: pr: foundry v10

#3723 Bump system compatibility version again
  system.json
Labels: pr: housekeeping

#3726 Rename Exploration Effects to Other Effects, move Cover effect to it
  packs/data/abomination-vaults-bestiary.db/sarglagon-av.json
  packs/data/actions.db/follow-the-expert.json
  packs/data/actions.db/scout.json
  packs/data/feats.db/incredible-scout.json
  packs/data/feats.db/shield-wall.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/peng.json
  packs/data/npc-gallery.db/archer-sentry.json
  packs/data/other-effects.db/effect-cover.json
  packs/data/other-effects.db/effect-follow-the-expert.json
  packs/data/other-effects.db/effect-scouting-incredible-scout.json
  packs/data/other-effects.db/effect-scouting.json
  packs/data/pathfinder-bestiary-2.db/sarglagon.json
  packs/data/pathfinder-bestiary-3.db/azarketi-explorer.json
  packs/data/pathfinder-bestiary-3.db/mix-couatl.json
  src/module/migration/migrations/778-rename-feature-effects-refs.ts
  system.json
Labels: pr: data migration

#3725 Make rollable buttons for Athletics checks
  packs/data/adventure-specific-actions.db/topple-crates.json
  packs/data/age-of-ashes-bestiary.db/ilgreth.json
  packs/data/agents-of-edgewatch-bestiary.db/avsheros-the-betrayer.json
  packs/data/agents-of-edgewatch-bestiary.db/clockwork-arms.json
  packs/data/agents-of-edgewatch-bestiary.db/ink-drowning-vats.json
  packs/data/agents-of-edgewatch-bestiary.db/the-winder.json
  packs/data/agents-of-edgewatch-bestiary.db/waxworks-onslaught-trap.json
  packs/data/archetypes.db/ghost.json
  packs/data/blood-lords-bestiary.db/sallowdrudge.json
  packs/data/book-of-the-dead-bestiary.db/siabrae.json
  packs/data/criticaldeck.db/critical-fumble-deck-31.json
  packs/data/equipment.db/anchor-spear.json
  packs/data/equipment.db/beacon-shot.json
  packs/data/equipment.db/climbing-bolt.json
  packs/data/equipment.db/immovable-tripod.json
  packs/data/equipment.db/mountain-to-the-sky.json
  packs/data/equipment.db/necklace-of-strangulation.json
  packs/data/equipment.db/net.json
  packs/data/equipment.db/sovereign-glue.json
  packs/data/extinction-curse-bestiary.db/deghuun-child-of-mhar.json
  packs/data/extinction-curse-bestiary.db/vavakia.json
  packs/data/feats.db/garudas-squall.json
  packs/data/feats.db/pinning-fire.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/taiga-yai.json
  packs/data/hazards.db/perilous-flash-flood.json
  packs/data/hazards.db/plummeting-doom.json
  packs/data/hazards.db/quicksand.json
  packs/data/iconics.db/harsk-level-5.json
  packs/data/npc-gallery.db/veteran-reclaimer.json
  packs/data/one-shot-bestiary.db/precarious-pile.json
  packs/data/paizo-pregens.db/zeah.json
  packs/data/pathfinder-bestiary-2.db/ancient-magma-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-2.db/bog-strider.json
  packs/data/pathfinder-bestiary-2.db/grippli-scout.json
  packs/data/pathfinder-bestiary-2.db/lerritan.json
  packs/data/pathfinder-bestiary-2.db/marut.json
  packs/data/pathfinder-bestiary-2.db/planetar.json
  packs/data/pathfinder-bestiary-3.db/cecaelia-trapper.json
  packs/data/pathfinder-bestiary-3.db/draconal-black.json
  packs/data/pathfinder-bestiary-3.db/draconal-green.json
  packs/data/pathfinder-bestiary-3.db/draconal-red.json
  packs/data/pathfinder-bestiary-3.db/draconal-white.json
  packs/data/pathfinder-bestiary-3.db/draconal-yellow.json
  packs/data/pathfinder-bestiary-3.db/lampad-queen.json
  packs/data/pathfinder-bestiary-3.db/sturzstromer.json
  packs/data/pathfinder-bestiary-3.db/tolokand.json
  packs/data/pfs-introductions-bestiary.db/swampy-quicksand.json
  packs/data/spells.db/aqueous-orb.json
  packs/data/spells.db/earthquake.json
  packs/data/spells.db/maze-of-locked-doors.json
  packs/data/spells.db/pillars-of-sand.json
  packs/data/spells.db/transmute-rock-and-mud.json
  packs/data/strength-of-thousands-bestiary.db/slana.json
  packs/data/strength-of-thousands-bestiary.db/ssumzili.json
  packs/data/strength-of-thousands-bestiary.db/unshadowed-anchor-root.json
  packs/data/strength-of-thousands-bestiary.db/worknesh.json
  packs/data/the-slithering-bestiary.db/scroll-shock-trap.json
Labels: pr: data update

#3728 Filter out V10 journal entry pages from isItemSource
  packs/scripts/packman/compendium-pack.ts
Labels: pr: foundry v10

#3729 Move Aid and Aquatic Combat effects to Other Effects
  packs/data/actions.db/aid.json
  packs/data/other-effects.db/effect-aid.json
  packs/data/other-effects.db/effect-aquatic-combat-no-swim-speed.json
  packs/data/other-effects.db/effect-aquatic-combat.json
Labels: pr: data update

#3733 Remove html in table formatting
  packs/data/equipment.db/pistol-of-wonder.json
  packs/data/iconics.db/seelah-level-1.json
Labels: pr: data update

#3735 Change "statusEffectShowCombatMessage" setting to world scope
  src/module/system/settings/index.ts
Labels: pr: bugfix

#3734 Fix dead overlay receiving overridden icon in token HUD
  src/module/canvas/status-effects.ts
Labels: pr: bugfix

#3737 Restore rules-based vision for V10
  src/module/canvas/perception/modes.ts
  src/module/canvas/status-effects.ts
  src/module/scene/sheet.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  src/module/user/player-config.ts
  src/scripts/hooks/init.ts
  src/styles/scene/_token-config.scss
  static/lang/en.json
Labels: pr: foundry v10

#3739 Remove #private field in TokenDocumentPF2e
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#3742 Add duration to Air Bubble spell
  packs/data/spells.db/air-bubble.json
Labels: pr: data update

#3741 Fix details of Intensify Vulnerability feature
  packs/data/classfeatures.db/intensify-vulnerability.json
Labels: pr: data update

#3740 Add automation to the Magical Experiment background.
  packs/data/backgrounds.db/magical-experiment.json
  static/lang/re-en.json
Labels: pr: data update

#3731 Begin consolidating journals, add GM screen.
  packs/data/journals.db/archetypes.json
  packs/data/journals.db/domains.json
  packs/data/journals.db/gm-screen.json
  system.json
Labels: pr: data update

#3746 Fix issue preventing name-to-uuid in some items from build.ts
  packs/scripts/packman/compendium-pack.ts
Labels: pr: bugfix

#3750 No longer save Elite/Weak in traits
  packs/data/agents-of-edgewatch-bestiary.db/barrel-launcher.json
  packs/data/agents-of-edgewatch-bestiary.db/clockwork-chopper.json
  packs/data/agents-of-edgewatch-bestiary.db/clockwork-injector.json
  packs/data/agents-of-edgewatch-bestiary.db/lie-master.json
  packs/data/agents-of-edgewatch-bestiary.db/mr-snips.json
  packs/data/agents-of-edgewatch-bestiary.db/pulping-golem.json
  packs/data/blood-lords-bestiary.db/arghun-the-annihilator.json
  packs/data/blood-lords-bestiary.db/mummy-valet.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-brartork.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-han.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-jun.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-krankkiss.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-mingyu.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-numoriz.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-paunnima.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-rajna.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/ki-adept-ahmoza-twins.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/weapon-master-under-the-pale-sun-dervishes.json
  packs/data/outlaws-of-alkenstar-bestiary.db/alethsia.json
  packs/data/outlaws-of-alkenstar-bestiary.db/brighite-herexen.json
  packs/data/outlaws-of-alkenstar-bestiary.db/broken-centurion.json
  packs/data/outlaws-of-alkenstar-bestiary.db/captured-dezullon.json
  packs/data/outlaws-of-alkenstar-bestiary.db/glass-sentry.json
  packs/data/outlaws-of-alkenstar-bestiary.db/ioton-f6.json
  packs/data/outlaws-of-alkenstar-bestiary.db/ogre-slug.json
  packs/data/outlaws-of-alkenstar-bestiary.db/skeletal-crocodile.json
  packs/data/pfs-season-1-bestiary.db/elite-boggard-swampseer-pfs-1-24-animal-staff.json
  packs/data/pfs-season-1-bestiary.db/elite-boggard-swampseer-pfs-1-24-staff.json
  packs/data/pfs-season-1-bestiary.db/weak-green-hag.json
  packs/data/pfs-season-3-bestiary.db/elite-hieracosphinx-pfs-3-14.json
  packs/data/pfs-season-3-bestiary.db/eltha-embercall-11-12-28-cp.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/throttled-blindheim.json
  packs/scripts/run-migration.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/index.ts
  src/module/actor/npc/sheet.ts
  src/module/migration/migrations/779-elite-weak.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: bugfix

#3753 Permit macros and modules to pass roll-option arrays to CheckPF2e.roll
  src/module/system/rolls.ts
Labels: pr: enhancement

#3755 Add See Invisibility sense, move sense localization to `Actor.Creature`
  packs/data/spell-effects.db/spell-effect-see-invisibility.json
  packs/data/spells.db/see-invisibility.json
  src/module/actor/creature/sense.ts
  src/module/actor/familiar/index.ts
  src/module/scene/token-document/document.ts
  src/scripts/config/index.ts
  static/lang/en.json
  static/templates/items/ancestry-sidebar.html
Labels: localization, pr: enhancement

#3757 Remove uiTheme user setting
  src/module/user/player-config.ts
  src/scripts/hooks/ready.ts
  src/styles/settings/_index.scss
  static/styles/user/color-scheme-blue.css
  static/styles/user/color-scheme-original.css
  static/styles/user/color-scheme-red.css
  static/styles/user/color-scheme-ui.css
Labels: pr: enhancement

#3758 Fix application of dexterity modifier cap when AC is zero
  src/module/actor/base.ts
  src/module/actor/character/data/types.ts
  src/module/actor/character/index.ts
  src/module/actor/character/types.ts
  src/module/actor/data/base.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/index.ts
  src/module/rules/rule-element/dexterity-modifier-cap.ts
  src/module/rules/synthetics.ts
Labels: pr: bugfix, pr: refactor

#3756 Add selector list support to FlatModifier
  src/module/rules/rule-element/flat-modifier.ts
Labels: pr: enhancement

#3760 Update token drag-preview cloning for V10
  src/module/canvas/token/object.ts
Labels: pr: foundry v10

#3761 Move management of system user settings to user sheet
  src/module/apps/ui/player-list.ts
  src/module/user/data.ts
  src/module/user/document.ts
  src/module/user/player-config.ts
  src/module/user/sheet.ts
  src/scripts/hooks/init.ts
  src/scripts/register-sheets.ts
  static/lang/en.json
  static/templates/user/player-config.html
  static/templates/user/sheet.html
  types/foundry/client/application/form-application/document-sheet-config.d.ts
  types/foundry/client/application/form-application/document-sheet/base.d.ts
  types/foundry/client/application/form-application/document-sheet/user-config.d.ts
  types/foundry/client/application/form-application/other.d.ts
  types/foundry/client/application/hud/players.d.ts
  types/foundry/client/config.d.ts
  types/foundry/index.d.ts
Labels: pr: refactor

#3763 Hide sidebar on rules tab
  src/module/item/sheet/base.ts
  src/module/item/sheet/data-types.ts
  src/styles/item/_index.scss
  src/styles/item/_sidebar.scss
  static/templates/items/ancestry-sidebar.html
  static/templates/items/armor-sidebar.html
  static/templates/items/backpack-sidebar.html
  static/templates/items/book-sidebar.html
  static/templates/items/condition-sidebar.html
  static/templates/items/consumable-sidebar.html
  static/templates/items/effect-sidebar.html
  static/templates/items/equipment-sidebar.html
  static/templates/items/feat-sidebar.html
  static/templates/items/formula-sidebar.html
  static/templates/items/heritage-sidebar.html
  static/templates/items/item-sheet.html
  static/templates/items/kit-sidebar.html
  static/templates/items/lore-sidebar.html
  static/templates/items/spell-sidebar.html
  static/templates/items/treasure-sidebar.html
  static/templates/items/weapon-sidebar.html
Labels: ui/ux

#3766 Avoid error in `getTrackedAttributes` given actor with crafting entries
  src/module/actor/character/crafting/entry.ts
  src/module/rules/rule-element/crafting/entry.ts
Labels: pr: bugfix

#3767 Update tagify and work around bug with firefox
  package-lock.json
  package.json
  src/util/tags.ts
Labels: pr: bugfix

#3770 Add series of DOM query helper functions for typescript
  src/util/dom.ts
  src/util/index.ts
Labels: pr: enhancement

#3772 Refocus tagify on re-render
  src/module/actor/sheet/base.ts
  src/module/item/sheet/base.ts
  src/util/tags.ts
Labels: pr: enhancement

#3777 Add v10 compatibility data to v9 system.json
  system.json
Labels: pr: bugfix

#3779 Monkey-patch `TokenDocument#_preUpdateTokenActor`
  src/scripts/🐵🩹.ts
Labels: pr: foundry v10

#3780 Port fix over from #3774
  src/module/migration/migrations/774-unpersist-crafting-entries.ts
Labels: pr: bugfix

#3774 Remove `selector` property from base RuleElementSource interface
  src/module/actor/character/crafting/entry.ts
  src/module/item/sheet/base.ts
  src/module/migration/migrations/631-fix-sense-rule-element-selector.ts
  src/module/migration/migrations/655-creature-token-sizes.ts
  src/module/migration/migrations/668-armor-speed-penalty.ts
  src/module/migration/migrations/673-remove-bulwark-res.ts
  src/module/migration/migrations/675-flat-modifier-aes-to-res.ts
  src/module/migration/migrations/689-encumberance-aes.ts
  src/module/migration/migrations/691-weapon-range-ability-category-group.ts
  src/module/migration/migrations/696-flat-ability-modifiers.ts
  src/module/migration/migrations/701-modifier-name-to-slug.ts
  src/module/migration/migrations/702-re-formulas-at-instance-level.ts
  src/module/migration/migrations/708-specific-rule-label.ts
  src/module/migration/migrations/716-strike-damage-selector.ts
  src/module/migration/migrations/725-quick-climb-rule-elements.ts
  src/module/migration/migrations/730-derune-handwraps.ts
  src/module/migration/migrations/731-toggle-property-to-roll-option.ts
  src/module/migration/migrations/745-effect-target-to-choice-set.ts
  src/module/migration/migrations/764-panache-vivacious-res.ts
  src/module/migration/migrations/774-unpersist-crafting-entries.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/adjust-degree-of-success.ts
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/base-speed.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/crafting/entry.ts
  src/module/rules/rule-element/damage-dice.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/fixed-proficiency.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/module/rules/rule-element/multiple-attack-penalty.ts
  src/module/rules/rule-element/roll-note.ts
  src/module/rules/rule-element/roll-twice.ts
  src/module/rules/rule-element/sense.ts
  src/module/rules/rule-element/striking.ts
  src/module/rules/rule-element/substitute-roll.ts
  src/module/rules/rule-element/weapon-potency.ts
Labels: pr: refactor

#3776 Show message when scene darkness slider is disabled
  src/module/apps/scene-darkness-adjuster.ts
  src/module/apps/world-clock/app.ts
  src/module/scene/document.ts
  src/module/scene/sheet.ts
  src/module/scene/token-document/sheet.ts
  src/styles/_globals.scss
  src/styles/scene/_darkness-adjuster.scss
  src/styles/scene/_index.scss
  src/styles/scene/_sheet.scss
  src/styles/settings/_index.scss
  src/styles/settings/_scene.scss
  static/lang/en.json
Labels: pr: enhancement, ui/ux

#3727 Focus check dialog roll button on initial render so that enter key rolls immediately
  src/module/system/check-modifiers-dialog.ts
Labels: pr: enhancement

#3785 Refrain from using basic unarmed attack as item for combat maneuvers
  src/module/system/action-macros/helpers.ts
Labels: pr: bugfix

#3769 Automate suli feats
  packs/data/feat-effects.db/effect-elemental-assault.json
  packs/data/feats.db/dualborn.json
  packs/data/feats.db/elemental-assault.json
  packs/data/feats.db/elemental-embellish.json
  packs/data/feats.db/scholars-inheritance.json
  packs/data/feats.db/suli-jann.json
  static/lang/re-en.json
Labels: pr: data update

#3789 Prevent substituted D20 rolls from being classified as damage rolls
  src/module/chat-message/document.ts
Labels: pr: bugfix

#3788 Add penalty for attempting to Force Open without crowbar
  src/module/actor/character/helpers.ts
  src/module/actor/character/index.ts
  static/lang/en.json
Labels: pr: enhancement

#3784 Automate sylph and undine feats
  packs/data/actions.db/mist-blending.json
  packs/data/actions.db/salt-wound.json
  packs/data/actions.db/smoke-blending.json
  packs/data/feat-effects.db/effect-tidal-shield.json
  packs/data/feats.db/airy-step.json
  packs/data/feats.db/fumesoul.json
  packs/data/feats.db/rimesoul.json
  packs/data/feats.db/tidal-shield.json
  packs/data/feats.db/wings-of-air.json
Labels: pr: data update

#3792 Remove mention of Foundry (Classic) journal entry sheet
  src/scripts/register-sheets.ts
  static/lang/en.json
Labels: pr: bugfix

#3790 Move journal entry `InlineRollLinks.listen` call to hook
  src/module/journal-entry/sheet.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-journal-page-sheet.ts
  src/scripts/hooks/render-journal-text-page-sheet.ts
  types/foundry/client/core/hooks.d.ts
Labels: pr: foundry v10

#3791 Fix heightening spontaneous spells and tricked spells
  src/module/item/spell/index.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/spellcasting-entry/trick.ts
Labels: pr: bugfix

#3794 Fix actor sheets not updating if tagify traits are empty
  src/module/actor/npc/sheet.ts
Labels: pr: bugfix

#3781 Convert inline links in localizations to reference UUID
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#3795 Acquire of modifier adjustments from within @actor/character/helpers
  src/module/actor/character/helpers.ts
  src/module/actor/character/index.ts
  src/module/system/action-macros/helpers.ts
Labels: pr: bugfix

#3754 Prune `location` from unembedded feats and spells on extract
  packs/scripts/extract.ts
Labels: pr: data update

#3796 Remove deprecated `CharacterPF2e#insertFeats`
  src/module/actor/character/index.ts
Labels: pr: housekeeping

#3802 Fix empty gap created by @Localize and use all sub-elements
  src/module/system/text-editor.ts
  src/styles/legacy/_chat.scss
  src/styles/mixins/_tinymce.scss
Labels: pr: bugfix, pr: foundry v10

#3800 Migrate applicable items to suppress no-crowbar penalty
  packs/data/agents-of-edgewatch-bestiary.db/franca-laurentz.json
  packs/data/extinction-curse-bestiary.db/swardlands-delinquent.json
  packs/data/iconics.db/merisiel-level-1.json
  packs/data/iconics.db/merisiel-level-3.json
  packs/data/iconics.db/merisiel-level-5.json
  packs/data/iconics.db/sajan-level-1.json
  packs/data/iconics.db/sajan-level-5.json
  packs/data/npc-gallery.db/saboteur.json
  packs/data/paizo-pregens.db/booker-kaar.json
  packs/data/paizo-pregens.db/kangir.json
  packs/data/paizo-pregens.db/muruwa.json
  packs/data/paizo-pregens.db/yacob.json
  packs/data/pfs-season-3-bestiary.db/branwaen.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/781-suppress-no-crowbar.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration

#3803 Fix version number in crowbar migration
  src/module/migration/migrations/781-suppress-no-crowbar.ts
Labels: pr: bugfix

#3805 Remove effect badge type selection while counter is the only type
  static/templates/items/effect-sidebar.html
Labels: pr: housekeeping

#3808 Replace reference to Module#compatibleCoreVersion with #compatibility
  src/scripts/hooks/ready.ts
  types/foundry/client/game.d.ts
Labels: pr: foundry v10

#3809 Restore json data-dtype handling to homebrew menu
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/menu.ts
Labels: pr: foundry v10

#3783 Automate strix feats
  packs/data/feat-effects.db/effect-juvenile-flight.json
  packs/data/feats.db/feathered-cloak.json
  packs/data/feats.db/ferocious-gust.json
  packs/data/feats.db/fledgling-flight.json
  packs/data/feats.db/juvenile-flight.json
  packs/data/feats.db/story-crooner.json
  packs/data/feats.db/strix-defender.json
  packs/data/feats.db/strix-lore.json
  packs/data/feats.db/strix-vengeance.json
Labels: pr: data update

#3812 Fix display of scrollbars in hazard sheet
  src/styles/actor/hazard/_index.scss
  src/styles/actor/hazard/_sidebar.scss
Labels: pr: bugfix, ui/ux

#3813 Accommodate recent changes to token post-update workflows
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix, pr: foundry v10

#3814 Fix display and deprecation warnings in vehicle biography screen
  src/styles/actor/tabs/_bio.scss
  static/templates/actors/vehicle/tabs/vehicle-description.html
Labels: pr: bugfix, ui/ux

#3811 Fix hazard updates when traits are empty
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/sheet/base.ts
  src/module/sheet/helpers.ts
Labels: pr: bugfix

#3816 Fix darkvision vision mode not seeing tokens when RBV was disabled
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#3815 Show Granted Item on same line in form
  src/styles/item/_index.scss
  src/styles/item/_rules.scss
  src/styles/item/_tagify.scss
  src/util/tags.ts
  static/templates/items/rules/grant-item.html
  types/foundry/common/utils/helpers.d.ts
Labels: ui/ux

#3817 Fix injected paths for AE-like REs
  src/module/rules/rule-element/ae-like.ts
Labels: pr: bugfix

#3818 Release Notes 4.0.0-beta2
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#3819 Release 4.0.0-beta2
  CHANGELOG.md
  package-lock.json
  package.json
  packs/data/feat-effects.db/effect-juvenile-flight.json
  packs/data/feats.db/feathered-cloak.json
  packs/data/feats.db/ferocious-gust.json
  packs/data/feats.db/fledgling-flight.json
  packs/data/feats.db/juvenile-flight.json
  packs/data/feats.db/story-crooner.json
  packs/data/feats.db/strix-defender.json
  packs/data/feats.db/strix-lore.json
  packs/data/feats.db/strix-vengeance.json
  packs/data/pathfinder-bestiary-2.db/icewyrm.json
  src/module/actor/base.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/sheet/base.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/scene/token-document/document.ts
  src/module/sheet/helpers.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/menu.ts
  src/scripts/hooks/ready.ts
  src/styles/actor/hazard/_index.scss
  src/styles/actor/hazard/_sidebar.scss
  src/styles/actor/tabs/_bio.scss
  src/styles/item/_index.scss
  src/styles/item/_rules.scss
  src/styles/item/_tagify.scss
  src/util/tags.ts
  static/templates/actors/vehicle/tabs/vehicle-description.html
  static/templates/items/rules/grant-item.html
  system.json
  types/foundry/client/game.d.ts
  types/foundry/common/utils/helpers.d.ts
Labels: pr: housekeeping

#3824 Remove some explicit `any`s in `CharacterSheetPF2e`
  .betterer.results
  src/module/actor/character/sheet.ts
Labels: pr: types update

#3825 Restore damage types to spell sheet
  src/module/item/spell/sheet.ts
Labels: pr: bugfix

#3829 Fix tagify refocus regression for npc embedded item traits
  src/module/actor/sheet/base.ts
  src/module/item/sheet/base.ts
  src/module/sheet/helpers.ts
Labels: pr: bugfix

#3827 Fix removing Elite/Weak adjustments
  src/module/actor/npc/sheet.ts
  static/templates/actors/npc/partials/header.html
Labels: pr: bugfix

#3826 Move RE forms to folder
  src/module/item/sheet/base.ts
  src/module/item/sheet/rule-elements/base.ts
  src/module/item/sheet/rule-elements/index.ts
Labels: pr: housekeeping

#3832 Clone item source before using it for crafting entry update
  src/module/actor/character/crafting/entry.ts
Labels: pr: bugfix

#3833 Release Notes 4.0.0-beta3
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#3831 Fix source of Undead Scourge equipment
  packs/data/equipment.db/undead-scourge.json
Labels: pr: data update

#3836 Disable vision options in prototype token config if RBV is enabled
  src/module/scene/token-document/sheet.ts
Labels: pr: bugfix

#3837 Abbreviate link tag in en.json as "wt" instead of "wc"
  src/module/apps/world-clock/app.ts
  static/lang/en.json
Labels: pr: bugfix

#3838 Fix compendium browser pre-filter for ancestry feats on PC sheet
  src/module/actor/character/feats.ts
  src/module/apps/world-clock/app.ts
Labels: pr: bugfix

#3843 Rename another DnD-ism introduced in V10
  static/lang/en.json
Labels: pr: enhancement

#3840 Change default order-by for most compendium browser tabs to level
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
  src/module/apps/compendium-browser/tabs/spell.ts
  static/templates/compendium-browser/filters.html
Labels: pr: enhancement

#3845 Add support for item drops on familiar tokens
  src/module/actor/base.ts
  src/scripts/hooks/drop-canvas-data.ts
Labels: pr: enhancement

#3850 Fix display of repeating ammo in character sheet
  static/templates/actors/character/tabs/actions.html
Labels: pr: bugfix

#3854 Take first stab at hearing detection mode
  src/module/canvas/perception/modes.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/pixi/mask-filter/base.d.ts
  types/foundry/client/pixi/mask-filter/inverse-occlusion-mask-filter.d.ts
  types/foundry/client/pixi/perception/detection-mode.d.ts
  types/foundry/client/pixi/webgl/base.d.ts
  types/foundry/client/pixi/webgl/filters/filters.d.ts
  types/foundry/client/pixi/webgl/filters/index.d.ts
  types/foundry/client/pixi/webgl/index.d.ts
  types/foundry/index.d.ts
Labels: pr: enhancement

#3860 Fix stack overflow sometimes triggered when closing token config
  src/module/actor/base.ts
Labels: pr: bugfix

#3861 Remove `PlayersListPF2e` now that `UserConfigPF2e` is constructed
  src/module/apps/ui/player-list.ts
  src/scripts/hooks/init.ts
Labels: pr: housekeeping

#3862 Fix pair of issues with darkness adjuster when viewed scene is changed
  src/module/apps/scene-darkness-adjuster.ts
  src/scripts/hooks/get-scene-control-buttons.ts
Labels: pr: bugfix

#3865 Remove monkey patching of `TokenDocument#_preUpdateTokenActor`
  src/scripts/🐵🩹.ts
  system.json
Labels: pr: housekeeping

#3866 Remove `applyMod` from Harm spell variant
  packs/data/spells.db/harm.json
Labels: pr: data update

#3867 Fix ammo not getting consumed
  src/module/actor/character/index.ts
Labels: pr: bugfix

#3874 Fix removal of basic unarmed attack causing strike-index mismatching
  src/module/actor/character/data/types.ts
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/styles/actor/tabs/_actions.scss
  static/templates/actors/character/tabs/actions.html
Labels: pr: bugfix

#3849 Add strike getter to chat message for module use
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
  src/util/dom.ts
Labels: pr: enhancement

#3875 Remove temporary method override in TemplateLayerPF2e
  src/module/canvas/layer/template.ts
Labels: pr: foundry v10

#3876 Override `Token#_draw` instead of `PlaceableObject#draw`
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/placeable-object/ambient-light.d.ts
  types/foundry/client/pixi/placeable-object/ambient-sound.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/client/pixi/placeable-object/drawing.d.ts
  types/foundry/client/pixi/placeable-object/measured-template.d.ts
  types/foundry/client/pixi/placeable-object/note.d.ts
  types/foundry/client/pixi/placeable-object/tile.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
  types/foundry/client/pixi/placeable-object/wall.d.ts
Labels: pr: foundry v10

#3880 Fix incorrect prototype token names
  packs/data/blood-lords-bestiary.db/aeolaeka.json
  packs/data/blood-lords-bestiary.db/benefactors-end.json
  packs/data/blood-lords-bestiary.db/grace-the-rhino-owano.json
  packs/data/blood-lords-bestiary.db/guloval.json
  packs/data/blood-lords-bestiary.db/hungering-growths.json
  packs/data/blood-lords-bestiary.db/kerinza.json
  packs/data/blood-lords-bestiary.db/lasheeli.json
  packs/data/blood-lords-bestiary.db/memory-hole.json
  packs/data/blood-lords-bestiary.db/nwanyian-archers.json
  packs/data/blood-lords-bestiary.db/shadow-heart.json
  packs/data/blood-lords-bestiary.db/shimmernewt.json
  packs/data/blood-lords-bestiary.db/skeletal-knights.json
  packs/data/blood-lords-bestiary.db/the-fight.json
  packs/data/blood-lords-bestiary.db/the-flight.json
  packs/data/blood-lords-bestiary.db/yshula.json
Labels: pr: data update

#3858 Add missing traits to Peachwood Talisman
  packs/data/equipment.db/peachwood-talisman.json
Labels: pr: data update

#3877 Add REs to handle Flying Blade feat
  packs/data/classfeatures.db/precise-strike.json
  packs/data/feats.db/swashbucklers-speed.json
Labels: pr: data update

#3882 Fix add/remove attack proficiencies on PC sheet
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/popups/manage-attack-proficiencies.ts
  src/util/dom.ts
  static/templates/actors/character/tabs/proficiencies.html
Labels: pr: bugfix

#3884 Actually replace Earn Income macro
  packs/data/macros.db/earn-income.json
Labels: pr: data update

#3881 Add references to Coerce and buttons to Intimidation Feats
  packs/data/feats.db/battle-cry.json
  packs/data/feats.db/group-coercion.json
  packs/data/feats.db/intimidating-glare.json
  packs/data/feats.db/intimidating-prowess.json
  packs/data/feats.db/lasting-coercion.json
  packs/data/feats.db/quick-coercion.json
  packs/data/feats.db/reveal-true-name.json
  packs/data/feats.db/terrifying-resistance.json
Labels: pr: data update

#3887 Fix localization of sprite strikes
  packs/data/feats.db/sprites-spark.json
Labels: pr: data update

#3883 Fix error when enriching null strings
  src/module/system/text-editor.ts
  types/foundry/client/core/text-editor.d.ts
Labels: pr: bugfix

#3889 Fix showing limited NPCs with `actorLink`s in actor directory
  src/module/actor/npc/index.ts
Labels: pr: foundry v10

#3885 Automate tengu feats
  packs/data/equipment.db/tengu-feather-fan.json
  packs/data/feat-effects.db/effect-great-tengu-form.json
  packs/data/feat-effects.db/effect-soaring-flight.json
  packs/data/feats.db/blade-of-justice.json
  packs/data/feats.db/favor-of-heaven.json
  packs/data/feats.db/great-tengu-form.json
  packs/data/feats.db/long-nosed-form.json
  packs/data/feats.db/scar-thick-skin.json
  packs/data/feats.db/soaring-flight.json
  packs/data/feats.db/soaring-form.json
  packs/data/feats.db/tengu-feather-fan.json
  packs/data/feats.db/tengu-lore.json
  packs/data/feats.db/thunder-gods-fan.json
  packs/data/feats.db/waxed-feathers.json
  packs/data/feats.db/wind-gods-fan.json
Labels: pr: data update

#3892 Only show repost buttons on chat messages to message owners
  src/scripts/hooks/render-chat-message.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: enhancement

#3895 Always perform combined shallow/deep search in compendium sidebar
  src/module/apps/ui/compendium-directory.ts
  src/styles/ui/sidebar/_compendium-directory.scss
  static/lang/en.json
  static/templates/sidebar/compendium-directory.html
Labels: pr: enhancement

#3893 Include equivalent weapon bases in weapon roll options
  src/module/item/weapon/index.ts
Labels: pr: bugfix

#3896 Fix strike drops on hotbar
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/ui/hotbar.ts
Labels: pr: bugfix

#3897 Fix hazard attack and damage rolls
  src/module/actor/hazard/sheet.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base.ts
  src/module/item/melee/index.ts
  static/templates/actors/hazard/sheet.html
Labels: pr: bugfix

#3898 Fix arguments passed to `InterfaceCanvasGroup#createScrollingText`
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/groups/interface.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
Labels: pr: bugfix, pr: foundry v10

#3899 Fix exclusion of loot actors from hearing detection
  src/module/canvas/perception/modes.ts
Labels: pr: bugfix

#3900 Make ChatMessage's strike getter semi-private in the meantime
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
Labels: pr: housekeeping

#3891 Add Dark Archive Web Supplement content
  packs/data/pathfinder-dark-archive.db/cocoon-of-lucid-potential.json
  packs/data/pathfinder-dark-archive.db/the-weaver-in-dreams.json
  static/licenses/OpenGameLicense.md
Labels: pr: data entry

#3853 Sort item traits in sheet header
  src/module/item/sheet/base.ts
  src/module/item/sheet/data-types.ts
  static/templates/items/item-sheet.html
Labels: pr: enhancement

#3901 Pass `mode` argument to get boolean from `WallsLayer#checkCollision`
  src/module/canvas/helpers.ts
  types/foundry/client/pixi/core/index.d.ts
  types/foundry/client/pixi/core/interaction/index.d.ts
  types/foundry/client/pixi/core/shapes/index.d.ts
  types/foundry/client/pixi/core/shapes/polygon-helpers.d.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/placeables-layer/walls-layer.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/index.d.ts
Labels: pr: bugfix

#3903 Fix compendium browser pre-filters for remaining feat types on PC sheet
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#3904 Release Notes 4.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#3907 Work around core bug in which getting active tokens creates new ones
  src/module/actor/base.ts
Labels: pr: bugfix

#3908 Fix drag/drop behavior in compendium search
  src/module/apps/ui/compendium-directory.ts
  types/foundry/client/collections/compendium-collection.d.ts
Labels: pr: bugfix

#3909 Release Notes 4.0.2
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#3910 Release 4.0.2
  CHANGELOG.md
  package-lock.json
  package.json
  src/module/actor/base.ts
  src/module/apps/ui/compendium-directory.ts
  system.json
  types/foundry/client/collections/compendium-collection.d.ts
Labels: pr: housekeeping

#3911 Correct perception and missing darkvision on spellskein
  packs/data/strength-of-thousands-bestiary.db/spellskein-consecrate.json
  packs/data/strength-of-thousands-bestiary.db/spellskein-control-weather.json
  packs/data/strength-of-thousands-bestiary.db/spellskein-heroes-feast.json
  packs/data/strength-of-thousands-bestiary.db/spellskein.json
Labels: source: adventure path, pr: data update

#3916 Update changelog URL to point to V10 release branch
  src/scripts/hooks/render-settings.ts
Labels: pr: bugfix

#3915 Fix darkness adjuster rendering on scene view
  src/module/apps/scene-darkness-adjuster.ts
  src/scripts/hooks/get-scene-control-buttons.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-scene-controls.ts
Labels: pr: bugfix

#3917 Release Notes 4.0.3
  CHANGELOG.md
  changes.txt
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#3912 Add type definitions of `TooltipManager`
  types/foundry/client/game.d.ts
  types/foundry/client/ui/index.d.ts
  types/foundry/client/ui/tooltip.d.ts
Labels: pr: foundry v10, pr: types update

#3919 Prevent default behavior in `StatusEffects.#setStatusValue`
  src/module/canvas/status-effects.ts
Labels: pr: bugfix

#3923 Migrate spellskeins
  packs/data/strength-of-thousands-bestiary.db/spellskein-consecrate.json
  packs/data/strength-of-thousands-bestiary.db/spellskein-control-weather.json
  packs/data/strength-of-thousands-bestiary.db/spellskein-heroes-feast.json
  packs/data/strength-of-thousands-bestiary.db/spellskein.json
Labels: pr: data update

#3922 Restore Fledgling Flight feat
  packs/data/feats.db/fledgling-flight.json
Labels: pr: data update

#3925 Make ChatMessage#item return the strike weapon if available
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
Labels: pr: enhancement

#3926 Remove damage dice from tanglefoot bags
  packs/data/equipment.db/tanglefoot-bag-greater.json
  packs/data/equipment.db/tanglefoot-bag-major.json
  packs/data/equipment.db/tanglefoot-bag-moderate.json
Labels: pr: data update

#3927 Do not show damage buttons for not-damaging weapons
  src/module/actor/character/index.ts
  src/module/item/weapon/index.ts
  src/module/system/check/strike/attack-roll.ts
  src/module/system/rolls.ts
  static/lang/en.json
  static/templates/actors/character/tabs/actions.html
  static/templates/chat/check/strike/attack-roll.html
Labels: pr: enhancement, ui/ux

#3928 Remove stored identified data on physical items
  src/module/item/armor/data.ts
  src/module/item/consumable/data.ts
  src/module/item/container/data.ts
  src/module/item/equipment/data.ts
  src/module/item/physical/data.ts
  src/module/item/weapon/data/types.ts
  src/module/migration/migrations/786-remove-identified-data.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration

#3930 Add Flat Modifier Form (dev only)
  src/module/item/sheet/base.ts
  src/module/item/sheet/rule-elements/flat-modifier.ts
  src/module/item/sheet/rule-elements/index.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/util.ts
  src/styles/item/_index.scss
  src/styles/item/_rules.scss
  src/styles/item/_sidebar.scss
  static/lang/re-en.json
  static/templates/items/rules/flat-modifier.html
Labels: pr: new feature, ui/ux

#3914 Add missing Dread runes
  packs/data/equipment.db/sisterstone-chunk.json
  packs/data/equipment.db/sisterstone-ingot.json
  src/module/item/physical/materials.ts
  src/module/item/physical/values.ts
  src/module/item/weapon/types.ts
  src/module/item/weapon/values.ts
  src/module/system/damage/calculation.ts
  src/scripts/config/index.ts
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data entry

#3936 Include journal entries in compendium search
  src/module/apps/ui/compendium-directory.ts
Labels: pr: enhancement

#3937 Fix html sent in "renderJournalTextPageSheet" hook
  src/scripts/hooks/render-journal-text-page-sheet.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#3938 Restore top/bottom anchor points to floaty text
  src/module/canvas/token/object.ts
Labels: ui/ux

#3935 Fix split of precious material strings in armor/weapon sheets
  src/module/item/physical/sheet.ts
  static/templates/items/armor-details.html
  static/templates/items/weapon-details.html
Labels: pr: bugfix

#3933 Migrate weapon and spell resolvables to use .system
  packs/scripts/run-migration.ts
  src/module/migration/migrations/787-resolvables-to-system.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: foundry v10

#3940 Fix construction of persistent damage icon path
  src/module/actor/base.ts
  src/module/canvas/status-effects.ts
Labels: pr: bugfix

#3752 Data Entry World fixes for September 3 2022
  packs/data/extinction-curse-bestiary.db/doblagub.json
  packs/data/feats.db/feverish-enzymes.json
  packs/data/feats.db/hellknight-dedication.json
  packs/data/feats.db/skill-mastery-rogue.json
  packs/data/feats.db/terrified-retreat.json
  packs/data/outlaws-of-alkenstar-bestiary.db/slick.json
  packs/data/pathfinder-bestiary-2.db/froghemoth.json
  packs/data/pathfinder-bestiary-2.db/giant-chameleon.json
  packs/data/pfs-season-3-bestiary.db/khisisi-5-6.json
  packs/data/pfs-season-3-bestiary.db/khisisi-7-8.json
  static/lang/re-en.json
Labels: pr: data update

#3944 Remove P elements and utilize `title` in several roll notes
  packs/data/equipment.db/boastful-hunter.json
  packs/data/equipment.db/little-love.json
  packs/data/equipment.db/spider-gun-greater.json
  packs/data/equipment.db/spider-gun-major.json
  packs/data/equipment.db/spider-gun.json
  packs/data/equipment.db/tanglefoot-bag-greater.json
  packs/data/equipment.db/tanglefoot-bag-lesser.json
  packs/data/equipment.db/tanglefoot-bag-major.json
  packs/data/equipment.db/tanglefoot-bag-moderate.json
  packs/data/feats.db/adhyabhau.json
  packs/data/feats.db/archaeologists-luck.json
  packs/data/feats.db/battle-cry.json
  packs/data/feats.db/bloodletting-fangs.json
  packs/data/feats.db/core-cannon.json
  packs/data/feats.db/relentless-disarm.json
  packs/data/monsters-of-myth-bestiary.db/spring-heeled-jack.json
  packs/data/pfs-season-3-bestiary.db/arisept-7-8.json
  packs/data/pfs-season-3-bestiary.db/arisept-9-10.json
  packs/data/spell-effects.db/spell-effect-aerial-form-wasp.json
  packs/data/spell-effects.db/spell-effect-flame-wisp.json
  packs/data/spell-effects.db/spell-effect-insect-form-centipede.json
  packs/data/spell-effects.db/spell-effect-insect-form-scorpion.json
  packs/data/spell-effects.db/spell-effect-insect-form-spider.json
  packs/data/spell-effects.db/spell-effect-monstrosity-form-phoenix.json
  packs/data/spell-effects.db/spell-effect-monstrosity-form-purple-worm.json
  static/lang/re-en.json
Labels: pr: data update

#3943 Fix multiple issues with roll notes
  src/module/actor/npc/index.ts
  src/module/notes.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/rolls.ts
  src/styles/_globals.scss
Labels: pr: bugfix

#3947 Migrate tanglefoot bags to have titled roll notes and no damage dice
  packs/data/agents-of-edgewatch-bestiary.db/bloody-berleth.json
  packs/data/agents-of-edgewatch-bestiary.db/diobel-sweeper-tough.json
  packs/data/equipment.db/tanglefoot-bag-lesser.json
  packs/data/extinction-curse-bestiary.db/thessekka.json
  packs/data/fall-of-plaguestone.db/vilree.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/yabin-the-just-level-13.json
  packs/data/npc-gallery.db/gang-leader.json
  packs/data/outlaws-of-alkenstar-bestiary.db/drela.json
  packs/data/outlaws-of-alkenstar-bestiary.db/hansin.json
  packs/data/outlaws-of-alkenstar-bestiary.db/shoma-lyzerius.json
  packs/data/pfs-season-3-bestiary.db/cole-farsen-gang-leader.json
  packs/data/strength-of-thousands-bestiary.db/fire-pot-ubanu.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/788-update-tanglefoot-bags.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: data update

#3951 Fix obscuring sender names on chat messages
  src/module/chat-message/document.ts
  src/scripts/ui/user-visibility.ts
Labels: pr: bugfix

#3952 Fix functionality of greater darkvision with no standard darkvision
  packs/data/equipment-effects.db/effect-goggles-of-night-greater.json
  packs/data/equipment-effects.db/effect-goggles-of-night-major.json
  packs/data/equipment-effects.db/effect-goggles-of-night.json
  src/module/actor/creature/index.ts
  src/module/rules/rule-element/sense.ts
Labels: pr: bugfix, pr: data update
