Repository foundryvtt/pf2e, pull requests merged in 2022-10, with the labels that each got.

#4283 Turn another `Array#forEach` into `for`-loop
  src/module/system/damage/weapon.ts
Labels: pr: refactor

#4286 Reset actor and scene data when encounter turn changes
  src/module/encounter/document.ts
Labels: pr: enhancement

#4285 List correct bonus value in Staff of Healing (True)
  packs/data/equipment.db/staff-of-healing-true.json
Labels: pr: data update

#4284 Add feats for the Psychic Duelist Dedication
  packs/data/feats.db/duel-spell-advantage.json
  packs/data/feats.db/instigate-psychic-duel.json
  packs/data/feats.db/psychic-duelist-dedication.json
  packs/data/feats.db/supreme-psychic-center.json
Labels: pr: data entry, source: rulebooks

#4290 Add support for RE-based land speeds
  src/module/actor/creature/data.ts
  src/module/actor/creature/index.ts
  src/module/rules/rule-element/base-speed.ts
  src/module/rules/synthetics.ts
Labels: pr: enhancement

#4214 Add missing item from Strength of Thousands 4
  packs/data/equipment.db/deathless-light.json
Labels: source: adventure path, pr: data entry

#4292 Restore NPC skill variants
  src/module/actor/npc/index.ts
Labels: pr: bugfix

#4293 Allow for crit-only splash damage
  src/module/actor/modifiers.ts
Labels: pr: bugfix

#4294 Fix validation of bracketed damage dice overrides
  src/module/rules/rule-element/damage-dice.ts
Labels: pr: bugfix

#4295 Add type definition of "targetToken" hook
  types/foundry/client/core/hooks.d.ts
Labels: pr: types update

#4299 Throw error if type of added custom modifier is invalid
  src/module/system/check-modifiers-dialog.ts
Labels: pr: refactor

#4297 Update licensing and add missing trait
  src/scripts/config/index.ts
  src/scripts/config/traits.ts
  static/lang/en.json
  static/licenses/OpenGameLicense.md
Labels: pr: data entry, source: pathfinder society, source: adventure

#4301 Fix PWoL variant not honoring untrained proficiency penalties
  src/module/actor/character/index.ts
  src/module/actor/creature/index.ts
  src/module/actor/modifiers.ts
Labels: pr: bugfix, pr: refactor

#4264 Convert Earn Income to skill statistic and fix check dialog title
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/character/index.ts
  src/module/actor/creature/index.ts
  src/module/actor/modifiers.ts
  src/module/system/statistic/data.ts
  src/module/system/statistic/index.ts
  src/scripts/macros/earn-income/calculate.ts
  src/scripts/macros/earn-income/helpers.ts
  src/scripts/macros/earn-income/macro.ts
  tests/module/earn-income.test.ts
Labels: pr: refactor

#4303 Fix setting mirrorX/mirrorY in token config
  src/module/scene/token-document/sheet.ts
  types/foundry/client/application/form-application/token-config.d.ts
Labels: pr: bugfix

#4302 Add user setting to disable monochrome darkvision
  src/module/scene/token-document/document.ts
  src/module/user/document.ts
  static/lang/en.json
  static/templates/user/sheet.html
Labels: pr: enhancement

#4306 Fix aberrant behavior in check dialog for `hideIfDisabled` modifiers
  src/module/system/check-modifiers-dialog.ts
  src/styles/ui/_dialog.scss
  static/templates/chat/check-modifiers-dialog.html
Labels: pr: bugfix

#4304 Release Notes 4.2.0
  CHANGELOG.md
Labels: pr: housekeeping

#4308 Bump version to 4.2.0
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4309 Move pair of lines to correct section in changelog
  CHANGELOG.md
Labels: pr: housekeeping

#4313 Fix dropping conditions on actors
  src/module/actor/base.ts
Labels: pr: bugfix

#4315 Restore raw note functionality to CheckPF2e
  src/module/notes.ts
  src/module/system/rolls.ts
Labels: pr: bugfix

#4317 Fix predicate of RE on Orc Weapon Carnage
  packs/data/feats.db/orc-weapon-carnage.json
  src/module/migration/migrations/759-crit-spec-re.ts
Labels: pr: bugfix, pr: data update

#4311 Default toggle in Unleash Psyche effect to true
  packs/data/feat-effects.db/effect-unleash-psyche.json
Labels: pr: data update

#4318 Catch one more unmigrated predicate property
  packs/data/feats.db/game-hunter-dedication.json
  packs/data/feats.db/triple-shot.json
  src/module/migration/migrations/793-make-predicates-arrays.ts
Labels: pr: bugfix, pr: data update

#4320 Truncate `BaseSpeed` values in case of being percentage of land speed
  src/module/rules/rule-element/base-speed.ts
Labels: pr: bugfix

#4319 Release Notes 4.2.1
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4321 Update some pixi-related Foundry types
  types/foundry/client/pixi/layers/controls/ruler.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
Labels: pr: types update

#4322 Use fa-stack for heal button, enlarge labels slightly
  src/styles/ui/sidebar/chat/_damage.scss
  static/templates/chat/damage/buttons.html
Labels: ui/ux

#4323 Support path-based choice sets that are arrays
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: enhancement

#4327 Fix prereq format in psychic duelist dedication
  packs/data/feats.db/psychic-duelist-dedication.json
Labels: pr: data update

#4324 Have wild shape effect grant battle form effect
  packs/data/feats.db/dragon-shape.json
  packs/data/feats.db/elemental-shape.json
  packs/data/feats.db/ferocious-shape.json
  packs/data/feats.db/insect-shape.json
  packs/data/feats.db/monstrosity-shape.json
  packs/data/feats.db/plant-shape.json
  packs/data/feats.db/soaring-shape.json
  packs/data/feats.db/wild-shape.json
  packs/data/spell-effects.db/spell-effect-wild-shape.json
  static/lang/re-en.json
Labels: pr: data update

#4333 Call ActorPF2e#increaseCondition from token HUD
  src/module/canvas/status-effects.ts
Labels: pr: bugfix

#4331 Have granted effects match levels of respective granting effects
  src/module/rules/rule-element/grant-item/base.ts
Labels: pr: enhancement

#4337 Fix inline check in Psi Burst
  packs/data/feats.db/psi-burst.json
Labels: pr: data update

#4338 Fix AE-likes adding to wild shape choice set
  packs/data/feats.db/dragon-shape.json
  packs/data/feats.db/elemental-shape.json
  packs/data/feats.db/ferocious-shape.json
  packs/data/feats.db/insect-shape.json
  packs/data/feats.db/monstrosity-shape.json
  packs/data/feats.db/plant-shape.json
  packs/data/feats.db/soaring-shape.json
  packs/data/spell-effects.db/spell-effect-wild-shape.json
Labels: pr: data update

#4339 Add migration to update druid shape feat REs
  src/module/migration/migrations/794-add-wild-shape-choices.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration

#4341 Fix start of turn status message
  src/module/canvas/status-effects.ts
Labels: pr: bugfix

#4342 Fix display of drag gap and mystified name (gm view) in encounter view popouts
  src/styles/ui/_combat.scss
Labels: pr: bugfix, ui/ux

#4340 Store NPC identification data in details
  src/module/actor/npc/data.ts
  src/module/actor/npc/index.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/popups/recall-knowledge-popup.ts
  src/module/recall-knowledge.ts
  tests/module/recall-knowledge.test.ts
Labels: pr: enhancement

#4344 Add sanity check to `sluggify` to ensure argument passed is a string
  src/util/misc.ts
Labels: pr: enhancement

#4348 Set range of Spined Azerketi's unarmed attack
  packs/data/heritages.db/spined-azarketi.json
Labels: pr: data update

#4347 Fix display of level in actor directory for level-zero actors
  static/templates/sidebar/actor-document-partial.html
Labels: pr: bugfix

#4346 Add GM Vision keybinding and setting
  src/global.d.ts
  src/module/system/settings/index.ts
  src/scripts/config/index.ts
  src/scripts/hooks/ready.ts
  src/scripts/register-keybindings.ts
  static/lang/en.json
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/common/utils/color.d.ts
Labels: pr: new feature

#4335 Add Hispanic Heritage Month Paizo blog items
  packs/data/equipment.db/guiding-cajon-drum.json
  packs/data/equipment.db/memory-guitar.json
  packs/data/equipment.db/tornado-trompo.json
Labels: pr: data entry, source: blog

#4353 Fix styling of popped out compendium sidebar
  src/styles/ui/sidebar/_compendium-directory.scss
Labels: pr: bugfix

#4355 Restore click-event listeners on lore items
  src/module/item/sheet/base.ts
Labels: pr: bugfix

#4354 Add Wild Hunt creature trait
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data entry

#4351 Release Notes 4.2.2
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4356 Link Treat Wounds macro in Treat Wounds action
  packs/data/actions.db/treat-wounds.json
Labels: pr: data update

#4357 Fix styling of flat modifier form in certain cases
  src/styles/item/_rules.scss
Labels: pr: bugfix, ui/ux

#4370 Minor corrections of Iconic sheets
  packs/data/iconics.db/droogami-level-1.json
  packs/data/iconics.db/droogami-level-5.json
  packs/data/iconics.db/feiya-level-5.json
  packs/data/iconics.db/harsk-level-5.json
  packs/data/iconics.db/jirelle-level-5.json
  packs/data/iconics.db/korakai-level-1.json
  packs/data/iconics.db/korakai-level-5.json
  packs/data/iconics.db/lem-level-5.json
  packs/data/iconics.db/lini-level-1.json
  packs/data/iconics.db/lini-level-5.json
  packs/data/iconics.db/quinn-level-1.json
  packs/data/iconics.db/quinn-level-5.json
  packs/data/iconics.db/sajan-level-1.json
  packs/data/iconics.db/sajan-level-5.json
  packs/data/iconics.db/seoni-level-1.json
  packs/data/iconics.db/seoni-level-5.json
Labels: pr: data update

#4369 Return false early when testing detection of GM-hidden placeable objects
  src/module/canvas/perception/modes.ts
  types/foundry/client/documents/mixins/canvas-document-mixin.d.ts
  types/foundry/client/pixi/layers/effects/visibility.d.ts
Labels: pr: enhancement

#4364 Prevent browser-defined default actions for CTRL-G keypress
  src/scripts/register-keybindings.ts
  types/foundry/common/types.d.ts
Labels: pr: bugfix

#4358 Only show FlatModifier form damage row for damage selectors, remove value range fields
  src/module/item/sheet/rule-elements/base.ts
  src/module/item/sheet/rule-elements/flat-modifier.ts
  static/templates/items/rules/flat-modifier.html
Labels: ui/ux

#4372 Add Damaj's Gloves
  packs/data/equipment.db/damajs-gloves.json
  src/scripts/config/index.ts
  src/scripts/config/traits.ts
  static/lang/en.json
  static/licenses/OpenGameLicense.md
Labels: pr: data entry, source: blog

#4373 Release Notes 4.2.3
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4376 Mark Foundry 10.287 as verified in system.json
  system.json
Labels: pr: housekeeping

#4374 Add critical field to FlatModifier form
  src/module/item/sheet/rule-elements/flat-modifier.ts
  src/styles/item/_rules.scss
  static/lang/re-en.json
  static/templates/items/rules/flat-modifier.html
Labels: pr: enhancement, ui/ux

#4375 Re-render actor directory when world actor's level is changed
  src/module/apps/ui/actor-directory.ts
  types/foundry/client/application/sidebar/sidebar-tab/sidebar-directory/base.d.ts
Labels: pr: bugfix

#4377 Send warning thrown by sluggify sanity check to console
  src/util/misc.ts
Labels: pr: enhancement

#4379 Fix double-granting world items from ABC items
  src/module/item/abc/manager.ts
  static/lang/en.json
  static/templates/items/class-details.html
Labels: pr: bugfix

#4380 Fix strike macros
  src/module/chat-message/document.ts
Labels: pr: bugfix

#4383 Fix Mountain Quake requirement
  packs/data/feats.db/mountain-quake.json
Labels: pr: data update

#4378 Prevent error thrown on concurrent token effects drawing
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#4381 Change initiative fa-fist-raised icon to fa-swords
  src/module/apps/ui/chat-log.ts
  src/module/chat-message/listeners/set-as-initiative.ts
  src/util/misc.ts
  static/templates/actors/npc/partials/sidebar.html
Labels: ui/ux

#4386 Add lighting control tool to toggle GM vision
  src/module/apps/scene-darkness-adjuster.ts
  src/scripts/config/index.ts
  src/scripts/hooks/get-scene-control-buttons.ts
  src/scripts/register-keybindings.ts
  types/foundry/client/apps/sidebar/apps/keybindings-config.d.ts
  types/foundry/client/apps/sidebar/index.d.ts
  types/foundry/client/apps/sidebar/package-configuration.d.ts
  types/foundry/index.d.ts
Labels: pr: enhancement, ui/ux

#4387 Don't show GM vision toggle for non-GMs
  src/scripts/hooks/get-scene-control-buttons.ts
Labels: pr: bugfix

#4368 Fix usage of Crown of the Companion
  packs/data/equipment.db/crown-of-the-companion.json
Labels: pr: data update

#4389 Fix distortion of actor portraits in compendium search results
  src/styles/ui/sidebar/_compendium-directory.scss
Labels: pr: bugfix, ui/ux

#4390 Release Notes 4.2.4
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4392 Organize imports in extract.ts
  packs/scripts/extract.ts
Labels: pr: housekeeping

#4393 Use generic `Macro` parameter in `Hotbar` type definition
  types/foundry/client/application/hotbar.d.ts
  types/foundry/client/documents/chat-message.d.ts
Labels: pr: types update

#4394 Refrain from showing floaty text if token is not visible
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
Labels: pr: enhancement

#4396 Fix position of delete button on heritage's prerequisite ancestry
  src/styles/item/_heritage-sheet.scss
  static/lang/en.json
  static/templates/items/heritage-sidebar.html
Labels: pr: bugfix, ui/ux

#4397 Fix premature filtering of damage modifiers
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#4400 Re-render actor directory when NPC adjustments change
  src/module/apps/ui/actor-directory.ts
Labels: pr: bugfix

#4399 Fix TokenImage RE for unlinked tokens
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#4391 Allow parameters to be shadowed in script macros' eval scopes
  src/module/macro.ts
Labels: pr: bugfix

#4401 Add type definition for Token#_onUpdateAppearance
  types/foundry/client/pixi/placeable-object/token.d.ts
Labels: pr: types update

#4402 Remove remaining uses of deprecated `ChatMessage#roll`
  src/module/apps/ui/chat-log.ts
  src/module/chat-message/crit-fumble-cards.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/damage-buttons.ts
  src/module/chat-message/listeners/set-as-initiative.ts
  src/module/system/action-macros/crafting/repair.ts
  src/module/system/rolls.ts
Labels: pr: foundry v10

#4405 Fix predication for spell/class/save dc modifiers
  src/module/system/statistic/index.ts
Labels: pr: bugfix

#4403 Add support for multiple IWR types per RE
  src/module/rules/rule-element/iwr/base.ts
  src/module/rules/rule-element/iwr/immunity.ts
  src/module/rules/rule-element/iwr/resistance.ts
  src/module/rules/rule-element/iwr/weakness.ts
Labels: pr: enhancement

#4409 Refactor damage roll chat message content rendering
  src/module/system/damage/roll-dialog.ts
  src/module/system/damage/types.ts
  static/templates/chat/damage/damage-card-content.html
Labels: pr: refactor

#4410 Fix style of damage cards with triple-damage buttons
  src/styles/ui/sidebar/chat/_damage.scss
  static/templates/chat/damage/buttons.html
Labels: pr: bugfix, ui/ux

#4415 Restore ability-based domains for spellcasting
  src/module/actor/character/index.ts
Labels: pr: bugfix

#4407 Fix flat modifier editor adding critical: false to newly added rules
  src/module/item/sheet/rule-elements/flat-modifier.ts
Labels: pr: bugfix

#4417 Restore re-rendering token HUD after mouse interactions
  src/module/canvas/status-effects.ts
Labels: pr: bugfix

#4418 Move `StatisticModifier#applyAdjustments` to helper function
  src/module/actor/modifiers.ts
Labels: pr: refactor

#4419 Fix modifier adjustments for top level selectors
  src/module/actor/modifiers.ts
  src/module/system/statistic/index.ts
Labels: pr: bugfix

#4420 Add toggle for Ostovite's bone chariot
  packs/data/pathfinder-bestiary-3.db/ostovite.json
Labels: pr: data update

#4404 Release Notes 4.2.5
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4421 Recheck auras when token sizes change
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#4429 Fix aura colors getting inverted
  src/module/canvas/token/aura/renderer.ts
Labels: pr: bugfix

#4432 Fix double adjustments on statistic rolls
  src/module/system/statistic/index.ts
Labels: pr: bugfix

#4437 Accommodate macros ending with single-line comments
  src/module/macro.ts
Labels: pr: bugfix

#4438 Simplify aura-rendering workflow
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/object.ts
Labels: pr: refactor

#4436 Remove duplicate/misspelled psychopomp mask
  packs/data/equipment.db/psychopomp-mask.json
  packs/data/equipment.db/pyschopomp-mask.json
Labels: pr: data update

#4424 Fix rule elements on Elemental Assault effect
  packs/data/feat-effects.db/effect-elemental-assault.json
Labels: pr: data update

#4442 Restore setting self:condition roll options
  src/module/item/condition/document.ts
Labels: pr: bugfix

#4441 Sort tokens by z-index in dropCanvasData hook
  src/scripts/hooks/drop-canvas-data.ts
Labels: pr: bugfix

#4446 Refrain from highlighting measured templates invisible to players
  src/module/canvas/measured-template.ts
  types/foundry/client/pixi/placeable-object/measured-template.d.ts
Labels: pr: bugfix

#4444 Move "Perception for Selected Tokens" macro to system codebase
  packs/data/macros.db/perception-for-selected-tokens.json
  src/global.d.ts
  src/scripts/macros/index.ts
  src/scripts/macros/perception-for-selected-tokens.ts
  src/scripts/macros/travel/index.ts
  src/scripts/set-game-pf2e.ts
  static/macros/perception-for-selected.js
  static/macros/xp.js
Labels: pr: refactor

#4440 Fix bidirectional diff of aura changes
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#4431 Create Statistic check/dc in constructor and full-load check/dc modifiers
  src/module/system/statistic/index.ts
Labels: pr: bugfix, pr: refactor

#4448 Set actor synthetics object in `ActorPF2e#_initialize`
  src/module/actor/base.ts
Labels: pr: refactor

#4449 Fix adjusted npc spell dc style
  src/styles/actor/npc/_spells.scss
Labels: pr: bugfix, ui/ux

#4450 Release Notes 4.2.6
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#4452 Make correction in changelog
  CHANGELOG.md
Labels: pr: housekeeping

#4451 Update NPM dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#4453 Update typescript to 4.8.4
  package-lock.json
  package.json
Labels: pr: housekeeping

#4455 Correct aura from 5 to 10 feet for elemental avalanche
  packs/data/pathfinder-bestiary.db/elemental-avalanche.json
Labels: pr: data update, source: rulebooks

#4458 Standardize predicates for virtuosic performer
  packs/data/feats.db/virtuosic-performer-acting.json
  packs/data/feats.db/virtuosic-performer-comedy.json
  packs/data/feats.db/virtuosic-performer-dance.json
  packs/data/feats.db/virtuosic-performer-keyboards.json
  packs/data/feats.db/virtuosic-performer-oratory.json
  packs/data/feats.db/virtuosic-performer-percussion.json
  packs/data/feats.db/virtuosic-performer-singing.json
  packs/data/feats.db/virtuosic-performer-strings.json
  packs/data/feats.db/virtuosic-performer-winds.json
Labels: pr: data update, source: rulebooks

#4461 Use item type unions for world and embedded collections
  src/global.d.ts
  src/module/actor/base.ts
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/module/actor/inventory/index.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/abc/index.ts
  src/module/item/abc/manager.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/action/index.ts
  src/module/item/ancestry/index.ts
  src/module/item/armor/document.ts
  src/module/item/background/index.ts
  src/module/item/base.ts
  src/module/item/book/document.ts
  src/module/item/class/index.ts
  src/module/item/condition/document.ts
  src/module/item/consumable/index.ts
  src/module/item/container/index.ts
  src/module/item/data/index.ts
  src/module/item/deity/document.ts
  src/module/item/effect/document.ts
  src/module/item/equipment/index.ts
  src/module/item/feat/index.ts
  src/module/item/heritage/document.ts
  src/module/item/index.ts
  src/module/item/kit/index.ts
  src/module/item/lore/index.ts
  src/module/item/melee/data.ts
  src/module/item/melee/index.ts
  src/module/item/physical/document.ts
  src/module/item/physical/index.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/data/sheet.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/treasure/index.ts
  src/module/item/weapon/document.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/rules/rule-element/grant-item/helpers.ts
  src/module/system/conditions/manager.ts
  src/module/system/damage/roll-dialog.ts
  src/module/system/damage/weapon.ts
  src/module/system/rolls.ts
  src/module/system/statistic/index.ts
  types/foundry/client/documents/item.d.ts
  types/foundry/common/abstract/document.d.ts
Labels: pr: refactor

#4459 Localize treat wounds macro
  src/scripts/macros/treat-wounds.ts
  static/lang/en.json
Labels: pr: enhancement

#4470 Add psychic multiclass as a valid selection for Eldritch Trickster Rogue
  packs/data/classfeatures.db/eldritch-trickster.json
Labels: pr: data update, source: rulebooks

#4474 Remove remaining `ItemPF2e` subclasses to document.ts files
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/trick-magic-item-popup.ts
  src/module/item/abc/document.ts
  src/module/item/abc/index.ts
  src/module/item/abc/manager.ts
  src/module/item/action/document.ts
  src/module/item/action/index.ts
  src/module/item/ancestry/document.ts
  src/module/item/ancestry/index.ts
  src/module/item/ancestry/sheet.ts
  src/module/item/background/document.ts
  src/module/item/background/index.ts
  src/module/item/base.ts
  src/module/item/book/index.ts
  src/module/item/class/document.ts
  src/module/item/class/index.ts
  src/module/item/consumable/document.ts
  src/module/item/consumable/index.ts
  src/module/item/container/document.ts
  src/module/item/container/index.ts
  src/module/item/equipment/document.ts
  src/module/item/equipment/index.ts
  src/module/item/feat/document.ts
  src/module/item/feat/index.ts
  src/module/item/index.ts
  src/module/item/kit/document.ts
  src/module/item/kit/index.ts
  src/module/item/melee/document.ts
  src/module/item/melee/index.ts
  src/module/item/sheet/index.ts
  src/module/item/treasure/document.ts
  src/module/item/treasure/index.ts
  src/scripts/register-sheets.ts
Labels: pr: housekeeping

#4468 Update sly striker rule elements to function in V10
  packs/data/feats.db/sly-striker.json
Labels: pr: data update, source: rulebooks

#4384 Add roll mode param to cast() function
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/data/types.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/spellcasting-entry/trick.ts
Labels: pr: enhancement, pr: housekeeping

#4487 Add `isNand` method to predicate statement validator
  src/module/system/predication.ts
Labels: pr: bugfix

#4489 Add placeholder to paizo-style trait inputs
  src/styles/_tags.scss
  src/styles/actor/hazard/_header.scss
  static/lang/en.json
  static/templates/actors/hazard/partials/header.html
  static/templates/actors/npc/partials/header.html
  static/templates/items/item-sheet.html
Labels: pr: enhancement, ui/ux

#4490 Allow `number`s and `null` to pass through `resolveInjectedProperties`
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/grant-item/base.ts
Labels: pr: enhancement

#4481 Avoid unnecessary redraw on unlinked token updates
  src/module/canvas/status-effects.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#4484 Re-render combat in `ActorPF2e#_onEmbeddedDocumentChange`
  src/module/actor/base.ts
Labels: pr: bugfix

#4493 Correct Rebounding Barrier Requirement to Trigger
  packs/data/spells.db/rebounding-barrier.json
Labels: pr: data update

#4496 Fix localization keys on Armor Innovation feature
  packs/data/classfeatures.db/armor-innovation.json
Labels: pr: data update

#4494 Record ID of granted item in GrantItem source
  src/module/rules/rule-element/grant-item/base.ts
  static/lang/re-en.json
Labels: pr: enhancement

#4498 Removed outdated duplicate `README` file
  static/README.md
Labels: pr: housekeeping

#4488 Disable tagify style sheets from modules
  src/scripts/hooks/init.ts
Labels: pr: enhancement

#4499 Move @actor/character/data/values to @actor/character/values
  src/module/actor/character/data/sheet.ts
  src/module/actor/character/index.ts
  src/module/actor/character/values.ts
Labels: pr: housekeeping

#4497 Use flashier icon for lantern implement
  static/icons/features/classes/lantern.webp
Labels: pr: data update

#4506 Move flat-footed toggle to relevant features, add setting to show
  packs/data/classfeatures.db/laughing-shadow.json
  packs/data/classfeatures.db/sneak-attack.json
  packs/data/feats.db/undead-slayer.json
  src/global.d.ts
  src/module/actor/creature/index.ts
  src/module/rules/rule-element/roll-option.ts
  src/module/system/settings/index.ts
  static/lang/en.json
  static/lang/re-en.json
  static/templates/actors/character/tabs/actions.html
Labels: pr: enhancement

#4507 Move damage type icons to values
  src/module/system/damage/roll-dialog.ts
  src/module/system/damage/values.ts
Labels: pr: housekeeping

#4505 Default requiresInvestment to value of requiresEquipped where applicable
  src/module/rules/rule-element/base.ts
Labels: pr: enhancement

#4510 Remove special handling for flat footed toggle
  src/module/actor/sheet/base.ts
  src/module/rules/rule-element/roll-option.ts
Labels: pr: bugfix

#4508 Put top level roll options at the top in the inspector
  src/module/chat-message/chat-roll-details.ts
Labels: pr: enhancement

#4511 Run recent migrations on compendium JSON
  packs/data/classfeatures.db/precise-strike.json
  packs/data/feats.db/finishing-precision.json
  packs/data/iconics.db/droogami-level-1.json
  packs/data/iconics.db/droogami-level-5.json
  packs/data/iconics.db/feiya-level-5.json
  packs/data/iconics.db/harsk-level-5.json
  packs/data/iconics.db/jirelle-level-1.json
  packs/data/iconics.db/jirelle-level-5.json
  packs/data/iconics.db/korakai-level-1.json
  packs/data/iconics.db/korakai-level-5.json
  packs/data/iconics.db/kyra-level-1.json
  packs/data/iconics.db/kyra-level-3.json
  packs/data/iconics.db/kyra-level-5.json
  packs/data/iconics.db/lem-level-5.json
  packs/data/iconics.db/lini-level-1.json
  packs/data/iconics.db/lini-level-5.json
  packs/data/iconics.db/merisiel-level-1.json
  packs/data/iconics.db/merisiel-level-3.json
  packs/data/iconics.db/merisiel-level-5.json
  packs/data/iconics.db/quinn-level-1.json
  packs/data/iconics.db/quinn-level-5.json
  packs/data/iconics.db/sajan-level-1.json
  packs/data/iconics.db/sajan-level-5.json
  packs/data/iconics.db/seoni-level-1.json
  packs/data/iconics.db/seoni-level-5.json
  packs/data/iconics.db/valeros-level-1.json
  packs/data/iconics.db/valeros-level-3.json
  packs/data/iconics.db/valeros-level-5.json
  packs/data/paizo-pregens.db/bottlespeaker.json
  packs/data/paizo-pregens.db/eteleon.json
  packs/data/paizo-pregens.db/grimmnir.json
  packs/data/paizo-pregens.db/izni.json
  packs/data/paizo-pregens.db/kellsti.json
  packs/data/paizo-pregens.db/kyra-beginner-box.json
  packs/data/paizo-pregens.db/lavanna-saltspray.json
  packs/data/paizo-pregens.db/melvok.json
  packs/data/paizo-pregens.db/savshin-starwatcher.json
  packs/data/paizo-pregens.db/ufi.json
  packs/data/paizo-pregens.db/zathri.json
  static/template.json
Labels: pr: data update

#4513 Set tag roll options in `PhysicalItemPF2e`
  src/module/item/physical/document.ts
  src/module/item/weapon/document.ts
Labels: pr: refactor

#4514 Actually fix toggles for totm
  src/module/rules/rule-element/roll-option.ts
Labels: pr: bugfix

#4515 Introduce damage roll class, delegate roll drilldown rendering
  src/module/actor/character/crafting/helpers.ts
  src/module/chat-message/data.ts
  src/module/chat-message/document.ts
  src/module/system/check/roll.ts
  src/module/system/check/strike/attack-roll.ts
  src/module/system/damage/roll-dialog.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/types.ts
  src/module/system/rolls.ts
  src/scripts/hooks/init.ts
  static/templates/chat/damage/damage-card-content.html
  static/templates/chat/damage/damage-card-details.html
  types/foundry/client/roll.d.ts
Labels: pr: refactor

#4517 Add a space to special statement in medic dedication
  packs/data/feats.db/medic-dedication.json
Labels: pr: data update, source: rulebooks

#4485 Automate Life Oracle curse effects
  packs/data/feat-effects.db/effect-life-curse.json
  static/lang/re-en.json
Labels: pr: data update

#4525 Add updated SVGs to ignore metadata bug
  static/assets/icons/heavy-bullets.svg
  static/assets/icons/pathfinder-orn.svg
  static/assets/icons/pfs-white.svg
  static/assets/icons/pfs.svg
  static/assets/icons/shield-broken.svg
  static/assets/icons/shield.svg
  static/assets/icons/toolbar-icon.svg
Labels: pr: bugfix

#4526 Change Eternal Wings RE from speed.total to speed.base
  packs/data/feats.db/eternal-wings-aasimar.json
  packs/data/feats.db/eternal-wings-sylph.json
Labels: pr: data update, source: rulebooks

#4535 Include domains in character/npc strike roll inspector
  src/module/actor/character/index.ts
  src/module/actor/npc/index.ts
  src/module/chat-message/chat-roll-details.ts
  static/templates/chat/chat-roll-details.html
Labels: pr: enhancement

#4533 Add effect for Calculate Threats action
  packs/data/actions.db/calculate-threats.json
  packs/data/feat-effects.db/effect-calculate-threats.json
Labels: pr: data entry

#4536 Add inspector support to strike damage
  src/module/actor/character/index.ts
  src/module/actor/npc/index.ts
  src/module/chat-message/chat-roll-details.ts
  src/module/chat-message/data.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/roll-dialog.ts
  src/module/system/rolls.ts
  src/styles/ui/sidebar/chat/_chat-roll-details.scss
  static/templates/chat/chat-roll-details.html
Labels: pr: enhancement

#4539 Fix generation of NPC attacks from weapons with constant damage
  src/module/item/weapon/document.ts
Labels: pr: bugfix

#4540 Fix predicates on two new items
  packs/data/equipment-effects.db/effect-ring-of-torag.json
  packs/data/equipment-effects.db/effect-tallowheart-mass.json
Labels: pr: data update

#4541 Convert `itemGrants` arrays to objects
  packs/data/iconics.db/amiri-level-5.json
  packs/data/iconics.db/droogami-level-1.json
  packs/scripts/run-migration.ts
  src/module/actor/character/feats.ts
  src/module/item/background/document.ts
  src/module/item/base.ts
  src/module/item/condition/document.ts
  src/module/item/data/base.ts
  src/module/migration/migrations/755-grant-ids-to-data.ts
  src/module/migration/migrations/796-item-grants-to-objects.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/rules/rule-element/grant-item/base.ts
  src/module/rules/rule-element/grant-item/helpers.ts
Labels: pr: data migration, pr: refactor
