Repository foundryvtt/pf2e, pull requests merged in 2022-08, with the labels that each got.

#3288 Add slugs to REs on Advanced Undead Benefits and Grave Strength
  packs/data/ancestryfeatures.db/advanced-undead-benefits.json
  packs/data/feats.db/grave-strength.json
Labels: pr: data update

#3289 Add Community Macros module to unmaintained list
  src/scripts/hooks/ready.ts
Labels: pr: enhancement

#3291 Has `CreaturePF2e#isDead` handle cases of being unconscious at zero HP
  src/module/actor/creature/index.ts
Labels: pr: bugfix

#3292 Only highlight aura grid squares when combat is active and started
  src/module/canvas/token/aura/renderer.ts
Labels: pr: enhancement

#3293 Fix rule elements on several effects
  packs/data/bestiary-effects.db/effect-motivating-assault.json
  packs/data/bestiary-effects.db/effect-sylvan-wine.json
  packs/data/equipment-effects.db/effect-sylvan-wine.json
  packs/data/equipment.db/large-bore-modifications.json
  packs/data/feat-effects.db/effect-spin-tale.json
Labels: pr: data update

#3294 Remove Sylvan Wine from the Equipment Compendia
  packs/data/equipment-effects.db/effect-sylvan-wine.json
  packs/data/equipment.db/sylvan-wineskin.json
  packs/data/extinction-curse-bestiary.db/adrivallo.json
Labels: pr: data update

#3290 Release Notes 3.13.5
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#3296 Retire previous hazard sheet
  src/module/actor/hazard/sheet-new.ts
  src/module/actor/hazard/sheet.ts
  src/scripts/register-sheets.ts
  src/styles/actor/hazard/_index.scss
  src/styles/actor/hazard/_legacy.scss
  static/templates/actors/hazard/sheet-new.html
  static/templates/actors/hazard/sheet-no-edit.html
  static/templates/actors/hazard/sheet.html
Labels: pr: enhancement, pr: housekeeping

#3095 Distinguish between cast and slot level in spell chat data
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/chat-message/data.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base.ts
  src/module/item/spell/index.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/spellcasting-entry/trick.ts
  src/scripts/system/dragstart-handler.ts
  static/templates/actors/spellcasting-spell-list.html
  static/templates/chat/spell-card.html
Labels: pr: refactor

#3221 Train skills from class during data preparation
  src/module/item/class/index.ts
Labels: pr: enhancement

#3150 Adjust modifiers instead of adding new ones for elite/weak adjustments
  src/module/actor/base.ts
  src/module/actor/creature/index.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/index.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/types.ts
  src/module/item/base.ts
  src/module/item/melee/index.ts
  src/module/item/spell/index.ts
  src/scripts/dice.ts
  src/styles/actor/npc/_spells.scss
  static/templates/actors/npc/tabs/spells.html
Labels: pr: refactor

#3300 Convert remaining items to use `Item#system`
  src/module/item/action/index.ts
  src/module/item/base.ts
  src/module/item/condition/index.ts
  src/module/item/effect/index.ts
  src/module/item/kit/index.ts
  src/module/item/kit/sheet.ts
  src/module/item/melee/index.ts
  src/module/item/sheet/base.ts
Labels: pr: foundry v10

#3299 Convert PC-building items to use `Item#system`
  src/module/item/abc/index.ts
  src/module/item/abc/sheet.ts
  src/module/item/ancestry/index.ts
  src/module/item/background/index.ts
  src/module/item/class/index.ts
  src/module/item/deity/document.ts
  src/module/item/deity/sheet.ts
  src/module/item/feat/data.ts
  src/module/item/feat/index.ts
  src/module/item/feat/sheet.ts
  src/module/item/heritage/document.ts
  src/module/item/heritage/sheet.ts
Labels: pr: foundry v10

#3298 Convert spell and spellcastingEntry items to use `Item#system`
  src/module/item/spell/index.ts
  src/module/item/spell/sheet.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/spellcasting-entry/sheet.ts
  src/module/item/spellcasting-entry/trick.ts
Labels: pr: foundry v10

#3297 Convert physical items to use `Item#system`
  src/module/item/consumable/index.ts
  src/module/item/container/index.ts
  src/module/item/equipment/index.ts
  src/module/item/physical/index.ts
  src/module/item/physical/sheet.ts
  src/module/item/treasure/index.ts
  src/module/item/weapon/index.ts
  src/module/item/weapon/sheet.ts
Labels: pr: foundry v10

#3302 Convert files in @scripts to use `Actor/Item#system`
  src/scripts/actor/status-effects.ts
  src/scripts/macros/encouraging-words.ts
  src/scripts/macros/hotbar.ts
  src/scripts/macros/rest-for-the-night.ts
  src/scripts/macros/steel-your-resolve.ts
  src/scripts/macros/treat-wounds.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: foundry v10

#3301 Convert files in @actor to use `Actor#system`
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/actor/character/feats.ts
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/module/actor/character/strike-weapon-traits.ts
  src/module/actor/creature/index.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/index.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/inventory/bulk.ts
  src/module/actor/inventory/index.ts
  src/module/actor/loot/index.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/npc/index.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/skills-editor.ts
  src/module/actor/npc/strike-attack-traits.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/actor/sheet/trick-magic-item-popup.ts
  src/module/actor/vehicle/index.ts
Labels: pr: foundry v10

#3303 Use tagify for editing hazard traits
  src/module/actor/hazard/index.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/sheet/base.ts
  src/styles/actor/hazard/_index.scss
  src/styles/ui/_tags.scss
  static/templates/actors/hazard/partials/header.html
  static/templates/compendium-browser/filters.html
  static/templates/items/spell-details.html
Labels: pr: enhancement, ui/ux

#3304 Create empty vendor.bundle.js to keep Foundry V10 server happy
  webpack.config.ts
Labels: pr: foundry v10

#3305 Tone down tagify disabled effects for paizo style
  src/styles/ui/_tags.scss
Labels: pr: bugfix

#3306 Convert some missed actor/item.data.datas
  src/module/actor/base.ts
  src/module/actor/helpers.ts
  src/module/actor/item-transfer.ts
  src/module/actor/spellcasting.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/module/rules/index.ts
  src/module/system/effect-tracker.ts
  src/module/system/rolls.ts
  src/module/system/text-editor.ts
Labels: pr: foundry v10

#3309 Add `system` property to `ActorSource` and `ItemSource` types
  src/module/actor/character/data/types.ts
  src/module/actor/creature/data.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/hazard/data.ts
  src/module/actor/loot/data.ts
  src/module/actor/npc/data.ts
  src/module/item/data/base.ts
  src/module/migration/migrations/711-heritage-items.ts
  types/foundry/common/data/data/actor-data.d.ts
  types/foundry/common/data/data/item-data.d.ts
Labels: pr: foundry v10

#3312 Fix migration 662 and remove migration 622
  src/module/migration/migrations/622-remove-old-token-effect-icons.ts
  src/module/migration/migrations/662-link-to-actor-size-defaults.ts
  src/module/migration/migrations/index.ts
Labels: pr: foundry v10

#3307 Fix description of Iris of the Sky item
  packs/data/equipment.db/iris-of-the-sky.json
Labels: pr: data update

#3315 Get an empty scene loading without errors or warnings
  packs/scripts/extract.ts
  src/module/apps/world-clock/animate-darkness.ts
  src/module/apps/world-clock/app.ts
  src/module/canvas/layer/lighting.ts
  src/module/canvas/measured-template.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/scene/data.ts
  src/module/scene/document.ts
  src/module/scene/token-document/aura/index.ts
  src/module/scene/token-document/document.ts
  src/module/system/settings/world-clock.ts
  src/scripts/hooks/lighting-refresh.ts
  types/foundry/client/documents/scene.d.ts
  types/foundry/client/documents/token-document.d.ts
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/client/pixi/placeables-layer/lighting-layer.d.ts
  types/foundry/common/data/data/scene-data.d.ts
  types/foundry/common/documents/index.d.ts
  types/foundry/common/documents/scene.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v10

#3316 Add sources to NPCs from SoT Book 4
  packs/data/abomination-vaults-bestiary.db/bone-gladiator.json
  packs/data/one-shot-bestiary.db/doatara-the-poisoner.json
  packs/data/one-shot-bestiary.db/doatara-the-priest.json
  packs/data/one-shot-bestiary.db/kelorbeyan-guard.json
  packs/data/pathfinder-dark-archive.db/reflection.json
  packs/data/strength-of-thousands-bestiary.db/abendego-brutes.json
  packs/data/strength-of-thousands-bestiary.db/avatar-of-walkena.json
  packs/data/strength-of-thousands-bestiary.db/baaupa-mdoudu.json
  packs/data/strength-of-thousands-bestiary.db/biloko-reaver.json
  packs/data/strength-of-thousands-bestiary.db/dajermube.json
  packs/data/strength-of-thousands-bestiary.db/dimari-diji.json
  packs/data/strength-of-thousands-bestiary.db/drenchdead.json
  packs/data/strength-of-thousands-bestiary.db/gambulami.json
  packs/data/strength-of-thousands-bestiary.db/gold-defender-garrison.json
  packs/data/strength-of-thousands-bestiary.db/gold-defender.json
  packs/data/strength-of-thousands-bestiary.db/grave-karina.json
  packs/data/strength-of-thousands-bestiary.db/graveknight-captain.json
  packs/data/strength-of-thousands-bestiary.db/graveknight-champion.json
  packs/data/strength-of-thousands-bestiary.db/jackal-guard.json
  packs/data/strength-of-thousands-bestiary.db/kilia-mwibo.json
  packs/data/strength-of-thousands-bestiary.db/living-sun-spire.json
  packs/data/strength-of-thousands-bestiary.db/nkiruka.json
  packs/data/strength-of-thousands-bestiary.db/reborn-sun-hunter.json
  packs/data/strength-of-thousands-bestiary.db/reborn-sun-mage.json
  packs/data/strength-of-thousands-bestiary.db/reborn-sun-warrior.json
  packs/data/strength-of-thousands-bestiary.db/soul-swarm.json
  packs/data/strength-of-thousands-bestiary.db/sun-warrior-brigade.json
  packs/data/strength-of-thousands-bestiary.db/sunburst-corpse.json
  packs/data/strength-of-thousands-bestiary.db/worknesh.json
Labels: source: adventure path, pr: data entry, pr: data update

#3320 Support @ actor in roll macros
  src/module/actor/base.ts
Labels: pr: enhancement

#3319 Continue addressing warnings on PC & sheet
  .betterer.results
  src/module/actor/character/feats.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/npc/config.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/index.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/popups/ability-builder.ts
  src/module/apps/ui/chat-log.ts
  src/module/apps/ui/encounter-tracker.ts
  src/module/canvas/ghost-measured-template.ts
  src/module/canvas/token/object.ts
  src/module/encounter/combatant.ts
  src/module/item/abc/manager.ts
  src/module/item/action/index.ts
  src/module/item/ancestry/index.ts
  src/module/item/base.ts
  src/module/item/condition/index.ts
  src/module/item/effect/index.ts
  src/module/item/feat/index.ts
  src/module/item/heritage/document.ts
  src/module/item/physical/sheet.ts
  src/module/item/sheet/base.ts
  src/module/item/weapon/index.ts
  src/module/migration/migrations/611-update-toughness-mountains-stoutness.ts
  src/module/migration/migrations/723-cumulative-item-bonuses.ts
  src/module/migration/migrations/738-update-laughing-shadow.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/rules/rule-element/grant-item/base.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/module/rules/rule-element/temp-hp.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  src/module/system/conditions/manager.ts
  src/module/system/settings/homebrew/menu.ts
  src/scripts/hooks/ready.ts
  src/scripts/macros/hotbar.ts
  src/scripts/macros/raise-a-shield.ts
  src/scripts/register-module-art.ts
  types/foundry/client/config.d.ts
  types/foundry/client/documents/combatant.d.ts
  types/foundry/client/documents/mixins/canvas-document-mixin.d.ts
  types/foundry/client/documents/token-document.d.ts
  types/foundry/client/game.d.ts
  types/foundry/client/pixi/canvas-layer/sight-layer.d.ts
  types/foundry/client/pixi/placeable-object/ambient-sound.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/client/pixi/placeables-layer/sounds-layer.d.ts
  types/foundry/common/documents/token.d.ts
  types/foundry/index.d.ts
Labels: pr: foundry v10

#3322 Allow scenes with tokens to load without errors
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
Labels: pr: foundry v10

#3325 Remove references to ItemData in condition manager
  src/module/system/conditions/manager.ts
Labels: pr: foundry v10

#3323 Fix display of token effects and scrolling text
  src/module/actor/base.ts
  src/module/actor/token-effect.ts
  src/module/canvas/token/object.ts
  src/module/rules/rule-element/token-effect-icon.ts
  src/scripts/actor/status-effects.ts
  types/foundry/client/documents/active-effect.d.ts
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/client/pixi/interface-canvas-group.d.ts
  types/foundry/index.d.ts
Labels: pr: foundry v10

#3326 Get NPC sheet to load without errors/warnings
  src/module/actor/creature/index.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/npc/index.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/recall-knowledge.ts
  src/module/scene/token-document/document.ts
  static/templates/actors/npc/partials/header.html
  static/templates/actors/npc/partials/sidebar.html
  static/templates/actors/npc/tabs/main.html
  static/templates/actors/npc/tabs/notes.html
  tests/module/recall-knowledge.test.ts
Labels: pr: foundry v10

#3327 Convert .data.data to .system in macros
  src/module/system/action-macros/helpers.ts
  src/scripts/macros/travel/travel-speed-sheet.ts
  src/scripts/macros/treat-wounds.ts
Labels: pr: foundry v10

#3329 Convert tag selectors to use `system`
  src/module/system/tag-selector/basic.ts
  src/module/system/tag-selector/resistances.ts
  src/module/system/tag-selector/senses.ts
  src/module/system/tag-selector/speeds.ts
  src/module/system/tag-selector/weaknesses.ts
  static/templates/actors/character/partials/traits.html
  static/templates/actors/character/sidebar/resistances.html
  static/templates/actors/hazard/partials/sidebar.html
  static/templates/actors/npc/partials/header.html
  static/templates/actors/npc/partials/sidebar.html
  static/templates/actors/npc/tabs/main.html
  static/templates/actors/vehicle/sidebar/vehicle-resistances.html
  static/templates/actors/vehicle/tabs/vehicle-details.html
  static/templates/items/action-details.html
  static/templates/items/ancestry-details.html
  static/templates/items/armor-details.html
  static/templates/items/background-details.html
  static/templates/items/backpack-details.html
  static/templates/items/book-details.html
  static/templates/items/class-details.html
  static/templates/items/consumable-details.html
  static/templates/items/equipment-details.html
  static/templates/items/feat-details.html
  static/templates/items/kit-details.html
  static/templates/items/melee-details.html
  static/templates/items/weapon-details.html
Labels: pr: foundry v10

#3328 Update CompendiumBrowser drag workflow for v10
  src/module/apps/compendium-browser/index.ts
  static/templates/compendium-browser/action-browser.html
  static/templates/compendium-browser/bestiary-browser.html
  static/templates/compendium-browser/feat-browser.html
  static/templates/compendium-browser/hazard-browser.html
  static/templates/compendium-browser/inventory-browser.html
  static/templates/compendium-browser/spell-browser.html
Labels: pr: foundry v10

#3335 Remove V9 data shims from AE-like RE
  src/module/rules/rule-element/ae-like.ts
Labels: pr: foundry v10

#3337 Refactor CompendiumBrowser listeners
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/action.ts
  src/module/apps/compendium-browser/tabs/base.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
  src/module/apps/compendium-browser/tabs/spell.ts
  src/scripts/register-templates.ts
  static/templates/compendium-browser/action-browser.html
  static/templates/compendium-browser/bestiary-browser.html
  static/templates/compendium-browser/compendium-browser.html
  static/templates/compendium-browser/feat-browser.html
  static/templates/compendium-browser/hazard-browser.html
  static/templates/compendium-browser/inventory-browser.html
  static/templates/compendium-browser/partials/action.html
  static/templates/compendium-browser/partials/bestiary.html
  static/templates/compendium-browser/partials/equipment.html
  static/templates/compendium-browser/partials/feat.html
  static/templates/compendium-browser/partials/hazard.html
  static/templates/compendium-browser/partials/spell.html
  static/templates/compendium-browser/spell-browser.html
Labels: pr: bugfix, pr: refactor

#3344 Start using .system instead of .data.data in item sheets
  src/module/item/abc/manager.ts
  src/module/item/abc/sheet.ts
  src/module/item/action/data.ts
  src/module/item/ancestry/data.ts
  src/module/item/ancestry/sheet.ts
  src/module/item/background/data.ts
  src/module/item/background/sheet.ts
  src/module/item/base.ts
  src/module/item/class/data.ts
  src/module/item/class/sheet.ts
  src/module/item/condition/data.ts
  src/module/item/data/index.ts
  src/module/item/deity/data.ts
  src/module/item/effect/data.ts
  src/module/item/heritage/data.ts
  src/module/item/kit/data.ts
  src/module/item/lore/data.ts
  src/module/item/sheet/base.ts
  src/module/item/spellcasting-entry/data/types.ts
  static/templates/items/ancestry-details.html
  static/templates/items/deity-details.html
  static/templates/items/item-sheet.html
  static/templates/items/mystify-panel.html
  types/foundry/client/application/form-application/base.d.ts
Labels: pr: foundry v10

#3345 Use .system instead of .data in pack builder
  packs/scripts/packman/compendium-pack.ts
Labels: pr: foundry v10

#3340 Use system. instead of data. in kit sheet
  src/module/item/kit/sheet.ts
Labels: pr: foundry v10

#3346 Fix character strike generation from weapons
  src/module/item/weapon/index.ts
Labels: pr: foundry v10

#3347 Convert more system `data.data` properties to `system` properties
  src/module/actor/base.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/config.ts
  src/module/actor/npc/index.ts
  src/module/actor/sheet/trick-magic-item-popup.ts
  src/module/actor/vehicle/sheet.ts
  src/module/chat-message/document.ts
  src/module/doc-helpers.ts
  src/module/item/class/data.ts
  src/module/item/class/index.ts
  src/module/item/consumable/spell-consumables.ts
  src/module/item/data/helpers.ts
  src/module/item/data/index.ts
  src/module/item/identification.ts
  src/module/item/physical/bulk.ts
  src/module/item/physical/index.ts
  src/module/item/spell/index.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/item/weapon/index.ts
  src/module/migration/migrations/736-remove-broken-threshold.ts
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/prompt.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/rules/rule-element/grant-item/base.ts
  src/module/system/settings/homebrew/cleanup-migration.ts
Labels: pr: foundry v10

#3342 Fix roll expressions and remove unused translation key
  packs/data/blood-lords-bestiary.db/opkherab.json
  packs/data/blood-lords-bestiary.db/zombie-horse.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/archery-specialist.json
  packs/data/pfs-season-1-bestiary.db/reefclaw-spawn.json
  packs/data/pfs-season-2-bestiary.db/nuglub-pfs-2-00.json
  packs/data/pfs-season-2-bestiary.db/quickling-pfs-2-00.json
  packs/data/pfs-season-2-bestiary.db/qxal-the-thorned-monarch.json
  packs/data/pfs-season-3-bestiary.db/nuglub-pfs-3-18.json
Labels: pr: data update

#3351 Update system.json for V10 compatibility
  system.json
Labels: pr: foundry v10

#3357 Convert more instances of data to system
  src/module/actor/hazard/index.ts
  src/module/item/weapon/index.ts
  src/module/item/weapon/sheet.ts
Labels: pr: foundry v10

#3358 Fix bug with updating frequency values
  static/templates/actors/character/tabs/actions.html
Labels: pr: bugfix

#3360 Update character actions tab to new headers, reset styling for v10
  src/styles/actor/_index.scss
  src/styles/actor/_reset.scss
  src/styles/actor/tabs/_actions.scss
  static/lang/en.json
  static/templates/actors/character/tabs/actions.html
  static/templates/actors/character/tabs/feats.html
Labels: pr: foundry v10, ui/ux

#3361 Update system.json to indicate support for 10.277
  system.json
Labels: pr: foundry v10

#3362 Expand creation of empty static files in dev mode to tinymce.css
  webpack.config.ts
Labels: pr: foundry v10

#3363 Convert more data properties to system properties in sheet classes
  src/module/actor/sheet/base.ts
  src/module/item/armor/sheet.ts
  src/module/item/equipment/sheet.ts
  src/module/item/physical/sheet.ts
  src/module/item/spell/sheet.ts
  src/module/item/weapon/sheet.ts
Labels: pr: foundry v10

#3364 Remove cyclic import of PhysicalItemPF2e
  src/module/actor/loot/index.ts
Labels: pr: bugfix

#3365 Expand usage of `isOfType`
  src/module/actor/character/crafting/helpers.ts
  src/module/canvas/token/object.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/physical/index.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/module/scene/token-document/document.ts
  src/module/system/conditions/manager.ts
  src/module/system/effect-tracker.ts
  src/module/system/statistic/index.ts
Labels: pr: refactor

#3366 Allow scrolls/wands for entries that contain the spell
  src/module/actor/spellcasting.ts
  src/module/item/consumable/index.ts
  src/module/item/spellcasting-entry/index.ts
Labels: pr: enhancement

#3367 Continue the data-to-system conversion
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/inventory/index.ts
  src/module/actor/sheet/base.ts
  src/module/actor/vehicle/index.ts
  src/module/encounter/combatant.ts
  src/module/item/abc/index.ts
  src/module/item/action/index.ts
  src/module/item/class/sheet.ts
  src/module/item/effect/index.ts
  src/module/item/feat/index.ts
  src/module/item/kit/index.ts
  src/module/item/spell/index.ts
  src/module/item/spell/overlay.ts
  src/module/item/weapon/index.ts
  src/module/system/action-macros/crafting/repair.ts
  src/module/system/damage/roll-dialog.ts
  src/module/system/rolls.ts
  src/module/system/tag-selector/resistances.ts
  src/module/system/tag-selector/weaknesses.ts
Labels: pr: foundry v10

#3372 Fix melee/ranged status of chakrams
  packs/data/equipment.db/chakram.json
  packs/data/equipment.db/tamchal-chakram.json
Labels: pr: data update

#3368 Convert embedded spell variants from `data` to `system`
  packs/data/age-of-ashes-bestiary.db/malarunk.json
  packs/data/pathfinder-bestiary-3.db/girtablilu-seer.json
  packs/data/pathfinder-bestiary-3.db/gliminal.json
  packs/data/pathfinder-bestiary-3.db/green-man.json
  packs/data/pathfinder-bestiary-3.db/grioth-cultist.json
  packs/data/pathfinder-bestiary-3.db/herexen.json
  packs/data/pathfinder-bestiary-3.db/tomb-giant.json
  packs/data/spells.db/aberrant-whispers.json
  packs/data/spells.db/aspirational-state.json
  packs/data/spells.db/awaken-entropy.json
  packs/data/spells.db/blessing-of-defiance.json
  packs/data/spells.db/boneshaker.json
  packs/data/spells.db/concordant-choir.json
  packs/data/spells.db/elemental-annihilation-wave.json
  packs/data/spells.db/etheric-shards.json
  packs/data/spells.db/faerie-dust.json
  packs/data/spells.db/gravitational-pull.json
  packs/data/spells.db/harm.json
  packs/data/spells.db/heal-animal.json
  packs/data/spells.db/heal-companion.json
  packs/data/spells.db/heal.json
  packs/data/spells.db/horizon-thunder-sphere.json
  packs/data/spells.db/inner-radiance-torrent.json
  packs/data/spells.db/ki-blast.json
  packs/data/spells.db/kinetic-ram.json
  packs/data/spells.db/rebuke-death.json
  packs/data/spells.db/rip-the-spirit.json
  packs/data/spells.db/scorching-ray.json
  packs/data/spells.db/swamp-of-sloth.json
  packs/data/spells.db/warped-terrain.json
  packs/data/spells.db/wronged-monks-wrath.json
  packs/scripts/run-migration.ts
  src/module/item/spell/data/types.ts
  src/module/migration/migrations/771-spell-variants-to-system.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: foundry v10

#3374 Convert SpellHeightenLayer to use `system` instead of `data`
  src/module/item/spell/data/types.ts
  src/module/item/spell/index.ts
  src/module/item/spell/sheet.ts
  static/templates/items/spell-overlay.html
Labels: pr: foundry v10

#3376 Update codebase to reflect new location of token img and scale
  packs/scripts/extract.ts
  src/module/actor/base.ts
  src/module/actor/npc/index.ts
  src/module/canvas/token/object.ts
  src/module/migration/migrations/620-rename-to-webp.ts
  src/module/migration/migrations/645-token-image-size.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  static/templates/chat/treasure-card.html
  static/templates/system/actions/repair/roll-damage-chat-message.html
  types/foundry/common/data/data/prototype-token-data.d.ts
  types/foundry/common/data/data/token-data.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v10

#3373 Restore functionality of system compendium directory in Foundry V10
  src/module/apps/ui/compendium-directory.ts
  src/scripts/hooks/ready.ts
  static/templates/sidebar/compendium-directory.html
Labels: pr: foundry v10

#3378 Remove uses of deprecated `NormalizedRectangle` class
  src/module/canvas/effect-area-square.ts
  src/module/canvas/helpers.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/object.ts
  src/module/scene/token-document/aura/index.ts
  src/module/scene/token-document/aura/types.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/pixi/helpers/index.d.ts
  types/foundry/client/pixi/helpers/rectangle.d.ts
  types/foundry/client/pixi/placeable-object/ambient-light.d.ts
  types/foundry/client/pixi/placeable-object/drawing.d.ts
  types/foundry/client/pixi/placeable-object/measured-template.d.ts
  types/foundry/client/pixi/placeable-object/note.d.ts
  types/foundry/client/pixi/placeable-object/tile.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
  types/foundry/client/pixi/placeable-object/wall.d.ts
  types/foundry/client/pixi/placeables-layer/walls-layer.d.ts
Labels: pr: foundry v10

#3379 Pass ammo items in full to PC sheet template
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/module/actor/data/base.ts
  static/templates/actors/character/tabs/actions.html
Labels: pr: foundry v10

#3380 Update spellcasting/crafting headers and chat/spellprep stylings for v10
  src/styles/_reset.scss
  src/styles/actor/_index.scss
  src/styles/actor/character/_actions.scss
  src/styles/actor/character/_crafting.scss
  src/styles/actor/character/_spellcasting.scss
  src/styles/ui/sidebar/chat/_index.scss
Labels: pr: foundry v10

#3385 Update token sheet for V10
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  src/styles/scene/_token-config.scss
  static/templates/scene/token-config.html
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v10

#3386 Cut off access to .data.data in actor and item types
  packs/scripts/extract.ts
  src/module/actor/base.ts
  src/module/actor/creature/index.ts
  src/module/actor/data/base.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/skills-editor.ts
  src/module/actor/npc/types.ts
  src/module/actor/sheet/data-types.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/apps/effects-panel.ts
  src/module/chat-message/listeners/cards.ts
  src/module/encounter/document.ts
  src/module/item/ancestry/index.ts
  src/module/item/base.ts
  src/module/item/consumable/spell-consumables.ts
  src/module/item/data/base.ts
  src/module/item/sheet/data-types.ts
  src/module/item/spell/index.ts
  src/module/item/spell/overlay.ts
  src/module/migration/migrations/626-update-spell-category.ts
  src/module/rules/rule-element/adjust-degree-of-success.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/module/rules/rule-element/roll-option.ts
  src/module/rules/rule-element/strike.ts
  src/util/from-uuids.ts
  tests/fakes/fake-item.ts
  types/foundry/client/documents/combat.d.ts
  types/foundry/common/data/data/actor-data.d.ts
  types/foundry/common/data/data/item-data.d.ts
  types/foundry/common/documents/actor.d.ts
  types/foundry/common/documents/item.d.ts
Labels: pr: foundry v10

#3387 Update NPM dependencies
  package-lock.json
  package.json
  src/module/item/sheet/base.ts
  src/module/journal-entry/sheet.ts
  types/foundry/client/application/form-application/base.d.ts
  types/foundry/client/config.d.ts
  types/foundry/client/core/text-editor.d.ts
  types/foundry/client/pixi/index.d.ts
Labels: pr: foundry v10

#3389 Fix build following V10 types update
  .gitignore
  package-lock.json
  types/foundry/client/pixi/index.d.ts
Labels: pr: bugfix

#3390 Change `name` property in system.json to `id`
  system.json
Labels: pr: foundry v10

#3391 Remove V9 shims in RuleElementPF2e#resolveInjectedProperties
  src/module/rules/rule-element/base.ts
Labels: pr: foundry v10

#3388 Add PFS level bump to damage rolls
  src/module/actor/base.ts
  src/module/actor/character/index.ts
Labels: pr: bugfix

#3393 Convert "data." to "system." in css name attribute selectors
  src/styles/item/_sidebar.scss
  src/styles/legacy/_pf2e.scss
Labels: pr: foundry v10

#3394 Use newly available wand-magic-sparkles icon for PC spellcasting tab
  static/templates/actors/character/sheet.html
Labels: ui/ux

#3395 Remove `ActorPF2e#physicalItems` getter
  src/module/actor/base.ts
Labels: pr: foundry v10

#3396 Update character proficiency tab to new headers
  src/styles/actor/character/_proficiencies.scss
  static/templates/actors/character/tabs/proficiencies.html
Labels: pr: bugfix, ui/ux

#3398 Fix pair of regressions from V10 conversion work
  src/module/actor/base.ts
  src/module/item/base.ts
  src/module/rules/rule-element/grant-item/base.ts
Labels: pr: bugfix

#2972 Report bulk differences in the inventory
  src/module/actor/data/size.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/styles/actor/_inventory.scss
  static/templates/actors/partials/item-line.html
Labels: pr: enhancement

#3402 Convert a few item sheets to use getBaseData
  src/module/item/action/sheet.ts
  src/module/item/effect/sheet.ts
  src/module/item/feat/sheet.ts
  src/module/item/sheet/base.ts
  src/module/item/spell/sheet.ts
  src/styles/item/_index.scss
  static/templates/items/feat-sidebar.html
Labels: pr: refactor

#3404 Fix RE labels on sheets that use getBaseData
  src/module/item/sheet/base.ts
  src/module/item/sheet/data-types.ts
Labels: pr: bugfix

#3407 Add sheet toggle for container stowability
  src/module/item/container/sheet.ts
  src/module/item/sheet/base.ts
  src/scripts/register-sheets.ts
  static/lang/en.json
  static/templates/items/backpack-details.html
Labels: pr: enhancement

#3408 Update TokenImage RE for V10
  src/module/actor/base.ts
  src/module/rules/rule-element/token-image.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/documents/token-document.d.ts
Labels: pr: foundry v10

#3409 Fix loading Journal sheet on v10
  src/module/journal-entry/sheet.ts
  src/scripts/hooks/render-journal-page-sheet.ts
  src/styles/mixins/_tinymce.scss
  src/styles/system/journal/_index.scss
  static/templates/journal/sheet.html
Labels: pr: foundry v10

#3410 Fix triggered refresh of effects panel
  src/module/apps/effects-panel.ts
  src/module/item/data/base.ts
  src/module/item/effect/data.ts
  static/templates/system/effects-panel.html
Labels: pr: bugfix

#3411 Update ItemDataPF2e type property omission for V10
  src/module/item/action/data.ts
  src/module/item/ancestry/data.ts
  src/module/item/armor/data.ts
  src/module/item/background/data.ts
  src/module/item/book/data.ts
  src/module/item/class/data.ts
  src/module/item/condition/data.ts
  src/module/item/consumable/data.ts
  src/module/item/container/data.ts
  src/module/item/deity/data.ts
  src/module/item/equipment/data.ts
  src/module/item/feat/data.ts
  src/module/item/heritage/data.ts
  src/module/item/kit/data.ts
  src/module/item/lore/data.ts
  src/module/item/melee/data.ts
  src/module/item/physical/data.ts
  src/module/item/spell/data/types.ts
  src/module/item/spellcasting-entry/data/types.ts
  src/module/item/treasure/data.ts
  src/module/item/weapon/data/types.ts
Labels: pr: foundry v10, pr: types update

#3412 Use `Item` instance when appropriate in item card templates
  static/templates/chat/action-card.html
  static/templates/chat/armor-card.html
  static/templates/chat/backpack-card.html
  static/templates/chat/condition-card.html
  static/templates/chat/consumable-card.html
  static/templates/chat/effect-card.html
  static/templates/chat/equipment-card.html
  static/templates/chat/feat-card.html
  static/templates/chat/melee-card.html
  static/templates/chat/strike-card.html
  static/templates/chat/weapon-card.html
Labels: pr: refactor

#3414 Preserve hacked-together damage data of acid flasks and similar weapons
  src/module/item/weapon/data/types.ts
  src/module/item/weapon/index.ts
  src/module/item/weapon/sheet.ts
  types/foundry/package-lock.json
Labels: pr: bugfix

#3415 .gitignore package-lock.json in types/foundry
  .gitignore
  types/foundry/package-lock.json
Labels: pr: housekeeping

#3417 Fix data in combat actor re-prep
  src/scripts/hooks/ready.ts
  types/foundry/common/abstract/document.d.ts
Labels: pr: foundry v10

#3418 Convert entity-link to content-link
  packs/scripts/extract.ts
  src/module/actor/sheet/base.ts
  src/scripts/system/dragstart-handler.ts
  src/styles/_globals.scss
  src/styles/mixins/_tinymce.scss
Labels: pr: foundry v10

#3420 Use v10 getters for token controlled and hover
  src/module/actor/base.ts
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/object.ts
  src/module/chat-message/document.ts
  src/module/rules/rule-element/base.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
Labels: pr: foundry v10

#3421 Fix regression with opening melee sheets
  src/module/item/armor/sheet.ts
  src/module/item/container/sheet.ts
  src/module/item/equipment/sheet.ts
  src/module/item/melee/sheet.ts
  src/module/item/physical/sheet.ts
  src/module/item/sheet/base.ts
  src/module/item/sheet/data-types.ts
  src/module/item/weapon/sheet.ts
  src/scripts/register-sheets.ts
Labels: pr: bugfix, pr: refactor

#3425 Squash more v10 warnings
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/item/sheet/base.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/system/action-macros/crafting/craft.ts
  src/scripts/dice.ts
  static/templates/actors/npc/tabs/spells.html
  types/foundry/common/documents/chat-message.d.ts
Labels: pr: foundry v10

#3416 Cascade pf2e styling to prosemirror editor sheet
  src/module/journal-entry/sheet.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-journal-page-sheet.ts
  src/styles/system/journal/_index.scss
  types/foundry/client/application/journal/journal-page-sheet.ts
  types/foundry/client/core/hooks.d.ts
  types/foundry/client/documents/constructors.d.ts
  types/foundry/client/documents/journal-entry-page.d.ts
  types/foundry/client/documents/journal-entry.d.ts
  types/foundry/common/data/data/index.d.ts
  types/foundry/common/data/data/journal-entry-data.d.ts
  types/foundry/common/data/data/journal-entry-page-data.d.ts
  types/foundry/common/documents/base-journal-entry-page.d.ts
  types/foundry/common/documents/base-journal-entry.d.ts
  types/foundry/common/documents/index.d.ts
Labels: pr: foundry v10

#3426 Work around `DataModel` constructor altering descriptors on `source`
  src/module/actor/base.ts
  src/module/item/base.ts
Labels: pr: foundry v10

#3427 Implement Brutal trait for PCs
  src/module/actor/character/index.ts
  src/module/item/weapon/index.ts
  src/scripts/config/traits.ts
Labels: pr: enhancement

#3428 Convert `data` to `system` in code that sneaks past type checks
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/popups/ability-builder.ts
  src/module/item/action/sheet.ts
  src/module/item/base.ts
  src/module/item/feat/index.ts
  src/module/item/feat/sheet.ts
  src/module/system/rolls.ts
  src/scripts/macros/rest-for-the-night.ts
Labels: pr: foundry v10

#3429 Fix cantrip toggle
  src/module/item/spell/sheet.ts
Labels: pr: bugfix

#3432 Fix assigning default token image
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
Labels: pr: foundry v10

#3433 Avoid double data preparation
  src/module/actor/base.ts
  src/module/canvas/token/object.ts
  src/module/item/abc/manager.ts
  src/module/item/base.ts
  src/module/scene/token-document/document.ts
  src/module/system/effect-tracker.ts
  src/module/system/settings/automation.ts
  src/scripts/hooks/migration-complete.ts
Labels: pr: foundry v10

#3434 Remove remaining RBV canvas code and token-auras module check
  src/module/canvas/layer/token.ts
  src/module/canvas/token/object.ts
  src/module/scene/token-document/document.ts
Labels: pr: foundry v10

#3438 Move journal-entry-related sheets to proper folder and index
  types/foundry/client/application/form-application/document-sheet/journal-page-sheet.d.ts
  types/foundry/client/application/form-application/document-sheet/journal-sheet.d.ts
  types/foundry/client/application/form-application/document-sheet/note-config.d.ts
  types/foundry/client/documents/index.d.ts
  types/foundry/index.d.ts
Labels: pr: types update

#3440 Remove deprecated Token#animateMovement type and use Token#animate
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/core/interaction/canvas-animation.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
  types/foundry/index.d.ts
Labels: pr: foundry v10

#3439 Add async overloads to `TextEditor.enrichHTML` and `TextEditorPF2e.enrichHTML`
  src/module/system/text-editor.ts
  types/foundry/client/core/text-editor.d.ts
Labels: pr: foundry v10, pr: types update

#3435 Add show image button to npc and characters
  src/module/actor/sheet/base.ts
  src/styles/actor/character/_character.scss
  src/styles/actor/npc/_index.scss
  static/templates/actors/character/tabs/general.html
  static/templates/actors/npc/partials/sidebar.html
Labels: pr: new feature

#3442 Use fa-stack for held carry type in item lines
  src/styles/actor/_inventory.scss
  static/templates/actors/partials/carry-type.html
  static/templates/actors/partials/item-line.html
Labels: ui/ux

#3444 Fix handling of item drops onto hotbar
  src/module/apps/ui/hotbar.ts
Labels: pr: foundry v10

#3445 Sort lines in .gitignore
  .gitignore
Labels: pr: housekeeping

#3441 Add type definition for `fromUuidSync` helper function
  types/foundry/client/collections/compendium-collection.d.ts
Labels: pr: foundry v10

#3443 Set default value for `async` option in TextEditor#enrichHTML
  src/module/system/text-editor.ts
Labels: pr: bugfix, pr: foundry v10

#3447 Only show popout art image when hovering
  src/styles/actor/_index.scss
  src/styles/actor/character/_character.scss
  src/styles/actor/npc/_index.scss
  static/templates/actors/character/tabs/general.html
  static/templates/actors/npc/partials/sidebar.html
Labels: pr: enhancement

#3448 Remove reference to `Macro#data` and `Item#data` in macro hotbar scripts
  src/scripts/macros/hotbar.ts
  types/foundry/client/documents/macro.d.ts
Labels: pr: foundry v10

#3449 Set `TokenDocumentPF2e#initialized` only once
  src/module/rules/rule-element/token-light.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix, pr: foundry v10

#3451 Remove use Actor#overrides by token REs in favor of ActorPF2e#synthetics
  src/module/actor/base.ts
  src/module/rules/rule-element/token-image.ts
  src/module/rules/rule-element/token-light.ts
  src/module/rules/rule-element/token-name.ts
  src/module/rules/synthetics.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix, pr: foundry v10, pr: refactor

#3452 Assert LightData construction as compatible with V9 type definition
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#3459 Fix color of input text on NPC sheet spellcasting entry headers
  src/styles/actor/npc/_spells.scss
Labels: pr: bugfix, ui/ux

#3456 Restore functionality of auras in V10
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/aura/util.ts
  src/module/scene/document.ts
  src/module/scene/token-document/aura/index.ts
  types/foundry/client/game.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/common/utils/color.d.ts
  types/foundry/common/utils/index.d.ts
Labels: pr: foundry v10

#3460 Fix category of two drake rifle variants
  packs/data/equipment.db/drake-rifle-fire.json
  packs/data/equipment.db/drake-rifle-poison.json
Labels: pr: data update

#3462 Remove reference to Combatant#data
  src/module/apps/ui/encounter-tracker.ts
Labels: pr: foundry v10

#3464 Remove reference to item.data.sort in hazard sheet
  src/module/actor/hazard/sheet.ts
Labels: pr: foundry v10

#3467 Remove reference to actor.data.type
  src/module/encounter/document.ts
Labels: pr: foundry v10

#3463 Rename `ConsumablePF2e#charges` to `#uses`, remove `uses.current`
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/item/consumable/index.ts
  src/scripts/macros/rest-for-the-night.ts
Labels: pr: foundry v10

#3466 Fix duration of Veil of Dreams spell effect
  packs/data/spell-effects.db/spell-effect-veil-of-dreams.json
Labels: pr: data update

#3472 Move `AbilityBuilderPopup#activateListeners` to bottom of class
  src/module/actor/sheet/popups/ability-builder.ts
Labels: pr: housekeeping

#3471 Exclude negative ability modifiers from battle form damage
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: bugfix

#3465 Review weapon and mystified traits, prune/add as needed
  src/module/item/data/values.ts
  src/scripts/config/traits.ts
Labels: pr: bugfix

#3461 Suppress fundamental runes on armor if ABP is enabled
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/item/armor/data.ts
  src/module/item/armor/index.ts
  src/module/item/armor/sheet.ts
  src/module/item/runes.ts
  src/module/item/weapon/index.ts
  src/module/item/weapon/sheet.ts
  src/module/migration/migrations/679-tower-shield-speed-penalty.ts
  src/module/migration/migrations/728-flatten-physical-properties.ts
Labels: pr: bugfix, pr: refactor

#3473 Fix some Compendium Browser filters not expanding on click
  src/module/apps/compendium-browser/index.ts
Labels: pr: bugfix

#3474 Fix regression with heightened prepared/signature spells
  src/module/chat-message/listeners/cards.ts
  src/module/item/spell/index.ts
  src/module/item/spellcasting-entry/index.ts
  static/templates/actors/spellcasting-spell-list.html
Labels: pr: bugfix

#3455 Convert all `enrichHTML` references to async and remove handlebars helper
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/actor/vehicle/sheet.ts
  src/module/apps/migration-summary.ts
  src/module/chat-message/document.ts
  src/module/item/abc/sheet.ts
  src/module/item/action/index.ts
  src/module/item/action/sheet.ts
  src/module/item/armor/index.ts
  src/module/item/base.ts
  src/module/item/consumable/index.ts
  src/module/item/container/index.ts
  src/module/item/data/index.ts
  src/module/item/deity/sheet.ts
  src/module/item/equipment/index.ts
  src/module/item/feat/index.ts
  src/module/item/feat/sheet.ts
  src/module/item/heritage/sheet.ts
  src/module/item/kit/sheet.ts
  src/module/item/melee/index.ts
  src/module/item/melee/sheet.ts
  src/module/item/physical/index.ts
  src/module/item/physical/sheet.ts
  src/module/item/sheet/base.ts
  src/module/item/sheet/data-types.ts
  src/module/item/spell/index.ts
  src/module/item/spell/sheet.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/spellcasting-entry/sheet.ts
  src/module/item/treasure/index.ts
  src/module/item/weapon/index.ts
  src/module/system/conditions/types.ts
  src/module/system/damage/roll-dialog.ts
  src/module/system/rolls.ts
  src/scripts/handlebars.ts
  src/scripts/macros/hotbar.ts
  static/templates/actors/character/limited.html
  static/templates/actors/hazard/sheet.html
  static/templates/actors/limited/npc-sheet.html
  static/templates/actors/loot/sidebar.html
  static/templates/actors/npc/partials/attack.html
  static/templates/actors/partials/conditions.html
  static/templates/chat/damage/damage-card-flavor.html
  static/templates/items/item-sheet.html
  static/templates/items/mystify-panel.html
  static/templates/system/migration-summary.html
  types/foundry/client/documents/chat-message.d.ts
Labels: pr: foundry v10

#3478 Rename `PrototypeTokenData` to `PrototypeToken`
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  src/module/scene/token-document/document.ts
  src/scripts/hooks/init.ts
  types/foundry/client/documents/actor.d.ts
  types/foundry/common/data/data/prototype-token-data.d.ts
  types/foundry/common/documents/actor.d.ts
Labels: pr: foundry v10

#3479 Use a custom enricher for PF2e specific enrichHTML patterns
  src/module/actor/npc/index.ts
  src/module/item/base.ts
  src/module/system/text-editor.ts
  src/scripts/hooks/init.ts
  types/foundry/client/config.d.ts
Labels: pr: foundry v10

#3477 Change default to core.notesDisplayToggle setting
  src/global.d.ts
  src/scripts/hooks/setup.ts
  types/foundry/client/core/settings.d.ts
Labels: pr: enhancement

#3476 Allow strike attack and damage roll methods to be called with no args
  src/module/actor/character/index.ts
  src/module/actor/npc/index.ts
Labels: pr: enhancement

#3483 Make `PredicatePF2e.validate` a type guard
  src/module/system/predication.ts
Labels: pr: enhancement

#3482 Sort tagified whitelists by label
  src/util/tags.ts
Labels: pr: enhancement

#3484 Remove `data` references from Hazard sheet and adjust GhostTemplate to v10
  src/module/actor/hazard/sheet.ts
  src/module/canvas/ghost-measured-template.ts
  static/templates/actors/hazard/sheet.html
Labels: pr: foundry v10

#3487 Prune foundry `_stats` property in extract.ts
  packs/scripts/extract.ts
Labels: pr: housekeeping

#3490 Add localizations for persistent force damage
  static/lang/re-en.json
Labels: pr: data update

#3488 Fix bonuses and penalties that should only apply to land speed
  packs/data/bestiary-effects.db/effect-entangling-slime.json
  packs/data/bestiary-effects.db/effect-graveknights-curse.json
  packs/data/bestiary-effects.db/effect-rope-snare.json
  packs/data/consumable-effects.db/effect-applereed-mutagen-lesser.json
  packs/data/consumable-effects.db/effect-applereed-mutagen-moderate.json
  packs/data/consumable-effects.db/effect-cheetahs-elixir-greater.json
  packs/data/consumable-effects.db/effect-cheetahs-elixir-lesser.json
  packs/data/consumable-effects.db/effect-cheetahs-elixir-moderate.json
  packs/data/consumable-effects.db/effect-quicksilver-mutagen-greater.json
  packs/data/consumable-effects.db/effect-quicksilver-mutagen-lesser.json
  packs/data/consumable-effects.db/effect-quicksilver-mutagen-major.json
  packs/data/consumable-effects.db/effect-quicksilver-mutagen-moderate.json
  packs/data/consumable-effects.db/effect-stone-body-mutagen-greater.json
  packs/data/consumable-effects.db/effect-stone-body-mutagen-lesser.json
  packs/data/consumable-effects.db/effect-stone-body-mutagen-moderate.json
  packs/data/equipment-effects.db/effect-anklets-of-alacrity.json
  packs/data/equipment-effects.db/effect-bracelet-of-dashing.json
  packs/data/equipment-effects.db/effect-greater-fanged-rune-animal-form.json
  packs/data/equipment-effects.db/effect-mudrock-snare-failure.json
  packs/data/equipment-effects.db/effect-mudrock-snare-success.json
  packs/data/equipment-effects.db/effect-silkspinners-shield-animated-strike.json
  packs/data/equipment-effects.db/effect-tanglefoot-bag-greater.json
  packs/data/equipment-effects.db/effect-tanglefoot-bag-lesser.json
  packs/data/equipment-effects.db/effect-tanglefoot-bag-major.json
  packs/data/equipment-effects.db/effect-tanglefoot-bag-moderate.json
  packs/data/equipment-effects.db/effect-vaultbreakers-harness.json
  packs/data/equipment-effects.db/equipment-effect-south-winds-scorch-song-speed-boost.json
  packs/data/equipment.db/boots-of-bounding-greater.json
  packs/data/equipment.db/boots-of-bounding.json
  packs/data/equipment.db/jerkin-of-liberation.json
  packs/data/feat-effects.db/effect-heroic-recovery.json
  packs/data/feat-effects.db/effect-tillers-drive.json
  packs/data/feats.db/bellflower-dedication.json
  packs/data/feats.db/call-of-elysium.json
  packs/data/feats.db/scamper.json
  packs/data/feats.db/scouts-speed.json
  packs/data/feats.db/swashbucklers-speed.json
  packs/data/feats.db/tillers-drive.json
  packs/data/pathfinder-bestiary.db/lemure.json
  packs/data/pfs-season-2-bestiary.db/murta-kronniksdottir-3-4.json
  packs/data/pfs-season-2-bestiary.db/murta-kronniksdottir-5-6.json
  packs/data/spell-effects.db/spell-effect-accelerating-touch.json
  packs/data/spell-effects.db/spell-effect-blessing-of-defiance-2-action.json
  packs/data/spell-effects.db/spell-effect-necrotize-legs.json
  packs/data/spell-effects.db/spell-effect-shifting-form-speed.json
  packs/data/spell-effects.db/spell-effect-swampcall-critical-failure.json
  packs/data/spell-effects.db/spell-effect-swampcall-failure.json
  packs/data/spell-effects.db/spell-effect-triple-time.json
Labels: pr: data update

#3493 Fix rendering of effect sheet
  src/module/item/effect/sheet.ts
Labels: pr: bugfix

#3495 Add type annotations to some handlebars helpers
  src/scripts/handlebars.ts
Labels: pr: types update

#3496 Fix inline damage on Violent Unleash feat
  packs/data/feats.db/violent-unleash.json
Labels: pr: data update

#3497 Warn if the spell level is moved or prepared to an invalid level
  src/module/actor/sheet/base.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/index.ts
  static/lang/en.json
Labels: pr: enhancement

#3503 Remove legacy code deleting unpersisted skill data and custom modifiers
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#3502 Fix traits of Confident Finisher
  packs/data/actions.db/confident-finisher.json
Labels: pr: data update

#3501 Fix feat type of Corpse Tender archetype feats
  packs/data/feats.db/command-corpse.json
  packs/data/feats.db/corpse-tender-dedication.json
  packs/data/feats.db/corpse-tenders-font.json
  packs/data/feats.db/imbue-mindlessness.json
  packs/data/feats.db/improved-command-corpse.json
Labels: pr: data update

#3504 Set `ItemPF2e#initialized` in the same way as `ActorPF2e#initialized`
  src/module/item/base.ts
Labels: pr: refactor

#3499 Fix the alignment of Spirit Naga
  packs/data/pathfinder-bestiary-2.db/spirit-naga.json
Labels: pr: data update

#3505 Set slugs in modifiers added from @actor/character/strike-weapon-traits
  src/module/actor/character/strike-weapon-traits.ts
Labels: pr: enhancement

#3506 Convert instances of `data.` hiding in backtick'd update strings
  src/module/actor/character/crafting/entry.ts
  src/module/actor/character/index.ts
  src/module/item/abc/sheet.ts
  src/module/item/class/index.ts
  src/module/item/deity/sheet.ts
  src/module/item/physical/sheet.ts
  src/module/item/spell/sheet.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/weapon/sheet.ts
  src/module/migration/migrations/653-aes-to-res.ts
  src/module/migration/migrations/758-prune-pc-attributes.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/crafting/entry.ts
Labels: pr: foundry v10

#3508 Add ESLint rule to enforce array types
  .eslintrc.js
  src/module/actor/sheet/loot/loot-npcs-popup.ts
  src/module/item/base.ts
  src/module/migration/migrations/651-ephemeral-focus-pool.ts
  src/module/migration/migrations/656-other-focus-pool-sources.ts
  src/module/migration/migrations/702-re-formulas-at-instance-level.ts
  src/module/migration/migrations/704-martial-proficiency-re.ts
  src/module/system/settings/menu.ts
  types/foundry/client/config.d.ts
  types/foundry/client/pixi/helpers/ruler.d.ts
  types/foundry/client/roll.d.ts
  types/foundry/common/utils/helpers.d.ts
  types/foundry/common/utils/primitives.d.ts
Labels: pr: housekeeping

#3500 Add Reborn Soul background
  packs/data/backgrounds.db/reborn-soul.json
Labels: pr: data entry
