Repository foundryvtt/pf2e, pull requests merged in 2022-07, with the labels that each got.

#2744 add Fistful of flowers items, PCs and NPCs
  packs/data/equipment.db/sack-of-rotten-fruit.json
  packs/data/one-shot-bestiary.db/bad-vibrations.json
  packs/data/one-shot-bestiary.db/darius.json
  packs/data/one-shot-bestiary.db/grazing-deer.json
  packs/data/one-shot-bestiary.db/meliosas-leshy-golden-bamboo.json
  packs/data/one-shot-bestiary.db/meliosas-leshy-minkaian-honeysuckle-leshy.json
  packs/data/one-shot-bestiary.db/meliosas-leshy-mint-leshy.json
  packs/data/one-shot-bestiary.db/meliosas-leshy-wisteria-leshy.json
  packs/data/one-shot-bestiary.db/meliosas-leshy.json
  packs/data/one-shot-bestiary.db/scented-candle-homunculus.json
  packs/data/paizo-pregens.db/bottlespeaker.json
  packs/data/paizo-pregens.db/fluff-fang.json
  packs/data/paizo-pregens.db/popcorn.json
  packs/data/paizo-pregens.db/reaching-rings.json
  packs/data/paizo-pregens.db/twinsprout.json
  static/licenses/OpenGameLicense.md
Labels: mr::data entry

#2759 Add NPCs from PFS 3-16
  packs/data/pfs-season-3-bestiary.db/cobbled-bruiser.json
  packs/data/pfs-season-3-bestiary.db/cobbled-brutalizer.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-guard.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-mage.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-operative.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-soldier.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-war-mage.json
  packs/data/pfs-season-3-bestiary.db/thomil-bolyrius-3-4.json
  packs/data/pfs-season-3-bestiary.db/thomil-bolyrius-5-6.json
  packs/data/pfs-season-3-bestiary.db/weakened-cobbleswarm.json
Labels: mr::data entry

#2789 Fix roll twice api option for character strikes, add for skills/saves
  src/module/actor/character/index.ts
  src/module/system/statistic/index.ts
Labels: mr::bugfix, mr::enhancement

#2792 Rest macro: Re-render sheet at after all writes have completed
  src/scripts/macros/rest-for-the-night.ts
Labels: mr::bugfix

#2791 Migrate Panache and Vicacious Speed to latest iterations
  packs/data/iconics.db/jirelle-level-1.json
  packs/data/iconics.db/jirelle-level-5.json
  packs/data/paizo-pregens.db/zathri.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/764-panache-vivacious-res.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: mr::data migration

#2794 Refrain from overriding PC alliance if explicitly set
  src/module/actor/character/index.ts
Labels: mr::enhancement

#2795 Release Notes 3.12.2
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: mr::housekeeping

#2803 Replace core Signika font
  src/styles/_fonts.scss
  static/fonts/signika-v19-latin-ext_latin-500.woff2
  static/fonts/signika-v19-latin-ext_latin-600.woff2
  static/fonts/signika-v19-latin-ext_latin-700.woff2
  static/fonts/signika-v19-latin-ext_latin-regular.woff2
Labels: mr::enhancement, ui/ux

#2805 Update system fonts to latest versions
  src/fonts/.gitkeep
  src/fonts/Eczar/eczar.css
  src/styles/_fonts.scss
  src/styles/actor/character/_character.scss
  static/fonts/eczar-v16-latin-ext_latin-500.woff2
  static/fonts/eczar-v16-latin-ext_latin-600.woff2
  static/fonts/eczar-v16-latin-ext_latin-700.woff2
  static/fonts/eczar-v16-latin-ext_latin-800.woff2
  static/fonts/eczar-v16-latin-ext_latin-regular.woff2
  static/fonts/gelasio-v4-latin-500.woff2
  static/fonts/gelasio-v4-latin-500italic.woff2
  static/fonts/gelasio-v4-latin-700.woff2
  static/fonts/gelasio-v4-latin-700italic.woff2
  static/fonts/gelasio-v4-latin-italic.woff2
  static/fonts/gelasio-v4-latin-regular.woff2
  static/fonts/gelasio-v9-latin-ext_latin-500.woff2
  static/fonts/gelasio-v9-latin-ext_latin-500italic.woff2
  static/fonts/gelasio-v9-latin-ext_latin-600.woff2
  static/fonts/gelasio-v9-latin-ext_latin-600italic.woff2
  static/fonts/gelasio-v9-latin-ext_latin-700.woff2
  static/fonts/gelasio-v9-latin-ext_latin-700italic.woff2
  static/fonts/gelasio-v9-latin-ext_latin-italic.woff2
  static/fonts/gelasio-v9-latin-ext_latin-regular.woff2
  static/fonts/la-belle-aurore-v11-latin-regular.woff2
  static/fonts/la-belle-aurore-v16-latin-regular.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-500.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-500italic.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-700.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-700italic.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-900.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-900italic.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-italic.woff2
  static/fonts/roboto-v29-latin-ext_latin_cyrillic-regular.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-500.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-500italic.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-700.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-700italic.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-900.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-900italic.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-italic.woff2
  static/fonts/roboto-v30-latin-ext_latin_cyrillic-regular.woff2
  static/fonts/vollkorn-v13-latin-500.woff2
  static/fonts/vollkorn-v13-latin-700.woff2
  static/fonts/vollkorn-v13-latin-900.woff2
  static/fonts/vollkorn-v13-latin-regular.woff2
  static/fonts/vollkorn-v20-latin-ext_latin_cyrillic-500.woff2
  static/fonts/vollkorn-v20-latin-ext_latin_cyrillic-700.woff2
  static/fonts/vollkorn-v20-latin-ext_latin_cyrillic-900.woff2
  static/fonts/vollkorn-v20-latin-ext_latin_cyrillic-regular.woff2
  static/styles/Eczar-Bold.woff
  static/styles/Eczar-Bold.woff2
  static/styles/Eczar-ExtraBold.woff
  static/styles/Eczar-ExtraBold.woff2
  static/styles/Eczar-Medium.woff
  static/styles/Eczar-Medium.woff2
  static/styles/Eczar-Regular.woff
  static/styles/Eczar-Regular.woff2
  static/styles/Eczar-SemiBold.woff
  static/styles/Eczar-SemiBold.woff2
Labels: mr::enhancement, ui/ux

#2799 Errata of the Blast lance (greater)
  packs/data/equipment.db/blast-lance-greater.json
Labels: mr::data update, source::core rulebooks

#2790 Fix a double info in Cairn linnorm venom
  packs/data/pathfinder-bestiary-2.db/cairn-linnorm.json
Labels: mr::data update, source::core rulebooks

#2798 Delete G&G page references in Blast Lance
  packs/data/equipment.db/blast-lance.json
Labels: mr::data update, source::core rulebooks

#2758 Don't show value for container treasures and fix container alignment
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/scripts/register-templates.ts
  src/styles/actor/_inventory.scss
  src/styles/actor/character/_inventory.scss
  src/styles/actor/hazard/_index.scss
  src/styles/actor/hazard/_legacy.scss
  src/styles/actor/loot/_inventory.scss
  src/styles/actor/npc/_inventory.scss
  src/styles/actor/vehicle/_inventory.scss
  src/styles/legacy/_pf2e.scss
  static/templates/actors/character/tabs/inventory.html
  static/templates/actors/npc/loot-sheet.html
  static/templates/actors/npc/tabs/inventory.html
  static/templates/actors/partials/inventory.html
  static/templates/actors/partials/item-line.html
  static/templates/actors/vehicle/tabs/vehicle-inventory.html
Labels: mr::bugfix, mr::refactor

#2768 Move prepare spellcasting implementation to creature sheet
  src/module/actor/character/sheet.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/creature/types.ts
  src/module/actor/npc/sheet.ts
Labels: mr::housekeeping, mr::refactor

#2780 Standardize Ability Scores Header and use for Feat section
  src/styles/_colors.scss
  src/styles/actor/character/_character.scss
  src/styles/actor/character/_feats.scss
  src/styles/actor/character/_index.scss
  static/lang/en.json
  static/templates/actors/character/tabs/feats.html
  static/templates/actors/character/tabs/general.html
Labels: ui/ux

#2787 Implement Gradual Ability Boosts Variant Rule
  src/global.d.ts
  src/module/actor/character/data/types.ts
  src/module/actor/character/index.ts
  src/module/actor/sheet/popups/ability-builder.ts
  src/module/system/settings/variant-rules.ts
  static/lang/en.json
  static/templates/actors/ability-builder.html
  static/templates/system/settings/variant-rules-settings.html
Labels: mr::enhancement

#2809 Open up grid highlighting for uses other than measured templates
  src/module/canvas/measured-template.ts
Labels: mr::enhancement

#2760 Remove TreatWounds with alt skills setting, the answer is yes
  packs/data/macros.db/treat-wounds.json
  src/module/system/rolls.ts
  src/module/system/settings/index.ts
  src/module/system/statistic/index.ts
  src/scripts/macros/treat-wounds.ts
  src/scripts/set-game-pf2e.ts
  static/lang/en.json
  static/macros/treatwounds.js
Labels: mr::enhancement, mr::housekeeping

#2815 Move several MeasuredTemplatePF2e static methods to helpers file
  src/module/canvas/helpers.ts
  src/module/canvas/measured-template.ts
  src/module/canvas/token.ts
Labels: mr::refactor

#2813 Make Critical Spec saving throws rollable
  static/lang/en.json
Labels: mr::data update

#2816 Fixed typos of Environment
  packs/data/heritages.db/tactile-azarketi.json
  src/scripts/config/index.ts
  static/lang/en.json
Labels: mr::data update

#2822 Fix regression with deleting inventory items
  src/module/actor/sheet/base.ts
Labels: mr::bugfix

#2825 Review B3 - sea dragon spellcasters
  packs/data/pathfinder-bestiary-3.db/adult-sea-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-3.db/ancient-sea-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-3.db/young-sea-dragon-spellcaster.json
Labels: mr::data update, source::core rulebooks

#2826 Rename Living Runes
  packs/data/pathfinder-bestiary-3.db/living-rune-arcane.json
  packs/data/pathfinder-bestiary-3.db/living-rune-divine.json
  packs/data/pathfinder-bestiary-3.db/living-rune-occult.json
  packs/data/pathfinder-bestiary-3.db/living-rune-primal.json
Labels: mr::data update, source::core rulebooks

#2788 Removed superflous expended tag on NPC spell slots
  packs/data/abomination-vaults-bestiary.db/galudu.json
  packs/data/age-of-ashes-bestiary.db/emaliza-zandivar.json
  packs/data/book-of-the-dead-bestiary.db/vetalarana-manipulator.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/juspix-rammel.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/mafika-ayuwari.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/syu-tak-nwa-level-16.json
  packs/data/outlaws-of-alkenstar-bestiary.db/ibrium.json
  packs/data/paizo-pregens.db/lavanna-saltspray.json
  packs/data/pfs-season-1-bestiary.db/blue-streak-mage-7-8.json
  packs/data/pfs-season-3-bestiary.db/advanced-eltha-embercall-9-10-eltha-embercall-11-12.json
  packs/data/pfs-season-3-bestiary.db/eltha-embercall-11-12-28-cp.json
  packs/data/pfs-season-3-bestiary.db/eltha-embercall-9-10.json
Labels: mr::data update

#2819 Correct deadly die size for lances
  packs/data/equipment.db/blast-lance-greater.json
  packs/data/equipment.db/blast-lance.json
  packs/data/equipment.db/knight-captains-lance.json
  packs/data/equipment.db/lance.json
  packs/data/equipment.db/radiant-lance.json
  packs/data/pathfinder-bestiary.db/skeletal-champion.json
  packs/data/pfs-season-1-bestiary.db/flaming-skull-skeletal-champion.json
  packs/data/pfs-season-1-bestiary.db/skeletal-gladiator.json
  packs/data/pfs-season-1-bestiary.db/skeleton-captain.json
  packs/data/pfs-season-3-bestiary.db/bloody-skeletal-champion.json
  packs/data/pfs-season-3-bestiary.db/unstable-skeletal-champion.json
Labels: mr::data update

#2818 Link Effect: Aid to the Aid action
  packs/data/actions.db/aid.json
  packs/data/feature-effects.db/effect-aid.json
Labels: mr::data update

#2808 Localize Persistent Mental Damage
  packs/data/abomination-vaults-bestiary.db/canker-cultist.json
  packs/data/abomination-vaults-bestiary.db/mister-beak.json
  packs/data/abomination-vaults-bestiary.db/morlock-cultist.json
  packs/data/abomination-vaults-bestiary.db/padli.json
  packs/data/abomination-vaults-bestiary.db/urdefhan-blood-mage.json
  packs/data/abomination-vaults-bestiary.db/volluk-azrinae.json
  packs/data/abomination-vaults-bestiary.db/witchfire-warden.json
  packs/data/abomination-vaults-bestiary.db/ysondkhelir.json
  packs/data/age-of-ashes-bestiary.db/crucidaemon.json
  packs/data/bestiary-family-ability-glossary.db/ghost-memento-mori.json
  packs/data/blog-bestiary.db/zhang-yong.json
  packs/data/extinction-curse-bestiary.db/kirosthrek.json
  packs/data/extinction-curse-bestiary.db/shanchek.json
  packs/data/extinction-curse-bestiary.db/xulgath-thoughtmaw.json
  packs/data/extinction-curse-bestiary.db/yaganty.json
  packs/data/feats.db/accursed-claws.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/syu-tak-nwa-level-14.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/syu-tak-nwa-level-16.json
  packs/data/iconics.db/feiya-level-1.json
  packs/data/iconics.db/feiya-level-5.json
  packs/data/malevolence-bestiary.db/architect-and-hunter.json
  packs/data/monsters-of-myth-bestiary.db/somnalu-oculus.json
  packs/data/outlaws-of-alkenstar-bestiary.db/ioton-f6.json
  packs/data/pathfinder-bestiary-2.db/caligni-slayer.json
  packs/data/pathfinder-bestiary-2.db/chernobue.json
  packs/data/pathfinder-bestiary-2.db/cythnigot.json
  packs/data/pathfinder-bestiary-2.db/denizen-of-leng.json
  packs/data/pathfinder-bestiary-2.db/gosreg.json
  packs/data/pathfinder-bestiary-2.db/meladaemon.json
  packs/data/pathfinder-bestiary-2.db/osyluth.json
  packs/data/pathfinder-bestiary-2.db/thulgant.json
  packs/data/pathfinder-bestiary-2.db/witchfire.json
  packs/data/pathfinder-bestiary-2.db/worm-that-walks-cultist.json
  packs/data/pathfinder-bestiary-3.db/duende.json
  packs/data/pathfinder-bestiary-3.db/ghoran-manipulator.json
  packs/data/pathfinder-bestiary-3.db/grioth-cultist.json
  packs/data/pathfinder-bestiary-3.db/grioth-scout.json
  packs/data/pathfinder-bestiary-3.db/ioton.json
  packs/data/pathfinder-bestiary-3.db/munavri-spellblade.json
  packs/data/pathfinder-bestiary-3.db/phantom-beast.json
  packs/data/pathfinder-bestiary-3.db/stheno-harpist.json
  packs/data/pathfinder-bestiary-3.db/xiuh-couatl.json
  packs/data/pathfinder-bestiary.db/dero-magister.json
  packs/data/pathfinder-bestiary.db/lamia-matriarch.json
  packs/data/pfs-season-2-bestiary.db/qxal-the-thorned-monarch.json
  packs/data/pfs-season-2-bestiary.db/teflar.json
  packs/data/spells.db/phantom-pain.json
  packs/data/spells.db/savor-the-sting.json
  packs/data/strength-of-thousands-bestiary.db/formian-mageslayer.json
  packs/data/strength-of-thousands-bestiary.db/formian-queen.json
  packs/data/strength-of-thousands-bestiary.db/king-of-biting-ants.json
  static/lang/re-en.json
Labels: mr::data update

#2806 Add Persistent Damage Notes to Ember Fox Jaws
  packs/data/pathfinder-bestiary-2.db/ember-fox.json
Labels: mr::data update, source::core rulebooks

#2820 Add a rollable button to Terrifying Howl
  packs/data/feats.db/intimidating-prowess.json
  packs/data/feats.db/terrifying-howl.json
Labels: mr::data update

#2821 Audit the Poison Eater (AoE)
  packs/data/agents-of-edgewatch-bestiary.db/poison-eater.json
  packs/data/bestiary-effects.db/effect-poison-frenzy.json
Labels: source::adventure path, mr::data update

#2833 Fix regression with NPC strike generation
  src/module/actor/npc/sheet.ts
Labels: mr::bugfix

#2834 Fix damage dice number on Gaff
  packs/data/equipment.db/gaff.json
  packs/data/pathfinder-bestiary-2.db/marsh-giant.json
Labels: mr::data update

#2835 Update Slayer's Strike Rule Element
  packs/data/feats.db/slayers-strike.json
Labels: mr::data update

#2827 Add Spell School to Roiling Incant name
  packs/data/pathfinder-bestiary-3.db/roiling-incant-evocation.json
  packs/data/rollable-tables.db/hills-dangers.json
Labels: mr::data update, source::core rulebooks

#2837 Add rollable damage buttons per action to the Ring of the Ram
  packs/data/equipment.db/ring-of-the-ram-greater.json
  packs/data/equipment.db/ring-of-the-ram.json
Labels: mr::data update, source::core rulebooks

#2839 Fix Forge Warden shield stats from CR errata 1.
  packs/data/equipment.db/forge-warden.json
Labels: mr::data update

#2838 Fix malformed spell chat message html
  src/styles/legacy/_chat.scss
  static/templates/chat/spell-card.html
Labels: mr::bugfix

#2843 Copy weapon REs when creating NPC attack, add trait for range increment
  src/module/item/melee/data.ts
  src/module/item/weapon/index.ts
Labels: mr::enhancement

#2847 Fix feat double summary rendering
  src/module/actor/sheet/item-summary-renderer.ts
Labels: mr::bugfix

#2836 Add Owb Prophet Forsakens as Deities
  packs/data/deities.db/enkaar-the-malformed-prisoner.json
  packs/data/deities.db/eyes-that-watch.json
  packs/data/deities.db/grasping-iovett.json
  packs/data/deities.db/husk.json
  packs/data/deities.db/lady-razor.json
  packs/data/deities.db/reshmit-of-the-heavy-voice.json
  packs/data/deities.db/thalaphyrr-martyr-minder.json
Labels: mr::data entry, source::core rulebooks

#2850 Remove no-op getter call
  src/module/item/physical/index.ts
Labels: mr::bugfix

#2852 Create new actions sub-navigation (Mats)
  src/styles/actor/_index.scss
  src/styles/actor/character/_index.scss
  src/styles/actor/character/_inventory.scss
  src/styles/actor/tabs/_actions.scss
  src/styles/actor/vehicle/_index.scss
  src/styles/actor/vehicle/_inventory.scss
  static/assets/sheet/sub-nav-decoration.png
  static/templates/actors/character/tabs/actions.html
Labels: ui/ux

#2858 Automate orc feats
  packs/data/feat-effects.db/effect-victorious-vigor.json
  packs/data/feats.db/beast-trainer.json
  packs/data/feats.db/deaths-drums.json
  packs/data/feats.db/fortify-shield.json
  packs/data/feats.db/guided-by-the-stars.json
  packs/data/feats.db/hold-mark.json
  packs/data/feats.db/shed-tail.json
  static/lang/re-en.json
Labels: mr::data update

#2507 Add support for spell variants of spells with a variable cast time
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/chat-message/data.ts
  src/module/chat-message/index.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/sheet/data-types.ts
  src/module/item/spell/data/types.ts
  src/module/item/spell/index.ts
  src/module/item/spell/overlay.ts
  src/module/item/spell/sheet.ts
  src/module/item/spellcasting-entry/index.ts
  static/lang/en.json
  static/templates/actors/spellcasting-spell-list.html
  static/templates/chat/spell-card.html
  static/templates/items/item-sheet.html
  static/templates/items/spell-details.html
  static/templates/items/spell-variant-prompt.html
Labels: mr::new feature

#2861 Fix styling of deity on main tab of PC sheet
  src/styles/actor/character/_character.scss
Labels: mr::bugfix, ui/ux

#2864 Fill in some gaps in CONFIG and ControlsLayer type definitions
  types/foundry/client/config.d.ts
  types/foundry/client/pixi/canvas-layer/controls-layer.d.ts
Labels: mr::types update

#2875 Add "unarmed-damage" as damage selector
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/system/damage/weapon.ts
Labels: mr::bugfix

#2882 Move codemirror imports to separate file with single export
  src/module/item/sheet/base.ts
  src/module/item/sheet/codemirror.ts
Labels: mr::refactor

#2881 Show defenses for beta hazard sheet if there is an AC value
  src/module/actor/hazard/sheet-new.ts
  src/module/actor/hazard/types.ts
  static/template.json
  static/templates/actors/hazard/partials/sidebar.html
Labels: mr::bugfix

#2879 Extend weapon material strike adjustments to NPC attacks
  packs/data/bestiary-effects.db/effect-adaptive-strike.json
  src/module/actor/npc/index.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/system/damage/weapon.ts
  static/lang/en.json
Labels: mr::enhancement

#2883 Distinguish between 0 and null for hazard stealth modifier
  src/module/actor/hazard/data.ts
  src/module/actor/hazard/sheet-new.ts
  src/module/encounter/combatant.ts
Labels: mr::bugfix

#2887 Run extractPacks all
  packs/data/age-of-ashes-bestiary.db/rinnarv-bontimar.json
  packs/data/consumable-effects.db/effect-lastwall-soup.json
  packs/data/equipment.db/animal-staff-greater.json
  packs/data/equipment.db/animal-staff-major.json
  packs/data/equipment.db/animal-staff.json
  packs/data/equipment.db/verdant-staff-greater.json
  packs/data/equipment.db/verdant-staff.json
  packs/data/monsters-of-myth-bestiary.db/mosquito-witch-the-legion-leech.json
  packs/data/monsters-of-myth-bestiary.db/mosquito-witch-the-swarm-seer.json
  packs/data/monsters-of-myth-bestiary.db/mosquito-witch.json
  packs/data/one-shot-bestiary.db/darius.json
  packs/data/pfs-season-2-bestiary.db/quickling-pfs-2-00.json
  packs/data/strength-of-thousands-bestiary.db/kilia-mwibo.json
  packs/scripts/extract.ts
Labels: mr::data update

#2889 Restore loot inventory scrollbar
  src/styles/actor/loot/_inventory.scss
Labels: mr::bugfix

#2854 Condense effects styling and use non-svg header for PC effects
  src/styles/actor/character/_effects.scss
  src/styles/mixins/_effects-list.scss
  static/templates/actors/character/tabs/effects.html
  static/templates/actors/character/tabs/pfs.html
Labels: ui/ux

#2893 Remove pair of unused methods in @actor/sheet/base
  src/module/actor/sheet/base.ts
Labels: mr::housekeeping

#2892 Set baseType property of pregens' Powerful Fist class features
  packs/data/iconics.db/sajan-level-1.json
  packs/data/iconics.db/sajan-level-5.json
  packs/data/paizo-pregens.db/ekene.json
  packs/data/paizo-pregens.db/yacob.json
Labels: mr::data update

#2896 Fix PFS boons styling
  src/styles/actor/character/_pfs.scss
  src/styles/mixins/_effects-list.scss
  static/templates/actors/character/tabs/pfs.html
Labels: mr::bugfix

#2895 Refrain from replacing DocumentSheetConfig with CreatureConfig
  src/module/actor/character/config.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/config.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/npc/config.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/types.ts
  types/foundry/client/application/form-application/document-sheet/base.d.ts
Labels: mr::refactor

#2869 Add basic support for auras that transmit effects to allies
  packs/data/feat-effects.db/effect-marshals-aura.json
  packs/data/feats.db/marshal-dedication.json
  src/module/actor/base.ts
  src/module/actor/creature/index.ts
  src/module/actor/types.ts
  src/module/canvas/effect-area-square.ts
  src/module/canvas/helpers.ts
  src/module/canvas/index.ts
  src/module/canvas/token/aura.ts
  src/module/canvas/token/auras.ts
  src/module/canvas/token/index.ts
  src/module/canvas/token/object.ts
  src/module/item/effect/data.ts
  src/module/item/effect/index.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/aura.ts
  src/module/system/effect-tracker.ts
  src/scripts/hooks/canvas-ready.ts
  static/icons/features/feats/marshals-aura.webp
  static/lang/re-en.json
Labels: mr::new feature

#2898 Fix failure of aura detection from large+ tokens
  src/module/canvas/token/aura.ts
Labels: mr::bugfix

#2811 Add NPCs from PFS 3-19
  packs/data/pfs-season-3-bestiary.db/arisept-7-8.json
  packs/data/pfs-season-3-bestiary.db/arisept-9-10.json
  packs/data/pfs-season-3-bestiary.db/lesser-animate-dream.json
  packs/data/pfs-season-3-bestiary.db/marcien-blakros-7-8-shadow-double.json
  packs/data/pfs-season-3-bestiary.db/marcien-blakros-7-8.json
  packs/data/pfs-season-3-bestiary.db/marcien-blakros-9-10-shadow-double.json
  packs/data/pfs-season-3-bestiary.db/marcien-blakros-9-10.json
  packs/data/pfs-season-3-bestiary.db/onyx-alliance-commander.json
  packs/data/pfs-season-3-bestiary.db/onyx-alliance-officer.json
  packs/data/pfs-season-3-bestiary.db/shadow-spears-7-8.json
  packs/data/pfs-season-3-bestiary.db/shadow-spears-9-10.json
Labels: mr::data entry, source::pathfinder society

#2900 Remove redundant area-effect check on initial canvas-ready call
  src/scripts/hooks/canvas-ready.ts
Labels: mr::bugfix

#2901 Show carried bulk for loot actors
  src/styles/actor/loot/_index.scss
  static/templates/actors/loot/sidebar.html
Labels: mr::enhancement

#2903 Handle ranged attacks with only max range, abort strikes if out of range
  packs/data/feats.db/foxfire.json
  packs/data/feats.db/sprites-spark-draxie.json
  packs/data/feats.db/sprites-spark-firefly-sprite.json
  packs/data/feats.db/sprites-spark-grig.json
  packs/data/feats.db/sprites-spark-melixie.json
  packs/data/feats.db/sprites-spark-nyktera.json
  packs/data/feats.db/sprites-spark-pixie.json
  packs/data/paizo-pregens.db/takemiru.json
  packs/data/pathfinder-bestiary-3.db/kitsune-trickster.json
  src/module/actor/character/index.ts
  src/module/actor/npc/index.ts
  src/module/item/melee/index.ts
  src/module/item/weapon/data/types.ts
  src/module/item/weapon/index.ts
  src/module/rules/rule-element/strike.ts
  static/lang/en.json
Labels: mr::bugfix

#2905 Remove edit/delete/add buttons for hazard actions/strikes in view mode
  static/templates/actors/hazard/sheet-new.html
Labels: ui/ux

#2849 Add or update NPCs from PFS 1-12
  packs/data/pfs-season-1-bestiary.db/barralbus-1-2.json
  packs/data/pfs-season-1-bestiary.db/barralbus-3-4.json
  packs/data/pfs-season-1-bestiary.db/boggard-swampseer-pfs-1-24.json
  packs/data/pfs-season-1-bestiary.db/elite-boggard-swampseer-pfs-1-24-animal-staff.json
  packs/data/pfs-season-1-bestiary.db/great-white-shark-pfs-1-12.json
  packs/data/pfs-season-1-bestiary.db/hungry-blade-apprentice.json
  packs/data/pfs-season-1-bestiary.db/hungry-blade-recruit.json
  packs/data/pfs-season-1-bestiary.db/reefclaw-pfs-1-12.json
  packs/data/pfs-season-1-bestiary.db/submerged-shard.json
Labels: mr::data entry, mr::data update

#2909 Fix speed adjustment on Stoked Flame Stance effect
  packs/data/classfeatures.db/incredible-movement.json
  packs/data/feat-effects.db/stance-stoked-flame-stance.json
Labels: mr::data update

#2917 Send module nags to console in addition to notifications
  src/scripts/hooks/ready.ts
Labels: mr::enhancement

#2919 Auto-adjust current hit points when changing PC level or adding ABC item
  src/module/actor/character/index.ts
  src/module/actor/creature/index.ts
  src/module/actor/creature/types.ts
  src/module/item/abc/index.ts
Labels: mr::enhancement

#2915 Make actions sortable in new hazard sheet, reactions go first
  src/module/actor/hazard/sheet-new.ts
  src/module/actor/hazard/types.ts
  src/styles/actor/hazard/_actions.scss
  static/templates/actors/hazard/sheet-new.html
Labels: mr::enhancement

#2921 Use serif font with action category tabs
  src/styles/actor/character/_index.scss
Labels: ui/ux

#2923 Skip damage modifiers on spells that don't have formulas
  src/module/item/spell/index.ts
Labels: mr::bugfix

#2913 Predicate save bonuses against spells on the item type
  packs/data/backgrounds.db/tech-reliant.json
  packs/data/equipment-effects.db/effect-spellguard-shield.json
  packs/data/equipment.db/staff-of-the-magi.json
  packs/data/feats.db/bloodline-resistance.json
  packs/data/feats.db/pervasive-superstition.json
  packs/data/feats.db/spellmaster-dedication.json
  packs/data/feats.db/spellmasters-resilience.json
  static/lang/re-en.json
Labels: mr::data update

#2924 Automate poppet, ratfolk & shisk feats
  packs/data/actions.db/barbed-quills.json
  packs/data/feats.db/eidetic-ear.json
  packs/data/feats.db/inured-to-the-heat.json
  packs/data/feats.db/lab-rat.json
  packs/data/feats.db/nothing-but-fluff.json
  packs/data/feats.db/piercing-quills.json
  packs/data/feats.db/quill-spray.json
  packs/data/feats.db/ratfolk-lore.json
  packs/data/feats.db/skull-creeper.json
  packs/data/feats.db/tinkering-fingers.json
  packs/data/feats.db/victorious-vigor.json
  packs/data/feats.db/warren-digger.json
  packs/data/feats.db/warren-navigator.json
  packs/data/feats.db/wash-out.json
  packs/data/heritages.db/desert-rat.json
  static/lang/re-en.json
Labels: mr::data update

#2886 Fix malformed HTML in critical-fumble deck
  packs/data/criticaldeck.db/critical-fumble-deck-1.json
  packs/data/criticaldeck.db/critical-fumble-deck-10.json
  packs/data/criticaldeck.db/critical-fumble-deck-11.json
  packs/data/criticaldeck.db/critical-fumble-deck-12.json
  packs/data/criticaldeck.db/critical-fumble-deck-13.json
  packs/data/criticaldeck.db/critical-fumble-deck-14.json
  packs/data/criticaldeck.db/critical-fumble-deck-15.json
  packs/data/criticaldeck.db/critical-fumble-deck-16.json
  packs/data/criticaldeck.db/critical-fumble-deck-17.json
  packs/data/criticaldeck.db/critical-fumble-deck-18.json
  packs/data/criticaldeck.db/critical-fumble-deck-19.json
  packs/data/criticaldeck.db/critical-fumble-deck-2.json
  packs/data/criticaldeck.db/critical-fumble-deck-20.json
  packs/data/criticaldeck.db/critical-fumble-deck-21.json
  packs/data/criticaldeck.db/critical-fumble-deck-22.json
  packs/data/criticaldeck.db/critical-fumble-deck-23.json
  packs/data/criticaldeck.db/critical-fumble-deck-24.json
  packs/data/criticaldeck.db/critical-fumble-deck-25.json
  packs/data/criticaldeck.db/critical-fumble-deck-26.json
  packs/data/criticaldeck.db/critical-fumble-deck-27.json
  packs/data/criticaldeck.db/critical-fumble-deck-28.json
  packs/data/criticaldeck.db/critical-fumble-deck-29.json
  packs/data/criticaldeck.db/critical-fumble-deck-3.json
  packs/data/criticaldeck.db/critical-fumble-deck-30.json
  packs/data/criticaldeck.db/critical-fumble-deck-31.json
  packs/data/criticaldeck.db/critical-fumble-deck-32.json
  packs/data/criticaldeck.db/critical-fumble-deck-33.json
  packs/data/criticaldeck.db/critical-fumble-deck-34.json
  packs/data/criticaldeck.db/critical-fumble-deck-35.json
  packs/data/criticaldeck.db/critical-fumble-deck-36.json
  packs/data/criticaldeck.db/critical-fumble-deck-37.json
  packs/data/criticaldeck.db/critical-fumble-deck-38.json
  packs/data/criticaldeck.db/critical-fumble-deck-39.json
  packs/data/criticaldeck.db/critical-fumble-deck-4.json
  packs/data/criticaldeck.db/critical-fumble-deck-40.json
  packs/data/criticaldeck.db/critical-fumble-deck-41.json
  packs/data/criticaldeck.db/critical-fumble-deck-42.json
  packs/data/criticaldeck.db/critical-fumble-deck-43.json
  packs/data/criticaldeck.db/critical-fumble-deck-44.json
  packs/data/criticaldeck.db/critical-fumble-deck-45.json
  packs/data/criticaldeck.db/critical-fumble-deck-46.json
  packs/data/criticaldeck.db/critical-fumble-deck-47.json
  packs/data/criticaldeck.db/critical-fumble-deck-48.json
  packs/data/criticaldeck.db/critical-fumble-deck-49.json
  packs/data/criticaldeck.db/critical-fumble-deck-5.json
  packs/data/criticaldeck.db/critical-fumble-deck-50.json
  packs/data/criticaldeck.db/critical-fumble-deck-51.json
  packs/data/criticaldeck.db/critical-fumble-deck-52.json
  packs/data/criticaldeck.db/critical-fumble-deck-53.json
  packs/data/criticaldeck.db/critical-fumble-deck-54.json
  packs/data/criticaldeck.db/critical-fumble-deck-6.json
  packs/data/criticaldeck.db/critical-fumble-deck-7.json
Labels: mr::data update

#2927 Fix spell variants check in item summary renderer
  src/module/item/spell/index.ts
Labels: mr::bugfix

#2922 Put feats instead of feat data in actor.featGroups
  src/module/actor/character/data/types.ts
  src/module/actor/character/index.ts
  static/templates/actors/character/tabs/effects.html
  static/templates/actors/character/tabs/feats.html
  static/templates/actors/character/tabs/pfs.html
Labels: mr::refactor

#2930 Automate shoony feats
  packs/data/feats.db/bone-missile.json
  packs/data/feats.db/esteemed-visitor.json
  packs/data/feats.db/handy-with-your-paws.json
  packs/data/feats.db/practiced-paddler.json
  packs/data/feats.db/scamper-underfoot.json
  packs/data/feats.db/shoony-lore.json
  packs/data/feats.db/sodbuster.json
  packs/data/feats.db/unrivaled-builder.json
  packs/data/heritages.db/fishseeker-shoony.json
  static/lang/re-en.json
Labels: mr::data update

#2929 B3 - Add underworld dragon spellcasters
  packs/data/pathfinder-bestiary-3.db/adult-underworld-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-3.db/ancient-underworld-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-3.db/young-underworld-dragon-spellcaster.json
Labels: mr::data entry, source::core rulebooks

#2928 B3 - add sovereign dragon spellcasters
  packs/data/pathfinder-bestiary-3.db/adult-sovereign-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-3.db/ancient-sovereign-dragon-spellcaster.json
  packs/data/pathfinder-bestiary-3.db/young-sovereign-dragon-spellcaster.json
Labels: mr::data entry, source::core rulebooks

#2931 Have extractModifiers call extractModifierAdjustments
  src/module/actor/base.ts
  src/module/actor/character/index.ts
  src/module/actor/creature/index.ts
  src/module/actor/familiar/index.ts
  src/module/actor/hazard/index.ts
  src/module/actor/npc/index.ts
  src/module/actor/vehicle/index.ts
  src/module/item/spell/index.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/util.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/damage/weapon.ts
  src/module/system/statistic/index.ts
  src/module/system/text-editor.ts
Labels: mr::bugfix

#2932 Reduce area-effect checks to single redraw
  src/scripts/hooks/canvas-ready.ts
Labels: mr::bugfix

#2933 Add target item traits as roll options for the Repair action
  src/module/system/action-macros/crafting/repair.ts
Labels: mr::enhancement

#2848 Add NPCs from PFS 1-13
  packs/data/pathfinder-bestiary.db/poltergeist.json
  packs/data/pfs-season-1-bestiary.db/elite-skeletal-giant-pfs-1-18.json
  packs/data/pfs-season-1-bestiary.db/flesh-golem-pfs-1-25.json
  packs/data/pfs-season-1-bestiary.db/guard-pfs-1-17.json
  packs/data/pfs-season-1-bestiary.db/murderous-bathhouse-3-4.json
  packs/data/pfs-season-1-bestiary.db/murderous-bathhouse-5-6.json
  packs/data/pfs-season-1-bestiary.db/palace-guard-pfs-1-17.json
  packs/data/pfs-season-1-bestiary.db/the-ascendant-3-4.json
  packs/data/pfs-season-1-bestiary.db/the-ascendant-5-6.json
  packs/data/pfs-season-1-bestiary.db/unkillable-zombie-brute-pfs-1-13.json
  packs/data/pfs-season-1-bestiary.db/zombie-brute-pfs-1-18.json
  packs/data/pfs-season-2-bestiary.db/fence-pfs-2-00.json
  packs/data/pfs-season-2-bestiary.db/kobold-warrior-pfs-2-11.json
  packs/data/pfs-season-3-bestiary.db/fasiel-ibn-sazadin-1-2.json
  packs/data/pfs-season-3-bestiary.db/fasiel-ibn-sazadin-3-4.json
  packs/data/pfs-season-3-bestiary.db/filth-fire-pfs-3-01.json
  packs/data/pfs-season-3-bestiary.db/grimple-pfs-3-18.json
  packs/data/pfs-season-3-bestiary.db/nuglub-pfs-3-18.json
Labels: mr::data entry, mr::data update

#2853 Update NPCs from PFS 1-10
  packs/data/pfs-season-1-bestiary.db/giant-short-faced-bear.json
  packs/data/pfs-season-1-bestiary.db/lesser-giant-short-faced-bear.json
Labels: mr::data update

#2810 Update NPCs from Extinction Curse Book 3 Adventure Toolbox
  packs/data/extinction-curse-bestiary.db/bugul-noz.json
  packs/data/extinction-curse-bestiary.db/cat-sith.json
  packs/data/extinction-curse-bestiary.db/counteflora.json
  packs/data/extinction-curse-bestiary.db/ginjana-mindkeeper.json
  packs/data/extinction-curse-bestiary.db/herecite-of-zevgavizeb.json
  packs/data/extinction-curse-bestiary.db/shoony-hierarch.json
  packs/data/extinction-curse-bestiary.db/shoony-militia-member.json
  packs/data/extinction-curse-bestiary.db/shoony-tiller.json
  packs/data/extinction-curse-bestiary.db/skarja.json
  packs/data/extinction-curse-bestiary.db/thessekka.json
  packs/data/extinction-curse-bestiary.db/xulgath-stoneliege.json
  packs/data/extinction-curse-bestiary.db/yaganty.json
Labels: source::adventure path, mr::data update

#2939 Remove redundant aura notification, add necessary aura check
  src/module/canvas/token/object.ts
Labels: mr::bugfix

#2943 Remove some accidental handlebars logging
  static/templates/actors/character/tabs/pfs.html
  static/templates/chat/chat-roll-details.html
Labels: mr::housekeeping

#2941 Don't skip basic unarmed attacks in unarmed attack choicesets
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: mr::bugfix

#2938 Correct Sources for #170 Spoken on the Song Wind
  packs/data/strength-of-thousands-bestiary.db/damibwa.json
  packs/data/strength-of-thousands-bestiary.db/froglegs.json
  packs/data/strength-of-thousands-bestiary.db/gbahali.json
  packs/data/strength-of-thousands-bestiary.db/great-grodair.json
  packs/data/strength-of-thousands-bestiary.db/grippli-jinxer.json
  packs/data/strength-of-thousands-bestiary.db/grippli-skirmisher.json
  packs/data/strength-of-thousands-bestiary.db/iiko-dragon.json
  packs/data/strength-of-thousands-bestiary.db/kiru.json
  packs/data/strength-of-thousands-bestiary.db/kolbo.json
  packs/data/strength-of-thousands-bestiary.db/kreekoss.json
  packs/data/strength-of-thousands-bestiary.db/loakan.json
  packs/data/strength-of-thousands-bestiary.db/mashkudu-the-bully.json
  packs/data/strength-of-thousands-bestiary.db/mpeshi.json
  packs/data/strength-of-thousands-bestiary.db/mutated-sewer-ooze.json
  packs/data/strength-of-thousands-bestiary.db/old-thrasher.json
  packs/data/strength-of-thousands-bestiary.db/reth.json
  packs/data/strength-of-thousands-bestiary.db/salathiss.json
  packs/data/strength-of-thousands-bestiary.db/serpentfolk-granitescale.json
  packs/data/strength-of-thousands-bestiary.db/serpentfolk-venom-caller.json
  packs/data/strength-of-thousands-bestiary.db/yorulu.json
Labels: source::adventure path, mr::data update

#2936 Correct sources for Punks in a Powderkeg
  packs/data/outlaws-of-alkenstar-bestiary.db/clockwork-handler.json
  packs/data/outlaws-of-alkenstar-bestiary.db/clockwork-hunter.json
  packs/data/outlaws-of-alkenstar-bestiary.db/dewey-daystar.json
  packs/data/outlaws-of-alkenstar-bestiary.db/follower-of-shumfallow.json
  packs/data/outlaws-of-alkenstar-bestiary.db/glaz-nixbrix.json
  packs/data/outlaws-of-alkenstar-bestiary.db/gold-tank-broker.json
  packs/data/outlaws-of-alkenstar-bestiary.db/gunmarshal.json
  packs/data/outlaws-of-alkenstar-bestiary.db/irkem-dresh.json
  packs/data/outlaws-of-alkenstar-bestiary.db/powderkeg-punk-bombardier.json
  packs/data/outlaws-of-alkenstar-bestiary.db/powderkeg-punk-gunner.json
  packs/data/outlaws-of-alkenstar-bestiary.db/prairie-drake.json
  packs/data/outlaws-of-alkenstar-bestiary.db/roxy.json
  packs/data/outlaws-of-alkenstar-bestiary.db/rust-ooze.json
  packs/data/outlaws-of-alkenstar-bestiary.db/shoma-lyzerius.json
  packs/data/outlaws-of-alkenstar-bestiary.db/sludgespine-killer.json
  packs/data/outlaws-of-alkenstar-bestiary.db/yeast-ooze.json
Labels: source::adventure path, mr::data update

#2945 Add spell variants for heal, harm, heal animal, heal companion
  packs/data/spells.db/harm.json
  packs/data/spells.db/heal-animal.json
  packs/data/spells.db/heal-companion.json
  packs/data/spells.db/heal.json
Labels: mr::data update

#2946 Prevent bonuses to skills from increasing inline DCs improperly
  src/module/system/text-editor.ts
Labels: mr::bugfix

#2944 Automate sprite feats
  packs/data/feats.db/animal-speaker.json
  packs/data/feats.db/catchy-tune.json
  packs/data/feats.db/fey-skin.json
  packs/data/feats.db/heros-wings.json
  packs/data/feats.db/speak-with-bats.json
  packs/data/feats.db/sprites-spark-draxie.json
  packs/data/feats.db/sprites-spark-firefly-sprite.json
  packs/data/feats.db/sprites-spark-grig.json
  packs/data/feats.db/sprites-spark-melixie.json
  packs/data/feats.db/sprites-spark-nyktera.json
  packs/data/feats.db/sprites-spark-pixie.json
  packs/data/feats.db/sprites-spark.json
  packs/data/heritages.db/luminous-sprite.json
  static/lang/re-en.json
Labels: mr::data update

#2862 Update NPCs from PFS 1-08
  packs/data/pfs-season-1-bestiary.db/chops-1-2.json
  packs/data/pfs-season-1-bestiary.db/chops-3-4.json
  packs/data/pfs-season-1-bestiary.db/elite-rebel.json
  packs/data/pfs-season-1-bestiary.db/elite-waterworks-rebel.json
  packs/data/pfs-season-1-bestiary.db/guard-captain.json
  packs/data/pfs-season-1-bestiary.db/guard.json
  packs/data/pfs-season-1-bestiary.db/harsus-1-2.json
  packs/data/pfs-season-1-bestiary.db/harsus-3-4.json
  packs/data/pfs-season-1-bestiary.db/nalla-rebel-leader-1-2.json
  packs/data/pfs-season-1-bestiary.db/nalla-rebel-leader-3-4.json
  packs/data/pfs-season-1-bestiary.db/quagmire.json
  packs/data/pfs-season-1-bestiary.db/rebel-brute.json
  packs/data/pfs-season-1-bestiary.db/rebel.json
  packs/data/pfs-season-1-bestiary.db/treacherous-quagmire.json
  packs/data/pfs-season-1-bestiary.db/veteran-guard-captain.json
  packs/data/pfs-season-1-bestiary.db/vigilant-guard.json
  packs/data/pfs-season-1-bestiary.db/waterworks-rebel.json
  packs/data/pfs-season-1-bestiary.db/weak-spider-swarm.json
Labels: mr::data update

#2957 Fix homebrew input height scaling when multiple lines long
  src/styles/settings/_homebrew.scss
Labels: mr::bugfix

#2961 Add a secret focus cap property that can be overwritten by REs/modules
  src/module/actor/character/data/types.ts
  src/module/actor/character/index.ts
Labels: mr::enhancement

#2966 Fix regression with scroll position on tabbed content
  src/module/actor/character/sheet.ts
Labels: mr::bugfix

#2874 Add NPCs from PFS 3-99 (Tier 1-2)
  packs/data/pfs-season-3-bestiary.db/animated-blade-pfs-3-99.json
  packs/data/pfs-season-3-bestiary.db/cog-the-torchbearer.json
  packs/data/pfs-season-3-bestiary.db/displaced-robot-1-2.json
  packs/data/pfs-season-3-bestiary.db/eternal-hall-1-2.json
  packs/data/pfs-season-3-bestiary.db/fipp-the-prophet.json
  packs/data/pfs-season-3-bestiary.db/firespark-trap-1-2.json
  packs/data/pfs-season-3-bestiary.db/junk-launcher.json
  packs/data/pfs-season-3-bestiary.db/kobold-warrior-pfs-3-99.json
  packs/data/pfs-season-3-bestiary.db/overloading-arch-1-2.json
  packs/data/pfs-season-3-bestiary.db/poisoned-dart-trap-1-2.json
  packs/data/pfs-season-3-bestiary.db/pup-of-tindalos.json
  packs/data/pfs-season-3-bestiary.db/temporal-echoes-1-2.json
  packs/data/pfs-season-3-bestiary.db/timewarped-amalgam.json
  packs/data/pfs-season-3-bestiary.db/young-arabuk.json
Labels: mr::data entry, source::pathfinder society

#2868 Add or update NPCs from PFS 1-04
  packs/data/pfs-season-1-bestiary.db/animal-companion-wolf-1-2.json
  packs/data/pfs-season-1-bestiary.db/animal-companion-wolf-3-4.json
  packs/data/pfs-season-1-bestiary.db/ankle-trap-1-2.json
  packs/data/pfs-season-1-bestiary.db/ankle-trap-3-4.json
  packs/data/pfs-season-1-bestiary.db/deadfall-trap-1-2.json
  packs/data/pfs-season-1-bestiary.db/deadfall-trap-3-4.json
  packs/data/pfs-season-1-bestiary.db/frog-swarm.json
  packs/data/pfs-season-1-bestiary.db/giant-osprey.json
  packs/data/pfs-season-1-bestiary.db/halfling-druid-1-2.json
  packs/data/pfs-season-1-bestiary.db/halfling-druid-3-4.json
  packs/data/pfs-season-1-bestiary.db/osprey.json
  packs/data/pfs-season-1-bestiary.db/rabid-squirrel-swarm.json
  packs/data/pfs-season-1-bestiary.db/reefclaw-spawn.json
  packs/data/pfs-season-1-bestiary.db/squirrel-swarm-1-04.json
  packs/data/pfs-season-1-bestiary.db/vengeant-thorn-1-2.json
  packs/data/pfs-season-1-bestiary.db/vengeant-thorn-3-4.json
Labels: mr::data entry, mr::data update

#2907 Add NPCs from PFS 3-99 Tier 3-4
  packs/data/pfs-season-3-bestiary.db/animated-full-plate-pfs-3-99.json
  packs/data/pfs-season-3-bestiary.db/cog-the-ruffian.json
  packs/data/pfs-season-3-bestiary.db/displaced-robot-3-4.json
  packs/data/pfs-season-3-bestiary.db/elite-green-hag-pfs-3-99.json
  packs/data/pfs-season-3-bestiary.db/eternal-hall-3-4.json
  packs/data/pfs-season-3-bestiary.db/firespark-trap-3-4.json
  packs/data/pfs-season-3-bestiary.db/kobold-dragon-mage-pfs-3-99.json
  packs/data/pfs-season-3-bestiary.db/kobold-scout-pfs-3-99.json
  packs/data/pfs-season-3-bestiary.db/overloading-arch-3-4.json
  packs/data/pfs-season-3-bestiary.db/poisoned-dart-trap-3-4.json
  packs/data/pfs-season-3-bestiary.db/rock-launcher.json
  packs/data/pfs-season-3-bestiary.db/temporal-echoes-3-4.json
Labels: mr::data entry, source::pathfinder society

#2951 Add spell variants for damage spells with variable cast times
  packs/data/spells.db/concordant-choir.json
  packs/data/spells.db/elemental-annihilation-wave.json
  packs/data/spells.db/horizon-thunder-sphere.json
  packs/data/spells.db/inner-radiance-torrent.json
  packs/data/spells.db/ki-blast.json
  packs/data/spells.db/rip-the-spirit.json
  packs/data/spells.db/wronged-monks-wrath.json
Labels: mr::data update

#2970 Update and rename flensing-trap.json to flensing-trap-7-8.json
  packs/data/pfs-season-3-bestiary.db/flensing-trap-7-8.json
Labels: mr::data update

#2908 Add NPCs and Hazards from PFS 3-99 Tier 5-6
  packs/data/pfs-season-3-bestiary.db/arabuk-yearling.json
  packs/data/pfs-season-3-bestiary.db/arabuk.json
  packs/data/pfs-season-3-bestiary.db/bergworm.json
  packs/data/pfs-season-3-bestiary.db/bloodletting-scythe-blade.json
  packs/data/pfs-season-3-bestiary.db/displaced-robot-5-6.json
  packs/data/pfs-season-3-bestiary.db/eternal-hall-5-6.json
  packs/data/pfs-season-3-bestiary.db/flensing-trap-5-6.json
  packs/data/pfs-season-3-bestiary.db/overloading-arch-5-6.json
  packs/data/pfs-season-3-bestiary.db/reckless-akitonian-scientist.json
  packs/data/pfs-season-3-bestiary.db/shobhad-hunter-5-6.json
  packs/data/pfs-season-3-bestiary.db/temporal-echoes-5-6.json
Labels: mr::data entry, source::pathfinder society

#2953 Expand choice set owned items to non-weapons
  packs/scripts/run-migration.ts
  src/module/item/base.ts
  src/module/migration/migrations/765-choice-owned-item-types.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: mr::enhancement

#2974 Fix malformed HTML in critical-hit deck
  packs/data/criticaldeck.db/critical-fumble-deck-8.json
  packs/data/criticaldeck.db/critical-fumble-deck-9.json
  packs/data/criticaldeck.db/critical-hit-deck-1.json
  packs/data/criticaldeck.db/critical-hit-deck-10.json
  packs/data/criticaldeck.db/critical-hit-deck-11.json
  packs/data/criticaldeck.db/critical-hit-deck-12.json
  packs/data/criticaldeck.db/critical-hit-deck-13.json
  packs/data/criticaldeck.db/critical-hit-deck-14.json
  packs/data/criticaldeck.db/critical-hit-deck-15.json
  packs/data/criticaldeck.db/critical-hit-deck-16.json
  packs/data/criticaldeck.db/critical-hit-deck-17.json
  packs/data/criticaldeck.db/critical-hit-deck-18.json
  packs/data/criticaldeck.db/critical-hit-deck-19.json
  packs/data/criticaldeck.db/critical-hit-deck-2.json
  packs/data/criticaldeck.db/critical-hit-deck-20.json
  packs/data/criticaldeck.db/critical-hit-deck-21.json
  packs/data/criticaldeck.db/critical-hit-deck-22.json
  packs/data/criticaldeck.db/critical-hit-deck-23.json
  packs/data/criticaldeck.db/critical-hit-deck-24.json
  packs/data/criticaldeck.db/critical-hit-deck-25.json
  packs/data/criticaldeck.db/critical-hit-deck-26.json
  packs/data/criticaldeck.db/critical-hit-deck-27.json
  packs/data/criticaldeck.db/critical-hit-deck-28.json
  packs/data/criticaldeck.db/critical-hit-deck-29.json
  packs/data/criticaldeck.db/critical-hit-deck-3.json
  packs/data/criticaldeck.db/critical-hit-deck-30.json
  packs/data/criticaldeck.db/critical-hit-deck-31.json
  packs/data/criticaldeck.db/critical-hit-deck-32.json
  packs/data/criticaldeck.db/critical-hit-deck-33.json
  packs/data/criticaldeck.db/critical-hit-deck-34.json
  packs/data/criticaldeck.db/critical-hit-deck-35.json
  packs/data/criticaldeck.db/critical-hit-deck-36.json
  packs/data/criticaldeck.db/critical-hit-deck-37.json
  packs/data/criticaldeck.db/critical-hit-deck-38.json
  packs/data/criticaldeck.db/critical-hit-deck-39.json
  packs/data/criticaldeck.db/critical-hit-deck-4.json
  packs/data/criticaldeck.db/critical-hit-deck-40.json
  packs/data/criticaldeck.db/critical-hit-deck-41.json
  packs/data/criticaldeck.db/critical-hit-deck-42.json
  packs/data/criticaldeck.db/critical-hit-deck-43.json
  packs/data/criticaldeck.db/critical-hit-deck-44.json
  packs/data/criticaldeck.db/critical-hit-deck-45.json
  packs/data/criticaldeck.db/critical-hit-deck-46.json
  packs/data/criticaldeck.db/critical-hit-deck-47.json
  packs/data/criticaldeck.db/critical-hit-deck-48.json
  packs/data/criticaldeck.db/critical-hit-deck-49.json
  packs/data/criticaldeck.db/critical-hit-deck-5.json
  packs/data/criticaldeck.db/critical-hit-deck-50.json
  packs/data/criticaldeck.db/critical-hit-deck-51.json
  packs/data/criticaldeck.db/critical-hit-deck-52.json
  packs/data/criticaldeck.db/critical-hit-deck-53.json
  packs/data/criticaldeck.db/critical-hit-deck-54.json
  packs/data/criticaldeck.db/critical-hit-deck-6.json
  packs/data/criticaldeck.db/critical-hit-deck-7.json
  packs/data/criticaldeck.db/critical-hit-deck-8.json
  packs/data/criticaldeck.db/critical-hit-deck-9.json
Labels: mr::data update

#2955 Implement Roll Note RE Editor
  src/module/item/deity/sheet.ts
  src/module/item/feat/sheet.ts
  src/module/item/sheet/base.ts
  src/module/item/sheet/data-types.ts
  src/module/item/sheet/rule-elements.ts
  src/scripts/register-templates.ts
  src/styles/item/_rules.scss
  src/util/tags.ts
  static/lang/re-en.json
  static/templates/items/rules-panel.html
  static/templates/items/rules/default.html
  static/templates/items/rules/note.html
Labels: mr::enhancement, mr::new feature

#2979 Ensure unique actors are checked for aura effects
  src/module/actor/base.ts
  src/module/canvas/token/auras.ts
Labels: mr::bugfix

#2981 Add definition of CanvasHistory interface
  types/foundry/client/pixi/placeables-layer/base.d.ts
Labels: mr::types update

#2965 Add Clockwork Reanimator archetype feats
  packs/data/feats.db/advanced-reanimated-companion.json
  packs/data/feats.db/clockwork-reanimator-dedication.json
  packs/data/feats.db/hijack-undead.json
  packs/data/feats.db/improved-hijack-undead.json
  packs/data/feats.db/incredible-reanimated-companion.json
  packs/data/feats.db/its-alive.json
  packs/data/feats.db/paragon-reanimated-companion.json
  packs/data/feats.db/self-destruct.json
  packs/data/feats.db/unwind-death.json
  packs/data/feats.db/zombie-horde.json
Labels: mr::data entry

#2985 Run up to migration 765 on current compendia
  packs/data/pfs-season-3-bestiary.db/arabuk.json
  packs/data/pfs-season-3-bestiary.db/cog-the-torchbearer.json
  packs/data/pfs-season-3-bestiary.db/mature-arabuk.json
Labels: mr::data migration

#2997 Fix display of consumable charges on sheet
  src/module/item/consumable/index.ts
  src/scripts/macros/rest-for-the-night.ts
  static/templates/actors/partials/item-line.html
Labels: mr::bugfix

#3002 Fix and localize IWR exceptions and placeholder text
  static/lang/en.json
  static/templates/actors/trait-selector.html
  static/templates/system/trait-selector/resistances.html
Labels: mr::bugfix

#2920 Refactor feat group assignment into feat categories
  src/module/actor/character/data/sheet.ts
  src/module/actor/character/data/types.ts
  src/module/actor/character/feats.ts
  src/module/actor/character/index.ts
  src/module/actor/character/sheet.ts
  src/module/item/class/index.ts
  src/module/item/feat/index.ts
  static/templates/actors/character/tabs/feats.html
Labels: mr::refactor

#3005 Add unspecific signature overloads to Scene embedded CRUD callbacks
  types/foundry/client/documents/scene.d.ts
Labels: mr::types update

#3009 Recheck auras whenever an actor has an owned item change
  src/module/scene/document.ts
  src/module/scene/token-document/document.ts
Labels: mr::bugfix

#3007 Improve feat drag/drop and handle invalid feat drops
  src/module/actor/character/feats.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/styles/actor/character/_feats.scss
  static/lang/en.json
  static/templates/actors/character/tabs/feats.html
Labels: ui/ux

#3011 Sort roll options from ActorPF2e#getRollOptions and strike attack rolls
  src/module/actor/base.ts
  src/module/actor/character/index.ts
Labels: mr::enhancement

#3012 Use source token coordinates when checking aura proximities
  src/module/canvas/token/aura/map.ts
  src/module/scene/document.ts
  src/module/scene/token-document/aura/index.ts
  src/module/scene/token-document/document.ts
Labels: mr::bugfix

#3016 Remove aura effects on token deletion
  src/module/actor/base.ts
  src/module/scene/document.ts
  src/module/scene/token-document/document.ts
Labels: mr::bugfix

#3019 Use distinct icon for generate-npc-attack button
  src/module/actor/npc/sheet.ts
  static/templates/actors/partials/item-line.html
Labels: ui/ux

#3020 Set FA icons to fixed-width in a few places on PC and NPC sheets
  src/styles/actor/_index.scss
  src/styles/actor/character/_feats.scss
  src/styles/actor/npc/_inventory.scss
  src/styles/actor/tabs/_actions.scss
  static/templates/actors/character/partials/granted-feat.html
  static/templates/actors/character/tabs/actions.html
  static/templates/actors/character/tabs/feats.html
  static/templates/actors/npc/partials/action.html
  static/templates/actors/npc/partials/attack.html
  static/templates/actors/partials/inventory.html
Labels: ui/ux

#2994 Update missed actionCategories from PFS 3-99 NPCs
  packs/data/pfs-season-3-bestiary.db/bergworm-tyrant.json
  packs/data/pfs-season-3-bestiary.db/shobhad-hunter-7-8.json
Labels: mr::data update, source::pathfinder society

#3021 Avoid aberrant behavior when two tokens of single actor emit auras
  src/module/scene/document.ts
Labels: mr::bugfix

#2992 Add NPCs and hazards from Tier 1-2 of PFS 3-98
  packs/data/pathfinder-bestiary.db/duergar-bombardier.json
  packs/data/pfs-season-3-bestiary.db/aspis-defender.json
  packs/data/pfs-season-3-bestiary.db/aspis-recruit.json
  packs/data/pfs-season-3-bestiary.db/aspis-usurper.json
  packs/data/pfs-season-3-bestiary.db/carved-mourner.json
  packs/data/pfs-season-3-bestiary.db/faulty-tidal-controls.json
  packs/data/pfs-season-3-bestiary.db/giant-amoeba-pfs-3-98.json
  packs/data/pfs-season-3-bestiary.db/giant-rat-pfs-3-98.json
  packs/data/pfs-season-3-bestiary.db/half-formed-abrikandilu.json
  packs/data/pfs-season-3-bestiary.db/skeleton-warrior.json
  packs/data/pfs-season-3-bestiary.db/tilting-floor.json
  packs/data/pfs-season-3-bestiary.db/tombstone-door.json
  packs/data/pfs-season-3-bestiary.db/trip-wire.json
  packs/data/pfs-season-3-bestiary.db/unstable-column-1-2.json
  packs/data/pfs-season-3-bestiary.db/wailing-ghost.json
  static/icons/pathfinder-society/aspis-consortium.webp
  static/icons/pathfinder-society/envoys-alliance.webp
  static/icons/pathfinder-society/grand-archive.webp
  static/icons/pathfinder-society/horizon-hunters.webp
  static/icons/pathfinder-society/radiant-oath.webp
  static/icons/pathfinder-society/verdant-wheel.webp
  static/icons/pathfinder-society/vigilant-shield.webp
  static/licenses/OpenGameLicense.md
Labels: mr::data entry, mr::data update, source::pathfinder society

#2987 Add Visual trait to Hazard actors and Apocryphal Subdomains
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: mr::data update

#3025 Move PC hit-point overage handling to base item class
  src/module/item/abc/index.ts
  src/module/item/base.ts
Labels: mr::enhancement

#3026 Refactor spellcasting entry create/edit to use FormApplication
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/util/misc.ts
  static/lang/en.json
  static/templates/actors/spellcasting-dialog.html
Labels: mr::refactor

#2996 Add NPCs and Hazards from PFS 3-98 Tier 5-6
  packs/data/pathfinder-bestiary.db/ochre-jelly.json
  packs/data/pfs-season-3-bestiary.db/anguished-tombstone-door.json
  packs/data/pfs-season-3-bestiary.db/aspis-bulwark.json
  packs/data/pfs-season-3-bestiary.db/aspis-oppressor.json
  packs/data/pfs-season-3-bestiary.db/aspis-striker.json
  packs/data/pfs-season-3-bestiary.db/grieving-carved-mourner.json
  packs/data/pfs-season-3-bestiary.db/mutated-brown-mold.json
  packs/data/pfs-season-3-bestiary.db/precarious-sliding-floor.json
  packs/data/pfs-season-3-bestiary.db/raseri-kanton-skeleton.json
  packs/data/pfs-season-3-bestiary.db/severing-trip-wire.json
  packs/data/pfs-season-3-bestiary.db/unstable-column-5-6.json
  packs/data/pfs-season-3-bestiary.db/volatile-tidal-controls.json
Labels: mr::data entry, mr::data update, source::pathfinder society

#2999 Update Kelorbeyan Guard Longsword attack modifier.
  packs/data/one-shot-bestiary.db/kelorbeyan-guard.json
Labels: mr::data update

#3031 Fix "move" wall restriction type in collision testing
  src/module/canvas/helpers.ts
  src/module/canvas/token/aura/util.ts
  types/foundry/client/pixi/placeables-layer/walls-layer.d.ts
  types/foundry/common/constants.d.ts
Labels: mr::bugfix

#3028 Fix Treat Wounds macro
  src/scripts/macros/treat-wounds.ts
Labels: mr::bugfix

#3030 Add fa-fw class to more Font Awesome icons on PC sheet
  src/styles/actor/_spell-list.scss
  src/styles/actor/character/_feats.scss
  src/styles/actor/character/_proficiencies.scss
  src/styles/actor/character/_spellcasting.scss
  static/templates/actors/character/sheet.html
  static/templates/actors/character/tabs/actions.html
  static/templates/actors/character/tabs/crafting.html
  static/templates/actors/character/tabs/effects.html
  static/templates/actors/character/tabs/feats.html
  static/templates/actors/character/tabs/general.html
  static/templates/actors/character/tabs/pfs.html
  static/templates/actors/character/tabs/proficiencies.html
  static/templates/actors/character/tabs/spellcasting.html
  static/templates/actors/spellcasting-spell-list.html
Labels: ui/ux

#3003 update elemental form to properly size non-medium creates.
  packs/data/spell-effects.db/spell-effect-elemental-form-air.json
  packs/data/spell-effects.db/spell-effect-elemental-form-earth.json
  packs/data/spell-effects.db/spell-effect-elemental-form-fire.json
  packs/data/spell-effects.db/spell-effect-elemental-form-water.json
Labels: mr::data update

#3035 Fix regression with dragging feat to token
  src/module/actor/character/sheet.ts
Labels: mr::bugfix

#2995 Add NPCs and Hazards from PFS 3-98 Tier 3-4
  packs/data/pfs-season-3-bestiary.db/aspis-agent.json
  packs/data/pfs-season-3-bestiary.db/aspis-enforcer.json
  packs/data/pfs-season-3-bestiary.db/aspis-warden.json
  packs/data/pfs-season-3-bestiary.db/duergar-crusher.json
  packs/data/pfs-season-3-bestiary.db/enhanced-brown-mold.json
  packs/data/pfs-season-3-bestiary.db/lacerating-trip-wire.json
  packs/data/pfs-season-3-bestiary.db/malfunctioning-tidal-controls.json
  packs/data/pfs-season-3-bestiary.db/sliding-floor.json
  packs/data/pfs-season-3-bestiary.db/sorrowful-tombstone-door.json
  packs/data/pfs-season-3-bestiary.db/unstable-column-3-4.json
  packs/data/pfs-season-3-bestiary.db/weeping-carved-mourner.json
Labels: mr::data entry, source::pathfinder society

#2978 Add Blade Launcher from Guns & Gears
  packs/data/equipment.db/blade-launcher.json
Labels: mr::data entry

#3036 Add field property to RE brackets in Girzanje's March effect
  packs/data/spell-effects.db/spell-effect-girzanjes-march.json
Labels: mr::data update

#2998 correct prerequisites in Named artillery
  packs/data/feats.db/named-artillery.json
Labels: mr::data update

#3032 Re-prepare token data when updating actor alliance
  src/module/actor/base.ts
Labels: mr::bugfix

#3038 Show notification for newly added feats
  src/module/actor/character/feats.ts
  static/lang/en.json
Labels: ui/ux

#3039 Fix regression with archetype and bonus feat slots
  src/module/actor/character/feats.ts
Labels: mr::bugfix

#3040 Attempt to find best slot when dropping feat in invalid or no slot
  src/module/actor/character/feats.ts
Labels: mr::enhancement

#3034 Add configuration for NPC auto heighten
  src/module/actor/sheet/spellcasting-dialog.ts
  static/lang/en.json
  static/templates/actors/spellcasting-dialog.html
Labels: mr::enhancement

#3044 Add icons for abysium chunk and ingot, bring hue of powder in line
  packs/data/equipment.db/abysium-chunk.json
  packs/data/equipment.db/abysium-ingot.json
  static/icons/equipment/alchemical-items/alchemical-poisons/abysium-powder.webp
  static/icons/equipment/materials/abysium-chunk.webp
  static/icons/equipment/materials/abysium-ingot.webp
Labels: mr::data update

#3050 Clean up and consolidate CRB-style action and inventory tabs
  src/styles/actor/_coinage.scss
  src/styles/actor/_index.scss
  src/styles/actor/_inventory.scss
  src/styles/actor/character/_actions.scss
  src/styles/actor/character/_crafting.scss
  src/styles/actor/character/_index.scss
  src/styles/actor/character/_inventory.scss
  src/styles/actor/tabs/_actions.scss
  src/styles/actor/tabs/_bio.scss
  src/styles/actor/vehicle/_index.scss
  src/styles/actor/vehicle/_inventory.scss
  static/templates/actors/character/tabs/actions.html
  static/templates/actors/loot/inventory.html
  static/templates/actors/partials/coinage.html
  static/templates/actors/vehicle/tabs/vehicle-actions.html
  static/templates/actors/vehicle/tabs/vehicle-description.html
  static/templates/actors/vehicle/tabs/vehicle-details.html
  static/templates/actors/vehicle/tabs/vehicle-inventory.html
Labels: ui/ux

#3051 Tweak padding between action/inventory lists and scrollbar
  src/styles/actor/_inventory.scss
  src/styles/actor/tabs/_actions.scss
Labels: ui/ux

#3052 Move RuleElementSynthetics to own file
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/index.ts
  src/module/rules/rule-element/multiple-attack-penalty.ts
  src/module/rules/rule-element/roll-twice.ts
  src/module/rules/rule-element/striking.ts
  src/module/rules/rule-element/weapon-potency.ts
  src/module/rules/synthetics.ts
  src/module/rules/util.ts
  src/module/system/check-modifiers-dialog.ts
  src/module/system/damage/weapon.ts
  src/module/system/rolls.ts
Labels: mr::housekeeping

#3048 Add frequency and display to actions and feats in the character sheet
  src/module/actor/creature/sheet.ts
  src/module/actor/creature/types.ts
  src/module/item/action/data.ts
  src/module/item/action/index.ts
  src/module/item/action/sheet.ts
  src/module/item/data/base.ts
  src/module/item/feat/data.ts
  src/module/item/feat/index.ts
  src/module/item/feat/sheet.ts
  src/module/item/physical/data.ts
  src/module/item/physical/sheet.ts
  src/module/item/sheet/data-types.ts
  src/scripts/macros/rest-for-the-night.ts
  src/styles/actor/character/_actions.scss
  src/styles/item/_activations.scss
  src/styles/item/_index.scss
  static/lang/en.json
  static/templates/actors/character/tabs/actions.html
  static/templates/items/action-details.html
  static/templates/items/activation-panel.html
  static/templates/items/feat-details.html
Labels: mr::new feature
