Repository foundryvtt/pf2e, pull requests merged in 2023-06, with the labels that each got.

#8079 Fix effect for Heartripper Blade. Add link from weapon to effect.
  packs/data/equipment-effects.db/effect-heartripper-blade.json
  packs/data/equipment.db/heartripper-blade.json
Labels: pr: data update

#8075 Correct several data fields in Acrobat's Staff
  packs/data/equipment.db/acrobats-staff.json
Labels: pr: data update

#8076 Fix spelling mistake in Pit of Toil
  packs/data/crown-of-the-kobold-king-bestiary.db/pit-of-toil.json
Labels: pr: data update

#8077 Add rule elements to Tallow Guardian's Melt
  packs/data/crown-of-the-kobold-king-bestiary.db/tallow-guardian.json
Labels: pr: data update

#8078 Add rule elements to Festrog's On All Fours
  packs/data/pathfinder-bestiary-3.db/festrog.json
Labels: pr: data update

#8082 Fix item:base roll option for NPC attacks with linked weapon
  src/module/item/melee/document.ts
Labels: pr: bugfix

#8085 Fix missing extreme for Curse of Living Death and Curse of the Hero's Burden
  packs/data/feat-effects.db/effect-curse-of-living-death.json
  packs/data/feat-effects.db/effect-curse-of-the-heros-burden.json
Labels: pr: data update

#8087 Fix base damagetype and diesize lookup for 0 base damage
  src/module/item/affliction/document.ts
  src/module/item/spell/document.ts
  src/module/item/spell/helpers.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/types.ts
Labels: pr: bugfix

#8088 Explicitly allow damage dice overrides of zero `diceNumber`
  src/module/rules/rule-element/damage-dice.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix, pr: enhancement

#8059 Add Affinity Ablaze actions
  packs/data/adventure-specific-actions.db/affinity-ablaze-arms-of-balance-walking-the-cardinal-paths.json
  packs/data/adventure-specific-actions.db/affinity-ablaze-biting-roses-glimpses-to-beyond.json
  packs/data/adventure-specific-actions.db/affinity-ablaze-speakers-to-the-winds-all-is-one-one-is-all.json
  packs/data/adventure-specific-actions.db/affinity-ablaze-steps-of-the-sun-grand-harmony.json
  packs/data/adventure-specific-actions.db/affinity-ablaze-winters-roar-rampaging-glacier-charge.json
  packs/data/feat-effects.db/effect-walking-the-cardinal-paths.json
Labels: source: adventure path, pr: data entry

#8091 Fix retrieval of origin actor from inline saving throws
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#8080 Fix breakdown data of NPC land speeds
  src/module/actor/npc/document.ts
  src/module/actor/npc/sheet.ts
Labels: pr: bugfix

#8089 Fix strikes for weapons lacking "base" damage
  src/module/item/melee/document.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#8090 Remove equipment activation data
  packs/data/equipment.db/tallow-bomb-greater.json
  packs/data/equipment.db/tallow-bomb-major.json
  packs/data/equipment.db/tallow-bomb-moderate.json
  packs/data/equipment.db/twigjack-sack-greater.json
  packs/data/equipment.db/twigjack-sack-lesser.json
  packs/data/equipment.db/twigjack-sack-major.json
  packs/data/equipment.db/twigjack-sack-moderate.json
  packs/data/pfs-season-3-bestiary.db/tyrannical-interrogator.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/ardissa-prendergant.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/pakano.json
Labels: pr: data update

#8093 Correct success message for Wellspring Surge to be 3 rounds
  static/lang/re-en.json
Labels: pr: data update

#8081 Update rule elements for Urbel
  packs/data/strength-of-thousands-bestiary.db/urbel.json
Labels: pr: data update

#8083 Add rule elements for Brute Strength and Trident Bully
  packs/data/strength-of-thousands-bestiary.db/abendego-brute.json
  packs/data/strength-of-thousands-bestiary.db/ajbal-kimon.json
  packs/data/strength-of-thousands-bestiary.db/bharlen-sajor.json
Labels: pr: data update

#8096 Bump system version, update NPM deps, and declare V11 compatibility
  .eslintrc.json
  package-lock.json
  package.json
  src/global.d.ts
  src/module/canvas/layer/template.ts
  src/module/canvas/measured-template.ts
  src/module/canvas/token/object.ts
  static/system.json
  tsconfig.json
  types/foundry/client/index.d.ts
  types/foundry/client/pixi/canvas-layer/controls-layer.d.ts
  types/foundry/client/pixi/canvas.d.ts
  types/foundry/client/pixi/helpers/door-control.d.ts
  types/foundry/client/pixi/helpers/resize-handle.d.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/layers/controls/ruler.d.ts
  types/foundry/client/pixi/placeable-object/ambient-light.d.ts
  types/foundry/client/pixi/placeable-object/ambient-sound.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/client/pixi/placeable-object/measured-template.d.ts
  types/foundry/client/pixi/placeable-object/tile.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
  types/foundry/client/pixi/placeable-object/wall.d.ts
  types/foundry/client/pixi/placeables-layer/base.d.ts
  types/foundry/client/pixi/placeables-layer/lighting-layer.d.ts
  types/foundry/client/pixi/placeables-layer/token-layer.d.ts
  types/foundry/client/pixi/placeables-layer/walls-layer.d.ts
Labels: pr: foundry v11

#8098 Override `CheckRoll.MATH_PROXY`
  src/module/system/check/roll.ts
  src/scripts/hooks/load.ts
Labels: pr: foundry v11

#8099 Move actor/item type names to new location, remove system `fromUuidSync`
  src/module/actor/hazard/document.ts
  src/module/actor/npc/document.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/sidebar/compendium-directory.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/armor/document.ts
  src/module/item/physical/document.ts
  src/module/item/sheet/base.ts
  src/module/item/weapon/document.ts
  src/module/migration/migrations/760-separate-note-title.ts
  src/module/migration/migrations/788-update-tanglefoot-bags.ts
  src/module/rules/rule-element/aura.ts
  src/module/rules/rule-element/base.ts
  src/module/system/statistic/armor-class.ts
  src/scripts/config/index.ts
  src/scripts/register-sheets.ts
  src/util/uuid.ts
  static/lang/en.json
  static/templates/actors/character/ability-builder.hbs
  static/templates/actors/character/partials/detail-item.hbs
  static/templates/actors/familiar-sheet.hbs
  static/templates/actors/hazard/partials/header.hbs
  static/templates/actors/hazard/sheet.hbs
  static/templates/actors/party/sheet.hbs
  static/templates/items/deity-details.hbs
  static/templates/items/heritage-sidebar.hbs
Labels: pr: foundry v11

#8100 Minor localization structure change tweaks
  src/module/apps/sidebar/compendium-directory.ts
  src/module/system/statistic/armor-class.ts
Labels: pr: foundry v11

#8101 Replace `DataModel#_validateModel` with `DataModel.validateJoint`
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/iwr/base.ts
  src/module/rules/rule-element/roll-option.ts
  types/foundry/common/abstract/data.d.ts
Labels: pr: foundry v11

#8102 Update `PointSource` constructor definition
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/helpers/point-source/base.d.ts
  types/foundry/client/pixi/helpers/point-source/light-source.d.ts
Labels: pr: foundry v11

#8094 Refactor action rendering and maintain summary expanded state
  src/module/actor/character/sheet.ts
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: bugfix, pr: refactor

#8104 Release Notes 4.12.7
  CHANGELOG.md
Labels: pr: housekeeping

#8105 Restore navigation of PC actions
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: foundry v11

#8108 Use `classic-level` to build and extract compendium packs
  build/build-packs.ts
  build/extract-packs.ts
  build/lib/compendium-pack.ts
  build/lib/extractor.ts
  build/lib/level-database.ts
  package-lock.json
  package.json
  static/system.json
  types/foundry/common/documents/table-result.d.ts
Labels: pr: refactor, pr: foundry v11

#8110 Annotate return types of `MATH_PROXY` functions
  src/module/system/check/roll.ts
Labels: pr: types update

#8116 Include roll data in effects panel descriptions
  src/module/apps/effects-panel.ts
Labels: pr: bugfix

#8115 Fix creation of custom physical items on actor sheets
  src/module/actor/sheet/base.ts
  src/styles/actor/character/_proficiencies.scss
Labels: pr: bugfix

#8114 Set icons for inline actor and item links
  src/scripts/hooks/load.ts
  types/foundry/client/config.d.ts
Labels: pr: enhancement

#8118 Add feat inline link icon
  src/scripts/hooks/load.ts
Labels: ui/ux

#8120 Move certain document/collection types to updated location
  types/foundry/client/data/abstract/document-collection.d.ts
  types/foundry/client/data/abstract/world-collection.d.ts
  types/foundry/client/data/collections/actors.d.ts
  types/foundry/client/data/collections/combat-encounters.d.ts
  types/foundry/client/data/collections/compendium-collection.d.ts
  types/foundry/client/data/collections/folders.d.ts
  types/foundry/client/data/collections/items.d.ts
  types/foundry/client/data/collections/journal.d.ts
  types/foundry/client/data/collections/macros.d.ts
  types/foundry/client/data/collections/messages.d.ts
  types/foundry/client/data/collections/playlists.d.ts
  types/foundry/client/data/collections/roll-tables.d.ts
  types/foundry/client/data/collections/scenes.d.ts
  types/foundry/client/data/collections/users.d.ts
  types/foundry/client/data/documents/active-effect.d.ts
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/client/data/documents/ambient-light-document.d.ts
  types/foundry/client/data/documents/ambient-sound-document.d.ts
  types/foundry/client/data/documents/cards.d.ts
  types/foundry/client/data/documents/chat-message.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/client-document.d.ts
  types/foundry/client/data/documents/combat.d.ts
  types/foundry/client/data/documents/combatant.d.ts
  types/foundry/client/data/documents/drawing-document.d.ts
  types/foundry/client/data/documents/fog-exploration.d.ts
  types/foundry/client/data/documents/folder.d.ts
  types/foundry/client/data/documents/index.d.ts
  types/foundry/client/data/documents/item.d.ts
  types/foundry/client/data/documents/journal-entry-page.d.ts
  types/foundry/client/data/documents/journal-entry.d.ts
  types/foundry/client/data/documents/macro.d.ts
  types/foundry/client/data/documents/measured-template-document.d.ts
  types/foundry/client/data/documents/note-document.d.ts
  types/foundry/client/data/documents/playlist-sound.d.ts
  types/foundry/client/data/documents/playlist.d.ts
  types/foundry/client/data/documents/roll-table.d.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/data/documents/table-result.d.ts
  types/foundry/client/data/documents/tile-document.d.ts
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/client/data/documents/user.d.ts
  types/foundry/client/data/documents/wall-document.d.ts
  types/foundry/index.d.ts
Labels: pr: foundry v11

#8121 Restore compendium sidebar functionality
  src/module/apps/sidebar/compendium-directory.ts
  src/styles/ui/sidebar/_compendium-directory.scss
  static/templates/sidebar/compendium-directory.hbs
  types/foundry/client/data/collections/compendium-collection.d.ts
Labels: pr: foundry v11

#8122 Restore party sidebar functionality for v11
  src/module/actor/party/document.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/collection/actors.ts
  static/templates/sidebar/party-document-partial.hbs
  types/foundry/client/data/abstract/world-collection.d.ts
  types/foundry/common/constants.d.ts
Labels: pr: foundry v11

#8124 Use `PointSource#shape` instead of `PointSource#los`
  src/module/canvas/perception/hearing-source.ts
  src/module/canvas/perception/modes.ts
  types/foundry/client/pixi/helpers/point-source/base.d.ts
  types/foundry/client/pixi/helpers/point-source/light-source.d.ts
  types/foundry/client/pixi/helpers/point-source/sound-source.d.ts
  types/foundry/client/pixi/helpers/point-source/vision-source.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
Labels: pr: foundry v11

#7906 Move cast level and spell variant info to origin flag
  src/module/canvas/measured-template.ts
  src/module/chat-message/data.ts
  src/module/chat-message/document.ts
  src/module/item/base.ts
  src/module/item/spell/document.ts
  src/module/scene/measured-template-document.ts
  src/module/system/check/check.ts
  src/module/system/damage/damage.ts
Labels: pr: refactor

#8125 Remove definition of deprecated `CompendiumCollection#private` getter
  src/module/apps/sidebar/compendium-directory.ts
  types/foundry/client/data/collections/compendium-collection.d.ts
Labels: pr: types update, pr: foundry v11

#8126 Use `Color.fromRGB` instead of deprecated `PIXI.utils.rgb2hex`
  src/module/canvas/token/object.ts
Labels: pr: foundry v11

#8128 Restore functionality of hearing detection
  src/module/canvas/perception/hearing-source.ts
  types/foundry/client/data/documents/fog-exploration.d.ts
  types/foundry/client/pixi/core/containers/index.d.ts
  types/foundry/client/pixi/core/containers/point-source-mesh.d.ts
  types/foundry/client/pixi/core/index.d.ts
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/helpers/point-source/base.d.ts
  types/foundry/client/pixi/helpers/point-source/sound-source.d.ts
  types/foundry/client/pixi/helpers/point-source/vision-source.d.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/sources/base-source.d.ts
  types/foundry/client/pixi/sources/index.d.ts
  types/foundry/client/pixi/sources/light-source.d.ts
  types/foundry/client/pixi/sources/rendered-source.d.ts
  types/foundry/client/pixi/sources/sound-source.d.ts
  types/foundry/client/pixi/sources/vision-source.d.ts
  types/foundry/index.d.ts
Labels: pr: refactor, pr: foundry v11

#8129 Have effects panel use condition items instead of `FlattenedCondition`s
  src/module/apps/effects-panel.ts
Labels: pr: bugfix

#8130 Reimplement `FlattenedCondition#breakdown` in `ConditionPF2e`
  src/module/item/condition/document.ts
Labels: pr: bugfix

#8132 Migrate system.json for V11
  static/system.json
Labels: pr: foundry v11

#8133 Add `data-dtype` to numeric world clock setting form element
  static/templates/system/settings/world-clock/index.hbs
Labels: pr: bugfix

#8134 Fix styling of system links in Settings sidebar
  src/scripts/hooks/render-settings.ts
  src/styles/settings/_index.scss
Labels: ui/ux, pr: foundry v11

#8135 Add data-dtype to numeric variant rule setting form element
  src/module/system/settings/variant-rules.ts
  static/templates/system/settings/variant-rules.hbs
Labels: pr: bugfix

#8136 Support embedded compendium folders in pack scripts
  build/lib/compendium-pack.ts
  build/lib/extractor.ts
  build/lib/helpers.ts
  build/lib/level-database.ts
Labels: pr: foundry v11

#8141 Update changelog from v10-maintenance branch
  CHANGELOG.md
Labels: pr: housekeeping

#8143 Add a sample pack folder
  static/system.json
Labels: pr: data update

#8139 Move system `MATH_PROXY` functions to `Math` namespace
  src/global.d.ts
  src/module/system/check/roll.ts
  src/scripts/hooks/load.ts
Labels: pr: foundry v11

#8144 Restore system placeholder for compendium search input
  static/templates/sidebar/compendium-directory.hbs
Labels: ui/ux, pr: foundry v11

#8142 Remove global style overrides for chat log
  src/styles/legacy/_chat.scss
  src/styles/ui/sidebar/chat/_index.scss
Labels: ui/ux, pr: foundry v11

#8149 Fix location of search placeholder in compendium directory templates
  static/templates/sidebar/compendium-directory.hbs
Labels: pr: bugfix

#8150 Stub out `ActorDelta`
  src/module/item/base.ts
  src/module/migration/migrations/624-removed-token-effect-icon-flags.ts
  src/module/migration/runner/index.ts
  src/module/scene/token-document/document.ts
  tests/mocks/scene.ts
  tests/module/migration.test.ts
  types/foundry/client/data/documents/actor-delta.d.ts
  types/foundry/client/data/documents/index.d.ts
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/common/documents/actor-delta.d.ts
  types/foundry/common/documents/module.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v11

#8151 Remove uses of deprecated `WallsLayer#checkCollision`
  src/module/canvas/helpers.ts
  src/module/canvas/token/aura/util.ts
  types/foundry/client/config.d.ts
  types/foundry/client/pixi/core/shapes/source-polygon.d.ts
  types/foundry/client/pixi/placeables-layer/walls-layer.d.ts
Labels: pr: foundry v11

#8158 Fix regression in calls to `ClockwiseSweepPolygon.testCollision`
  src/module/canvas/helpers.ts
  src/module/canvas/token/aura/util.ts
  types/foundry/client/pixi/core/shapes/source-polygon.d.ts
Labels: pr: bugfix, pr: foundry v11

#8157 Remove deprecated system features
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/familiar/document.ts
  src/module/actor/initiative.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/document.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/system/statistic/data.ts
  src/module/system/statistic/index.ts
Labels: pr: foundry v11

#8159 Move IWR RE processing to `afterPrepareData` callback
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/iwr/base.ts
Labels: pr: enhancement

#8160 Update minisearch to latest
  package-lock.json
  package.json
  src/module/apps/sidebar/compendium-directory.ts
Labels: pr: housekeeping, pr: refactor

#8161 Include origin items in rolls from inline saving throw links
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#8165 Fix clearing of `TokenDocument#overlayEffect`
  src/module/actor/base.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: bugfix, pr: foundry v11

#8167 Add simple NPC sheet
  src/module/actor/npc/sheet.ts
  src/scripts/register-sheets.ts
  static/templates/actors/npc/simple-sheet.hbs
Labels: pr: enhancement

#8166 Fix damage reversion of numeric-only damage
  src/module/actor/base.ts
Labels: pr: bugfix

#8164 Work around upstream issue causing actor updates to return `ActorDelta`s
  src/module/actor/base.ts
  types/foundry/client/data/documents/actor-delta.d.ts
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/common/documents/actor-delta.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v11

#8179 Harden check of two-hand trait before application
  src/module/system/damage/weapon.ts
Labels: pr: refactor

#8183 Remove mention of type field from AdjustDegreeOfSuccessRuleElement validation failure
  src/module/rules/rule-element/adjust-degree-of-success.ts
Labels: pr: bugfix

#8176 Mystify scrolls and wands when GM drops spell onto an actor sheet while holding the ALT key
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/sheet/base.ts
  src/module/item/consumable/spell-consumables.ts
Labels: pr: enhancement

#8182 Fix radius of Burning Blossoms
  packs/spells/burning-blossoms.json
Labels: pr: data update

#8177 Enable creation of Roll Tables from Compendium Browser search results
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/base.ts
  src/styles/packs/_tab.scss
  static/lang/en.json
  static/templates/compendium-browser/filters.hbs
  types/foundry/client/ui/dialog.d.ts
Labels: pr: new feature

#8172 Fix descriptions of entrench melee and entrench ranged
  src/scripts/config/traits.ts
Labels: pr: data update

#8184 Remove usage of `FlattenedCondition` objects
  src/module/actor/character/sheet.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/creature/types.ts
  src/module/item/condition/document.ts
  src/module/system/conditions/index.ts
  src/module/system/conditions/manager.ts
  src/module/system/conditions/types.ts
  src/scripts/register-templates.ts
  static/templates/actors/character/tabs/effects.hbs
  static/templates/actors/familiar-sheet.hbs
  static/templates/actors/npc/tabs/effects.hbs
  static/templates/actors/partials/effects.hbs
Labels: pr: refactor

#8185 Fix `CompendiumBrowserTab#getRollTableResults` range increase
  src/module/apps/compendium-browser/tabs/base.ts
Labels: pr: bugfix

#8195 Restore `effects` property of items and actors in the pack builder
  build/lib/compendium-pack.ts
Labels: pr: foundry v11

#8200 Avoid issues caused by `ActorDelta`-triggered double data preparation
  src/global.d.ts
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/item/base.ts
  src/module/item/melee/document.ts
  src/module/item/physical/document.ts
  src/module/scene/token-document/actor-delta.ts
  src/module/scene/token-document/document.ts
  src/scripts/hooks/load.ts
  types/foundry/client/config.d.ts
  types/foundry/client/data/documents/actor-delta.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/scripts/generate-client-base-mixes.ts
Labels: pr: foundry v11

#8162 Fix ephemeral effect transmitted by Holy Castigation feat
  packs/feats/holy-castigation.json
Labels: pr: data update

#8169 Add automation to Halo
  packs/feats/halo.json
Labels: pr: data update

#8170 Fix rule elements for Telekinetic Slip
  packs/feats/telekinetic-slip.json
Labels: pr: data update

#8174 Add burst template to Blindpepper Bomb
  packs/equipment/blindpepper-bomb.json
Labels: pr: data update

#8178 Fix Twisting Tree damage die upgrade
  packs/classfeatures/twisting-tree.json
Labels: pr: data update

#8187 Collapse some resistance rule elements
  packs/bestiary-effects/effect-aura-of-vitality.json
  packs/equipment-effects/effect-polished-demon-horn-armor-greater.json
  packs/equipment-effects/effect-polished-demon-horn-armor-major.json
  packs/equipment-effects/effect-polished-demon-horn-armor.json
Labels: pr: data update

#8188 Add link to effect for Kreeth-Ni's Wrath of Spurned Hospitality
  packs/outlaws-of-alkenstar-bestiary/kreeth-ni.json
Labels: pr: data update

#8190 Fix some Agents of Edgewatch NPCs
  packs/agents-of-edgewatch-bestiary/clockwork-chopper.json
  packs/agents-of-edgewatch-bestiary/clockwork-injector.json
  packs/agents-of-edgewatch-bestiary/daemonic-skinner.json
  packs/agents-of-edgewatch-bestiary/gage-carlyle.json
Labels: pr: data update

#8198 Add effects for Potions of Resistance
  packs/equipment-effects/effect-potion-of-acid-resistance-greater.json
  packs/equipment-effects/effect-potion-of-acid-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-acid-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-cold-resistance-greater.json
  packs/equipment-effects/effect-potion-of-cold-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-cold-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-electricity-resistance-greater.json
  packs/equipment-effects/effect-potion-of-electricity-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-electricity-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-fire-resistance-greater.json
  packs/equipment-effects/effect-potion-of-fire-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-fire-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-sonic-resistance-greater.json
  packs/equipment-effects/effect-potion-of-sonic-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-sonic-resistance-moderate.json
  packs/equipment/potion-of-acid-resistance-greater.json
  packs/equipment/potion-of-acid-resistance-lesser.json
  packs/equipment/potion-of-acid-resistance-moderate.json
  packs/equipment/potion-of-cold-resistance-greater.json
  packs/equipment/potion-of-cold-resistance-lesser.json
  packs/equipment/potion-of-cold-resistance-moderate.json
  packs/equipment/potion-of-electricity-resistance-greater.json
  packs/equipment/potion-of-electricity-resistance-lesser.json
  packs/equipment/potion-of-electricity-resistance-moderate.json
  packs/equipment/potion-of-fire-resistance-greater.json
  packs/equipment/potion-of-fire-resistance-lesser.json
  packs/equipment/potion-of-fire-resistance-moderate.json
  packs/equipment/potion-of-sonic-resistance-greater.json
  packs/equipment/potion-of-sonic-resistance-lesser.json
  packs/equipment/potion-of-sonic-resistance-moderate.json
Labels: pr: data update

#8194 Add damage links to Aroden's Hearthstone
  packs/equipment/arodens-hearthstone.json
Labels: pr: data update

#8193 Fix action symbols in Instinct Crowns
  packs/equipment/instinct-crown-animal.json
  packs/equipment/instinct-crown-dragon.json
  packs/equipment/instinct-crown-fury.json
  packs/equipment/instinct-crown-giant.json
  packs/equipment/instinct-crown-spirit.json
  packs/equipment/instinct-crown-superstition.json
Labels: pr: data update

#8192 Add damage links to Potions of Retaliation
  packs/equipment/potion-of-acid-retaliation-greater.json
  packs/equipment/potion-of-acid-retaliation-lesser.json
  packs/equipment/potion-of-acid-retaliation-major.json
  packs/equipment/potion-of-acid-retaliation-minor.json
  packs/equipment/potion-of-acid-retaliation-moderate.json
  packs/equipment/potion-of-cold-retaliation-greater.json
  packs/equipment/potion-of-cold-retaliation-lesser.json
  packs/equipment/potion-of-cold-retaliation-major.json
  packs/equipment/potion-of-cold-retaliation-minor.json
  packs/equipment/potion-of-cold-retaliation-moderate.json
  packs/equipment/potion-of-electricity-retaliation-greater.json
  packs/equipment/potion-of-electricity-retaliation-lesser.json
  packs/equipment/potion-of-electricity-retaliation-major.json
  packs/equipment/potion-of-electricity-retaliation-minor.json
  packs/equipment/potion-of-electricity-retaliation-moderate.json
  packs/equipment/potion-of-fire-retaliation-greater.json
  packs/equipment/potion-of-fire-retaliation-lesser.json
  packs/equipment/potion-of-fire-retaliation-major.json
  packs/equipment/potion-of-fire-retaliation-minor.json
  packs/equipment/potion-of-fire-retaliation-moderate.json
Labels: pr: data update

#8181 Add HTML template and functional sheet javascript for a "simple NPC" sheet
  src/module/actor/base.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/types.ts
  src/scripts/dice.ts
  src/scripts/register-sheets.ts
  src/styles/actor/npc/_index.scss
  static/lang/en.json
  static/templates/actors/npc/simple-sheet.hbs
  static/templates/actors/npc/tabs/main.hbs
Labels: pr: new feature

#8203 Set empty `delta` when initializing `TokenDocument` source
  src/module/scene/token-document/document.ts
Labels: pr: foundry v11

#8206 Replace ChoiceSet pack queries with index lookups and predicate testing
  packs/classfeatures/deity.json
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  types/foundry/client/data/collections/compendium-collection.d.ts
  types/foundry/common/types.d.ts
Labels: pr: refactor, pr: foundry v11

#8208 Add "system.maxTakeable" to ChoiceSet index fields
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#8204 Fix bonus in Clarity Goggles description
  packs/equipment/clarity-goggles-greater.json
  packs/equipment/clarity-goggles-moderate.json
Labels: pr: data update

#8210 Add maxItemLevel to Gadget Specialist
  packs/feats/gadget-specialist.json
Labels: pr: data update

#8213 Prevent `ActorDelta`s from preparing item data shared with linked actors
  src/module/scene/token-document/actor-delta.ts
Labels: pr: bugfix, pr: foundry v11

#8214 Restore display of spellcasting entries on NPC sheet
  src/module/actor/npc/sheet.ts
Labels: pr: bugfix

#8205 Add links to Capsaicin Tonic
  packs/equipment/capsaicin-tonic.json
Labels: pr: data update

#8202 Fix longbow range on Spell Effect: Devil Form (Erinys)
  packs/spell-effects/spell-effect-devil-form-erinys.json
Labels: pr: data update

#8207 Update Weapon Innovation and General Training choice sets
  packs/classfeatures/weapon-innovation.json
  packs/feats/general-training.json
  static/lang/re-en.json
Labels: pr: data update

#8215 Work around more `ActorDelta` issues
  src/module/scene/token-document/actor-delta.ts
  types/foundry/client/data/documents/actor-delta.d.ts
Labels: pr: foundry v11

#8217 Fix rule elements on Munavri Spellblade
  packs/pathfinder-bestiary-3/munavri-spellblade.json
Labels: pr: data update

#8219 Restore token Z-cycling
  src/module/canvas/layer/token.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
Labels: pr: foundry v11

#8218 Fix range increments and maximum ranges on battle form attacks
  packs/spell-effects/spell-effect-angel-form-choral.json
  packs/spell-effects/spell-effect-cosmic-form-moon.json
  packs/spell-effects/spell-effect-cosmic-form-sun.json
  packs/spell-effects/spell-effect-daemon-form-leukodaemon.json
  packs/spell-effects/spell-effect-devil-form-erinys.json
  packs/spell-effects/spell-effect-devil-form-osyluth.json
  packs/spell-effects/spell-effect-element-embodied-air.json
  packs/spell-effects/spell-effect-element-embodied-earth.json
  packs/spell-effects/spell-effect-element-embodied-fire.json
  packs/spell-effects/spell-effect-element-embodied-water.json
  packs/spell-effects/spell-effect-insect-form-spider.json
Labels: pr: data update

#8211 Add rule elements to Exemplary Finisher
  packs/classfeatures/battledancer.json
  packs/classfeatures/braggart.json
  packs/classfeatures/fencer.json
  packs/classfeatures/gymnast.json
  packs/classfeatures/wit.json
  static/lang/re-en.json
Labels: pr: data update

#8223 Update migration 841 to handle more UUID locations
  src/module/migration/migrations/841-v11-uuid-format.ts
Labels: pr: data migration

#8201 Add content from Pathfinder Wake the Dead #1
  packs/backgrounds/awful-scab.json
  packs/equipment/nexian-sealing-blade-greater.json
  packs/equipment/nexian-sealing-blade.json
  packs/equipment/rattling-bolt-greater.json
  packs/equipment/rattling-bolt.json
  packs/equipment/silver-orb-greater.json
  packs/equipment/silver-orb-lesser.json
  packs/equipment/silver-orb-powder.json
  packs/spells/cyclone-rondo.json
Labels: pr: data entry

#8225 Move April Fools bestiary creatures to Paizo Blog Bestiary
  packs/blog-bestiary/blarghest.json
  packs/blog-bestiary/cacaodaemon.json
  packs/blog-bestiary/demom.json
  packs/blog-bestiary/floolf.json
  packs/blog-bestiary/nonsequitaur.json
  packs/blog-bestiary/nosferotter.json
  packs/blog-bestiary/psstpsstmitl.json
  packs/blog-bestiary/squirrelwind.json
  packs/blog-bestiary/weredigo.json
  static/system.json
Labels: pr: data update

#8224 Type `event` parameters as `FederatedPointerEvent`s where appropriate
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/client/pixi/placeable-object/tile.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
  types/foundry/client/pixi/placeable-object/wall.d.ts
Labels: pr: types update

#8226 Remove "Bestiary" from bestiary pack names in anticipation of foldering
  static/system.json
Labels: pr: data update

#8227 Remove override of no-longer-existing _onUpdateTokenActor
  src/module/scene/token-document/document.ts
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v11

#8230 Restore token render changes triggered by synthetic actor updates
  src/module/canvas/layer/token.ts
  src/module/scene/token-document/actor-delta.ts
  types/foundry/client/data/documents/actor-delta.d.ts
  types/foundry/client/pixi/core/interaction/index.d.ts
  types/foundry/client/pixi/core/interaction/render-flags.d.ts
  types/foundry/client/pixi/placeable-object/base.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
Labels: pr: foundry v11

#8229 Fill @UUID link labels on build
  build/lib/compendium-pack.ts
  packs/adventure-specific-actions/affinity-ablaze-arms-of-balance-walking-the-cardinal-paths.json
  packs/adventure-specific-actions/affinity-ablaze-biting-roses-glimpses-to-beyond.json
  packs/adventure-specific-actions/affinity-ablaze-speakers-to-the-winds-all-is-one-one-is-all.json
  packs/adventure-specific-actions/affinity-ablaze-winters-roar-rampaging-glacier-charge.json
  packs/blood-lords-bestiary/dead-faine.json
  packs/equipment-effects/effect-whispering-staff-enemy.json
  packs/feat-effects/effect-walking-the-cardinal-paths.json
  packs/feats/cooperative-nature.json
  packs/gatewalkers-bestiary/vhisa-resgrido.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/journals/archetypes.json
  packs/journals/gm-screen.json
  packs/kingmaker-bestiary/tristian-level-1.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/npc-gallery/charlatan.json
  packs/npc-gallery/mastermind.json
  packs/pathfinder-bestiary-2/planetar.json
  packs/pfs-season-3-bestiary/shobhad-hunter-7-8.json
  packs/pfs-season-4-bestiary/charlatan-pfs-4-05.json
Labels: pr: data update, pr: housekeeping

#8231 Remove non-existant note from Track macro
  src/module/system/action-macros/exploration/track.ts
Labels: pr: data update

#8232 Move pregen PC compendiums to top-level folder
  static/system.json
Labels: pr: housekeeping

#8234 await `NPCSheetPF2e##prepareActions`
  src/module/actor/npc/sheet.ts
Labels: pr: bugfix

#8235 Update type definition of `TokenDocument.getTrackedAttributes`'s return
  src/module/scene/token-document/document.ts
  types/foundry/client/data/documents/token-document.d.ts
Labels: pr: types update, pr: foundry v11

#8241 add pronoun field in player config
  static/templates/user/sheet.hbs
Labels: pr: foundry v11

#8237 Temporarily remove `packFolders`
  static/system.json
Labels: pr: data update, pr: foundry v11

#8239 Show a progress bar when fetching pack indices for choice set rule elements
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/progress.ts
  src/module/apps/progress.ts
  src/module/rules/rule-element/choice-set/prompt.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/styles/_globals.scss
  static/lang/en.json
  types/foundry/client/application/hud/navigation.d.ts
Labels: pr: refactor, pr: foundry v11

#8245 Fix appended CombatConfig settings
  src/scripts/hooks/render-combat-tracker-config.ts
  static/templates/sidebar/encounter-tracker/config.hbs
Labels: pr: foundry v11

#8247 Fix saving throw links on NPC sheet
  static/templates/actors/npc/partials/sidebar.hbs
Labels: pr: bugfix

#8246 Add more options to Compendium Browser roll table dialogs
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/base.ts
  static/lang/en.json
  static/templates/compendium-browser/roll-table-dialog.hbs
Labels: pr: enhancement

#8251 Fix pair of settings numeric settings possibly returning as strings
  src/module/migration/migrations/842-numify-numeric-settings.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration

#8255 [CompendiumBrowser] Hide Roll Table buttons for non-GM users
  static/templates/compendium-browser/filters.hbs
Labels: pr: enhancement

#8257 Fix `TemplateLayerPF2e#_onDragLeftMove`
  src/module/canvas/layer/template.ts
  types/foundry/client/pixi/placeables-layer/base.d.ts
Labels: pr: bugfix, pr: foundry v11

#8254 Make Awful Approach recharge rolls blind
  packs/book-of-the-dead-bestiary/unrisen.json
  packs/crown-of-the-kobold-king-bestiary/the-disciples.json
Labels: pr: data update

#8259 Release Notes 5.0.0-beta2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#8253 Stack items acquired or purchased from the compendium browser
  src/module/actor/inventory/index.ts
  src/module/apps/compendium-browser/index.ts
Labels: pr: enhancement

#8252 Minor visual updates to character skills
  src/styles/actor/character/_proficiencies.scss
  src/styles/actor/character/_proficiency-ranks.scss
  static/templates/actors/character/tabs/proficiencies.hbs
Labels: ui/ux

#8260 Add schema type definition for `BaseAmbientLight`
  src/module/rules/rule-element/choice-set/rule-element.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/ambient-light.d.ts
Labels: pr: types update

#8263 Add ability for members to add & remove physical items from party sheet
  src/module/actor/party/document.ts
  src/module/actor/party/sheet.ts
  src/styles/actor/party/_index.scss
Labels: pr: enhancement

#8264 Fix vehicle sheet effects tab using the old `conditions.hbs` partial
  static/templates/actors/vehicle/tabs/vehicle-effects.hbs
Labels: pr: bugfix

#8266 Prevent error from being thrown from `ItemTransfer##sendMessage`
  src/module/actor/item-transfer.ts
  src/module/actor/loot/sheet.ts
  static/lang/en.json
Labels: pr: bugfix

#8265 Fix broken thumbnails in compendium sidebar `JournalEntry` search results
  src/module/apps/sidebar/compendium-directory.ts
Labels: pr: bugfix

#8270 Delay compilation of compendium directory's search index
  src/module/apps/sidebar/compendium-directory.ts
  src/scripts/hooks/ready.ts
Labels: pr: foundry v11

#8271 Add core Append Number and Prepend Adjective fields to Prototype Token Config
  static/templates/scene/token/partials/identity.hbs
Labels: pr: foundry v11

#8273 [CD] Rename `packs-json.zip` to `json-assets.zip` and add `static/lang` files
  .github/workflows/cd.yml
  .gitignore
  build/lib/compendium-pack.ts
Labels: localization, pr: enhancement

#8275 Set hardness getter override for vehicles
  src/module/actor/vehicle/document.ts
Labels: pr: bugfix

#8261 Update Hero Point deck to paged format, migrate UUIDs to V11 format
  packs/hero-point-deck/ancestral-might.json
  packs/hero-point-deck/aura-of-protection.json
  packs/hero-point-deck/battle-cry.json
  packs/hero-point-deck/called-foe.json
  packs/hero-point-deck/catch-your-breath.json
  packs/hero-point-deck/channel-life-force.json
  packs/hero-point-deck/class-might.json
  packs/hero-point-deck/critical-moment.json
  packs/hero-point-deck/cut-through-the-fog.json
  packs/hero-point-deck/daring-attempt.json
  packs/hero-point-deck/desperate-swing.json
  packs/hero-point-deck/distract-foe.json
  packs/hero-point-deck/dive-out-of-danger.json
  packs/hero-point-deck/drain-power.json
  packs/hero-point-deck/endure-the-onslaught.json
  packs/hero-point-deck/flash-of-insight.json
  packs/hero-point-deck/fluid-motion.json
  packs/hero-point-deck/grazing-blow.json
  packs/hero-point-deck/hasty-block.json
  packs/hero-point-deck/healing-prayer.json
  packs/hero-point-deck/hold-the-line.json
  packs/hero-point-deck/i-hope-this-works.json
  packs/hero-point-deck/impossible-shot.json
  packs/hero-point-deck/last-ounce-of-strength.json
  packs/hero-point-deck/last-second-sidestep.json
  packs/hero-point-deck/last-stand.json
  packs/hero-point-deck/magical-reverberation.json
  packs/hero-point-deck/make-way.json
  packs/hero-point-deck/misdirected-attack.json
  packs/hero-point-deck/opportune-distraction.json
  packs/hero-point-deck/pierce-resistance.json
  packs/hero-point-deck/press-on.json
  packs/hero-point-deck/protect-the-innocent.json
  packs/hero-point-deck/push-through-the-pain.json
  packs/hero-point-deck/rage-and-fury.json
  packs/hero-point-deck/rampage.json
  packs/hero-point-deck/reckless-charge.json
  packs/hero-point-deck/rending-swipe.json
  packs/hero-point-deck/reverse-strike.json
  packs/hero-point-deck/roll-back.json
  packs/hero-point-deck/run-and-shoot.json
  packs/hero-point-deck/shake-it-off.json
  packs/hero-point-deck/shoot-through.json
  packs/hero-point-deck/spark-of-courage.json
  packs/hero-point-deck/stay-in-the-fight.json
  packs/hero-point-deck/stoke-the-magical-flame.json
  packs/hero-point-deck/strike-true.json
  packs/hero-point-deck/surge-of-magic.json
  packs/hero-point-deck/surge-of-speed.json
  packs/hero-point-deck/tuck-and-roll.json
  packs/hero-point-deck/tumble-through.json
  packs/hero-point-deck/warding-sign.json
  packs/journals/hero-point-deck.json
  packs/rollable-tables/hero-point-deck.json
  static/system.json
Labels: pr: data update

#8269 Add rule elements to Snaring Anadi heritage
  packs/ancestryfeatures/fangs.json
  packs/heritages/snaring-anadi.json
Labels: pr: data update

#8276 Update Cyclops Bully's Terrorizing Swing rule elements and localize
  packs/strength-of-thousands-bestiary/cyclops-bully.json
  static/lang/re-en.json
Labels: pr: data update

#8277 Add effects for Crushing runes
  packs/equipment-effects/effect-crushing-greater.json
  packs/equipment-effects/effect-crushing.json
  packs/equipment/crushing-greater.json
  packs/equipment/crushing.json
  static/lang/en.json
Labels: pr: data update

#8284 Fix css classes in secondary crafting tab template
  src/styles/actor/character/_crafting.scss
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/actors/crafting-entry-alchemical.hbs
Labels: pr: bugfix

#8287 Update format of source links generated in spell consumable descriptions
  src/module/item/consumable/spell-consumables.ts
Labels: pr: foundry v11

#8282 Reset actors when stamina variant rule setting is changed
  src/module/migration/migrations/842-numify-numeric-settings.ts
  src/module/system/settings/variant-rules.ts
Labels: pr: bugfix

#8283 Add heatsight as sense type, refine sense selector template
  src/module/actor/creature/sense.ts
  src/module/actor/creature/values.ts
  src/module/system/tag-selector/senses.ts
  src/scripts/config/index.ts
  static/lang/en.json
  static/templates/system/tag-selector/senses.hbs
Labels: pr: enhancement, pr: refactor

#8138 Create Kingdom builder sheet and validate kingdom data
  src/module/actor/party/document.ts
  src/module/actor/party/invalid-campaign.ts
  src/module/actor/party/kingdom/builder.ts
  src/module/actor/party/kingdom/data.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/types.ts
  src/styles/actor/party/_index.scss
  src/styles/actor/party/kingdom/_builder.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/ui/sidebar/_actor-directory.scss
  static/lang/en.json
  static/lang/kingmaker-en.json
  static/system.json
  static/templates/actors/party/kingdom/builder.hbs
  static/templates/sidebar/party-document-partial.hbs
  types/foundry/common/abstract/data.d.ts
  types/foundry/common/abstract/document.d.ts
Labels: pr: enhancement

#8288 Don't enforce tremorsense as imprecise
  src/module/actor/creature/values.ts
Labels: pr: bugfix

#8220 Minor Data updates for impact foam, doprillu and archer's aim
  packs/equipment/impact-foam-chassis-greater.json
  packs/equipment/impact-foam-chassis-major.json
  packs/equipment/impact-foam-chassis-moderate.json
  packs/feats/archers-aim.json
  packs/pathfinder-bestiary-2/doprillu.json
  static/lang/re-en.json
Labels: pr: data update

#8289 Improve automation of Shield of the Unified Legion
  packs/equipment/shield-of-the-unified-legion.json
Labels: pr: data update

#8291 Move Parsus' key details to GM note
  packs/outlaws-of-alkenstar-bestiary/parsus.json
Labels: pr: data update

#8279 Reorganize party sheet overview listeners, add hero point click listener
  src/module/actor/character/data.ts
  src/module/actor/party/sheet.ts
  src/module/actor/party/types.ts
  src/styles/actor/party/_overview.scss
  static/templates/actors/party/regions/inventory-members.hbs
  static/templates/actors/party/regions/overview.hbs
Labels: pr: enhancement, pr: refactor
