Repository foundryvtt/pf2e, pull requests merged in 2023-03, with the labels that each got.

#6409 Add EphemeralEffect rule element
  packs/data/feats.db/dread-striker.json
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/data/base.ts
  src/module/actor/helpers.ts
  src/module/actor/modifiers.ts
  src/module/actor/types.ts
  src/module/item/spell/document.ts
  src/module/rules/helpers.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/mixins.ts
  src/module/rules/synthetics.ts
  src/module/system/conditions/manager.ts
  src/module/system/statistic/index.ts
  static/lang/re-en.json
Labels: pr: new feature

#6692 Don't rerender actor sheets every turn change
  src/module/actor/helpers.ts
  src/module/canvas/status-effects.ts
  src/module/encounter/document.ts
  src/module/system/effect-tracker.ts
  src/module/system/settings/index.ts
  src/module/system/settings/variant-rules.ts
  src/scripts/hooks/ready.ts
Labels: ui/ux

#6689 Update Jellyfish Stance per FotRP Hardcover
  packs/data/feat-effects.db/stance-jellyfish-stance.json
  packs/data/feats.db/jellyfish-stance.json
Labels: pr: data update

#6694 Fix Skeletal Woolly Rhinoceros' Rhinoceros Charge. Clean up Rhinoceros Charge REs.
  packs/data/pathfinder-bestiary-2.db/rhinoceros.json
  packs/data/pathfinder-bestiary-2.db/woolly-rhinoceros.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/skeletal-woolly-rhinoceros.json
Labels: pr: data update

#6693 Update triceratops Vicious Gore from Note RE to DamageDice RE.
  packs/data/pathfinder-bestiary.db/triceratops.json
Labels: pr: data update

#6691 Fix level for Unending Itch
  packs/data/equipment.db/unending-itch.json
Labels: pr: data update

#6686 Update necrohusk Impaling Lunge from Note RE to DamageDice RE. Add Note RE to Vile Innards.
  packs/data/quest-for-the-frozen-flame-bestiary.db/necrohusk.json
Labels: pr: data update

#6684 Add cantrips to Pickled Demon Tongue and Polished Demon Horn. Clean up formatting.
  packs/data/equipment.db/pickled-demon-tongue-greater.json
  packs/data/equipment.db/pickled-demon-tongue-major.json
  packs/data/equipment.db/pickled-demon-tongue.json
  packs/data/equipment.db/polished-demon-horn-greater.json
  packs/data/equipment.db/polished-demon-horn-major.json
  packs/data/equipment.db/polished-demon-horn.json
Labels: pr: data update

#6699 Add Returning and Shifting to Blade Ally choices
  packs/data/feat-effects.db/effect-blade-ally.json
Labels: pr: data update

#6701 Fix display of range increment in weapon summaries
  src/module/item/weapon/document.ts
  src/module/system/check/check.ts
Labels: pr: bugfix

#6700 Restore blind/gm initiative rolling
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/encounter/document.ts
  src/scripts/sheet-util.ts
  types/foundry/client/documents/combat.d.ts
Labels: pr: bugfix

#6697 Default spell location to `null`, remove `system.ability` property
  src/module/item/spell/data.ts
  src/module/item/spell/document.ts
  static/template.json
Labels: pr: refactor

#6677 Prune invalid traits from actors and items
  packs/scripts/run-migration.ts
  src/module/item/weapon/document.ts
  src/module/migration/migrations/828-prune-invalid-traits.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/scripts/config/traits.ts
Labels: pr: data migration

#6706 Fix localized string for condition sidebar duration
  static/templates/items/condition-sidebar.hbs
Labels: pr: bugfix

#6648 Add Escape action macro
  packs/data/action-macros.db/escape-acrobatics.json
  packs/data/action-macros.db/escape-athletics.json
  packs/data/action-macros.db/escape-unarmed-attack.json
  packs/data/action-macros.db/escape.json
  packs/data/actions.db/escape.json
  src/module/system/action-macros/basic/escape.ts
  src/module/system/action-macros/index.ts
  static/lang/en.json
Labels: pr: enhancement

#6708 Add description of Artifact trait
  static/lang/en.json
Labels: pr: data update

#6709 Exclude "artifact" and "cursed" traits from generated NPC attacks
  src/module/item/weapon/document.ts
Labels: pr: enhancement

#6710 Add classOrSpellDC property to NPCs
  src/module/actor/npc/data.ts
  src/module/actor/npc/document.ts
Labels: pr: enhancement

#6713 Add icons to and localize names of monk stance Strikes
  packs/data/feat-effects.db/stance-clinging-shadows-stance.json
  packs/data/feat-effects.db/stance-cobra-stance-cobra-envenom.json
  packs/data/feat-effects.db/stance-cobra-stance.json
  packs/data/feat-effects.db/stance-crane-stance.json
  packs/data/feat-effects.db/stance-dragon-stance.json
  packs/data/feat-effects.db/stance-gorilla-stance-gorilla-pound.json
  packs/data/feat-effects.db/stance-gorilla-stance.json
  packs/data/feat-effects.db/stance-ironblood-stance.json
  packs/data/feat-effects.db/stance-jellyfish-stance.json
  packs/data/feat-effects.db/stance-mountain-stance.json
  packs/data/feat-effects.db/stance-rain-of-embers-stance.json
  packs/data/feat-effects.db/stance-reflective-ripple-stance.json
  packs/data/feat-effects.db/stance-sky-and-heaven-stance.json
  packs/data/feat-effects.db/stance-stoked-flame-stance.json
  packs/data/feat-effects.db/stance-stumbling-stance.json
  packs/data/feat-effects.db/stance-tangled-forest-stance.json
  packs/data/feat-effects.db/stance-tiger-stance.json
  packs/data/feat-effects.db/stance-wild-winds-stance.json
  packs/data/feat-effects.db/stance-wolf-stance.json
  static/lang/re-en.json
Labels: pr: data update

#6634 Create effects for Sanguine Fang
  packs/data/equipment-effects.db/effect-sanguine-fang-armor-greater.json
  packs/data/equipment-effects.db/effect-sanguine-fang-armor-major.json
  packs/data/equipment-effects.db/effect-sanguine-fang-armor.json
  packs/data/equipment-effects.db/effect-sanguine-fang-weapon-greater.json
  packs/data/equipment-effects.db/effect-sanguine-fang-weapon-major.json
  packs/data/equipment-effects.db/effect-sanguine-fang-weapon.json
  packs/data/equipment.db/sanguine-fang-greater.json
  packs/data/equipment.db/sanguine-fang-major.json
  packs/data/equipment.db/sanguine-fang.json
Labels: pr: data update

#6650 Create effects for Phantasmal Doorknob
  packs/data/equipment-effects.db/effect-phantasmal-doorknob-armor-greater.json
  packs/data/equipment-effects.db/effect-phantasmal-doorknob-armor-major.json
  packs/data/equipment-effects.db/effect-phantasmal-doorknob-armor.json
  packs/data/equipment-effects.db/effect-phantasmal-doorknob-weapon-greater.json
  packs/data/equipment-effects.db/effect-phantasmal-doorknob-weapon-major.json
  packs/data/equipment-effects.db/effect-phantasmal-doorknob-weapon.json
  packs/data/equipment.db/phantasmal-doorknob-greater.json
  packs/data/equipment.db/phantasmal-doorknob-major.json
  packs/data/equipment.db/phantasmal-doorknob.json
Labels: pr: data update

#6707 Set icon for energy beam, add persistent damage
  packs/data/feats.db/armor-specialist.json
  packs/data/feats.db/energy-beam.json
Labels: pr: data update

#6717 Add GrantItem RE to Corpse Stitcher background
  packs/data/backgrounds.db/corpse-stitcher.json
Labels: pr: data update

#6714 Add some Strike damage REs
  packs/data/pfs-season-1-bestiary.db/acid-spray-fountain.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/hall-of-fiery-doom.json
Labels: pr: data update

#6719 Organize and desillify @module/dc.ts
  src/module/dc.ts
Labels: pr: refactor

#6704 Add rule element to Surprise Attack class feature
  packs/data/classfeatures.db/surprise-attack.json
Labels: pr: data update

#6723 Remove alignment trait description text indicating alignment restrictions
  static/lang/en.json
Labels: pr: data update

#6721 Generate `target` roll options before extracting `EphemeralEffect`s
  src/module/actor/base.ts
Labels: pr: bugfix

#6720 Log statistic used to roll initiative in Combatant flags
  src/module/actor/base.ts
  src/module/actor/creature/document.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/module/system/check/check.ts
  src/module/system/check/roll.ts
Labels: pr: enhancement

#6635 Create effects for Rime Crystal
  packs/data/equipment-effects.db/effect-rime-crystal-armor-greater.json
  packs/data/equipment-effects.db/effect-rime-crystal-armor-major.json
  packs/data/equipment-effects.db/effect-rime-crystal-armor.json
  packs/data/equipment-effects.db/effect-rime-crystal-weapon-greater.json
  packs/data/equipment-effects.db/effect-rime-crystal-weapon-major.json
  packs/data/equipment-effects.db/effect-rime-crystal-weapon.json
  packs/data/equipment.db/rime-crystal-greater.json
  packs/data/equipment.db/rime-crystal-major.json
  packs/data/equipment.db/rime-crystal.json
Labels: pr: data update

#6725 Fix REs on Virtuosic Performer
  packs/data/feats.db/virtuosic-performer.json
Labels: pr: data update

#6726 Reorganize User types, remove flags from `UserData`
  src/global.d.ts
  src/module/actor/item-transfer.ts
  src/module/chat-message/data.ts
  src/module/chat-message/document.ts
  src/module/migration/base.ts
  src/module/migration/migrations/603-reset-quick-roll-default.ts
  src/module/migration/migrations/617-fix-user-flags.ts
  src/module/migration/migrations/620-rename-to-webp.ts
  src/module/migration/runner/base.ts
  src/module/scene/sheet.ts
  src/module/user/data.ts
  src/module/user/document.ts
  types/foundry/client/application/form-application/document-sheet/macro-config.d.ts
  types/foundry/client/application/form-application/document-sheet/scene-config.d.ts
  types/foundry/client/application/sidebar/sidebar-tab/settings.d.ts
  types/foundry/client/collections/world-collection/users.d.ts
  types/foundry/client/documents/chat-message.d.ts
  types/foundry/client/documents/user.d.ts
  types/foundry/client/game.d.ts
  types/foundry/client/pixi/placeable-object/token.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/data/data/chat-message-data.d.ts
  types/foundry/common/data/data/index.d.ts
  types/foundry/common/data/data/user-data.d.ts
  types/foundry/common/documents/user.d.ts
  types/foundry/index.d.ts
Labels: pr: types update

#6636 Replace ritual spellcasting entries with in-memory ones
  src/module/actor/base.ts
  src/module/actor/character/data/sheet.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/creature/spell-preparation-sheet.ts
  src/module/actor/creature/types.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/types.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/actor/spellcasting.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/item/consumable/document.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/data/index.ts
  src/module/item/spellcasting-entry/data/sheet.ts
  src/module/item/spellcasting-entry/data/types.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/index.ts
  src/module/item/spellcasting-entry/rituals.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/item/spellcasting-entry/types.ts
  src/styles/actor/_index.scss
  src/styles/actor/_spell-list.scss
  src/styles/actor/npc/_spells.scss
  static/lang/en.json
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/spellcasting-dialog.hbs
  static/templates/actors/spellcasting-spell-list.hbs
  types/foundry/client/documents/mixins/client-document-mixin.d.ts
Labels: pr: refactor

#6729 Unify isLocked getter
  src/module/item/abstract-effect/document.ts
  src/module/item/condition/document.ts
  src/module/system/conditions/manager.ts
  src/module/system/conditions/types.ts
  static/templates/system/effects-panel.hbs
Labels: pr: refactor

#6731 Move toggleable roll options to actor synthetics
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/module/rules/rule-element/roll-option.ts
  src/module/rules/synthetics.ts
  static/templates/actors/character/tabs/actions.hbs
  static/templates/actors/npc/tabs/main.hbs
Labels: pr: refactor

#6732 Remove generic parameter defaults from `StringField`
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/strike.ts
  types/foundry/common/data/fields.d.mts
Labels: pr: refactor, pr: types update

#6734 Fix some skill names
  packs/data/abomination-vaults-bestiary.db/jarelle-kaldrian.json
  packs/data/age-of-ashes-bestiary.db/dragonscarred-dead.json
  packs/data/book-of-the-dead-bestiary.db/harlo-krant.json
  packs/data/book-of-the-dead-bestiary.db/silent-stalker.json
  packs/data/crown-of-the-kobold-king-bestiary.db/drazmorg-the-damned.json
  packs/data/crown-of-the-kobold-king-bestiary.db/foolish-hunter.json
  packs/data/crown-of-the-kobold-king-bestiary.db/king-merlokrep.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/mafika-ayuwari.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/umbasi.json
  packs/data/kingmaker-bestiary.db/vordakai.json
  packs/data/npc-gallery.db/ethereal-sailor.json
  packs/data/paizo-pregens.db/fluff-fang.json
  packs/data/pfs-season-1-bestiary.db/ogre.json
  packs/data/pfs-season-2-bestiary.db/wounded-dragon-turtle-3-4.json
  packs/data/pfs-season-2-bestiary.db/wounded-dragon-turtle-5-6.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/summer-hora-queen.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/summer-hora.json
Labels: pr: data update

#6739 Restore toggles in PC sheet template
  static/templates/actors/character/tabs/actions.hbs
  static/templates/actors/npc/tabs/main.hbs
Labels: pr: bugfix

#6740 Restore presence of school trait in spell sheet
  src/module/item/spell/sheet.ts
Labels: pr: bugfix

#6742 Allow Mummy Dedication to Grant Basic Undead Benefits
  packs/data/feats.db/mummy-dedication.json
Labels: source: rulebooks

#6741 Add aura RE to Undying Conviction
  packs/data/feat-effects.db/effect-under-control.json
  packs/data/feat-effects.db/effect-undying-conviction.json
  packs/data/feats.db/undying-conviction.json
Labels: pr: data update

#6743 Add missing LO Absalom feat
  packs/data/feats.db/irezoko-tattoo.json
Labels: pr: data update

#6744 Add an effect for Ghostly Weapon
  packs/data/spell-effects.db/spell-effect-ghostly-weapon.json
  packs/data/spells.db/ghostly-weapon.json
Labels: pr: data entry, source: rulebooks

#6745 Automate Expert Backstabber feat
  packs/data/feats.db/expert-backstabber.json
  src/module/system/damage/weapon.ts
Labels: pr: data update

#6746 Add ammunition rule elements to linked weapons
  src/module/item/consumable/document.ts
  src/module/item/physical/document.ts
  src/module/item/weapon/document.ts
Labels: pr: enhancement

#6748 Add description link from Spell Effect: Ghostly Weapon to Ghostly Weapon spell
  packs/data/spell-effects.db/spell-effect-ghostly-weapon.json
Labels: pr: data update

#6749 Fix localized strings for shield deflecting traits
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#6750 Add RE for Eroding Bullet
  packs/data/equipment.db/eroding-bullet.json
Labels: pr: data update

#6751 Expand damage roll options for strikes with ammunition details
  src/module/item/weapon/document.ts
Labels: pr: enhancement

#6522 Emphasize spell link when creating consumable from spell
  src/module/item/consumable/spell-consumables.ts
Labels: pr: enhancement

#6757 Fix Frost's Touch to be a cantrip. Remove extraneous emphasis.
  packs/data/equipment.db/pathfinders-coin.json
  packs/data/equipment.db/unending-youth.json
  packs/data/feats.db/blessed-one-dedication.json
  packs/data/feats.db/debilitating-dichotomy.json
  packs/data/feats.db/final-form.json
  packs/data/feats.db/first-frost.json
  packs/data/feats.db/pierce-the-light.json
  packs/data/feats.db/rokoan-arts.json
  packs/data/spells.db/frosts-touch.json
Labels: pr: data update

#6756 Fill out `EphemeralEffect` alterations schema field
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/system/schema-data-fields.ts
Labels: pr: bugfix

#6733 Add schema for `RollOptionRuleElement`
  src/module/rules/rule-element/roll-option.ts
Labels: pr: refactor

#6765 Fix generic parameter passed to `ArrayField`
  src/module/system/schema-data-fields.ts
  types/foundry/common/data/fields.d.mts
Labels: pr: types update

#6762 Start filling out GrantItem schema, relocate item alteration schema
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/grant-item/schema.ts
  src/module/rules/rule-element/mixins.ts
  src/module/system/schema-data-fields.ts
  src/util/misc.ts
Labels: pr: refactor

#6768 Fix display of rarity in armor and equipement chat cards
  src/module/item/armor/document.ts
  src/module/item/container/document.ts
  src/module/item/equipment/document.ts
  static/templates/chat/armor-card.hbs
  static/templates/chat/backpack-card.hbs
  static/templates/chat/consumable-card.hbs
  static/templates/chat/equipment-card.hbs
  static/templates/chat/weapon-card.hbs
Labels: pr: bugfix

#6770 Fix item alterations being applied multiple times to ephemeral effects
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix

#6769 Prevent double data preparation of embedded items
  src/module/actor/base.ts
  src/module/item/armor/document.ts
  src/module/item/base.ts
  src/module/item/weapon/document.ts
Labels: pr: enhancement

#6771 Further detach from V9 `ActorData` class
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  types/foundry/client/documents/actor.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/data/data/actor-data.d.ts
  types/foundry/common/documents/actor.d.ts
Labels: pr: foundry v10, pr: types update

#6777 Detach item flags from `ItemData`
  src/module/actor/character/data/types.ts
  src/module/actor/creature/data.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/hazard/data.ts
  src/module/actor/loot/data.ts
  src/module/actor/npc/data.ts
  src/module/actor/party/data.ts
  src/module/actor/vehicle/data.ts
  src/module/item/action/data.ts
  src/module/item/affliction/data.ts
  src/module/item/affliction/document.ts
  src/module/item/ancestry/data.ts
  src/module/item/armor/data.ts
  src/module/item/background/data.ts
  src/module/item/base.ts
  src/module/item/book/data.ts
  src/module/item/class/data.ts
  src/module/item/condition/data.ts
  src/module/item/consumable/data.ts
  src/module/item/container/data.ts
  src/module/item/data/base.ts
  src/module/item/deity/data.ts
  src/module/item/effect/data.ts
  src/module/item/effect/document.ts
  src/module/item/equipment/data.ts
  src/module/item/feat/data.ts
  src/module/item/heritage/data.ts
  src/module/item/kit/data.ts
  src/module/item/lore/data.ts
  src/module/item/melee/data.ts
  src/module/item/melee/document.ts
  src/module/item/physical/data.ts
  src/module/item/spell/data.ts
  src/module/item/treasure/data.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  types/foundry/client/documents/item.d.ts
  types/foundry/common/data/data/item-data.d.ts
  types/foundry/common/data/data/token-data.d.ts
  types/foundry/common/documents/item.d.ts
Labels: pr: foundry v10, pr: types update

#6772 Fix roll formatting in Elemental Ammunition
  packs/data/equipment.db/elemental-ammunition-greater.json
  packs/data/equipment.db/elemental-ammunition-lesser.json
  packs/data/equipment.db/elemental-ammunition-moderate.json
Labels: pr: data update

#6779 Localize toggle suboption labels on PC sheet
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: bugfix

#6780 Fix creation of damage instances for fixed heightened overlays
  src/module/item/spell/sheet.ts
  static/templates/items/spell-overlay.hbs
Labels: pr: bugfix

#6782 Set evaluated roll to "pf2e.damageRoll" hook
  src/module/system/damage/damage.ts
Labels: pr: bugfix

#6787 Hide mystified item traits and price
  src/module/actor/base.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/actor/vehicle/sheet.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/effect/document.ts
  src/module/system/conditions/manager.ts
  src/module/system/conditions/types.ts
  static/templates/actors/partials/conditions.hbs
  static/templates/actors/partials/item-summary.hbs
  static/templates/system/effects-panel.hbs
Labels: pr: bugfix, pr: refactor

#6781 Identify "hidden" results for Dice so Nice
  src/module/system/damage/roll.ts
Labels: pr: enhancement

#6784 Add scope to roll option rule element
  src/module/rules/rule-element/roll-option.ts
  src/module/rules/synthetics.ts
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: enhancement

#6788 Only show roll notes for adjusted degree of success
  src/module/system/check/check.ts
Labels: pr: bugfix

#6789 Prevent GM notes button from appearing on variant spell sheets
  src/module/item/sheet/base.ts
Labels: pr: bugfix

#6794 Disallow blank `SlugField`s
  src/module/system/schema-data-fields.ts
Labels: pr: bugfix

#6792 Conditionally hide fields on armor shield irrelevant to shields
  static/templates/items/armor-details.hbs
Labels: ui/ux

#6796 Link Mindshift trait to its description
  src/scripts/config/index.ts
Labels: pr: data update

#6640 Brushup Barbarian Rage automation
  packs/data/classfeatures.db/animal-instinct.json
  packs/data/classfeatures.db/ape-animal-instinct.json
  packs/data/classfeatures.db/bear-animal-instinct.json
  packs/data/classfeatures.db/black-dragon-instinct.json
  packs/data/classfeatures.db/blue-dragon-instinct.json
  packs/data/classfeatures.db/brass-dragon-instinct.json
  packs/data/classfeatures.db/bronze-dragon-instinct.json
  packs/data/classfeatures.db/bull-animal-instinct.json
  packs/data/classfeatures.db/cat-animal-instinct.json
  packs/data/classfeatures.db/copper-dragon-instinct.json
  packs/data/classfeatures.db/deer-animal-instinct.json
  packs/data/classfeatures.db/dragon-instinct.json
  packs/data/classfeatures.db/frog-animal-instinct.json
  packs/data/classfeatures.db/fury-instinct.json
  packs/data/classfeatures.db/giant-instinct.json
  packs/data/classfeatures.db/gold-dragon-instinct.json
  packs/data/classfeatures.db/green-dragon-instinct.json
  packs/data/classfeatures.db/instinct.json
  packs/data/classfeatures.db/rage.json
  packs/data/classfeatures.db/red-dragon-instinct.json
  packs/data/classfeatures.db/shark-animal-instinct.json
  packs/data/classfeatures.db/silver-dragon-instinct.json
  packs/data/classfeatures.db/snake-animal-instinct.json
  packs/data/classfeatures.db/spirit-instinct.json
  packs/data/classfeatures.db/superstition-instinct.json
  packs/data/classfeatures.db/white-dragon-instinct.json
  packs/data/classfeatures.db/wolf-animal-instinct.json
  packs/data/feats.db/advanced-fury.json
  packs/data/feats.db/barbarian-dedication.json
  packs/data/feats.db/barbarian-resiliency.json
  packs/data/feats.db/basic-fury.json
  packs/data/feats.db/instinct-ability.json
  packs/data/feats.db/juggernauts-fortitude.json
  packs/data/paizo-pregens.db/popcorn.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/830-condense-instincts.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  static/lang/re-en.json
Labels: pr: data migration, pr: data update

#6755 Move cleric doctrine data to enable homebrew
  packs/data/classfeatures.db/cloistered-cleric.json
  packs/data/classfeatures.db/doctrine.json
  packs/data/classfeatures.db/first-doctrine.json
  packs/data/classfeatures.db/warpriest.json
  packs/data/iconics.db/kyra-level-1.json
  packs/data/iconics.db/kyra-level-3.json
  packs/data/iconics.db/kyra-level-5.json
  packs/data/kingmaker-bestiary.db/tristian-level-1.json
  packs/data/kingmaker-bestiary.db/tristian-level-10.json
  packs/data/paizo-pregens.db/eteleon.json
  packs/data/paizo-pregens.db/kellsti.json
  packs/data/paizo-pregens.db/kyra-beginner-box.json
  packs/data/paizo-pregens.db/lavanna-saltspray.json
  packs/data/paizo-pregens.db/ufi.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/831-cleric-doctrines.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  static/lang/re-en.json
Labels: pr: data migration, pr: data update

#6773 Update Ambrost Mugland's Eroding Bullet inventory item
  packs/data/outlaws-of-alkenstar-bestiary.db/ambrost-mugland.json
Labels: pr: data update

#6800 Run sort on localization files
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#6795 Add item-alteration option of physical-item rarity
  src/module/rules/rule-element/mixins.ts
Labels: pr: enhancement

#6791 Change Rule Element UI setting to one that controls player access
  src/module/item/sheet/base.ts
  static/lang/en.json
Labels: pr: enhancement

#6804 Fix `CreaturePF2e#visionLevel`
  src/module/actor/creature/document.ts
Labels: pr: bugfix

#6805 Fix setting schema versions on newly created actors and items
  src/module/actor/helpers.ts
  src/module/item/base.ts
Labels: pr: bugfix

#6803 Fix unlocked lower value conditions out-prioritizing higher value ones
  src/module/actor/base.ts
  src/module/item/condition/document.ts
Labels: pr: bugfix

#6806 Allow Strike REs to have zero dice
  src/module/rules/rule-element/strike.ts
Labels: pr: bugfix

#6810 Fix `CompendiumBrowser#openSpellTab` using `number`s instead of `string`s for level
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/data.ts
Labels: pr: bugfix

#6807 Tune avoidance of double data preparation
  src/module/actor/base.ts
  src/module/item/base.ts
Labels: pr: bugfix

#6802 Add ability to track items from GrantItem rule element
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/grant-item/schema.ts
Labels: pr: enhancement

#6819 Don't increase existing conditions when dragging new ones
  src/module/actor/base.ts
  src/module/actor/sheet/base.ts
  src/module/item/condition/document.ts
Labels: pr: bugfix

#6821 Fill missing generic param in Game interface merge declaration
  src/global.d.ts
Labels: pr: bugfix, pr: types update

#6822 Append numeric badge values to condition names
  src/module/canvas/token/object.ts
  src/module/item/condition/document.ts
Labels: pr: bugfix

#6824 Add "wornfootwear" to physical-item usages
  src/module/item/physical/usage.ts
  static/lang/en.json
Labels: pr: bugfix

#6826 Add singular string for rest for the night hit points
  src/scripts/macros/rest-for-the-night.ts
  static/lang/en.json
Labels: localization, pr: data update

#6827 Remove unused listener on NPC sheet
  src/module/actor/npc/sheet.ts
Labels: pr: housekeeping

#6828 Remove redundant save options in save event handler
  src/module/chat-message/listeners/cards.ts
Labels: pr: housekeeping

#6829 Show persistent damage dialog when dragging a condition link
  src/module/actor/base.ts
Labels: pr: bugfix, pr: enhancement

#6825 Fix usage of Swim Fins
  packs/data/equipment.db/swim-fins.json
Labels: pr: data update

#6814 Add effects for Wyrm Claw
  packs/data/equipment-effects.db/effect-wyrm-claw-armor-greater.json
  packs/data/equipment-effects.db/effect-wyrm-claw-armor-major.json
  packs/data/equipment-effects.db/effect-wyrm-claw-armor.json
  packs/data/equipment.db/wyrm-claw-greater.json
  packs/data/equipment.db/wyrm-claw-major.json
  packs/data/equipment.db/wyrm-claw.json
Labels: pr: data update

#6833 Refactor initial filtering of Compendium Browser tabs
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/compendium-browser/data.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/action.ts
  src/module/apps/compendium-browser/tabs/base.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
  src/module/apps/compendium-browser/tabs/spell.ts
Labels: pr: refactor

#6835 Super up in all calls to `RuleElementPF2e._validateModel`
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix

#6836 Fix name of Gunslinger deed Break Them Down
  packs/data/actions.db/break-them-down.json
  packs/data/classfeatures.db/greater-deed.json
  packs/data/classfeatures.db/way-of-the-triggerbrand.json
Labels: pr: data update

#6837 Remove `UUIDUtils.fromUuid`
  src/module/actor/base.ts
  src/module/actor/helpers.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/hotbar.ts
  src/module/apps/sidebar/compendium-directory.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base.ts
  src/module/item/heritage/sheet.ts
  src/module/item/kit/sheet.ts
  src/module/item/sheet/rule-elements/grant-item-form.ts
  src/module/migration/migrations/823-heritage-ancestry-slug.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/system/action-macros/crafting/craft.ts
  src/module/system/action-macros/crafting/repair.ts
  src/module/system/action-macros/crafting/select-item.ts
  src/scripts/macros/raise-a-shield.ts
  src/util/uuid-utils.ts
Labels: pr: housekeeping

#6834 Reset actors more frequently during encounter events
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
Labels: pr: bugfix

#6838 Fix descriptions with non-bolded Activate. Fix descriptions of some spellguns.
  packs/data/equipment.db/apricot-of-bestial-might.json
  packs/data/equipment.db/bargainers-instrument.json
  packs/data/equipment.db/bewildering-spellgun.json
  packs/data/equipment.db/black-tendril-shot-greater.json
  packs/data/equipment.db/black-tendril-shot-lesser.json
  packs/data/equipment.db/black-tendril-shot-moderate.json
  packs/data/equipment.db/brightbloom-posy-major.json
  packs/data/equipment.db/conrasu-coin-arbiter.json
  packs/data/equipment.db/conrasu-coin-bythos.json
  packs/data/equipment.db/drake-rifle-acid.json
  packs/data/equipment.db/drake-rifle-cold.json
  packs/data/equipment.db/drake-rifle-electricity.json
  packs/data/equipment.db/drake-rifle-fire.json
  packs/data/equipment.db/drake-rifle-poison.json
  packs/data/equipment.db/effervescent-decoction.json
  packs/data/equipment.db/energizing-treat.json
  packs/data/equipment.db/familiar-morsel.json
  packs/data/equipment.db/forgetful-ink.json
  packs/data/equipment.db/garrote-bolt.json
  packs/data/equipment.db/mana-rattler-liniment.json
  packs/data/equipment.db/moonlit-spellgun-greater.json
  packs/data/equipment.db/moonlit-spellgun-lesser.json
  packs/data/equipment.db/moonlit-spellgun-major.json
  packs/data/equipment.db/moonlit-spellgun-minor.json
  packs/data/equipment.db/moonlit-spellgun-moderate.json
  packs/data/equipment.db/mutagenic-renovator.json
  packs/data/equipment.db/necrobinding-serum.json
  packs/data/equipment.db/neophytes-fipple.json
  packs/data/equipment.db/potion-patch-greater.json
  packs/data/equipment.db/potion-patch-lesser.json
  packs/data/equipment.db/potion-patch-moderate.json
  packs/data/equipment.db/reapers-spellgun.json
  packs/data/equipment.db/sparking-spellgun-greater.json
  packs/data/equipment.db/sparking-spellgun-lesser.json
  packs/data/equipment.db/sparking-spellgun-moderate.json
  packs/data/equipment.db/spiritual-warhorn-greater.json
  packs/data/equipment.db/spiritual-warhorn-lesser.json
  packs/data/equipment.db/spiritual-warhorn-major.json
  packs/data/equipment.db/spiritual-warhorn-moderate.json
  packs/data/equipment.db/stags-helm.json
  packs/data/equipment.db/starless-scope-lens.json
  packs/data/equipment.db/talespinners-lyre.json
  packs/data/equipment.db/torrent-spellgun-greater.json
  packs/data/equipment.db/torrent-spellgun-lesser.json
  packs/data/equipment.db/torrent-spellgun-major.json
  packs/data/equipment.db/torrent-spellgun-moderate.json
  packs/data/equipment.db/vermin-repellent-agent-greater.json
  packs/data/equipment.db/vermin-repellent-agent-lesser.json
  packs/data/equipment.db/vermin-repellent-agent-major.json
  packs/data/equipment.db/vermin-repellent-agent-moderate.json
  packs/data/equipment.db/watchful-portrait.json
  packs/data/equipment.db/whelming-scrimshaw.json
  packs/data/equipment.db/wind-ocarina.json
  packs/data/kingmaker-bestiary.db/the-stag-lord.json
Labels: pr: data update

#6840 Fix sorting tagify item traits
  src/module/sheet/helpers.ts
Labels: pr: bugfix

#6818 Ensure dromedary camel case of Choice Set flags
  packs/data/backgrounds.db/magical-experiment.json
  packs/data/bestiary-effects.db/effect-bittersweet-dreams.json
  packs/data/bestiary-effects.db/effect-inspire-envoy.json
  packs/data/bestiary-effects.db/effect-mutilating-bite.json
  packs/data/bestiary-effects.db/effect-sixfold-flurry.json
  packs/data/boons-and-curses.db/nocticula-moderate-curse.json
  packs/data/campaign-effects.db/gebs-blessing.json
  packs/data/feat-effects.db/effect-brightness-seeker.json
  packs/data/feats.db/fighting-horn.json
  packs/data/feats.db/greater-augmentation.json
  packs/data/feats.db/lesser-augmentation.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/832-choice-set-flags.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: data update

#6843 Fix regression when retrieving heightened spell level for roll options
  src/module/item/base.ts
Labels: pr: bugfix

#6842 Move `NPCPF2e#getBaseLevel` to getter
  src/module/actor/npc/document.ts
Labels: pr: refactor

#6844 Set source from mindless trait's mental immunity
  src/module/actor/creature/helpers.ts
Labels: pr: bugfix

#6839 Add splash damage link to Scarlet Mist. Remove implicit persistent from bleed damage links.
  packs/data/equipment.db/sanguine-mutagen-greater.json
  packs/data/equipment.db/sanguine-mutagen-lesser.json
  packs/data/equipment.db/sanguine-mutagen-major.json
  packs/data/equipment.db/sanguine-mutagen-moderate.json
  packs/data/equipment.db/scarlet-mist.json
  packs/data/gatewalkers-bestiary.db/skin-beetle-swarm.json
  packs/data/gatewalkers-bestiary.db/skin-beetle.json
  packs/data/iconics.db/feiya-level-5.json
  packs/data/iconics.db/seoni-level-1.json
  packs/data/iconics.db/seoni-level-5.json
Labels: pr: data update

#6845 Add Automation to the Raptor Guard Wight
  packs/data/extinction-curse-bestiary.db/raptor-guard-wight.json
  static/lang/re-en.json
Labels: source: adventure path, pr: data update

#6847 Allow checks as the source of damage rolls
  src/module/system/damage/damage.ts
  src/module/system/damage/types.ts
Labels: pr: enhancement

#6848 Set IDs of tracked items in actor flag
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: enhancement

#6849 Add class features for initial weapon modifications
  packs/data/classfeatures.db/blunt-shot.json
  packs/data/classfeatures.db/complex-simplicity.json
  packs/data/classfeatures.db/dynamic-weighting.json
  packs/data/classfeatures.db/entangling-form.json
  packs/data/classfeatures.db/hampering-spikes.json
  packs/data/classfeatures.db/hefty-composition.json
  packs/data/classfeatures.db/modular-head.json
  packs/data/classfeatures.db/pacification-tools.json
  packs/data/classfeatures.db/razor-prongs.json
  packs/data/classfeatures.db/segmented-frame.json
  packs/data/classfeatures.db/weapon-innovation.json
  static/icons/features/classes/blunt-shot.webp
  static/icons/features/classes/complex-simplicity.webp
  static/icons/features/classes/dynamic-weighting.webp
  static/icons/features/classes/entangling-form.webp
  static/icons/features/classes/hampering-spikes.webp
  static/icons/features/classes/hefty-composition.webp
  static/icons/features/classes/modular-head.webp
  static/icons/features/classes/pacification-tools.webp
  static/icons/features/classes/razor-prongs.webp
  static/icons/features/classes/segmented-frame.webp
  static/lang/re-en.json
Labels: pr: data entry, pr: data update

#6850 Fix rule elements on Segmented Frame and Modular Head
  packs/data/classfeatures.db/modular-head.json
  packs/data/classfeatures.db/segmented-frame.json
  static/lang/re-en.json
Labels: pr: data update

#6852 Suppress RE warnings when actor is cloned and has no `_id`
  src/module/rules/rule-element/base.ts
Labels: ui/ux

#6801 Fix typo in Brightness Seeker
  packs/data/feats.db/brightness-seeker.json
Labels: pr: data update

#6324 Improve character sheet crafting tab
  src/module/actor/character/crafting/entry.ts
  src/module/actor/character/crafting/formula.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/consumable/document.ts
  src/styles/actor/character/_crafting.scss
  static/lang/en.json
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/actors/crafting-entry-alchemical.hbs
  static/templates/actors/crafting-entry-list.hbs
Labels: pr: enhancement

#6856 Create tiny items when crafted by tiny PCs
  src/module/actor/character/crafting/helpers.ts
Labels: pr: bugfix

#6857 Append buttons to open compendium browser from sidebar classes
  src/module/apps/compendium-browser/index.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/apps/sidebar/item-directory.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-actor-directory.ts
Labels: pr: enhancement, pr: refactor

#6862 Add Ghost Touch rune REs to Ghost Dedication
  packs/data/feats.db/ghost-dedication.json
Labels: pr: data update

#6860 Fix localized string for Slayer's Presence
  packs/data/feats.db/slayers-presence.json
  packs/data/spell-effects.db/spell-effect-elephant-form.json
  static/lang/re-en.json
Labels: pr: data update

#6866 Fix spell level in Wand of Overflowing Life description
  packs/data/equipment.db/wand-of-overflowing-life-3rd-level-spell.json
  packs/data/equipment.db/wand-of-overflowing-life-4th-level-spell.json
  packs/data/equipment.db/wand-of-overflowing-life-5th-level-spell.json
  packs/data/equipment.db/wand-of-overflowing-life-6th-level-spell.json
  packs/data/equipment.db/wand-of-overflowing-life-7th-level-spell.json
  packs/data/equipment.db/wand-of-overflowing-life-8th-level-spell.json
Labels: pr: data update

#6861 Fix barbarian localizations
  packs/data/classfeatures.db/dragon-instinct.json
  packs/data/classfeatures.db/superstition-instinct.json
  static/lang/re-en.json
Labels: pr: data update

#6873 Fix crafting of items without a variable quantity
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#6872 Fix resetting of spell slots and display of signature spell button
  static/templates/actors/spellcasting-spell-list.hbs
Labels: pr: bugfix

#6875 Fix toggle listener on NPC sheet
  src/module/actor/sheet/base.ts
  src/module/rules/synthetics.ts
  static/templates/actors/character/tabs/actions.hbs
  static/templates/actors/npc/tabs/main.hbs
Labels: pr: bugfix

#6876 Fix display of roll mode in check dialog
  src/module/system/check/check.ts
  src/module/system/check/dialog.ts
Labels: pr: bugfix

#6877 Don't register GM Vision keybind when GM Vision module is enabled
  src/scripts/hooks/ready.ts
  src/scripts/register-keybindings.ts
Labels: pr: enhancement

#6878 Don't attempt to sluggify strings consisting of only a hyphen
  src/util/misc.ts
Labels: pr: bugfix

#6867 Include bulk in roll options
  src/module/item/weapon/document.ts
Labels: pr: enhancement

#6871 Add Bullet Dancer Stance effect
  packs/data/actions.db/bullet-dancer-stance.json
  packs/data/feat-effects.db/stance-bullet-dancer-stance.json
Labels: pr: data update

#6869 Override damage type of deadly dice when main damage type is changed
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#6879 Grant Commune with Nature from Read the Land feat
  packs/data/feats.db/read-the-land.json
Labels: pr: data update

#6881 Fix regression with functionality of Show Slotless Levels
  src/module/actor/creature/sheet.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/types.ts
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/spellcasting-spell-list.hbs
Labels: pr: bugfix

#6855 Add list of core icons to check against while building packs
  packs/scripts/core-icons.json
  packs/scripts/packman/compendium-pack.ts
Labels: pr: enhancement

#6885 Remove "Use Assurance" checkbox from Earn Income dialog
  src/scripts/macros/earn-income/helpers.ts
Labels: pr: bugfix

#6882 Make loot inventory controls fixed-width
  static/templates/actors/loot/inventory.hbs
Labels: ui/ux

#6893 Remove extraneous word from Constricting Hall Lose Form description
  packs/data/pathfinder-dark-archive.db/constricting-hall.json
Labels: pr: data update

#6892 Rebuild Popcorn pregen
  packs/data/paizo-pregens.db/popcorn.json
Labels: pr: data update

#6890 Use "light" and "negligible" for bulk in roll options
  src/module/item/weapon/document.ts
Labels: pr: bugfix

#6766 Fix inline roll in sunlight Healing
  packs/data/ancestryfeatures.db/sunlight-healing.json
Labels: pr: data update

#6900 Fix missing dragon instinct localization
  static/lang/re-en.json
Labels: pr: data update

#6901 Fix predicate statement in Weapon Innovation choice set
  packs/data/classfeatures.db/weapon-innovation.json
Labels: pr: data update

#6897 Standardize on "leveled" rather than "levelled"
  packs/data/actions.db/anadi-venom.json
  packs/data/actions.db/barbed-quills.json
  packs/data/actions.db/breath-weapon-acid-cone.json
  packs/data/actions.db/breath-weapon-acid-line.json
  packs/data/actions.db/breath-weapon-cold-cone.json
  packs/data/actions.db/breath-weapon-cold-line.json
  packs/data/actions.db/breath-weapon-electricity-cone.json
  packs/data/actions.db/breath-weapon-electricity-line.json
  packs/data/actions.db/breath-weapon-fire-cone.json
  packs/data/actions.db/breath-weapon-fire-line.json
  packs/data/actions.db/breath-weapon-negative-cone.json
  packs/data/actions.db/breath-weapon-negative-line.json
  packs/data/actions.db/breath-weapon-piercing-cone.json
  packs/data/actions.db/breath-weapon-piercing-line.json
  packs/data/actions.db/breath-weapon-poison-cone.json
  packs/data/actions.db/breath-weapon-poison-line.json
  packs/data/actions.db/energy-emanation-acid.json
  packs/data/actions.db/energy-emanation-cold.json
  packs/data/actions.db/energy-emanation-electricity.json
  packs/data/actions.db/energy-emanation-fire.json
  packs/data/actions.db/toxic-skin.json
  packs/data/feats.db/defensive-needles.json
  packs/data/feats.db/dragons-breath.json
  packs/data/feats.db/quill-spray.json
  packs/data/heritages.db/fruit-leshy.json
Labels: pr: data update

#6902 Fix Barbed Quills leveled damage type
  packs/data/actions.db/barbed-quills.json
Labels: pr: data update

#6898 Release Notes 4.9.0
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#6883 Run aura effect UUIDs through `#resolveInjectedProperties`
  src/module/rules/rule-element/aura.ts
Labels: pr: enhancement

#6905 Add deprecation paths for properties and methods used by TAH
  src/module/actor/base.ts
  src/module/item/spellcasting-entry/document.ts
Labels: pr: bugfix

#6904 Migrate Surprise Attack, Dread striker, & Precision edge to add/fix REs
  packs/data/classfeatures.db/precision.json
  packs/data/classfeatures.db/surprise-attack.json
  packs/data/feats.db/surprise-attack.json
  packs/data/iconics.db/merisiel-level-1.json
  packs/data/iconics.db/merisiel-level-3.json
  packs/data/iconics.db/merisiel-level-5.json
  packs/data/kingmaker-bestiary.db/ekundayo-level-1.json
  packs/data/kingmaker-bestiary.db/ekundayo-level-6.json
  packs/data/kingmaker-bestiary.db/nok-nok-level-1.json
  packs/data/kingmaker-bestiary.db/nok-nok-level-5.json
  packs/data/paizo-pregens.db/kaako-ashfeather.json
  packs/data/paizo-pregens.db/merisiel-beginner-box.json
  packs/data/paizo-pregens.db/muruwa.json
  packs/data/paizo-pregens.db/quizrel.json
  packs/data/paizo-pregens.db/reaching-rings.json
  packs/data/paizo-pregens.db/zeah.json
  packs/data/paizo-pregens.db/zerryd.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/833-add-rogue-toys-fix-precision.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  static/lang/re-en.json
Labels: pr: data migration, pr: data update

#6906 Hold off on sending deprecation notices
  src/module/actor/base.ts
  src/module/item/spellcasting-entry/document.ts
Labels: ui/ux

#6907 Run AdjustModifier predicates through `resolveInjectedProperties`
  src/module/rules/rule-element/adjust-modifier.ts
Labels: pr: enhancement

#6908 Release Notes 4.9.1
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping
