Repository foundryvtt/pf2e, pull requests merged in 2023-09, with the labels that each got.

#9723 Add automation for NPC Bleed for Lamashtu, Impromptu Toxin, Iron Command, Powerful Uppercut, Smite Good
  packs/agents-of-edgewatch-bestiary/norgorberite-poisoner.json
  packs/blood-lords-bestiary/seldeg-bheldis.json
  packs/fists-of-the-ruby-phoenix-bestiary/golarions-finest-han.json
  packs/kingmaker-bestiary/darivan.json
  packs/stolen-fate-bestiary/drustan.json
Labels: pr: data update

#9724 Add automation for NPC Fleeting Blossoms, Gnash, Gnashing Bite, Retaliate, Swinging Spear
  packs/pathfinder-bestiary-3/severed-head.json
  packs/pathfinder-bestiary-3/toshigami.json
  packs/rage-of-elements-bestiary/murajau.json
  packs/stolen-fate-bestiary/bhanyada-scavenger.json
  packs/strength-of-thousands-bestiary/thorn-guardian.json
Labels: pr: data update

#9725 Brush up Geist's Haunt and Elk's Hoof
  packs/book-of-the-dead-bestiary/geist.json
  packs/quest-for-the-frozen-flame-bestiary/elk.json
Labels: pr: data update

#9735 Add automation for Shatterling's Blood-Fueled Titter and Wrent Dicaspiron's Flay
  packs/agents-of-edgewatch-bestiary/shatterling.json
  packs/agents-of-edgewatch-bestiary/wrent-dicaspiron.json
Labels: pr: data update

#9737 Add inline checks to several NPC abilities
  packs/abomination-vaults-bestiary/wrin-sivinxi.json
  packs/agents-of-edgewatch-bestiary/bregdi.json
  packs/agents-of-edgewatch-bestiary/cobbleswarm-aoe.json
  packs/agents-of-edgewatch-bestiary/minchgorm.json
  packs/blood-lords-bestiary/ruby.json
  packs/blood-lords-bestiary/shadow-leydroth.json
  packs/book-of-the-dead-bestiary/ecorche.json
  packs/crown-of-the-kobold-king-bestiary/tallow-guardian.json
  packs/equipment/void-mirror.json
  packs/extinction-curse-bestiary/cu-sith.json
  packs/fists-of-the-ruby-phoenix-bestiary/golarions-finest-brartork.json
  packs/fists-of-the-ruby-phoenix-bestiary/ran-to-level-14.json
  packs/fists-of-the-ruby-phoenix-bestiary/ran-to-level-16.json
  packs/fists-of-the-ruby-phoenix-bestiary/ran-to-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/takatorra-daitengu-form.json
  packs/highhelm-bestiary/graul.json
  packs/kingmaker-bestiary/enormous-dragonfly.json
  packs/kingmaker-bestiary/hargulka.json
  packs/kingmaker-bestiary/irahkatu.json
  packs/kingmaker-bestiary/the-dancing-lady.json
  packs/npc-gallery/prisoner.json
  packs/outlaws-of-alkenstar-bestiary/clockwork-puppeteer.json
  packs/pathfinder-bestiary-2/ahuizotl.json
  packs/pathfinder-bestiary-2/baobhan-sith.json
  packs/pathfinder-bestiary-2/cave-fisher.json
  packs/pathfinder-bestiary-2/culdewen.json
  packs/pathfinder-bestiary-2/fire-yai.json
  packs/pathfinder-bestiary-2/giant-dragonfly.json
  packs/pathfinder-bestiary-2/hodag.json
  packs/pathfinder-bestiary-2/leydroth.json
  packs/pathfinder-bestiary-2/rusalka.json
  packs/pathfinder-bestiary-3/animated-trebuchet.json
  packs/pathfinder-bestiary-3/cobbleswarm.json
  packs/pathfinder-bestiary-3/krampus.json
  packs/pathfinder-bestiary-3/sturzstromer.json
  packs/pathfinder-bestiary/pit-fiend.json
  packs/pfs-season-1-bestiary/meleeka-sanvara-1-2.json
  packs/pfs-season-1-bestiary/meleeka-sanvara-3-4.json
  packs/pfs-season-1-bestiary/zombie-flesh-golem-3-4.json
  packs/pfs-season-1-bestiary/zombie-flesh-golem-5-6.json
  packs/pfs-season-2-bestiary/cobbleswarm-b5.json
  packs/pfs-season-2-bestiary/master-sergeant-morgroar-3-4.json
  packs/pfs-season-2-bestiary/master-sergeant-morgroar-5-6.json
  packs/pfs-season-2-bestiary/young-ahuizotl.json
  packs/pfs-season-3-bestiary/umbral-cu-sith.json
  packs/pfs-season-3-bestiary/weakened-cobbleswarm.json
  packs/quest-for-the-frozen-flame-bestiary/tar-zombie-mammoth.json
  packs/strength-of-thousands-bestiary/drenchdead.json
  packs/strength-of-thousands-bestiary/urbel.json
  packs/strength-of-thousands-bestiary/worknesh.json
Labels: pr: data update

#9747 Refresh copies of Ice Storm and Lightning Storm
  packs/blood-lords-bestiary/creeping-crone.json
  packs/pathfinder-bestiary-3/storm-hag.json
  packs/pathfinder-bestiary-3/winter-hag.json
  packs/pfs-season-2-bestiary/chesjilawa-jadwiga-karina-7-8.json
  packs/pfs-season-4-bestiary/coven-winter-hag.json
  packs/quest-for-the-frozen-flame-bestiary/jesseri-the-hailstorm.json
  packs/spell-effects/spell-effect-corrosive-body-heightened-9th.json
  packs/spell-effects/spell-effect-corrosive-body.json
  packs/spell-effects/spell-effect-fiery-body-9th-level.json
  packs/spell-effects/spell-effect-fiery-body.json
Labels: pr: data update

#9745 Add automation for Chromatic Ooze's Chromatic Shift and Chromatic Slam
  packs/strength-of-thousands-bestiary/chromatic-ooze.json
  static/lang/re-en.json
Labels: pr: data update

#9741 Fix resolvables for @Damage roll notes
  src/module/system/damage/damage.ts
  src/module/system/text-editor.ts
Labels: pr: bugfix

#9728 Support roller:party for inline check rolls
  src/scripts/ui/inline-roll-links.ts
  static/lang/en.json
Labels: pr: enhancement, pr:kingmaker

#9750 Fix css variable in item input styling
  src/styles/item/_index.scss
Labels: pr: bugfix

#9752 Fix compendium browser ability search by category
  src/module/apps/compendium-browser/tabs/action.ts
Labels: pr: bugfix

#9751 Convert proficiency rank colors to CSS variables
  src/styles/_colors.scss
  src/styles/actor/character/_actions.scss
  src/styles/actor/character/_proficiency-ranks.scss
  src/styles/actor/party/_index.scss
  src/styles/actor/party/_overview.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/actor/tabs/_actions.scss
Labels: pr: refactor

#9753 Define `system.details.alliance` in all actor-source interfaces
  src/module/actor/character/data.ts
  src/module/actor/creature/data.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/hazard/data.ts
  src/module/actor/loot/data.ts
  src/module/actor/npc/data.ts
  src/module/actor/party/data.ts
  src/module/actor/party/document.ts
  static/template.json
Labels: pr: refactor, pr: types update

#9754 await calls to `TokenAura#notifyActors`
  src/module/scene/helpers.ts
Labels: pr: bugfix

#9756 Recheck auras when alliance is manually changed
  src/module/actor/base.ts
  src/module/actor/helpers.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/data/collections/compendium-collection.d.ts
Labels: pr: bugfix

#9755 Eliminate unnecessary calls to `AuraData#containsToken`
  src/module/scene/helpers.ts
  src/module/scene/token-document/aura/index.ts
Labels: pr: refactor

#9762 Flip value of `playerRestricted` in party sheet
  src/module/actor/party/sheet.ts
Labels: pr: bugfix

#9763 Remove errant stripe in trait tags section of sheets
  src/styles/_tags.scss
Labels: pr: bugfix

#9759 Fix damage links in Wooden Fists
  packs/spells/wooden-fists.json
Labels: pr: data update

#9764 Release Notes 5.4.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#9768 Fill some jsdoc in TempHP RE
  src/module/rules/rule-element/index.ts
  src/module/rules/rule-element/temp-hp.ts
Labels: pr: refactor

#9770 Fix darkness of physical damage text color
  src/styles/_colors.scss
Labels: pr: bugfix

#9767 Move clown car management to helper class
  src/module/canvas/token/clown-car.ts
  src/scripts/hooks/render-token-hud.ts
Labels: pr: refactor

#9749 Remove scroll case and sheath from actors
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/iconics/lem-level-1.json
  packs/iconics/lem-level-5.json
  packs/iconics/merisiel-level-1.json
  packs/iconics/merisiel-level-3.json
  packs/iconics/merisiel-level-5.json
  packs/iconics/seoni-level-1.json
  packs/iconics/seoni-level-5.json
  packs/kingmaker-bestiary/jubilost-level-1.json
  packs/kingmaker-bestiary/jubilost-level-8.json
  packs/npc-gallery/adept.json
  packs/npc-gallery/navigator.json
  packs/npc-gallery/tax-collector.json
  packs/paizo-pregens/savshin-starwatcher.json
Labels: pr: data update

#9716 Add automation for Umbral Dragon's Ghost Bane
  packs/blood-lords-bestiary/urbulinex.json
  packs/pathfinder-bestiary-2/adult-umbral-dragon-spellcaster.json
  packs/pathfinder-bestiary-2/adult-umbral-dragon.json
  packs/pathfinder-bestiary-2/ancient-umbral-dragon-spellcaster.json
  packs/pathfinder-bestiary-2/ancient-umbral-dragon.json
  packs/pathfinder-bestiary-2/young-umbral-dragon-spellcaster.json
  packs/pathfinder-bestiary-2/young-umbral-dragon.json
Labels: pr: data update

#9758 Normalize damage links in Burning Grasp description
  packs/pathfinder-bestiary/efreeti.json
  packs/pfs-season-2-bestiary/burned-out-efreet.json
  packs/pfs-season-2-bestiary/run-down-efreet.json
  packs/pfs-season-4-bestiary/farah-al-saleel-3-4.json
  packs/pfs-season-4-bestiary/farah-al-saleel-5-6.json
  packs/rage-of-elements-bestiary/ifrit-shuyookh.json
Labels: pr: data update

#9769 Add spell effect for Wooden Fists
  packs/spell-effects/spell-effect-wooden-fists.json
  packs/spells/wooden-fists.json
Labels: pr: data update

#9771 Set explicit `onCreate` event options in TempHP REs
  packs/equipment-effects/effect-numbing-tonic-greater.json
  packs/equipment-effects/effect-numbing-tonic-lesser.json
  packs/equipment-effects/effect-numbing-tonic-major.json
  packs/equipment-effects/effect-numbing-tonic-minor.json
  packs/equipment-effects/effect-numbing-tonic-moderate.json
  packs/feat-effects/effect-aura-junction-wood.json
  packs/feat-effects/stance-arcane-cascade.json
Labels: pr: data update

#9772 Add inline healing links to Qxal's Blood Siphon
  packs/pfs-season-1-bestiary/manifestation-of-qxal-3-4.json
  packs/pfs-season-1-bestiary/manifestation-of-qxal-5-6.json
  packs/pfs-season-2-bestiary/qxal-the-thorned-monarch.json
Labels: pr: data update

#9774 Add automation for Groplit's Flammable Grease and add effect for Incendiary Dollop
  packs/bestiary-effects/effect-incendiary-dollop.json
  packs/quest-for-the-frozen-flame-bestiary/groplit.json
Labels: pr: data update

#9775 Fix formatting in Glass River Midge Attach
  packs/pfs-season-1-bestiary/elite-glass-river-midge.json
  packs/pfs-season-1-bestiary/glass-river-midge.json
Labels: pr: data update

#9777 Update core types concerning token animation
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/pixi/placeables/primary-canvas-objects/token-mesh.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
Labels: pr: types update

#9776 Fix damage of Frostbite
  packs/spells/frostbite.json
Labels: pr: data update

#9773 Animate clown car loading/unloading tokens and flip of HUD arrow
  src/module/canvas/token/clown-car.ts
  src/module/scene/token-document/aura/index.ts
  src/module/scene/token-document/aura/types.ts
  src/scripts/hooks/render-token-hud.ts
  src/styles/ui/_token-hud.scss
Labels: ui/ux

#9781 Consolidate sourcing of sheet rarity/traits/alignment/size tags
  src/styles/_tags.scss
  src/styles/actor/npc/_index.scss
  src/styles/actor/npc/data-entry/_index.scss
  src/styles/item/_index.scss
  src/styles/legacy/_pf2e.scss
  static/templates/actors/hazard/partials/header.hbs
  static/templates/actors/npc/partials/header.hbs
  static/templates/actors/npc/sheet.hbs
  static/templates/items/sheet.hbs
Labels: pr: bugfix, pr: refactor

#9782 Restore legacy boost row in attribute builder
  src/module/actor/character/sheet.ts
  src/styles/actor/character/_attribute-builder.scss
  static/templates/actors/character/attribute-builder.hbs
Labels: pr: bugfix

#9757 Brush up some FFoF actors
  packs/bestiary-effects/effect-active-mutagen.json
  packs/one-shot-bestiary/darius.json
  packs/one-shot-bestiary/grazing-deer.json
  packs/one-shot-bestiary/scented-candle-homunculus.json
Labels: pr: data update

#9783 Add inline checks to several NPC abilities
  packs/actions/drink-blood.json
  packs/agents-of-edgewatch-bestiary/shredskin.json
  packs/bestiary-family-ability-glossary/vampire-basic-drink-blood.json
  packs/bestiary-family-ability-glossary/vampire-jiang-shi-basic-drain-qi.json
  packs/bestiary-family-ability-glossary/vampire-nosferatu-drink-blood.json
  packs/bestiary-family-ability-glossary/vampire-strigoi-drink-essence.json
  packs/bestiary-family-ability-glossary/vampire-strigoi-progenitor-drink-essence.json
  packs/bestiary-family-ability-glossary/vampire-true-drink-blood.json
  packs/bestiary-family-ability-glossary/vampire-vetalarana-basic-drain-thoughts.json
  packs/bestiary-family-ability-glossary/vampire-vetalarana-manipulator-drain-thoughts.json
  packs/bestiary-family-ability-glossary/vampire-vrykolakas-drink-blood.json
  packs/blood-lords-bestiary/harmony-in-agony.json
  packs/blood-lords-bestiary/hyrune-loxenna.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/blood-lords-bestiary/vampire-guardian.json
  packs/blood-lords-bestiary/vampire-taviah.json
  packs/blood-lords-bestiary/weeping-jack.json
  packs/book-of-the-dead-bestiary/minister-of-tumult.json
  packs/book-of-the-dead-bestiary/provincial-jiang-shi.json
  packs/book-of-the-dead-bestiary/shredskin.json
  packs/book-of-the-dead-bestiary/vetalarana-emergent.json
  packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
  packs/extinction-curse-bestiary/faceless-butcher.json
  packs/extinction-curse-bestiary/the-vanish-man.json
  packs/extinction-curse-bestiary/zinogyvaz.json
  packs/feats/freeze-it.json
  packs/impossible-lands-bestiary/skinskitter.json
  packs/kingmaker-bestiary/kundal.json
  packs/kingmaker-bestiary/river-elasmosaurus.json
  packs/mwangi-expanse-bestiary/asanbosam.json
  packs/pathfinder-bestiary-2/culdewen.json
  packs/pathfinder-bestiary-2/elasmosaurus.json
  packs/pathfinder-bestiary-2/froghemoth.json
  packs/pathfinder-bestiary-2/vrykolakas-ancient.json
  packs/pathfinder-bestiary-2/vrykolakas-master.json
  packs/pathfinder-bestiary-2/vrykolakas-spawn.json
  packs/pathfinder-bestiary-3/blood-hag.json
  packs/pathfinder-bestiary-3/mobogo.json
  packs/pathfinder-bestiary-3/nosferatu-malefactor.json
  packs/pathfinder-bestiary-3/nosferatu-overlord.json
  packs/pathfinder-bestiary/vampire-count.json
  packs/pathfinder-bestiary/vampire-mastermind.json
  packs/pathfinder-bestiary/vampire-spawn-rogue.json
  packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
  packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
  packs/pfs-season-4-bestiary/cunning-vampire-spawn.json
  packs/pfs-season-4-bestiary/evasive-vampire-count.json
  packs/pfs-season-4-bestiary/weak-cunning-vampire-spawn.json
  packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
  packs/quest-for-the-frozen-flame-bestiary/everburning-mammoth.json
  packs/shadows-at-sundown-bestiary/aliriel.json
  packs/shadows-at-sundown-bestiary/bishop-keppira-dbear.json
  packs/shadows-at-sundown-bestiary/strigoi-progenitor.json
  packs/shadows-at-sundown-bestiary/strigoi-servant.json
  packs/stolen-fate-bestiary/gegnir.json
  packs/stolen-fate-bestiary/kannijo.json
  packs/strength-of-thousands-bestiary/gambulami.json
Labels: pr: data update

#9780 Implement Nanite Surge status bonus as a second self remove effect
  packs/feat-effects/effect-nanite-surge-bonus.json
  packs/feat-effects/effect-nanite-surge.json
  packs/feats/nanite-surge.json
Labels: pr: data update

#9746 Add automation for Gallowdead's Charge Chain
  packs/book-of-the-dead-bestiary/gallowdead.json
Labels: pr: data update

#9788 Extend clown car deposit range to 15ft
  src/module/canvas/token/clown-car.ts
Labels: pr: enhancement

#9789 Allow weapon-trait adjustments of NPC attacks to be NPC attack traits
  src/module/rules/rule-element/adjust-strike.ts
Labels: pr: enhancement

#9790 Include roll options passed to strike methods when rolling
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
Labels: pr: bugfix

#9798 Update `Document#delete` signature to reflect it can return `undefined`
  src/module/item/base.ts
  types/foundry/common/abstract/document.d.ts
Labels: pr: types update

#9799 Take better control of spin animation during clown car token retrieval
  src/module/canvas/token/clown-car.ts
  src/module/canvas/token/object.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/pixi/core/interaction/canvas-animation.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
Labels: pr: enhancement

#9807 Add Capritellix
  packs/rage-of-elements-bestiary/capritellix.json
Labels: pr: data entry

#9779 Fix Wooden Fists spell effect to add Fist attack
  packs/spell-effects/spell-effect-wooden-fists.json
Labels: pr: data update

#9787 Remove unneeded roll link from Rousing Splash
  packs/spells/rousing-splash.json
Labels: pr: data update

#9791 Automate reach for Gallowdead's Charge Chain
  packs/book-of-the-dead-bestiary/gallowdead.json
Labels: pr: data update

#9794 Set roll type on several healing links
  packs/crown-of-the-kobold-king-bestiary/dark-talon-kobold.json
  packs/crown-of-the-kobold-king-bestiary/drazmorg-the-damned.json
  packs/equipment/ambrosia-of-undying-hope.json
  packs/equipment/belt-of-regeneration.json
  packs/equipment/knapsack-of-halflingkind-greater.json
  packs/equipment/knapsack-of-halflingkind.json
  packs/equipment/lovers-knot.json
  packs/equipment/panacea-fruit.json
  packs/extinction-curse-bestiary/urushil.json
  packs/extinction-curse-bestiary/xilvirek.json
  packs/feats/high-speed-regeneration.json
  packs/kingmaker-bestiary/darivan.json
  packs/kingmaker-bestiary/oleg.json
  packs/outlaws-of-alkenstar-bestiary/clearwater-cleaner.json
  packs/outlaws-of-alkenstar-bestiary/dewey-daystar.json
  packs/outlaws-of-alkenstar-bestiary/follower-of-shumfallow.json
  packs/outlaws-of-alkenstar-bestiary/prairie-drake.json
  packs/outlaws-of-alkenstar-bestiary/roxy.json
  packs/pathfinder-bestiary-2/eremite.json
  packs/pathfinder-bestiary-2/norn.json
  packs/pathfinder-bestiary-2/peryton.json
  packs/pfs-season-1-bestiary/zombie-riding-horse.json
  packs/pfs-season-1-bestiary/zombie-warhorse.json
  packs/pfs-season-3-bestiary/carved-mourner.json
  packs/pfs-season-3-bestiary/grieving-carved-mourner.json
  packs/pfs-season-3-bestiary/pelagastr-tail.json
  packs/pfs-season-3-bestiary/peryton-arctic.json
  packs/pfs-season-3-bestiary/peryton-heretical.json
  packs/pfs-season-3-bestiary/peryton-rifle-mutation.json
  packs/pfs-season-3-bestiary/thick-pelagastr-tail.json
  packs/pfs-season-3-bestiary/weeping-carved-mourner.json
  packs/pfs-season-4-bestiary/suhko-1-2.json
  packs/pfs-season-4-bestiary/suhko-3-4.json
  packs/sky-kings-tomb-bestiary/krohan-possessed.json
  packs/stolen-fate-bestiary/diskrasia-the-sharp.json
  packs/stolen-fate-bestiary/fabrina-the-spinster.json
  packs/stolen-fate-bestiary/hala-the-rod.json
  packs/strength-of-thousands-bestiary/apocalypse-ant-swarm.json
  packs/strength-of-thousands-bestiary/tatterthread.json
Labels: pr: data update

#9795 Add effect for Therapeutic Snap Peas
  packs/equipment-effects/effect-therapeutic-snap-peas.json
  packs/equipment/therapeutic-snap-peas.json
Labels: pr: data update

#9797 Update automation for Spriggan's Enraged Growth and Bully's Bludgeon
  packs/kingmaker-bestiary/agai.json
  packs/pathfinder-bestiary-2/spriggan-bully.json
  packs/pathfinder-bestiary-2/spriggan-warlord.json
Labels: pr: data update

#9800 Fix some prototype token names
  packs/menace-under-otari-bestiary/hobgoblin-warrior-bb.json
  packs/pfs-season-1-bestiary/elite-glass-river-midge.json
  packs/pfs-season-1-bestiary/glass-river-midge.json
  packs/pfs-season-1-bestiary/metallic-sod-hound.json
  packs/pfs-season-1-bestiary/osprey.json
  packs/pfs-season-1-bestiary/skeleton-corporal.json
  packs/pfs-season-2-bestiary/daughter-of-cocytus-grunt.json
  packs/pfs-season-2-bestiary/daughter-of-cocytus-tough.json
  packs/pfs-season-2-bestiary/onyx-alliance-agent-7-8.json
  packs/pfs-season-2-bestiary/ygracix.json
  packs/pfs-season-3-bestiary/kobold-dragon-mage-pfs-3-99.json
  packs/pfs-season-3-bestiary/lightweight-animated-armor.json
  packs/pfs-season-4-bestiary/bloody-barber-thief.json
  packs/pfs-season-4-bestiary/farah-al-saleel-3-4.json
  packs/pfs-season-4-bestiary/farah-al-saleel-5-6.json
  packs/pfs-season-4-bestiary/mutated-scorpion.json
  packs/pfs-season-4-bestiary/runt-1-2.json
  packs/pfs-season-4-bestiary/runt-3-4.json
  packs/rage-of-elements-bestiary/asp-of-grief.json
  packs/rage-of-elements-bestiary/austral-the-south-wind.json
  packs/rage-of-elements-bestiary/boreal-the-north-wind.json
  packs/rage-of-elements-bestiary/eural-the-east-wind.json
  packs/rage-of-elements-bestiary/kizidhar-shuyookh.json
  packs/rage-of-elements-bestiary/zephyr-the-west-wind.json
  packs/sky-kings-tomb-bestiary/alchemist-ivy.json
  packs/sky-kings-tomb-bestiary/algerschmick.json
  packs/sky-kings-tomb-bestiary/blacknoon-apprentice.json
  packs/sky-kings-tomb-bestiary/fazil.json
  packs/sky-kings-tomb-bestiary/skibrellon.json
  packs/sky-kings-tomb-bestiary/sporeborn-skull.json
  packs/sky-kings-tomb-bestiary/stonemaker.json
  packs/sky-kings-tomb-bestiary/zivzeb.json
Labels: pr: data update

#9812 Move `PartyClownCar` to @scene/token-document
  src/module/actor/base.ts
  src/module/canvas/token/object.ts
  src/module/documents.ts
  src/module/scene/ambient-light-document.ts
  src/module/scene/document.ts
  src/module/scene/index.ts
  src/module/scene/token-document/actor-delta.ts
  src/module/scene/token-document/clown-car.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  src/scripts/hooks/load.ts
  src/scripts/hooks/render-token-hud.ts
  src/scripts/register-sheets.ts
  types/foundry/client/data/documents/actor.d.ts
Labels: pr: refactor

#9809 Set suboption flag to `null` if main value is false in RollOption RE
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/damage-dice.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/roll-note.ts
  src/module/rules/rule-element/roll-option.ts
Labels: pr: enhancement

#9810 Make single token update call in `PartyClownCar##retrieve`
  src/module/actor/base.ts
  src/module/apps/effects-panel.ts
  src/module/canvas/token/object.ts
  src/module/documents.ts
  src/module/scene/token-document/clown-car.ts
  src/module/scene/token-document/document.ts
  tests/mocks/actor.ts
  tests/mocks/token.ts
Labels: pr: refactor

#9813 Remove @module/documents.ts
  build/lib/types.ts
  src/global.ts
  src/module/active-effect.ts
  src/module/actor/actions/types.ts
  src/module/actor/base.ts
  src/module/actor/character/helpers.ts
  src/module/actor/character/sheet.ts
  src/module/actor/initiative.ts
  src/module/actor/item-transfer.ts
  src/module/actor/loot/document.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/party/document.ts
  src/module/actor/types.ts
  src/module/data.ts
  src/module/documents.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/equipment/document.ts
  src/module/item/melee/document.ts
  src/module/rules/helpers.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  src/module/scene/measured-template-document.ts
  tests/mocks/actor.ts
  tests/mocks/collection.ts
  tests/mocks/token.ts
Labels: pr: housekeeping

#9818 Prune false components entries from spell system data on extract
  build/lib/extractor.ts
Labels: pr: housekeeping

#9784 Add UI/UX enhancements to party stash tab
  src/module/actor/sheet/base.ts
  src/styles/actor/_coinage.scss
  src/styles/actor/_inventory.scss
  src/styles/actor/character/_inventory.scss
  src/styles/actor/npc/_inventory.scss
  src/styles/actor/party/_index.scss
  src/styles/actor/party/_inventory.scss
  static/lang/en.json
  static/templates/actors/character/tabs/inventory.hbs
  static/templates/actors/partials/inventory.hbs
  static/templates/actors/partials/item-line.hbs
  static/templates/actors/party/sheet.hbs
Labels: pr: enhancement, ui/ux

#9814 Conditionally set "item:magical" roll option for all item types
  src/module/item/base.ts
  src/module/item/melee/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
Labels: pr: bugfix

#9792 Highlight setting upon clicking "restricted" link in party sheet
  src/module/actor/party/sheet.ts
  src/module/system/settings/menu.ts
  types/foundry/common/types.d.ts
Labels: pr: enhancement, ui/ux

#9817 Add set of stop words to compendium search
  src/module/apps/compendium-browser/tabs/base.ts
  src/module/apps/sidebar/compendium-directory.ts
Labels: ui/ux

#9819 Use core icon for Jolt Coil
  packs/equipment-effects/effect-jolt-coil-armor-greater.json
  packs/equipment-effects/effect-jolt-coil-armor-major.json
  packs/equipment-effects/effect-jolt-coil-armor.json
  packs/equipment-effects/effect-jolt-coil-weapon-greater.json
  packs/equipment-effects/effect-jolt-coil-weapon-major.json
  packs/equipment-effects/effect-jolt-coil-weapon.json
  packs/equipment/jolt-coil-greater.json
  packs/equipment/jolt-coil-major.json
  packs/equipment/jolt-coil.json
Labels: pr: data update

#9796 fix token name of baby brine shark
  packs/pfs-season-5-bestiary/baby-brine-shark.json
Labels: pr: data update

#9822 Automate Fatal Bullet feat
  packs/feats/fatal-bullet.json
Labels: pr: data update

#9821 Add lighting automation to Jellyfish Lamp
  packs/equipment/jellyfish-lamp.json
Labels: pr: data update

#9820 Add effects for Grindlegrub Steak and Irondust Stew
  packs/equipment-effects/effect-grindlegrub-steak.json
  packs/equipment-effects/effect-irondust-stew.json
  packs/equipment/grindlegrub-steak.json
  packs/equipment/irondust-stew.json
Labels: pr: data update

#9816 Use core icons for some fire spells
  packs/spells/fire-ray.json
  packs/spells/fire-shield.json
  packs/spells/flame-vortex.json
  packs/spells/flaming-fusillade.json
Labels: pr: data update

#9823 Add light automation to Abysium Horror's Green Glow
  packs/rage-of-elements-bestiary/abysium-horror.json
Labels: pr: data update

#9804 Add spell effect for Anima Invocation
  packs/spell-effects/spell-effect-anima-invocation.json
  packs/spells/anima-invocation-modified.json
Labels: pr: data update

#9801 (pedrogrullada) Add spell effect for Phase Familiar
  packs/spell-effects/spell-effect-phase-familiar.json
  packs/spells/phase-familiar.json
Labels: pr: data update

#9827 Fix display of NPC attack modifiers that include predicated synthetics
  src/module/actor/helpers.ts
Labels: pr: bugfix

#9828 Include "magical" roll option for spells with no tradition
  src/module/item/base.ts
Labels: pr: bugfix

#9811 Standardize Meliosa's Leshy names and update automation
  packs/one-shot-bestiary/meliosas-leshy-golden-bamboo-leshy.json
  packs/one-shot-bestiary/meliosas-leshy-minkaian-honeysuckle-leshy.json
Labels: pr: data update

#9832 Fix display of attack modifier on familiar sheet
  src/styles/actor/familiar/_index.scss
  static/templates/actors/familiar-sheet.hbs
Labels: pr: bugfix

#9834 Fix more token names
  packs/pfs-season-2-bestiary/electric-lock-rune.json
  packs/pfs-season-3-bestiary/cleansing-torrent.json
  packs/pfs-season-3-bestiary/cooking-catastrophe.json
Labels: pr: data update

#9815 Add automation for Capritellix's Shift Mood skill bonus
  packs/rage-of-elements-bestiary/capritellix.json
  static/lang/re-en.json
Labels: pr: data update

#9835 Give explicit label to DC name of Stunning Fist inline roll link
  static/lang/re-en.json
Labels: pr: data update

#9831 Release Notes 5.4.3
  CHANGELOG.md
  package.json
  static/system.json
Labels: pr: housekeeping

#9833 Attempt to retrieve roll data for inline links via `dataset.itemUuid`
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: enhancement

#9837 Add additional kingdom features and tweaks
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/sheet.ts
  src/styles/actor/party/kingdom/_activities.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/actor/party/kingdom/_main.scss
  static/lang/kingmaker-en.json
  static/templates/actors/party/kingdom/main.hbs
  static/templates/actors/party/kingdom/sheet.hbs
Labels: pr:kingmaker

#9836 Update names and token names of Chariots
  packs/vehicles/chariot-heavy.json
  packs/vehicles/chariot-light.json
  packs/vehicles/sky-chariot-heavy.json
  packs/vehicles/sky-chariot-light.json
  packs/vehicles/sky-chariot-medium.json
Labels: pr: data update

#9838 Update some PFS token names
  packs/pfs-season-2-bestiary/perizia-7-8.json
  packs/pfs-season-3-bestiary/crushing-spirits-5-6.json
  packs/pfs-season-3-bestiary/crushing-spirits-7-8.json
  packs/pfs-season-3-bestiary/tadrun-1-2.json
  packs/pfs-season-3-bestiary/tadrun-3-4.json
  packs/pfs-season-4-bestiary/animated-dagger-3-4.json
  packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
  packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
  packs/pfs-season-4-bestiary/fascinating-lecture-1-2.json
  packs/pfs-season-4-bestiary/fascinating-lecture-3-4.json
  packs/pfs-season-4-bestiary/hidden-forest-bog-3-4.json
  packs/pfs-season-4-bestiary/hidden-forest-bog-5-6.json
  packs/pfs-season-4-bestiary/hidden-forest-bog-7-8.json
  packs/pfs-season-4-bestiary/liaskra-1-2.json
  packs/pfs-season-4-bestiary/liaskra-3-4.json
  packs/pfs-season-4-bestiary/nathatel-3-4.json
  packs/pfs-season-4-bestiary/nathatel-5-6.json
  packs/pfs-season-4-bestiary/nathatel-7-8.json
  packs/pfs-season-4-bestiary/pappy-draighean-5-6.json
  packs/pfs-season-4-bestiary/serraleth-7-8.json
  packs/pfs-season-4-bestiary/snakebush-1-2.json
  packs/pfs-season-4-bestiary/unbridled-necromantic-energy-1-2.json
  packs/pfs-season-4-bestiary/unbridled-necromantic-energy-3-4.json
  packs/pfs-season-4-bestiary/undead-nathatel-7-8.json
  packs/pfs-season-5-bestiary/augmented-azlanti-elemental-nexus-5-6.json
  packs/pfs-season-5-bestiary/azlanti-elemental-nexus-5-6.json
Labels: pr: data update

#9840 Update party travel labels to adhere to mechanics
  static/lang/en.json
  static/templates/actors/party/regions/exploration.hbs
Labels: ui/ux

#9841 Fix width constraint of lootable NPC sheet sidebar
  src/styles/actor/_index.scss
  static/templates/actors/npc/loot-sheet.hbs
Labels: pr: bugfix

#9846 Fix compendium browser rarity-tag coloration
  src/styles/packs/_tab.scss
  static/templates/compendium-browser/partials/bestiary.hbs
  static/templates/compendium-browser/partials/equipment.hbs
  static/templates/compendium-browser/partials/feat.hbs
  static/templates/compendium-browser/partials/hazard.hbs
  static/templates/compendium-browser/partials/spell.hbs
Labels: pr: bugfix

#9845 Add defense to Morlock Tinker inline check
  packs/abomination-vaults-bestiary/morlock-engineer.json
  packs/abomination-vaults-bestiary/warped-brew-morlock.json
  packs/pathfinder-bestiary-2/morlock.json
  packs/stolen-fate-bestiary/xiuli-cachu.json
Labels: pr: data update

#9848 Add effect for Rousing Splash
  packs/spell-effects/spell-effect-rousing-splash.json
  packs/spells/rousing-splash.json
Labels: pr: data update

#9851 Fix interactivity of roll-note form checkbox
  static/templates/items/rules/note.hbs
Labels: pr: bugfix

#9854 Make Simple NPC sheet available in production builds
  src/scripts/register-sheets.ts
  static/lang/en.json
  static/templates/actors/npc/simple-sheet.hbs
Labels: pr: new feature

#9853 Add option to include innerHTML in `createHTMLElement`
  src/module/actor/party/sheet.ts
  src/module/system/text-editor.ts
  src/util/dom.ts
Labels: pr: enhancement

#9855 Add remaining TV armor property runes
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data update

#9852 Fix party name input being editable to non-owners
  src/styles/actor/party/_index.scss
  static/templates/actors/party/sheet.hbs
Labels: pr: bugfix

#9847 Widen left/right border of paizo-style trait tags
  src/styles/_tags.scss
Labels: ui/ux

#9859 Refresh Tiger Stance on the Sajans
  packs/iconics/sajan-level-1.json
  packs/iconics/sajan-level-5.json
Labels: pr: data update

#9856 Add several more inline checks
  packs/actions/grim-swagger.json
  packs/adventure-specific-actions/appeal-to-shadowy-intruders.json
  packs/agents-of-edgewatch-bestiary/grospek-lavarsus.json
  packs/agents-of-edgewatch-bestiary/minchgorm.json
  packs/agents-of-edgewatch-bestiary/shristi-melipdra.json
  packs/bestiary-family-ability-glossary/secret-society-prepared-trap.json
  packs/equipment/cresset-of-grisly-interrogation.json
  packs/equipment/glass-cutter.json
  packs/equipment/handcuffs-average.json
  packs/equipment/handcuffs-good.json
  packs/equipment/handcuffs-superior.json
  packs/equipment/self-emptying-pocket.json
  packs/equipment/the-crows.json
  packs/extinction-curse-bestiary/daring-danika.json
  packs/feats/awesome-blow.json
  packs/feats/battle-prayer.json
  packs/feats/dazzling-bullet.json
  packs/feats/disarming-smile.json
  packs/feats/divine-disharmony.json
  packs/feats/explosive-death-drop.json
  packs/feats/gunpowder-gauntlet.json
  packs/feats/helts-spelldance.json
  packs/feats/leading-dance.json
  packs/feats/log-roll.json
  packs/feats/melodious-spell.json
  packs/feats/plant-evidence.json
  packs/feats/sabotage.json
  packs/feats/scare-to-death.json
  packs/feats/stay-down.json
  packs/feats/swift-elusion.json
  packs/feats/tumbling-strike.json
  packs/feats/unseat.json
  packs/feats/upset-balance.json
  packs/feats/watch-your-back.json
  packs/feats/whirling-knockdown.json
  packs/kingmaker-bestiary/grigori.json
  packs/kingmaker-bestiary/linzi-level-7.json
  packs/npc-gallery/surgeon.json
  packs/paizo-pregens/reaching-rings-level-4.json
  packs/pathfinder-bestiary-2/water-yai.json
  packs/pathfinder-bestiary-3/palace-skelm.json
  packs/pfs-season-4-bestiary/elite-palace-skelm-pfs-4-11.json
  packs/pfs-season-4-bestiary/transformed-bremix-7-8.json
Labels: pr: data update

#9844 Brush up NPC automation for Mark for Death and Dismantler. Add automation to Cursed King's Berserk.
  packs/abomination-vaults-bestiary/siora-fallowglade.json
  packs/impossible-lands-bestiary/cursed-king.json
  packs/monsters-of-myth-bestiary/ulistul.json
  packs/night-of-the-gray-death-bestiary/gray-gardener-assassin.json
  packs/night-of-the-gray-death-bestiary/zintaya-calbieste.json
Labels: pr: data update

#9860 Tweak basic (non-paizo-style) tag height
  src/styles/_tags.scss
Labels: ui/ux

#9858 Release Notes 5.4.4
  CHANGELOG.md
  package.json
  static/system.json
Labels: pr: housekeeping

#9864 Remove tag line-height styling from NPC sheet
  src/styles/actor/npc/_index.scss
Labels: ui/ux

#9857 Refactor note markup to use `createHTMLElement`
  src/module/notes.ts
  src/module/system/check/check.ts
  src/module/system/damage/damage.ts
  src/module/system/text-editor.ts
  src/scripts/ui/user-visibility.ts
  src/styles/ui/sidebar/chat/_index.scss
Labels: pr: enhancement, pr: refactor

#9865 Implement roll option retrieval for kingdom
  src/module/actor/party/document.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/types.ts
  src/module/item/campaign-feature/document.ts
Labels: pr: enhancement, pr:kingmaker

#9842 Handle NPC lootability without faking ownership level
  src/module/actor/loot/document.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/sheet.ts
  src/module/canvas/token/object.ts
  types/foundry/client/application/form-application/document-sheet/base.d.ts
Labels: pr: refactor

#9866 Add data for kingdom feats with very basic automation
  packs/kingmaker-features/kingdom-activities/create-a-masterpiece.json
  packs/kingmaker-features/kingdom-activities/new-leadership.json
  packs/kingmaker-features/kingdom-feats/civil-service.json
  packs/kingmaker-features/kingdom-feats/cooperative-leadership.json
  packs/kingmaker-features/kingdom-feats/crush-dissent.json
  packs/kingmaker-features/kingdom-feats/endure-anarchy.json
  packs/kingmaker-features/kingdom-feats/fame-and-fortune.json
  packs/kingmaker-features/kingdom-feats/fortified-fiefs.json
  packs/kingmaker-features/kingdom-feats/free-and-fair.json
  packs/kingmaker-features/kingdom-feats/insider-trading.json
  packs/kingmaker-features/kingdom-feats/inspiring-entertainment.json
  packs/kingmaker-features/kingdom-feats/kingdom-assurance.json
  packs/kingmaker-features/kingdom-feats/liquidate-resources.json
  packs/kingmaker-features/kingdom-feats/muddle-through.json
  packs/kingmaker-features/kingdom-feats/practical-magic.json
  packs/kingmaker-features/kingdom-feats/pull-together.json
  packs/kingmaker-features/kingdom-feats/quality-of-life.json
  packs/kingmaker-features/kingdom-feats/quick-recovery.json
  packs/kingmaker-features/kingdom-feats/skill-training.json
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/item/campaign-feature/document.ts
Labels: pr: data update, pr: enhancement, pr:kingmaker

#9861 Fix some malformed inline recharge rolls
  packs/abomination-vaults-bestiary/nhimbaloths-cutter.json
  packs/age-of-ashes-bestiary/vazgorlu.json
  packs/fists-of-the-ruby-phoenix-bestiary/flying-mountain-kaminari.json
  packs/fists-of-the-ruby-phoenix-bestiary/syndara-the-sculptor.json
  packs/highhelm-bestiary/grand-defender.json
  packs/kingmaker-bestiary/bloom-of-lamashtu.json
  packs/kingmaker-bestiary/fionn.json
  packs/kingmaker-bestiary/jurgrindor.json
  packs/kingmaker-bestiary/overgrown-viper-vine.json
  packs/monsters-of-myth-bestiary/somnalu.json
  packs/monsters-of-myth-bestiary/spectral-devil.json
  packs/pathfinder-bestiary-2/bralani.json
  packs/pathfinder-bestiary-2/derghodaemon.json
  packs/pathfinder-bestiary-2/glass-golem.json
  packs/pathfinder-bestiary-2/jotund-troll.json
  packs/pathfinder-bestiary-2/radiant-warden.json
  packs/pathfinder-bestiary-2/sandpoint-devil.json
  packs/pathfinder-bestiary-2/striding-fire.json
  packs/pathfinder-bestiary-2/thunderbird.json
  packs/pathfinder-bestiary-2/viper-vine.json
  packs/pfs-season-4-bestiary/infested-clockwork-vessel.json
  packs/pfs-season-4-bestiary/possessed-clockwork-vessel.json
  packs/stolen-fate-bestiary/aquatic-viper-vine.json
  packs/stolen-fate-bestiary/gegnir.json
Labels: pr: data update

#9869 Temporarily unlock rotation while party token is retrieving members
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#9878 Add module prop to kingdom schema
  src/module/actor/party/kingdom/schema.ts
Labels: pr:kingmaker

#9871 Limit visibility of auras outside of encounters
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/object.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/module/scene/document.ts
  src/module/scene/token-document/document.ts
Labels: ui/ux

#9879 Add tooltip to open kingdom sheet button
  src/module/actor/party/kingdom/model.ts
  static/lang/kingmaker-en.json
Labels: ui/ux, pr:kingmaker

#9877 Add rules-based vision override for individual scenes
  src/module/scene/data.ts
  src/module/scene/document.ts
  src/module/scene/sheet.ts
  src/scripts/config/index.ts
  src/styles/scene/_sheet.scss
  static/lang/en.json
  static/templates/scene/sheet-partials.hbs
Labels: pr: enhancement

#9881 Fix comment and template tooltip in scene RBV override
  src/module/scene/sheet.ts
  static/lang/en.json
  static/templates/scene/sheet-partials.hbs
Labels: pr: bugfix

#9882 Normalize capitalization of system setting names
  static/lang/en.json
Labels: ui/ux

#9880 Add support for kingdom phase summaries
  src/module/actor/party/kingdom/sheet.ts
  src/styles/actor/party/kingdom/_activities.scss
  static/lang/kingmaker-en.json
  static/templates/actors/party/kingdom/activities.hbs
Labels: ui/ux, pr:kingmaker

#9883 Add resource points to kingdom header
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/kingdom/sheet.ts
  src/styles/actor/party/kingdom/_index.scss
  static/lang/kingmaker-en.json
  static/templates/actors/party/kingdom/sheet.hbs
Labels: pr: kingmaker

#9872 Use core icons for some equipment
  packs/equipment-effects/effect-grasp-of-droskar.json
  packs/equipment-effects/effect-tallowheart-mass.json
  packs/equipment-effects/effect-therapeutic-snap-peas.json
  packs/equipment-effects/effect-voice-of-oceans.json
  packs/equipment/anchor-of-aquatic-exploration.json
  packs/equipment/conch-of-otherworldly-seas.json
  packs/equipment/grasp-of-droskar.json
  packs/equipment/inquisitive-quill.json
  packs/equipment/necrobinding-serum.json
  packs/equipment/owlbear-egg.json
  packs/equipment/shell-of-easy-breathing-greater.json
  packs/equipment/shell-of-easy-breathing.json
  packs/equipment/soulspeaker.json
  packs/equipment/tallowheart-mass.json
  packs/equipment/therapeutic-snap-peas.json
Labels: pr: data update

#9885 Fix computating kingdom vacancy penalties
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/values.ts
Labels: pr: bugfix, pr: kingmaker

#9886 Add hearing range to system scene settings
  src/module/scene/data.ts
  src/module/scene/document.ts
  src/module/scene/sheet.ts
  src/module/scene/token-document/document.ts
  src/styles/scene/_sheet.scss
  static/lang/en.json
  static/templates/scene/sheet-partials.hbs
Labels: pr: enhancement

#9887 Visual tweaks to kingdom leaders and control dc
  src/module/actor/party/kingdom/sheet.ts
  src/styles/actor/party/kingdom/_activities.scss
  src/styles/actor/party/kingdom/_main.scss
  static/templates/actors/party/kingdom/main.hbs
Labels: ui/ux, pr: kingmaker

#9863 Remove inline damage link from Pummeling Rubble spell, use core icon
  packs/spells/pummeling-rubble.json
Labels: pr: data update

#9868 Improve Flame Wisp effect counter
  packs/spell-effects/spell-effect-flame-wisp.json
Labels: pr: data update

#9870 Remove template link from Dread Wraith's Draining Presence ability
  packs/pathfinder-bestiary-2/dread-wraith.json
Labels: pr: data update

#9893 Update type definition of `Notifications` class
  src/module/actor/character/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/chat-message/document.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base.ts
  src/module/item/deity/sheet.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/scripts/macros/earn-income/macro.ts
  src/scripts/macros/encouraging-words.ts
  src/scripts/macros/hotbar.ts
  src/scripts/macros/steel-your-resolve.ts
  src/scripts/macros/treat-wounds.ts
  src/scripts/system/remigrate.ts
  types/foundry/client/ui/notifications.d.ts
Labels: pr: bugfix, pr: types update

#9896 Have `UserVisibility.process` only access `HTMLElement`s
  src/module/system/text-editor.ts
  src/scripts/ui/user-visibility.ts
  src/util/dom.ts
Labels: pr: refactor

#9891 Rename `Statistic#ability` to `Statistic#attribute`
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/data.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/document.ts
  src/module/actor/hazard/data.ts
  src/module/actor/hazard/document.ts
  src/module/actor/initiative.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/document.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/actor/values.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/rules/rule-element/special-statistic.ts
  src/module/system/statistic/armor-class.ts
  src/module/system/statistic/data.ts
  src/module/system/statistic/hit-points.ts
  src/module/system/statistic/index.ts
  src/scripts/config/index.ts
Labels: remaster

#9897 Hide spell DCs when appropriate
  src/module/item/spell/document.ts
  src/styles/legacy/_chat.scss
  static/lang/en.json
  static/templates/chat/spell-card.hbs
Labels: pr: bugfix

#9898 Set party level to rounded mean of PC member levels
  src/module/actor/party/document.ts
Labels: pr: enhancement

#9899 Fix calculation of counteract total modifier
  src/module/item/spell/document.ts
Labels: pr: bugfix

#9903 Minor refactor to check creation
  src/module/system/text-editor.ts
Labels: pr: refactor

#9909 Support campaign features for inline checks
  src/scripts/ui/inline-roll-links.ts
Labels: pr: enhancement, pr: kingmaker

#9907 Manage token-aura rendering from `Token#_refreshVisibility`
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/object.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/module/scene/token-document/aura/types.ts
  src/module/scene/token-document/clown-car.ts
  types/foundry/client/pixi/placeables-layer/base.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
Labels: pr: refactor

#9908 Restore acceptance of numeric DCs in `StatisticCheck#roll`
  src/module/system/statistic/index.ts
Labels: pr: bugfix

#9910 Remove some references to Flat-Footed and fix some broken links
  packs/bestiary-effects/effect-riding-zogototaru.json
  packs/equipment-effects/aura-demons-knot.json
  packs/equipment-effects/effect-demons-knot.json
  packs/equipment/caverns-heart.json
  packs/equipment/demons-knot.json
  packs/equipment/sigil-of-the-first-clan.json
  packs/feats/statue.json
  packs/sky-kings-tomb-bestiary/ashrin.json
  packs/sky-kings-tomb-bestiary/hryngar-assassin.json
  packs/sky-kings-tomb-bestiary/hryngar-breccia-squad.json
  packs/sky-kings-tomb-bestiary/juvenile-cave-worm-azure.json
  packs/sky-kings-tomb-bestiary/juvenile-cave-worm-crimson.json
  packs/sky-kings-tomb-bestiary/juvenile-cave-worm-glacial.json
  packs/sky-kings-tomb-bestiary/juvenile-cave-worm-gray.json
  packs/sky-kings-tomb-bestiary/juvenile-cave-worm-rock.json
  packs/sky-kings-tomb-bestiary/repelling-surge.json
  packs/sky-kings-tomb-bestiary/stoneriver.json
  packs/sky-kings-tomb-bestiary/zogototaru.json
Labels: pr: data update

#9911 Consolidate redundant encounter-tracker style sheets
  src/styles/ui/sidebar/_combat-tracker.scss
  src/styles/ui/sidebar/_encounter-tracker.scss
  src/styles/ui/sidebar/_index.scss
Labels: pr: refactor

#9902 Fix inline perception check icon
  src/module/system/text-editor.ts
Labels: pr: data update

#9904 Add effects for Spiny Lodestone
  packs/equipment-effects/effect-spiny-lodestone-armor-greater.json
  packs/equipment-effects/effect-spiny-lodestone-armor-major.json
  packs/equipment-effects/effect-spiny-lodestone-armor.json
  packs/equipment-effects/effect-spiny-lodestone-weapon-greater.json
  packs/equipment-effects/effect-spiny-lodestone-weapon-major.json
  packs/equipment-effects/effect-spiny-lodestone-weapon.json
  packs/equipment/spiny-lodestone-greater.json
  packs/equipment/spiny-lodestone-major.json
  packs/equipment/spiny-lodestone.json
Labels: pr: data update

#9894 Fix effect for Sand Form
  packs/spell-effects/spell-effect-sand-form.json
  packs/spells/sand-form.json
Labels: pr: data update

#9901 Add icons to some spellhearts
  packs/equipment-effects/effect-jyotis-feather-armor-greater.json
  packs/equipment-effects/effect-jyotis-feather-armor-major.json
  packs/equipment-effects/effect-jyotis-feather-armor.json
  packs/equipment-effects/effect-jyotis-feather-weapon-greater.json
  packs/equipment-effects/effect-jyotis-feather-weapon-major.json
  packs/equipment-effects/effect-jyotis-feather-weapon.json
  packs/equipment-effects/effect-rime-crystal-armor-greater.json
  packs/equipment-effects/effect-rime-crystal-armor-major.json
  packs/equipment-effects/effect-rime-crystal-armor.json
  packs/equipment-effects/effect-rime-crystal-weapon-greater.json
  packs/equipment-effects/effect-rime-crystal-weapon-major.json
  packs/equipment-effects/effect-rime-crystal-weapon.json
  packs/equipment-effects/effect-sanguine-fang-armor-greater.json
  packs/equipment-effects/effect-sanguine-fang-armor-major.json
  packs/equipment-effects/effect-sanguine-fang-armor.json
  packs/equipment-effects/effect-sanguine-fang-weapon-greater.json
  packs/equipment-effects/effect-sanguine-fang-weapon-major.json
  packs/equipment-effects/effect-sanguine-fang-weapon.json
  packs/equipment-effects/effect-wyrm-claw-armor-greater.json
  packs/equipment-effects/effect-wyrm-claw-armor-major.json
  packs/equipment-effects/effect-wyrm-claw-armor.json
  packs/equipment/jyotis-feather-greater.json
  packs/equipment/jyotis-feather-major.json
  packs/equipment/jyotis-feather.json
  packs/equipment/rime-crystal-greater.json
  packs/equipment/rime-crystal-major.json
  packs/equipment/rime-crystal.json
  packs/equipment/sanguine-fang-greater.json
  packs/equipment/sanguine-fang-major.json
  packs/equipment/sanguine-fang.json
  packs/equipment/wyrm-claw-greater.json
  packs/equipment/wyrm-claw-major.json
  packs/equipment/wyrm-claw.json
Labels: pr: data update

#9884 Add effect for Conductive Weapon
  packs/spell-effects/spell-effect-conductive-weapon.json
  packs/spells/conductive-weapon.json
  static/lang/re-en.json
Labels: pr: data update

#9892 Fix effect for Ferrous Form
  packs/spell-effects/spell-effect-ferrous-form.json
  packs/spells/ferrous-form.json
Labels: pr: data update

#9912 Mark type-only imports in encounter/document.ts
  src/module/encounter/document.ts
Labels: pr: housekeeping

#9919 Organize `Statistic` and related classes into separate files
  src/module/actor/base.ts
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/actor/familiar/document.ts
  src/module/actor/hazard/document.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/types.ts
  src/module/actor/vehicle/data.ts
  src/module/actor/vehicle/document.ts
  src/module/encounter/combatant.ts
  src/module/system/statistic/armor-class.ts
  src/module/system/statistic/base.ts
  src/module/system/statistic/full.ts
  src/module/system/statistic/hit-points.ts
  src/module/system/statistic/index.ts
Labels: pr: refactor

#9921 Nudge rollup to define `CharacterPF2e` later
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/actor/character/feats.ts
  src/module/actor/character/tab-manager.ts
  src/module/actor/creature/config.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/sheet/popups/distribute-coins-popup.ts
  src/module/actor/sheet/popups/manage-attack-proficiencies.ts
  src/module/actor/sheet/trick-magic-item-popup.ts
  src/module/actor/spellcasting.ts
  src/module/item/ancestry/document.ts
  src/module/item/class/document.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/weapon/helpers.ts
  src/module/system/statistic/hit-points.ts
  src/scripts/macros/steel-your-resolve.ts
Labels: pr: housekeeping

#9920 Support kingmaker campaign features in compendium browser
  src/module/actor/character/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/apps/compendium-browser/data.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/loader.ts
  src/module/apps/compendium-browser/tabs/campaignFeature.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/apps/compendium-browser/tabs/index.ts
  src/styles/actor/party/kingdom/_activities.scss
  static/lang/en.json
  static/templates/actors/character/partials/feat-slot.hbs
  static/templates/actors/character/tabs/effects.hbs
  static/templates/actors/character/tabs/feats.hbs
  static/templates/actors/party/kingdom/advancement.hbs
  static/templates/compendium-browser/compendium-browser.hbs
Labels: pr: enhancement, pr: kingmaker

#9915 Add automation to Cape of Illumination. Fix rarity and usage of Cape of Illumination and Cape of Grand Entrances.
  packs/equipment/cape-of-grand-entrances.json
  packs/equipment/cape-of-illumination-greater.json
  packs/equipment/cape-of-illumination-lesser.json
  packs/equipment/cape-of-illumination-moderate.json
Labels: pr: data update

#9917 Use core icons for Sack of Rotten Fruit and Putrid Sack of Rotting Fruit. Refresh copies.
  packs/equipment/putrid-sack-of-rotting-fruit.json
  packs/equipment/sack-of-rotten-fruit.json
  packs/paizo-pregens/reaching-rings-level-4.json
  packs/paizo-pregens/reaching-rings.json
Labels: pr: data update

#9926 Localize bundled conditions only if Babele is running
  src/module/system/conditions/manager.ts
Labels: pr: bugfix

#9929 Use better icon for Chain Lightning spell
  static/icons/spells/chain-lightning.webp
Labels: pr: data update

#9925 Add icon for Stickeytoe Grippli heritage
  packs/heritages/stickytoe-grippli.json
  static/icons/features/ancestry/stickeytoe-tripkee.webp
Labels: pr: data update

#9928 Add melee/ranged strike-specific domains to attack and damage rolls
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
  src/module/system/damage/weapon.ts
Labels: pr: enhancement

#9927 Extract modifier adjustments for kickback trait
  src/module/system/damage/weapon.ts
Labels: pr: bugfix
