Repository foundryvtt/pf2e, pull requests merged in 2023-12, with the labels that each got.

#11898 Prevent deletion keys from getting saved to armor on update
  src/module/item/armor/document.ts
Labels: pr: bugfix

#11884 Add automation to Ghost Ammunition
  packs/equipment/ghost-ammunition.json
Labels: pr: data update

#11868 Add light automation to Life-Saver Mail
  packs/equipment/life-saver-mail-greater.json
  packs/equipment/life-saver-mail.json
  static/lang/re-en.json
Labels: pr: data update

#11883 Add automation for Serithtial
  packs/equipment/serithtial.json
  static/lang/re-en.json
Labels: pr: data update

#11869 Add low-light vision automation to Moonlit Chain
  packs/equipment/moonlit-chain.json
  packs/rollable-tables/7th-level-permanent-items.json
  static/lang/re-en.json
Labels: pr: data update

#11900 Add actor-sheet-wide listener on `a[data-action]` elements
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/base.ts
  src/styles/actor/character/_proficiencies.scss
  src/styles/actor/character/_spellcasting.scss
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/character/tabs/proficiencies.hbs
  static/templates/actors/character/tabs/spellcasting.hbs
Labels: pr: bugfix, pr: refactor

#11903 Ensure `MeasuredTemplatePF2e`s have `pf2e` flags and (if inferable) `areaType`s
  src/module/scene/measured-template-document.ts
Labels: pr: bugfix

#11905 Fix Psychic Clarity of Focus
  packs/classfeatures/clarity-of-focus.json
Labels: pr: data update

#11901 Add missing inline check to Scholar's Bane
  packs/campaign-effects/effect-spirit-power-passion.json
  packs/gatewalkers-bestiary/scholars-bane.json
Labels: pr: data update

#11906 Fix handling of Clarity of Focus class feature in migration 889
  src/module/migration/migrations/889-remove-focus-max-increases.ts
Labels: pr: bugfix

#11909 Fix NaN check in TempHP RE
  src/module/rules/rule-element/temp-hp.ts
Labels: pr: bugfix

#11911 Remove no-longer-needed workaround of upstream issue
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/data/documents/token-document.d.ts
Labels: pr: refactor

#11914 Ensure `resetActors` operates each actor only once
  src/module/actor/helpers.ts
Labels: pr: bugfix

#11902 Clean up proficiencies tab CSS, change px units to em/rem
  src/styles/actor/character/_proficiencies.scss
  static/templates/actors/character/tabs/proficiencies.hbs
Labels: pr: refactor

#11910 Have `Statistic` ensure `${attribute}-based` domain when applicable
  src/module/actor/character/document.ts
  src/module/rules/rule-element/special-statistic.ts
  src/module/system/statistic/base.ts
  src/module/system/statistic/statistic.ts
Labels: pr: enhancement

#11912 Expand `resetActors` helper to optionally rerender tokens
  src/module/actor/helpers.ts
  src/module/encounter/document.ts
Labels: pr: enhancement

#11915 Fix Divine Health Predicate and add DoS adjustment
  packs/feats/divine-health.json
Labels: pr: data update

#11916 removes bold for actions after Activate
  packs/equipment/energy-breath-potion-acid-greater.json
  packs/equipment/energy-breath-potion-acid-lesser.json
  packs/equipment/energy-breath-potion-acid-moderate.json
  packs/equipment/energy-breath-potion-cold-greater.json
  packs/equipment/energy-breath-potion-cold-lesser.json
  packs/equipment/energy-breath-potion-cold-moderate.json
  packs/equipment/energy-breath-potion-electricity-greater.json
  packs/equipment/energy-breath-potion-electricity-lesser.json
  packs/equipment/energy-breath-potion-electricity-moderate.json
  packs/equipment/energy-breath-potion-fire-greater.json
  packs/equipment/energy-breath-potion-fire-lesser.json
  packs/equipment/energy-breath-potion-fire-moderate.json
  packs/equipment/energy-breath-potion-sonic-greater.json
  packs/equipment/energy-breath-potion-sonic-lesser.json
  packs/equipment/energy-breath-potion-sonic-moderate.json
  packs/equipment/redpitch-bomb-greater.json
  packs/equipment/redpitch-bomb-lesser.json
  packs/equipment/redpitch-bomb-major.json
  packs/equipment/redpitch-bomb-moderate.json
  packs/equipment/salve-of-antiparalysis-greater.json
Labels: pr: data update

#11917 Add effect for Heart of the Kaiju
  packs/feats/heart-of-the-kaiju.json
  packs/spell-effects/spell-effect-monstrosity-form-kaiju.json
Labels: pr: data update

#11918 Add effect for Aeon Stone (Sprouting)
  packs/equipment-effects/effect-aeon-stone-sprouting.json
  packs/equipment/aeon-stone-sprouting.json
Labels: pr: data update

#11920 Ensure same behavior between `SceneControl` and `@Template`-created lines
  src/module/canvas/layer/template.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/pixi/board.d.ts
  types/foundry/client/pixi/canvas-layer/base.d.ts
  types/foundry/client/pixi/canvas-layer/controls-layer.d.ts
  types/foundry/client/pixi/canvas-layer/grid-layer.d.ts
  types/foundry/client/pixi/layers/base/interaction-layer.d.ts
  types/foundry/client/pixi/layers/base/placeables-layer.d.ts
  types/foundry/client/pixi/layers/effects/visibility.d.ts
  types/foundry/client/pixi/layers/placeables/lighting.d.ts
  types/foundry/client/pixi/layers/placeables/token.d.ts
  types/foundry/client/pixi/placeables/measured-template.d.ts
  types/foundry/common/abstract/data.d.ts
Labels: pr: bugfix

#11922 Fix rarity of Aeon Stone (Sprouting)
  packs/equipment/aeon-stone-sprouting.json
Labels: pr: data update

#11924 Make damage from vitalizing rune persistent
  src/module/item/physical/runes.ts
Labels: pr: data update, remaster

#11925 Update vite and small number of other packages
  package-lock.json
  package.json
Labels: pr: housekeeping

#11926 Release Notes 5.10.0
  CHANGELOG.md
  package.json
  static/system.json
Labels: pr: housekeeping

#11930 Release Notes 5.10.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#11937 Refresh Rations on Level 1 Kyra
  packs/iconics/kyra-level-1.json
Labels: pr: data update

#11936 Fix broken action macro link in Disarm Action
  packs/actions/disarm.json
Labels: pr: data update

#11933 Add rudimentary support for army alliance
  src/module/actor/army/document.ts
  src/module/actor/army/sheet.ts
  src/styles/actor/army/_index.scss
  static/lang/kingmaker-en.json
  static/templates/actors/army/sheet.hbs
Labels: pr: enhancement, kingmaker

#11939 Fix bulk of Spacious Pouches
  packs/equipment/bag-of-devouring-type-i.json
  packs/equipment/bag-of-devouring-type-ii.json
  packs/equipment/bag-of-devouring-type-iii.json
  packs/equipment/bag-of-weasels.json
  packs/equipment/sleeves-of-storage.json
  packs/equipment/spacious-pouch-type-i.json
  packs/equipment/spacious-pouch-type-ii.json
  packs/equipment/spacious-pouch-type-iii.json
  packs/equipment/spacious-pouch-type-iv.json
  src/module/migration/migrations/901-reorganize-bulk-data.ts
Labels: pr: data update

#11938 Add effect for Staff of Illumination
  packs/equipment-effects/effect-staff-of-illumination.json
  packs/equipment/staff-of-illumination.json
Labels: pr: data update

#11923 Add resistance to Aeon Stone (Preserving)
  packs/equipment/aeon-stone-preserving.json
  src/scripts/config/iwr.ts
Labels: pr: data update

#11875 Update Many Action Macros with Remaster Text
  static/lang/action-en.json
Labels: pr: data update, remaster

#11944 Restore AC bonus and speed penalty fields in armor sheets
  static/templates/items/armor-details.hbs
Labels: pr: bugfix

#11947 Fix excessive grid-snapping for some shape types
  src/module/canvas/layer/template.ts
Labels: pr: bugfix

#11949 Fix rule element on Emblazon Armament (Shield) effect
  packs/feat-effects/effect-emblazon-armament-shield.json
Labels: pr: data update

#11950 Add placeholder to strength field in armor sheet
  static/templates/items/armor-details.hbs
Labels: ui/ux

#11962 Fix bulk and usage of Druid's Crown
  packs/equipment/druids-crown.json
Labels: pr: data update

#11963 Prevent bulk and size adjustments from saving upon closing item sheets
  src/module/item/armor/sheet.ts
  src/module/item/physical/document.ts
  src/module/item/physical/helpers.ts
  src/module/item/physical/sheet.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/sheet/helpers.ts
  src/styles/item/_index.scss
  static/lang/en.json
  static/templates/items/backpack-details.hbs
  static/templates/items/physical-sidebar.hbs
  static/templates/items/sheet.hbs
Labels: pr: bugfix, ui/ux

#11965 Sort army saves and move strike strike before buttons
  packs/kingmaker-features/army-tactics/toughened-soldiers.json
  src/module/actor/army/sheet.ts
  static/templates/actors/army/sheet.hbs
Labels: pr: data update, ui/ux, kingmaker

#11966 Use base hardness/max HP of specific magic shields if higher than material values
  src/module/item/shield/document.ts
Labels: pr: enhancement

#11970 Fix trio of migrated shield stat blocks
  packs/equipment/indestructible-shield.json
  packs/equipment/kizidhars-shield.json
  packs/equipment/lodestone-shield.json
  src/module/migration/migrations/899-armor-shields-to-shield-shields.ts
Labels: pr: bugfix, pr: data update

#11973 Release Notes 5.10.3
  CHANGELOG.md
  package.json
  static/system.json
Labels: pr: housekeeping

#11975 Redirect raise-a-shield macro to PC auxiliary action
  src/scripts/macros/raise-a-shield.ts
Labels: pr: bugfix, pr: refactor

#11972 Add toggles to army sheet (needs styling)
  packs/kingmaker-features/army-tactics/live-off-the-land.json
  static/lang/kingmaker-en.json
  static/templates/actors/army/sheet.hbs
Labels: pr: enhancement, kingmaker

#11979 Fix choice set prompts remaining open despite no options or drop zone
  src/module/rules/rule-element/choice-set/prompt.ts
  types/foundry/client/apps/app.d.ts
Labels: pr: bugfix

#11980 Don't throw error on PC sheet when navigation panel isn't found
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#11985 Set focus cap on NPCs during data preparation
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#11986 Use new Magic Hands rules
  src/scripts/macros/treat-wounds.ts
Labels: pr: bugfix, remaster

#11983 Fix Einherji Shield HP
  packs/pathfinder-bestiary-3/einherji.json
Labels: pr: data update

#11996 Fix targeting hazards via `Statistic`
  src/module/system/statistic/statistic.ts
Labels: pr: bugfix

#11994 Prevent integrated weapon data from being added to shields without integrated weapons
  src/module/item/shield/document.ts
  src/module/item/shield/sheet.ts
Labels: pr: bugfix

#11993 Iterative improvements to warfare subsystem's items
  packs/kingmaker-features/_folders.json
  packs/kingmaker-features/army-conditions/concealed.json
  packs/kingmaker-features/army-conditions/defeated.json
  packs/kingmaker-features/army-conditions/lost.json
  packs/kingmaker-features/army-conditions/mired.json
  packs/kingmaker-features/army-conditions/pinned.json
  packs/kingmaker-features/army-conditions/routed.json
  packs/kingmaker-features/army-conditions/shaken.json
  packs/kingmaker-features/army-tactics/ambush.json
  packs/kingmaker-features/army-tactics/cavalry-experts.json
  packs/kingmaker-features/army-tactics/defensive-tactics.json
  packs/kingmaker-features/army-tactics/explosive-shot.json
  packs/kingmaker-features/army-tactics/field-triage.json
  packs/kingmaker-features/army-tactics/flaming-shot.json
  packs/kingmaker-features/army-tactics/flexible-tactics.json
  packs/kingmaker-features/army-tactics/focused-devotion.json
  packs/kingmaker-features/army-tactics/hold-the-line.json
  packs/kingmaker-features/army-tactics/keen-eyed.json
  packs/kingmaker-features/army-tactics/merciless.json
  packs/kingmaker-features/army-tactics/opening-salvo.json
  packs/kingmaker-features/army-tactics/reckless-flankers.json
  packs/kingmaker-features/army-tactics/sharpshooter.json
  packs/kingmaker-features/army-war-actions-basic/advance.json
  packs/kingmaker-features/army-war-actions-basic/battle.json
  packs/kingmaker-features/army-war-actions-basic/disengage.json
  packs/kingmaker-features/army-war-actions-basic/guard.json
  packs/kingmaker-features/automation-effects/engines-of-war.json
  packs/kingmaker-features/automation-effects/guarded-critical-success.json
  packs/kingmaker-features/automation-effects/guarded-success.json
  packs/kingmaker-features/automation-effects/overrun.json
  packs/kingmaker-features/automation-effects/reduced-accuracy.json
Labels: pr: data update, kingmaker

#12001 Remove emphasis from "Frightened" in fearsome runes
  packs/equipment/fearsome-greater.json
  packs/equipment/fearsome.json
Labels: pr: data update

#11992 Fix beacon shot
  packs/equipment/beacon-shot.json
Labels: pr: data update

#11991 Fix arsenic
  packs/equipment/arsenic.json
Labels: pr: data update

#11958 Add light automation to Vine of Roses
  packs/equipment/vine-of-roses.json
Labels: pr: data update

#11977 Add automation for Sacred Armaments
  packs/feats/sacred-armaments.json
Labels: pr: data update

#11971 Align Heal Animal spell description with remaster changes
  packs/spells/heal-animal.json
Labels: pr: data update

#12009 Fix inline roll for Brutal Bully and Overpowering Charge and emit note on critical success
  packs/feats/brutal-bully.json
  packs/feats/overpowering-charge.json
Labels: pr: data update

#12011 Delete copies of retired javascript macros
  static/macros/takeabreather.js
  static/macros/travel-speed.js
Labels: pr: housekeeping

#12010 Declare containers over capacity only when over 100% full in Bulk units
  src/module/item/container/document.ts
  static/templates/actors/partials/item-line.hbs
Labels: pr: bugfix

#12007 Fix data preparation order of conditions
  src/module/actor/base.ts
  src/module/item/condition/document.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix

#11968 Clean up and consolidate item deletion handling from actor sheets
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  static/templates/actors/delete-condition-dialog.hbs
Labels: pr: refactor

#12021 Add effect for Undying Ferocity
  packs/feat-effects/effect-undying-ferocity.json
  packs/feats/undying-ferocity.json
Labels: pr: data update

#12016 Remove usage from ghost charge description
  packs/equipment/ghost-charge-greater.json
  packs/equipment/ghost-charge-lesser.json
  packs/equipment/ghost-charge-major.json
  packs/equipment/ghost-charge-moderate.json
Labels: pr: data update

#12015 Add ammunition type to ghost ammunition
  packs/equipment/ghost-ammunition.json
Labels: pr: data update

#12018 Add ammunition type to penetrating ammunition
  packs/equipment/penetrating-ammunition.json
Labels: pr: data update

#12019 Add spell link to Medusa's Scream and clean up description
  packs/equipment/medusas-scream-greater.json
  packs/equipment/medusas-scream.json
Labels: pr: data update

#12008 Track simplified roll terms that have been doubled
  src/module/system/damage/damage.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  types/foundry/client/roll.d.ts
Labels: pr: bugfix

#12023 Fix kingdom feat slot drag/drop
  src/module/actor/party/kingdom/sheet.ts
Labels: pr: bugfix, kingmaker

#12025 Convert tactics to feat slots and add section for free tactics
  src/module/actor/army/document.ts
  src/module/actor/army/sheet.ts
  src/module/item/campaign-feature/document.ts
  src/styles/actor/army/_index.scss
  static/lang/kingmaker-en.json
  static/templates/actors/army/sheet.hbs
Labels: pr: enhancement, kingmaker

#12027 Fix tooltip in heritage sidebar
  static/templates/items/heritage-sidebar.hbs
Labels: pr: bugfix

#11696 Add edicts and anathema formatted text fields to actor bio
  src/module/actor/character/data.ts
  static/lang/en.json
  static/template.json
  static/templates/actors/character/tabs/biography.hbs
Labels: pr: enhancement, remaster

#12028 Implement army potion consumption
  src/module/actor/army/document.ts
  src/module/actor/army/sheet.ts
  src/styles/actor/army/_index.scss
  static/lang/kingmaker-en.json
  static/templates/actors/army/sheet.hbs
Labels: pr: enhancement, kingmaker

#12031 Fix FA-icon styling, convert px to em/rem on NPC sidebar
  src/module/actor/character/crafting/helpers.ts
  src/styles/actor/npc/_index.scss
  src/styles/ui/sidebar/chat/_damage.scss
Labels: pr: bugfix, ui/ux

#12032 Fix regression in collecting dice from damage instances
  src/module/system/damage/roll.ts
Labels: pr: bugfix

#12033 Add suport for persistent-damage resistance/weakness
  src/module/actor/data/iwr.ts
Labels: pr: enhancement, iwr

#12035 Add `zeroIsNegative` option to `signedInteger`, use with IWR breakdown
  src/scripts/handlebars.ts
  src/util/misc.ts
  static/templates/chat/damage/iwr-breakdown.hbs
Labels: pr: enhancement

#12038 Use `tsx` directly instead of via `esno`
  package-lock.json
  package.json
Labels: pr: housekeeping

#12024 Update Lamashtu for Remaster
  packs/deities/lamashtu.json
Labels: pr: data update

#12029 Clean up some description formatting
  packs/ancestries/android.json
  packs/classfeatures/divine-ally.json
  packs/equipment/armor-potency-1.json
  packs/equipment/armor-potency-2.json
  packs/equipment/armor-potency-3.json
  packs/equipment/entertainers-cincture-greater.json
  packs/equipment/entertainers-cincture.json
  packs/equipment/gelid-shard.json
  packs/equipment/hunters-arrowhead.json
  packs/equipment/linguists-dictionary.json
  packs/equipment/pathfinders-coin.json
  packs/equipment/primeval-mistletoe-greater.json
  packs/equipment/primeval-mistletoe.json
  packs/equipment/ring-of-sigils-greater.json
  packs/equipment/ring-of-sigils.json
  packs/equipment/shadow-ash.json
  packs/feats/basic-red-mantis-magic.json
  packs/feats/frozen-breadth.json
  packs/feats/magical-edification.json
  packs/feats/master-snowcasting.json
  packs/feats/reclaimant-plea.json
  packs/gatewalkers-bestiary/shadowshift-field.json
  packs/gatewalkers-bestiary/shroud-of-silence.json
  packs/iconics/seelah-level-5.json
  packs/outlaws-of-alkenstar-bestiary/cranium-preserver.json
  packs/paizo-pregens/zeah.json
  packs/pathfinder-bestiary-3/ganzi-martial-artist.json
  packs/pathfinder-bestiary-3/green-man.json
  packs/pathfinder-bestiary-3/popobawa.json
  packs/pathfinder-bestiary-3/winter-hag.json
  packs/pfs-season-4-bestiary/coven-winter-hag.json
  packs/stolen-fate-bestiary/ndede.json
Labels: pr: data update

#12030 Update Monstrosity Form for remaster
  packs/spell-effects/spell-effect-monstrosity-form-cave-worm.json
  packs/spell-effects/spell-effect-monstrosity-form-phoenix.json
  packs/spell-effects/spell-effect-monstrosity-form-sea-serpent.json
  packs/spells/monstrosity-form.json
Labels: pr: data update

#12036 Add unified effect for Nature Incarnate and update
  packs/spell-effects/spell-effect-nature-incarnate.json
  packs/spells/nature-incarnate.json
  static/lang/re-en.json
Labels: pr: data update

#12040 Fill in type definition of `ControlIcon` class
  types/foundry/client/pixi/helpers/control-icon.d.ts
Labels: pr: types update

#12041 Fix auto classification of ray templates as being of `areaType` "line"
  src/module/canvas/helpers.ts
  src/module/canvas/measured-template.ts
  src/module/scene/measured-template-document.ts
Labels: pr: bugfix

#12042 Run extractPacks all
  packs/actions/disarm.json
  packs/actions/sneak.json
  packs/equipment/sovereign-steel-chunk.json
  packs/equipment/sovereign-steel-ingot.json
  packs/feat-effects/stance-assume-earths-mantle.json
  packs/feats/divine-health.json
Labels: pr: data update

#12043 Reduce number of auxiliary actions appearing on PC sheet
  src/module/actor/character/document.ts
Labels: ui/ux

#12046 Fix several issues with `ItemPF2e#toMessage` by using core API
  src/module/item/base/document.ts
  types/foundry/client/data/documents/chat-message.d.ts
Labels: pr: bugfix, pr: refactor

#12047 Fix regression in ancestry flaws tooltip
  src/module/actor/character/attribute-builder.ts
Labels: pr: bugfix

#12044 Add support for resistance to critical hits
  src/module/actor/data/iwr.ts
  src/module/system/damage/iwr.ts
Labels: pr: enhancement

#12048 Update `tsx` to latest
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#12049 Add automation for zombie abilities Unholy Speed and Unkillable
  packs/bestiary-family-ability-glossary/zombie-unholy-speed.json
  packs/bestiary-family-ability-glossary/zombie-unkillable.json
Labels: pr: data update

#12051 Lower intensity of Latern of Empty Light's token light RE
  packs/equipment/lantern-of-empty-light.json
Labels: pr: data update

#12052 Fix `for` attribute in weapon sheet range label
  static/templates/items/weapon-details.hbs
Labels: pr: bugfix

#12050 Add effect for precise debilitations
  packs/feat-effects/effect-precise-debilitations.json
  packs/feats/bloody-debilitation.json
  packs/feats/critical-debilitation.json
  packs/feats/eldritch-debilitations.json
  packs/feats/methodical-debilitations.json
  packs/feats/precise-debilitations.json
  packs/feats/tactical-debilitations.json
  packs/feats/vicious-debilitations.json
  static/lang/re-en.json
Labels: pr: data update

#12053 Use common color and height for item-sheet form fields
  src/styles/_colors.scss
  src/styles/_reset.scss
  src/styles/actor/character/_proficiency-ranks.scss
  src/styles/actor/npc/_index.scss
  src/styles/item/_header.scss
  src/styles/item/_index.scss
  src/styles/item/_rules.scss
  src/styles/item/_sidebar.scss
Labels: ui/ux

#12055 Touch up some item sheets after form-field-height normalization
  src/styles/_reset.scss
  src/styles/_tags.scss
  src/styles/item/_abc-sheet.scss
  src/styles/item/_deity-sheet.scss
  src/styles/item/_spell-sheet.scss
  static/templates/items/deity-details.hbs
Labels: ui/ux

#12058 Fix RE form not reverting to base form type when the type changes
  src/module/item/base/sheet/sheet.ts
Labels: pr: bugfix

#12061 Handle template preview wheel listeners warning
  src/module/canvas/layer/template.ts
Labels: pr: refactor

#12063 Restore `ownIfHigher` default to battle form strikes
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: bugfix

#12067 Integrate astral runes with IWR
  src/module/actor/data/iwr.ts
  src/module/item/physical/runes.ts
  src/module/system/damage/damage.ts
Labels: pr: enhancement, remaster

#12066 Add decaying and raiment to property rune options
  src/module/item/armor/values.ts
  src/module/item/physical/runes.ts
  src/module/item/weapon/values.ts
  static/lang/en.json
Labels: pr: data update

#12068 Relax prohibition of GrantItem REs from being on physical items
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix, pr: enhancement

#12070 Remove parameter defaults in method signature overloads
  build/lib/compendium-pack.ts
Labels: pr: types update

#12071 Update typescript and vite to latest
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pr: housekeeping

#12037 Replace remaining fas/far HTML classes with fa-solid/fa-regular
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/trick-magic-item-popup.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/apps/world-clock/app.ts
  src/module/chat-message/crit-fumble-cards.ts
  src/module/system/settings/index.ts
  src/scripts/hooks/get-scene-control-buttons.ts
  src/scripts/macros/treat-wounds.ts
  src/scripts/macros/xp/dialog.ts
  src/styles/actor/_nav.scss
  src/styles/actor/party/kingdom/_builder.scss
  src/styles/actor/sidebar/_health.scss
  src/styles/scene/_darkness-adjuster.scss
  src/styles/ui/_hover.scss
  static/templates/actors/crafting-entry-alchemical.hbs
  static/templates/actors/crafting-entry-list.hbs
  static/templates/actors/distribute-coins.hbs
  static/templates/actors/hazard/sheet.hbs
  static/templates/actors/identify-item.hbs
  static/templates/actors/loot/loot-npcs-popup.hbs
  static/templates/actors/npc/config.hbs
  static/templates/actors/npc/tabs/main.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/partials/carry-type.hbs
  static/templates/actors/partials/dying-pips.hbs
  static/templates/actors/partials/modifiers-tooltip.hbs
  static/templates/actors/party/kingdom/builder.hbs
  static/templates/actors/party/kingdom/tabs/activities.hbs
  static/templates/actors/party/regions/exploration.hbs
  static/templates/actors/party/sheet.hbs
  static/templates/actors/vehicle/tabs/details.hbs
  static/templates/chat/damage/damage-taken.hbs
  static/templates/chat/persistent-damage-recovery.hbs
  static/templates/items/activation-panel.hbs
  static/templates/items/affliction-sidebar.hbs
  static/templates/items/ancestry-details.hbs
  static/templates/items/background-details.hbs
  static/templates/items/melee-details.hbs
  static/templates/items/rules/token-light.hbs
  static/templates/popups/casting-item-create-dialog.hbs
  static/templates/popups/loot/move-loot-popup.hbs
  static/templates/scene/token/partials/lighting.hbs
  static/templates/scene/token/sheet.hbs
  static/templates/system/settings/menu.hbs
  static/templates/system/settings/world-clock/index.hbs
  static/templates/user/sheet.hbs
Labels: pr: refactor

#12072 Fix tag creation for ghost touch
  src/module/system/damage/damage.ts
Labels: pr: bugfix

#12077 Fix traits and action cost of In Tune
  packs/feats/in-tune.json
Labels: pr: data update

#12078 Remove extra link to Treat Wounds in Natural Medicine
  packs/feats/natural-medicine.json
  packs/iconics/lini-level-1.json
Labels: pr: data update

#12080 Fix rule elements on Sapling Shields
  packs/equipment/sapling-shield-greater.json
  packs/equipment/sapling-shield-lesser.json
  packs/equipment/sapling-shield-major.json
  packs/equipment/sapling-shield-minor.json
  packs/equipment/sapling-shield-moderate.json
  packs/equipment/sapling-shield-true.json
Labels: pr: data update

#12020 Add ammunition type to spellstrike ammunition
  packs/equipment/spellstrike-ammunition-type-i.json
  packs/equipment/spellstrike-ammunition-type-ii.json
  packs/equipment/spellstrike-ammunition-type-iii.json
  packs/equipment/spellstrike-ammunition-type-iv.json
  packs/equipment/spellstrike-ammunition-type-ix.json
  packs/equipment/spellstrike-ammunition-type-v.json
  packs/equipment/spellstrike-ammunition-type-vi.json
  packs/equipment/spellstrike-ammunition-type-vii.json
  packs/equipment/spellstrike-ammunition-type-viii.json
Labels: pr: data update

#12081 Fix quirks with inventory sorting
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/base/sheet/sheet.ts
  src/styles/actor/_inventory.scss
  src/util/misc.ts
  static/templates/actors/partials/inventory.hbs
  static/templates/actors/partials/item-line.hbs
Labels: pr: bugfix, pr: refactor, ui/ux

#12088 Change h3.header into section.major > header in character and kingdom sheets
  src/styles/actor/_index.scss
  src/styles/actor/character/_biography.scss
  src/styles/actor/character/_index.scss
  src/styles/actor/character/_proficiencies.scss
  src/styles/actor/party/kingdom/_activities.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/actor/party/kingdom/_ongoing.scss
  src/styles/actor/vehicle/_header.scss
  src/styles/actor/vehicle/_index.scss
  static/templates/actors/character/tabs/actions.hbs
  static/templates/actors/character/tabs/biography.hbs
  static/templates/actors/character/tabs/effects.hbs
  static/templates/actors/character/tabs/feats.hbs
  static/templates/actors/character/tabs/general.hbs
  static/templates/actors/character/tabs/pfs.hbs
  static/templates/actors/character/tabs/proficiencies.hbs
  static/templates/actors/party/kingdom/tabs/activities.hbs
  static/templates/actors/party/kingdom/tabs/features.hbs
  static/templates/actors/party/kingdom/tabs/main.hbs
  static/templates/actors/party/kingdom/tabs/ongoing.hbs
  static/templates/actors/party/kingdom/tabs/world.hbs
  static/templates/actors/vehicle/tabs/effects.hbs
Labels: pr: refactor

#12091 Import item-type-specific scss files after main item-sheet styling
  src/styles/_globals.scss
  src/styles/actor/_index.scss
  src/styles/item/_header.scss
  src/styles/item/_index.scss
  src/styles/item/_nav.scss
Labels: pr: refactor

#12093 Add select menu to edit spell damage kinds
  src/module/item/spell/sheet.ts
  src/styles/item/_spell-sheet.scss
  static/lang/en.json
  static/templates/items/spell-details.hbs
  static/templates/items/spell-overlay.hbs
Labels: pr: enhancement, ui/ux

#12094 Remove old `property[1-3]` cruft from some embedded weapons
  packs/agents-of-edgewatch-bestiary/alchemist-aspirant.json
  packs/agents-of-edgewatch-bestiary/amateur-chemist.json
  packs/agents-of-edgewatch-bestiary/black-whale-guard-f3.json
  packs/agents-of-edgewatch-bestiary/black-whale-guard.json
  packs/agents-of-edgewatch-bestiary/bloody-barber-goon.json
  packs/agents-of-edgewatch-bestiary/calennia.json
  packs/agents-of-edgewatch-bestiary/garrote-master-assassin.json
  packs/agents-of-edgewatch-bestiary/grimwold.json
  packs/agents-of-edgewatch-bestiary/norgorberite-poisoner.json
  packs/agents-of-edgewatch-bestiary/priest-of-blackfingers.json
  packs/agents-of-edgewatch-bestiary/sad-liza.json
  packs/agents-of-edgewatch-bestiary/secret-keeper.json
  packs/agents-of-edgewatch-bestiary/sleepless-sun-veteran.json
  packs/agents-of-edgewatch-bestiary/starwatch-commando.json
  packs/agents-of-edgewatch-bestiary/twisted-jack.json
  packs/agents-of-edgewatch-bestiary/venom-mage.json
  packs/agents-of-edgewatch-bestiary/wynsal-starborn.json
  packs/agents-of-edgewatch-bestiary/zealborn.json
  packs/menace-under-otari-bestiary/kobold-trapmaster-bb.json
Labels: pr: data update

#12097 Fix transposed Dimension spells in remaster journal
  packs/journals/remaster-changes.json
Labels: pr: data update

#12103 Reduce vertical separation in item sheets with action glyph
  src/styles/item/_header.scss
Labels: ui/ux

#12105 Fix some Sky Kings Tomb 1 actors
  packs/sky-kings-tomb-bestiary/algerschmick.json
  packs/sky-kings-tomb-bestiary/krohan-possessed.json
  packs/sky-kings-tomb-bestiary/krohan-veldollow.json
  packs/sky-kings-tomb-bestiary/lady-shimmersnip.json
  packs/sky-kings-tomb-bestiary/skibrellon.json
Labels: pr: data update

#12098 Upgrade favored weapon proficiency to master in Warpriest's Final Doctrine
  packs/classfeatures/final-doctrine-warpriest.json
Labels: pr: data update

#12108 Bring item mystification panel in line with styling changes
  src/styles/_reset.scss
  src/styles/item/_index.scss
  src/styles/item/_mystification.scss
  src/styles/item/_nav.scss
  static/lang/en.json
  static/templates/items/mystify-panel.hbs
Labels: ui/ux

#12107 Adjust migration 828 to skip "hb_" traits
  src/module/migration/migrations/828-prune-invalid-traits.ts
Labels: pr: bugfix

#12090 Run spell overlay changes through `_preUpdate` normalizations
  src/module/item/spell/document.ts
  src/module/item/spell/sheet.ts
Labels: pr: bugfix

#12099 Remove unneeded labels for some RollOptions
  packs/sky-kings-tomb-bestiary/ether-sprite-swarm.json
  packs/sky-kings-tomb-bestiary/ether-sprite.json
  packs/sky-kings-tomb-bestiary/glacial-worm.json
Labels: pr: data update

#12111 Allow bulk alterations to apply to any physical item type
  src/module/rules/rule-element/item-alteration/schemas.ts
Labels: pr: enhancement

#12112 Use `fieldIdPrefix` in more physical item sheets
  static/templates/items/armor-details.hbs
  static/templates/items/shield-details.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: refactor

#12113 Modify Sapling Shield bulk when activated
  packs/equipment/sapling-shield-greater.json
  packs/equipment/sapling-shield-lesser.json
  packs/equipment/sapling-shield-major.json
  packs/equipment/sapling-shield-minor.json
  packs/equipment/sapling-shield-moderate.json
  packs/equipment/sapling-shield-true.json
Labels: pr: data update

#12110 Somewhat unify handling of item summaries on actor sheets
  src/module/actor/creature/spell-preparation-sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/apps/compendium-browser/tabs/campaign-feature.ts
  src/module/item/ability/document.ts
  src/styles/_globals.scss
  src/styles/actor/_item-summary.scss
  src/styles/actor/_spell-collection.scss
  src/styles/actor/_spell-preparation.scss
  src/styles/actor/character/_index.scss
  src/styles/actor/party/_overview.scss
  src/styles/actor/party/kingdom/_features.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/actor/tabs/_actions.scss
  src/util/dom.ts
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/actors/character/partials/feat-slot.hbs
  static/templates/actors/character/partials/strike.hbs
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/actors/character/tabs/effects.hbs
  static/templates/actors/hazard/sheet.hbs
  static/templates/actors/limited/npc-sheet.hbs
  static/templates/actors/npc/partials/action.hbs
  static/templates/actors/partials/action.hbs
  static/templates/actors/partials/effects.hbs
  static/templates/actors/partials/item-line.hbs
  static/templates/actors/partials/item-summary.hbs
  static/templates/actors/partials/spell-collection.hbs
  static/templates/actors/party/kingdom/partials/settlement.hbs
  static/templates/actors/party/kingdom/tabs/activities.hbs
  static/templates/actors/party/kingdom/tabs/features.hbs
  static/templates/actors/spell-preparation-sheet.hbs
Labels: pr: bugfix, pr: refactor

#12118 Update Puff of Poison with Remaster errata
  packs/spells/puff-of-poison.json
Labels: pr: data update

#12121 Restore "Use" button in item summaries for consumables lacking formulas
  static/templates/actors/partials/item-summary.hbs
Labels: pr: bugfix

#12124 Update `EmbeddedCollection` type
  types/foundry/common/abstract/embedded-collection.d.ts
  types/foundry/common/abstract/module.d.ts
Labels: pr: types update

#12129 Update Sunburst description to remaster and add auto-heightening vitality damage link
  packs/spells/sunburst.json
Labels: pr: data update

#12127 Fix source of Rewrite Memory
  packs/season-of-ghosts-bestiary/kagekuma.json
  packs/spells/rewrite-memory.json
Labels: pr: data update

#12123 Add defense to some inline checks
  packs/book-of-the-dead-bestiary/raw-nerve.json
  packs/pathfinder-bestiary-3/monkey-swarm.json
  packs/strength-of-thousands-bestiary/damibwa.json
  packs/strength-of-thousands-bestiary/halbrux-far-sight.json
  packs/strength-of-thousands-bestiary/nkiruka.json
Labels: pr: data update

#12120 Use better icon for Cornucopia spell, set healing type to vitality
  packs/spells/cornucopia.json
Labels: pr: data update

#12117 Add light automation for Wand of Dazzling Rays
  packs/equipment/wand-of-dazzling-rays-3rd-level.json
  packs/equipment/wand-of-dazzling-rays-4th-level.json
  packs/equipment/wand-of-dazzling-rays-5th-level.json
  packs/equipment/wand-of-dazzling-rays-6th-level.json
  packs/equipment/wand-of-dazzling-rays-7th-level.json
  packs/equipment/wand-of-dazzling-rays-8th-level.json
  packs/equipment/wand-of-dazzling-rays-9th-level.json
  static/lang/re-en.json
Labels: pr: data update

#12114 Add effect for Shimmering Dust
  packs/equipment-effects/effect-shimmering-dust.json
  packs/equipment/shimmering-dust.json
Labels: pr: data update

#12130 Avoid declaring massive damage against actors with no HP
  src/module/actor/base.ts
Labels: pr: bugfix

#12140 Add senses to army
  src/module/actor/army/data.ts
  src/module/actor/army/document.ts
  src/styles/actor/army/_index.scss
  static/templates/actors/army/sheet.hbs
Labels: pr: enhancement, kingmaker

#12141 Implement Army MAP and Keep Up the Pressure
  packs/kingmaker-features/army-tactics/keep-up-the-pressure.json
  src/module/actor/army/document.ts
  static/lang/kingmaker-en.json
Labels: pr: enhancement, kingmaker

#12142 Update `PlaceableObject` types
  types/foundry/client/pixi/placeable.d.ts
  types/foundry/client/pixi/placeables/ambient-light.d.ts
  types/foundry/client/pixi/placeables/ambient-sound.d.ts
  types/foundry/client/pixi/placeables/drawing.d.ts
  types/foundry/client/pixi/placeables/measured-template.d.ts
  types/foundry/client/pixi/placeables/note.d.ts
  types/foundry/client/pixi/placeables/tile.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/client/pixi/placeables/wall.d.ts
Labels: pr: types update

#12144 Fix issue when rerunning migration 907
  src/module/migration/migrations/907-restructure-armor-weapon-runes.ts
Labels: pr: bugfix

#12137 Fix incorrect bold tags in action-en
  static/lang/action-en.json
Labels: pr: data update

#12133 Add effect for Elemental Betrayal
  packs/spell-effects/spell-effect-elemental-betrayal.json
  packs/spells/elemental-betrayal.json
Labels: pr: data update

#12136 Add glyph to stealth check in conceal an object
  packs/actions/conceal-an-object.json
Labels: pr: data update

#12138 Add glyph to intimidation check in demoralize
  packs/actions/demoralize.json
Labels: pr: data update

#12139 Add glyph to diplomacy check in request
  packs/actions/request.json
Labels: pr: data update

#12126 Add automation for Fey Influence and Fey Ascension
  packs/feat-effects/effect-monarch-wings.json
  packs/feats/fey-ascension.json
  packs/feats/fey-influence.json
  static/lang/re-en.json
Labels: pr: data update

#12134 Add unified effect for Shifting Form
  packs/spell-effects/spell-effect-shifting-form.json
  packs/spells/shifting-form.json
Labels: pr: data update
