Repository foundryvtt/pf2e, pull requests merged in 2023-11, with the labels that each got.

#11030 Fix hardness alteration of shield in sparkling target class feature
  packs/classfeatures/sparkling-targe.json
Labels: pr: data update

#10971 Conditionally roll vitality damage from property runes
  src/module/item/physical/runes.ts
  src/module/system/damage/damage.ts
  src/styles/_tags.scss
Labels: pr: enhancement

#11031 Fix some spell sheet errors and update to fieldset
  src/module/item/spell/sheet.ts
  src/styles/item/_index.scss
  src/styles/item/_spell-sheet.scss
  static/templates/items/spell-details.hbs
  static/templates/items/spell-overlay.hbs
Labels: pr: bugfix, ui/ux

#11032 Fix description of Fence's Sneak Attack
  packs/npc-gallery/fence.json
  packs/pfs-season-2-bestiary/fence-pfs-2-00.json
  packs/pfs-season-3-bestiary/ninth-army-fence.json
  packs/pfs-season-4-bestiary/elven-fence.json
  packs/stolen-fate-bestiary/dieral-myrnese.json
Labels: pr: data update

#11034 Clean up damage modifiers dialog
  src/module/system/damage/dialog.ts
  src/module/system/damage/roll.ts
  src/styles/_colors.scss
  src/styles/actor/character/_actions.scss
  src/styles/ui/_roll-modifiers-dialog.scss
  static/lang/en.json
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/chat/check-modifiers-dialog.hbs
  static/templates/chat/damage/damage-modifier-dialog.hbs
  static/templates/dice/damage-roll.hbs
  static/templates/dice/damage-tooltip.hbs
Labels: ui/ux

#11037 Fix the bonus on attack rolls in the sulfur bomb (greater) description
  packs/equipment/sulfur-bomb-greater.json
Labels: pr: data update

#11033 Fix War Formation to remove explicit damage type
  packs/stolen-fate-bestiary/harpy-warbird.json
  packs/stolen-fate-bestiary/queen-kawlinawk.json
Labels: pr: data update

#11038 Add automation for Brimorak's Flaming Weapon
  packs/npc-gallery/demonologist.json
  packs/pathfinder-bestiary-3/brimorak.json
  packs/pfs-season-2-bestiary/firestorm-brimorak.json
Labels: pr: data update

#11039 Set Weapon Surge effect duration to 1 round
  packs/spell-effects/spell-effect-weapon-surge-major-striking.json
  packs/spell-effects/spell-effect-weapon-surge.json
Labels: pr: data update

#11042 Remove spell sheet overlay collection path property and fix regressions
  src/module/item/spell/sheet.ts
  static/templates/items/spell-overlay.hbs
Labels: pr: bugfix, pr: refactor

#11043 Fix creating and editing spell area for fixed heightening
  src/module/item/spell/sheet.ts
  src/scripts/handlebars.ts
  static/templates/items/spell-overlay.hbs
Labels: pr: bugfix

#11044 Pass data to datafield `initial` functions in RE form
  src/module/item/base/sheet/rule-element-form/base.ts
Labels: pr: bugfix

#11045 Fix abberant results when drag dropping identical rule elements
  src/module/item/base/sheet/base.ts
Labels: pr: bugfix

#11046 Update `DataField` type to guarantee that source data is JSON-compatible
  src/module/actor/party/data.ts
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  src/module/rules/rule-element/token-mark/rule-element.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/data/data.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/util.d.ts
Labels: pr: types update

#11047 Shore up reliability of not applying effects from hidden tokens
  src/module/actor/base.ts
  src/module/scene/token-document/aura/index.ts
Labels: pr: bugfix

#11049 Make some NPC rolls blind
  packs/age-of-ashes-bestiary/aluum-enforcer.json
  packs/age-of-ashes-bestiary/spiritbound-aluum.json
  packs/age-of-ashes-bestiary/weathered-wail.json
  packs/one-shot-bestiary/pairaka-one-shot-4.json
  packs/pathfinder-bestiary-2/akata.json
  packs/pathfinder-bestiary-2/vrykolakas-ancient.json
  packs/pathfinder-bestiary-2/vrykolakas-master.json
Labels: pr: data update

#11050 Fix Brochmaw's Hot Oil damage
  packs/rage-of-elements-bestiary/brochmaw.json
Labels: pr: data update

#11048 Release Notes 5.8.0
  CHANGELOG.md
  package.json
  static/system.json
Labels: pr: housekeeping

#11035 Add "not" button to Compendium Browser filter tags
  src/module/apps/compendium-browser/index.ts
  src/styles/_tags.scss
Labels: ui/ux

#11051 Fix regression in hazard initiative rolling
  CHANGELOG.md
  static/templates/actors/hazard/partials/sidebar.hbs
Labels: pr: bugfix, pr: housekeeping

#11052 Add typed damage links to Manifestation Of Dahak's Focused Breath Weapon
  packs/age-of-ashes-bestiary/manifestation-of-dahak.json
Labels: pr: data update

#11061 Remove checking of hands available for free-hand weapons
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  static/templates/actors/character/partials/strike.hbs
Labels: pr: bugfix

#11062 Resolve injected properties in custom IWR definitions
  src/module/rules/rule-element/iwr/base.ts
Labels: pr: bugfix

#11063 Update The Eclipse damage to `@Damage` format
  packs/agents-of-edgewatch-bestiary/hundun-chaos-mage.json
  packs/stolen-fate-bestiary/the-eclipse.json
Labels: pr: data update

#11064 Use a V5 UUID hash digest of Foundry UUIDs for roll options
  package-lock.json
  package.json
  packs/feat-effects/effect-aura-junction-fire.json
  src/module/actor/base.ts
Labels: pr: bugfix, pr: data update

#11065 Release Notes 5.8.1
  CHANGELOG.md
  package-lock.json
  static/system.json
Labels: pr: housekeeping

#11053 Automate damage-based instant death
  src/module/actor/base.ts
  src/module/system/settings/index.ts
  src/scripts/config/index.ts
  static/lang/en.json
  static/templates/sidebar/encounter-tracker/config.hbs
Labels: pr: enhancement

#11068 Fix deleting spell fixed heightening entries
  src/module/item/spell/sheet.ts
Labels: pr: bugfix

#11059 Brush up Reginald Vancaskerkin and add effect for Overdrive Engine
  packs/agents-of-edgewatch-bestiary/reginald-vancaskerkin.json
  packs/bestiary-effects/effect-overdrive-engine.json
Labels: pr: data update

#11069 Fix application of Blade Ally property rune effects on handwraps
  packs/feat-effects/effect-blade-ally.json
Labels: pr: data update

#11071 Fix issue preventing NPC loot sheet inventory from appearing to players
  src/module/actor/npc/sheet.ts
  src/styles/actor/npc/_inventory.scss
  static/templates/actors/npc/loot-sheet.hbs
Labels: pr: bugfix

#11072 Add instant death message for undead creatures
  src/module/actor/base.ts
  static/lang/en.json
Labels: ui/ux

#11076 Fix shield hardness label in armor sheet
  static/templates/items/armor-details.hbs
Labels: pr: bugfix, ui/ux

#11074 Move always show dialog toggle from the header to the dialog body
  src/module/system/check/dialog.ts
  src/module/system/damage/dialog.ts
  src/styles/ui/_roll-modifiers-dialog.scss
  static/lang/en.json
  static/templates/chat/check-modifiers-dialog.hbs
  static/templates/chat/damage/damage-modifier-dialog.hbs
Labels: ui/ux

#11073 Fix healing links in Life Shot
  packs/equipment/life-shot-greater.json
  packs/equipment/life-shot-lesser.json
  packs/equipment/life-shot-major.json
  packs/equipment/life-shot-minor.json
  packs/equipment/life-shot-moderate.json
  packs/equipment/life-shot-true.json
Labels: pr: data update

#11080 Fix regression in creation of shield-block listener on damage messages
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/helpers.ts
Labels: pr: bugfix

#11083 Update type signature of `FormApplication#_onSubmit`
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/popups/distribute-coins-popup.ts
  src/module/item/base/sheet/base.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/variant-rules.ts
  src/module/system/tag-selector/senses.ts
  types/foundry/client/apps/form.d.ts
  types/foundry/client/ui/filepicker.d.ts
Labels: pr: types update

#11082 Display total bulk in vehicle sheet inventory
  src/styles/actor/_coinage.scss
  src/styles/actor/_index.scss
  src/styles/actor/_nav.scss
  src/styles/actor/vehicle/_index.scss
  static/templates/actors/character/sheet.hbs
  static/templates/actors/vehicle/sheet.hbs
  static/templates/actors/vehicle/tabs/inventory.hbs
Labels: pr: enhancement, ui/ux

#11067 Support spell heighten trait overrides
  src/module/item/spell/sheet.ts
  src/module/sheet/helpers.ts
  src/styles/item/_spell-sheet.scss
  static/templates/items/spell-overlay.hbs
Labels: pr: enhancement

#11085 Release Notes 5.8.2
  CHANGELOG.md
  package.json
  static/system.json
Labels: pr: housekeeping

#11086 Restore removability of custom attack proficiencies
  src/module/actor/sheet/popups/manage-attack-proficiencies.ts
Labels: pr: bugfix

#11075 Add effect for Sparkler
  packs/equipment-effects/effect-sparkler.json
  packs/equipment/sparkler.json
  static/lang/re-en.json
Labels: pr: data update

#11070 Fix some inline check traits
  packs/age-of-ashes-bestiary/lazurite-infused-stone-golem.json
  packs/agents-of-edgewatch-bestiary/baatamidar.json
  packs/agents-of-edgewatch-bestiary/chaos-gulgamodh.json
  packs/agents-of-edgewatch-bestiary/hestriviniaas.json
  packs/agents-of-edgewatch-bestiary/kharnass-lesser-glyph.json
  packs/agents-of-edgewatch-bestiary/overdrive-imentesh.json
  packs/blood-lords-bestiary/urbulinex.json
  packs/book-of-the-dead-bestiary/siphoning-spirit.json
  packs/crown-of-the-kobold-king-bestiary/id-ooze.json
  packs/equipment/hail-of-arrows-snare.json
  packs/equipment/sky-piercing-bow.json
  packs/equipment/the-beating.json
  packs/extinction-curse-bestiary/dyzallin-shraen.json
  packs/hazards/grasp-of-the-damned.json
  packs/menace-under-otari-bestiary/sewer-ooze-bb.json
  packs/monsters-of-myth-bestiary/krampus-celebrant.json
  packs/night-of-the-gray-death-bestiary/gray-gardener-enforcer.json
  packs/pathfinder-bestiary-3/adult-sky-dragon-spellcaster.json
  packs/pathfinder-bestiary-3/adult-sky-dragon.json
  packs/pathfinder-bestiary-3/ancient-sky-dragon-spellcaster.json
  packs/pathfinder-bestiary-3/ancient-sky-dragon.json
  packs/pfs-season-1-bestiary/injured-weak-otyugh.json
  packs/pfs-season-2-bestiary/charmed-crab.json
  packs/pfs-season-2-bestiary/churning-lava-1-2.json
  packs/pfs-season-2-bestiary/churning-lava-3-4.json
  packs/pfs-season-2-bestiary/collapsing-ice.json
  packs/pfs-season-2-bestiary/storastas-last-stand-3-4.json
  packs/pfs-season-2-bestiary/storastas-last-stand-5-6.json
  packs/quest-for-the-frozen-flame-bestiary/cave-in.json
  packs/quest-for-the-frozen-flame-bestiary/punishing-altar.json
  packs/quest-for-the-frozen-flame-bestiary/soul-draining-cage.json
  packs/spells/pernicious-poltergeist.json
  packs/strength-of-thousands-bestiary/agitated-carnivorous-plants.json
  packs/strength-of-thousands-bestiary/flensing-chute.json
  packs/strength-of-thousands-bestiary/grave-karina.json
  packs/strength-of-thousands-bestiary/living-sun-spire.json
  packs/strength-of-thousands-bestiary/mutated-sewer-ooze.json
  packs/strength-of-thousands-bestiary/old-thrasher.json
  packs/strength-of-thousands-bestiary/umbo.json
Labels: pr: data update

#11089 Add setting to skip damage modifiers dialog
  src/module/actor/character/document.ts
  src/module/actor/character/elemental-blast.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/helpers.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/spell/document.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/check/check.ts
  src/module/system/check/dialog.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/dialog.ts
  src/module/system/statistic/statistic.ts
  src/module/system/text-editor.ts
  src/module/user/document.ts
  src/scripts/dice.ts
  src/scripts/macros/perception-for-selected-tokens.ts
  src/scripts/macros/stealth-for-selected-tokens.ts
  src/scripts/macros/treat-wounds.ts
  src/scripts/sheet-util.ts
  src/scripts/ui/inline-roll-links.ts
  static/lang/en.json
  static/templates/chat/check-modifiers-dialog.hbs
  static/templates/chat/damage/damage-modifier-dialog.hbs
  static/templates/user/sheet.hbs
Labels: pr: enhancement

#11093 Fix typo in description of retch rust feat
  packs/feats/retch-rust.json
Labels: pr: data update

#11101 Fix icon color of precision/splash damage
  src/styles/_colors.scss
Labels: pr: bugfix

#11099 Add icon to Candlecap
  packs/equipment/candlecap.json
Labels: pr: data update

#11102 Fix NPC damage formula creation when precision/splash occurs first
  src/module/item/melee/document.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#11097 Fix condition increasing when no value is passed
  src/module/actor/base.ts
Labels: pr: bugfix

#11094 Use "empty" CSS class for empty NPC sheet sections instead of "disabled"
  src/styles/actor/npc/_index.scss
  static/templates/actors/npc/partials/sidebar.hbs
  static/templates/actors/npc/sheet.hbs
Labels: pr: bugfix, pr: refactor

#11091 Add custom resistance for Perfect Droplet
  packs/equipment-effects/effect-perfect-droplet-armor-greater.json
  packs/equipment-effects/effect-perfect-droplet-armor-major.json
  packs/equipment-effects/effect-perfect-droplet-armor.json
  static/lang/re-en.json
Labels: pr: data update

#11107 Migrate "showRollDialogs" user setting
  src/module/migration/migrations/880-split-show-dialogs-setting.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/user/data.ts
Labels: pr: data migration

#11105 Include max stamina when determining whether massive damage is taken
  src/module/actor/base.ts
Labels: pr: enhancement

#11106 Return false early in `ActorPF2e#isImmuneTo` if IWR is disabled
  src/module/actor/base.ts
Labels: pr: bugfix

#11104 Show secret text in item descriptions to GMs
  src/module/item/base/sheet/base.ts
Labels: pr: bugfix

#11108 Fix fatal override when base damage type is overwritten
  src/module/system/damage/helpers.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#11088 Add icon for Shobhad Longrifle
  packs/equipment/shobhad-longrifle.json
  static/icons/equipment/weapons/shobhad-longrifle.webp
Labels: pr: data update, pr: static assets

#11100 Add TokenLight to Songbird's Brush
  packs/equipment/scarlet-queen.json
  packs/equipment/songbirds-brush.json
Labels: pr: data update

#11103 Add effects for Thorn Triad
  packs/equipment-effects/effect-thorn-triad-armor-greater.json
  packs/equipment-effects/effect-thorn-triad-armor-major.json
  packs/equipment-effects/effect-thorn-triad-armor.json
  packs/equipment-effects/effect-thorn-triad-weapon-greater.json
  packs/equipment-effects/effect-thorn-triad-weapon-major.json
  packs/equipment-effects/effect-thorn-triad-weapon.json
  packs/equipment/thorn-triad-greater.json
  packs/equipment/thorn-triad-major.json
  packs/equipment/thorn-triad.json
Labels: pr: data update

#11087 Add spells to Spirit Turtle
  packs/fists-of-the-ruby-phoenix-bestiary/spirit-turtle.json
Labels: pr: data update

#11109 Fix description of Jax
  packs/equipment/jax.json
  packs/outlaws-of-alkenstar-bestiary/palzu.json
Labels: pr: data update

#11111 Fix Purple Worm Sting damage
  packs/spells/purple-worm-sting.json
Labels: pr: data update

#11114 Level 0 and back Witch and Wizard pregens
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/iconics/feiya-level-1.json
  packs/iconics/feiya-level-5.json
  packs/paizo-pregens/ezren-beginner-box.json
  packs/paizo-pregens/melvok.json
Labels: pr: data update

#11113 Fix predicate in Ongoing Strategy feat
  packs/feats/ongoing-strategy.json
  src/module/migration/migrations/879-devise-a-stratagem-and-friends.ts
Labels: pr: data update

#11115 Run extractPacks all
  packs/feat-effects/effect-kinetic-aura.json
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/iconics/feiya-level-1.json
  packs/iconics/feiya-level-5.json
  packs/iconics/kyra-level-1.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/iconics/sajan-level-1.json
  packs/iconics/sajan-level-5.json
  packs/iconics/seelah-level-1.json
  packs/iconics/seelah-level-5.json
  packs/iconics/valeros-level-1.json
  packs/iconics/valeros-level-3.json
  packs/iconics/valeros-level-5.json
  packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
  packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
  packs/kingmaker-bestiary/ekundayo-level-1.json
  packs/kingmaker-bestiary/ekundayo-level-6.json
  packs/kingmaker-bestiary/tristian-level-1.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/kingmaker-bestiary/valerie-level-1.json
  packs/kingmaker-bestiary/valerie-level-9.json
  packs/paizo-pregens/booker-kaar.json
  packs/paizo-pregens/doc-featherton.json
  packs/paizo-pregens/eteleon.json
  packs/paizo-pregens/ezren-beginner-box.json
  packs/paizo-pregens/fluff-fang-level-4.json
  packs/paizo-pregens/jadren-tagar.json
  packs/paizo-pregens/kaako-ashfeather.json
  packs/paizo-pregens/kalaggi-nakutu.json
  packs/paizo-pregens/kellsti.json
  packs/paizo-pregens/kyra-beginner-box.json
  packs/paizo-pregens/lavanna-saltspray.json
  packs/paizo-pregens/melvok.json
  packs/paizo-pregens/ufi.json
  packs/paizo-pregens/yacob.json
  packs/paizo-pregens/zane-ikundi.json
  packs/paizo-pregens/zeah.json
Labels: pr: data update

#11116 Convert UUID ChoiceSet selections to names in pack queries
  build/lib/compendium-pack.ts
Labels: pr: bugfix, pr: housekeeping

#11118 Prevent side-effects for damage modifiers and dice
  src/module/system/damage/formula.ts
Labels: pr: bugfix

#11121 Fix styling for spellcasting drag handle
  src/scripts/register-templates.ts
  src/styles/actor/_index.scss
  src/styles/actor/_spell-collection.scss
  src/styles/actor/_spell-preparation.scss
  src/styles/actor/npc/_index.scss
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/spell-collection.hbs
Labels: pr: bugfix, pr: refactor, ui/ux

#11122 Acquire roll notes, substitutions, and rollTwices from context clones
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
Labels: pr: bugfix

#11124 Use `Application` search filter API in roll inspector
  src/module/chat-message/chat-inspect-roll.ts
  src/module/chat-message/document.ts
  src/module/chat-message/roll-inspector.ts
  src/styles/ui/sidebar/chat/_index.scss
  src/styles/ui/sidebar/chat/_roll-inspector.scss
  static/templates/chat/chat-inspect-roll.hbs
  static/templates/chat/roll-inspector.hbs
Labels: pr: refactor

#11123 Fix NPC shield labels
  static/lang/en.json
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/npc/partials/sidebar.hbs
Labels: pr: bugfix

#11127 Update type definitions of Foundry's prototype extensions
  types/foundry/common/module.d.ts
  types/foundry/common/primitives/array.d.ts
  types/foundry/common/primitives/date.d.ts
  types/foundry/common/primitives/math.d.ts
  types/foundry/common/primitives/module.d.ts
  types/foundry/common/primitives/number.d.ts
  types/foundry/common/primitives/regexp.d.ts
  types/foundry/common/primitives/set.d.ts
  types/foundry/common/primitives/string.d.ts
  types/foundry/common/primitives/url.d.ts
  types/foundry/common/utils/primitives.d.ts
Labels: pr: types update

#11126 Add damage automation to Garrote Bolt and Garrote Shot
  packs/equipment/garrote-bolt.json
  packs/equipment/garrote-shot.json
Labels: pr: data update

#11129 Add effects for Silver Crescent
  packs/equipment-effects/effect-silver-crescent-greater.json
  packs/equipment-effects/effect-silver-crescent-lesser.json
  packs/equipment-effects/effect-silver-crescent-moderate.json
  packs/equipment/silver-crescent-greater.json
  packs/equipment/silver-crescent-lesser.json
  packs/equipment/silver-crescent-moderate.json
Labels: pr: data update

#11131 Fix height of vertical rule dividing chat message tags
  src/styles/_globals.scss
  src/styles/ui/sidebar/chat/_roll-inspector.scss
Labels: pr: bugfix, ui/ux

#11120 Add TokenLight to Radiant Lance and Glorious Plate
  packs/equipment/glorious-plate.json
  packs/equipment/radiant-lance.json
  static/lang/re-en.json
Labels: pr: data update

#11135 Fix physical resistance exception for The First Faithful
  packs/kingmaker-bestiary/the-first-faithful.json
Labels: pr: data update

#11132 Use pf2e tooltip style in participant-conditions chat messages
  static/templates/chat/participant-conditions.hbs
Labels: ui/ux

#11128 Never delete consumed ammunition carrying rule elements
  src/module/item/consumable/document.ts
Labels: pr: bugfix

#11130 Pass spell damage rolls through `ActorPF2e#getDamageRollContext`
  src/module/actor/base.ts
  src/module/item/spell/document.ts
  src/module/system/check/check.ts
Labels: pr: enhancement

#11136 Refactor spell area labels
  src/module/item/spell/data.ts
  src/module/item/spell/document.ts
  static/lang/en.json
  static/templates/chat/spell-card.hbs
Labels: pr: refactor

#11138 Add automation for House Drake's Silver Strike
  packs/pathfinder-bestiary-3/house-drake.json
Labels: pr: data update

#11139 Add silver to Sterling Dynamo Strikes and magical with Golem Dynamo
  packs/feats/golem-dynamo.json
  packs/feats/sterling-dynamo-dedication.json
Labels: pr: data update

#11125 Add effect for Glowing Lantern Fruit
  packs/equipment-effects/effect-glowing-lantern-fruit-lantern-light.json
  packs/equipment/glowing-lantern-fruit.json
  packs/equipment/mechanical-torch.json
Labels: pr: data update

#11141 Add automation for Stasian Smash
  packs/feats/stasian-smash.json
  static/lang/re-en.json
Labels: pr: data update

#11143 Restore roll options of the form "proficiency:rank:${rankString}"
  src/module/actor/character/document.ts
Labels: pr: bugfix

#11140 Add button to place template in spell item summary
  src/module/actor/sheet/item-summary-renderer.ts
  static/templates/actors/partials/item-summary.hbs
Labels: pr: enhancement

#11142 Update remaining mentions of "spell level(s)" in localized strings
  src/module/actor/sheet/helpers.ts
  src/module/apps/compendium-browser/tabs/spell.ts
  src/module/apps/world-clock/app.ts
  src/module/item/spell/document.ts
  src/module/item/spell/sheet.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
  src/scripts/config/index.ts
  src/scripts/handlebars.ts
  src/util/misc.ts
  static/lang/en.json
  static/templates/actors/spellcasting-prep-sheet.hbs
  static/templates/compendium-browser/partials/spell.hbs
  types/foundry/common/primitives/array.d.ts
Labels: remaster

#11148 Add leshy trait to Towering Growth
  packs/feats/towering-growth.json
Labels: pr: data update

#11152 Prevent stack overflow when accessing synthetic actors as effect origins
  src/module/item/abstract-effect/document.ts
Labels: pr: bugfix

#11147 Fix grindlegrub steak
  packs/equipment/grindlegrub-steak.json
Labels: pr: data update

#11153 Fix localization of spell ranks in NPC spellcasting config dialog
  static/templates/actors/spellcasting-dialog.hbs
Labels: pr: bugfix

#11154 Make `StrictArrayField` less explody when receiving invalid data
  src/module/system/schema-data-fields.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: bugfix

#11151 Add Metal and Wood to effect for Elemental Absorption
  packs/spell-effects/spell-effect-elemental-absorption.json
Labels: pr: data update

#11150 Add effects for Element Embodied (Metal) and Element Embodied (Wood)
  packs/spell-effects/spell-effect-element-embodied-air.json
  packs/spell-effects/spell-effect-element-embodied-earth.json
  packs/spell-effects/spell-effect-element-embodied-fire.json
  packs/spell-effects/spell-effect-element-embodied-metal.json
  packs/spell-effects/spell-effect-element-embodied-water.json
  packs/spell-effects/spell-effect-element-embodied-wood.json
  packs/spells/element-embodied.json
  static/lang/re-en.json
Labels: pr: data update

#11156 Bump verified core compatibility version to 11.315
  static/system.json
Labels: pr: housekeeping

#11158 Fix single action damage for Wronged Monk's Wrath
  packs/spells/wronged-monks-wrath.json
Labels: pr: data update

#11160 Fix recent modifier adjustments regression in damage rolls
  src/module/system/damage/formula.ts
Labels: pr: bugfix

#11155 Add temporary "Last Stop Before Remaster" message in migration 880
  src/module/migration/migrations/880-split-show-dialogs-setting.ts
  src/module/system/settings/index.ts
  static/lang/en.json
  static/templates/system/last-stop-message.hbs
Labels: remaster

#11161 Remove untyped damage links from Arboreal Snag's Axe Vulnerability
  packs/blood-lords-bestiary/arboreal-snag-axan-wood.json
  packs/blood-lords-bestiary/arboreal-snag.json
Labels: pr: data update

#11163 Move grant alterations to before temporary item construction
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix

#11146 Add Wood and Metal effects for Elemental Gift
  packs/spell-effects/spell-effect-elemental-gift.json
  packs/spells/elemental-gift.json
  static/lang/re-en.json
Labels: pr: data update

#11162 Add automation for Burning Mammoth Commando's Cruel Cutter
  packs/quest-for-the-frozen-flame-bestiary/burning-mammoth-commando.json
Labels: pr: data update

#11166 Release Notes 5.8.3
  CHANGELOG.md
  package.json
  static/lang/en.json
  static/system.json
Labels: pr: housekeeping

#11165 Show RE validation failures in rules panel of item sheets
  src/module/item/base/sheet/rule-element-form/base.ts
  src/styles/item/_rules.scss
  static/templates/items/rules-panel.hbs
  static/templates/items/rules/partials/outer.hbs
  types/foundry/common/abstract/data.d.ts
Labels: pr: enhancement, ui/ux

#11167 Clean up some damage links
  packs/adventure-specific-actions/repair-huntergate.json
  packs/age-of-ashes-bestiary/soulbound-ruin.json
  packs/boons-and-curses/milani-moderate-curse.json
  packs/pfs-season-4-bestiary/unbridled-necromantic-energy-1-2.json
  packs/pfs-season-4-bestiary/unbridled-necromantic-energy-3-4.json
  packs/vehicles/shark-diver.json
Labels: pr: data update

#11168 Add automation for Pleroma's Energy Touch
  packs/pathfinder-bestiary/pleroma.json
Labels: pr: data update

#11170 Add kingmaker army type trait descriptions
  src/scripts/config/traits.ts
  static/lang/kingmaker-en.json
Labels: kingmaker

#11174 perform deletions on embedded items in JSON migration script
  build/run-migration.ts
Labels: pr: bugfix, pr: housekeeping

#11145 Add support for including material damage effects in consumable inline rolls
  src/module/item/armor/data.ts
  src/module/item/consumable/data.ts
  src/module/item/consumable/sheet.ts
  src/module/item/container/data.ts
  src/module/item/equipment/data.ts
  src/module/item/melee/document.ts
  src/module/item/physical/data.ts
  src/module/item/physical/document.ts
  src/module/item/weapon/data.ts
  src/module/system/damage/formula.ts
  src/module/system/text-editor.ts
  src/styles/item/_index.scss
  static/lang/en.json
  static/templates/items/action-details.hbs
  static/templates/items/consumable-details.hbs
Labels: pr: enhancement

#11137 Remove spell components from actor sheets
  src/module/actor/creature/spell-preparation-sheet.ts
  src/scripts/register-templates.ts
  src/styles/actor/_spell-collection.scss
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/partials/spell-collection.hbs
  static/templates/actors/spell-preparation-sheet.hbs
Labels: ui/ux, remaster

#11178 Move inline silver trait for Silver Crescent to materials
  packs/equipment/silver-crescent-greater.json
  packs/equipment/silver-crescent-lesser.json
  packs/equipment/silver-crescent-moderate.json
Labels: pr: data update

#11176 Fix malformed predicates
  packs/equipment/entertainers-cincture.json
  packs/feats/ongoing-strategy.json
Labels: pr: data update

#11179 Remove aasimar/tiefling feats not being renamed
  packs/equipment/entertainers-cincture-greater.json
  packs/equipment/entertainers-cincture.json
  packs/feats/agathion-magic.json
  packs/feats/archon-magic.json
  packs/feats/asura-magic.json
  packs/feats/beastbrood.json
  packs/feats/bestial-manifestation.json
  packs/feats/blessed-blood-nephilim.json
  packs/feats/call-of-elysium.json
  packs/feats/celestial-strikes.json
  packs/feats/devil-in-plain-sight.json
  packs/feats/devilish-wiles.json
  packs/feats/divine-countermeasures.json
  packs/feats/divine-declaration.json
  packs/feats/dominion-aura.json
  packs/feats/emberkin.json
  packs/feats/empyreal-blessing.json
  packs/feats/enforced-order.json
  packs/feats/extraplanar-supplication.json
  packs/feats/faultspawn.json
  packs/feats/fiendish-strikes.json
  packs/feats/final-form.json
  packs/feats/finest-trick.json
  packs/feats/flame-jump.json
  packs/feats/garuda-magic.json
  packs/feats/garudas-squall.json
  packs/feats/grimspawn.json
  packs/feats/halo.json
  packs/feats/healers-halo.json
  packs/feats/idol-threat.json
  packs/feats/idyllkin.json
  packs/feats/jalmeri-rakshasa-magic.json
  packs/feats/lawbringer.json
  packs/feats/light-from-darkness.json
  packs/feats/musetouched.json
  packs/feats/nephilim-eyes.json
  packs/feats/nephilim-lore.json
  packs/feats/nephilim-resistance.json
  packs/feats/nimble-hooves.json
  packs/feats/peri-magic.json
  packs/feats/pitborn.json
  packs/feats/plumekith.json
  packs/feats/purge-sins.json
  packs/feats/qlippoth-magic.json
  packs/feats/radiate-glory.json
  packs/feats/rakshasa-magic.json
  packs/feats/reveal-hidden-self.json
  packs/feats/riftmarked.json
  packs/feats/shackleborn.json
  packs/feats/skillful-tail-nephilim.json
  packs/feats/summon-nephilim-kin.json
  packs/feats/towering-presence.json
  packs/feats/tranquil-sanctuary.json
  packs/feats/truespeech.json
  packs/feats/velstrac-magic.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#11189 Drop dual class and ancestry paragon variants
  src/global.ts
  src/module/actor/character/feats.ts
  src/module/item/class/document.ts
  src/module/migration/migrations/880-split-show-dialogs-setting.ts
  src/module/system/settings/variant-rules.ts
  static/lang/en.json
  static/templates/system/last-stop-message.hbs
  static/templates/system/settings/variant-rules.hbs
Labels: pr: enhancement, remaster

#11191 Fix some sources
  packs/actions/avert-gaze.json
  packs/actions/crawl.json
  packs/equipment/breastplate.json
  packs/equipment/class-kit-cleric.json
  packs/equipment/class-kit-druid.json
  packs/equipment/class-kit-witch.json
  packs/equipment/cloak-of-elvenkind.json
  packs/equipment/crossbow.json
  packs/equipment/crystal-ball-clear-quartz.json
  packs/equipment/energy-breath-potion-cold-moderate.json
  packs/equipment/guisarme.json
  packs/equipment/half-plate.json
  packs/equipment/halfling-sling-staff.json
  packs/equipment/hand-crossbow.json
  packs/equipment/hatchet.json
  packs/equipment/katar.json
  packs/equipment/mages-hat-greater.json
  packs/equipment/musical-instrument-virtuoso-heavy.json
  packs/equipment/oil-of-unlife-greater.json
  packs/equipment/oil-of-weightlessness-greater.json
  packs/equipment/orichalcum-chunk.json
  packs/equipment/orichalcum-ingot.json
  packs/equipment/orichalcum-shield-high-grade.json
  packs/equipment/staff-of-healing-greater.json
  packs/equipment/staff-of-healing-major.json
  packs/equipment/tool-long.json
  packs/feats/bespell-strikes.json
  packs/feats/skill-mastery-rogue.json
Labels: pr: data update

#11183 Add vitality type to some healing effects
  packs/equipment/healers-gloves-greater.json
  packs/equipment/healers-gloves.json
  packs/feats/vivacious-conduit.json
Labels: pr: data update

#11184 Add vitality type to Fresh Produce healing
  packs/feat-effects/effect-fresh-produce.json
  packs/feats/fresh-produce.json
Labels: pr: data update

#11187 Add effect for Protector's Sphere
  packs/spell-effects/aura-protectors-sphere.json
  packs/spell-effects/spell-effect-protectors-sphere.json
  packs/spells/protectors-sphere.json
Labels: pr: data update

#11188 Fix prerequisites for Ironblood Stance
  packs/feats/ironblood-stance.json
Labels: pr: data update

#11190 Update Moonburst's inline vitality damage link to autolevel
  packs/spells/moonburst.json
Labels: pr: data update

#11090 Remove necessity of "hb_" prefix in homebrew elements
  src/module/actor/character/feats.ts
  src/module/apps/compendium-browser/tabs/action.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/campaign-feature.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/spell.ts
  src/module/migration/migrations/881-no-hb-prefix.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/helpers.ts
  src/module/system/settings/homebrew/menu.ts
  src/scripts/config/index.ts
  src/scripts/config/traits.ts
  static/lang/en.json
  static/templates/system/settings/homebrew.hbs
Labels: pr: data migration, pr: enhancement

#11182 Account for `Document#update` returning `undefined`
  src/module/actor/base.ts
  src/module/actor/creature/sheet.ts
  src/module/item/base/document.ts
  src/module/item/kit/sheet.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
  types/foundry/common/abstract/document.d.ts
Labels: pr: bugfix

#11192 Coerce resolvable negative numeric strings to actual numbers
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/data.ts
  static/icons/default-icons/shield.svg
Labels: pr: bugfix

#11185 Include all traits in scrolls/wands generated from spells
  src/module/item/consumable/spell-consumables.ts
  src/module/item/consumable/types.ts
  src/scripts/config/traits.ts
Labels: pr: bugfix

#11026 Prune and reorganize several areas of spell data
  build/lib/extractor.ts
  build/run-migration.ts
  src/module/actor/creature/helpers.ts
  src/module/actor/sheet/helpers.ts
  src/module/apps/compendium-browser/tabs/spell.ts
  src/module/item/armor/document.ts
  src/module/item/physical/runes.ts
  src/module/item/spell/data.ts
  src/module/item/spell/document.ts
  src/module/item/spell/helpers.ts
  src/module/item/spell/sheet.ts
  src/module/item/spell/types.ts
  src/module/item/spell/values.ts
  src/module/item/weapon/document.ts
  src/module/migration/migrations/605-catch-up-to-template-json.ts
  src/module/migration/migrations/621-remove-config-spell-schools.ts
  src/module/migration/migrations/626-update-spell-category.ts
  src/module/migration/migrations/627-lowercase-spell-saves.ts
  src/module/migration/migrations/638-spell-components.ts
  src/module/migration/migrations/659-multiple-damage-rows.ts
  src/module/migration/migrations/663-fix-spell-damage.ts
  src/module/migration/migrations/674-stable-homebrew-tag-ids.ts
  src/module/migration/migrations/703-spell-damage-structure.ts
  src/module/migration/migrations/747-fixed-heightening.ts
  src/module/migration/migrations/829-rm-ritual-entries.ts
  src/module/migration/migrations/846-spell-school-optional.ts
  src/module/migration/migrations/882-spell-data-reorganization.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/system/damage/types.ts
  src/scripts/config/index.ts
  src/scripts/config/iwr.ts
  src/scripts/config/traits.ts
  src/styles/item/_index.scss
  src/styles/item/_spell-sheet.scss
  static/lang/en.json
  static/template.json
  static/templates/items/spell-details.hbs
  static/templates/items/spell-overlay.hbs
  static/templates/items/spell-sidebar.hbs
Labels: pr: data migration, remaster

#11193 Don't use `setFlags` in roll dialogs
  src/module/system/check/dialog.ts
  src/module/system/damage/dialog.ts
Labels: pr: refactor

#11199 Reduce type coercion in migration 882
  src/module/migration/migrations/882-spell-data-reorganization.ts
Labels: pr: refactor

#11202 Fix migration 879 of Ongoing Strategy
  packs/feats/ongoing-strategy.json
  src/module/migration/migrations/879-devise-a-stratagem-and-friends.ts
Labels: pr: bugfix, pr: data update

#11205 Fix `saveType` value in `SpellPF2e#getChatData`
  src/module/item/spell/document.ts
Labels: pr: bugfix

#11214 Include parent roll options when predicate-testing item alterations
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: bugfix

#11203 Fill the price value of the staff of the desert winds (major)
  packs/equipment/staff-of-the-desert-winds-major.json
Labels: pr: data update

#11206 Set the price for Impulse control
  packs/equipment/impulse-control.json
Labels: pr: data update

#11207 Remove incorrect elite adjustments from compendium NPCs
  packs/agents-of-edgewatch-bestiary/clockwork-chopper.json
  packs/agents-of-edgewatch-bestiary/mr-snips.json
  packs/agents-of-edgewatch-bestiary/pulping-golem.json
  packs/spells/cinder-swarm.json
Labels: pr: data update

#11210 Add 20ft emanation to Final Sacrifice
  packs/spells/final-sacrifice.json
Labels: pr: data update

#11211 Add localized notes for Holy and Unholy Water
  packs/equipment/holy-water.json
  packs/equipment/unholy-water.json
  static/lang/re-en.json
Labels: pr: data update

#11213 Add effect for Raise Menhir
  packs/feat-effects/effect-raise-menhir.json
  packs/feats/raise-menhir.json
Labels: pr: data update

#11216 Fix reserved term check in `HomebrewElements#_onSubmit`
  src/module/system/settings/homebrew/menu.ts
Labels: pr: bugfix

#11223 Fix overeager splice in spell consumable creation
  src/module/item/consumable/spell-consumables.ts
Labels: pr: bugfix

#11225 Fix and consolidate some spellcasting localization entries
  src/scripts/config/index.ts
  static/lang/en.json
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/spellcasting-dialog.hbs
  static/templates/gm/check-prompt.hbs
  static/templates/items/spell-details.hbs
Labels: pr: bugfix, pr: refactor

#11217 Update effect for Weapon Surge
  packs/spell-effects/spell-effect-weapon-surge.json
  packs/spells/weapon-surge.json
Labels: pr: data update

#11218 Add effect for Force Shield
  packs/equipment-effects/effect-force-shield.json
  packs/equipment/force-shield.json
Labels: pr: data update

#11219 Add ChoiceSet to Beast Trainer
  packs/feats/beast-trainer.json
Labels: pr: data update

#11220 Add Floating Spores to Poisonous Mold
  packs/hazards/poisonous-mold.json
Labels: pr: data update

#11233 Fix tagification of divine attributes on deity sheet
  src/module/item/deity/sheet.ts
Labels: pr: bugfix

#11229 Finish remaster changes tables
  packs/feats/spellshape-channel.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#11239 Fix regression in inclusion of action traits on strike damage rolls
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
Labels: pr: bugfix

#11240 Remove errant HTML entities from Force Bolt description
  packs/spells/force-bolt.json
Labels: pr: data update

#11242 Add actor roll options for deity sanctification options
  src/module/item/deity/document.ts
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: enhancement, remaster

#11245 Add unified effect for Sweet Dream and update
  packs/spell-effects/spell-effect-sweet-dream.json
  packs/spells/sweet-dream.json
  static/lang/re-en.json
Labels: pr: data update
