Repository foundryvtt/pf2e, pull requests merged in 2023-08, with the labels that each got.

#9052 Stop re-rendering item sidebar 5000 times during choice set queries
  src/module/item/base.ts
Labels: pr: bugfix

#9049 Fix typo in Sewer Dragon background
  packs/backgrounds/sewer-dragon.json
Labels: pr: data update

#9037 Test damage dice REs with parent roll options
  src/module/rules/rule-element/damage-dice.ts
Labels: pr: bugfix

#9022 Reframe creature ability scores as modifiers
  build/run-migration.ts
  src/module/actor/character/attribute-builder.ts
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/helpers.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/data.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/ancestry/document.ts
  src/module/item/background/document.ts
  src/module/item/class/document.ts
  src/module/item/feat/document.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/migration/migrations/852-ability-scores-to-modifiers.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/sheet/helpers.ts
  src/scripts/register-templates.ts
  src/styles/actor/character/_attribute-builder.scss
  src/styles/actor/character/_character.scss
  static/lang/en.json
  static/templates/actors/character/attribute-builder.hbs
  static/templates/actors/character/partials/abilities.hbs
  static/templates/actors/character/partials/attributes.hbs
  static/templates/actors/character/tabs/general.hbs
Labels: pr: data migration, pr: data update, remaster

#9057 Render character hero points in template
  src/module/actor/character/sheet.ts
  static/templates/actors/character/partials/header.hbs
Labels: pr: refactor

#9058 Reset actors when campaignFeats setting changes
  src/module/system/settings/index.ts
Labels: pr: enhancement

#9053 Fix spelling of Sussuran language
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data update

#9065 Add healing-received +5 to Godless Healing feat
  packs/feats/godless-healing.json
Labels: pr: data update

#9068 Updated equipment images.
  packs/equipment/aboutface-figurehead.json
  packs/equipment/accompaniment-cloak.json
  packs/equipment/achaekeks-kiss.json
  packs/equipment/acid-spitter.json
  packs/equipment/aeon-stone-cymophane-cabochon.json
  packs/equipment/aeon-stone-olivine-pendeloque.json
Labels: pr: data update

#9070 Catch missed cases in migration 852
  packs/classfeatures/infused-reagents.json
  packs/feats/thaumaturges-investiture.json
  packs/iconics/fumbus-level-1.json
  packs/iconics/fumbus-level-3.json
  packs/iconics/fumbus-level-5.json
  packs/kingmaker-bestiary/jubilost-level-1.json
  packs/kingmaker-bestiary/jubilost-level-8.json
  src/module/migration/migrations/852-ability-scores-to-modifiers.ts
Labels: pr: bugfix, pr: data update

#9072 Support custom modifiers for kingdom skills
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/kingdom/sheet.ts
  src/styles/actor/party/kingdom/_activities.scss
  src/styles/actor/party/kingdom/_index.scss
  static/templates/actors/party/kingdom/activities.hbs
Labels: pr: enhancement

#9073 Improve automation of Flame Wisp
  packs/spell-effects/spell-effect-flame-wisp.json
Labels: pr: data update

#9074 Add Scions of Domora archetype journal entry
  packs/journals/archetypes.json
Labels: pr: data update

#9069 Scrub remaining instances of "flat-footed" in localization files
  static/lang/action-en.json
  static/lang/en.json
Labels: pr: data update

#9075 Set bonus bulk values for NPCs
  src/module/actor/inventory/bulk.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#9076 Hide GM-hidden tokens from (GMs controlling tokens with) tremorsense
  src/module/canvas/perception/modes.ts
Labels: pr: bugfix

#9079 Fix regression with updating hero points
  static/templates/actors/character/partials/header.hbs
Labels: pr: bugfix

#9080 Fix some incorrect localization strings
  packs/classfeatures/fourth-gates-threshold.json
  packs/classfeatures/gates-threshold.json
  packs/classfeatures/second-gates-threshold.json
  packs/classfeatures/third-gates-threshold.json
Labels: pr: data update

#9056 Fix more party sheet bugs
  src/module/actor/party/document.ts
  src/module/actor/party/sheet.ts
  src/module/item/base.ts
  static/templates/actors/party/sheet.hbs
  static/templates/sidebar/party-document-partial.hbs
Labels: pr: bugfix

#9081 Add Elemental Instinct to instinct choices
  packs/classfeatures/elemental-instinct.json
  packs/classfeatures/instinct.json
Labels: pr: data update

#9082 Update elementalist archetype
  packs/classfeatures/elemental-magic.json
  packs/feats/burning-spell.json
  packs/feats/dousing-spell.json
  packs/feats/elemental-familiar.json
  packs/feats/elementalist-dedication.json
  packs/feats/metabolize-element.json
  packs/feats/redirect-elements.json
  packs/feats/rockslide-spell.json
  packs/feats/wind-tossed-spell.json
Labels: pr: data update

#9086 Correct the price of Starsong Nectar from Treasure Vault
  packs/equipment/starsong-nectar.json
Labels: pr: data update, source: rulebooks

#9085 Add PFS 4-99 errata from org play major convensions planning server
  packs/pfs-season-4-bestiary/ambush-assassin.json
  packs/pfs-season-4-bestiary/nathatel-3-4.json
  packs/pfs-season-4-bestiary/nathatel-5-6.json
  packs/pfs-season-4-bestiary/nathatel-7-8.json
  packs/pfs-season-4-bestiary/serraleth-7-8.json
  packs/pfs-season-4-bestiary/serraleth.json
Labels: pr: data update, source: pathfinder society

#9089 Change case on some spells and feats to match standard
  packs/feats/one-with-earth.json
  packs/feats/one-with-the-land.json
  packs/journals/archetypes.json
  packs/rage-of-elements-bestiary/jann-shuyookh.json
  packs/spell-effects/spell-effect-one-with-the-land.json
  packs/spells/one-with-plants.json
  packs/spells/one-with-stone.json
  packs/spells/one-with-the-land.json
Labels: pr: data update

#9063 Vehicle data fixes/adds
  packs/vehicles/battery-tower.json
  packs/vehicles/bunta.json
  packs/vehicles/helepolis.json
  packs/vehicles/sand-racer.json
  packs/vehicles/sandsailer.json
  packs/vehicles/siege-tower.json
  packs/vehicles/sky-chariot-heavy.json
Labels: pr: data update

#9091 Add images to several weapons missing them
  packs/equipment/earthbreaker.json
  packs/equipment/gakgung.json
Labels: pr: data update

#9093 Type vehicle/hazard `system.traits.languages` property as `never`
  src/module/actor/hazard/data.ts
  src/module/actor/vehicle/data.ts
Labels: pr: types update

#9087 Fix prefix of PC attribute roll options
  src/module/actor/character/document.ts
Labels: pr: bugfix

#9083 More party sheet tweaks and fixes
  src/module/actor/party/document.ts
  src/module/actor/party/sheet.ts
  src/module/system/settings/metagame.ts
  src/styles/actor/party/_index.scss
  src/styles/actor/party/_overview.scss
  static/templates/actors/party/regions/exploration.hbs
  static/templates/actors/party/regions/inventory-members.hbs
  static/templates/actors/party/regions/overview.hbs
  static/templates/actors/party/sheet.hbs
Labels: pr: enhancement

#9092 Add remaster changes journal
  packs/journals/remaster-changes.json
Labels: pr: data entry

#9096 Inform `Statistic` of targeted class-statistic checks
  src/module/system/statistic/index.ts
Labels: pr: enhancement

#9097 Add inline @Check to Elemental Blast action
  packs/actions/elemental-blast.json
Labels: pr: data update

#9095 Release Notes 5.3.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#9060 Display vehicle source in description tab
  static/templates/actors/vehicle/tabs/vehicle-description.hbs
Labels: pr: bugfix

#9098 Grant Channel Elements action from Kinetic Aura class feature
  packs/classfeatures/kinetic-aura.json
Labels: pr: data update

#9110 Fix attribute boost buttons sometimes not reflecting being clicked
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#9113 Indicate compatibility with FVTT 11.307
  src/module/actor/base.ts
  src/module/encounter/document.ts
  src/module/macro.ts
  static/system.json
Labels: pr: housekeeping

#9117 Add "damage" selector to @Damage
  src/module/system/text-editor.ts
Labels: pr: enhancement

#9118 Fix some damage selectors
  packs/feats/student-of-the-staff.json
  packs/kingmaker-bestiary/auchs.json
  packs/kingmaker-bestiary/kressle.json
  packs/kingmaker-bestiary/old-crackjaw.json
  packs/kingmaker-bestiary/satinder-morne.json
  packs/outlaws-of-alkenstar-bestiary/atticus.json
  packs/outlaws-of-alkenstar-bestiary/corrupt-shieldmarshal-clan-pistol.json
  packs/outlaws-of-alkenstar-bestiary/corrupt-shieldmarshal-jezail.json
  packs/outlaws-of-alkenstar-bestiary/leadsmith.json
  packs/pathfinder-bestiary-2/aurumvorax.json
  packs/pathfinder-bestiary-3/flaming-skull.json
  packs/pathfinder-bestiary-3/gurgist-mauler.json
  packs/pfs-season-3-bestiary/arisept-7-8.json
  packs/pfs-season-3-bestiary/arisept-9-10.json
  packs/pfs-season-3-bestiary/fasiel-ibn-sazadin-1-2.json
  packs/pfs-season-3-bestiary/fasiel-ibn-sazadin-3-4.json
  packs/pfs-season-3-bestiary/thundering-wihsaak-heretical.json
  packs/pfs-season-4-bestiary/fasiel-ibn-sazadin-5-6.json
  packs/pfs-season-4-bestiary/pups.json
  packs/pfs-season-4-bestiary/ulfen-soldier.json
  packs/pfs-season-4-bestiary/veteran-ulfen-soldier.json
  packs/rage-of-elements-bestiary/jann-shuyookh.json
Labels: pr: data update

#9123 Assume actor is level 1 in @Damage instead of skipping
  src/module/system/text-editor.ts
Labels: pr: enhancement

#9125 Add types for new static methods on `BaseActor` and `BaseItem`
  types/foundry/common/documents/actor.d.ts
  types/foundry/common/documents/item.d.ts
Labels: pr: types update

#9124 Remove some workarounds of resolved upstream issues
  src/module/macro.ts
  src/module/scene/token-document/document.ts
  static/system.json
Labels: pr: refactor

#9126 Override `BaseItem.getDefaultArtwork`
  src/module/item/base.ts
Labels: pr: refactor

#9099 Fix broken links in remaster journal
  packs/journals/remaster-changes.json
Labels: pr: data update

#9128 Handle top level math terms and subtraction in @Damage
  src/module/system/damage/helpers.ts
Labels: pr: bugfix

#9127 Remove inline vitality and void damage
  packs/feats/solar-detonation.json
  packs/rage-of-elements-bestiary/ardande-gardener.json
  packs/spells/hungry-depths.json
Labels: pr: data update

#9134 Add Translate to list of renamed spells
  packs/journals/remaster-changes.json
Labels: pr: data update

#9122 Automate Bristle's inline damage increase
  packs/actions/barbed-quills.json
  packs/feat-effects/effect-bristle.json
  packs/feats/bristle.json
Labels: pr: data update

#9100 Change the Kinetic Gate feature to be renamed with the choices
  packs/classfeatures/kinetic-gate.json
Labels: pr: data update

#9135 Fix Spiderfoot Brew item variants
  packs/equipment-effects/effect-spiderfoot-brew-greater.json
  packs/equipment-effects/effect-spiderfoot-brew-lesser.json
  packs/equipment-effects/effect-spiderfoot-brew-moderate.json
  packs/equipment/spiderfoot-brew-greater.json
  packs/equipment/spiderfoot-brew-lesser.json
  packs/equipment/spiderfoot-brew-moderate.json
Labels: pr: data update

#9136 Fix bravery baldric descriptions
  packs/equipment/bravery-baldric-fleet.json
  packs/equipment/bravery-baldric-flight.json
  packs/equipment/bravery-baldric-haste.json
  packs/equipment/bravery-baldric-restoration-greater.json
  packs/equipment/bravery-baldric-restoration.json
  packs/equipment/bravery-baldric-stoneskin.json
Labels: pr: data update

#9139 Respect `overrideTraits` (and its absence) in @Damage expressions
  src/module/system/text-editor.ts
Labels: pr: bugfix

#9137 Automatically classify some inline checks as attack rolls
  src/scripts/hooks/render-dialog.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: enhancement

#9144 Add automation for Martial Performance feat
  packs/feats/martial-performance.json
Labels: pr: data update

#9143 Fix party sheet speeds and update summary
  src/module/actor/party/data.ts
  src/module/actor/party/document.ts
  src/module/actor/party/sheet.ts
  static/lang/en.json
  static/templates/actors/party/regions/exploration.hbs
  static/templates/actors/party/regions/overview.hbs
Labels: pr: enhancement

#9141 Migrate bracketed AE-likes modifying ability scores
  build/run-migration.ts
  src/module/migration/migrations/852-ability-scores-to-modifiers.ts
  src/module/migration/migrations/854-bracketed-ability-scores-to-modifiers.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration

#9142 Add knockdown to cinder wolf strikes from PFS 1-14
  packs/pfs-season-1-bestiary/cinder-wolf-1-2.json
  packs/pfs-season-1-bestiary/cinder-wolf-3-4.json
Labels: pr: data update, source: pathfinder society

#9147 Add new language changes to remaster journal
  packs/journals/remaster-changes.json
  packs/rage-of-elements-bestiary/gennayn.json
  packs/spell-effects/spell-effect-frostbite.json
  packs/spells/frostbite.json
Labels: pr: data update

#9146 Show GMs remaster changes journal entry once (ever) on startup
  src/global.d.ts
  src/module/system/settings/index.ts
  src/scripts/hooks/ready.ts
Labels: pr: enhancement

#9149 Make `BaseUser#character` generic
  src/global.d.ts
  src/module/user/document.ts
  types/foundry/client/config.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/user.d.ts
  types/foundry/client/game.d.ts
  types/foundry/common/abstract/backend.d.ts
  types/foundry/common/documents/user.d.ts
Labels: pr: types update

#9153 Attribute the @Damage roll to the actor that owns it
  src/module/system/text-editor.ts
Labels: pr: bugfix

#9152 Refactor @Damage extraction to use DamageInstance.getValue() more
  src/module/system/damage/helpers.ts
Labels: pr: refactor

#9155 Fix regression in setting default token icon
  src/module/actor/base.ts
  static/icons/default-icons/character.svg
  static/icons/default-icons/npc.svg
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/common/documents/actor.d.ts
Labels: pr: bugfix

#9158 Release Notes 5.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#9161 Rename `ABILITY_ABBREVIATIONS` and `AbilityString`
  CHANGELOG.md
  src/module/actor/character/attribute-builder.ts
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/types.ts
  src/module/actor/creature/data.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/creature/types.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/initiative.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/types.ts
  src/module/actor/values.ts
  src/module/item/abc/sheet.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/ancestry/data.ts
  src/module/item/ancestry/document.ts
  src/module/item/background/data.ts
  src/module/item/class/data.ts
  src/module/item/deity/data.ts
  src/module/item/feat/data.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/data.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/item/spellcasting-entry/types.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/migration/migrations/653-aes-to-res.ts
  src/module/migration/migrations/696-flat-ability-modifiers.ts
  src/module/migration/migrations/767-convert-voluntary-flaws.ts
  src/module/rules/rule-element/battle-form/types.ts
  src/module/rules/rule-element/fixed-proficiency.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/strike.ts
  src/module/system/damage/weapon.ts
  src/module/system/statistic/data.ts
  src/module/system/statistic/index.ts
  src/scripts/config/index.ts
Labels: pr: refactor

#9164 Add `Statistic` rule element, utilize to create Impulse statistic
  packs/actions/elemental-blast.json
  packs/classfeatures/impulses.json
  packs/equipment/gate-attenuator-greater.json
  packs/equipment/gate-attenuator-major.json
  packs/equipment/gate-attenuator.json
  src/module/actor/base.ts
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/actor/familiar/document.ts
  src/module/actor/npc/document.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/vehicle/document.ts
  src/module/chat-message/helpers.ts
  src/module/rules/helpers.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/fixed-proficiency.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/statistic.ts
  src/module/rules/synthetics.ts
  src/module/system/schema-data-fields.ts
  src/scripts/ui/inline-roll-links.ts
  static/lang/action-en.json
  static/lang/re-en.json
Labels: pr: data update, pr: new feature

#9169 Remove erroneous Arrow Slavo spell
  packs/spells/arrow-slavo.json
Labels: pr: data update

#9174 Fix celestial staff description
  packs/equipment/celestial-staff.json
Labels: pr: data update

#9184 Add `StrictStringField`, utilize in RE schemas
  src/module/rules/rule-element/roll-option.ts
  src/module/system/schema-data-fields.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: enhancement

#9185 Remove prototype token name from zombie charger
  packs/pfs-season-1-bestiary/zombie-charger.json
Labels: pr: data update

#9180 Add missing spell DC to Obrousian
  packs/agents-of-edgewatch-bestiary/obrousian.json
  packs/book-of-the-dead-bestiary/obrousian.json
Labels: pr: data update

#9179 Fix inline damage of Eldritch Flare
  packs/equipment/eldritch-flare.json
Labels: pr: data update

#9177 Fix immunities of Choking Tethers hazard
  packs/blood-lords-bestiary/choking-tethers.json
Labels: pr: data update

#9178 Add area to Grasping Grave focus spell
  packs/spells/grasping-grave.json
Labels: pr: data update

#9186 Consolidate action/feat duplicate code into helpers
  src/module/item/action/document.ts
  src/module/item/action/helpers.ts
  src/module/item/action/sheet.ts
  src/module/item/campaign-feature/document.ts
  src/module/item/campaign-feature/sheet.ts
  src/module/item/feat/document.ts
  src/module/item/feat/sheet.ts
Labels: pr: refactor

#9188 Fix provision of arguments in reroll hooks
  src/module/system/check/check.ts
Labels: pr: bugfix

#9196 Further loosen effect-origin safety check
  src/module/item/abstract-effect/document.ts
Labels: pr: bugfix

#9200 Defer creation of strike-variant button labels
  src/module/actor/character/document.ts
Labels: pr: bugfix

#9195 Allow Aura RE to include effect level
  src/module/actor/base.ts
  src/module/actor/types.ts
  src/module/rules/rule-element/aura.ts
Labels: pr: enhancement

#9197 Fix major vigilant eye description
  packs/equipment/vigilant-eye-major.json
Labels: pr: data update

#9199 Take token step toward renaming action items as ability items
  build/lib/extractor.ts
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/hazard/types.ts
  src/module/actor/npc/types.ts
  src/module/actor/vehicle/sheet.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/item/ability/data.ts
  src/module/item/ability/document.ts
  src/module/item/ability/helpers.ts
  src/module/item/ability/index.ts
  src/module/item/ability/sheet.ts
  src/module/item/ability/types.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/action/types.ts
  src/module/item/affliction/sheet.ts
  src/module/item/campaign-feature/document.ts
  src/module/item/campaign-feature/sheet.ts
  src/module/item/data/base.ts
  src/module/item/data/index.ts
  src/module/item/feat/document.ts
  src/module/item/feat/sheet.ts
  src/module/item/index.ts
  src/module/item/physical/data.ts
  src/module/item/spell/document.ts
  src/module/item/types.ts
  src/module/migration/migrations/828-prune-invalid-traits.ts
  src/module/migration/migrations/839-action-categories.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/synthetics.ts
  src/scripts/config/index.ts
  src/scripts/register-sheets.ts
  src/scripts/ui/inline-roll-links.ts
  static/lang/en.json
Labels: pr: refactor, remaster

#9193 Support frequency alterations and Consistent Surge
  packs/feats/consistent-surge.json
  src/module/item/data/base.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
Labels: pr: enhancement

#9203 Use `Statistic` for familiar attack-roll statistic
  src/module/actor/familiar/data.ts
  src/module/actor/familiar/document.ts
  src/module/actor/familiar/sheet.ts
  static/templates/actors/familiar-sheet.hbs
Labels: pr: refactor

#9205 Nudge `FilePicker` launched from `TokenConfig` to redirect to root
  src/module/actor/base.ts
  src/module/scene/token-document/sheet.ts
  types/foundry/client/application/form-application/base.d.ts
  types/foundry/client/ui/filepicker.d.ts
  types/foundry/common/documents/actor.d.ts
Labels: pr: enhancement

#9211 Fix kingdom builder localization and restrict worksites to ore/lumber/stone
  src/module/actor/party/kingdom/builder.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/kingdom/types.ts
  src/module/actor/party/kingdom/values.ts
  static/lang/kingmaker-en.json
  static/templates/actors/party/kingdom/builder.hbs
  static/templates/actors/party/kingdom/main.hbs
Labels: pr: bugfix

#9210 Fix bugged description for Composite trait
  src/scripts/config/traits.ts
Labels: pr: data update

#9191 Fix greater clockwork shield description
  packs/equipment/clockwork-shield-greater.json
Labels: pr: data update

#9206 Add Shory Language from Stolen Fate Player's Guide
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data update

#9213 Add getter for max affliction stage + minor cleanup
  src/module/item/affliction/document.ts
Labels: pr: housekeeping

#9170 Fix hero points with non-standard max value
  src/module/actor/character/sheet.ts
  src/module/system/check/check.ts
  static/templates/actors/character/partials/header.hbs
Labels: pr: bugfix

#9218 Replace "scorching ray" with "blazing bolt" in description
  packs/spells/blazing-bolt.json
Labels: pr: data update

#9219 Show all property runes on ABP magic items embedded in loot actors
  src/module/item/physical/runes.ts
Labels: pr: enhancement, ui/ux

#9225 Make `Too Angry to Die` a Reaction
  packs/feats/too-angry-to-die.json
Labels: pr: data update

#9212 Force attribute modifier of spellshot class DC to be int
  packs/classfeatures/way-of-the-spellshot.json
Labels: pr: data update

#9207 Remove Persistence of Memory ability from Shadow King's statblock
  packs/stolen-fate-bestiary/the-shadow-prince.json
Labels: pr: data update

#9157 Add leveled damage/healing to kineticists impulses
  packs/feats/aerial-boomerang.json
  packs/feats/ambush-bladderwort.json
  packs/feats/ash-strider.json
  packs/feats/blazing-wave.json
  packs/feats/call-the-hurricane.json
  packs/feats/command-elemental.json
  packs/feats/dash-of-herbs.json
  packs/feats/driving-rain.json
  packs/feats/elemental-artillery.json
  packs/feats/flinging-updraft.json
  packs/feats/flying-flame.json
  packs/feats/fresh-produce.json
  packs/feats/hail-of-splinters.json
  packs/feats/infinite-expanse-of-bluest-heaven.json
  packs/feats/jagged-berms.json
  packs/feats/lava-leap.json
  packs/feats/lightning-dash.json
  packs/feats/lightning-rod.json
  packs/feats/living-bonfire.json
  packs/feats/magnetic-pinions.json
  packs/feats/molten-wire.json
  packs/feats/oceans-balm.json
  packs/feats/rain-of-razors.json
  packs/feats/rain-of-rust.json
  packs/feats/ravel-of-thorns.json
  packs/feats/retch-rust.json
  packs/feats/rising-hurricane.json
  packs/feats/roiling-mudslide.json
  packs/feats/sanguivolent-roots.json
  packs/feats/scorching-column.json
  packs/feats/scrap-barricade.json
  packs/feats/sea-glass-guardians.json
  packs/feats/shard-strike.json
  packs/feats/solar-detonation.json
  packs/feats/spike-skin.json
  packs/feats/steam-knight.json
  packs/feats/storm-spiral.json
  packs/feats/tidal-hands.json
  packs/feats/torrent-in-the-blood.json
  packs/feats/tree-of-duality.json
  packs/feats/tremor.json
  packs/feats/tumbling-lumber.json
  packs/feats/volcanic-escape.json
  packs/feats/walk-through-the-conflagration.json
  packs/feats/weight-of-stone.json
  packs/feats/whirling-grindstone.json
  packs/feats/wiles-on-the-wind.json
  packs/feats/winters-clutch.json
  packs/feats/witchwood-seed.json
Labels: pr: data update

#9220 Add duration and traditions to One with Stone
  packs/spells/one-with-stone.json
Labels: pr: data update

#9228 Add more class/spell search options to `ActorPF2e#getStatistic`
  src/module/actor/character/document.ts
  src/module/actor/character/types.ts
  src/module/actor/creature/document.ts
Labels: pr: enhancement

#9192 Grant conditions when affliction stage changes
  src/module/item/affliction/document.ts
  src/module/item/condition/document.ts
Labels: pr: enhancement

#9237 Remove errant leftover setting of clear-template-buttons display style
  src/module/chat-message/listeners/cards.ts
Labels: pr: bugfix

#9226 Automate Blasting Beams deviant ability
  packs/classfeatures/dragon-deviant-classification.json
  packs/feats/blasting-beams.json
  packs/feats/consume-energy.json
  static/lang/re-en.json
Labels: pr: data update

#9229 Allow configuration of active party
  src/global.d.ts
  src/module/actor/party/document.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/collection/actors.ts
  src/module/system/settings/index.ts
  src/styles/ui/sidebar/_actor-directory.scss
  static/lang/en.json
  static/templates/sidebar/party-document-partial.hbs
Labels: pr: enhancement

#9236 Add Versatile Poison trait
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#9233 Determine that scene is in focus before checking auras
  src/module/scene/document.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#9241 Add convenience getters in `ActorConditions` for use by REs
  src/module/actor/conditions.ts
  src/module/rules/rule-element/base.ts
Labels: pr: enhancement

#9242 Simplify subterms of `IntermediateDie`s
  src/module/system/damage/terms.ts
Labels: pr: bugfix, pr: enhancement

#9235 Set hit points roll options for all actor types
  src/module/actor/character/document.ts
  src/module/actor/familiar/document.ts
  src/module/actor/hazard/document.ts
  src/module/actor/helpers.ts
  src/module/actor/npc/document.ts
  src/module/actor/vehicle/document.ts
Labels: pr: enhancement, pr: refactor

#9238 Add Swallow-Spike armor property runes
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data update

#9244 Attempt to resolve `IntermediateDie`s to `Die`s as soon as possible
  src/module/system/damage/helpers.ts
  src/module/system/damage/terms.ts
Labels: pr: enhancement

#9232 Add `removeAfterRoll` property to FlatModifer REs
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/system/schema-data-fields.ts
  src/module/system/statistic/index.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: enhancement

#9245 Deduplicate modifiers at `BaseStatistic` level
  src/module/actor/modifiers.ts
  src/module/system/statistic/index.ts
Labels: pr: bugfix

#9246 Release Notes 5.3.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#9247 Add `mergeExisting` property to Aura RE
  src/module/rules/rule-element/aura.ts
Labels: pr: enhancement

#9250 Fix some malformed predicates
  packs/equipment/aeon-stone-olivine-pendeloque.json
  packs/feats/grove-harbored.json
  packs/spell-effects/spell-effect-take-root.json
Labels: pr: data update

#9248 Level-zero-and-back the Merisiels
  packs/iconics/merisiel-level-1.json
  packs/iconics/merisiel-level-3.json
  packs/iconics/merisiel-level-5.json
  packs/paizo-pregens/merisiel-beginner-box.json
Labels: pr: data update

#9251 Fix some shield usages
  packs/equipment/broadleaf-shield-greater.json
  packs/equipment/broadleaf-shield-major.json
  packs/equipment/broadleaf-shield-true.json
  packs/equipment/broadleaf-shield.json
  packs/equipment/kizidhars-shield.json
  packs/equipment/limestone-shield.json
Labels: pr: data update

#9209 Fix description of Level 3 Gate Attenuator Item
  packs/equipment/gate-attenuator.json
Labels: pr: data update

#9254 Fix links
  packs/classes/kineticist.json
  packs/equipment/fossil-fragment-amber-mosquito.json
  packs/equipment/fossil-fragment-brontosaurus-phalange.json
  packs/equipment/fossil-fragment-deinonychus-claw.json
  packs/equipment/fossil-fragment-eurypterid-paddle.json
  packs/equipment/fossil-fragment-triceratops-frill.json
  packs/equipment/fossil-fragment-tyrannosaur-tooth.json
  packs/feats/tree-of-duality.json
  packs/rage-of-elements-bestiary/avalanche-legion.json
  packs/rage-of-elements-bestiary/melomach.json
  packs/rage-of-elements-bestiary/metal-wisp.json
  packs/rage-of-elements-bestiary/nightwood-guardian.json
  packs/rage-of-elements-bestiary/vault-builder.json
  packs/rage-of-elements-bestiary/veiled-current.json
  packs/rage-of-elements-bestiary/veldenar.json
  packs/rage-of-elements-bestiary/whipping-willow.json
  packs/rage-of-elements-bestiary/wood-wisp.json
  packs/rage-of-elements-bestiary/zuhra-shuyookh.json
  packs/vehicles/battery-tower.json
  packs/vehicles/bunta.json
  packs/vehicles/helepolis.json
  packs/vehicles/sand-racer.json
Labels: pr: data update

#9215 Add management of ABP Apex increase to attribute builder
  src/module/actor/character/attribute-builder.ts
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/styles/actor/character/_attribute-builder.scss
  static/lang/en.json
  static/templates/actors/character/attribute-builder.hbs
Labels: pr: enhancement

#9257 Fix Gate's Threshold's ChoiceSet flag to be camel case
  packs/classfeatures/gates-threshold.json
Labels: pr: data update

#9255 Add missing localized label for Elemental Evolution Damage Type
  static/lang/re-en.json
Labels: pr: data update

#9252 Fix display of actor sidebar when there are no parties
  src/module/apps/sidebar/actor-directory.ts
Labels: pr: bugfix

#9259 Remove level prefiltering from equipment browser links on PC sheet
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#9265 Updated Lesson of Element's Focus Spell spellType
  packs/spells/elemental-betrayal.json
Labels: pr: data update

#9223 Integrate action macros into check-context-acquisition pipeline
  src/module/actor/actions/single-check.ts
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/types.ts
  src/module/system/action-macros/acrobatics/tumble-through.ts
  src/module/system/action-macros/ancestry/automaton/arcane-slam.ts
  src/module/system/action-macros/athletics/disarm.ts
  src/module/system/action-macros/athletics/grapple.ts
  src/module/system/action-macros/athletics/shove.ts
  src/module/system/action-macros/athletics/trip.ts
  src/module/system/action-macros/athletics/whirling-throw.ts
  src/module/system/action-macros/basic/escape.ts
  src/module/system/action-macros/basic/sense-motive.ts
  src/module/system/action-macros/class/inventor/tamper.ts
  src/module/system/action-macros/deception/create-a-diversion.ts
  src/module/system/action-macros/deception/feint.ts
  src/module/system/action-macros/deception/impersonate.ts
  src/module/system/action-macros/deception/lie.ts
  src/module/system/action-macros/diplomacy/bon-mot.ts
  src/module/system/action-macros/diplomacy/make-an-impression.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/action-macros/intimidation/coerce.ts
  src/module/system/action-macros/intimidation/demoralize.ts
  src/module/system/action-macros/medicine/administer-first-aid.ts
  src/module/system/action-macros/nature/command-an-animal.ts
  src/module/system/action-macros/performance/perform.ts
  src/module/system/action-macros/stealth/conceal-an-object.ts
  src/module/system/action-macros/stealth/hide.ts
  src/module/system/action-macros/stealth/sneak.ts
  src/module/system/action-macros/thievery/palm-an-object.ts
  src/module/system/action-macros/thievery/steal.ts
  src/module/system/action-macros/types.ts
  src/module/system/check/check.ts
  src/module/system/degree-of-success.ts
  src/module/system/statistic/index.ts
Labels: pr: bugfix, pr: refactor

#9266 Update rule elements on several AV actors
  packs/abomination-vaults-bestiary/barcumbuk.json
  packs/abomination-vaults-bestiary/drill-field-barbazu.json
  packs/abomination-vaults-bestiary/hellforge-barbazu.json
  packs/abomination-vaults-bestiary/torture-chamber-barbazu.json
  packs/pathfinder-bestiary/erinys.json
Labels: pr: data update

#9253 Fix name of Witchwyrd Beacon
  packs/equipment/witchwyrd-beacon.json
Labels: pr: data update

#9269 Allow trick magic item counteract
  src/module/item/spell/document.ts
Labels: pr: bugfix, pr: refactor

#9271 Add Underwater weapon property rune
  packs/equipment/lionfish-spear-greater.json
  packs/equipment/lionfish-spear.json
  packs/other-effects/effect-aquatic-combat.json
  src/module/item/physical/runes.ts
  src/module/item/weapon/values.ts
  static/lang/en.json
Labels: pr: data update

#9280 Add automation for Shoulder to Shoulder and Skirmishing Dash
  packs/abomination-vaults-bestiary/caligni-defender.json
  packs/abomination-vaults-bestiary/quara-orshendiel.json
Labels: pr: data update

#9279 Add effect for Sharkskin Robe
  packs/equipment-effects/effect-sharkskin-robe.json
  packs/equipment/sharkskin-robe.json
Labels: pr: data update

#9277 Fix faerie queen's bower description
  packs/equipment/faerie-queens-bower.json
Labels: pr: data update

#9273 Use core icon for rage effect
  packs/bestiary-effects/effect-bullys-rage.json
  packs/bestiary-effects/effect-pulse-of-rage.json
  packs/classfeatures/rage.json
  packs/feat-effects/effect-rage.json
  packs/feat-effects/effect-share-rage.json
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
  packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
  packs/paizo-pregens/popcorn-level-4.json
  packs/paizo-pregens/popcorn.json
Labels: pr: data update

#9272 Fix some incorrect casing on NPC attacks and fix some missing attack traits
  packs/rage-of-elements-bestiary/coldmire-pond.json
  packs/rage-of-elements-bestiary/murajau.json
  packs/rage-of-elements-bestiary/olobigonde.json
  packs/rage-of-elements-bestiary/ore-louse.json
  packs/rage-of-elements-bestiary/tantriog.json
Labels: pr: data update

#9264 Add missing auras and aura slugs for RoE
  packs/equipment/atmospheric-staff.json
  packs/rage-of-elements-bestiary/abysium-horror.json
  packs/rage-of-elements-bestiary/anemos.json
  packs/rage-of-elements-bestiary/asp-of-grief.json
  packs/rage-of-elements-bestiary/austral-the-south-wind.json
  packs/rage-of-elements-bestiary/blustering-gale.json
  packs/rage-of-elements-bestiary/boiling-spring.json
  packs/rage-of-elements-bestiary/boreal-the-north-wind.json
  packs/rage-of-elements-bestiary/comozant-wyrd.json
  packs/rage-of-elements-bestiary/elemental-thicket.json
  packs/rage-of-elements-bestiary/eural-the-east-wind.json
  packs/rage-of-elements-bestiary/faydhaan-shuyookh.json
  packs/rage-of-elements-bestiary/ifrit-shuyookh.json
  packs/rage-of-elements-bestiary/jaathoom-shuyookh.json
  packs/rage-of-elements-bestiary/jann-shuyookh.json
  packs/rage-of-elements-bestiary/living-lodestone.json
  packs/rage-of-elements-bestiary/living-magma.json
  packs/rage-of-elements-bestiary/metal-wisp.json
  packs/rage-of-elements-bestiary/munsahir-gatecrasher.json
  packs/rage-of-elements-bestiary/munsahir-trooper.json
  packs/rage-of-elements-bestiary/oregorger.json
  packs/rage-of-elements-bestiary/picture-in-clouds.json
  packs/rage-of-elements-bestiary/saltborn-stalkers.json
  packs/rage-of-elements-bestiary/snapdrake.json
  packs/rage-of-elements-bestiary/wood-wisp.json
  packs/rage-of-elements-bestiary/zephyr-the-west-wind.json
  packs/rage-of-elements-bestiary/zuhra-shuyookh.json
Labels: pr: data update

#9263 Add aura effect for Beacon of the Rowan Guard
  packs/bestiary-effects/effect-beacon-of-the-rowan-guard.json
  packs/rage-of-elements-bestiary/twins-of-rowan.json
Labels: pr: data update

#9261 Fix elder seed description
  packs/equipment/elder-seed.json
Labels: pr: data update

#9278 Fix fiddle of the maestro description
  packs/equipment/fiddle-of-the-maestro.json
Labels: pr: data update

#9281 Remove numbers from party sheet sidebars
  src/styles/actor/party/_index.scss
Labels: pr: bugfix

#9276 Support extending statistic rule elements for spellcasting
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/document.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/item/spellcasting-entry/document.ts
  static/templates/actors/spellcasting-dialog.hbs
Labels: pr: enhancement

#9282 Catch some more old style damage rolls.
  packs/abomination-vaults-bestiary/deepwater-dhuthorex.json
  packs/abomination-vaults-bestiary/dread-dhuthorex.json
  packs/abomination-vaults-bestiary/viscous-black-pudding.json
  packs/age-of-ashes-bestiary/manifestation-of-dahak.json
  packs/age-of-ashes-bestiary/tarrasque-the-armageddon-engine.json
  packs/age-of-ashes-bestiary/xotani-the-firebleeder.json
  packs/book-of-the-dead-bestiary/last-guard.json
  packs/kingmaker-bestiary/exploding-bloom-pods.json
  packs/kingmaker-bestiary/fen-pudding.json
  packs/kingmaker-bestiary/rezatha.json
  packs/monsters-of-myth-bestiary/cuetzmonquali.json
  packs/monsters-of-myth-bestiary/kothogaz-dance-of-disharmony.json
  packs/pathfinder-bestiary-2/thulgant.json
  packs/pathfinder-bestiary-3/xiuh-couatl.json
  packs/pathfinder-bestiary/black-pudding.json
  packs/pathfinder-bestiary/crimson-worm.json
  packs/pathfinder-bestiary/giant-flytrap.json
  packs/pathfinder-bestiary/imp.json
  packs/pathfinder-bestiary/ochre-jelly.json
  packs/pathfinder-bestiary/pit-fiend.json
  packs/pathfinder-bestiary/pleroma.json
  packs/pathfinder-bestiary/remorhaz.json
  packs/pathfinder-bestiary/salamander.json
  packs/pathfinder-bestiary/snapping-flytrap.json
  packs/pfs-season-2-bestiary/storastas-last-stand-3-4.json
  packs/pfs-season-2-bestiary/ygracix.json
  packs/pfs-season-4-bestiary/stabilized-black-pudding.json
  packs/pfs-season-4-bestiary/stabilized-ochre-jelly.json
  packs/stolen-fate-bestiary/demonic-rabble.json
  packs/stolen-fate-bestiary/wrath-riot.json
  packs/strength-of-thousands-bestiary/aspect-of-hunger.json
  packs/strength-of-thousands-bestiary/avatar-of-walkena.json
  packs/strength-of-thousands-bestiary/crawling-slurry.json
  packs/strength-of-thousands-bestiary/gluttonworm.json
  packs/strength-of-thousands-bestiary/reborn-sun-warrior.json
  packs/strength-of-thousands-bestiary/sunburst-corpse.json
Labels: pr: data update

#9284 Fix filter on Through the Gate feat
  packs/feats/through-the-gate.json
Labels: pr: data update

#9285 Add missing Decompose action
  packs/actions/a-quick-glimpse-beyond.json
  packs/actions/avoid-dire-fate.json
  packs/actions/chaotic-destiny.json
  packs/actions/decompose.json
  packs/actions/fated-not-to-die.json
  packs/actions/harrow-the-fiend.json
  packs/actions/lucky-break.json
  packs/actions/recall-under-pressure.json
  packs/feats/moldersoul.json
Labels: pr: data update

#9287 Order methods in `ChatLogPF2e` to mirror core class
  src/module/apps/sidebar/chat-log.ts
Labels: pr: refactor

#9293 Fix Sawtooth Saber bulk
  packs/equipment/sawtooth-saber.json
  packs/paizo-pregens/eteleon.json
  packs/paizo-pregens/yacob.json
  packs/paizo-pregens/zeah.json
Labels: pr: data update

#9283 Automate several frequency alterations
  packs/feats/advanced-red-mantis-magic.json
  packs/feats/basic-red-mantis-magic.json
  packs/feats/continuous-assault.json
  packs/feats/crimson-shroud.json
  packs/feats/greater-despair.json
  packs/feats/ka-stone-ritual.json
  packs/feats/mantis-form.json
  packs/feats/rain-of-bolts.json
  packs/feats/red-mantis-assassin-dedication.json
  packs/feats/unbelievable-escape.json
  packs/feats/unbelievable-luck.json
Labels: pr: data update

#9294 Retrieve `this.actor` early in `CharacterSheetPF2e#getData`
  src/module/actor/character/sheet.ts
Labels: pr: refactor

#9289 Fix some NPC linked weapons
  packs/pfs-season-5-bestiary/experienced-robbers.json
  packs/pfs-season-5-bestiary/tough-robber.json
  packs/rage-of-elements-bestiary/faydhaan-shuyookh.json
  packs/rage-of-elements-bestiary/murajau.json
  packs/sky-kings-tomb-bestiary/krohan-possessed.json
Labels: pr: data update

#9296 Fix regression in managing in-memory state of attribute builder
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#9288 Emphasize blazing bolt in description
  packs/spells/blazing-bolt.json
Labels: pr: data update
