Repository foundryvtt/pf2e, pull requests merged in 2023-01, with the labels that each got.

#5385 Add a getter for a damage instance's "formal description"
  src/module/system/damage/roll.ts
Labels: pr: enhancement

#5388 Add silver/coldiron to certain spells
  packs/data/spells.db/dread-secret.json
  packs/data/spells.db/impaling-spike.json
  packs/data/spells.db/moonbeam.json
  packs/data/spells.db/moonburst.json
  packs/data/spells.db/moonlight-ray.json
Labels: pr: data update

#5387 Correct Localized Persistent and Splash Formulas
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#5389 Enable condition retrieval/recovery via persistent-damage-x string
  src/module/actor/base.ts
  src/module/item/condition/data.ts
  src/module/item/condition/document.ts
Labels: pr: enhancement

#5390 Add basic IWR
  src/global.d.ts
  src/module/actor/base.ts
  src/module/actor/data/iwr.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/damage-buttons.ts
  src/module/chat-message/listeners/damage-taken.ts
  src/module/chat-message/listeners/index.ts
  src/module/item/physical/runes.ts
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  static/lang/en.json
  static/templates/chat/damage/damage-taken.hbs
  static/templates/chat/damage/iwr-breakdown.hbs
Labels: pr: new feature

#5391 Add temporary mapping for persistent damage icons for each type
  src/module/item/condition/document.ts
  src/module/system/damage/values.ts
Labels: pr: enhancement

#5392 Release Notes 4.6.0
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#5393 Fix dragging persistent inline rolls from actor item summaries
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#5394 Fix sheet crashes caused by invalid spell formulas
  src/module/item/spell/document.ts
Labels: pr: bugfix

#5397 Include spell materials in message header
  src/module/item/spell/document.ts
  src/module/system/damage/roll.ts
Labels: pr: enhancement

#5395 Remove superfluous main category and fix negative spell modifiers
  src/module/item/spell/document.ts
  src/scripts/dice.ts
Labels: pr: bugfix

#5398 Fix adamantine golem resistance exception
  packs/data/pathfinder-bestiary.db/adamantine-golem.json
  src/scripts/config/iwr.ts
  static/lang/en.json
Labels: pr: data update

#5399 Update Hazard sheet sidebar template to new IWR format
  static/templates/actors/hazard/partials/sidebar.hbs
Labels: pr: bugfix

#5400 Fix `IWRRuleElement#validate` failing for weaknesses and resistances
  src/module/rules/rule-element/iwr/base.ts
Labels: pr: bugfix

#5411 Fix first level daze with negative modifier
  src/scripts/dice.ts
Labels: pr: bugfix

#5408 Update baomal's shell rake damage
  packs/data/pathfinder-bestiary.db/baomal.json
Labels: pr: data update

#5412 Shorten generated name of persistent damage conditions
  src/module/item/condition/document.ts
  static/lang/en.json
Labels: pr: bugfix

#5407 Change feats from DamageDice to AdjustStrike
  packs/data/feats.db/overwhelming-blow.json
  packs/data/feats.db/wolf-drag.json
  static/lang/re-en.json
Labels: pr: data update

#5413 Fix errant exclusion of negative modifiers
  src/module/system/damage/formula.ts
Labels: pr: bugfix

#5414 Exclude RE-added IWR data from editor form submission
  src/module/actor/sheet/popups/iwr-editor.ts
  src/module/rules/rule-element/iwr/resistance.ts
  src/styles/actor/_iwr-editor.scss
  static/templates/actors/iwr-editor.hbs
Labels: pr: bugfix

#5416 Fix AELike rule element overriding arrays in "add" mode when the target array already contains the new value
  src/module/rules/rule-element/ae-like.ts
Labels: pr: bugfix

#5417 Make disabled select elements in IWR editor more readable
  src/styles/actor/_iwr-editor.scss
Labels: ui/ux

#5418 Set `IWRData#source` property when replacing weakness/resistance value
  src/module/actor/data/iwr.ts
  src/module/rules/rule-element/iwr/resistance.ts
  src/module/rules/rule-element/iwr/weakness.ts
Labels: pr: bugfix

#5358 Fix automation of Time and Ashes Oracle curses
  packs/data/classfeatures.db/time.json
  packs/data/feat-effects.db/effect-ashes-curse.json
  packs/data/feat-effects.db/effect-time-curse.json
Labels: pr: data update

#5419 Release Notes 4.6.1
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#5420 Make a couple corrections in release notes 4.6.1
  CHANGELOG.md
Labels: pr: housekeeping

#5421 Apply IWR after manual multipliers and addends
  src/module/actor/base.ts
  src/module/actor/types.ts
  src/module/chat-message/listeners/damage-buttons.ts
  src/module/system/damage/iwr.ts
Labels: pr: bugfix

#5424 Have Foundry perform reloads on setting changes
  src/module/system/settings/automation.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/metagame.ts
Labels: pr: enhancement

#5429 Fix time symbol in Wild morph spell
  packs/data/spells.db/wild-morph.json
Labels: pr: data update

#5425 Add aura to gibbering mouther
  packs/data/pathfinder-bestiary.db/gibbering-mouther.json
Labels: pr: data update

#5427 Fix Veshumirix Breath Weapon recharge
  packs/data/age-of-ashes-bestiary.db/veshumirix.json
Labels: pr: data update

#5428 Fix time symbol in Heal companion spell
  packs/data/spells.db/heal-animal.json
Labels: pr: data update

#5434 Remove most JQuery from check roll dialog listeners
  src/module/system/check-modifiers-dialog.ts
Labels: pr: refactor

#5435 Quote adjustments in damage-taken template
  static/templates/chat/damage/damage-taken.hbs
Labels: pr: bugfix

#5443 Ensure all undead NPCs have negative healing
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#5440 Fix alignment ampoules to be martial weapons.
  packs/data/equipment.db/alignment-ampoule-greater.json
  packs/data/equipment.db/alignment-ampoule-lesser.json
  packs/data/equipment.db/alignment-ampoule-major.json
  packs/data/equipment.db/alignment-ampoule-moderate.json
  static/lang/en.json
Labels: pr: data update

#5423 Add support for condition immunity
  src/module/actor/base.ts
  src/module/actor/hazard/document.ts
  src/module/actor/helpers.ts
  src/module/actor/loot/document.ts
  src/module/actor/npc/document.ts
  src/module/actor/values.ts
  src/module/canvas/token/object.ts
  src/module/item/base.ts
  src/module/item/condition/document.ts
  src/module/system/damage/iwr.ts
  static/lang/en.json
Labels: pr: enhancement

#5361 Add preselection to Deep Orc item grant
  packs/data/heritages.db/deep-orc.json
  packs/data/heritages.db/hunter-automaton.json
Labels: pr: data update

#5396 Add custom damage types to IWR
  src/module/item/condition/document.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/helpers.ts
  src/module/system/settings/homebrew/menu.ts
Labels: pr: bugfix, pr: enhancement

#5444 Set mental immunity for any non-PC with mindless trait
  src/module/actor/creature/document.ts
  src/module/actor/creature/helpers.ts
Labels: pr: enhancement

#5437 Prevent ABP from applying Devastating Attacks to battle form attacks
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/strike.ts
Labels: pr: bugfix

#5449 Set base familiar traits earlier in data preparation
  src/module/actor/familiar/document.ts
Labels: pr: bugfix

#5436 Add support for critical-hits immunity
  roll-grammar.peggy
  src/module/actor/base.ts
  src/module/actor/data/iwr.ts
  src/module/chat-message/listeners/damage-buttons.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
Labels: pr: bugfix, pr: enhancement

#5448 Fix Splash Damage formula in Acid Splash
  packs/data/spells.db/acid-splash.json
Labels: pr: data update

#5446 Define Organsight damage as Precision Damage
  packs/data/spell-effects.db/spell-effect-organsight.json
Labels: pr: data update

#5447 Fix some pf2-icon styling
  packs/data/equipment.db/bottled-screams.json
  packs/data/equipment.db/carrion-cask.json
  packs/data/equipment.db/condensed-mana.json
  packs/data/equipment.db/defiled-costa-greater.json
  packs/data/equipment.db/defiled-costa.json
  packs/data/equipment.db/grave-token.json
  packs/data/equipment.db/unsullied-blood-greater.json
  packs/data/equipment.db/unsullied-blood-lesser.json
  packs/data/equipment.db/unsullied-blood-major.json
  packs/data/equipment.db/unsullied-blood-moderate.json
Labels: pr: data update

#5451 Use `DamageRoll` in FastHealing RE
  src/module/rules/rule-element/fast-healing.ts
Labels: pr: bugfix

#5450 Add `IntermediateDie` term class to handle non-numeric numbers/faces
  roll-grammar.peggy
  src/module/system/damage/helpers.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  src/scripts/hooks/load.ts
  types/foundry/client/roll-term/dice-term/die.d.ts
  types/foundry/client/roll-term/math-term.d.ts
  types/foundry/client/roll-term/numeric-term.d.ts
Labels: pr: bugfix, pr: enhancement

#5452 Fix chat message regression for inflicted persistent damage
  src/module/item/condition/document.ts
Labels: pr: bugfix

#5441 Fixes for ancestors oracle curse effects not applying correctly
  packs/data/feat-effects.db/effect-ancestor-curse.json
Labels: pr: data update

#5453 Fix validation check for PoolTerm class name
  src/module/system/damage/roll.ts
Labels: pr: bugfix

#5454 Fix regression in doubling/halving damage rolls
  src/module/item/melee/document.ts
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  types/foundry/client/roll-term/base.d.ts
  types/foundry/client/roll-term/numeric-term.d.ts
Labels: pr: bugfix

#5462 Strip out empty terms before creating damage expression strings
  src/module/system/damage/formula.ts
Labels: pr: bugfix

#5463 Fix damage halving/doubling
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
Labels: pr: bugfix

#5460 Apply ancestors oracle spell damage bonus to correct spells
  packs/data/feat-effects.db/effect-ancestor-curse.json
Labels: pr: data update

#5466 Fix application of manual addends to damage rolls
  src/module/system/damage/roll.ts
Labels: pr: bugfix

#5465 Token image rule element bracketed value
  src/module/rules/rule-element/token-image.ts
Labels: pr: bugfix

#5467 Apply stacking rules to spell-damage modifiers
  src/module/item/spell/document.ts
Labels: pr: bugfix

#5468 Add IWR support for ghost-touch runes, (not-)magical attacks, and spell schools
  src/module/actor/base.ts
  src/module/actor/data/iwr.ts
  src/module/actor/types.ts
  src/module/chat-message/listeners/damage-buttons.ts
  src/module/item/spell/document.ts
  src/module/item/weapon/document.ts
  src/module/system/damage/iwr.ts
Labels: pr: enhancement

#5469 Fix blocking of selected roll mode from chat log
  src/module/apps/sidebar/chat-log.ts
  types/foundry/client/documents/chat-message.d.ts
Labels: pr: bugfix

#5470 Create unevaluated numeric terms when parsing melee-item damage
  src/module/item/melee/document.ts
  types/foundry/client/roll-term/numeric-term.d.ts
Labels: pr: bugfix

#5456 Do not include splash in main damage instance flavor for spells
  src/module/item/spell/document.ts
Labels: pr: bugfix

#5471 Add Earth trait to elemental IWR processing
  src/module/actor/data/iwr.ts
Labels: pr: enhancement

#5464 Release Notes 4.6.2
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#5474 Fix healing button and damage application from message context menu
  src/module/actor/base.ts
  src/module/actor/types.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/damage-buttons.ts
Labels: pr: bugfix

#5476 Release Notes 4.6.3
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#5477 Add support for axe and arrow vulnerability
  src/module/actor/data/iwr.ts
Labels: pr: enhancement

#5480 Normalize spelling of "cold-iron" slug in NPC attack traits
  packs/data/blood-lords-bestiary.db/iron-taviah.json
  packs/data/blood-lords-bestiary.db/kepgeda-the-hag-nailed.json
  packs/data/blood-lords-bestiary.db/vampire-taviah.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-brartork.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-han.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-jun.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-krankkiss.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-mingyu.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-numoriz.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-paunnima.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/golarions-finest-rajna.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/gomwai.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/ki-adept-ahmoza-twins.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/ki-adept.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/shino-hakusa-level-14.json
  packs/data/fists-of-the-ruby-phoenix-bestiary.db/shino-hakusa-level-16.json
  packs/data/kingmaker-bestiary.db/ankou-assassin.json
  packs/data/kingmaker-bestiary.db/jaggedbriar-hag.json
  packs/data/kingmaker-bestiary.db/the-knurly-witch.json
  packs/data/pathfinder-bestiary-2.db/ankou.json
  packs/data/pathfinder-bestiary.db/annis-hag.json
  packs/data/pfs-season-1-bestiary.db/annis-hag-1-06.json
  packs/data/pfs-season-2-bestiary.db/ragewight-3-4.json
  packs/data/pfs-season-2-bestiary.db/ragewight-5-6.json
  packs/scripts/run-migration.ts
  src/module/migration/migrations/813-npc-cold-iron.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: data update

#5482 Fix prompt for Giant Instinct Barbarian
  packs/data/classfeatures.db/giant-instinct.json
  static/lang/re-en.json
Labels: pr: data update

#5478 Fix shark diver's electrify ability
  packs/data/vehicles.db/shark-diver.json
Labels: pr: data update

#5488 Fix context menu applying triple damage when double damage is selected
  src/module/apps/sidebar/chat-log.ts
Labels: pr: bugfix

#5489 Fix handling of splash damage in sumExpression function
  src/module/system/damage/formula.ts
Labels: pr: bugfix

#5491 Ensure full JSONification in system `RollTerm`s
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
Labels: pr: refactor

#5494 Fix battle form spell effects to use "cold-iron" rather than "coldiron"
  packs/data/spell-effects.db/spell-effect-demon-form-babau.json
  packs/data/spell-effects.db/spell-effect-demon-form-hezrou.json
  packs/data/spell-effects.db/spell-effect-demon-form-nabasu.json
  packs/data/spell-effects.db/spell-effect-demon-form-vrock.json
  packs/data/spell-effects.db/spell-effect-fey-form-dryad.json
  packs/data/spell-effects.db/spell-effect-fey-form-elananx.json
  packs/data/spell-effects.db/spell-effect-fey-form-naiad.json
  packs/data/spell-effects.db/spell-effect-fey-form-redcap.json
  packs/data/spell-effects.db/spell-effect-fey-form-unicorn.json
Labels: pr: data update

#5492 Fix Grab on Minchgorm
  packs/data/agents-of-edgewatch-bestiary.db/lusca.json
  packs/data/agents-of-edgewatch-bestiary.db/minchgorm.json
Labels: pr: data update

#5487 Correct spelling of Woolly Rhinoceros
  packs/data/monsters-of-myth-bestiary.db/ainamuuren.json
  packs/data/pathfinder-bestiary-2.db/woolly-rhinoceros.json
Labels: pr: data update

#5490 Adds Spell Effect: Prismatic Armor
  packs/data/spell-effects.db/spell-effect-prismatic-armor.json
  packs/data/spells.db/prismatic-armor.json
Labels: pr: data update

#5496 Add Gouging Claw damage variants
  packs/data/spells.db/gouging-claw.json
Labels: pr: data update

#5481 Unify handling of material damage effects among PCs and NPCS
  src/module/actor/data/iwr.ts
  src/module/item/spell/data.ts
  src/module/item/weapon/types.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/synthetics.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/types.ts
  src/module/system/damage/values.ts
  src/module/system/damage/weapon.ts
  src/module/system/tag-selector/index.ts
  src/scripts/config/index.ts
  static/templates/items/spell-details.hbs
Labels: pr: enhancement

#5500 Update Actor construction with module art scale properties V10 standard
  src/module/actor/base.ts
Labels: pr: foundry v10

#5499 Update migration 813 to normalize remaining "cold-iron" slugs
  packs/data/bestiary-effects.db/effect-adaptive-strike.json
  packs/data/crown-of-the-kobold-king-bestiary.db/king-merlokrep.json
  packs/data/equipment.db/blackaxe.json
  packs/data/equipment.db/blade-of-the-black-sovereign.json
  packs/data/equipment.db/briar.json
  packs/data/equipment.db/cold-iron-buckler-high-grade.json
  packs/data/equipment.db/cold-iron-buckler-low-grade.json
  packs/data/equipment.db/cold-iron-buckler-standard-grade.json
  packs/data/equipment.db/cold-iron-shield-high-grade.json
  packs/data/equipment.db/cold-iron-shield-low-grade.json
  packs/data/equipment.db/cold-iron-shield-standard-grade.json
  packs/data/equipment.db/eclipse.json
  packs/data/equipment.db/final-rest.json
  packs/data/equipment.db/holy-avenger.json
  packs/data/equipment.db/man-feller.json
  packs/data/equipment.db/mattock-of-the-titans.json
  packs/data/equipment.db/nethysian-bulwark.json
  packs/data/equipment.db/phoenix-fighting-fan.json
  packs/data/equipment.db/ridill.json
  packs/data/equipment.db/rod-of-razors.json
  packs/data/equipment.db/sky-hammer.json
  packs/data/equipment.db/spiral-athame.json
  packs/data/equipment.db/torags-silver-anvil.json
  packs/data/feats.db/metal-veined-strikes.json
  packs/data/kingmaker-bestiary.db/castruccio-irovetti.json
  packs/data/pathfinder-bestiary.db/treerazer.json
  packs/scripts/run-migration.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/module/migration/migrations/813-normalize-cold-iron.ts
  src/module/migration/migrations/813-npc-cold-iron.ts
  src/module/migration/migrations/index.ts
Labels: pr: data migration

#5501 Change `looksLikeDamageFormula` to parse test
  src/module/system/damage/helpers.ts
Labels: pr: bugfix

#5502 Don't show "untyped" in damage formulas
  src/module/system/damage/roll.ts
Labels: ui/ux

#5497 Fix case of Telekinetic Projectile variant names
  packs/data/spells.db/telekinetic-projectile.json
Labels: pr: data update

#5505 Don't label every damage part of NPC attacks as "Base"
  src/module/system/damage/weapon.ts
Labels: ui/ux

#5506 Correct spelling of "Rejuvenation"
  packs/data/age-of-ashes-bestiary.db/candlarons-echo.json
  packs/data/malevolence-bestiary.db/ioseff-xarwin.json
Labels: pr: data update

#5510 Update claws.json to make it translation friendly
  packs/data/ancestryfeatures.db/claws.json
Labels: pr: data update

#5504 Remove some unnecessary attackEffects. Add some missing damageRolls.
  packs/data/quest-for-the-frozen-flame-bestiary.db/hegremon.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/metuak.json
  packs/data/strength-of-thousands-bestiary.db/bharlen-sajor.json
  packs/data/strength-of-thousands-bestiary.db/ixamè.json
  packs/data/strength-of-thousands-bestiary.db/slana.json
Labels: pr: data update

#5498 Fix some sources
  packs/data/abomination-vaults-bestiary.db/specter-av-c2.json
  packs/data/backgrounds.db/borderlands-pioneer.json
  packs/data/backgrounds.db/brevic-noble.json
  packs/data/backgrounds.db/brevic-outcast.json
  packs/data/backgrounds.db/dreams-of-vengeance.json
  packs/data/backgrounds.db/issian-patriot.json
  packs/data/backgrounds.db/local-brigand.json
  packs/data/backgrounds.db/lost-loved-one.json
  packs/data/backgrounds.db/rostlander.json
  packs/data/backgrounds.db/sense-of-belonging.json
  packs/data/backgrounds.db/sword-scion.json
  packs/data/backgrounds.db/total-power.json
  packs/data/backgrounds.db/wanderlust.json
  packs/data/backgrounds.db/wish-for-riches.json
  packs/data/campaign-effects.db/effect-burned-mouth-and-throat-linguistic.json
  packs/data/campaign-effects.db/effect-burned-mouth-and-throat-no-singing-or-yelling.json
  packs/data/campaign-effects.db/effect-burned-tongue-linguistic.json
  packs/data/campaign-effects.db/effect-burned-tongue-no-singing-or-yelling.json
  packs/data/campaign-effects.db/effect-extreme-stomach-cramps.json
  packs/data/campaign-effects.db/effect-heightened-awareness.json
  packs/data/campaign-effects.db/effect-immediate-and-intense-headache.json
  packs/data/campaign-effects.db/effect-improved-reflexes.json
  packs/data/campaign-effects.db/effect-keen-insight.json
  packs/data/campaign-effects.db/mixed-drink-dancing-lights.json
  packs/data/campaign-effects.db/mixed-drink-guidance.json
  packs/data/campaign-effects.db/mixed-drink-luck.json
  packs/data/campaign-effects.db/mixed-drink-prestidigitation.json
  packs/data/equipment-effects.db/effect-disarm-success.json
  packs/data/equipment.db/belt-of-good-health.json
  packs/data/equipment.db/green-wyrmling-breath-potion.json
  packs/data/equipment.db/hunters-bow.json
  packs/data/equipment.db/poisonous-dagger.json
  packs/data/equipment.db/pyrite-rat.json
  packs/data/equipment.db/smoking-sword.json
  packs/data/equipment.db/storm-hammer.json
  packs/data/familiar-abilities.db/augury.json
  packs/data/familiar-abilities.db/soul-sight.json
  packs/data/familiar-abilities.db/spirit-touch.json
  packs/data/outlaws-of-alkenstar-bestiary.db/lonely-machine-spirit.json
  packs/data/outlaws-of-alkenstar-bestiary.db/lyzerium-bottles.json
  packs/data/outlaws-of-alkenstar-bestiary.db/precarious-thunderstone-trap.json
  packs/data/outlaws-of-alkenstar-bestiary.db/purple-dye-trap.json
  packs/data/outlaws-of-alkenstar-bestiary.db/repeater-crossbow-trap.json
  packs/data/outlaws-of-alkenstar-bestiary.db/stink-sap-trap.json
  packs/data/outlaws-of-alkenstar-bestiary.db/subduing-gas-chamber.json
  packs/data/outlaws-of-alkenstar-bestiary.db/volatile-reagents.json
  packs/data/outlaws-of-alkenstar-bestiary.db/wooden-bullets-trap.json
  packs/data/pfs-season-1-bestiary.db/pile-of-fireworks-3-4.json
  packs/data/pfs-season-1-bestiary.db/pile-of-fireworks-5-6.json
Labels: pr: data update

#5514 Fix inclusion and doubling of critical damage
  src/module/rules/rule-element/damage-dice.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/types.ts
  src/module/system/damage/values.ts
Labels: pr: bugfix

#5521 Cap precision-damage resistance at the initial damage total
  src/module/system/damage/iwr.ts
Labels: pr: bugfix

#5507 Add support for alternate ancestry boosts
  src/module/actor/character/data/types.ts
  src/module/actor/sheet/popups/ability-builder.ts
  src/module/item/ancestry/data.ts
  src/module/item/ancestry/document.ts
  src/styles/actor/character/_ability-builder.scss
  static/templates/actors/character/ability-builder.hbs
Labels: pr: new feature

#5522 Hide damage-instance breakdown from private damage rolls
  src/module/chat-message/document.ts
  src/module/system/damage/roll.ts
Labels: pr: bugfix

#5519 Add IWR support for area damage
  src/module/actor/data/iwr.ts
  src/module/item/spell/document.ts
Labels: pr: enhancement

#5524 Fix overflow in effect panel from longer badges
  src/styles/system/_effects-panel.scss
Labels: pr: bugfix, ui/ux

#5533 Change module art helpers into class
  src/global.d.ts
  src/module/system/module-art.ts
  src/scripts/hooks/ready.ts
  src/scripts/register-module-art.ts
  src/scripts/set-game-pf2e.ts
Labels: pr: refactor

#5538 Fix display of empty middle ancestry boosts in ability builder
  packs/data/ancestries.db/human.json
  src/module/actor/sheet/popups/ability-builder.ts
Labels: pr: bugfix

#5529 Only increase weapon dice number from striking/ABP if originally 1
  src/module/item/weapon/document.ts
Labels: pr: bugfix

#5540 Fix migration 698 breaking on familiars
  src/module/actor/familiar/data.ts
  src/module/migration/migrations/698-remove-derived-actor-traits.ts
Labels: pr: bugfix

#5541 Update NPM dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#5532 Ensure minimum damage totals of 1
  src/module/system/damage/roll.ts
  src/scripts/handlebars.ts
  src/styles/ui/sidebar/chat/_damage.scss
  static/lang/en.json
  static/templates/dice/damage-roll.hbs
Labels: pr: bugfix, pr: enhancement

#5530 Add minimum- and maximum-value getters to damage roll and term classes
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  types/foundry/client/roll-term/dice-term/die.d.ts
Labels: pr: enhancement

#5542 Limit unknown usage warning to dev build mode
  src/module/item/physical/usage.ts
Labels: pr: enhancement

#5545 Fix bracket row deletion in flat modifier always deleting the first row
  static/templates/items/rules/flat-modifier.hbs
Labels: pr: bugfix

#5546 Cache result of character/creature skills
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
Labels: pr: refactor

#5548 Add new keys for Shark
  static/icons/equipment/held-items/key-copper.webp
  static/icons/equipment/held-items/key-gold.webp
  static/icons/equipment/held-items/key-jeweled-gold-purple.webp
  static/icons/equipment/held-items/key-ring-gold.webp
  static/icons/equipment/held-items/key-short-gold.webp
  static/icons/equipment/held-items/key-steel-grey.webp
  static/icons/equipment/held-items/key-steel.webp
Labels: pr: data update

#5547 Add ability to include persistent damage directly in weapon data
  packs/scripts/extract.ts
  src/module/actor/creature/document.ts
  src/module/actor/modifiers.ts
  src/module/item/melee/document.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/weapon.ts
  src/styles/item/_index.scss
  src/styles/item/_weapon-sheet.scss
  static/lang/en.json
  static/template.json
  static/templates/items/weapon-details.hbs
Labels: pr: enhancement

#5549 Delete only top-level class features when class is changed
  src/module/item/class/document.ts
Labels: pr: bugfix

#5523 Create persistent damage conditions when applying damage
  src/module/actor/base.ts
  src/module/item/condition/data.ts
  src/module/system/damage/iwr.ts
  src/styles/ui/sidebar/chat/_damage.scss
  static/templates/chat/damage/damage-taken.hbs
Labels: pr: enhancement

#5536 Correct some sources in AP 185 and 186
  packs/data/adventure-specific-actions.db/mental-ward.json
  packs/data/adventure-specific-actions.db/soul-ward.json
  packs/data/bestiary-effects.db/effect-energy-ward.json
  packs/data/bestiary-effects.db/effect-gird-in-prayer.json
  packs/data/bestiary-effects.db/effect-spotlight.json
  packs/data/campaign-effects.db/gebs-blessing.json
  packs/data/equipment-effects.db/effect-soulspark-candle.json
  packs/data/equipment.db/aeon-stone-amber-sphere.json
  packs/data/equipment.db/aeon-stone-black-disc.json
  packs/data/equipment.db/aeon-stone-mottled-ellipsoid.json
  packs/data/equipment.db/aeon-stone-rainbow-prism.json
  packs/data/equipment.db/curtain-call-cloak.json
  packs/data/equipment.db/passage-pane.json
  packs/data/equipment.db/phantom-shroud.json
  packs/data/equipment.db/redsand-hourglass.json
  packs/data/equipment.db/shadows-heart.json
  packs/data/equipment.db/soulspark-candle.json
  packs/data/equipment.db/spectral-opera-glasses.json
  packs/data/equipment.db/spiral-athame.json
  packs/data/equipment.db/splendid-floodlight.json
  packs/data/equipment.db/umbraex-eye.json
  packs/data/spells.db/curse-of-the-spirit-orchestra.json
  packs/data/spells.db/infectious-comedy.json
  packs/data/spells.db/split-shadow.json
Labels: pr: data update

#5509 Fix deadly variant of Clawsong spell effect
  packs/data/spell-effects.db/spell-effect-clawsong-deadly-d8.json
Labels: pr: data update

#5535 Add missing GrantItem to Psychic Dedication
  packs/data/feats.db/psychic-dedication.json
Labels: pr: data update

#5518 Fix name of Hamstringing Strike and add effect
  packs/data/feat-effects.db/effect-hamstringing-strike.json
  packs/data/feats.db/hamstring-strike.json
  packs/data/feats.db/hamstringing-strike.json
  static/lang/re-en.json
Labels: pr: data update

#5551 Add an effect for Nyktera's Righteous Fury
  packs/data/bestiary-effects.db/effect-wrath-of-spurned-hospitality.json
  packs/data/pathfinder-bestiary-3.db/nyktera.json
Labels: pr: data entry, pr: data update, source: rulebooks

#5555 Prune empty WeaponSource#system#damage#value and #persistent
  packs/scripts/extract.ts
Labels: pr: housekeeping

#5554 Work around physical item levels being set as strings
  src/module/item/physical/sheet.ts
  static/templates/items/item-sheet.hbs
Labels: pr: bugfix

#5527 Remove non-RE weapons master entry from Shraen Graveknight NPC
  packs/data/extinction-curse-bestiary.db/shraen-graveknight.json
Labels: source: adventure path, pr: data update

#5517 Fix Galudu's inventory
  packs/data/abomination-vaults-bestiary.db/galudu.json
Labels: pr: data update

#5515 Fix Lomok's Oath of the Burning Mammoths
  packs/data/quest-for-the-frozen-flame-bestiary.db/bone-warrior.json
  packs/data/quest-for-the-frozen-flame-bestiary.db/lomok.json
Labels: pr: data update

#5512 Fix Clawsong versatile spell effect
  packs/data/spell-effects.db/spell-effect-clawsong-versatile-piercing.json
Labels: pr: data update

#5483 Fix bomb notes
  static/lang/re-en.json
Labels: pr: data update

#5516 Revise CRB Errata 4 Changes
  packs/data/classfeatures.db/bomber.json
  packs/data/classfeatures.db/chirurgeon.json
  packs/data/classfeatures.db/field-discovery-chirurgeon.json
  packs/data/classfeatures.db/first-doctrine-warpriest.json
  packs/data/classfeatures.db/leaf-order.json
  packs/data/classfeatures.db/mutagenist.json
  packs/data/classfeatures.db/warpriest.json
  packs/data/equipment.db/alchemists-tools.json
  packs/data/equipment.db/artisans-tools-sterling.json
  packs/data/equipment.db/artisans-tools.json
  packs/data/equipment.db/basic-crafters-book.json
  packs/data/equipment.db/elven-chain-high-grade.json
  packs/data/equipment.db/elven-chain-standard-grade.json
  packs/data/equipment.db/healers-tools-expanded.json
  packs/data/equipment.db/healers-tools.json
  packs/data/equipment.db/spellguard-shield.json
  packs/data/equipment.db/thieves-tools-infiltrator.json
  packs/data/equipment.db/thieves-tools.json
  packs/data/equipment.db/verdant-staff-greater.json
  packs/data/equipment.db/verdant-staff.json
  packs/data/feats.db/green-empathy.json
  packs/data/feats.db/leshy-familiar.json
  packs/data/feats.db/magical-crafting.json
  packs/data/feats.db/minor-magic.json
  packs/data/feats.db/woodland-stride.json
  packs/data/spells.db/alter-reality.json
  packs/data/spells.db/avatar.json
  packs/data/spells.db/commune-with-nature.json
  packs/data/spells.db/entangle.json
  packs/data/spells.db/miracle.json
  packs/data/spells.db/natures-enmity.json
  packs/data/spells.db/primal-phenomenon.json
  packs/data/spells.db/speak-with-plants.json
  packs/data/spells.db/wall-of-stone.json
  packs/data/spells.db/wish.json
  packs/data/spells.db/word-of-freedom.json
Labels: pr: data update

#5531 Fix some SoT inventories
  packs/data/strength-of-thousands-bestiary.db/gambulami.json
  packs/data/strength-of-thousands-bestiary.db/grouloop.json
  packs/data/strength-of-thousands-bestiary.db/terwa-prodigy.json
  packs/data/strength-of-thousands-bestiary.db/worknesh.json
Labels: pr: data update

#5557 Update Twitchy feat to use latest RE technologies
  packs/data/feats.db/twitchy.json
Labels: pr: data update

#5544 Fix more sources
  packs/data/april-fools-bestiary.db/blarghest.json
  packs/data/april-fools-bestiary.db/cacaodaemon.json
  packs/data/april-fools-bestiary.db/demom.json
  packs/data/april-fools-bestiary.db/floolf.json
  packs/data/april-fools-bestiary.db/nonsequitaur.json
  packs/data/april-fools-bestiary.db/nosferotter.json
  packs/data/april-fools-bestiary.db/psstpsstmitl.json
  packs/data/april-fools-bestiary.db/squirrelwind.json
  packs/data/april-fools-bestiary.db/weredigo.json
  packs/data/equipment.db/dwarven-daisy-lesser.json
  packs/data/equipment.db/dwarven-daisy-moderate.json
  packs/data/equipment.db/wasul-reed-mask.json
  packs/data/kingmaker-bestiary.db/cleansed-cultist.json
  packs/data/outlaws-of-alkenstar-bestiary.db/slick.json
  packs/data/pathfinder-bestiary.db/balisse.json
  packs/data/pfs-season-1-bestiary.db/pile-of-fireworks-3-4.json
  packs/data/pfs-season-1-bestiary.db/pile-of-fireworks-5-6.json
  packs/data/pfs-season-2-bestiary.db/scorched-earth-mephit.json
  packs/data/pfs-season-3-bestiary.db/alchemy-gorged-giant-leech.json
  packs/data/pfs-season-3-bestiary.db/cole-farsen-advisor.json
  packs/data/pfs-season-3-bestiary.db/cole-farsen-gang-leader.json
  packs/data/pfs-season-3-bestiary.db/hellbound-jailer-5-6.json
  packs/data/pfs-season-3-bestiary.db/living-landslide-pfs-3-11.json
  packs/data/pfs-season-3-bestiary.db/monastic-bodyguard-3-4.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-bodyguard.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-burglar.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-fence.json
  packs/data/pfs-season-3-bestiary.db/ninth-army-ruffian.json
  packs/data/pfs-season-3-bestiary.db/weak-hell-hound-pfs-3-07.json
  packs/data/pfs-season-4-bestiary.db/animated-leather-armor.json
  packs/data/pfs-season-4-bestiary.db/charlatan-pfs-4-05.json
  packs/data/pfs-season-4-bestiary.db/dero-stalker-pfs-4-05.json
  packs/data/pfs-season-4-bestiary.db/overtaxed-vrisk.json
  packs/data/pfs-season-4-bestiary.db/skulk-raider.json
  packs/data/pfs-season-4-bestiary.db/vrisk.json
Labels: pr: data update

#5550 Move damage colors to global SCSS variables
  src/styles/_colors.scss
  src/styles/ui/sidebar/chat/_damage.scss
Labels: pr: refactor

#5562 Add persistent damage to Acid Flask
  packs/data/equipment.db/acid-flask-greater.json
  packs/data/equipment.db/acid-flask-lesser.json
  packs/data/equipment.db/acid-flask-major.json
  packs/data/equipment.db/acid-flask-moderate.json
Labels: pr: data update

#5560 Update Deflecting Branch
  packs/data/equipment.db/deflecting-branch.json
Labels: pr: data update

#5559 Fixed the Daemonic Infector "Cleric Domain Spells" spellcasting entry from innate to focus
  packs/data/agents-of-edgewatch-bestiary.db/daemonic-infector.json
Labels: pr: data update

#5558 Fixed Anadi Elder and Anadi Sage spellcasting entry type from "Innate" to "innate"
  packs/data/mwangi-expanse-bestiary.db/anadi-elder.json
  packs/data/mwangi-expanse-bestiary.db/anadi-sage.json
Labels: pr: data update

#5564 Touch up PFS equipment
  packs/data/agents-of-edgewatch-bestiary.db/sleepless-sun-veteran.json
  packs/data/pfs-season-1-bestiary.db/charlatan.json
  packs/data/pfs-season-1-bestiary.db/elite-duergar-taskmaster.json
  packs/data/pfs-season-1-bestiary.db/ruffian.json
  packs/data/pfs-season-2-bestiary.db/russian-soldier-5-6.json
  packs/data/pfs-season-2-bestiary.db/russian-soldier-7-8.json
  packs/data/pfs-season-2-bestiary.db/semyon-5-6.json
  packs/data/pfs-season-2-bestiary.db/semyon-7-8.json
  packs/data/pfs-season-3-bestiary.db/aspis-agent.json
  packs/data/pfs-season-3-bestiary.db/aspis-bulwark.json
  packs/data/pfs-season-3-bestiary.db/aspis-defender.json
  packs/data/pfs-season-3-bestiary.db/aspis-enforcer.json
  packs/data/pfs-season-3-bestiary.db/aspis-oppressor.json
  packs/data/pfs-season-3-bestiary.db/aspis-recruit.json
  packs/data/pfs-season-3-bestiary.db/aspis-striker.json
  packs/data/pfs-season-3-bestiary.db/aspis-usurper.json
  packs/data/pfs-season-3-bestiary.db/aspis-warden.json
Labels: pr: data update

#5565 Add variants for shadow Blast save types
  packs/data/spells.db/shadow-blast.json
Labels: pr: data update

#5566 Remove unneeded AV variant actors
  packs/data/abomination-vaults-bestiary.db/beluthus.json
  packs/data/abomination-vaults-bestiary.db/child-of-belcorra.json
  packs/data/abomination-vaults-bestiary.db/cynemi.json
  packs/data/abomination-vaults-bestiary.db/falxi-orshendiel.json
  packs/data/abomination-vaults-bestiary.db/murmur.json
Labels: pr: data update

#5567 Skip altering roll when applying healing to actor
  src/module/chat-message/helpers.ts
Labels: pr: bugfix

#5563 Add splash damage as separate roll in chat messages
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/document.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/damage-buttons.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  src/styles/ui/sidebar/chat/_damage.scss
  static/templates/dice/damage-roll.hbs
  types/foundry/client/roll.d.ts
Labels: pr: enhancement, pr: refactor

#5569 Release Notes 3.6.4
  CHANGELOG.md
  package-lock.json
  package.json
  system.json
Labels: pr: housekeeping

#5570 Add persistent damage to alchemical bombs
  packs/data/equipment.db/blight-bomb-greater.json
  packs/data/equipment.db/blight-bomb-lesser.json
  packs/data/equipment.db/blight-bomb-major.json
  packs/data/equipment.db/blight-bomb-moderate.json
  packs/data/equipment.db/goo-grenade-greater.json
  packs/data/equipment.db/goo-grenade-lesser.json
  packs/data/equipment.db/goo-grenade-major.json
  packs/data/equipment.db/goo-grenade-moderate.json
  packs/data/equipment.db/junk-bomb-greater.json
  packs/data/equipment.db/junk-bomb-lesser.json
  packs/data/equipment.db/junk-bomb-major.json
  packs/data/equipment.db/junk-bomb-moderate.json
  packs/data/equipment.db/pernicious-spore-bomb-greater.json
  packs/data/equipment.db/pernicious-spore-bomb-lesser.json
  packs/data/equipment.db/pernicious-spore-bomb-major.json
  packs/data/equipment.db/pernicious-spore-bomb-moderate.json
  packs/data/equipment.db/redpitch-bomb-greater.json
  packs/data/equipment.db/redpitch-bomb-lesser.json
  packs/data/equipment.db/redpitch-bomb-major.json
  packs/data/equipment.db/redpitch-bomb-moderate.json
  packs/data/equipment.db/tallow-bomb-greater.json
  packs/data/equipment.db/tallow-bomb-lesser.json
  packs/data/equipment.db/tallow-bomb-major.json
  packs/data/equipment.db/tallow-bomb-moderate.json
  packs/data/equipment.db/twigjack-sack-greater.json
  packs/data/equipment.db/twigjack-sack-lesser.json
  packs/data/equipment.db/twigjack-sack-major.json
  packs/data/equipment.db/twigjack-sack-moderate.json
Labels: pr: data update

#5571 Fix `ActorPF2e#isAffectedBy` for positive damage
  src/module/actor/base.ts
Labels: pr: bugfix

#5572 Restore the variant Devourer and Bog Mummy from AV
  packs/data/abomination-vaults-bestiary.db/beluthus.json
  packs/data/abomination-vaults-bestiary.db/child-of-belcorra.json
Labels: pr: data update

#5574 Fix addend adjustments of damage rolls with multiple instances
  src/module/system/damage/roll.ts
Labels: pr: bugfix

#5573 Add effect for Goo Grenade
  packs/data/equipment-effects.db/effect-goo-grenade.json
  packs/data/equipment.db/goo-grenade-greater.json
  packs/data/equipment.db/goo-grenade-lesser.json
  packs/data/equipment.db/goo-grenade-major.json
  packs/data/equipment.db/goo-grenade-moderate.json
  static/lang/re-en.json
Labels: pr: data update

#5576 Fix Brevic Noble Garess to grant crafting rather than arcana
  packs/data/backgrounds.db/brevic-noble.json
Labels: pr: data update

#5582 Fix Bottled Sunlight to have a range of 20 feet
  packs/data/equipment.db/bottled-sunlight-greater.json
  packs/data/equipment.db/bottled-sunlight-lesser.json
  packs/data/equipment.db/bottled-sunlight-major.json
  packs/data/equipment.db/bottled-sunlight-moderate.json
Labels: pr: data update

#5579 Fix level value of Soulspark candle
  packs/data/equipment.db/soulspark-candle.json
Labels: pr: data update

#5578 Add missing range localization keys
  static/lang/en.json
Labels: pr: data update

#5583 Exclude weaknesses and resistances resolving to <= 0
  src/module/rules/rule-element/iwr/resistance.ts
  src/module/rules/rule-element/iwr/weakness.ts
Labels: pr: bugfix

#5587 Fix link in Spell Effect: Prismatic Armor
  packs/data/spell-effects.db/spell-effect-prismatic-armor.json
Labels: pr: data update

#5577 Add support for CRB 4.0 voluntary flaws
  src/module/actor/sheet/popups/ability-builder.ts
  src/module/item/ancestry/data.ts
  src/module/item/ancestry/document.ts
  src/module/migration/migrations/767-convert-voluntary-flaws.ts
  src/styles/actor/character/_ability-builder.scss
  static/lang/en.json
  static/templates/actors/character/ability-builder.hbs
Labels: pr: new feature

#5590 Add some missing emphasis to spell links
  packs/data/criticaldeck.db/critical-fumble-deck-1.json
  packs/data/criticaldeck.db/critical-fumble-deck-15.json
  packs/data/criticaldeck.db/critical-fumble-deck-34.json
  packs/data/criticaldeck.db/critical-fumble-deck-8.json
  packs/data/criticaldeck.db/critical-hit-deck-12.json
  packs/data/criticaldeck.db/critical-hit-deck-25.json
  packs/data/criticaldeck.db/critical-hit-deck-38.json
  packs/data/journals.db/gm-screen.json
  packs/data/rollable-tables.db/deck-of-many-things.json
Labels: pr: data update

#5591 Audit Bestial Mutagen effect REs
  packs/data/equipment-effects.db/effect-bestial-mutagen-greater.json
  packs/data/equipment-effects.db/effect-bestial-mutagen-lesser.json
  packs/data/equipment-effects.db/effect-bestial-mutagen-major.json
  packs/data/equipment-effects.db/effect-bestial-mutagen-moderate.json
Labels: pr: data update
