Repository foundryvtt/pf2e, pull requests merged in 2023-07, with the labels that each got.

#8501 Fix issue causing compendium browser to get stuck with no pointer events
  src/module/apps/compendium-browser/index.ts
Labels: pr: bugfix

#8513 Add SVG icon for Kashrishi ancestry
  packs/ancestries/kashrishi.json
  static/icons/default-icons/alternatives/ancestries/kashrishi.svg
Labels: pr: data update

#8509 Add remaining weapon property runes from TV and LO:KoL
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/item/physical/runes.ts
  src/module/item/weapon/values.ts
  src/module/system/damage/weapon.ts
  static/lang/en.json
Labels: pr: data update, pr: enhancement

#8510 Add NPCs from PFS 4-15
  packs/pfs-season-3-bestiary/lesser-animate-dream.json
  packs/pfs-season-4-bestiary/combustive-zombie.json
  packs/pfs-season-4-bestiary/elite-clacking-skull-swarm.json
  packs/pfs-season-4-bestiary/elite-combustive-zombie.json
  packs/pfs-season-4-bestiary/elite-smokesight-deadeye-wight.json
  packs/pfs-season-4-bestiary/elite-smokesight-hunter-wight.json
  packs/pfs-season-4-bestiary/elite-smokesight-prowler-wight.json
  packs/pfs-season-4-bestiary/elite-smokesight-stalker-wight.json
  packs/pfs-season-4-bestiary/elite-smokesight-wight-captain.json
  packs/pfs-season-4-bestiary/elite-smokesight-wight-commander.json
  packs/pfs-season-4-bestiary/elite-sulfur-zombie.json
  packs/pfs-season-4-bestiary/smokesight-deadeye-wight.json
  packs/pfs-season-4-bestiary/smokesight-hunter-wight.json
  packs/pfs-season-4-bestiary/smokesight-prowler-wight.json
  packs/pfs-season-4-bestiary/smokesight-stalker-wight.json
  packs/pfs-season-4-bestiary/smokesight-wight-captain.json
  packs/pfs-season-4-bestiary/smokesight-wight-commander.json
  packs/pfs-season-4-bestiary/weak-clacking-skull-swarm.json
Labels: pr: data entry, pr: data update, source: pathfinder society

#8514 Fix some inline damage rolls.
  packs/equipment/swarmeaters-clasp.json
  packs/equipment/verdant-branch.json
  packs/gatewalkers-bestiary/glimmervine.json
  packs/gatewalkers-bestiary/kvernknurr.json
  packs/journals/hero-point-deck.json
  packs/pfs-season-3-bestiary/waking-nightmare.json
  packs/pfs-season-3-bestiary/waking-terror.json
  packs/pfs-season-4-bestiary/deimostride-7-8.json
  packs/stolen-fate-bestiary/nornhound.json
  packs/stolen-fate-bestiary/obcisidaemon.json
  packs/stolen-fate-bestiary/phasmadaemon.json
Labels: pr: data update

#8515 Fix mispelling of Corpses
  packs/book-of-the-dead-bestiary/wight-commander.json
  packs/pfs-season-4-bestiary/elite-smokesight-wight-commander.json
  packs/pfs-season-4-bestiary/smokesight-wight-commander.json
Labels: pr: data update

#8494 Add content from A Few Flowers More
  packs/equipment/putrid-sack-of-rotting-fruit.json
  packs/one-shot-bestiary/carl-the-cobbler.json
  packs/one-shot-bestiary/hidden-spiked-pit.json
  packs/one-shot-bestiary/jinkin-ripclaw.json
  packs/one-shot-bestiary/vilm.json
  packs/paizo-pregens/bottlespeaker-level-4.json
  packs/paizo-pregens/fluff-fang-level-4.json
  packs/paizo-pregens/popcorn-level-4.json
  packs/paizo-pregens/reaching-rings-level-4.json
  static/lang/re-en.json
  static/licenses/OpenGameLicense.md
Labels: pr: data entry, source: adventure

#8518 Fix regression in suppression of usage console spam
  src/module/item/physical/usage.ts
Labels: pr: bugfix

#8521 Fix empty stringified actions count
  packs/one-shot-bestiary/hidden-spiked-pit.json
  packs/one-shot-bestiary/jinkin-ripclaw.json
  packs/one-shot-bestiary/vilm.json
  packs/paizo-pregens/bottlespeaker-level-4.json
  packs/paizo-pregens/fluff-fang-level-4.json
  packs/paizo-pregens/reaching-rings-level-4.json
Labels: pr: data update

#8520 Give template-preview event handlers better names
  src/module/canvas/measured-template.ts
  src/module/item/physical/runes.ts
Labels: pr: refactor

#8519 Restore parameter shadowing to script macros
  src/module/macro.ts
Labels: pr: foundry v11

#8522 Fix dragged-template grid highlighting
  src/module/canvas/helpers.ts
  src/module/canvas/measured-template.ts
Labels: pr: bugfix

#8523 Add kingdom activity traits
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#8516 Update Akuzhail's Of Three Minds to use suboptions and add Note
  packs/kingmaker-bestiary/akuzhail.json
  static/lang/re-en.json
Labels: pr: data update

#8480 Update Marut's Fists of Thunder and Lightning to suboptions
  packs/pathfinder-bestiary-2/marut.json
  static/lang/re-en.json
Labels: pr: data update

#8529 Release Notes 5.1.0
  CHANGELOG.md
Labels: pr: housekeeping

#8531 Bump version
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#8534 Use token name when available for `Statistic` checks
  src/module/system/statistic/index.ts
Labels: pr: bugfix

#8527 Add getter placeholder for active party
  src/module/collection/actors.ts
Labels: pr: enhancement

#8528 Start on party exploration tab
  src/module/actor/party/data.ts
  src/module/actor/party/document.ts
  src/module/actor/party/sheet.ts
  src/scripts/config/index.ts
  src/styles/actor/party/_exploration.scss
  src/styles/actor/party/_index.scss
  src/styles/actor/party/_inventory.scss
  static/lang/en.json
  static/templates/actors/party/regions/exploration.hbs
  static/templates/actors/party/regions/inventory-members.hbs
  static/templates/actors/party/sheet.hbs
Labels: pr: enhancement

#8524 Resolve statistic dc to value in roll formulas and handlebars templates
  src/module/system/statistic/index.ts
Labels: pr: enhancement

#8540 Fix basic tag selector search
  src/module/system/tag-selector/base.ts
  src/module/system/tag-selector/basic.ts
  static/templates/system/tag-selector/basic.hbs
Labels: pr: bugfix

#8526 Include actor roll data in item roll data
  src/module/actor/base.ts
  src/module/actor/party/document.ts
  src/module/actor/party/types.ts
  src/module/item/base.ts
Labels: pr: enhancement

#8530 Update NPM dependencies, remove workaround of V9/V10 core issue
  .eslintrc.json
  package-lock.json
  package.json
  src/module/collection/actors.ts
Labels: pr: housekeeping, pr: foundry v11

#8525 Prefer highest value of same type when deduping modifiers
  src/module/actor/modifiers.ts
Labels: pr: enhancement

#8544 Pull target from strike-attack message for strike-damage rolls
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
  src/module/chat-message/listeners/cards.ts
  src/module/system/rolls.ts
Labels: pr: enhancement

#8545 Fix auto-toggling checkboxes in speeds selector
  src/module/system/tag-selector/base.ts
  src/module/system/tag-selector/senses.ts
  src/module/system/tag-selector/speeds.ts
Labels: pr: bugfix

#8543 Test property-rune dice
  src/module/actor/modifiers.ts
  src/module/item/physical/runes.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#8547 Add missing traits to Shatterstone
  packs/equipment/shatterstone-greater.json
  packs/equipment/shatterstone.json
Labels: pr: data update

#8546 Prepare more kingdom data, including vacancies and size modifiers
  src/module/actor/party/kingdom/data.ts
  src/module/actor/party/kingdom/helpers.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/kingdom/values.ts
  static/lang/kingmaker-en.json
Labels: pr: enhancement

#8550 Declare `fields` in RE `defineSchema` methods
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/crit-spec.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/iwr/immunity.ts
  src/module/rules/rule-element/strike.ts
Labels: pr: refactor

#8552 Fix level and price of Grub Gloves
  packs/equipment/grub-gloves-lesser.json
  packs/equipment/grub-gloves-moderate.json
Labels: pr: data update

#8548 Update Calikang's Suspended Animation to use suboptions
  packs/pathfinder-bestiary-3/calikang.json
  static/lang/re-en.json
Labels: pr: data update

#8542 Add deathdrinking weapon property rune
  src/module/item/physical/runes.ts
  src/module/item/weapon/values.ts
  static/lang/en.json
Labels: pr: data update

#8553 Update emulated token-hover methods to work with 11.304
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#8556 Set Simple NPC sheet as can't be default
  src/scripts/register-sheets.ts
  types/foundry/client/application/form-application/document-sheet-config.d.ts
Labels: pr: bugfix, pr: foundry v11

#8558 Fix level of Bloodknuckles
  packs/equipment/bloodknuckles.json
Labels: pr: data update

#8504 Add schemas to `DexterityModifierCapRuleElement` and `FastHealingRuleElement`
  src/module/item/sheet/rule-elements/fast-healing-form.ts
  src/module/rules/rule-element/dexterity-modifier-cap.ts
  src/module/rules/rule-element/fast-healing.ts
Labels: pr: refactor

#8489 Add schemas to `ActorTraitsRuleElement`, `AdjustDegreeOfSuccessRuleElement` and `MarkTokenRuleElement`
  src/module/rules/rule-element/actor-traits.ts
  src/module/rules/rule-element/adjust-degree-of-success.ts
  src/module/rules/rule-element/mark-token/rule-element.ts
Labels: pr: refactor, pr: delay merge

#8503 Add schemas to `BaseSpeedRuleElement` and `CreatureSizeRuleElement`
  src/module/rules/rule-element/base-speed.ts
  src/module/rules/rule-element/creature-size.ts
Labels: pr: refactor

#8561 Add new methods to fields type definitions
  types/foundry/common/data/fields.d.ts
Labels: pr: types update, pr: foundry v11

#8557 Allow setting active exploration activities + show in party sheet
  src/module/actor/character/data.ts
  src/module/actor/character/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/styles/actor/character/_actions.scss
  src/styles/actor/party/_exploration.scss
  src/styles/actor/party/_index.scss
  static/lang/en.json
  static/template.json
  static/templates/actors/character/tabs/actions.hbs
  static/templates/actors/party/regions/exploration.hbs
Labels: pr: enhancement, pr: new feature

#8563 Remove pre-caching attempt at load reduction when calling `itemTypes`
  src/module/actor/character/document.ts
Labels: pr: refactor

#8560 Enable secret perception checks for the GM from party overview
  src/module/actor/party/sheet.ts
  src/styles/actor/party/_index.scss
  static/templates/actors/party/regions/overview.hbs
Labels: pr: enhancement

#8562 Set armor HP max to show whether it is adjusted higher or lower
  static/templates/items/armor-details.hbs
Labels: pr: enhancement

#8568 Use snapped origin when calculating cone offset
  src/module/canvas/helpers.ts
Labels: pr: bugfix

#8571 Work around upstream error thrown when encounters are created
  src/module/encounter/document.ts
  types/foundry/client/data/documents/combat.d.ts
Labels: pr: bugfix

#8572 Update some PIXI-related type definitions
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/layers/effects/visibility.d.ts
  types/foundry/client/pixi/sources/light-source.d.ts
Labels: pr: types update

#8570 Fix test of token visibility in `TokenDocument#_onRelatedUpdate`
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/data/documents/actor.d.ts
Labels: pr: bugfix

#8573 Adjust token-visibility testing to be more compliant with 2e rules
  src/module/canvas/token/object.ts
Labels: pr: enhancement, vision

#8575 localise "legacy flaws" on ability builder
  static/lang/en.json
  static/templates/actors/character/ability-builder.hbs
Labels: pr: bugfix

#8581 Update type definition of `ClockwiseSweepPolygon`
  types/foundry/client/pixi/core/shapes/polygon-helpers.d.ts
  types/foundry/client/pixi/perception/clockwise-sweep.d.ts
Labels: pr: types update

#8584 Indicate verified compatibility with 11.305
  src/module/encounter/document.ts
  static/system.json
Labels: pr: housekeeping

#8586 Add missing localization string on NPC sheet.
  static/lang/en.json
Labels: pr: data update

#8580 Utilize `Users.activeGM` where appropriate
  src/module/actor/base.ts
  src/scripts/hooks/ready.ts
  types/foundry/client/data/collections/users.d.ts
Labels: pr: refactor, pr: foundry v11

#8583 Include parent items' names and UUIDs in `DataModel` validation warnings
  src/module/rules/rule-element/base.ts
Labels: pr: enhancement

#8587 Have token HUD show Broken for vehicles/loot and Hidden for others
  src/module/canvas/status-effects.ts
  src/scripts/config/index.ts
Labels: ui/ux

#8588 Remove hidden tokens from vision detection
  src/module/canvas/perception/modes.ts
Labels: pr: enhancement, vision

#8582 Group Ankhrav's Spray Acid damage
  packs/pathfinder-bestiary/ankhrav.json
  packs/pathfinder-bestiary/hive-mother.json
Labels: pr: data update

#8574 Update Effect: Fiddle to include grant of flat-footed and slowed
  packs/bestiary-effects/effect-fiddle.json
Labels: pr: data update

#8591 Apply damage-type overrides to fatal damage dice
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#8590 Expand search for possible token image changes on delta updates
  src/module/scene/token-document/actor-delta.ts
  types/foundry/client/data/documents/actor-delta.d.ts
Labels: pr: bugfix

#8592 Add Frequency to Rupture Stomp description
  packs/feats/rupture-stomp.json
Labels: pr: data update

#8569 Fix category of Gathering Moss and Propulsive Leap. Add duration to Effect: Gathering Moss.
  packs/feat-effects/effect-gathering-moss.json
  packs/feat-effects/effect-propulsive-leap.json
  packs/feats/gathering-moss.json
  packs/feats/propulsive-leap.json
Labels: pr: data update

#8589 Obscure token sprite if hearing/tremorsense detection filter is applied
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: enhancement, ui/ux, vision

#8593 Release Notes 5.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#8601 Add fallback for stale template.json
  src/module/actor/character/document.ts
  src/module/item/feat/document.ts
  src/util/misc.ts
Labels: pr: bugfix

#8604 Fix stringified level for Ashen
  packs/equipment/ashen.json
Labels: pr: data update

#8603 Fix whitespace and alignment issues in party inventory
  src/styles/actor/party/_exploration.scss
  src/styles/actor/party/_index.scss
  src/styles/actor/party/_inventory.scss
  src/styles/actor/party/_overview.scss
  static/templates/actors/party/regions/inventory-members.hbs
Labels: ui/ux

#8600 Update some NPM dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#8598 Fix rule element in Echo of the Fallen
  packs/feats/echo-of-the-fallen.json
Labels: pr: data update

#8612 Fix regression in determining battle form attack modifiers
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: bugfix

#8611 Restore RE-based token effect icons in `ActorPF2e#temporaryEffects`
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  src/module/rules/rule-element/token-effect-icon.ts
  src/module/rules/synthetics.ts
Labels: pr: bugfix

#8619 Fix price of major cloister robe
  packs/equipment/cloister-robe-major.json
Labels: pr: data update

#8621 Release Notes 5.1.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#8622 Hide active button if actor has no parties
  src/module/actor/character/document.ts
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: bugfix

#8620 Fix character exploration if character renders before party, and reprepare on member change
  src/module/actor/party/document.ts
  src/scripts/hooks/ready.ts
Labels: pr: bugfix

#8608 Add schemas to `FixedProficiencyRuleElement`, `LoseHitPointsRuleElement` and `MartialProficiencyRuleElement`
  src/module/rules/rule-element/fixed-proficiency.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/module/rules/rule-element/martial-proficiency.ts
Labels: pr: refactor

#8625 Hide "showPartyStats" setting until party actor is released
  src/module/system/settings/metagame.ts
Labels: pr: bugfix

#8627 Add scrollbar to familiar sheet
  src/styles/actor/familiar/_index.scss
  static/templates/actors/familiar-sheet.hbs
Labels: pr: bugfix

#8635 Fix incorrect condition theme on initial load
  src/module/canvas/status-effects.ts
  src/scripts/hooks/init.ts
  src/scripts/hooks/setup.ts
Labels: pr: bugfix

#8609 Add schemas to `MultipleAttackPenaltyRuleElement`, `RollTwiceRuleElement` and `SenseRuleElement`
  src/module/rules/rule-element/multiple-attack-penalty.ts
  src/module/rules/rule-element/roll-twice.ts
  src/module/rules/rule-element/sense.ts
Labels: pr: refactor

#8636 Fill out rest of AE data model interface in `TokenEffect` class
  src/module/actor/token-effect.ts
  types/foundry/client/data/documents/active-effect.d.ts
  types/foundry/common/documents/active-effect.d.ts
Labels: pr: enhancement

#8638 Handle RE-added traits that may affect actors' modes of being
  packs/feats/mummy-dedication.json
  src/module/rules/rule-element/actor-traits.ts
Labels: pr: bugfix, pr: data update

#8639 Fix refresh of death icon on setting change
  src/module/canvas/status-effects.ts
  src/module/system/settings/index.ts
  src/scripts/hooks/setup.ts
Labels: pr: bugfix

#8640 Group ActorTraits REs
  packs/feats/ghost-dedication.json
  packs/feats/ghoul-dedication.json
  packs/feats/vampire-dedication.json
Labels: pr: data update

#8626 Add schemas to `TokenEffectIconRuleElement`, `TokenImageRuleElement`, `TokenNameRuleElement`, `TokenLightRuleElement` and `WeaponPotencyRuleElement`
  src/module/rules/rule-element/token-effect-icon.ts
  src/module/rules/rule-element/token-image.ts
  src/module/rules/rule-element/token-light.ts
  src/module/rules/rule-element/token-name.ts
  src/module/rules/rule-element/weapon-potency.ts
Labels: pr: refactor

#8642 Fix return type of `DataField#initialize`
  src/module/system/schema-data-fields.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/data/validation-failure.d.ts
Labels: pr: types update

#8641 Reorganize imports in armor/document.ts
  src/module/item/armor/document.ts
Labels: pr: refactor

#8644 Add types for `Quadtree` and `CanvasQuadtree`
  types/foundry/client/pixi/helpers/index.d.ts
  types/foundry/client/pixi/helpers/quadtree.d.ts
  types/foundry/client/pixi/placeables-layer/base.d.ts
  types/foundry/client/pixi/placeables-layer/drawings-layer.d.ts
  types/foundry/client/pixi/placeables-layer/lighting-layer.d.ts
  types/foundry/client/pixi/placeables-layer/notes-layer.d.ts
  types/foundry/client/pixi/placeables-layer/sounds-layer.d.ts
  types/foundry/client/pixi/placeables-layer/template-layer.d.ts
  types/foundry/client/pixi/placeables-layer/tiles-layer.d.ts
  types/foundry/client/pixi/placeables-layer/token-layer.d.ts
  types/foundry/client/pixi/placeables-layer/walls-layer.d.ts
Labels: pr: types update, pr: foundry v11

#8643 Fix maintaining focus on data-property sheet inputs upon rerender
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/sheet/base.ts
  src/module/sheet/helpers.ts
Labels: pr: bugfix

#8646 Update type signature of `_on*DescendantDocuments` methods
  src/module/actor/loot/document.ts
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/combat.d.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/common/documents/token.d.ts
  types/foundry/scripts/generate-client-base-mixes.ts
Labels: pr: types update, pr: foundry v11

#8566 Allow Strike RE dice property to be resolvable
  src/module/rules/rule-element/strike.ts
Labels: pr: enhancement

#8648 Work around issue affecting updated synthetic actors in unviewed scenes
  .eslintrc.json
  src/module/actor/base.ts
Labels: pr: bugfix

#8651 Add note to Wereant Poisoner's Vitriolic Strikes
  packs/strength-of-thousands-bestiary/wereant-poisoner.json
Labels: pr: data update

#8650 Update werecreature's Moon Frenzy
  packs/bestiary-effects/effect-moon-frenzy.json
  packs/pathfinder-bestiary-2/wereboar.json
  packs/pathfinder-bestiary-2/weretiger.json
  packs/pathfinder-bestiary-3/werebat.json
  packs/pathfinder-bestiary-3/werecrocodile.json
  packs/pfs-season-3-bestiary/werebat-pfs-3-13.json
  packs/pfs-season-3-bestiary/weretiger-pfs-3-13.json
Labels: pr: data update

#8649 Add missing Athletics to Tallow Guardian
  packs/crown-of-the-kobold-king-bestiary/tallow-guardian.json
Labels: pr: data update

#8647 Fix some action predicates
  packs/abomination-vaults-bestiary/volluk-azrinae.json
  packs/age-of-ashes-bestiary/ishti.json
  packs/age-of-ashes-bestiary/kelda-halrig.json
  packs/age-of-ashes-bestiary/renali.json
  packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
  packs/agents-of-edgewatch-bestiary/daemonic-infector.json
  packs/blood-lords-bestiary/lasheeli.json
  packs/equipment-effects/effect-impossible-cake-greater.json
  packs/equipment-effects/effect-impossible-cake-major.json
  packs/equipment-effects/effect-impossible-cake.json
  packs/equipment/curtain-call-cloak.json
  packs/equipment/doll-exquisite-surprise.json
  packs/equipment/nosoi-charm-greater.json
  packs/equipment/nosoi-charm.json
  packs/equipment/oozepick-greater.json
  packs/equipment/oozepick.json
  packs/equipment/pickpockets-tailoring.json
  packs/equipment/ring-of-maniacal-devices-greater.json
  packs/equipment/songbirds-brush.json
  packs/equipment/stole-of-civility.json
  packs/equipment/writ-of-authenticity.json
  packs/feats/fleeing-diversion.json
  packs/feats/green-empathy.json
  packs/feats/virtuosic-performer.json
  packs/heritages/songbird-strix.json
  packs/kingmaker-bestiary/the-dancing-lady.json
  packs/menace-under-otari-bestiary/harpy-bb.json
  packs/paizo-pregens/fluff-fang-level-4.json
  packs/pathfinder-bestiary-2/baobhan-sith.json
  packs/pathfinder-bestiary-2/rusalka.json
  packs/pathfinder-bestiary-2/vexgit.json
  packs/pathfinder-bestiary-3/vine-leshy.json
  packs/pathfinder-bestiary/harpy.json
  packs/pathfinder-bestiary/salamander.json
  packs/pfs-season-4-bestiary/harpy-forager.json
  packs/pfs-season-4-bestiary/harpy-wailer.json
  packs/pfs-season-4-bestiary/revna-the-brave-5-6.json
  packs/pfs-season-4-bestiary/revna-the-brave-7-8.json
Labels: pr: data update

#8637 Standardize language of some choice set prompts
  static/lang/re-en.json
Labels: pr: data update

#8606 Update Ahmoza Twins's Channel Element to use suboptions
  packs/fists-of-the-ruby-phoenix-bestiary/ki-adept-ahmoza-twins.json
Labels: pr: data update

#8607 Allow City Scavenger's subsist bonus to apply to Society
  packs/feats/city-scavenger.json
  static/lang/re-en.json
Labels: pr: data update

#8654 Fix type of `ActorDelta#items`
  src/module/scene/token-document/actor-delta.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: types update

#8658 Include linked tokens in `ActorPF2e#_updateDependentTokens`
  src/module/actor/base.ts
Labels: pr: bugfix

#8653 Start process of referring to spell levels as ranks
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/helpers.ts
  src/module/actor/sheet/popups/casting-item-create-dialog.ts
  src/module/chat-message/document.ts
  src/module/item/base.ts
  src/module/item/consumable/spell-consumables.ts
  src/module/item/deity/sheet.ts
  src/module/item/spell/document.ts
  src/module/item/spell/sheet.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/item/spellcasting-entry/types.ts
  src/module/scene/measured-template-document.ts
  src/module/system/statistic/index.ts
  static/templates/chat/spell-card.hbs
Labels: pr: refactor

#8618 Track "unrecoverable" hit points, implement in Quicksilver mutagen
  packs/equipment-effects/effect-quicksilver-mutagen-greater.json
  packs/equipment-effects/effect-quicksilver-mutagen-lesser.json
  packs/equipment-effects/effect-quicksilver-mutagen-major.json
  packs/equipment-effects/effect-quicksilver-mutagen-moderate.json
  src/module/actor/base.ts
  src/module/actor/character/data.ts
  src/module/actor/creature/data.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/data/base.ts
  src/module/actor/npc/data.ts
  src/module/actor/npc/types.ts
  src/module/actor/vehicle/data.ts
  src/module/actor/vehicle/document.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/styles/actor/sidebar/_health.scss
  static/lang/en.json
  static/templates/actors/character/sidebar/health.hbs
Labels: pr: data update, pr: enhancement

#8660 Fix hit points lost from lesser quicksilver mutagen
  packs/equipment-effects/effect-quicksilver-mutagen-lesser.json
Labels: pr: data update

#8661 Add `xor` predication operator
  src/module/system/predication.ts
  tests/module/system/predication.test.ts
Labels: pr: enhancement

#8564 Add Item Alteration rule element
  src/module/actor/base.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/base.ts
  src/module/item/condition/data.ts
  src/module/item/condition/document.ts
  src/module/item/effect/document.ts
  src/module/item/helpers.ts
  src/module/item/physical/document.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/alter-item/helpers.ts
  src/module/rules/rule-element/alter-item/index.ts
  src/module/rules/rule-element/alter-item/schema.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/grant-item/schema.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/index.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  src/module/rules/rule-element/roll-option.ts
  static/lang/re-en.json
  tsconfig.json
Labels: pr: new feature

#8666 Decrease fire persistent damage recovery DC on Charhide Goblin
  packs/heritages/charhide-goblin.json
Labels: pr: data update

#8667 Refresh Fumbus' Charhide Goblin heritage
  packs/iconics/fumbus-level-1.json
  packs/iconics/fumbus-level-3.json
  packs/iconics/fumbus-level-5.json
Labels: pr: data update

#8668 Set item alteration RE priority according to change mode
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: bugfix

#8663 Update traits for Lethargy Poison to change conjuration to consumable
  packs/equipment/lethargy-poison.json
Labels: pr: data update

#8662 Automate Construct Armor hardness breaking
  packs/agents-of-edgewatch-bestiary/prospecti-statue.json
  packs/blood-lords-bestiary/animated-fireplace.json
  packs/blood-lords-bestiary/animated-tea-cart.json
  packs/blood-lords-bestiary/mechanical-laborer.json
  packs/blood-lords-bestiary/shadowbound-monk-statue.json
  packs/crown-of-the-kobold-king-bestiary/dismemberment-table.json
  packs/crown-of-the-kobold-king-bestiary/ulizmilas-cauldron.json
  packs/extinction-curse-bestiary/guardian-of-the-faithful.json
  packs/gatewalkers-bestiary/ancient-tupilaq.json
  packs/gatewalkers-bestiary/apothecarys-cabinet.json
  packs/gatewalkers-bestiary/quarry-construct.json
  packs/menace-under-otari-bestiary/animated-armor-bb.json
  packs/one-shot-bestiary/princess-sunset.json
  packs/pathfinder-bestiary-3/animated-colossus.json
  packs/pathfinder-bestiary-3/animated-furnace.json
  packs/pathfinder-bestiary-3/animated-silverware-swarm.json
  packs/pathfinder-bestiary-3/animated-trebuchet.json
  packs/pathfinder-bestiary-3/tupilaq.json
  packs/pathfinder-bestiary/animated-armor.json
  packs/pathfinder-bestiary/animated-broom.json
  packs/pathfinder-bestiary/animated-statue.json
  packs/pathfinder-bestiary/giant-animated-statue.json
  packs/pfs-season-1-bestiary/lesser-guardian-statue.json
  packs/pfs-season-1-bestiary/spirit-guardian-statue.json
  packs/pfs-season-1-bestiary/statue-of-set.json
  packs/pfs-season-1-bestiary/synthetic-khismar-5-6.json
  packs/pfs-season-1-bestiary/synthetic-khismar-7-8.json
  packs/pfs-season-2-bestiary/anatomical-model-1-2.json
  packs/pfs-season-2-bestiary/anatomical-model-3-4.json
  packs/pfs-season-2-bestiary/animated-guardian-warrior.json
  packs/pfs-season-2-bestiary/animated-guardian.json
  packs/pfs-season-2-bestiary/elite-anatomical-model-3-4.json
  packs/pfs-season-2-bestiary/kayajima-guardian-dogu-3-4.json
  packs/pfs-season-2-bestiary/kayajima-guardian-dogu-5-6.json
  packs/pfs-season-2-bestiary/reinforced-animated-guardian.json
  packs/pfs-season-3-bestiary/animated-blade-pfs-3-99.json
  packs/pfs-season-3-bestiary/animated-cookware.json
  packs/pfs-season-3-bestiary/animated-full-plate-pfs-3-99.json
  packs/pfs-season-3-bestiary/animated-knickknack-1-2.json
  packs/pfs-season-3-bestiary/animated-knickknack-3-4.json
  packs/pfs-season-3-bestiary/deep-shadow-guardian.json
  packs/pfs-season-3-bestiary/flaming-animated-armor-ashgrip-1-2.json
  packs/pfs-season-3-bestiary/flaming-animated-armor-firecutter-1-2.json
  packs/pfs-season-3-bestiary/flaming-animated-armor-holy-hand-1-2.json
  packs/pfs-season-3-bestiary/flaming-animated-armor-leadroar-1-2.json
  packs/pfs-season-3-bestiary/lightweight-animated-armor.json
  packs/pfs-season-3-bestiary/sandswept-statue.json
  packs/pfs-season-3-bestiary/shadow-guardian.json
  packs/pfs-season-4-bestiary/animated-leather-armor.json
  packs/quest-for-the-frozen-flame-bestiary/animated-blade.json
  packs/strength-of-thousands-bestiary/living-sun-spire.json
Labels: pr: data update

#8657 Add spell effect for Moon Frenzy
  packs/spell-effects/spell-effect-moon-frenzy.json
  packs/spells/moon-frenzy.json
  static/lang/re-en.json
Labels: pr: data update

#8655 Add Spell Effect: Healer's Blessing
  packs/spell-effects/spell-effect-healers-blessing.json
  packs/spells/healers-blessing.json
Labels: pr: data entry, pr: data update

#8672 Add 120 foot reach to NPC strike list
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#8676 Fix remaining `_on*DescendantDocuments` callbacks
  types/foundry/client/data/documents/combat.d.ts
  types/foundry/client/data/documents/playlist.d.ts
  types/foundry/client/data/documents/roll-table.d.ts
  types/foundry/client/data/documents/scene.d.ts
Labels: pr: types update

#8674 Add effect for Infernal Wound
  packs/abomination-vaults-bestiary/drill-field-barbazu.json
  packs/abomination-vaults-bestiary/hellforge-barbazu.json
  packs/abomination-vaults-bestiary/torture-chamber-barbazu.json
  packs/abomination-vaults-bestiary/urevian.json
  packs/bestiary-effects/effect-infernal-wound.json
  packs/pathfinder-bestiary-2/cornugon.json
  packs/pathfinder-bestiary/barbazu.json
  packs/pathfinder-bestiary/phistophilus.json
  packs/pfs-season-1-bestiary/nashaxian-the-angered.json
Labels: pr: data update

#8680 Fix prefix in persistent damage category roll option
  src/module/item/condition/document.ts
Labels: pr: bugfix

#8679 Update `Document#_pre(Create|Update|Delete)` return types for V11
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/actor/party/document.ts
  src/module/actor/vehicle/document.ts
  src/module/item/action/document.ts
  src/module/item/affliction/document.ts
  src/module/item/base.ts
  src/module/item/condition/document.ts
  src/module/item/effect/document.ts
  src/module/item/feat/document.ts
  src/module/item/kit/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/weapon/document.ts
  types/foundry/client/data/documents/active-effect.d.ts
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/client/data/documents/chat-message.d.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/documents/active-effect.d.ts
  types/foundry/common/documents/actor.d.ts
  types/foundry/common/documents/fog-exploration.d.ts
  types/foundry/common/documents/macro.d.ts
Labels: pr: refactor, pr: types update, pr: foundry v11

#8684 Block changing badge values out of bounds in `EffectPF2e#_preUpdate`
  src/module/item/effect/document.ts
Labels: pr: bugfix, pr: refactor

#8686 Implement Curse of the Perpetual Storm as badged effect
  packs/feat-effects/effect-curse-of-the-perpetual-storm.json
Labels: pr: data update

#8687 Have perpetual storm item alterations alter self
  packs/feat-effects/effect-curse-of-the-perpetual-storm.json
Labels: pr: data update

#8683 Fix default ability action cost
  src/module/item/action/sheet.ts
  static/template.json
Labels: pr: bugfix

#8685 Distinguish between effect badge source and (prepared) data
  src/module/item/abstract-effect/data.ts
  src/module/item/affliction/document.ts
  src/module/item/condition/document.ts
  src/module/item/effect/data.ts
  src/module/item/effect/document.ts
  src/module/item/effect/sheet.ts
Labels: pr: refactor

#8695 Fix token Z-cycling in Foundry 11.304+
  src/module/canvas/layer/token.ts
  types/foundry/client/pixi/placeables-layer/base.d.ts
  types/foundry/client/pixi/placeables/base.d.ts
  types/foundry/client/pixi/placeables/primary-canvas-objects/token-mesh.d.ts
Labels: pr: bugfix

#8688 Support folders in run-migration
  build/run-migration.ts
Labels: pr: enhancement

#8696 Start adding canvas mixin output types
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/placeable.d.ts
  types/foundry/client/pixi/placeables/index.d.ts
  types/foundry/client/pixi/placeables/primary-canvas-objects/primary-canvas-object.d.ts
  types/foundry/client/pixi/placeables/primary-canvas-objects/token-mesh.d.ts
Labels: pr: types update

#8682 Remove `RuleElementPF2e#data`
  src/module/migration/migrations/745-effect-target-to-choice-set.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/rules/rule-element/crafting/formula.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/fixed-proficiency.ts
  src/module/rules/rule-element/index.ts
  static/templates/items/rules/flat-modifier.hbs
Labels: pr: refactor

#8698 Add missing sources for effects
  packs/feat-effects/effect-harrow-the-fiend.json
  packs/feat-effects/effect-recall-under-pressure.json
  packs/spell-effects/spell-effect-incendiary-aura.json
Labels: pr: data update

#8694 Update description formatting of Hunter's Dawn, Kortos Diamond, Piereta
  packs/equipment/hunters-dawn.json
  packs/equipment/kortos-diamond.json
  packs/equipment/piereta.json
Labels: pr: data update

#8689 Brush up Corrupted Priest rule elements
  packs/extinction-curse-bestiary/corrupted-priest.json
Labels: pr: data update

#8691 Remove @Template links in Tempest mystery description
  packs/classfeatures/tempest.json
Labels: pr: data update

#8700 Collect note and DoS adjustment synthetics for recovery checks
  src/module/actor/creature/document.ts
  src/module/item/condition/document.ts
  src/module/system/statistic/index.ts
  src/scripts/ui/inline-roll-links.ts
  static/lang/en.json
Labels: pr: enhancement

#8677 Update Effect: Ichthyosis Mutagen for persistent bleed recovery
  packs/equipment-effects/effect-ichthyosis-mutagen.json
Labels: pr: data update

#8706 Fix option acquisition and roll inspector for flat checks
  src/module/system/statistic/index.ts
  static/lang/en.json
  static/templates/chat/chat-roll-details.hbs
Labels: pr: bugfix

#8707 Add isDestroyed check to the raiseAShield action
  src/scripts/macros/raise-a-shield.ts
Labels: pr: bugfix

#8659 Allow thrown weapons to configured for use as ammunition
  packs/equipment/dart.json
  src/module/actor/character/document.ts
  src/module/actor/data/base.ts
  src/module/actor/sheet/trick-magic-item-popup.ts
  src/module/item/consumable/document.ts
  src/module/item/physical/sheet.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  static/lang/en.json
  static/templates/items/armor-details.hbs
  static/templates/items/consumable-details.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: enhancement

#8652 Add content from Sky King's Tomb Player's Guide
  packs/backgrounds/child-of-notoriety.json
  packs/backgrounds/clan-associate.json
  packs/backgrounds/conservator.json
  packs/backgrounds/dedicated-delver.json
  packs/backgrounds/eclectic-scholar.json
  packs/backgrounds/historical-reenactor.json
Labels: source: adventure path, pr: data entry

#8681 Remove `AELikeRuleElement` as subclass of other REs
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: refactor

#8714 Fix some formatting errors
  packs/equipment/mycoweave-shield-greater.json
  packs/equipment/mycoweave-shield-lesser.json
  packs/equipment/mycoweave-shield-major.json
  packs/sky-kings-tomb-bestiary/hhrulkaz.json
  packs/sky-kings-tomb-bestiary/sporeborn-sheep.json
  packs/sky-kings-tomb-bestiary/xulgath-ravening.json
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#8711 Add automation for Bloody Barber Goon's Thunk 'n' Slice
  packs/agents-of-edgewatch-bestiary/bloody-barber-goon.json
Labels: pr: data update

#8704 Add automation for Garrote Master Assassin's Point Blank and Starwatch Commando's Target Culprit
  packs/agents-of-edgewatch-bestiary/garrote-master-assassin.json
  packs/agents-of-edgewatch-bestiary/starwatch-commando.json
Labels: pr: data update

#8702 Fix missing damage types in some inline links
  packs/equipment/lifes-last-breath.json
  packs/equipment/nethysian-bulwark.json
  packs/equipment/numerian-steel-breastplate.json
  packs/equipment/staff-of-power.json
  packs/equipment/staff-of-the-magi.json
  packs/equipment/stoneraiser-javelin.json
  packs/equipment/storm-arrow.json
  packs/equipment/urn-of-ashes.json
  packs/equipment/wand-of-the-spider-2nd-level-spell.json
  packs/equipment/wand-of-the-spider-4th-level-spell.json
Labels: pr: data update

#8703 Add automation for Arrow of Death
  packs/feats/arrow-of-death.json
  static/lang/re-en.json
Labels: pr: data update

#8712 Fix missing damage types in One With the Land and Zon-Kuthon - Moderate Curse
  packs/boons-and-curses/zon-kuthon-moderate-curse.json
  packs/spell-effects/spell-effect-one-with-the-land.json
  packs/spells/one-with-the-land.json
Labels: pr: data update

#8716 Add effects for Deadweight Mutagens
  packs/equipment-effects/effect-deadweight-mutagen-greater.json
  packs/equipment-effects/effect-deadweight-mutagen-lesser.json
  packs/equipment-effects/effect-deadweight-mutagen-major.json
  packs/equipment-effects/effect-deadweight-mutagen-moderate.json
  packs/equipment/deadweight-mutagen-greater.json
  packs/equipment/deadweight-mutagen-lesser.json
  packs/equipment/deadweight-mutagen-major.json
  packs/equipment/deadweight-mutagen-moderate.json
Labels: pr: data update

#8717 Fix regression in AdjustModifier model validation
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/base.ts
Labels: pr: bugfix

#8713 Fix capitalization in localization key
  src/scripts/config/index.ts
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#8718 Fill missing localization entry used on item-sheet rules panel
  static/lang/en.json
Labels: pr: data update
