Repository foundryvtt/pf2e, pull requests merged in 2023-10, with the labels that each got.

#10448 Fix application of MAP REs to NPC attacks
  src/module/actor/helpers.ts
Labels: pr: bugfix

#10449 Resolve escape DC for unarmed-attack escape
  src/module/system/action-macros/helpers.ts
Labels: pr: bugfix

#10454 Adding missing traits to Straugh's claw strike
  packs/blood-lords-bestiary/straugh.json
Labels: pr: data update

#10455 Include aura predicate in basic form tab
  static/templates/items/rules/aura.hbs
Labels: pr: bugfix

#10456 Restore scroll position after codemirror rules edit
  src/module/item/sheet/base.ts
Labels: pr: enhancement

#10453 Condense community repair effects
  packs/spell-effects/spell-effect-community-repair.json
  packs/spells/community-repair.json
Labels: pr: data update

#10460 Unify inline damage links for Shanrigol's Sapping Squeeze
  packs/abomination-vaults-bestiary/shanrigol-behemoth.json
  packs/abomination-vaults-bestiary/shanrigol-heap.json
  packs/pfs-season-3-bestiary/shanrigol-mound.json
Labels: pr: data update

#10458 Remove Anticipate Peril spell effect after initiative rolls
  packs/spell-effects/spell-effect-anticipate-peril.json
Labels: pr: data update

#10459 Consolidate domain acquisition for strike attack and damage rolls
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
  src/module/item/melee/document.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/rules/rule-element/strike.ts
  src/module/system/damage/weapon.ts
Labels: pr: refactor

#10462 Fix rule element on Fearless Sash
  packs/equipment/fearless-sash.json
Labels: pr: data update

#10465 Fix link to Spell Effect: Community Repair and provide link to spell from effect
  packs/spell-effects/spell-effect-community-repair.json
  packs/spells/community-repair.json
Labels: pr: data update

#10469 Fix issue with showing critical damage cue when metagame settings should prevent it
  static/templates/chat/check/roll.hbs
Labels: pr: bugfix

#10470 Fix some mispellings of "visibility"
  packs/equipment/golden-chrysalis.json
  src/module/system/text-editor.ts
Labels: pr: data update

#10477 Fix missing emdash characters in Eternal Torch
  packs/feats/eternal-torch.json
Labels: pr: data update

#10466 Look for previous RE forms by exact constructor name
  src/module/item/sheet/base.ts
Labels: pr: bugfix

#10463 Add support for defense proficiencies to MartialProficiency RE
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/item/armor/values.ts
  src/module/item/class/document.ts
  src/module/migration/migrations/870-martial-to-proficiencies.ts
  src/module/rules/rule-element/martial-proficiency.ts
Labels: pr: enhancement

#10474 Fix loss of flavor on numeric inline splash and precision
  src/module/system/damage/helpers.ts
Labels: pr: bugfix

#10475 Add Shatter Glass reaction
  packs/actions/shatter-glass.json
  packs/feats/glass-skin.json
Labels: pr: data update

#10476 Automate Lock On feat
  packs/feat-effects/effect-lock-on.json
  packs/feats/lock-on.json
  static/lang/re-en.json
Labels: pr: data update

#10478 Convert hyphen-like and dash characters to hyphens and HTML entities
  build/lib/extractor.ts
Labels: pr: housekeeping

#10479 Reduce aggression of whitespace trimming on extract
  build/lib/extractor.ts
Labels: pr: bugfix, pr: housekeeping

#10481 Fix typo in PC AC preparation
  src/module/actor/character/document.ts
Labels: pr: bugfix

#10482 Fix parent of `ClientBaseActor`
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/common/documents/wall.d.ts
Labels: pr: types update

#10471 Allow slug set in choice sets to serve as roll-option prefixes and flags
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: enhancement

#10484 Add schema definitions for `TileDocument` and `WallDocument`
  build/lib/compendium-pack.ts
  src/module/migration/migrations/645-token-image-size.ts
  src/module/migration/migrations/719-shrug-flanking.ts
  types/foundry/common/documents/actor.d.ts
  types/foundry/common/documents/setting.d.ts
  types/foundry/common/documents/tile.d.ts
  types/foundry/common/documents/wall.d.ts
Labels: pr: types update

#10485 Extend `PrototypeToken` from `DataModel`
  src/module/scene/token-document/document.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/data/data.d.ts
Labels: pr: types update

#10483 Fix some broken links
  packs/bestiary-effects/effect-distracting-giggle.json
  packs/bestiary-effects/effect-howl-of-vengeful-fury.json
  packs/equipment-effects/effect-cape-of-justice-distracted.json
  packs/equipment-effects/effect-hongruis-gratitude-lantern.json
  packs/equipment-effects/effect-hongruis-gratitude-umbrella.json
  packs/equipment-effects/effect-matsukis-medicinal-wine.json
  packs/equipment-effects/effect-ugly-cutes-gift.json
  packs/equipment/animal-turning-fulu.json
  packs/equipment/cape-of-justice.json
  packs/equipment/fiends-hunger.json
  packs/equipment/firecracker-fulu.json
  packs/equipment/hongruis-gratitude.json
  packs/equipment/horn-of-rust.json
  packs/equipment/matsukis-medicinal-wine.json
  packs/equipment/noppera-bo-hood.json
  packs/equipment/privacy-ward-fulu-chamber.json
  packs/equipment/privacy-ward-fulu-hallway.json
  packs/equipment/privacy-ward-fulu-room.json
  packs/equipment/spider-lily-tattoo.json
  packs/equipment/spirit-trap.json
  packs/equipment/travelers-fulu.json
  packs/equipment/ugly-cutes-gift.json
  packs/rusthenge-bestiary/meitremar.json
  packs/season-of-ghosts-bestiary/animated-cookware-swarm.json
  packs/season-of-ghosts-bestiary/fan-hongrui.json
  packs/season-of-ghosts-bestiary/grasping-currents.json
  packs/season-of-ghosts-bestiary/haphazard-wood-pile.json
  packs/season-of-ghosts-bestiary/hu-ban-niang.json
  packs/season-of-ghosts-bestiary/jinkin.json
  packs/season-of-ghosts-bestiary/kugaptees-blessing.json
  packs/season-of-ghosts-bestiary/noppera-bo-grunt.json
  packs/season-of-ghosts-bestiary/noppera-bo-occultist.json
  packs/season-of-ghosts-bestiary/noppera-bo-trickster.json
  packs/season-of-ghosts-bestiary/phantom-boar.json
  packs/season-of-ghosts-bestiary/phantom-gecko.json
  packs/season-of-ghosts-bestiary/phantom-raven.json
  packs/season-of-ghosts-bestiary/phantom-wolf.json
  packs/season-of-ghosts-bestiary/red-hooded-thatchling.json
  packs/season-of-ghosts-bestiary/shinigami.json
  packs/season-of-ghosts-bestiary/shou-matsuki.json
  packs/season-of-ghosts-bestiary/stone-spider.json
  packs/season-of-ghosts-bestiary/thatchling.json
  packs/season-of-ghosts-bestiary/very-drunken-jinkin.json
  packs/season-of-ghosts-bestiary/zoudou-the-zealous.json
Labels: pr: data update

#10492 Add details template for all item sheets
  src/module/item/abc/sheet.ts
  src/module/item/affliction/sheet.ts
  src/module/item/ancestry/sheet.ts
  src/module/item/armor/sheet.ts
  src/module/item/book/sheet.ts
  src/module/item/consumable/sheet.ts
  src/module/item/container/sheet.ts
  src/module/item/deity/sheet.ts
  src/module/item/effect/sheet.ts
  src/module/item/equipment/sheet.ts
  src/module/item/heritage/sheet.ts
  src/module/item/kit/sheet.ts
  src/module/item/physical/sheet.ts
  src/module/item/sheet/base.ts
  src/module/item/treasure/sheet.ts
  src/module/item/weapon/sheet.ts
  src/scripts/register-templates.ts
  src/styles/item/_deity-sheet.scss
  src/styles/item/_feat-sheet.scss
  src/styles/item/_identify-item.scss
  src/styles/item/_index.scss
  src/styles/item/_melee-sheet.scss
  src/styles/item/_rules.scss
  src/styles/item/_weapon-sheet.scss
  static/templates/items/effect-details.hbs
  static/templates/items/heritage-details.hbs
  static/templates/items/mystify-panel.hbs
  static/templates/items/sheet.hbs
  static/templates/items/treasure-details.hbs
Labels: pr: refactor, ui/ux

#10493 Fix tag balance in item sheet, use `section` for tabbed panels
  static/templates/items/mystify-panel.hbs
  static/templates/items/sheet.hbs
Labels: pr: bugfix

#10473 Add support for alterations of several armor properties
  src/module/item/physical/bulk.ts
  src/module/item/physical/types.ts
  src/module/item/physical/values.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
Labels: pr: enhancement

#10490 Update NPM dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#10486 Brush up automation for Blade Magus and Ivarsa's Arcane Cascade
  packs/quest-for-the-frozen-flame-bestiary/ivarsa.json
  packs/stolen-fate-bestiary/blade-magus.json
  static/lang/re-en.json
Labels: pr: data update

#10489 Add automation for Alchemical Golem's Alchemical Injection
  packs/agents-of-edgewatch-bestiary/chalky.json
  packs/extinction-curse-bestiary/darklands-alchemical-golem.json
  packs/pathfinder-bestiary/alchemical-golem.json
  packs/the-slithering-bestiary/alchemical-golem-slithering.json
  static/lang/re-en.json
Labels: pr: data update

#10491 Unify some inline damage links
  packs/agents-of-edgewatch-bestiary/boiling-tub-trap.json
  packs/deities/jin-li.json
Labels: pr: data update

#10488 Add content from the Season of Ghosts player's guide
  packs/adventure-specific-actions/seasonal-boon-close-ties.json
  packs/adventure-specific-actions/seasonal-boon-folklore-enthusiast.json
  packs/adventure-specific-actions/seasonal-boon-northridge-scholar.json
  packs/adventure-specific-actions/seasonal-boon-outskirt-dweller.json
  packs/adventure-specific-actions/seasonal-boon-southbank-traditionalist.json
  packs/adventure-specific-actions/seasonal-boon-willowshore-urchin.json
  packs/backgrounds/close-ties.json
  packs/backgrounds/folklore-enthusiast.json
  packs/backgrounds/northridge-scholar.json
  packs/backgrounds/outskirt-dweller.json
  packs/backgrounds/southbank-traditionalist.json
  packs/backgrounds/willowshore-urchin.json
  packs/campaign-effects/effect-bickering-family.json
  packs/campaign-effects/effect-seasonal-boon-outskirt-dweller.json
  static/lang/re-en.json
  static/licenses/OpenGameLicense.md
Labels: pr: data update

#10461 Add explicit options to set aura highlight/border color to user color
  src/module/actor/helpers.ts
  src/module/item/sheet/rule-element-form/aura.ts
  src/module/rules/rule-element/aura.ts
  src/module/system/schema-data-fields.ts
  src/styles/item/_index.scss
  src/styles/item/_rules.scss
  static/templates/items/rules/aura.hbs
Labels: pr: bugfix, ui/ux

#10497 Include priority in header for rule element forms
  src/module/item/sheet/rule-element-form/base.ts
  src/styles/item/_rules.scss
  static/lang/re-en.json
  static/templates/items/rules/outer.hbs
Labels: ui/ux

#10502 Fix alteration of array properties in Item Alteration RE
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
Labels: pr: bugfix

#10499 Prepare effect rule elements last
  src/module/actor/base.ts
Labels: pr: enhancement

#10505 Fix regression in item-sheet tabbed panel styling
  src/styles/item/_index.scss
Labels: pr: bugfix

#10504 Update automation for Kolo Harvan's Upward Stab
  packs/agents-of-edgewatch-bestiary/kolo-harvan.json
Labels: pr: data update

#10506 Add automation for Azer's Burning Touch
  packs/pathfinder-bestiary-3/azer.json
  packs/rage-of-elements-bestiary/munsahir-gatecrasher.json
  packs/rage-of-elements-bestiary/munsahir-trooper.json
Labels: pr: data update

#10472 Add breakthrough armor innovations
  packs/classfeatures/antimagic-plating.json
  packs/classfeatures/armor-innovation.json
  packs/classfeatures/breakthrough-innovation.json
  packs/classfeatures/camouflage-pigmentation.json
  packs/classfeatures/dense-plating.json
  packs/classfeatures/enhanced-resistance.json
  packs/classfeatures/heavy-construction.json
  packs/classfeatures/hyper-boosters.json
  packs/classfeatures/layered-mesh.json
  packs/classfeatures/phlogistonic-regulator.json
  packs/classfeatures/tensile-absorption.json
  packs/classfeatures/weapon-innovation.json
  static/icons/features/classes/enhanced-resistance.webp
  static/icons/features/classes/layered-mesh.webp
  static/lang/re-en.json
Labels: pr: data entry, pr: data update

#10508 Remove a control character in Tap Treasury
  packs/kingmaker-features/kingdom-activities/tap-treasury.json
Labels: pr: data update

#10511 Remove change to dex cap in Heavy Construction modification
  packs/classfeatures/heavy-construction.json
Labels: pr: data update

#10510 Change slugs of follow the expert to kebab case
  packs/other-effects/effect-follow-the-expert.json
Labels: pr: data update

#10507 Add self-applied effect for Duelist's Challenge
  packs/feat-effects/effect-duelists-challenge.json
  packs/feats/duelists-challenge.json
  static/lang/re-en.json
Labels: pr: data entry, pr: data update

#10512 Add inline checks for Daring Act
  packs/feats/daring-act.json
Labels: pr: data update

#10517 Remove ineffective if/merge in aura merge
  src/module/rules/rule-element/aura.ts
Labels: pr: housekeeping

#10500 Set initial value of AE-like (and similar) `priority` values in schema
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/roll-option.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: refactor

#10520 Fix regression in scrollability of item-sheet descriptions
  src/styles/item/_effect-sheet.scss
  src/styles/item/_heritage-sheet.scss
  src/styles/item/_index.scss
  src/styles/item/_sidebar.scss
  static/templates/items/sheet.hbs
Labels: pr: bugfix

#10521 Add aura effect for Bless spell
  packs/spell-effects/aura-bless.json
  packs/spells/bless.json
Labels: pr: data entry

#10516 Add light to Angelic Wings and fix fly speed
  packs/spell-effects/spell-effect-angelic-wings.json
Labels: pr: data update

#10515 Remove description from Malarunk's Cinderclaw Gauntlet attack, as it's automated
  packs/age-of-ashes-bestiary/malarunk.json
Labels: pr: data update

#10514 Add automation for Visperath's persistent acid damage
  packs/blog-bestiary/eleukas.json
Labels: pr: data update

#10513 Add resistances to Oath of the Devoted
  packs/equipment/oath-of-the-devoted.json
Labels: pr: data update

#10524 Rehide sidebar in item sheet when rules tab is active
  src/module/item/sheet/base.ts
  src/styles/item/_identify-item.scss
  src/styles/item/_index.scss
  src/styles/item/_mystification.scss
  src/styles/item/_rules.scss
  src/styles/item/_sidebar.scss
Labels: pr: bugfix

#10527 Restore hiding of "item summary" label when viewing rules tab
  src/styles/item/_index.scss
  src/styles/item/_sidebar.scss
Labels: pr: bugfix

#10496 Update Light spell effect description
  packs/spell-effects/spell-effect-light.json
Labels: pr: data update

#10523 Add Inhabit Vessel Strike automation for Stone Lion, Stone Lion Cub and fix nonlethal immunity
  packs/pathfinder-bestiary-3/stone-lion-cub.json
  packs/pathfinder-bestiary-3/stone-lion.json
  static/lang/re-en.json
Labels: pr: data update

#10528 Remove emanation data from Bless spell
  packs/spells/bless.json
Labels: pr: data update

#10533 Add icons to Lotus Walk, Whelming Scrimshaw, Alchemist's Haversack, Alchemist's Flamethrower
  packs/equipment/alchemists-flamethrower.json
  packs/equipment/alchemists-haversack.json
  packs/equipment/whelming-scrimshaw.json
  packs/spells/lotus-walk.json
Labels: pr: data update

#10526 Fix regression in item description scrolling again
  src/module/item/sheet/base.ts
  src/styles/item/_index.scss
  static/templates/items/sheet.hbs
Labels: pr: bugfix

#10535 Fix setting initial value of `RollOptionRuleElement#value`
  src/module/rules/rule-element/roll-option.ts
Labels: pr: bugfix

#10525 Support immunity to persistent damage and wounded
  src/scripts/config/iwr.ts
  static/lang/en.json
Labels: pr: enhancement

#10529 Migrate `rollActionMacro` function paramas to an object
  src/module/item/melee/document.ts
  src/module/migration/migrations/871-migrate-rollactionmacro-params.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/scripts/macros/hotbar.ts
Labels: pr: data migration, pr: refactor

#10537 Reduce duplicate fields in DamageTemplate
  src/module/actor/character/document.ts
  src/module/actor/character/elemental-blast.ts
  src/module/actor/helpers.ts
  src/module/item/affliction/document.ts
  src/module/item/spell/document.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/types.ts
  src/module/system/damage/weapon.ts
  src/module/system/text-editor.ts
  static/templates/chat/damage/damage-modifier-dialog.hbs
Labels: pr: refactor

#10539 Bump verified core compatibility version to 11.313
  static/system.json
Labels: pr: housekeeping

#8482 Move `system.schema` property to `system._migrations`
  build/lib/compendium-pack.ts
  build/lib/extractor.ts
  build/run-migration.ts
  src/module/actor/base.ts
  src/module/actor/creature/document.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/helpers.ts
  src/module/data.ts
  src/module/doc-helpers.ts
  src/module/item/base.ts
  src/module/item/data/base.ts
  src/module/item/physical/document.ts
  src/module/migration/migrations/711-heritage-items.ts
  src/module/migration/migrations/872-move-schema-property.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/migration/runner/index.ts
  static/template.json
  tests/module/migration.test.ts
Labels: pr: refactor

#10540 Correctly source material valuation data for armor
  src/module/item/physical/materials.ts
Labels: pr: bugfix

#10536 Add Osseous Defense Strike automation for Jitterbone Contortionist
  packs/book-of-the-dead-bestiary/jitterbone-contortionist.json
  static/lang/re-en.json
Labels: pr: data update

#10538 Add missing links and traits to Death Gasp
  packs/book-of-the-dead-bestiary/relictner-eroder.json
  packs/book-of-the-dead-bestiary/shadern-immolator.json
  packs/night-of-the-gray-death-bestiary/gray-gardener-enforcer.json
  packs/pathfinder-bestiary-3/angheuvore-flesh-gnawer.json
  packs/pathfinder-bestiary-3/etioling-blightmage.json
  packs/pathfinder-bestiary-3/gurgist-mauler.json
  packs/pathfinder-bestiary-3/lifeleecher-brawler.json
  packs/pfs-season-1-bestiary/iloise-5-6.json
  packs/pfs-season-1-bestiary/iloise-7-8.json
Labels: pr: data update

#10542 Rename CreateDamageFormulaParams to DamageFormulaData
  src/module/actor/character/elemental-blast.ts
  src/module/item/spell/document.ts
  src/module/system/damage/dialog.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/types.ts
  src/module/system/damage/weapon.ts
  src/module/system/text-editor.ts
  static/templates/chat/damage/damage-modifier-dialog.hbs
Labels: pr: refactor

#10532 Add automation for Aurumvorax's Tenacious Stance
  packs/pathfinder-bestiary-2/aurumvorax.json
Labels: pr: data update

#10546 Migrate actors and items as soon as they arrive from server requests
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/system/client-backend.ts
  src/scripts/hooks/load.ts
  types/foundry/client/config.d.ts
  types/foundry/client/data/abstract/client-backend.d.ts
  types/foundry/common/abstract/backend.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/types.d.ts
Labels: pr: enhancement

#10543 Keep manually disabled modifiers in the dialog even if hideIfDisabled
  src/module/system/check/dialog.ts
  src/module/system/damage/dialog.ts
Labels: pr: enhancement

#10547 Add base damage to dialog and fix adding modifiers
  src/module/system/damage/dialog.ts
  src/styles/ui/_roll-modifiers-dialog.scss
  static/lang/en.json
  static/templates/chat/damage/damage-modifier-dialog.hbs
Labels: pr: bugfix, pr: enhancement

#10548 Add schema definitions for `BaseAdventure` and `BaseAmbientSound`
  types/foundry/client/data/documents/adventure.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/index.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/adventure.d.ts
  types/foundry/common/documents/ambient-sound.d.ts
Labels: pr: types update

#10549 Add schema definition for `BaseFolder`
  types/foundry/client/data/documents/folder.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/documents/folder.d.ts
Labels: pr: types update

#10550 Enumerate creature types and make accessible per creature via getter
  src/module/actor/creature/config.ts
  src/module/actor/creature/data.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/types.ts
  src/module/actor/data/index.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/values.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/scripts/config/index.ts
Labels: pr: enhancement

#10554 Update migration-object pruning on extract to current key name
  build/lib/extractor.ts
Labels: pr: bugfix, pr: housekeeping

#10551 Emphasize some spell links
  packs/spell-effects/aura-angelic-halo.json
  packs/spell-effects/aura-bless.json
  packs/spell-effects/effect-cinder-gaze.json
Labels: pr: data update

#10552 Fix some "damage-roll" domains
  packs/pathfinder-bestiary-3/severed-head.json
  packs/rusthenge-bestiary/severed-head.json
  packs/season-of-ghosts-bestiary/noppera-bo-occultist.json
Labels: pr: data update

#10560 Make all conditions' child conditions in-memory-only
  packs/conditions/confused.json
  packs/conditions/grabbed.json
  packs/conditions/paralyzed.json
  packs/conditions/prone.json
  packs/conditions/restrained.json
  packs/conditions/unconscious.json
Labels: pr: data update

#10563 Update vite
  package-lock.json
  package.json
Labels: pr: housekeeping

#10565 Allow AE-likes to add simulated partial attribute boosts
  src/module/actor/character/document.ts
Labels: pr: enhancement

#10564 Remove no-longer-necessary migrations of documents retrieve by UUID
  src/module/actor/character/sheet.ts
  src/module/item/abc/document.ts
Labels: pr: bugfix

#10561 Level-zero-and-back Seelah (Level 1) and remove extra copy of Retributive Strike
  packs/iconics/seelah-level-1.json
Labels: pr: data update

#10562 Update Aives's Smoke Exhalation Note to use item description
  packs/extinction-curse-bestiary/aives-the-smoke-dragon.json
Labels: pr: data update

#10568 Unify some inline damage rolls
  packs/agents-of-edgewatch-bestiary/exploding-statue.json
  packs/deities/tlehar.json
  packs/paizo-pregens/ufi.json
Labels: pr: data update

#10569 Prevent bundling of translation JSON files
  src/global.ts
  src/module/canvas/status-effects.ts
  src/scripts/config/index.ts
  vite.config.ts
Labels: pr: enhancement

#10570 Move multi-dice deadly traits to NPC attacks record
  src/scripts/config/traits.ts
Labels: pr: data update

#10573 Add `Setting` `ClientDocument` class
  types/foundry/client/core/settings.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/index.d.ts
  types/foundry/client/data/documents/setting.d.ts
Labels: pr: types update

#10578 Add icons to some spells
  packs/spells/airlift.json
  packs/spells/arrow-salvo.json
  packs/spells/blastback.json
  packs/spells/blazing-armory.json
  packs/spells/cauterize-wounds.json
  packs/spells/cinder-swarm.json
Labels: pr: data update

#10577 Fix effect for Entwined Roots and add icon
  packs/spell-effects/spell-effect-entwined-roots.json
  packs/spells/entwined-roots.json
Labels: pr: data update

#10580 Simplify `RawObject` type
  src/module/actor/npc/types.ts
  src/module/actor/sheet/base.ts
  types/foundry/common/abstract/document.d.ts
Labels: pr: types update

#10584 Remove usage of `form-group-stacked` and `details-container-flex-row`
  src/styles/item/_index.scss
  src/styles/item/_spell-sheet.scss
  static/templates/items/activation-panel.hbs
  static/templates/items/affliction-details.hbs
  static/templates/items/ancestry-details.hbs
  static/templates/items/armor-details.hbs
  static/templates/items/background-details.hbs
  static/templates/items/campaign-feature-details.hbs
  static/templates/items/class-details.hbs
  static/templates/items/consumable-details.hbs
  static/templates/items/effect-sidebar.hbs
  static/templates/items/equipment-details.hbs
  static/templates/items/kit-details.hbs
  static/templates/items/melee-details.hbs
  static/templates/items/partials/ability-activation.hbs
  static/templates/items/rules/grant-item.hbs
  static/templates/items/spell-details.hbs
  static/templates/items/spell-overlay.hbs
  static/templates/items/weapon-details.hbs
  static/templates/system/tag-selector/basic.hbs
Labels: pr: refactor

#10574 Add tooltip breakdown to encumbrance and max bulks
  src/module/actor/inventory/bulk.ts
  static/templates/actors/partials/encumbrance.hbs
Labels: ui/ux

#10558 Add `AttackPopout` sheet class that can render a single strike or blast
  src/module/actor/character/attack-popouts.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/hotbar.ts
  src/scripts/macros/hotbar.ts
  src/scripts/register-templates.ts
  src/styles/actor/_index.scss
  src/styles/actor/character/_attack-popout.scss
  static/templates/actors/character/attack-popout.hbs
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/actors/character/partials/strike.hbs
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: enhancement, pr: refactor

#10566 Add support for affliction duration and stage duration
  src/module/apps/effects-panel.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/abstract-effect/helpers.ts
  src/module/item/affliction/data.ts
  src/module/item/affliction/document.ts
  src/module/item/affliction/sheet.ts
  src/module/item/condition/data.ts
  src/module/item/condition/document.ts
  src/module/item/effect/data.ts
  src/module/item/effect/document.ts
  static/template.json
  static/templates/items/affliction-details.hbs
Labels: pr: enhancement

#10556 Restore increased content link line height
  src/styles/_globals.scss
Labels: ui/ux

#10586 Fix WeaponPotency RE not adding "magical" trait to weapons
  src/module/actor/character/document.ts
Labels: pr: bugfix

#10559 Change combatant comparison to constructed object
  src/module/actor/helpers.ts
Labels: pr: bugfix

#10509 Use params.target in attack roll
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
Labels: pr: bugfix

#10587 Have `FamiliarPF2e#combatant` return the master's
  src/module/actor/familiar/document.ts
Labels: pr: enhancement

#10582 Add Q15 Actors/Hazards
  packs/pfs-season-5-bestiary/alystair-caskwater-1-2.json
  packs/pfs-season-5-bestiary/alystair-caskwater-3-4.json
  packs/pfs-season-5-bestiary/arisen-shadow-pixie.json
  packs/pfs-season-5-bestiary/arisen-umbral-pixie.json
  packs/pfs-season-5-bestiary/elite-arisen-shadow-pixie.json
  packs/pfs-season-5-bestiary/elite-arisen-umbral-pixie.json
  packs/pfs-season-5-bestiary/pit-of-lives-lost-1-2.json
  packs/pfs-season-5-bestiary/pit-of-lives-lost-3-4.json
  packs/pfs-season-5-bestiary/shadow-draugr.json
  packs/pfs-season-5-bestiary/shadowborn-slayer.json
  packs/pfs-season-5-bestiary/shadowborn-stalker.json
  packs/pfs-season-5-bestiary/vengeful-alystair-caskwater-1-2.json
  packs/pfs-season-5-bestiary/vengeful-alystair-caskwater-3-4.json
  packs/pfs-season-5-bestiary/weak-shadow-draugr.json
Labels: pr: data entry

#10588 Add schema definitions for `BaseDrawing` and `BaseFogExploration`
  types/foundry/client/data/documents/active-effect.d.ts
  types/foundry/client/data/documents/drawing-document.d.ts
  types/foundry/client/data/documents/fog-exploration.d.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/active-effect.d.ts
  types/foundry/common/documents/drawing.d.ts
  types/foundry/common/documents/fog-exploration.d.ts
  types/foundry/common/documents/macro.d.ts
Labels: pr: types update

#10583 Add input for feat other tags
  src/module/item/base.ts
  src/module/item/feat/sheet.ts
  src/module/item/sheet/base.ts
  src/styles/item/_index.scss
  static/lang/en.json
  static/templates/items/feat-details.hbs
  static/templates/items/partials/ability-activation.hbs
Labels: pr: enhancement, ui/ux

#10579 Add support for custom IWR
  src/module/actor/base.ts
  src/module/actor/creature/helpers.ts
  src/module/actor/data/base.ts
  src/module/actor/data/iwr.ts
  src/module/actor/hazard/document.ts
  src/module/actor/sheet/popups/iwr-editor.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/iwr/base.ts
  src/module/rules/rule-element/iwr/immunity.ts
  src/module/rules/rule-element/iwr/resistance.ts
  src/module/rules/rule-element/iwr/weakness.ts
  src/module/system/damage/iwr.ts
  src/scripts/config/iwr.ts
Labels: pr: enhancement

#10576 Move stamina and resolve out of attributes, refactor settings
  build/run-migration.ts
  src/global.ts
  src/module/actor/base.ts
  src/module/actor/character/crafting/formula.ts
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/familiar/document.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/document.ts
  src/module/actor/sheet/popups/identify-popup.ts
  src/module/data.ts
  src/module/dc.ts
  src/module/encounter/document.ts
  src/module/migration/migrations/651-ephemeral-focus-pool.ts
  src/module/migration/migrations/873-remove-bonus-bulk-limit.ts
  src/module/migration/migrations/874-move-stamina-stuff.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/system/action-macros/crafting/craft.ts
  src/module/system/action-macros/crafting/repair.ts
  src/module/system/settings/variant-rules.ts
  src/scripts/macros/earn-income/helpers.ts
  src/scripts/macros/rest-for-the-night.ts
  src/scripts/macros/steel-your-resolve.ts
  src/scripts/macros/xp/dialog.ts
  src/styles/settings/_homebrew.scss
  src/styles/settings/_index.scss
  src/styles/settings/_variant-rules.scss
  static/lang/en.json
  static/template.json
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/system/settings/variant-rules.hbs
  tests/setup.ts
Labels: pr: data migration, pr: refactor, ui/ux

#10581 Add icons to some spells and effects
  packs/equipment-effects/effect-batsbreath-cane.json
  packs/equipment-effects/effect-wolfjaw-armor.json
  packs/equipment/batsbreath-cane.json
  packs/equipment/wolfjaw-armor.json
  packs/spell-effects/spell-effect-mind-swap-critical-success.json
  packs/spell-effects/spell-effect-musical-accompaniment.json
  packs/spell-effects/spell-effect-take-root.json
  packs/spell-effects/spell-effect-weaken-earth.json
  packs/spells/clad-in-metal.json
  packs/spells/engrave-memory.json
  packs/spells/take-root.json
  packs/spells/weaken-earth.json
Labels: pr: data update

#10593 Fix replaceSelf in Swashbuckler's Style GrantItem
  packs/classfeatures/instinct.json
  packs/classfeatures/mystery.json
  packs/classfeatures/swashbucklers-style.json
Labels: pr: data update

#10592 Fix some broken links
  packs/equipment/blightburn-bomb-greater.json
  packs/equipment/blightburn-bomb.json
Labels: pr: data update

#10591 Update vampire physical exception to magical cold iron, magical darkwood, magical silver
  packs/blood-lords-bestiary/harmony-in-agony.json
  packs/blood-lords-bestiary/hyrune-loxenna.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/blood-lords-bestiary/vampire-guardian.json
  packs/blood-lords-bestiary/vice-chancellor-vikroti-stroh.json
  packs/blood-lords-bestiary/weeping-jack.json
  packs/book-of-the-dead-bestiary/minister-of-tumult.json
  packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
  packs/extinction-curse-bestiary/iffdahsil.json
  packs/extinction-curse-bestiary/zinogyvaz.json
  packs/kingmaker-bestiary/vordakai.json
  packs/pathfinder-bestiary/vampire-count.json
  packs/pathfinder-bestiary/vampire-mastermind.json
  packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
  packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
  packs/pfs-season-4-bestiary/evasive-vampire-count.json
  packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
  static/lang/re-en.json
Labels: pr: data update

#10595 Fix regression in styling of checkboxes on GrantItem form
  src/styles/item/_rules.scss
  static/templates/items/rules/grant-item.hbs
Labels: pr: bugfix

#10598 Fix format of several item activations
  packs/equipment/blight-breath.json
  packs/equipment/candle-of-inflamed-passions.json
  packs/equipment/grub-gloves-greater.json
  packs/equipment/nimbus-breath.json
  packs/equipment/octopus-potion-greater.json
  packs/equipment/octopus-potion-lesser.json
  packs/equipment/octopus-potion-moderate.json
  packs/equipment/sairazul-blue.json
  packs/equipment/tailors-boll.json
  packs/equipment/toxic-effluence.json
Labels: pr: data update

#10599 Fix format of Webslinger description
  packs/feats/webslinger.json
Labels: pr: data update

#10601 Fix aspect of Searing wave
  packs/adventure-specific-actions/searing-wave.json
Labels: pr: data update

#10597 Fix format of description in Prey Mutagen & Terror Spores
  packs/equipment/prey-mutagen-greater.json
  packs/equipment/prey-mutagen-lesser.json
  packs/equipment/prey-mutagen-major.json
  packs/equipment/prey-mutagen-moderate.json
  packs/equipment/terror-spores.json
Labels: pr: data update

#10594 Fix domain on Gloom Blade's RollOption
  packs/equipment/gloom-blade.json
Labels: pr: data update

#10605 Use pack query for armor innovation's initial modification choice set
  packs/classfeatures/armor-innovation.json
  packs/classfeatures/harmonic-oscillator.json
  packs/classfeatures/metallic-reactance.json
  packs/classfeatures/muscular-exoskeleton.json
  packs/classfeatures/otherworldly-protection.json
  packs/classfeatures/phlogistonic-regulator.json
  packs/classfeatures/speed-boosters.json
  packs/classfeatures/subtle-dampeners.json
  src/module/item/feat/document.ts
Labels: pr: data update

#10602 Fix some sources
  packs/pfs-season-3-bestiary/ninth-army-soldier.json
  packs/pfs-season-4-bestiary/allegro.json
  packs/pfs-season-4-bestiary/bloody-barber-thief.json
  packs/pfs-season-4-bestiary/it-pours.json
  packs/pfs-season-4-bestiary/shaitan-tactics-3-4.json
  packs/pfs-season-4-bestiary/storm-wrought-chains.json
  packs/pfs-season-4-bestiary/tempest-forged-chains.json
  packs/pfs-season-4-bestiary/wicked-reflection.json
Labels: pr: data update

#10606 Fix damage on Major Blood Bomb
  packs/equipment/blood-bomb-major.json
Labels: pr: data update

#10608 Fix regression in display of damage rows on spell sheet
  static/templates/items/spell-details.hbs
Labels: pr: bugfix

#10612 Fix missing line breaks after interact in item descriptions
  packs/equipment/kraken-bottle.json
  packs/equipment/necrobinding-serum.json
  packs/equipment/octopus-bottle.json
Labels: pr: data update

#10613 Fix malformed span tags in descriptions
  packs/equipment/amulet-of-the-third-eye.json
  packs/equipment/armbands-of-the-gorgon.json
  packs/equipment/artificer-spectacles.json
  packs/equipment/boreal-staff-greater.json
  packs/equipment/boreal-staff-major.json
  packs/equipment/boreal-staff.json
  packs/equipment/bracers-of-strength.json
  packs/equipment/doctrine-of-blissful-eternity.json
  packs/equipment/ki-channeling-beads.json
  packs/equipment/palanquin-of-night.json
  packs/equipment/silver-crescent-greater.json
  packs/equipment/silver-crescent-lesser.json
  packs/equipment/silver-crescent-moderate.json
  packs/equipment/sunflower-censer.json
  packs/equipment/tyrants-writs.json
  packs/equipment/viper-rapier.json
  packs/equipment/vultures-wing.json
  packs/equipment/wand-of-reaching-1st-level.json
  packs/equipment/wand-of-reaching-2nd-level.json
  packs/equipment/wand-of-reaching-3rd-level.json
  packs/equipment/wand-of-reaching-4th-level.json
  packs/equipment/wand-of-reaching-5th-level.json
  packs/equipment/wand-of-reaching-6th-level.json
  packs/equipment/wand-of-reaching-7th-level.json
  packs/equipment/wand-of-reaching-8th-level.json
  packs/equipment/wand-of-reaching-9th-level.json
  packs/equipment/whisperer-of-souls.json
Labels: pr: data update

#10611 Move vampire custom resistances to rule elements
  packs/blood-lords-bestiary/harmony-in-agony.json
  packs/blood-lords-bestiary/hyrune-loxenna.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/blood-lords-bestiary/vampire-guardian.json
  packs/blood-lords-bestiary/vampire-taviah.json
  packs/blood-lords-bestiary/vice-chancellor-vikroti-stroh.json
  packs/blood-lords-bestiary/weeping-jack.json
  packs/book-of-the-dead-bestiary/minister-of-tumult.json
  packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
  packs/extinction-curse-bestiary/iffdahsil.json
  packs/extinction-curse-bestiary/zinogyvaz.json
  packs/kingmaker-bestiary/vordakai.json
  packs/pathfinder-bestiary/vampire-count.json
  packs/pathfinder-bestiary/vampire-mastermind.json
  packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
  packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
  packs/pfs-season-4-bestiary/evasive-vampire-count.json
  packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
  packs/stolen-fate-bestiary/kannijo.json
  static/lang/re-en.json
Labels: pr: data update

#10610 Swap out some icons for core ones and upgrades
  packs/classfeatures/alchemical-weapon-expertise.json
  packs/classfeatures/bard-weapon-expertise.json
  packs/classfeatures/druid-weapon-expertise.json
  packs/classfeatures/fighter-weapon-mastery.json
  packs/classfeatures/psychic-weapon-expertise.json
  packs/classfeatures/ranger-weapon-expertise.json
  packs/classfeatures/thaumaturge-weapon-expertise.json
  packs/classfeatures/weapon-expertise-swashbuckler.json
  packs/classfeatures/weapon-expertise.json
  packs/classfeatures/weapon-mastery.json
  packs/classfeatures/wizard-weapon-expertise.json
  packs/equipment/axe-of-the-dwarven-lords.json
  packs/equipment/dwarven-scattergun.json
  packs/equipment/dwarven-thrower.json
  packs/equipment/dwarven-war-axe.json
  packs/equipment/flail.json
  packs/equipment/hand-crossbow.json
  packs/equipment/poisonous-dagger.json
  packs/equipment/ranseur.json
  packs/equipment/retribution-axe.json
  packs/equipment/war-flail.json
  static/icons/equipment/weapons/dwarven-war-axe.webp
  static/icons/equipment/weapons/specific-magic-weapons/retribution-axe.webp
Labels: pr: data update, pr: static assets

#10616 Remove destructuring of `MergeObjectOptions` in `mergeObject` type definition
  types/foundry/common/utils/helpers.d.ts
Labels: pr: types update

#10619 Omit "custom" type from IWR editor
  src/module/actor/sheet/popups/iwr-editor.ts
Labels: pr: bugfix

#10621 Add metal and wood domains
  static/lang/en.json
Labels: pr: data update

#10622 Add schema definition for `BaseNote`
  types/foundry/client/data/documents/note-document.d.ts
  types/foundry/common/documents/note.d.ts
Labels: pr: types update

#10617 Use `validateJoint` in crit spec RE
  src/module/rules/rule-element/crit-spec.ts
Labels: pr: refactor

#10626 Add schema definitions for `BaseCard` and `BaseCards`
  types/foundry/client/data/documents/card.d.ts
  types/foundry/client/data/documents/cards.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/index.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/documents/card.d.ts
  types/foundry/common/documents/cards.d.ts
  types/foundry/common/documents/macro.d.ts
  types/foundry/common/documents/module.d.ts
Labels: pr: types update

#10624 Update deity styling after period of global item-sheet style changes
  src/module/item/deity/sheet.ts
  src/styles/item/_deity-sheet.scss
  src/styles/item/_index.scss
  static/lang/en.json
  static/templates/items/deity-details.hbs
Labels: pr: bugfix, ui/ux

#10625 Fix resistance exceptions for Ferrous Form and Metallic Skin
  packs/feat-effects/effect-metallic-skin.json
  packs/spell-effects/spell-effect-ferrous-form.json
Labels: pr: data update

#10623 Fix some untyped poison damage
  packs/blood-lords-bestiary/bloodshroud.json
  packs/pfs-season-4-bestiary/revna-the-brave-7-8.json
  packs/strength-of-thousands-bestiary/unshadowed-koride.json
Labels: pr: data update

#10627 Add custom resistance exceptions to Dragonshard Guardian, Aliriel, Strigoi Progenitor
  packs/age-of-ashes-bestiary/dragonshard-guardian.json
  packs/shadows-at-sundown-bestiary/aliriel.json
  packs/shadows-at-sundown-bestiary/strigoi-progenitor.json
  static/lang/re-en.json
Labels: pr: data update

#10607 Normalize some differences among NPC sheets
  src/styles/actor/_index.scss
  src/styles/actor/npc/_index.scss
  src/styles/legacy/_pf2e.scss
  static/templates/actors/limited/npc-sheet.hbs
  static/templates/actors/npc/partials/sidebar.hbs
  static/templates/actors/npc/simple-sheet.hbs
Labels: pr: bugfix, ui/ux

#10630 Update Clockwork Hunter's Target Weakness to apply deadly d4
  packs/outlaws-of-alkenstar-bestiary/clockwork-hunter.json
Labels: pr: data update

#10634 Add min height to npc notes editing
  src/styles/actor/npc/_index.scss
Labels: ui/ux

#10632 Add automation for Thrown Weapon Mastery
  packs/age-of-ashes-bestiary/charau-ka-dragon-priest.json
  packs/age-of-ashes-bestiary/charau-ka.json
  packs/age-of-ashes-bestiary/malarunk.json
  packs/age-of-ashes-bestiary/racharak.json
  packs/mwangi-expanse-bestiary/charau-ka-acolyte-of-angazhan.json
  packs/mwangi-expanse-bestiary/charau-ka-butcher.json
  packs/mwangi-expanse-bestiary/charau-ka-warrior.json
Labels: pr: data update

#10638 Fix drop selector on heritage sheet
  src/module/item/heritage/sheet.ts
Labels: pr: bugfix

#10637 Wipe out most cruft in legacy style sheet
  src/styles/legacy/_pf2e.scss
Labels: pr: refactor

#10639 Add type definitions of package data models
  src/module/actor/party/kingdom/schema.ts
  src/module/item/data/base.ts
  types/foundry/common/abstract/data.d.ts
  types/foundry/common/abstract/module.d.ts
  types/foundry/common/abstract/type-data.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/item.d.ts
  types/foundry/common/documents/module.d.ts
  types/foundry/common/module.d.ts
  types/foundry/common/packages/base-module.d.ts
  types/foundry/common/packages/base-package.d.ts
  types/foundry/common/packages/base-system.d.ts
  types/foundry/common/packages/module.d.ts
  types/foundry/common/packages/sub-types.d.ts
Labels: pr: types update

#10645 Add type definitions of client package classes
  types/foundry/client/core/index.d.ts
  types/foundry/client/core/packages.d.ts
  types/foundry/client/game.d.ts
  types/foundry/common/packages/base-package.d.ts
  types/foundry/common/packages/base-system.d.ts
  types/foundry/common/packages/base-world.d.ts
  types/foundry/common/packages/module.d.ts
Labels: pr: types update

#10647 Add base `clone` method to `DataModel` type definition
  src/module/item/weapon/document.ts
  types/foundry/common/abstract/data.d.ts
  types/foundry/common/abstract/document.d.ts
  types/foundry/common/documents/wall.d.ts
Labels: pr: types update

#10646 Set icon for kris
  packs/equipment/kris.json
Labels: pr: data update

#10649 Set kinetic aura level to actor level
  packs/feat-effects/effect-kinetic-aura.json
  packs/feat-effects/effect-thermal-nimbus-cold.json
  packs/feat-effects/effect-thermal-nimbus-fire.json
  packs/feat-effects/stance-thermal-nimbus.json
Labels: pr: data update

#10650 Unify some inline damage rolls
  packs/age-of-ashes-bestiary/dragonstorm.json
  packs/age-of-ashes-bestiary/ingnovims-assistant.json
  packs/book-of-the-dead-bestiary/flood-of-spirits.json
  packs/fall-of-plaguestone/mutant-wolf.json
  packs/kingmaker-bestiary/scalding-tar-lake.json
  packs/malevolence-bestiary/ioseff-xarwin.json
  packs/outlaws-of-alkenstar-bestiary/lyzerium-bottles.json
  packs/pathfinder-bestiary-2/adult-magma-dragon-spellcaster.json
  packs/pathfinder-bestiary-2/adult-magma-dragon.json
  packs/pathfinder-bestiary-2/ancient-magma-dragon-spellcaster.json
  packs/pathfinder-bestiary-2/ancient-magma-dragon.json
  packs/pathfinder-bestiary-2/calathgar.json
  packs/pathfinder-bestiary-2/young-magma-dragon-spellcaster.json
  packs/pathfinder-bestiary-2/young-magma-dragon.json
  packs/troubles-in-otari-bestiary/collapsing-porch.json
Labels: pr: data update
