Repository foundryvtt/pf2e, pull requests merged in 2024-12, with the labels that each got.

#17565 Fix NPC Destructive Vengeance effect
  packs/bestiary-effects/effect-destructive-vengeance.json
  packs/bestiary-effects/effect-field-of-slaughter-bleed.json
  packs/bestiary-effects/effect-field-of-slaughter-keen.json
  packs/bestiary-effects/effect-ironblood-stance.json
  packs/equipment-effects/effect-stubborn-skin.json
  packs/equipment/amulet-of-kinships-strength.json
  packs/equipment/aurochs-hide-armor.json
  packs/equipment/bracers-of-pain.json
  packs/equipment/dirt-sea-in-a-jar.json
  packs/equipment/gorums-tear.json
  packs/equipment/mat-of-resilience-greater.json
  packs/equipment/mat-of-resilience.json
  packs/equipment/needle-of-undeath.json
  packs/spell-effects/spell-effect-strength-of-mind.json
  packs/spells/ancestral-winds.json
  packs/spells/entreat-thunderbird.json
  packs/spells/mutilate.json
  packs/spells/strength-of-mind.json
  packs/spells/utter-destruction.json
  packs/triumph-of-the-tusk-bestiary/army-of-mist.json
  packs/triumph-of-the-tusk-bestiary/bloodwing.json
  packs/triumph-of-the-tusk-bestiary/bugark.json
  packs/triumph-of-the-tusk-bestiary/bull-of-zagresh.json
  packs/triumph-of-the-tusk-bestiary/bull-stampede.json
  packs/triumph-of-the-tusk-bestiary/collapsing-cliff-stairs.json
  packs/triumph-of-the-tusk-bestiary/death-tower-necromancer.json
  packs/triumph-of-the-tusk-bestiary/deathless-zealot-of-zagresh.json
  packs/triumph-of-the-tusk-bestiary/graveknight-umbra.json
  packs/triumph-of-the-tusk-bestiary/great-ironbill.json
  packs/triumph-of-the-tusk-bestiary/locus-of-death.json
  packs/triumph-of-the-tusk-bestiary/locus-of-destruction.json
  packs/triumph-of-the-tusk-bestiary/locus-of-pain.json
  packs/triumph-of-the-tusk-bestiary/molog.json
  packs/triumph-of-the-tusk-bestiary/nakasha.json
  packs/triumph-of-the-tusk-bestiary/nighttime-conflagration.json
  packs/triumph-of-the-tusk-bestiary/old-herok.json
  packs/triumph-of-the-tusk-bestiary/orc-hunter.json
  packs/triumph-of-the-tusk-bestiary/orc-raider.json
  packs/triumph-of-the-tusk-bestiary/orc-spinecracker.json
  packs/triumph-of-the-tusk-bestiary/palpares.json
  packs/triumph-of-the-tusk-bestiary/paskis-nine-knives.json
  packs/triumph-of-the-tusk-bestiary/tar-baphons-shadow.json
  packs/triumph-of-the-tusk-bestiary/the-carcass-man.json
  packs/triumph-of-the-tusk-bestiary/trampling-livestock.json
  packs/triumph-of-the-tusk-bestiary/tusk-mountains-avalanche.json
  packs/triumph-of-the-tusk-bestiary/tyrants-orders.json
  packs/triumph-of-the-tusk-bestiary/umbras-rage.json
  packs/triumph-of-the-tusk-bestiary/ungukk-fleshdredge.json
  packs/triumph-of-the-tusk-bestiary/verthok-the-reaper.json
  packs/triumph-of-the-tusk-bestiary/war-auroch.json
  packs/triumph-of-the-tusk-bestiary/warcat-of-rull.json
  packs/triumph-of-the-tusk-bestiary/wingripper-wyvern-rider.json
  packs/triumph-of-the-tusk-bestiary/wraithwell.json
  packs/triumph-of-the-tusk-bestiary/yagrekash.json
  static/lang/re-en.json
Labels: pr: data update

#17567 Fix some sources
  packs/bestiary-effects/effect-field-of-slaughter-bleed.json
  packs/bestiary-effects/effect-field-of-slaughter-keen.json
  packs/bestiary-effects/effect-ironblood-stance.json
  packs/deities/tian-gods/kofusachi.json
  packs/equipment-effects/effect-stubborn-skin.json
  packs/equipment/amulet-of-kinships-strength.json
  packs/equipment/aurochs-hide-armor.json
  packs/equipment/bracers-of-pain.json
  packs/equipment/dirt-sea-in-a-jar.json
  packs/equipment/gorums-tear.json
  packs/equipment/mat-of-resilience-greater.json
  packs/equipment/mat-of-resilience.json
  packs/equipment/needle-of-undeath.json
  packs/spell-effects/spell-effect-strength-of-mind.json
  packs/spells/ancestral-winds.json
  packs/spells/entreat-thunderbird.json
  packs/spells/mutilate.json
  packs/spells/strength-of-mind.json
  packs/spells/utter-destruction.json
  packs/triumph-of-the-tusk-bestiary/army-of-mist.json
  packs/triumph-of-the-tusk-bestiary/bloodwing.json
  packs/triumph-of-the-tusk-bestiary/bugark.json
  packs/triumph-of-the-tusk-bestiary/bull-of-zagresh.json
  packs/triumph-of-the-tusk-bestiary/bull-stampede.json
  packs/triumph-of-the-tusk-bestiary/collapsing-cliff-stairs.json
  packs/triumph-of-the-tusk-bestiary/death-tower-necromancer.json
  packs/triumph-of-the-tusk-bestiary/deathless-zealot-of-zagresh.json
  packs/triumph-of-the-tusk-bestiary/graveknight-umbra.json
  packs/triumph-of-the-tusk-bestiary/great-ironbill.json
  packs/triumph-of-the-tusk-bestiary/locus-of-death.json
  packs/triumph-of-the-tusk-bestiary/locus-of-destruction.json
  packs/triumph-of-the-tusk-bestiary/locus-of-pain.json
  packs/triumph-of-the-tusk-bestiary/molog.json
  packs/triumph-of-the-tusk-bestiary/nakasha.json
  packs/triumph-of-the-tusk-bestiary/nighttime-conflagration.json
  packs/triumph-of-the-tusk-bestiary/old-herok.json
  packs/triumph-of-the-tusk-bestiary/orc-hunter.json
  packs/triumph-of-the-tusk-bestiary/orc-raider.json
  packs/triumph-of-the-tusk-bestiary/orc-spinecracker.json
  packs/triumph-of-the-tusk-bestiary/palpares.json
  packs/triumph-of-the-tusk-bestiary/paskis-nine-knives.json
  packs/triumph-of-the-tusk-bestiary/tar-baphons-shadow.json
  packs/triumph-of-the-tusk-bestiary/the-carcass-man.json
  packs/triumph-of-the-tusk-bestiary/trampling-livestock.json
  packs/triumph-of-the-tusk-bestiary/tusk-mountains-avalanche.json
  packs/triumph-of-the-tusk-bestiary/tyrants-orders.json
  packs/triumph-of-the-tusk-bestiary/umbras-rage.json
  packs/triumph-of-the-tusk-bestiary/ungukk-fleshdredge.json
  packs/triumph-of-the-tusk-bestiary/verthok-the-reaper.json
  packs/triumph-of-the-tusk-bestiary/war-auroch.json
  packs/triumph-of-the-tusk-bestiary/warcat-of-rull.json
  packs/triumph-of-the-tusk-bestiary/wingripper-wyvern-rider.json
  packs/triumph-of-the-tusk-bestiary/wraithwell.json
  packs/triumph-of-the-tusk-bestiary/yagrekash.json
Labels: pr: data update

#17566 Clean up additional Spell Effects
  packs/spell-effects/spell-effect-demon-form-babau.json
  packs/spell-effects/spell-effect-demon-form-hezrou.json
  packs/spell-effects/spell-effect-demon-form-nabasu.json
  packs/spell-effects/spell-effect-demon-form-vrock.json
  packs/spell-effects/spell-effect-devil-form-barbazu.json
  packs/spell-effects/spell-effect-devil-form-erinys.json
  packs/spell-effects/spell-effect-devil-form-osyluth.json
  packs/spell-effects/spell-effect-devil-form-sarglagon.json
  packs/spell-effects/spell-effect-dinosaur-form-ankylosaurus.json
  packs/spell-effects/spell-effect-dinosaur-form-brontosaurus.json
  packs/spell-effects/spell-effect-dinosaur-form-deinonychus.json
  packs/spell-effects/spell-effect-dinosaur-form-stegosaurus.json
  packs/spell-effects/spell-effect-dinosaur-form-triceratops.json
  packs/spell-effects/spell-effect-dinosaur-form-tyrannosaurus.json
  packs/spell-effects/spell-effect-divine-vessel.json
  packs/spell-effects/spell-effect-downpour.json
  packs/spell-effects/spell-effect-dragon-form-adamantine.json
  packs/spell-effects/spell-effect-dragon-form-conspirator.json
  packs/spell-effects/spell-effect-dragon-form-diabolic.json
  packs/spell-effects/spell-effect-dragon-form-empyreal.json
  packs/spell-effects/spell-effect-dragon-form-fortune.json
  packs/spell-effects/spell-effect-dragon-form-horned.json
  packs/spell-effects/spell-effect-dragon-form-mirage.json
  packs/spell-effects/spell-effect-dragon-form-omen.json
  packs/spell-effects/spell-effect-dragon-wings-60-feet.json
  packs/spell-effects/spell-effect-dragon-wings-own-speed.json
  packs/spell-effects/spell-effect-dread-ambience.json
  packs/spell-effects/spell-effect-eat-fire.json
Labels: pr: data update

#17564 Update Aiuvarin and Droomar to be versatile heritages
  packs/heritages/versatile-heritages/aiuvarin.json
  packs/heritages/versatile-heritages/dromaar.json
Labels: pr: data update

#17561 Move Clandestine Cloak automation from the effect to the item
  packs/equipment-effects/effect-clandestine-cloak.json
  packs/equipment/clandestine-cloak-greater.json
  packs/equipment/clandestine-cloak.json
  static/lang/re-en.json
Labels: pr: data update

#17562 Update several Archetype journal entries to use `@Embed`
  packs/journals/archetypes.json
Labels: pr: data update

#17483 fix memory leaks due to retained tagify, sortable or tooltipster instances
  src/module/actor/character/sheet.ts
  src/module/actor/character/tab-manager.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/popups/iwr-editor.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/pick-a-thing-prompt.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/item/base/sheet/rule-element-form/actor-traits.ts
  src/module/item/base/sheet/rule-element-form/aura.ts
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/item/base/sheet/rule-element-form/fast-healing.ts
  src/module/item/base/sheet/rule-element-form/roll-note.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/campaign-feature/sheet.ts
  src/module/item/deity/sheet.ts
  src/module/item/feat/sheet.ts
  src/module/item/spell/sheet.ts
  src/module/scene/sheet.ts
  src/module/system/settings/homebrew/languages.ts
  src/module/system/settings/homebrew/menu.ts
  src/scripts/macros/check-prompt/prompt.ts
Labels: pr: bugfix

#17569 Localize Magical Fortitude class feature description
  packs/classfeatures/magical-fortitude.json
  static/lang/re-en.json
Labels: pr: data update

#17572 Fix Sublime Breath Feigned Strike strike name
  packs/war-of-immortals-bestiary/sublime-breath.json
Labels: pr: data update

#17568 Condense Clay Sphere armor equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-clay-sphere-armor-greater.json
  packs/equipment-effects/effect-clay-sphere-armor-major.json
  packs/equipment-effects/effect-clay-sphere-armor.json
  packs/equipment/clay-sphere-greater.json
  packs/equipment/clay-sphere-major.json
Labels: pr: data update

#17577 Add area heightening to Thunderburst
  packs/spells/thunderburst.json
Labels: pr: data update

#17576 Remove extraneous UUID redirect for Adventure actor
  build/uuid-redirects.json
Labels: pr: data update

#17581 Remove some unnecessary roll modifiers dialog styling
  src/styles/ui/_roll-modifiers-dialog.scss
Labels: pr: foundry v13

#17579 Automate several Archfiend archetype features
  packs/actions/drain-realm.json
  packs/actions/manifest-realm.json
  packs/actions/unleash-realm.json
  packs/feat-effects/effect-don-thy-fervor.json
  packs/feat-effects/effect-drain-realm.json
  packs/feat-effects/effect-lord-of-the-fiends.json
  packs/feat-effects/effect-manifest-realm.json
  packs/feats/archfiend-dedication.json
  packs/feats/brandish-authority.json
  packs/feats/don-thy-fervor.json
  packs/feats/fiend-eternal.json
  packs/feats/imprison-foe.json
  packs/feats/lord-of-the-fiends.json
  packs/feats/manipulate-realm.json
  packs/feats/marshall-fiendish-forces.json
  packs/feats/profane-bargain.json
  packs/feats/realm-strider.json
  packs/feats/seat-of-power.json
  static/lang/re-en.json
Labels: pr: data update

#17400 Finish implementing remaster alchemist archetype including quick alchemy
  packs/actions/quick-alchemy.json
  packs/feats/alchemist-dedication.json
  packs/feats/voluminous-vials.json
  src/module/actor/character/apps/formula-picker/app.svelte
  src/module/actor/character/apps/formula-picker/app.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/helpers.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/ability/document.ts
  src/module/item/base/data/index.ts
  src/module/item/base/document.ts
  src/module/item/consumable/document.ts
  src/module/item/feat/document.ts
  src/module/item/physical/document.ts
  src/module/rules/rule-element/crafting-ability.ts
  src/module/rules/rule-element/special-resource.ts
  src/module/sheet/components/hover-icon-button.svelte
  src/module/sheet/components/item-summary.svelte
  src/module/sheet/components/item-traits.svelte
  src/module/sheet/helpers.ts
  src/styles/_tags.scss
  src/styles/actor/character/_crafting.scss
  src/styles/ui/sidebar/chat/_action.scss
  static/lang/en.json
  static/lang/re-en.json
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/chat/action/collapsed.hbs
  static/templates/chat/action/self-effect.hbs
  types/foundry/client/data/documents/client-base-mixes.d.ts
Labels: pr: enhancement

#17582 Make Biographical Eye inline immutable
  packs/feats/biographical-eye.json
Labels: pr: data update

#17574 Condense Desolation Locket armor equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-desolation-locket-armor-greater.json
  packs/equipment-effects/effect-desolation-locket-armor-major.json
  packs/equipment-effects/effect-desolation-locket-armor.json
  packs/equipment/desolation-locket-greater.json
  packs/equipment/desolation-locket-major.json
Labels: pr: data update

#17486 Replace brackets with ternaries from several spell effects
  packs/spell-effects/spell-effect-blood-ward.json
  packs/spell-effects/spell-effect-call-to-arms.json
  packs/spell-effects/spell-effect-celestial-brand.json
  packs/spell-effects/spell-effect-competitive-edge.json
  packs/spell-effects/spell-effect-extract-poison.json
  packs/spell-effects/spell-effect-heroism.json
  packs/spell-effects/spell-effect-light.json
  packs/spell-effects/spell-effect-mountain-resilience.json
  packs/spell-effects/spell-effect-mystic-armor.json
  packs/spell-effects/spell-effect-resist-energy.json
  packs/spells/celestial-brand.json
  static/lang/re-en.json
Labels: pr: data update

#17554 Automate several Apocalypse Rider archetype features
  packs/feat-effects/effect-soul-vessel-mount.json
  packs/feat-effects/effect-steal-death.json
  packs/feat-effects/effect-to-war.json
  packs/feat-effects/effect-virulent-strike.json
  packs/feat-effects/effect-wither-away.json
  packs/feats/behold-a-pale-horse.json
  packs/feats/contagious-spell.json
  packs/feats/deathless-servant.json
  packs/feats/history-of-violence.json
  packs/feats/immortal-ruin.json
  packs/feats/jousting-mount.json
  packs/feats/memory-of-nothing.json
  packs/feats/night-terror.json
  packs/feats/one-among-the-masses.json
  packs/feats/putrefaction.json
  packs/feats/soul-vessel-mount.json
  packs/feats/steal-death.json
  packs/feats/to-war.json
  packs/feats/virulent-strike.json
  packs/feats/wither-away.json
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#17583 Move versatile vials scaling to physical item rather than the feature
  packs/classfeatures/versatile-vials.json
  packs/equipment/versatile-vial.json
Labels: pr: data update

#17571 Allow Class Might effect to select any attribute
  packs/other-effects/effect-ancestral-might.json
  packs/other-effects/effect-aura-of-protection.json
  packs/other-effects/effect-called-foe.json
  packs/other-effects/effect-catch-your-breath.json
  packs/other-effects/effect-class-might.json
  packs/other-effects/effect-critical-moment.json
  packs/other-effects/effect-daring-attempt.json
  packs/other-effects/effect-desperate-swing.json
  packs/other-effects/effect-endure-the-onslaught.json
  packs/other-effects/effect-fluid-motion.json
  packs/other-effects/effect-impossible-shot.json
  packs/other-effects/effect-rage-and-fury.json
  packs/other-effects/effect-spark-of-courage.json
  packs/other-effects/effect-strike-true.json
  static/lang/re-en.json
Labels: pr: data update

#17570 Add inline links to Cat's Eye Elixir
  packs/equipment/blood-sight-elixir-greater.json
  packs/equipment/blood-sight-elixir-lesser.json
  packs/equipment/blood-sight-elixir-major.json
  packs/equipment/blood-sight-elixir-moderate.json
  packs/equipment/cats-eye-elixir.json
  packs/equipment/unsullied-blood-greater.json
  packs/equipment/unsullied-blood-lesser.json
  packs/equipment/unsullied-blood-major.json
  packs/equipment/unsullied-blood-moderate.json
  packs/paizo-pregens/kangir.json
  packs/paizo-pregens/yacob.json
  packs/prey-for-death-bestiary/shirota.json
  packs/rollable-tables/2nd-level-consumables.json
Labels: pr: data update, pr: static assets

#17556 Update Domains journals
  packs/deities/covenants/faith-in-the-fallen.json
  packs/deities/covenants/rivethun.json
  packs/journals/domains.json
Labels: pr: data update

#17575 Add Howl of the Wild feats to Beastmaster Dedication Journal entry and add embeds to select journal entries
  packs/journals/archetypes.json
Labels: pr: data update

#17590 Add journal links to Battle Harbinger Dedication and Mortal Herald Dedication feats
  packs/feats/battle-harbinger-dedication.json
  packs/feats/mortal-herald-dedication.json
Labels: pr: data update

#17586 Allow setting quantity for daily crafting abilities instead of redragging
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/crafting/crafting.ts
  src/module/actor/character/crafting/types.ts
  static/templates/actors/character/tabs/crafting.hbs
Labels: pr: enhancement

#16884 Convert CompendiumBrowser to ApplicationV2
  package-lock.json
  package.json
  src/global.ts
  src/module/actor/character/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/compendium-browser/browser.ts
  src/module/apps/compendium-browser/components/app.svelte
  src/module/apps/compendium-browser/components/browser-tab.svelte
  src/module/apps/compendium-browser/components/filters.svelte
  src/module/apps/compendium-browser/components/filters/checkboxes.svelte
  src/module/apps/compendium-browser/components/filters/filter-container.svelte
  src/module/apps/compendium-browser/components/filters/level.svelte
  src/module/apps/compendium-browser/components/filters/partials/clear-filter-button.svelte
  src/module/apps/compendium-browser/components/filters/partials/traits-select.svelte
  src/module/apps/compendium-browser/components/filters/ranges.svelte
  src/module/apps/compendium-browser/components/filters/traits.svelte
  src/module/apps/compendium-browser/components/result-item.svelte
  src/module/apps/compendium-browser/data.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/loader.ts
  src/module/apps/compendium-browser/settings.ts
  src/module/apps/compendium-browser/tabs/action.ts
  src/module/apps/compendium-browser/tabs/base.svelte.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/campaign-feature.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
  src/module/apps/compendium-browser/tabs/spell.ts
  src/module/apps/sidebar/item-directory.ts
  src/scripts/register-templates.ts
  src/scripts/set-game-pf2e.ts
  src/styles/main.scss
  src/styles/packs/_filter-slider.scss
  src/styles/packs/_index.scss
  src/styles/packs/_nav.scss
  src/styles/packs/_settings.scss
  src/styles/packs/_tab.scss
  src/styles/system/_compendium-browser-settings.scss
  src/styles/system/_index.scss
  src/styles/system/license-viewer/_index.scss
  static/lang/en.json
  static/templates/compendium-browser/compendium-browser.hbs
  static/templates/compendium-browser/filters.hbs
  static/templates/compendium-browser/partials/action.hbs
  static/templates/compendium-browser/partials/bestiary.hbs
  static/templates/compendium-browser/partials/equipment.hbs
  static/templates/compendium-browser/partials/feat.hbs
  static/templates/compendium-browser/partials/hazard.hbs
  static/templates/compendium-browser/partials/spell.hbs
  static/templates/compendium-browser/settings/pack-settings.hbs
  static/templates/compendium-browser/settings/settings.hbs
  static/templates/compendium-browser/settings/source-settings.hbs
  types/foundry/client-esm/applications/api/application.d.ts
  types/foundry/client-esm/applications/api/handlebars-application.ts
Labels: pr: enhancement, pr: refactor

#17592 Add missing roll option to Skybearer's Belt immanence benefit predicate
  packs/classfeatures/skybearers-belt.json
  packs/iconics/nahoa-level-1.json
  packs/iconics/nahoa-level-3.json
  packs/iconics/nahoa-level-5.json
Labels: pr: data update

#17600 Condense Dragon Turtle Scale equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-dragon-turtle-scale-greater.json
  packs/equipment-effects/effect-dragon-turtle-scale.json
  packs/equipment/dragon-turtle-scale-greater.json
Labels: pr: data update

#17599 Apply `@Embed` to additional entries in the Archetype Journal
  packs/journals/archetypes.json
Labels: pr: data update

#17595 Move Quick-Tempered effects to its Note
  packs/actions/quick-tempered.json
  packs/feat-effects/effect-rage-temporary-hit-points-immunity.json
Labels: pr: data update

#17593 Add Oracle Mysteries to the Domains Journal
  packs/journals/domains.json
Labels: pr: data update

#17598 Add Left-Hand Blood Effect
  packs/feat-effects/effect-left-hand-blood.json
  packs/feats/left-hand-blood.json
Labels: pr: data update

#17597 Ensure GM-only browser tabs are only viewable by GMs
  src/module/actor/character/apps/abc-picker/app.svelte
  src/module/actor/character/apps/formula-picker/app.svelte
  src/module/apps/compendium-browser/browser.ts
  src/module/apps/compendium-browser/components/browser-tab.svelte
  src/module/apps/compendium-browser/components/filters.svelte
  src/module/apps/compendium-browser/components/filters/level.svelte
  src/module/apps/compendium-browser/tabs/base.svelte.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
Labels: pr: enhancement

#17605 Condense Exsanguinating Ammunition equipment effect
  build/uuid-redirects.json
  packs/equipment-effects/effect-exsanguinating-ammunition-greater.json
  packs/equipment-effects/effect-exsanguinating-ammunition-major.json
  packs/equipment-effects/effect-exsanguinating-ammunition.json
  packs/equipment/exsanguinating-ammunition-greater.json
  packs/equipment/exsanguinating-ammunition-major.json
Labels: pr: data update

#17587 Update additional Spell Effect descriptions
  packs/spell-effects/spell-effect-element-embodied-air.json
  packs/spell-effects/spell-effect-element-embodied-earth.json
  packs/spell-effects/spell-effect-element-embodied-fire.json
  packs/spell-effects/spell-effect-element-embodied-metal.json
  packs/spell-effects/spell-effect-element-embodied-water.json
  packs/spell-effects/spell-effect-element-embodied-wood.json
  packs/spell-effects/spell-effect-elemental-absorption.json
  packs/spell-effects/spell-effect-elemental-gift.json
  packs/spell-effects/spell-effect-elephant-form.json
  packs/spell-effects/spell-effect-enlarge.json
  packs/spell-effects/spell-effect-entangling-flora.json
  packs/spell-effects/spell-effect-entropic-wheel.json
  packs/spell-effects/spell-effect-entwined-roots.json
  packs/spell-effects/spell-effect-envenom-companion.json
  packs/spell-effects/spell-effect-evolution-surge.json
  packs/spell-effects/spell-effect-false-vitality.json
  packs/spell-effects/spell-effect-ferrous-form.json
  packs/spell-effects/spell-effect-fey-form-dryad.json
  packs/spell-effects/spell-effect-fey-form-elananx.json
  packs/spell-effects/spell-effect-fey-form-naiad.json
  packs/spell-effects/spell-effect-fey-form-redcap.json
  packs/spell-effects/spell-effect-fey-form-unicorn.json
  packs/spell-effects/spell-effect-fiery-body.json
  packs/spell-effects/spell-effect-fire-shield.json
  packs/spell-effects/spell-effect-flame-barrier.json
  packs/spell-effects/spell-effect-flashy-disappearance.json
  packs/spell-effects/spell-effect-flicker.json
  packs/spell-effects/spell-effect-fly.json
  packs/spell-effects/spell-effect-foresight.json
Labels: pr: data update

#17606 Correct Spirit Striking localization in Exemplar Class journal entry
  packs/journals/classes.json
Labels: pr: data update

#17591 Add Crafting Ability and Special Resource for Alchemist's Quick Alchemy
  packs/classfeatures/quick-alchemy.json
  packs/classfeatures/versatile-vials.json
  packs/feats/alchemist-dedication.json
Labels: pr: data update

#17596 Replace Blast Resistance Note RE with DoS adjustment, Remove Tide Hardened Note RE
  packs/feats/blast-resistance.json
  packs/feats/tide-hardened.json
  static/lang/re-en.json
Labels: pr: data update

#17601 Brush up Zephyr Guard Archetype
  build/uuid-redirects.json
  packs/feat-effects/effect-decry-thief-critical-success.json
  packs/feat-effects/effect-decry-thief-success.json
  packs/feat-effects/effect-decry-thief.json
  packs/feat-effects/effect-unfazed-assessment.json
  packs/feats/decry-thief.json
  packs/feats/flicker.json
  packs/feats/know-the-beat.json
  packs/feats/relentless-disarm.json
  packs/feats/unfazed-assessment.json
  packs/feats/zephyr-guard-dedication.json
Labels: pr: data update

#17609 Add champion trait to Champion's Aura class feature
  packs/classfeatures/champions-aura.json
Labels: pr: data update

#14960 Show post roll options in the inspector and include in notes
  src/module/chat-message/data.ts
  src/module/chat-message/roll-inspector.ts
  src/module/system/check/check.ts
  src/module/system/damage/damage.ts
  src/styles/ui/sidebar/chat/_roll-inspector.scss
  static/lang/en.json
  static/templates/chat/roll-inspector.hbs
Labels: pr: enhancement

#14957 Add description for damage and modifier roll options in the roll inspector
  src/module/chat-message/roll-inspector.ts
  src/module/item/base/sheet/sheet.ts
  src/styles/tooltip/_index.scss
  static/lang/en.json
  static/templates/chat/roll-inspector.hbs
  static/templates/system/roll-options-tooltip.hbs
Labels: pr: enhancement

#17616 Talon Stance now uses Talon image
  packs/feat-effects/stance-talon-stance.json
Labels: pr: data update

#17613 Add condition links to Curse of Turbulent Moments
  packs/classfeatures/curse-of-turbulent-moments.json
Labels: pr: data update

#17620 Correct Greatpick price
  packs/equipment/greatpick.json
Labels: pr: data update

#17614 Use AdjustDegreeOfSuccess rule element on Ageless Patience and localize its Note
  packs/feats/ageless-patience.json
  static/lang/re-en.json
Labels: pr: data update

#17623 Fix typo in Manifest Realm's template label
  packs/actions/manifest-realm.json
Labels: pr: data update

#17622 Add support for aura effect resolvables and parent options
  src/module/actor/base.ts
  src/module/actor/types.ts
  src/module/rules/rule-element/aura.ts
Labels: pr: enhancement

#17629 Remove effects from Eye of the Unseen
  packs/equipment-effects/effect-eye-of-the-unseen-greater.json
  packs/equipment-effects/effect-eye-of-the-unseen.json
  packs/equipment/eye-of-the-unseen-greater.json
  packs/equipment/eye-of-the-unseen.json
Labels: pr: data update

#17630 Round down max slots in crafting abilities
  src/module/rules/rule-element/crafting-ability.ts
Labels: pr: bugfix

#17611 Rename Hellknight Signifier to Signifer in feat prerequisites
  packs/crown-of-the-kobold-king-bestiary/dark-talon-kobold.json
  packs/crown-of-the-kobold-king-bestiary/kieragan-skross.json
  packs/equipment/hellknight-half-plate.json
  packs/feats/advanced-order-training.json
  packs/feats/gaze-of-veracity.json
Labels: pr: data update

#17634 Hide disabled Bloody Debilitation dice in Debilitating Strike feature
  packs/classfeatures/debilitating-strike.json
Labels: pr: data update

#17621 Correct Pilgrim's Token price
  packs/equipment/pilgrims-token.json
Labels: pr: data update

#17631 Add effects for Manifest Will and Multifaceted Will
  packs/feat-effects/effect-multifaceted-will.json
  packs/feats/multifaceted-will.json
  packs/spell-effects/aura-manifest-will.json
  packs/spell-effects/spell-effect-manifest-will.json
  packs/spells/manifest-will.json
Labels: pr: data update

#17615 Update even more Spell Effect descriptions
  packs/spell-effects/spell-effect-forge-critical-failure.json
  packs/spell-effects/spell-effect-fortifying-brew.json
  packs/spell-effects/spell-effect-glass-shield.json
  packs/spell-effects/spell-effect-glimpse-weakness.json
  packs/spell-effects/spell-effect-gravity-weapon.json
  packs/spell-effects/spell-effect-guidance.json
  packs/spell-effects/spell-effect-haste.json
  packs/spell-effects/spell-effect-healers-blessing.json
  packs/spell-effects/spell-effect-hymn-of-healing.json
  packs/spell-effects/spell-effect-ill-omen.json
  packs/spell-effects/spell-effect-infectious-enthusiasm.json
  packs/spell-effects/spell-effect-infuse-vitality.json
  packs/spell-effects/spell-effect-inscrutable-mask.json
  packs/spell-effects/spell-effect-insect-form-ant.json
  packs/spell-effects/spell-effect-insect-form-centipede.json
  packs/spell-effects/spell-effect-insect-form-mantis.json
  packs/spell-effects/spell-effect-insect-form-scorpion.json
  packs/spell-effects/spell-effect-insect-form-spider.json
  packs/spell-effects/spell-effect-iron-gut-3rd-level.json
  packs/spell-effects/spell-effect-iron-gut.json
  packs/spell-effects/spell-effect-knock.json
  packs/spells/fortifying-brew.json
  static/lang/re-en.json
Labels: pr: data update

#17636 Condense Flaming Star equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-flaming-star-armor-greater.json
  packs/equipment-effects/effect-flaming-star-armor-major.json
  packs/equipment-effects/effect-flaming-star-armor.json
  packs/equipment-effects/effect-flaming-star-weapon-greater.json
  packs/equipment-effects/effect-flaming-star-weapon-major.json
  packs/equipment-effects/effect-flaming-star-weapon.json
  packs/equipment/flaming-star-greater.json
  packs/equipment/flaming-star-major.json
Labels: pr: data update

#17635 Update additional deities with details from Divine Mysteries Web Supplement
  packs/deities/empyreal-lords/lalaci.json
  packs/deities/empyreal-lords/lorris.json
  packs/deities/empyreal-lords/neshen.json
  packs/deities/empyreal-lords/olheon.json
  packs/deities/empyreal-lords/pulura.json
  packs/deities/empyreal-lords/ragathiel.json
  packs/deities/empyreal-lords/reymenda.json
  packs/deities/empyreal-lords/seramaydiel.json
  packs/deities/empyreal-lords/soralyon.json
  packs/deities/empyreal-lords/tanagaar.json
  packs/deities/empyreal-lords/uskyeria.json
  packs/deities/empyreal-lords/valani.json
  packs/deities/empyreal-lords/vildeis.json
  packs/deities/empyreal-lords/ylimancha.json
  packs/deities/empyreal-lords/zohls.json
  packs/deities/giant-gods/aegirran.json
  packs/deities/giant-gods/bergelmir.json
  packs/deities/giant-gods/fandarra.json
  packs/deities/giant-gods/haggakal.json
  packs/deities/giant-gods/minderhal.json
  packs/deities/giant-gods/skode.json
  packs/deities/giant-gods/skrymir.json
  packs/deities/giant-gods/thremyr.json
  packs/deities/giant-gods/tjasse.json
  packs/deities/giant-gods/urazra.json
  packs/deities/giant-gods/yrmidar.json
  packs/deities/giant-gods/zursvaater.json
Labels: pr: data update

#17603 Add more `@Embed` localizations to the Archetype journal and brush up Dual Weapon Reload feat
  packs/feats/dual-weapon-reload.json
  packs/journals/archetypes.json
Labels: pr: data update

#17637 Add crane wing attack penalty to Crane Flutter
  packs/feat-effects/stance-crane-stance.json
  packs/feats/crane-flutter.json
Labels: pr: data update

#17640 Update Gale Blast heightening to match Player Core 2
  packs/spells/gale-blast.json
Labels: pr: data update

#17643 Remove trailing whitespace in many pack entries
  packs/feats/animal-trainer-dedication.json
  packs/feats/blade-of-law.json
  packs/feats/deaths-door.json
  packs/feats/everstand-strike.json
  packs/feats/font-of-knowledge.json
  packs/feats/harrying-strike.json
  packs/feats/hells-armaments.json
  packs/feats/mask-familiar.json
  packs/feats/masked-casting.json
  packs/feats/mature-trained-companion.json
  packs/feats/surreptitious-spellcaster.json
  packs/feats/survivor-of-desolation.json
  packs/feats/wild-witchs-armaments.json
  packs/kingmaker-bestiary/breath-of-despair.json
  packs/kingmaker-bestiary/numerian-radiant-warden.json
  packs/kingmaker-bestiary/prank-workshop-mitflit.json
  packs/kingmaker-bestiary/the-wriggling-man.json
  packs/pathfinder-bestiary-2/radiant-warden.json
  packs/pfs-season-4-bestiary/4-99/elven-hunter.json
  packs/pfs-season-5-bestiary/5-10/metal-rascal.json
  packs/pfs-season-5-bestiary/5-13/enraged-shurrizih.json
  packs/pfs-season-5-bestiary/5-13/shurrizih.json
  packs/pfs-season-6-bestiary/6-00/enava.json
  packs/season-of-ghosts-bestiary/rin.json
  packs/seven-dooms-for-sandpoint-bestiary/ghast-cultist.json
  packs/seven-dooms-for-sandpoint-bestiary/jervis-stoot.json
  packs/sky-kings-tomb-bestiary/bronwyl-holloward.json
  packs/sky-kings-tomb-bestiary/hryngar-breccia-squad.json
  packs/sky-kings-tomb-bestiary/hryngar-kings-agent.json
  packs/wardens-of-wildwood-bestiary/druulbach.json
  packs/wardens-of-wildwood-bestiary/old-thornbarker.json
  packs/wardens-of-wildwood-bestiary/zasir.json
Labels: pr: data update

#17642 Add embeds to additional entries in the Archetype journal
  packs/journals/archetypes.json
Labels: pr: data update

#17610 Brush up Wild Mimic Dedication
  packs/feat-effects/effect-wild-mimic-dedication.json
  packs/feats/electrogenesis.json
  packs/feats/emergency-regeneration.json
  packs/feats/petrifying-gaze-mimicry.json
  packs/feats/primal-proportions.json
  packs/feats/rend-mimicry.json
  packs/feats/roar-mimicry.json
  packs/feats/trample-mimicry.json
  packs/feats/wild-mimic-dedication.json
Labels: pr: data update

#17618 Implement natural 19 DoS adjustments on some monsters
  packs/age-of-ashes-bestiary/carnivorous-crystal.json
  packs/kingmaker-bestiary/lesser-jabberwock.json
  packs/pathfinder-bestiary-2/jabberwock.json
  packs/pathfinder-monster-core/guthallath.json
Labels: pr: data update

#17627 Fix description formatting for Shadow Leap
  packs/fists-of-the-ruby-phoenix-bestiary/bul-gae.json
  packs/stolen-fate-bestiary/mighty-bul-gae.json
Labels: pr: data update

#17628 Update Alchemist and Poisoner's Crafting Ability rule elements
  packs/classfeatures/advanced-alchemy.json
  packs/feats/advanced-efficient-alchemy.json
  packs/feats/advanced-poisoncraft.json
  packs/feats/efficient-alchemy-alchemist.json
  packs/feats/efficient-alchemy-paragon.json
  packs/feats/poisoner-dedication.json
Labels: pr: data update

#17624 Add Infectious Melody spell effect variants
  packs/spell-effects/spell-effect-infectious-melody-critical-failure.json
  packs/spell-effects/spell-effect-infectious-melody-failure.json
  packs/spell-effects/spell-effect-infectious-melody-success.json
  packs/spell-effects/spell-effect-infectious-melody.json
  packs/spells/infectious-melody.json
Labels: pr: data update

#17633 Add applicable modifiers to battle form unarmed modifier comparison
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: bugfix

#17649 Add DC by Level Performance check for Lingering Composition
  packs/spells/lingering-composition.json
Labels: pr: data update

#17625 Localize Magical Fortitude class feature text and update description text for Arcane Thesis and Mystery class features
  packs/classfeatures/arcane-thesis.json
  packs/classfeatures/mystery.json
  packs/journals/classes.json
Labels: pr: data update

#17607 Automate several Ascended Celestial archetype features
  packs/actions/bless-ally.json
  packs/feat-effects/effect-abjure-harm.json
  packs/feat-effects/effect-aegis-for-the-innocent.json
  packs/feat-effects/effect-ascend.json
  packs/feat-effects/effect-ascended-celestial-nimbus.json
  packs/feat-effects/effect-bless-ally.json
  packs/feat-effects/effect-celestial-armaments-allies.json
  packs/feat-effects/effect-celestial-armaments.json
  packs/feat-effects/effect-channel-divine-spark.json
  packs/feat-effects/effect-shining-glory.json
  packs/feats/a-thousand-cries-for-help.json
  packs/feats/abjure-harm.json
  packs/feats/aegis-for-the-innocent.json
  packs/feats/army-of-one.json
  packs/feats/ascend.json
  packs/feats/ascended-celestial-dedication.json
  packs/feats/celestial-armaments.json
  packs/feats/celestial-rebirth.json
  packs/feats/channel-divine-spark.json
  packs/feats/cleansing-spell.json
  packs/feats/consult-celestial-advisor.json
  packs/feats/eyes-unclouded.json
  packs/feats/scouring-spark.json
  packs/feats/shining-glory.json
  static/lang/re-en.json
Labels: pr: data update

#17644 Fix action cost of Steal Face
  packs/highhelm-bestiary/graul.json
  packs/pathfinder-bestiary-2/leucrotta.json
  packs/war-of-immortals-bestiary/vulot.json
Labels: pr: data update

#17647 Add prerequisites to harrower feats
  packs/feats/benevolent-spirit-deck.json
  packs/feats/experienced-harrower.json
  packs/feats/harrow-casting.json
  packs/feats/harrow-ritualist.json
  packs/feats/reading-the-signs.json
  packs/feats/restore-omen.json
  packs/feats/vengeful-spirit-deck.json
Labels: pr: data update

#17650 Revert "Add DC by Level Performance check for Lingering Composition"
  packs/spells/lingering-composition.json
Labels: pr: data update

#17654 Update additional Deity descriptions with Divine Mysteries Web Supplement details
  packs/deities/goblin-gods/cong.json
  packs/deities/goblin-gods/hadregash.json
  packs/deities/goblin-gods/lurlup.json
  packs/deities/goblin-gods/teki-stronggut.json
  packs/deities/goblin-gods/venkelvore.json
  packs/deities/goblin-gods/zarongel.json
  packs/deities/goblin-gods/zogmugot.json
  packs/deities/goblin-gods/zugero.json
  packs/deities/in-memoriam/alazhra.json
  packs/deities/in-memoriam/anubis.json
  packs/deities/in-memoriam/aroden.json
  packs/deities/in-memoriam/cernunnos.json
  packs/deities/in-memoriam/gorum.json
  packs/deities/in-memoriam/grundinnar.json
  packs/deities/in-memoriam/gyronna.json
  packs/deities/in-memoriam/horus.json
  packs/deities/in-memoriam/isis.json
  packs/deities/in-memoriam/maat.json
  packs/deities/in-memoriam/mestama.json
  packs/deities/in-memoriam/osiris.json
  packs/deities/in-memoriam/ra.json
  packs/deities/in-memoriam/smiad.json
  packs/deities/in-memoriam/sturovenen.json
  packs/deities/in-memoriam/thoth.json
  packs/deities/in-memoriam/ydersius.json
  packs/deities/infernal-dukes/bifrons.json
  packs/deities/infernal-dukes/furcas.json
  packs/deities/infernal-dukes/haborym.json
  packs/deities/infernal-dukes/malthus.json
  packs/deities/infernal-dukes/nergal.json
  packs/deities/infernal-dukes/titivilus.json
  packs/deities/infernal-dukes/ussharassim.json
  packs/deities/infernal-dukes/vapula.json
Labels: pr: data update

#17653 Add search filter to inventory and make minor style adjustments
  src/module/actor/character/sheet.ts
  src/styles/actor/_inventory.scss
  src/styles/actor/character/_inventory.scss
  static/lang/en.json
  static/templates/actors/character/tabs/inventory.hbs
  static/templates/actors/partials/coinage.hbs
  static/templates/actors/partials/encumbrance.hbs
  static/templates/actors/partials/inventory.hbs
Labels: pr: enhancement, ui/ux

#17648 Allow more characters to fit in transfer dialog quantity field
  src/styles/actor/_item-transfer-dialog.scss
Labels: ui/ux

#17657 Check subdirectories when processing UUID redirects during build
  build/uuid-redirects.json
  package-lock.json
  package.json
  vite.config.ts
Labels: pr: housekeeping

#17656 Move management of objects requiring explicit memory deallocation to mutation observer
  build/lib/compendium-pack.ts
  build/lib/foundry-utils.ts
  src/module/actor/character/apps/attribute-builder.ts
  src/module/actor/character/document.ts
  src/module/actor/character/helpers.ts
  src/module/actor/character/sheet.ts
  src/module/actor/character/tab-manager.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/helpers.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/helpers.ts
  src/module/actor/sheet/popups/iwr-editor.ts
  src/module/apps/pick-a-thing-prompt.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/damage-taken.ts
  src/module/item/base/sheet/rule-element-form/actor-traits.ts
  src/module/item/base/sheet/rule-element-form/aura.ts
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/item/base/sheet/rule-element-form/fast-healing.ts
  src/module/item/base/sheet/rule-element-form/roll-note.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/campaign-feature/sheet.ts
  src/module/item/condition/document.ts
  src/module/item/deity/sheet.ts
  src/module/item/feat/sheet.ts
  src/module/item/spell/sheet.ts
  src/module/migration/runner/base.ts
  src/module/rules/rule-element/effect-spinoff/spinoff.ts
  src/module/scene/sheet.ts
  src/module/system/check/check.ts
  src/module/system/html-elements/tagify-tags.ts
  src/module/system/settings/homebrew/languages.ts
  src/module/system/settings/homebrew/menu.ts
  src/scripts/hooks/ready.ts
  src/scripts/hooks/setup.ts
  src/scripts/macros/check-prompt/prompt.ts
  src/util/destroyables.ts
  src/util/index.ts
  src/util/misc.ts
  src/util/tags.ts
  types/foundry/client-esm/applications/elements/form-element.d.ts
Labels: pr: refactor

#17659 Update styling of known formulas
  src/module/actor/character/sheet.ts
  src/styles/actor/character/_crafting.scss
  static/lang/en.json
  static/templates/actors/character/tabs/crafting.hbs
Labels: ui/ux

#17661 Brush up additional Spell Effect descriptions
  packs/spell-effects/spell-effect-fungal-infestation.json
  packs/spell-effects/spell-effect-garden-of-death-critical-success.json
  packs/spell-effects/spell-effect-gecko-grip.json
  packs/spell-effects/spell-effect-girzanjes-march.json
  packs/spell-effects/spell-effect-hidden-mind.json
  packs/spell-effects/spell-effect-hidebound.json
  packs/spell-effects/spell-effect-imitate-fauna.json
  packs/spell-effects/spell-effect-life-boost.json
  packs/spell-effects/spell-effect-lifelink-surge.json
  packs/spell-effects/spell-effect-magic-hide.json
  packs/spell-effects/spell-effect-malignant-sustenance.json
  packs/spell-effects/spell-effect-mimic-undead.json
  packs/spell-effects/spell-effect-mind-of-menace.json
  packs/spell-effects/spell-effect-mind-swap-critical-success.json
  packs/spell-effects/spell-effect-mirecloak.json
  packs/spell-effects/spell-effect-monstrosity-form-cave-worm.json
  packs/spell-effects/spell-effect-monstrosity-form-phoenix.json
  packs/spell-effects/spell-effect-monstrosity-form-sea-serpent.json
  packs/spell-effects/spell-effect-moon-frenzy.json
  packs/spell-effects/spell-effect-nature-incarnate.json
  packs/spell-effects/spell-effect-necromancers-generosity.json
  packs/spell-effects/spell-effect-necrotize-legs.json
  packs/spell-effects/spell-effect-oaken-resilience.json
  packs/spell-effects/spell-effect-object-memory-weapon.json
Labels: pr: data update

#17660 Show common language first in party sheet
  src/module/actor/party/sheet.ts
Labels: pr: enhancement

#17662 Standardize action icons
  packs/actions/accept-echo.json
  packs/actions/anadi-venom.json
  packs/actions/arcane-cascade.json
  packs/actions/basic-actions/raise-a-shield.json
  packs/actions/blizzard-evasion.json
  packs/actions/channel-elements.json
  packs/actions/daydream-trance.json
  packs/actions/devise-a-stratagem.json
  packs/actions/entitys-resurgence.json
  packs/actions/rage.json
  packs/actions/rewrite-fate.json
  packs/actions/swirl-crimson-shroud.json
  packs/actions/tail-toxin.json
  packs/actions/tenacious-stance.json
  packs/actions/unleash-psyche.json
  packs/bestiary-effects/effect-icy-protection.json
  packs/bestiary-effects/effect-shackling-cold.json
  packs/bestiary-effects/effect-winters-bite.json
  packs/pfs-season-6-bestiary/6-08/high-matriarch-szvetneera.json
  packs/pfs-season-6-bestiary/6-08/king-rimesnap.json
  packs/pfs-season-6-bestiary/6-08/matriarch-szvetneera.json
  packs/pfs-season-6-bestiary/6-08/rimesnap.json
  packs/pfs-season-6-bestiary/6-08/ulfen-bodyguard.json
  packs/pfs-season-6-bestiary/6-08/ulfen-captain.json
  packs/pfs-season-6-bestiary/6-08/ulfen-witchguard.json
  packs/pfs-season-6-bestiary/6-08/zombie-crow-flock.json
  packs/pfs-season-6-bestiary/6-08/zombie-crow-swarm.json
  packs/pfs-season-6-bestiary/_folders.json
Labels: pr: data update

#17655 Apply `@Embed` to additional entries in the Archetype journal
  packs/feats/ghost-eater-dedication.json
  packs/feats/silent-sting.json
  packs/journals/archetypes.json
Labels: pr: data update

#17632 Automate several Beast Lord archetype features
  packs/feat-effects/effect-chosen-ward.json
  packs/feat-effects/effect-creature-of-myth-energy-aegis.json
  packs/feat-effects/stance-unified-stance.json
  packs/feats/bat-around.json
  packs/feats/chosen-ward.json
  packs/feats/creature-of-myth.json
  packs/feats/defend-our-union.json
  packs/feats/guarded-domain.json
  packs/feats/one-life-two-vessels.json
  packs/feats/pack-of-the-beast-lord.json
  packs/feats/unified-stance.json
  packs/feats/we-are-one.json
  packs/feats/you-cant-hide-from-us.json
  static/lang/re-en.json
Labels: pr: data update

#17665 Add window icon to compendium browser
  src/module/apps/compendium-browser/browser.ts
Labels: ui/ux

#17668 Hide quick alchemy toggle if there are no old alchemist abilities
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#17669 Add formula picker to prepared crafting abilities such as advanced alchemy
  src/module/actor/base.ts
  src/module/actor/character/apps/formula-picker/app.svelte
  src/module/actor/character/apps/formula-picker/app.ts
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/crafting/crafting.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/chat-message/helpers.ts
  src/module/sheet/components/hover-icon-button.svelte
  src/styles/actor/character/_crafting.scss
  static/lang/en.json
  static/templates/actors/character/tabs/crafting.hbs
Labels: pr: enhancement

#17652 Condense Mantle of the Frozen Heart spell effect
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart-ice-glide.json
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart-icy-claws.json
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart.json
  packs/spells/mantle-of-the-frozen-heart.json
  static/lang/re-en.json
Labels: pr: data update

#17674 Add effect for Extra Alchemy familiar ability
  packs/familiar-abilities/extra-alchemy.json
  packs/feat-effects/effect-extra-alchemy.json
  packs/feat-effects/effect-left-hand-blood.json
  packs/feats/chemical-contagion.json
Labels: pr: data update

#17672 Fix chat message preview expand for quick alchemy
  src/module/chat-message/helpers.ts
Labels: pr: bugfix

#17675 Update even more Spell Effect descriptions
  packs/spell-effects/spell-effect-ooze-form-black-pudding.json
  packs/spell-effects/spell-effect-ooze-form-gelatinous-cube.json
  packs/spell-effects/spell-effect-ooze-form-gray-ooze.json
  packs/spell-effects/spell-effect-ooze-form-ochre-jelly.json
  packs/spell-effects/spell-effect-penumbral-disguise.json
  packs/spell-effects/spell-effect-pest-form.json
  packs/spell-effects/spell-effect-phoenix-ward.json
  packs/spell-effects/spell-effect-physical-boost.json
  packs/spell-effects/spell-effect-plant-form-arboreal.json
  packs/spell-effects/spell-effect-plant-form-flytrap.json
  packs/spell-effects/spell-effect-plant-form-shambler.json
  packs/spell-effects/spell-effect-practice-makes-perfect.json
  packs/spell-effects/spell-effect-precious-metals.json
  packs/spell-effects/spell-effect-primal-summons.json
  packs/spell-effects/spell-effect-prismatic-armor.json
  packs/spell-effects/spell-effect-prismatic-shield.json
  packs/spell-effects/spell-effect-protect-companion.json
  packs/spell-effects/spell-effect-protection.json
  packs/spell-effects/spell-effect-protective-wards.json
  packs/spell-effects/spell-effect-rapid-adaptation.json
  packs/spell-effects/spell-effect-ray-of-frost.json
  packs/spell-effects/spell-effect-reinforce-eidolon.json
  packs/spell-effects/spell-effect-rejuvenating-flames.json
  packs/spell-effects/spell-effect-rejuvenating-touch.json
  packs/spell-effects/spell-effect-repel-metal.json
  packs/spell-effects/spell-effect-resilient-touch.json
  packs/spell-effects/spell-effect-return-the-favor.json
  packs/spell-effects/spell-effect-rousing-splash.json
Labels: pr: data update

#17682 Remove redundant type/value imports of `DataField`s in rule element files
  src/module/rules/rule-element/actor-traits.ts
  src/module/rules/rule-element/adjust-degree-of-success.ts
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/aura.ts
  src/module/rules/rule-element/base-speed.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/battle-form/schema.ts
  src/module/rules/rule-element/creature-size.ts
  src/module/rules/rule-element/crit-spec.ts
  src/module/rules/rule-element/damage-alteration/rule-element.ts
  src/module/rules/rule-element/effect-spinoff/rule-element.ts
  src/module/rules/rule-element/ephemeral-effect.ts
  src/module/rules/rule-element/fast-healing.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/iwr/base.ts
  src/module/rules/rule-element/lose-hit-points.ts
  src/module/rules/rule-element/martial-proficiency.ts
  src/module/rules/rule-element/multiple-attack-penalty.ts
  src/module/rules/rule-element/roll-note.ts
  src/module/rules/rule-element/roll-option/data.ts
  src/module/rules/rule-element/roll-twice.ts
  src/module/rules/rule-element/sense.ts
  src/module/rules/rule-element/special-statistic.ts
  src/module/rules/rule-element/strike.ts
  src/module/rules/rule-element/striking.ts
  src/module/rules/rule-element/substitute-roll.ts
  src/module/rules/rule-element/temp-hp.ts
  src/module/rules/rule-element/token-effect-icon.ts
  src/module/rules/rule-element/token-image.ts
  src/module/rules/rule-element/token-light.ts
  src/module/rules/rule-element/token-mark/rule-element.ts
  src/module/rules/rule-element/token-name.ts
  src/module/rules/rule-element/weapon-potency.ts
Labels: pr: refactor

#17673 Update Fresh Ingredients feat
  packs/feats/fresh-ingredients.json
Labels: pr: data update

#17684 Add wilderness label for Fresh Ingredients
  static/lang/re-en.json
Labels: pr: data update

#16759 Add basic support for physical implement items for Thaumaturge
  packs/classfeatures/amulet.json
  packs/classfeatures/bell.json
  packs/classfeatures/chalice.json
  packs/classfeatures/lantern.json
  packs/classfeatures/mirror.json
  packs/classfeatures/regalia.json
  packs/classfeatures/tome.json
  packs/classfeatures/wand.json
  packs/classfeatures/weapon.json
  packs/equipment/amulet-implement.json
  packs/equipment/bell-implement.json
  packs/equipment/chalice-implement.json
  packs/equipment/lantern-implement.json
  packs/equipment/mirror-implement.json
  packs/equipment/regalia-implement.json
  packs/equipment/tome-implement.json
  packs/equipment/wand-implement.json
Labels: pr: data update

#17686 Fix pillow shield ac bonus
  packs/equipment/pillow-shield.json
Labels: pr: data update

#17690 Load all available compendium packs by default in the Compendium Browser
  src/module/apps/compendium-browser/browser.ts
  src/module/apps/compendium-browser/data.ts
  src/module/apps/compendium-browser/settings.ts
  static/lang/en.json
  static/templates/compendium-browser/settings/pack-settings.hbs
Labels: pr: bugfix

#17691 Fix Wisp Chain variants descriptions
  packs/equipment/wisp-chain-greater.json
  packs/equipment/wisp-chain-major.json
  packs/equipment/wisp-chain-true.json
Labels: pr: data update

#17697 Floor max slots in crafting ability creation
  src/module/actor/character/crafting/ability.ts
Labels: pr: bugfix

#17699 Show selectors when inspecting damage taken messages
  src/module/actor/base.ts
  src/module/chat-message/data.ts
Labels: pr: enhancement

#17693 Remove destroyable management from chat messages
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/listeners/damage-taken.ts
Labels: pr: bugfix

#17700 Receive statistics from cloned actors for non-strikes
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#17679 Automate several Godling archetype features
  packs/feat-effects/effect-absolve-sins.json
  packs/feat-effects/effect-divine-invulnerability-domain-spell.json
  packs/feat-effects/effect-divine-invulnerability.json
  packs/feat-effects/effect-gird-champion-hierophant.json
  packs/feat-effects/effect-pass-vengeful-judgment.json
  packs/feat-effects/effect-stymie-the-gods.json
  packs/feats/absolve-sins.json
  packs/feats/assume-godhood.json
  packs/feats/claim-cardinal-domains.json
  packs/feats/divine-invulnerability.json
  packs/feats/font-of-life-or-death.json
  packs/feats/gird-champion.json
  packs/feats/godling-dedication.json
  packs/feats/pass-vengeful-judgment.json
  packs/feats/receive-prayers.json
  packs/feats/sanctified-relic.json
  packs/feats/stymie-the-gods.json
  static/lang/re-en.json
Labels: pr: data update

#17703 Fix `Craft` button being a submit button
  static/templates/actors/character/tabs/crafting.hbs
Labels: pr: bugfix

#17707 Support uuid when using rollItemMacro()
  src/scripts/macros/hotbar.ts
Labels: pr: enhancement

#17705 Use origin level instead of actor level on Cringe's effect
  packs/feat-effects/effect-cringe.json
  packs/feats/cringe.json
Labels: pr: data update

#17706 Add additional details to Deities from Divine Mysteries web supplement
  packs/deities/monitor-demigods/atropos.json
  packs/deities/monitor-demigods/barzahk.json
  packs/deities/monitor-demigods/ceyannan.json
  packs/deities/monitor-demigods/dammar.json
  packs/deities/monitor-demigods/dramindyr.json
  packs/deities/monitor-demigods/ilsurrish.json
  packs/deities/monitor-demigods/inna.json
  packs/deities/monitor-demigods/liisglan.json
  packs/deities/monitor-demigods/monad.json
  packs/deities/monitor-demigods/mother-vulture.json
  packs/deities/monitor-demigods/mrtyu.json
  packs/deities/monitor-demigods/narriseminek.json
  packs/deities/monitor-demigods/phlegyas.json
  packs/deities/monitor-demigods/saloc.json
  packs/deities/monitor-demigods/ssilameshnik.json
  packs/deities/monitor-demigods/telastmar.json
  packs/deities/monitor-demigods/teshallas.json
  packs/deities/monitor-demigods/the-pale-horse.json
  packs/deities/monitor-demigods/vale.json
  packs/deities/monitor-demigods/vavaalrav.json
  packs/deities/monitor-demigods/vonymos.json
  packs/deities/monitor-demigods/ydajisk.json
  packs/deities/orc-gods/grask-uldeth.json
  packs/deities/orc-gods/jukha.json
  packs/deities/orc-gods/mahja-firehair.json
  packs/deities/orc-gods/nulgreth.json
  packs/deities/orc-gods/rull.json
  packs/deities/orc-gods/uirch.json
  packs/deities/orc-gods/varg.json
  packs/deities/orc-gods/wulgren.json
Labels: pr: data update

#17696 Update additional Spell Effect descriptions
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart.json
  packs/spell-effects/spell-effect-pest-form.json
  packs/spell-effects/spell-effect-phase-bolt.json
  packs/spell-effects/spell-effect-runic-body.json
  packs/spell-effects/spell-effect-runic-weapon.json
  packs/spell-effects/spell-effect-sand-form.json
  packs/spell-effects/spell-effect-schadenfreude-success.json
  packs/spell-effects/spell-effect-seal-fate.json
  packs/spell-effects/spell-effect-serrate.json
  packs/spell-effects/spell-effect-shield.json
  packs/spell-effects/spell-effect-shields-of-the-spirit.json
  packs/spell-effects/spell-effect-shillelagh.json
  packs/spell-effects/spell-effect-shrink.json
  packs/spell-effects/spell-effect-silence.json
  packs/spell-effects/spell-effect-soothe.json
  packs/spell-effects/spell-effect-soothing-blossoms.json
  packs/spell-effects/spell-effect-soothing-words.json
  packs/spell-effects/spell-effect-speaking-sky.json
  packs/spell-effects/spell-effect-spectral-advance.json
  packs/spell-effects/spell-effect-spiral-of-horrors.json
  packs/spell-effects/spell-effect-spirit-of-the-beast.json
  packs/spell-effects/spell-effect-stoke-the-heart.json
  packs/spell-effects/spell-effect-summon-healing-servitor.json
  packs/spell-effects/spell-effect-summoners-visage.json
  packs/spell-effects/spell-effect-sure-strike.json
  packs/spell-effects/spell-effect-swampcall.json
  packs/spell-effects/spell-effect-take-root.json
  packs/spell-effects/spell-effect-tempest-cloak.json
  packs/spell-effects/spell-effect-tempest-form.json
  packs/spell-effects/spell-effect-tempt-fate.json
  packs/spell-effects/spell-effect-touch-of-the-moon.json
  packs/spell-effects/spell-effect-untamed-form.json
  packs/spell-effects/spell-effect-vapor-form.json
  packs/spell-effects/spell-effect-veil-of-dreams.json
  packs/spell-effects/spell-effect-vital-beacon.json
  packs/spell-effects/spell-effect-vitrifying-blast.json
  packs/spell-effects/spell-effect-volcanic-eruption.json
  packs/spell-effects/spell-effect-wash-your-luck.json
  packs/spell-effects/spell-effect-weaken-earth.json
  packs/spell-effects/spell-effect-wish-twisted-form-failure.json
  packs/spell-effects/spell-effect-wish-twisted-form-success.json
  packs/spell-effects/spell-effect-zealous-conviction.json
Labels: pr: data update

#17709 Add alternate amp and effect for Mind's Light Circlet
  packs/equipment-effects/effect-minds-light-circlet.json
  packs/equipment/minds-light-circlet.json
  static/lang/re-en.json
Labels: pr: data update

#17704 Add Ephemeral Effect for Disarm's bonus to further attempts
  packs/actions/skill-actions/disarm.json
  packs/other-effects/effect-disarm-bonus.json
  packs/other-effects/effect-disarm-success.json
  static/lang/action-en.json
  static/lang/re-en.json
Labels: pr: data update

#17701 Update additional Archetype journal entries to use `@Embed`
  packs/journals/archetypes.json
Labels: pr: data update

#17688 Add damage to Gust of Wind
  packs/howl-of-the-wild-bestiary/virtuosic-lyrebird.json
  packs/paizo-pregens/ezren-beginner-box.json
  packs/pathfinder-monster-core/air-scamp.json
  packs/pathfinder-monster-core/aiuvarin-elementalist.json
  packs/pathfinder-monster-core/dryad-queen.json
  packs/pathfinder-monster-core/fortune-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/fortune-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/fortune-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/horned-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/horned-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/horned-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/naiad-queen.json
  packs/pfs-season-5-bestiary/5-20/asper-hajeri-9-10.json
  packs/pfs-season-5-bestiary/5-20/asper-hajeri.json
  packs/prey-for-death-bestiary/mantis-keeper.json
  packs/spells/gust-of-wind.json
  packs/tian-xia-world-guide-bestiary/peng.json
Labels: pr: data update

#17689 Grant implement with Thaumaturge Dedication and add Note for Weapon Implement Adept
  packs/actions/implements-interruption.json
  packs/classfeatures/bell.json
  packs/classfeatures/chalice.json
  packs/classfeatures/implements-empowerment.json
  packs/classfeatures/mirror.json
  packs/classfeatures/wand.json
  packs/classfeatures/weapon.json
  packs/feats/thaumaturge-dedication.json
  static/lang/re-en.json
Labels: pr: data update

#17711 Roll item macros for linked actors even if another actor is selected
  src/module/apps/hotbar.ts
Labels: pr: enhancement

#17715 Exclude already-possessed heritages in heritage choice sets
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#17718 Fix typo on Rhysaphin's Greater Flameheart Weapon
  packs/prey-for-death-bestiary/rhysaphine.json
Labels: pr: data update

#17678 Condense Ghost Planchette equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-ghostcallers-planchette-armor-greater.json
  packs/equipment-effects/effect-ghostcallers-planchette-armor.json
  packs/equipment-effects/effect-ghostcallers-planchette-weapon-greater.json
  packs/equipment-effects/effect-ghostcallers-planchette-weapon.json
  packs/equipment/ghostcallers-planchette-greater.json
  static/lang/re-en.json
Labels: pr: data update

#17724 Update Spellcasting Archetype entry in Archetype journals to match Player Core 2
  packs/journals/archetypes.json
Labels: pr: data update

#17721 Allow 3rd rank revelation spells to be chosen for Diverse Mystery
  packs/feats/diverse-mystery.json
Labels: pr: data update

#17719 Correct Talos Gadgeteer's gadget inventory selection
  packs/rage-of-elements-bestiary/talos-gadgeteer.json
Labels: pr: data update

#17716 Add Lantern implement light and effect for bonus within its light
  packs/classfeatures/lantern.json
  packs/feat-effects/effect-lantern.json
  static/lang/re-en.json
Labels: pr: data update

#17714 Automate Drink from the Chalice and add effect for its adept benefit
  packs/actions/drink-from-the-chalice.json
  packs/classfeatures/chalice.json
  packs/feat-effects/effect-chalice-adept-benefit-self.json
  packs/feat-effects/effect-drink-from-the-chalice.json
  static/lang/re-en.json
Labels: pr: data update

#17694 Automate Thaumaturge Regalia aura and other benefits
  packs/classfeatures/regalia.json
  packs/feat-effects/effect-regalia.json
  static/lang/re-en.json
Labels: pr: data update

#17658 Alter versatile vial traits with bomber class feature
  packs/classfeatures/bomber.json
Labels: pr: data update

#17713 Brush up Werecreature Dedication
  packs/blood-lords-bestiary/ghoul-crocodile.json
  packs/feat-effects/effect-echolocation.json
  packs/feat-effects/effect-force-of-nature-silver-damage.json
  packs/feats/bear-hug-werecreature.json
  packs/feats/beastkin-resilience.json
  packs/feats/cornered-animal.json
  packs/feats/death-roll.json
  packs/feats/dire-growth.json
  packs/feats/echolocation.json
  packs/feats/fearful-symmetry.json
  packs/feats/feeding-frenzy.json
  packs/feats/feral-mending.json
  packs/feats/feral-scramble.json
  packs/feats/feral-senses.json
  packs/feats/force-of-nature.json
  packs/feats/pack-attack.json
  packs/feats/plague-rat.json
  packs/feats/pouncing-transformation.json
  packs/feats/rapid-hybridization.json
  packs/feats/scarred-hide.json
  packs/feats/touch-of-lunacy.json
  packs/feats/undying-beast.json
  packs/feats/werecreature-dedication.json
  packs/feats/you-dont-smell-right.json
  packs/pathfinder-monster-core/crocodile.json
  packs/pfs-season-5-bestiary/5-10/carcaras.json
  packs/pfs-season-5-bestiary/5-10/pampla.json
  packs/strength-of-thousands-bestiary/old-thrasher.json
  static/lang/re-en.json
Labels: pr: data update

#17712 Add effects for Amulet's Abeyance and its adept benefit
  packs/actions/amulets-abeyance.json
  packs/classfeatures/amulet.json
  packs/feat-effects/effect-amulets-abeyance-adept.json
  packs/feat-effects/effect-amulets-abeyance.json
  static/lang/re-en.json
Labels: pr: data update

#17722 Fix waterlogged source
  packs/bestiary-effects/effect-waterlogged.json
Labels: pr: data update

#17670 Automate several Broken Chain archetype features
  packs/actions/ultimatum-of-liberation.json
  packs/feat-effects/effect-bloc-tactics.json
  packs/feat-effects/effect-cry-of-rebellion.json
  packs/feat-effects/effect-ultimatum-of-liberation.json
  packs/feat-effects/effect-you-cant-kill-an-idea.json
  packs/feats/bloc-tactics.json
  packs/feats/break-the-causal-chain.json
  packs/feats/break-the-cycle.json
  packs/feats/bring-into-the-fold.json
  packs/feats/cry-of-rebellion.json
  packs/feats/liberty-or-death.json
  packs/feats/lose-your-chains.json
  packs/feats/rebellious-existence.json
  packs/feats/release-me.json
  packs/feats/remember-their-names.json
  packs/feats/reprisal-of-the-fallen.json
  packs/feats/rites-of-liberation.json
  packs/feats/stand-firm.json
  packs/feats/united-front.json
  packs/feats/you-cant-keep-us-down.json
  packs/feats/you-cant-kill-an-idea.json
  static/lang/re-en.json
Labels: pr: data update

#17723 Automate Tome Implement initiate benefits
  packs/classfeatures/tome.json
  packs/feat-effects/effect-tome-adept-benefit.json
  static/lang/re-en.json
Labels: pr: data update

#17725 Fix roll option on Tome physical thaumaturge implement
  packs/equipment/minds-light-circlet.json
  packs/equipment/tome-implement.json
Labels: pr: data update

#17677 Automate several Eternal Legend archetype features
  packs/feat-effects/effect-living-epic.json
  packs/feat-effects/effect-pierce-the-eye.json
  packs/feat-effects/effect-terrifying-mien.json
  packs/feat-effects/stance-immovable-object.json
  packs/feats/death-from-above-eternal-legend.json
  packs/feats/demolishing-knockback.json
  packs/feats/earth-to-heavens-strike.json
  packs/feats/eternal-legend-dedication.json
  packs/feats/exaltation-overwhelming.json
  packs/feats/faultless-defense.json
  packs/feats/fight-through-oblivion.json
  packs/feats/finish-their-story.json
  packs/feats/immovable-object.json
  packs/feats/leaping-hedgehog-strike.json
  packs/feats/legend-of-combat.json
  packs/feats/living-epic.json
  packs/feats/mythic-weapon-specialization.json
  packs/feats/pierce-the-eye.json
  packs/feats/scattering-shout.json
  packs/feats/terrifying-mien.json
  packs/feats/unstoppable-force.json
  packs/feats/weft-and-warp.json
  static/lang/re-en.json
Labels: pr: data update

#17114 Fix Kashrishi climbing feats
  packs/feats/scuttle-up.json
  packs/feats/skilled-climber.json
Labels: pr: data update

#17729 Add remaining Monster Core Fall 2024 Errata
  packs/pathfinder-monster-core/cassisian.json
  packs/pathfinder-monster-core/crawling-hand.json
  packs/pathfinder-monster-core/graveknight.json
  packs/pathfinder-monster-core/greater-nightmare.json
  packs/pathfinder-monster-core/ratfolk-grenadier.json
Labels: pr: data update

#17732 Automate Wand Implement Adept and Paragon benefits
  packs/classfeatures/adept-benefit-amulet.json
  packs/classfeatures/adept-benefit-bell.json
  packs/classfeatures/adept-benefit-chalice.json
  packs/classfeatures/adept-benefit-lantern.json
  packs/classfeatures/adept-benefit-mirror.json
  packs/classfeatures/adept-benefit-regalia.json
  packs/classfeatures/adept-benefit-tome.json
  packs/classfeatures/adept-benefit-wand.json
  packs/classfeatures/adept-benefit-weapon.json
  packs/classfeatures/paragon-benefit-amulet.json
  packs/classfeatures/paragon-benefit-bell.json
  packs/classfeatures/paragon-benefit-chalice.json
  packs/classfeatures/paragon-benefit-lantern.json
  packs/classfeatures/paragon-benefit-mirror.json
  packs/classfeatures/paragon-benefit-regalia.json
  packs/classfeatures/paragon-benefit-tome.json
  packs/classfeatures/paragon-benefit-wand.json
  packs/classfeatures/paragon-benefit-weapon.json
  packs/feat-effects/effect-fling-magic-adept-cold.json
  static/lang/re-en.json
Labels: pr: data update

#17734 Fix some emphasised spell links
  packs/actions/sustain-an-effect.json
  packs/feats/water-to-water.json
  packs/pfs-season-6-bestiary/6-00/accursed-cargo-1-2.json
  packs/pfs-season-6-bestiary/6-00/accursed-cargo-3-4.json
  packs/pfs-season-6-bestiary/6-00/accursed-cargo-5-6.json
  packs/pfs-season-6-bestiary/6-00/accursed-cargo-7-8.json
  packs/pfs-season-6-bestiary/6-00/hostile-architecture-1-2.json
  packs/pfs-season-6-bestiary/6-00/hostile-architecture-3-4.json
  packs/pfs-season-6-bestiary/6-00/hostile-architecture-5-6.json
  packs/pfs-season-6-bestiary/6-00/hostile-architecture-7-8.json
  packs/pfs-season-6-bestiary/6-00/sailors-warning-1-2.json
  packs/pfs-season-6-bestiary/6-00/sailors-warning-3-4.json
  packs/pfs-season-6-bestiary/6-00/sailors-warning-5-6.json
  packs/pfs-season-6-bestiary/6-00/sailors-warning-7-8.json
  static/lang/en.json
Labels: pr: data update

#17735 Add effect for Instructive Strike and automate Implement's Flight
  packs/classfeatures/mirror.json
  packs/classfeatures/second-adept.json
  packs/feat-effects/effect-instructive-strike.json
  packs/feats/cursed-effigy.json
  packs/feats/implements-flight.json
  packs/feats/instructive-strike.json
  packs/feats/intense-implement.json
  packs/feats/seven-part-link.json
  packs/feats/shared-warding.json
  packs/feats/thaumaturges-investiture.json
  packs/feats/thaumaturgic-ritualist.json
  packs/feats/ubiquitous-weakness.json
Labels: pr: data update

#17736 Condense Animal Swiftness feat and improve automation
  build/uuid-redirects.json
  packs/feats/animal-swiftness-climb.json
  packs/feats/animal-swiftness-fly.json
  packs/feats/animal-swiftness-land.json
  packs/feats/animal-swiftness-swim.json
  packs/feats/animal-swiftness.json
Labels: pr: data update

#17738 Refresh Fumbus pregens
  packs/iconics/fumbus-level-1.json
  packs/iconics/fumbus-level-3.json
  packs/iconics/fumbus-level-5.json
Labels: pr: data update

#17739 Add automation to Lighter than Air Oracle feat
  packs/feats/lighter-than-air.json
Labels: pr: data update

#17742 Update automation for Ancestry flight-granting feats
  packs/feats/energize-wings.json
  packs/feats/evanescent-wings.json
  packs/feats/juvenile-flight.json
  packs/feats/soaring-flight.json
  packs/feats/soaring-form.json
  packs/feats/strong-of-wing.json
  packs/feats/take-flight.json
  packs/feats/winglet-flight.json
Labels: pr: data update

#17743 Add note item alteration to Uplifting Winds druid feat
  packs/feats/uplifting-winds.json
Labels: pr: data update

#17744 Add localized notes to Wild Witch's Armaments feat
  packs/feats/wild-witchs-armaments.json
  static/lang/re-en.json
Labels: pr: data update

#17746 Implement remaining GM Core and Player Core 2 Fall 2024 Errata
  packs/classfeatures/oracle-spellcasting.json
  packs/equipment/chaplains-cudgel.json
  packs/equipment/medusas-scream.json
  packs/equipment/potion-of-emergency-escape.json
  packs/hazards/ghostly-choir.json
  packs/journals/archetypes.json
  packs/journals/classes.json
  packs/spells/live-wire.json
  static/lang/en.json
Labels: pr: data update

#17745 Add adept and paragon benefits description addenda to Ring Bell and Mirror's Reflection
  packs/classfeatures/adept-benefit-bell.json
  packs/classfeatures/adept-benefit-mirror.json
  packs/classfeatures/paragon-benefit-bell.json
  packs/classfeatures/paragon-benefit-mirror.json
  packs/feat-effects/effect-chalice-adept-benefit-self.json
  packs/feat-effects/effect-drink-from-the-chalice.json
  static/lang/re-en.json
Labels: pr: data update

#17747 Fix Divine Vessel spell effects
  packs/journals/remaster-changes.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level-evil.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level-good.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level-lawful.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level.json
  packs/spell-effects/spell-effect-divine-vessel-evil.json
  packs/spell-effects/spell-effect-divine-vessel-good.json
  packs/spell-effects/spell-effect-divine-vessel-lawful.json
  packs/spell-effects/spell-effect-divine-vessel.json
Labels: pr: data update

#17750 Fix a mismatched parenthesis
  packs/pfs-season-6-bestiary/quests/angry-chelaxian-adjutant.json
  packs/pfs-season-6-bestiary/quests/anxious-baby-scamp-swarm.json
  packs/pfs-season-6-bestiary/quests/baby-scamp-swarm.json
  packs/pfs-season-6-bestiary/quests/chelaxian-adjutant.json
  packs/pfs-season-6-bestiary/quests/earth-falls-1-2.json
  packs/pfs-season-6-bestiary/quests/earth-falls-3-4.json
  packs/pfs-season-6-bestiary/quests/elite-silver-devil-hooligan.json
  packs/pfs-season-6-bestiary/quests/lightning-strikes-1-2.json
  packs/pfs-season-6-bestiary/quests/lightning-strikes-3-4.json
  packs/pfs-season-6-bestiary/quests/silver-devil-delinquent.json
  packs/pfs-season-6-bestiary/quests/silver-devil-hooligan.json
  packs/pfs-season-6-bestiary/quests/umberweed.json
  packs/pfs-season-6-bestiary/quests/wind-buffets-1-2.json
  packs/pfs-season-6-bestiary/quests/wind-buffets-3-4.json
  packs/spells/demon-form.json
Labels: pr: data update

#17751 Add missing roll option to Twin Star's predicate
  packs/feats/twin-stars.json
Labels: pr: data update

#17753 Update additional Deities with Lost Omens Divine Mysteries web supplement details
  packs/deities/outer-gods-and-great-old-ones/azathoth.json
  packs/deities/outer-gods-and-great-old-ones/bokrug.json
  packs/deities/outer-gods-and-great-old-ones/cthulhu.json
  packs/deities/outer-gods-and-great-old-ones/hastur.json
  packs/deities/outer-gods-and-great-old-ones/mhar.json
  packs/deities/outer-gods-and-great-old-ones/nhimbaloth.json
  packs/deities/outer-gods-and-great-old-ones/nyarlathotep-the-crawling-chaos.json
  packs/deities/outer-gods-and-great-old-ones/nyarlathotep-the-faceless-sphinx.json
  packs/deities/outer-gods-and-great-old-ones/nyarlathotep-the-veiled-voice.json
  packs/deities/outer-gods-and-great-old-ones/orgesh.json
  packs/deities/outer-gods-and-great-old-ones/rhan-tegoth.json
  packs/deities/outer-gods-and-great-old-ones/xhamen-dor.json
  packs/deities/outer-gods-and-great-old-ones/yig.json
  packs/deities/outer-gods-and-great-old-ones/yog-sothoth.json
  packs/deities/qlippoth-lords/aonaurious.json
  packs/deities/qlippoth-lords/chavazvug.json
  packs/deities/qlippoth-lords/isph-aun-vuln.json
  packs/deities/qlippoth-lords/nyuo-ogh.json
  packs/deities/qlippoth-lords/oaur-ooung.json
  packs/deities/qlippoth-lords/thuskchoon.json
  packs/deities/qlippoth-lords/yamasoth.json
  packs/deities/queens-of-the-night/ardad-lili.json
  packs/deities/queens-of-the-night/doloras.json
  packs/deities/queens-of-the-night/eiseth.json
  packs/deities/queens-of-the-night/mahathallah.json
Labels: pr: data update
