Repository foundryvtt/pf2e, pull requests merged in 2024-01, with the labels that each got.

#12606 Add arrest a fall action object
  src/module/system/action-macros/index.ts
  src/module/system/action-macros/specialty-basic/arrest-a-fall.ts
  static/lang/action-en.json
Labels: pr: enhancement

#12607 Add grab an edge action object
  src/module/system/action-macros/index.ts
  src/module/system/action-macros/specialty-basic/grab-an-edge.ts
  static/lang/action-en.json
Labels: pr: enhancement

#12651 Classify languages according to rarity
  src/global.ts
  src/module/actor/creature/types.ts
  src/module/actor/creature/values.ts
  src/module/actor/sheet/base.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/tag-selector/base.ts
  src/module/system/tag-selector/basic.ts
  src/module/system/tag-selector/index.ts
  src/module/system/tag-selector/languages.ts
  src/styles/ui/_tag-selector.scss
  static/lang/en.json
  static/templates/actors/character/tabs/character.hbs
  static/templates/actors/npc/tabs/main.hbs
  static/templates/items/ancestry-details.hbs
  static/templates/system/tag-selector/basic.hbs
  types/foundry/common/types.d.ts
Labels: pr: enhancement

#12653 Add Sustain an Effect Exploration Activity
  packs/actions/sustain-an-effect.json
Labels: pr: data update

#12661 Fix initial setting of token hearing radius
  src/module/canvas/perception/modes.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/pixi/board.d.ts
  types/foundry/client/ui/editor.d.ts
  types/foundry/common/documents/scene.d.ts
Labels: pr: bugfix

#12663 Fix language selector search filter
  src/module/system/tag-selector/basic.ts
  static/templates/system/tag-selector/basic.hbs
Labels: pr: bugfix

#12662 Check that flanking buddies are allies
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#12664 Check for canvas readiness in more places
  src/module/canvas/helpers.ts
  src/module/canvas/layer/template.ts
  src/module/canvas/perception/modes.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/aura/util.ts
  src/module/canvas/token/flanking-highlight/renderer.ts
  src/module/canvas/token/object.ts
  src/module/item/spell/document.ts
  src/module/scene/token-document/clown-car.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: refactor

#12643 Add language feat subfeatures
  packs/classfeatures/wildsong.json
  packs/feats/multilingual.json
  packs/iconics/lini-level-1.json
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/item/ancestry/document.ts
  src/module/item/feat/data.ts
  src/module/item/feat/document.ts
  src/module/item/feat/sheet.ts
  src/styles/item/_feat-sheet.scss
  static/lang/en.json
  static/templates/items/feat-details.hbs
Labels: pr: enhancement

#12665 Remove redundant localization key for language subfeatures
  static/lang/en.json
  static/templates/items/feat-details.hbs
Labels: pr: refactor

#12656 Micro-optimize `ActorPF2e#hasCondition`
  src/module/actor/base.ts
  src/module/actor/conditions.ts
Labels: pr: refactor

#12666 Refactor older migrations ahead of language migration
  src/module/migration/migrations/647-fix-pc-senses.ts
  src/module/migration/migrations/674-stable-homebrew-tag-ids.ts
  src/module/migration/migrations/681-giant-language-to-jotun.ts
  src/module/migration/migrations/698-remove-derived-actor-traits.ts
  src/module/migration/migrations/743-fix-weakness-structure.ts
  src/module/migration/migrations/853-remaster-languages.ts
  src/module/migration/migrations/888-remaster-languages-heritages.ts
  src/module/migration/migrations/914-move-perception-senses.ts
Labels: pr: refactor

#12669 Include all when migrating stored traits to custom feat item
  src/module/migration/migrations/914-move-perception-senses.ts
Labels: pr: bugfix

#12670 Make size optional in base actor data
  src/module/actor/army/data.ts
  src/module/actor/base.ts
  src/module/actor/character/data.ts
  src/module/actor/creature/data.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/npc/data.ts
  src/module/item/weapon/document.ts
  src/module/system/tag-selector/basic.ts
Labels: pr: types update

#12671 Remove merging with stored PC saving throw data
  src/module/actor/character/document.ts
  src/module/actor/creature/values.ts
Labels: pr: refactor

#12672 Add languages to `system.details` in template.json
  static/template.json
Labels: pr: housekeeping

#12677 Fix display of perception details on NPC sheet
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#12668 Update witch lessons to use otherTags
  packs/classfeatures/lesson-of-bargains.json
  packs/classfeatures/lesson-of-calamity.json
  packs/classfeatures/lesson-of-death.json
  packs/classfeatures/lesson-of-dreams.json
  packs/classfeatures/lesson-of-elements.json
  packs/classfeatures/lesson-of-favors.json
  packs/classfeatures/lesson-of-life.json
  packs/classfeatures/lesson-of-mischief.json
  packs/classfeatures/lesson-of-protection.json
  packs/classfeatures/lesson-of-renewal.json
  packs/classfeatures/lesson-of-shadow.json
  packs/classfeatures/lesson-of-snow.json
  packs/classfeatures/lesson-of-the-frozen-queen.json
  packs/classfeatures/lesson-of-vengeance.json
  packs/feats/basic-lesson.json
  packs/feats/greater-lesson.json
  packs/feats/major-lesson.json
Labels: pr: data update

#12659 Update effect for Scout's Warning to removeAfterRoll
  packs/classes/barbarian.json
  packs/classfeatures/heightened-senses.json
  packs/feat-effects/effect-scouts-warning.json
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
  packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
  packs/paizo-pregens/popcorn-level-4.json
  packs/paizo-pregens/popcorn.json
Labels: pr: data update

#12657 Brush up automation for Cut from the Air
  packs/feats/cut-from-the-air.json
Labels: pr: data update

#12654 Correct level of Coven Spell feat
  packs/feats/coven-spell.json
Labels: pr: data update

#12633 Add effect for Energy Ablation
  packs/feat-effects/effect-energy-ablation.json
  packs/feats/energy-ablation.json
  static/lang/re-en.json
Labels: pr: data update

#12421 Brushup Scholarly Defense Rule Elements
  packs/feats/scholarly-defense.json
Labels: pr: data update

#12647 Fix Ruffian Rogue armor proficiency
  packs/classfeatures/ruffian.json
Labels: pr: data update

#12678 Fix spellcasting entry assignment for scroll/wand spells
  src/module/actor/spellcasting.ts
  src/module/chat-message/document.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/trick.ts
Labels: pr: bugfix, pr: refactor

#12681 Hide untrained martial proficiencies on PC sheet
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/rules/rule-element/martial-proficiency.ts
  static/templates/actors/character/tabs/proficiencies.hbs
Labels: ui/ux

#12686 Fill out Multilingual feat automation in migration 914
  packs/feats/multilingual.json
  packs/kingmaker-bestiary/jubilost-level-8.json
  packs/kingmaker-bestiary/tristian-level-1.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/paizo-pregens/fluff-fang-level-4.json
  packs/paizo-pregens/fluff-fang.json
  packs/paizo-pregens/jaithe.json
  packs/paizo-pregens/zerryd.json
  src/module/migration/migrations/914-move-perception-senses.ts
  src/module/system/tag-selector/languages.ts
Labels: pr: data migration, pr: data update

#12687 Use clearer property name for "common" language `LanguageRaritiesData`
  src/module/system/settings/homebrew/data.ts
  src/module/system/tag-selector/basic.ts
  src/module/system/tag-selector/languages.ts
  static/lang/en.json
Labels: pr: refactor

#12690 Fix description of commune spell
  packs/spells/commune.json
Labels: pr: data update

#12689 Automate the Sprite ancestry feature Magical Strikes
  packs/ancestryfeatures/magical-strikes.json
Labels: pr: data update

#12683 Update Purifying Icicle to deal extra vitality damage only against undead
  packs/spells/purifying-icicle.json
Labels: pr: data update

#12680 Add resistance effect for Magic's Vessel
  packs/spell-effects/spell-effect-magics-vessel-resistance.json
  packs/spell-effects/spell-effect-magics-vessel.json
  packs/spells/magics-vessel.json
  static/lang/re-en.json
Labels: pr: data update

#12679 Add Note RE with damage link for Cremate Undead
  packs/feats/cremate-undead.json
  static/lang/re-en.json
Labels: pr: data update

#12688 Allow use of @kingdom in rule element resolving
  src/module/rules/rule-element/base.ts
  static/templates/actors/party/kingdom/partials/settlement.hbs
Labels: pr: bugfix, kingmaker

#12694 Correct padding of paizo-style tags in chat messages
  src/styles/legacy/_chat.scss
Labels: ui/ux

#12658 Move item-related click listeners to global actor-sheet handler
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/sheet/base.ts
  src/styles/actor/_inventory.scss
  src/styles/actor/character/_crafting.scss
  src/styles/actor/character/_proficiencies.scss
  src/styles/actor/familiar/_index.scss
  src/styles/actor/hazard/_sidebar.scss
  static/lang/en.json
  static/templates/actors/army/sheet.hbs
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/actors/character/partials/feat-slot.hbs
  static/templates/actors/character/tabs/actions.hbs
  static/templates/actors/character/tabs/character.hbs
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/actors/character/tabs/effects.hbs
  static/templates/actors/character/tabs/pfs.hbs
  static/templates/actors/character/tabs/proficiencies.hbs
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/crafting-entry-alchemical.hbs
  static/templates/actors/crafting-entry-list.hbs
  static/templates/actors/familiar-sheet.hbs
  static/templates/actors/hazard/partials/sidebar.hbs
  static/templates/actors/hazard/sheet.hbs
  static/templates/actors/npc/partials/action.hbs
  static/templates/actors/npc/partials/attack.hbs
  static/templates/actors/npc/skills-editor.hbs
  static/templates/actors/npc/tabs/main.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/partials/action.hbs
  static/templates/actors/partials/effects.hbs
  static/templates/actors/partials/inventory.hbs
  static/templates/actors/partials/item-line.hbs
  static/templates/actors/partials/spell-collection.hbs
  static/templates/actors/party/kingdom/tabs/activities.hbs
  static/templates/actors/party/kingdom/tabs/features.hbs
  static/templates/actors/party/sheet.hbs
  static/templates/actors/vehicle/sidebar.hbs
  static/templates/actors/vehicle/tabs/actions.hbs
Labels: pr: refactor

#12699 Fix hazard health line regression
  src/styles/actor/hazard/_sidebar.scss
Labels: ui/ux

#12700 Change language rarities setting key to dot notation
  src/global.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/tag-selector/languages.ts
Labels: pr: refactor

#12702 Add CSS variables for sub-font-size spacing
  src/styles/_fonts.scss
  src/styles/_globals.scss
  src/styles/_tags.scss
  src/styles/actor/character/_attribute-builder.scss
Labels: pr: enhancement

#12708 Add missing baseType to several claw and jaws Strike REs
  packs/adventure-specific-actions/feral-claws.json
  packs/ancestries/conrasu.json
  packs/ancestryfeatures/claws.json
  packs/equipment-effects/effect-clawed-bracers.json
  packs/equipment-effects/effect-wolfjaw-armor.json
  packs/feat-effects/effect-ursine-avenger-form.json
  packs/feats/automaton-armament.json
  packs/feats/bestial-manifestation.json
  packs/feats/ceremony-of-the-evened-hand.json
  packs/feats/claws-of-the-dragon.json
  packs/feats/hag-claws.json
  packs/feats/living-weapon.json
  packs/feats/retractable-claws.json
  packs/feats/saber-teeth.json
  packs/feats/tusks-half-orc.json
  packs/feats/vicious-incisors.json
  packs/feats/witchs-armaments.json
  packs/feats/zombie-dedication.json
  packs/heritages/clawed-catfolk.json
  packs/heritages/earthly-wilds-kitsune.json
  packs/heritages/lahkgyan-vanara.json
  packs/heritages/strongjaw-kobold.json
  packs/heritages/vicious-goloma.json
  packs/paizo-pregens/jaithe.json
  packs/paizo-pregens/savshin-starwatcher.json
  packs/paizo-pregens/takemiru.json
  packs/paizo-pregens/zakzak.json
  packs/spell-effects/spell-effect-animal-feature-claws.json
  packs/spell-effects/spell-effect-animal-feature-jaws.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level-evil.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level.json
  packs/spell-effects/spell-effect-divine-vessel-evil.json
  packs/spell-effects/spell-effect-divine-vessel.json
  packs/spell-effects/spell-effect-dragon-claws.json
  packs/spell-effects/spell-effect-gluttons-jaw.json
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart-icy-claws.json
  packs/spell-effects/spell-effect-moon-frenzy.json
  packs/spell-effects/spell-effect-shifting-form-claws.json
  packs/spell-effects/spell-effect-shifting-form.json
Labels: pr: data update

#12710 Restore rarity description tooltips in physical-item summaries
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/item/feat/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
  static/templates/actors/partials/item-summary.hbs
  static/templates/chat/armor-card.hbs
  static/templates/chat/backpack-card.hbs
  static/templates/chat/consumable-card.hbs
  static/templates/chat/equipment-card.hbs
  static/templates/chat/feat-card.hbs
  static/templates/chat/shield-card.hbs
  static/templates/chat/weapon-card.hbs
Labels: pr: bugfix, pr: enhancement

#12709 Update description of Ochre Fulcrum Lens
  packs/equipment/ochre-fulcrum-lens.json
Labels: pr: data update

#12706 Remove guarantee of embedded item returns from spell-variant methods
  src/module/item/ability/helpers.ts
  src/module/item/spell/document.ts
  src/module/item/spell/overlay.ts
Labels: pr: bugfix

#12692 Brush up Life-Giving Form
  packs/spell-effects/spell-effect-life-giving-form.json
  packs/spells/life-giving-form.json
Labels: pr: data update

#12693 Fix frequency for flowering path
  packs/feats/flowering-path.json
Labels: pr: data update

#12695 Add leveled damage to extract element
  packs/actions/extract-element.json
Labels: pr: data update

#12698 Brush up Crimson Fulcrum Lens
  packs/abomination-vaults-bestiary/urthagul.json
  packs/equipment/crimson-fulcrum-lens.json
  static/lang/re-en.json
Labels: pr: data update

#12705 Add level to Hilllock Halfling's healing received from Treat Wounds
  packs/heritages/hillock-halfling.json
  packs/heritages/jinxed-halfling.json
  packs/heritages/nomadic-halfling.json
  packs/heritages/twilight-halfling.json
  packs/heritages/wildwood-halfling.json
Labels: pr: data update

#12707 Brush up Vine Leshy's climb automation
  packs/heritages/vine-leshy.json
Labels: pr: data update

#12711 Restore container cycle checks to inventory drag/drop
  src/module/actor/base.ts
  src/module/actor/creature/document.ts
  src/module/actor/sheet/base.ts
  src/module/item/container/document.ts
  src/module/item/container/helpers.ts
  src/module/item/physical/document.ts
Labels: pr: bugfix

#12713 Prune `_stats` property during spell overlay updates
  src/module/item/spell/overlay.ts
Labels: pr: bugfix

#12712 Span single-item proficiency lists across two columns on PC sheet
  src/styles/actor/character/_proficiencies.scss
  static/templates/actors/character/tabs/proficiencies.hbs
Labels: ui/ux

#12716 Remove schema validation from language rarities setting
  src/module/system/settings/homebrew/data.ts
  src/scripts/hooks/ready.ts
Labels: pr: bugfix

#12717 Remove redundant localization key for "Languages"
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: refactor

#12718 Clear cache upon closing or resetting settings menus
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/menu.ts
  src/module/system/settings/variant-rules.ts
  src/styles/settings/_index.scss
  src/styles/settings/_variant-rules.scss
  static/templates/system/settings/homebrew.hbs
  static/templates/system/settings/menu.hbs
  static/templates/system/settings/variant-rules.hbs
Labels: pr: bugfix

#12719 Move language rarities setting registration to site of other homebrew settings
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/menu.ts
Labels: pr: refactor

#12630 Add `description` item alteration
  src/module/item/abc/data.ts
  src/module/item/ability/data.ts
  src/module/item/affliction/data.ts
  src/module/item/ancestry/data.ts
  src/module/item/armor/data.ts
  src/module/item/background/data.ts
  src/module/item/base/data/system.ts
  src/module/item/book/data.ts
  src/module/item/campaign-feature/data.ts
  src/module/item/class/data.ts
  src/module/item/condition/data.ts
  src/module/item/consumable/data.ts
  src/module/item/container/data.ts
  src/module/item/deity/data.ts
  src/module/item/effect/data.ts
  src/module/item/equipment/data.ts
  src/module/item/feat/data.ts
  src/module/item/heritage/data.ts
  src/module/item/kit/data.ts
  src/module/item/lore.ts
  src/module/item/melee/data.ts
  src/module/item/physical/data.ts
  src/module/item/shield/data.ts
  src/module/item/spell/data.ts
  src/module/item/spellcasting-entry/data.ts
  src/module/item/weapon/data.ts
  src/module/migration/migrations/742-rm-class-ability-boost-levels.ts
  src/module/migration/migrations/767-convert-voluntary-flaws.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
Labels: pr: enhancement

#12715 Add bludgeoning, piercing, slashing, spirit overlays to Spiritual Armament
  packs/spells/spiritual-armament.json
Labels: pr: data update

#12696 Clean up errors in Spell data
  packs/spells/artistic-flourish.json
  packs/spells/commanding-lash.json
  packs/spells/control-water.json
  packs/spells/creative-splash.json
  packs/spells/cursed-metamorphosis.json
  packs/spells/dazzling-flash.json
  packs/spells/discern-secrets.json
  packs/spells/disintegrate.json
  packs/spells/divine-decree.json
  packs/spells/divine-lance.json
  packs/spells/divine-wrath.json
  packs/spells/earthbind.json
  packs/spells/falling-stars.json
  packs/spells/gentle-landing.json
  packs/spells/heal-animal.json
  packs/spells/impaling-briars.json
  packs/spells/perfected-body.json
  packs/spells/personal-blizzard.json
  packs/spells/pet-cache.json
  packs/spells/phantasmagoria.json
  packs/spells/precious-metals.json
  packs/spells/protective-wards.json
  packs/spells/rune-of-observation.json
  packs/spells/safeguard-secret.json
  packs/spells/shape-wood.json
  packs/spells/soothing-words.json
  packs/spells/speak-with-stones.json
  packs/spells/spirit-blast.json
  packs/spells/spirit-link.json
  packs/spells/take-its-course.json
  packs/spells/wall-of-thorns.json
  packs/spells/weapon-surge.json
  packs/spells/whispering-quiet.json
  packs/spells/wilding-word.json
  packs/spells/wrathful-storm.json
Labels: pr: data update

#12714 Brush up Ebon Fulcrum Lens
  packs/equipment-effects/effect-ebon-fulcrum-lens-2-action.json
  packs/equipment-effects/effect-ebon-fulcrum-lens-incorporeal.json
  packs/equipment/ebon-fulcrum-lens.json
Labels: pr: data update

#12723 Prefer `system` over `systemData` as shorthand variable in PC class
  src/module/actor/character/document.ts
Labels: pr: refactor

#12725 Remove "Disrupting" labels from content links to Vitalizing rune item
  packs/classfeatures/blade-ally.json
  packs/equipment/celestial-peachwood-sword.json
  packs/equipment/disrupting-oil.json
  packs/equipment/ladys-spiral.json
  packs/feat-effects/effect-blade-ally.json
  packs/feats/sing-to-the-steel.json
  packs/journals/archetypes.json
  packs/journals/classes.json
  packs/pathfinder-bestiary-3/shabti-redeemer.json
Labels: pr: data update

#12727 Add toggle and trait automation for Toppling Dance
  packs/feats/shadow-of-the-wilds.json
  packs/feats/telluric-power.json
  packs/feats/toppling-dance.json
Labels: pr: data update

#12726 Accommodate dromedary-cased senses in BattleForm REs
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: bugfix

#12721 Relax equipped check for invested non-worn items
  src/module/item/physical/document.ts
  src/scripts/config/traits.ts
Labels: pr: enhancement

#12731 Add metagame settings to setting cache
  src/global.ts
  src/module/actor/party/sheet.ts
  src/module/canvas/token/object.ts
  src/module/item/spell/document.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/check/check.ts
  src/module/system/check/roll.ts
  src/module/system/settings/metagame.ts
  src/module/system/text-editor.ts
  src/scripts/set-game-pf2e.ts
Labels: pr: enhancement

#12732 Refrain from destructuring in @system/check/check.ts when retrieving single properties
  src/module/system/check/check.ts
Labels: pr: refactor

#12703 Add homebrew language rarity settings
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/menu.ts
  src/styles/settings/_homebrew.scss
  static/lang/en.json
  static/templates/system/settings/homebrew.hbs
Labels: pr: enhancement

#12735 Add crit/fumble settings to setting cache
  src/global.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/crit-fumble-cards.ts
  src/module/chat-message/document.ts
  src/module/system/damage/roll.ts
  src/module/system/settings/index.ts
  src/scripts/set-game-pf2e.ts
Labels: pr: enhancement

#12730 Extend apex support to most physical items
  src/module/actor/character/sheet.ts
  src/module/item/armor/data.ts
  src/module/item/armor/document.ts
  src/module/item/book/data.ts
  src/module/item/consumable/data.ts
  src/module/item/container/data.ts
  src/module/item/equipment/data.ts
  src/module/item/equipment/document.ts
  src/module/item/equipment/sheet.ts
  src/module/item/physical/data.ts
  src/module/item/physical/document.ts
  src/module/item/physical/sheet.ts
  src/module/item/shield/data.ts
  src/module/item/shield/document.ts
  src/module/item/treasure/data.ts
  src/module/item/weapon/data.ts
  src/scripts/config/traits.ts
  src/scripts/register-templates.ts
  src/util/delegated-collection.ts
  static/templates/compendium-browser/partials/equipment.hbs
  static/templates/items/armor-details.hbs
  static/templates/items/backpack-details.hbs
  static/templates/items/equipment-details.hbs
  static/templates/items/partials/apex.hbs
  static/templates/items/shield-details.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: enhancement

#12728 Fix effect for Resurrectionist
  packs/feat-effects/effect-resurrectionist.json
Labels: pr: data update

#12734 Use sheet actor for general tab swim/climb checks
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#12739 Remove requirement that scenes be in focus to show flanking highlights
  src/module/canvas/token/flanking-highlight/renderer.ts
Labels: pr: enhancement

#12740 Remove background from spell summaries
  src/styles/actor/_spell-collection.scss
Labels: ui/ux

#12741 Move `.tags.light` below `.tags.paizo-style` for easier intermixing
  src/styles/_tags.scss
Labels: pr: refactor

#12742 Use color and space-size variables in legacy/_chat.scss
  src/styles/legacy/_chat.scss
Labels: pr: refactor

#12744 Fix error in Dragon Disciple journal
  packs/journals/archetypes.json
Labels: pr: data update

#12746 Replace Ki Form's lawful damage with spirit
  packs/spell-effects/spell-effect-ki-form.json
Labels: pr: data update

#12747 Add effect for Familiar of Balanced Luck
  packs/familiar-abilities/familiar-of-balanced-luck.json
  packs/feat-effects/effect-familiar-of-balanced-luck.json
Labels: pr: data update

#12736 Add Dense Plating to Breakthrough Innovation choices
  packs/classfeatures/breakthrough-innovation.json
Labels: pr: data update

#12748 Pull safe style adjustments from #12738
  src/styles/_globals.scss
  src/styles/ui/sidebar/chat/_index.scss
Labels: pr: refactor

#12749 Pull more safe style adjustments from #12738
  src/styles/ui/sidebar/chat/_check.scss
Labels: pr: refactor

#12750 Dispense with "pf2e-" prefixes in reroll HTML
  src/module/chat-message/listeners/degree-of-success.ts
  src/module/chat-message/listeners/set-as-initiative.ts
  src/module/system/check/check.ts
  src/module/system/module-art.ts
  src/module/system/settings/homebrew/menu.ts
  src/styles/ui/sidebar/chat/_reroll.scss
Labels: pr: refactor

#12753 Fix level of Ranger's Perception Legend feature
  packs/classes/ranger.json
Labels: pr: data update

#12754 Fix regression in NPC sheet toggle styling, utilize css variables
  src/styles/_reset.scss
  src/styles/actor/_red-action-boxes.scss
  src/styles/actor/npc/_index.scss
Labels: pr: bugfix

#12751 Add `area-damage` roll option to class feats @Damage rolls
  packs/actions/explode.json
  packs/feats/aerial-boomerang.json
  packs/feats/all-shall-end-in-flames.json
  packs/feats/blazing-wave.json
  packs/feats/call-the-hurricane.json
  packs/feats/cranial-detonation.json
  packs/feats/dragons-rage-breath.json
  packs/feats/driving-rain.json
  packs/feats/elemental-explosion.json
  packs/feats/hail-of-splinters.json
  packs/feats/hell-of-1-000-000-needles.json
  packs/feats/ignite-the-sun.json
  packs/feats/lava-leap.json
  packs/feats/lightning-dash.json
  packs/feats/megavolt.json
  packs/feats/ostentatious-arrival.json
  packs/feats/psi-catastrophe.json
  packs/feats/rain-of-razors.json
  packs/feats/retch-rust.json
  packs/feats/ride-the-tsunami.json
  packs/feats/rising-hurricane.json
  packs/feats/roiling-mudslide.json
  packs/feats/sanguivolent-roots.json
  packs/feats/scorching-column.json
  packs/feats/shard-strike.json
  packs/feats/solar-detonation.json
  packs/feats/storm-spiral.json
  packs/feats/the-shattered-mountain-weeps.json
  packs/feats/tidal-hands.json
  packs/feats/tremor.json
  packs/feats/tumbling-lumber.json
  packs/feats/turn-the-wheel-of-seasons.json
  packs/feats/violent-unleash.json
  packs/feats/walk-through-the-conflagration.json
  packs/feats/weight-of-stone.json
  packs/feats/winters-clutch.json
Labels: pr: data update

#12758 Restore line height to GM-visibility elements
  src/styles/_globals.scss
Labels: pr: bugfix

#12759 Fix line height of gm-visibility message senders
  src/styles/_globals.scss
Labels: pr: bugfix

#12738 Add metagame information setting to show or hide roll breakdowns
  src/global.ts
  src/module/chat-message/listeners/degree-of-success.ts
  src/module/system/check/check.ts
  src/module/system/check/roll.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/roll.ts
  src/module/system/rolls.ts
  src/module/system/settings/metagame.ts
  src/scripts/hooks/dice-so-nice-roll-start.ts
  src/scripts/hooks/index.ts
  src/scripts/set-game-pf2e.ts
  src/styles/ui/sidebar/chat/_check.scss
  src/styles/ui/sidebar/chat/_index.scss
  static/lang/en.json
  static/templates/chat/check/roll.hbs
  static/templates/dice/damage-roll.hbs
  static/templates/dice/damage-tooltip.hbs
Labels: pr: enhancement

#12760 Recover gm-visibility background color on roll-message modifiers
  src/styles/_colors.scss
  src/styles/ui/sidebar/chat/_index.scss
Labels: pr: bugfix

#12761 Remove unused animation scss, move global overrides to reset file
  src/styles/_globals.scss
  src/styles/_reset.scss
  src/styles/legacy/_index.scss
  src/styles/legacy/_tooltip.scss
  src/styles/lib/_animations.scss
  src/styles/lib/_index.scss
  src/styles/main.scss
  src/styles/mixins/_animations.scss
Labels: pr: bugfix

#12757 Use system font for notes in chat messages
  src/styles/ui/sidebar/chat/_index.scss
Labels: ui/ux

#12764 Exclude granted languages when counting number of manually-added ones
  src/module/actor/character/document.ts
Labels: pr: bugfix

#12762 Allow non-kingmaker worlds to enable kingdom and army sheets
  src/module/system/settings/automation.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/index.ts
  src/module/system/settings/menu.ts
  src/module/system/settings/metagame.ts
  src/scripts/register-templates.ts
  static/lang/en.json
  static/templates/system/settings/basic-setting.hbs
  static/templates/system/settings/homebrew.hbs
  static/templates/system/settings/menu.hbs
Labels: pr: enhancement, kingmaker

#12756 Set apex attributes for Breastplate of the Mountain and Viper Rapier
  packs/equipment/breastplate-of-the-mountain.json
  packs/equipment/viper-rapier.json
Labels: pr: data update

#12763 Add fire resist to Elemental Wayfinder (Fire)
  packs/equipment/elemental-wayfinder-fire.json
Labels: pr: data update

#12766 Fix description of magic sense feat
  packs/feats/magic-sense.json
Labels: pr: data update

#12769 Catch up familiar sheet with event listener/handler changes
  src/module/actor/familiar/sheet.ts
  src/styles/actor/familiar/_index.scss
  static/templates/actors/familiar-sheet.hbs
Labels: pr: bugfix

#12768 Clean up some needlessly complex markup on PC-sheet sidebar
  src/styles/actor/character/_index.scss
  src/styles/actor/character/_proficiencies.scss
  src/styles/actor/character/_proficiency-ranks.scss
  src/styles/actor/character/_sidebar.scss
  static/templates/actors/character/partials/sidebar.hbs
Labels: pr: refactor

#12774 Fix ternary expression in Multilingual feat
  packs/feats/multilingual.json
  packs/kingmaker-bestiary/jubilost-level-8.json
  packs/kingmaker-bestiary/tristian-level-1.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/paizo-pregens/fluff-fang-level-4.json
  packs/paizo-pregens/fluff-fang.json
  packs/paizo-pregens/jaithe.json
  packs/paizo-pregens/zerryd.json
  packs/spells/shape-wood.json
  packs/spells/speak-with-stones.json
  packs/spells/wall-of-thorns.json
  src/module/migration/migrations/914-move-perception-senses.ts
Labels: pr: bugfix, pr: data update

#12773 Exclude roll-note HTML when notes arrays are empty
  src/module/notes.ts
  src/module/system/check/check.ts
  src/module/system/damage/damage.ts
Labels: ui/ux

#12775 Tighten up predicate for Beast Speaker
  packs/feats/beast-speaker.json
  packs/heritages/vine-leshy.json
Labels: pr: data update

#12776 Fix casing of Prone in action strings
  static/lang/action-en.json
Labels: pr: data update

#12777 Clean up NPC sheet markup, scss, and event listeners
  src/module/actor/creature/data.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/styles/actor/character/_sidebar.scss
  src/styles/actor/npc/_index.scss
  src/styles/actor/npc/_sidebar.scss
  src/styles/actor/npc/_simple.scss
  static/templates/actors/character/icons/d20.hbs
  static/templates/actors/character/tabs/character.hbs
  static/templates/actors/npc/partials/header.hbs
  static/templates/actors/npc/partials/sidebar.hbs
  static/templates/actors/npc/simple-sheet.hbs
  static/templates/actors/npc/tabs/main.hbs
Labels: pr: bugfix, pr: refactor, ui/ux

#12779 Remove errant `<label for="...">` attributes
  src/styles/actor/npc/_simple.scss
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/character/tabs/biography.hbs
Labels: pr: bugfix

#12781 Fix regression in display of NPC toggles
  src/styles/actor/npc/_index.scss
  static/templates/actors/npc/tabs/spells.hbs
Labels: pr: bugfix

#12767 Reference newly created summon trait GM Screen page on summon spells
  packs/journals/gm-screen.json
  packs/spells/phantasmal-minion.json
  packs/spells/summon-animal.json
  packs/spells/summon-celestial.json
  packs/spells/summon-construct.json
  packs/spells/summon-dragon.json
  packs/spells/summon-elemental.json
  packs/spells/summon-entity.json
  packs/spells/summon-fey.json
  packs/spells/summon-fiend.json
  packs/spells/summon-giant.json
  packs/spells/summon-monitor.json
  packs/spells/summon-plant-or-fungus.json
  packs/spells/summon-undead.json
Labels: pr: data update

#12765 Brush up Kobold Breath damage automation
  packs/ancestryfeatures/draconic-exemplar.json
  packs/feats/dragonblood-paragon.json
  packs/feats/dragons-breath.json
  packs/feats/kobold-breath.json
  static/lang/re-en.json
Labels: pr: data update

#12785 Fix handler of delete-attack-proficiency links on PC sheet
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/popups/manage-attack-proficiencies.ts
  src/styles/actor/character/_proficiencies.scss
  static/templates/actors/character/tabs/proficiencies.hbs
Labels: pr: bugfix

#12784 Fix casing of labels in action strings
  static/lang/action-en.json
Labels: pr: data update

#12786 Move handlers of elite/weak adjustment links to sheetwide listener
  src/module/actor/npc/sheet.ts
  static/templates/actors/npc/partials/header.hbs
Labels: pr: refactor

#12789 Update NPM dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#12788 Prevent `augmentInlineDamageRolls` from polluting RE resolvables
  src/module/rules/rule-element/base.ts
  src/module/system/text-editor.ts
Labels: pr: bugfix

#12780 Spruce up item summaries and cards
  src/module/item/feat/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
  src/styles/_colors.scss
  src/styles/actor/_item-summary.scss
  src/styles/actor/_spell-collection.scss
  src/styles/actor/character/_actions.scss
  src/styles/actor/character/_feats.scss
  src/styles/item/_feat-sheet.scss
  src/styles/legacy/_chat.scss
  static/templates/actors/partials/item-summary.hbs
  static/templates/chat/armor-card.hbs
  static/templates/chat/backpack-card.hbs
  static/templates/chat/consumable-card.hbs
  static/templates/chat/equipment-card.hbs
  static/templates/chat/feat-card.hbs
  static/templates/chat/melee-card.hbs
  static/templates/chat/shield-card.hbs
  static/templates/chat/spell-card.hbs
  static/templates/chat/strike-card.hbs
  static/templates/chat/treasure-card.hbs
  static/templates/chat/weapon-card.hbs
Labels: ui/ux

#12791 Update Vicious Swing publication to remaster
  packs/feats/vicious-swing.json
Labels: pr: data update

#12787 Remove necessity for having multiple marshal's aura effects
  packs/feat-effects/effect-dread-marshal-stance.json
  packs/feat-effects/effect-inspiring-marshal-stance.json
  packs/feat-effects/stance-dread-marshal-stance.json
  packs/feat-effects/stance-inspiring-marshal-stance.json
Labels: pr: data update

#12783 Tidy Yabin the Just (Level 9)'s Nagaji Venom description
  packs/fists-of-the-ruby-phoenix-bestiary/yabin-the-just-level-9.json
Labels: pr: data update

#12782 Brush up Hadrinnex
  packs/bestiary-effects/effect-vent-energy.json
  packs/pathfinder-bestiary-3/hadrinnex.json
  static/lang/re-en.json
Labels: pr: data update

#12795 Tweak positioning of "Feat N" phrase in expanded feat summaries
  src/module/actor/base.ts
  src/styles/_fonts.scss
  src/styles/actor/character/_feats.scss
Labels: ui/ux

#12793 Include RE from Marshal's Aura effect in Devrin's Cunning Stance effect
  packs/feat-effects/effect-devrins-cunning-stance.json
  packs/feat-effects/stance-devrins-cunning-stance.json
Labels: pr: data update

#12794 Set healing type on several healing links
  packs/abomination-vaults-bestiary/khurfel.json
  packs/age-of-ashes-bestiary/kalavakus.json
  packs/agents-of-edgewatch-bestiary/tyrroicese.json
  packs/bestiary-family-ability-glossary/ghost-draining-touch.json
  packs/extinction-curse-bestiary/flea-swarm.json
  packs/extinction-curse-bestiary/giant-flea.json
  packs/extinction-curse-bestiary/kharostan.json
  packs/extinction-curse-bestiary/ulthadar.json
  packs/extinction-curse-bestiary/urdefhan-dominator.json
  packs/extinction-curse-bestiary/urdefhan-high-tormentor.json
  packs/extinction-curse-bestiary/urdefhan-hunter.json
  packs/fists-of-the-ruby-phoenix-bestiary/kannitri.json
  packs/kingmaker-bestiary/the-gardener.json
  packs/pathfinder-bestiary-2/urdefhan-tormentor.json
  packs/pathfinder-bestiary-2/urdefhan-warrior.json
  packs/pfs-season-4-bestiary/urdefhan-high-tormentor-pfs-4-11.json
  packs/quest-for-the-frozen-flame-bestiary/turkek.json
  packs/strength-of-thousands-bestiary/crawling-slurry.json
Labels: pr: data update

#12796 Add automation for Jann's Prism
  packs/equipment-effects/effect-janns-prism-janns-light.json
  packs/equipment/janns-prism.json
Labels: pr: data update

#12797 Release Notes 5.12.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#12800 Tweak placement of nested feat summaries
  src/styles/_globals.scss
  src/styles/actor/character/_feats.scss
Labels: ui/ux

#12804 Fix cases of erroneous PC language slot calculations
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#12802 Hide all buttons in `isPrivate` damage rolls
  static/templates/dice/damage-roll.hbs
Labels: pr: bugfix

#12803 Restore default of re-rendering actor sheets in `resetActors` helper
  src/module/actor/helpers.ts
Labels: pr: bugfix

#12805 Restore display of stamina on character sheet
  src/styles/actor/character/_sidebar.scss
  static/templates/actors/character/partials/sidebar.hbs
Labels: pr: bugfix

#12806 Fix notifications of failed migrations for individual actors and items
  src/module/migration/runner/index.ts
Labels: pr: bugfix

#12812 Add Wildsong language to Druidic Dedication feat
  packs/feats/druid-dedication.json
Labels: pr: data update

#12814 Fix opening AC modifiers on PC sheet
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/partials/modifiers-tooltip.hbs
Labels: pr: bugfix

#12817 Fix shimming of ritual sheet data
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/rituals.ts
  src/module/item/spellcasting-entry/types.ts
Labels: pr: bugfix

#12819 Disable checkboxes of granted languages even if also added manually
  src/module/system/tag-selector/languages.ts
Labels: ui/ux

#12820 Update handful of spell and feat icons
  packs/actions/arcane-cascade.json
  packs/agents-of-edgewatch-bestiary/daemonic-infector.json
  packs/agents-of-edgewatch-bestiary/jonis-flakfatter.json
  packs/agents-of-edgewatch-bestiary/secret-keeper.json
  packs/blood-lords-bestiary/shabti-votary.json
  packs/classfeatures/arcane-cascade.json
  packs/feat-effects/effect-devrins-cunning-stance.json
  packs/feat-effects/stance-arcane-cascade.json
  packs/feat-effects/stance-devrins-cunning-stance.json
  packs/pfs-season-4-bestiary/sounrel-3-4.json
  packs/pfs-season-4-bestiary/sounrel-5-6.json
  packs/quest-for-the-frozen-flame-bestiary/ivarsa.json
  packs/spells/biting-words.json
  packs/spells/eradicate-undeath.json
  packs/the-enmity-cycle-bestiary/amar.json
  static/icons/features/classes/arcane-cascade.webp
  static/icons/features/feats/devrins-cunning-stance.webp
  static/icons/spells/biting-words.webp
  static/icons/spells/eradicate-undeath.webp
Labels: pr: data update, pr: static assets

#12821 Release Notes 5.12.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#12827 Fix Ghostly Weapon to apply only to selected weapon
  packs/spell-effects/spell-effect-ghostly-weapon.json
  packs/spells/ghostly-weapon.json
Labels: pr: data update

#12830 Fix overlapping images in compendium browser
  src/styles/packs/_tab.scss
Labels: pr: bugfix

#12824 Fix escape action to be able to use saving throw statistics
  src/module/system/action-macros/basic/escape.ts
Labels: pr: bugfix

#12833 Fix style when feat summaries are expanded
  src/styles/actor/character/_feats.scss
Labels: pr: bugfix, ui/ux

#12832 Fix PC sheet character details sizing
  src/styles/actor/character/_character.scss
Labels: pr: bugfix, ui/ux

#12834 Update REs in Burn It! feat to match text in Player Core
  packs/feats/burn-it.json
Labels: pr: data update

#12843 Restore level data to template.json spell defaults
  static/template.json
Labels: pr: bugfix

#12844 Restore level data to template.json effect defaults
  static/template.json
Labels: pr: bugfix

#12836 Fix setting Champion class DC on Champion Dedication
  packs/feats/champion-dedication.json
Labels: pr: data update

#12842 Data Entry World fixes for Jan 2023
  packs/adventure-specific-actions/forgive-foe.json
  packs/bestiary-effects/effect-forgiven-defaced-naiad-queens-thanks.json
  packs/campaign-effects/effect-forgive-foe.json
  packs/criticaldeck/critical-fumble-deck-51.json
  packs/kingmaker-bestiary/defaced-naiad-queen.json
  packs/kingmaker-bestiary/phomandala.json
Labels: pr: data update

#12845 Accommodate unmigrated class DC attribute AE-likes
  packs/feats/fighter-dedication.json
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/migration/migrations/870-martial-to-proficiencies.ts
Labels: pr: bugfix

#12846 Fix outdated ancestry sheet low-light-vision value
  static/templates/items/ancestry-sidebar.hbs
Labels: pr: bugfix

#12847 Fix formula-drop listener in PC-sheet crafting tab
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/styles/actor/_index.scss
  src/styles/actor/character/_crafting.scss
  src/styles/actor/character/_feats.scss
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/actors/crafting-entry-alchemical.hbs
  static/templates/actors/crafting-entry-list.hbs
Labels: pr: bugfix

#12849 Include `showBreakdown` option in spell damage rolls
  src/module/item/spell/document.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/types.ts
Labels: pr: bugfix

#12850 Normalize temp HP before updating
  src/module/actor/creature/data.ts
  src/module/actor/creature/document.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/data.ts
  src/module/actor/npc/data.ts
Labels: pr: bugfix
