Repository foundryvtt/pf2e, pull requests merged in 2024-08, with the labels that each got.

#15653 Include action-specific modifiers for action check previews
  src/module/actor/actions/single-check.ts
Labels: pr: enhancement

#15660 Add missing Goading Feint localized Note
  static/lang/re-en.json
Labels: pr: data update

#15655 Add automation for Gruhastha - Moderate Boon
  packs/boons-and-curses/gruhastha-moderate-boon.json
  static/lang/re-en.json
Labels: pr: data update

#15648 add max dice to Dice Number formula for Amped Redistribute Potential
  packs/classfeatures/the-oscillating-wave.json
Labels: pr: data update

#15646 Add starshot arrow activation
  packs/equipment/starshot-arrow-greater.json
  packs/equipment/starshot-arrow-lesser.json
Labels: pr: data update

#15645 Add effects for Insight Coffee
  packs/equipment-effects/effect-insight-coffee-greater.json
  packs/equipment-effects/effect-insight-coffee-lesser.json
  packs/equipment-effects/effect-insight-coffee-moderate.json
  packs/equipment/insight-coffee-greater.json
  packs/equipment/insight-coffee-lesser.json
  packs/equipment/insight-coffee-moderate.json
Labels: pr: data update

#15635 Add spell variants for establish ward
  packs/spells/establish-ward.json
Labels: pr: data update

#15625 Brush up Goblin Zombie
  packs/blog-bestiary/goblin-zombie.json
  packs/feats/eerie-proclamation.json
  packs/hazards/spinning-blade-pillar.json
  packs/seven-dooms-for-sandpoint-bestiary/divine-warden-of-haagenti.json
  packs/spells/creative-splash.json
Labels: pr: data update

#15622 Remove Deep Backgrounds roll tables
  packs/journals/deep-backgrounds.json
  packs/rollable-tables/challenging-relationship.json
  packs/rollable-tables/homeland.json
  packs/rollable-tables/influential-associate.json
  packs/rollable-tables/inspiring-relationship.json
  packs/rollable-tables/major-childhood-event.json
Labels: pr: data update

#15613 Add icons to remaining Howl of the Wild spells
  packs/spells/albatross-curse.json
  packs/spells/antlion-trap.json
  packs/spells/blood-in-the-water.json
  packs/spells/camel-spit.json
  packs/spells/confusing-cry.json
  packs/spells/croak-voice.json
  packs/spells/foraging-friends.json
  packs/spells/frog-tongue.json
  packs/spells/hidebound.json
  packs/spells/luring-wail.json
  packs/spells/primal-chorus.json
  packs/spells/sacred-beasts.json
  packs/spells/spirit-of-the-beast.json
  packs/spells/summon-stampede.json
Labels: pr: data update

#15592 Add effects for new Howl of the Wild Animal Forms.
  packs/spell-effects/spell-effect-animal-form-crab.json
  packs/spell-effects/spell-effect-animal-form-crocodile.json
  packs/spell-effects/spell-effect-animal-form-orca.json
  packs/spell-effects/spell-effect-animal-form-seal.json
  packs/spells/animal-form.json
Labels: pr: data update

#15612 Update Retraining description to remaster
  packs/actions/invest-an-item.json
  packs/actions/long-term-rest.json
  packs/actions/retraining.json
Labels: pr: data update

#15629 Fix Performance bonus for Dancing Scarf
  packs/equipment/dancing-scarf.json
Labels: pr: data update

#15663 Fix typo in Bravado trait label
  src/scripts/config/traits.ts
Labels: pr: data update

#15669 Resolve injected properties in AdjustDegreeOfSuccess predicates
  src/module/rules/rule-element/adjust-degree-of-success.ts
Labels: pr: bugfix

#15670 Emphasize spell names in psychic amp description alterations
  static/lang/re-en.json
Labels: pr: data update

#15671 Fix cursor on spellcasting entry drag handles
  src/styles/actor/_index.scss
Labels: ui/ux

#15667 Fix some PC2 sources
  packs/bestiary-effects/effect-aggravating-aura.json
  packs/classfeatures/perception-legend.json
  packs/equipment/comprehension-elixir-lesser.json
  packs/equipment/corrosive-ammunition.json
  packs/equipment/crystal-shards-moderate.json
  packs/equipment/deadweight-snare.json
  packs/equipment/exploding-shield.json
  packs/equipment/hampering-snare.json
  packs/equipment/medusas-scream.json
  packs/equipment/potion-of-electricity-retaliation-greater.json
  packs/equipment/potion-of-electricity-retaliation-lesser.json
  packs/equipment/potion-of-electricity-retaliation-major.json
  packs/equipment/potion-of-electricity-retaliation-minor.json
  packs/equipment/potion-of-electricity-retaliation-moderate.json
  packs/equipment/surging-serum-moderate.json
  packs/equipment/witchwarg-elixir-greater.json
  packs/equipment/witchwarg-elixir-lesser.json
  packs/equipment/witchwarg-elixir-moderate.json
  packs/feats/armored-stealth.json
  packs/feats/blessed-sacrifice.json
  packs/feats/blessed-spell.json
  packs/feats/linguist-dedication.json
  packs/feats/retreating-finisher.json
  packs/feats/warren-navigator.json
  packs/heritages/hobgoblin/runtboss-hobgoblin.json
  packs/pathfinder-bestiary-3/nyktera.json
  packs/spells/moonlight-bridge.json
  static/lang/re-en.json
Labels: pr: data update

#15664 Localize some strings for PC2
  packs/equipment-effects/effect-sip-of-justice.json
  packs/feats/assassinate.json
  packs/feats/incorporeal-shot.json
  static/lang/re-en.json
Labels: pr: data update

#15665 Remove placeholder cursebound effect
  packs/feat-effects/effect-cursebound.json
Labels: pr: data update

#15666 Add missing localization strings
  packs/feats/illimitable-finisher.json
  packs/feats/sacred-defender.json
  static/lang/re-en.json
Labels: pr: data update

#15678 Add dragonblood trait
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#15679 Add Content from The Great Toy Heist
  packs/one-shot-bestiary/soulbound-guardian.json
  packs/one-shot-bestiary/splitsoul-object.json
  packs/paizo-pregens/cutie-killstuff.json
  packs/paizo-pregens/flappy.json
  packs/paizo-pregens/hellpup.json
  packs/paizo-pregens/marcella-the-marionette.json
  packs/paizo-pregens/the-tin-wizard.json
Labels: pr: data entry

#15677 Fix some token names
  packs/campaign-effects/effect-vicious-bluster-critical-success.json
  packs/campaign-effects/effect-vicious-bluster.json
  packs/feats/enjoy-the-show.json
  packs/feats/one-for-all.json
  packs/pfs-season-6-bestiary/abendegos-squall-1-2.json
  packs/pfs-season-6-bestiary/abendegos-squall-3-4.json
  packs/pfs-season-6-bestiary/abendegos-squall-5-6.json
  packs/pfs-season-6-bestiary/abendegos-squall-7-8.json
  packs/pfs-season-6-bestiary/accursed-cargo-1-2.json
  packs/pfs-season-6-bestiary/accursed-cargo-3-4.json
  packs/pfs-season-6-bestiary/accursed-cargo-5-6.json
  packs/pfs-season-6-bestiary/accursed-cargo-7-8.json
  packs/pfs-season-6-bestiary/averill-quint-1-2.json
  packs/pfs-season-6-bestiary/averill-quint-3-4.json
  packs/pfs-season-6-bestiary/averill-quint-5-6.json
  packs/pfs-season-6-bestiary/averill-quint-7-8.json
  packs/pfs-season-6-bestiary/blood-elegecide-doom-demon.json
  packs/pfs-season-6-bestiary/demon-ark.json
  packs/pfs-season-6-bestiary/demon-launch.json
  packs/pfs-season-6-bestiary/demon-ship.json
  packs/pfs-season-6-bestiary/elegecide-doom-demon.json
  packs/pfs-season-6-bestiary/getidline-riptide-demon.json
  packs/pfs-season-6-bestiary/haunting-elegecide-doom-demon.json
  packs/pfs-season-6-bestiary/historys-repetition-1-2.json
  packs/pfs-season-6-bestiary/historys-repetition-3-4.json
  packs/pfs-season-6-bestiary/historys-repetition-5-6.json
  packs/pfs-season-6-bestiary/historys-repetition-7-8.json
  packs/pfs-season-6-bestiary/hostile-architecture-1-2.json
  packs/pfs-season-6-bestiary/hostile-architecture-3-4.json
  packs/pfs-season-6-bestiary/hostile-architecture-5-6.json
  packs/pfs-season-6-bestiary/hostile-architecture-7-8.json
  packs/pfs-season-6-bestiary/sailors-warning-1-2.json
  packs/pfs-season-6-bestiary/sailors-warning-3-4.json
  packs/pfs-season-6-bestiary/sailors-warning-5-6.json
  packs/pfs-season-6-bestiary/sailors-warning-7-8.json
  packs/pfs-season-6-bestiary/singe-1-2.json
  packs/pfs-season-6-bestiary/singe-3-4.json
  packs/pfs-season-6-bestiary/singe-5-6.json
  packs/pfs-season-6-bestiary/singe-7-8.json
Labels: pr: data update

#15681 Release Notes 6.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#15684 Brushup Robust Health
  packs/feats/robust-health.json
Labels: pr: data update

#15675 Update Kobold Ancestry for PC2
  packs/ancestries/kobold.json
Labels: pr: data update

#15687 Fix Max Take count to 3 for Voluminous Vials Feat
  packs/feats/voluminous-vials.json
Labels: pr: data update

#15690 Fix link to Soothe in Life Oracle
  packs/classfeatures/life.json
Labels: pr: data update

#15693 Update Bestial Mutagen automation
  packs/equipment-effects/effect-bestial-mutagen-greater.json
  packs/equipment-effects/effect-bestial-mutagen-lesser.json
  packs/equipment-effects/effect-bestial-mutagen-major.json
  packs/equipment-effects/effect-bestial-mutagen-moderate.json
Labels: pr: data update

#15694 Add action cost to Breath of the Dragon dragonblood feat
  packs/classfeatures/furious-footfalls.json
  packs/feats/breath-of-the-dragon-dragonblood.json
Labels: pr: data update

#15695 Add missing text and proficiency scaling for Herbalist dedication
  packs/feats/herbalist-dedication.json
Labels: pr: data update

#15696 update formatting for PC2 Ancestries in Ancestry Journal
  packs/journals/ancestries.json
Labels: pr: data update

#15699 Increase max token subject scale to 3
  static/templates/scene/token/partials/appearance.hbs
Labels: pr: bugfix

#15701 Keep token subject scale step at 0.2
  static/templates/scene/token/partials/appearance.hbs
Labels: pr: bugfix

#15672 Add support for spell area size alterations
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  static/templates/items/spell-details.hbs
Labels: pr: enhancement

#15708 Fix zero option of fundamental rune select elements on item sheets
  static/templates/items/armor-details.hbs
  static/templates/items/shield-details.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: bugfix

#15713 Correct text on Stylish Tricks
  packs/classfeatures/stylish-tricks.json
Labels: pr: data update

#15702 Fix Bestial Mutagen description and Oracle spellcasting table
  packs/equipment/bestial-mutagen-greater.json
  packs/equipment/bestial-mutagen-lesser.json
  packs/equipment/bestial-mutagen-major.json
  packs/equipment/bestial-mutagen-moderate.json
  packs/journals/classes.json
Labels: pr: data update

#15704 Quick extractAll post content release
  packs/feats/robust-health.json
  packs/pfs-season-6-bestiary/damned-gargarthezul-captain.json
  packs/pfs-season-6-bestiary/immoral-gargarthezul-captain.json
  packs/pfs-season-6-bestiary/immoral-gargarthezul.json
  packs/spell-effects/spell-effect-animal-form-crab.json
  packs/spell-effects/spell-effect-animal-form-crocodile.json
  packs/spell-effects/spell-effect-animal-form-orca.json
  packs/spell-effects/spell-effect-animal-form-seal.json
Labels: pr: data update

#15716 Rearrange deity to be granted before cause on Champion
  packs/classes/champion.json
  packs/classfeatures/deity-champion.json
  packs/feats/champion-dedication.json
  packs/journals/classes.json
Labels: pr: data update

#15717 Update Crossblooded Evolution description
  packs/feats/crossblooded-evolution.json
Labels: pr: data update

#15707 Add support for homebrew shield traits
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/helpers.ts
  src/module/system/settings/homebrew/menu.ts
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: enhancement

#15722 Add structure trait to Resplendent Mansion
  packs/spells/resplendent-mansion.json
  src/scripts/config/traits.ts
Labels: pr: data update

#15715 Fix Certain Stratagem damage roll
  packs/equipment-effects/effect-insight-coffee-greater.json
  packs/equipment-effects/effect-insight-coffee-lesser.json
  packs/equipment-effects/effect-insight-coffee-moderate.json
  static/lang/re-en.json
Labels: pr: data update

#15719 Brush up Champion reactions implementation
  packs/actions/destructive-vengeance.json
  packs/actions/flash-of-grandeur.json
  packs/actions/glimpse-of-redemption.json
  packs/actions/iron-command.json
  packs/actions/liberating-step.json
  packs/actions/retributive-strike.json
  packs/actions/selfish-shield.json
  packs/classfeatures/exalted-reaction.json
  packs/classfeatures/relentless-reaction.json
  packs/feat-effects/effect-champions-extra-damage.json
  packs/feat-effects/effect-selfish-shield.json
  packs/feats/dragonslayer-oath.json
  packs/feats/esoteric-oath.json
  packs/feats/fiendsbane-oath.json
  packs/feats/gruesome-strike.json
  packs/feats/instrument-of-slaughter.json
  packs/feats/instrument-of-zeal.json
  packs/feats/shining-oath.json
  static/lang/re-en.json
Labels: pr: data update

#15720 Correct details on some PC2 archetype feats
  packs/feats/into-the-fray.json
  packs/feats/lightning-snares.json
  packs/feats/running-tackle.json
  packs/feats/swift-guardian.json
Labels: pr: data update

#15721 Restore missing Seal Fate spell effect link
  packs/spells/seal-fate.json
Labels: pr: data update

#15724 Allow Champion's Aura to be granted to archetype champions
  packs/classfeatures/deity-champion.json
Labels: pr: data update

#15725 Fix typo and update links on Champion Armament feats
  packs/feats/armament-paragon.json
  packs/feats/radiant-armament.json
Labels: pr: data update

#15732 Fix regression in handling of area data on spell sheet
  src/module/item/spell/sheet.ts
Labels: pr: bugfix

#15734 Add roll options for spell area data
  src/module/item/spell/document.ts
Labels: pr: enhancement

#15652 Replace inline roll defense param for against and support all statistics
  src/module/system/statistic/statistic.ts
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: new feature

#15731 Fix dimensions of pathfinder logo on PC sheet
  src/styles/actor/character/_sidebar.scss
  static/templates/actors/character/sheet.hbs
Labels: ui/ux

#15738 Increase area of Amped Redistribute Potential
  packs/classfeatures/the-oscillating-wave.json
Labels: pr: data update

#15703 Remove Unreachable Hex Check
  src/module/canvas/layer/template.ts
Labels: pr: refactor

#15730 Link damage and conditions on Age of Ashes NPC poison
  packs/age-of-ashes-bestiary/mud-spider.json
  packs/journals/classes.json
Labels: pr: data update

#15733 Grant Draconic Exemplar to Kobolds using legacy feats
  packs/feats/dracomancer.json
  packs/feats/kobold-breath.json
Labels: pr: data update

#15735 Fix selector for Hone Claws effect
  packs/feat-effects/effect-hone-claws.json
Labels: pr: data update

#15736 Automate dragonblood's Draconic Exemplar feats
  packs/feats/breath-of-the-dragon-dragonblood.json
  packs/feats/draconic-resistance.json
  packs/feats/formidable-breath.json
  packs/feats/lingering-breath.json
  packs/heritages/versatile-heritages/dragonblood.json
  static/lang/re-en.json
Labels: pr: data update

#15737 Automate Widen Spell
  packs/feats/widen-spell.json
Labels: pr: data update

#15741 Add missing Spirit Sense spell effect link
  packs/spells/spirit-sense.json
Labels: pr: data update

#15742 Add description alteration to Overwhelming Breath Monk Feat
  packs/feats/overwhelming-breath.json
  static/lang/re-en.json
Labels: pr: data update

#15740 Limit some material equivalences for IWR
  src/module/actor/data/iwr.ts
Labels: pr: bugfix

#15747 Add armor roll option for strength requirement
  src/module/item/armor/document.ts
Labels: pr: enhancement

#15759 Reduce token scale step value to 0.05
  static/templates/scene/token/partials/appearance.hbs
Labels: pr: enhancement

#15763 add description alteration and roll options to Oracle Spellshape feats.
  packs/feat-effects/effect-portentous-spell.json
  packs/feats/knowledge-of-shapes.json
  packs/feats/mystery-conduit.json
  packs/feats/portentous-spell.json
  packs/feats/surging-might.json
  static/lang/re-en.json
Labels: pr: data update

#15757 Update Mark for Death action
  packs/actions/mark-for-death.json
Labels: pr: data update

#15756 Rename Sulfur Bomb effect
  packs/equipment-effects/effect-sulfur-bomb.json
  packs/equipment/sulfur-bomb-greater.json
  packs/equipment/sulfur-bomb-lesser.json
  packs/equipment/sulfur-bomb-major.json
  packs/equipment/sulfur-bomb-moderate.json
  packs/sky-kings-tomb-bestiary/ashrin.json
  static/lang/re-en.json
Labels: pr: data update

#15751 Update Marshal Stances effects
  packs/feat-effects/effect-dread-marshal-stance.json
  packs/feat-effects/stance-dread-marshal-stance.json
  packs/feat-effects/stance-inspiring-marshal-stance.json
  packs/feats/dread-marshal-stance.json
  packs/feats/inspiring-marshal-stance.json
Labels: pr: data update

#15748 Add shepherd of decay as source for some items
  packs/equipment/burglars-rosebud-greater.json
  packs/equipment/burglars-rosebud.json
  packs/equipment/durian-bomb-greater.json
  packs/equipment/durian-bomb-lesser.json
  packs/equipment/durian-bomb-major.json
  packs/equipment/durian-bomb-moderate.json
Labels: pr: data update

#15723 Fix ranged attack penalty on Tempest curse
  packs/classfeatures/tempest.json
Labels: pr: data update

#15745 Update some blood magic effect descriptions
  packs/feat-effects/effect-elemental-blood-magic-self.json
  packs/feat-effects/effect-fey-blood-magic.json
  packs/feat-effects/effect-imperial-blood-magic.json
Labels: pr: data update

#15766 update spells on miscellaneous actors
  packs/kingmaker-bestiary/bloom-cultist.json
  packs/kingmaker-bestiary/darivan.json
  packs/rage-of-elements-bestiary/vault-builder.json
  packs/rage-of-elements-bestiary/zephyr-the-west-wind.json
  packs/rage-of-elements-bestiary/zuhra-shuyookh.json
Labels: pr: data update

#15774 Include `engines.node` in package-lock.json
  package-lock.json
Labels: pr: housekeeping

#15775 Fix retrieval of origin roll options from aura-transmitted effects
  src/module/actor/base.ts
Labels: pr: bugfix

#15772 Make `StrikeRuleElement#graspingAppendage` overridable for fists and claws
  src/module/rules/rule-element/strike.ts
Labels: pr: enhancement

#15769 Set all ephemeral effects to have unlimited duration
  src/module/rules/helpers.ts
  src/module/rules/rule-element/ephemeral-effect.ts
Labels: pr: enhancement

#15783 Fix regression in metagame-setting-dependent hiding of damage-button cues
  src/module/chat-message/document.ts
  src/scripts/ui/user-visibility.ts
Labels: pr: bugfix

#15780 change Sustain toggle for Angelic Halo effect and aura
  packs/spell-effects/aura-angelic-halo.json
  packs/spell-effects/spell-effect-angelic-halo.json
Labels: pr: data update

#15792 Shorten key for skills in `ModuleHomebrewData`
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/helpers.ts
  src/module/system/settings/homebrew/menu.ts
Labels: pr: refactor

#15795 correct Advanced Herbalism from Class Feature to Class Feat
  packs/feats/advanced-herbalism.json
Labels: pr: data update

#15770 Remove use of `isObject` system helper in `ElementalBlast` class
  src/module/actor/character/elemental-blast.ts
Labels: pr: refactor

#15799 Fix negative base modifiers getting dropped from NPC attacks
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#15807 Use dots transition animation in fine powder effect
  src/module/actor/base.ts
  src/module/item/effect/helpers.ts
Labels: pr: enhancement

#15821 Add Dragonblood trait to Dragon's Flight feat.
  packs/feats/dragons-flight.json
Labels: pr: data update

#15823 Correct typo on Kingmaker actor (Lickweed)
  packs/kingmaker-bestiary/lickweed.json
Labels: pr: data update

#15802 Add support for homebrew armor groups and base types
  src/module/item/armor/sheet.ts
  src/module/item/weapon/sheet.ts
  src/module/migration/migrations/893-no-hb-prefix-settings.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/helpers.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/settings/menu.ts
  static/lang/en.json
  static/templates/items/armor-details.hbs
  static/templates/items/weapon-details.hbs
  static/templates/system/settings/homebrew.hbs
Labels: pr: enhancement

#15837 Correct Long Hammer's rarity to common
  packs/equipment/long-hammer.json
Labels: pr: data update

#15835 Remove Invisible condition link from Connect the Dots
  packs/feats/connect-the-dots.json
  packs/journals/archetypes.json
Labels: pr: data update

#15834 Update Alchemical Assessment description
  packs/feats/alchemical-assessment.json
Labels: pr: data update

#15833 Update Invisible Item and Leaden Steps spell data
  packs/spells/invisible-item.json
  packs/spells/leaden-steps.json
Labels: pr: data update

#15812 Fix Ghoul Stalker's token name
  packs/pathfinder-monster-core/ghoul-stalker.json
Labels: pr: data update

#15786 add description alterations for Sorcerer Spellshape feats
  packs/feats/bloodline-conduit.json
  packs/feats/energy-fusion.json
  packs/feats/interweave-dispel.json
  packs/feats/safeguard-spell.json
  packs/feats/spell-shroud.json
  packs/feats/split-shot.json
  static/lang/re-en.json
Labels: pr: data update

#15800 Add Journals for Howl of the Wild Ancestries
  packs/ancestries/athamaru.json
  packs/ancestries/awakened-animal.json
  packs/ancestries/centaur.json
  packs/ancestries/merfolk.json
  packs/ancestries/minotaur.json
  packs/ancestries/surki.json
  packs/journals/ancestries.json
Labels: pr: data entry

#15785 add Howl of the Wild options to the Untamed Form feat.
  packs/feats/untamed-form.json
Labels: pr: data update

#15782 update more icons on select items and effects
  packs/equipment-effects/effect-auric-noodles.json
  packs/equipment-effects/effect-cinnamon-seers.json
  packs/equipment-effects/effect-ghostcallers-planchette-armor-greater.json
  packs/equipment-effects/effect-ghostcallers-planchette-armor.json
  packs/equipment-effects/effect-ghostcallers-planchette-weapon-greater.json
  packs/equipment-effects/effect-ghostcallers-planchette-weapon.json
  packs/equipment-effects/effect-starsong-nectar.json
  packs/equipment/cinnamon-seers.json
  packs/equipment/ghostcallers-planchette-greater.json
  packs/equipment/ghostcallers-planchette.json
  packs/equipment/starsong-nectar.json
  packs/spell-effects/spell-effect-hidebound.json
  packs/spell-effects/spell-effect-spirit-of-the-beast.json
Labels: pr: data update

#15771 Remove uuid being used as roll option in Kinetic Gate class feature
  packs/classfeatures/kinetic-gate.json
Labels: pr: data update

#15768 Remove Champion's Code class features and feats/spells depending on them
  packs/classfeatures/champions-code.json
  packs/classfeatures/the-tenets-of-evil.json
  packs/classfeatures/the-tenets-of-good.json
  packs/feat-effects/effect-liberating-step-vs-aberration.json
  packs/feat-effects/effect-liberating-step-vs-dragon.json
  packs/feat-effects/effect-liberating-step-vs-fiend.json
  packs/feat-effects/effect-liberating-step-vs-undead.json
  packs/feat-effects/effect-smite-good.json
  packs/feats/aura-of-unbreakable-virtue.json
  packs/feats/blade-of-justice.json
  packs/feats/celestial-form.json
  packs/feats/celestial-mount.json
  packs/feats/conceited-mindset.json
  packs/feats/corrupted-shield.json
  packs/feats/dragonslayer-oath.json
  packs/feats/esoteric-oath.json
  packs/feats/fiendish-form.json
  packs/feats/fiendish-mount.json
  packs/feats/fiendsbane-oath.json
  packs/feats/lightslayer-oath.json
  packs/feats/litany-against-sloth.json
  packs/feats/litany-against-wrath.json
  packs/feats/litany-of-depravity.json
  packs/feats/litany-of-righteousness.json
  packs/feats/litany-of-self-interest.json
  packs/feats/pale-horse.json
  packs/feats/sense-evil.json
  packs/feats/sense-good.json
  packs/feats/shining-oath.json
  packs/feats/smite-good.json
  packs/journals/archetypes.json
  packs/journals/remaster-changes.json
  packs/spell-effects/spell-effect-litany-of-depravity.json
  packs/spell-effects/spell-effect-litany-of-righteousness.json
  packs/spell-effects/spell-effect-litany-of-self-interest.json
  packs/spells/litany-against-sloth.json
  packs/spells/litany-against-wrath.json
  packs/spells/litany-of-depravity.json
  packs/spells/litany-of-righteousness.json
  packs/spells/litany-of-self-interest.json
Labels: pr: data update

#15810 Add spawn of dahak
  packs/age-of-ashes-bestiary/spawn-of-dahak.json
Labels: pr: data entry

#15832 Add description override to You're Next depending on the class
  packs/feats/youre-next.json
  static/lang/re-en.json
Labels: pr: data update

#15842 Fix damage dialog toggles not reflecting correct state
  static/templates/chat/check-modifiers-dialog.hbs
  static/templates/chat/damage/damage-modifier-dialog.hbs
Labels: pr: bugfix

#15840 Correct Harpy Hungry Winds action cost
  packs/pathfinder-monster-core/harpy.json
Labels: pr: data update

#15847 Add spell effect for Leaden Steps
  packs/spell-effects/spell-effect-leaden-steps.json
  packs/spells/leaden-steps.json
Labels: pr: data update

#15848 change Barding of the Zephyr and Waverider Barding to armor
  packs/equipment/barding-of-the-zephyr.json
  packs/equipment/waverider-barding.json
Labels: pr: data update

#15851 update Fling Magic to use damage syntax for rolls
  packs/actions/fling-magic.json
Labels: pr: data update

#15805 update Courageous Anthem effect to hide Discordant Voice damage dice
  packs/spell-effects/spell-effect-courageous-anthem.json
Labels: pr: data update

#15850 Brush up Hunter's Bow
  packs/equipment/hunters-bow.json
  packs/kingmaker-bestiary/armies/tusker-riders.json
Labels: pr: data update

#15853 update Barding Saddle to armor
  packs/equipment/barding-saddle.json
Labels: pr: data update

#15854 Brush up some Barbarian feats
  packs/feats/inner-strength.json
  packs/feats/scars-of-steel.json
  packs/feats/scouring-rage.json
  packs/feats/wounded-rage.json
Labels: pr: data update

#14920 Add Witch trait to Whisper of Wings
  packs/classfeatures/whisper-of-wings.json
Labels: pr: data update

#15527 add Effect to Albatross Curse spell
  packs/spell-effects/effect-albatross-curse-circumstance-bonus.json
  packs/spell-effects/effect-albatross-curse.json
  packs/spells/albatross-curse.json
Labels: pr: data update

#14772 Automate Persistent Boost
  packs/classfeatures/offensive-boost.json
  packs/feat-effects/effect-offensive-boost.json
  packs/feats/persistent-boost.json
  static/lang/re-en.json
Labels: pr: data update

#15859 Fix DC label in check when rolling an inline roll with against
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#15856 Brush up Fire Shield effect
  packs/classfeatures/the-oscillating-wave.json
  packs/spell-effects/spell-effect-fire-shield.json
Labels: pr: data update

#15863 Update the icon for Treat Wounds Immunity
  packs/feat-effects/effect-treat-wounds-immunity.json
Labels: pr: data update

#15865 Grant proficiency to advanced deity weapon with Deific Weapon
  packs/classfeatures/deific-weapon.json
Labels: pr: data update

#15868 Restrict weapon proficiency granted by Tengu Weapon Familiarity
  packs/feats/tengu-weapon-familiarity.json
Labels: pr: data update

#15861 Automate Advanced Weapon Training
  packs/feats/advanced-weapon-training.json
  packs/feats/scars-of-steel.json
  packs/feats/untamed-form.json
Labels: pr: data update

#15869 Update Herbalist Dedication batch size to match PC2
  packs/feats/herbalist-dedication.json
Labels: pr: data update

#15814 Automate Player Core 2 Sorcerer Blood Magic Feats
  packs/classfeatures/bloodline-aberrant.json
  packs/classfeatures/bloodline-angelic.json
  packs/classfeatures/bloodline-demonic.json
  packs/classfeatures/bloodline-diabolic.json
  packs/classfeatures/bloodline-draconic.json
  packs/classfeatures/bloodline-elemental.json
  packs/classfeatures/bloodline-fey.json
  packs/classfeatures/bloodline-genie.json
  packs/classfeatures/bloodline-hag.json
  packs/classfeatures/bloodline-harrow.json
  packs/classfeatures/bloodline-imperial.json
  packs/classfeatures/bloodline-nymph.json
  packs/classfeatures/bloodline-phoenix.json
  packs/classfeatures/bloodline-psychopomp.json
  packs/classfeatures/bloodline-shadow.json
  packs/classfeatures/bloodline-undead.json
  packs/classfeatures/bloodline-wyrmblessed.json
  packs/classfeatures/strategic-strike.json
  packs/feat-effects/effect-blood-sovereignty.json
  packs/feats/blood-rising.json
  packs/feats/blood-sovereignty.json
  packs/feats/crossblooded-evolution.json
  packs/feats/explosion-of-power.json
  packs/feats/propelling-sorcery.json
  packs/feats/reflect-harm.json
  packs/feats/terraforming-trickery.json
  static/lang/re-en.json
Labels: pr: data update

#15872 Add Barbarian Ligneous Instinct's speed decrease
  packs/classfeatures/bloodline-shadow.json
  packs/classfeatures/ligneous-instinct.json
Labels: pr: data update

#15876 add effect to track Unstable check failure.
  packs/feat-effects/effect-unstable-check-failure.json
  static/lang/re-en.json
Labels: pr: data update

#15879 Update Roll Twice rule elements to make use of multiple selectors
  packs/bestiary-effects/effect-black-cat-curse.json
  packs/bestiary-effects/effect-wrath-of-fate.json
  packs/feat-effects/effect-expel-maelstrom-misfortune.json
  packs/feat-effects/effect-guide-the-timeline.json
  packs/feat-effects/effect-inspired-stratagem.json
  packs/feat-effects/effect-roll-the-bones-of-fate-good.json
  packs/feat-effects/effect-wish-for-luck.json
  packs/spell-effects/spell-effect-ill-omen.json
  packs/spell-effects/spell-effect-sages-curse-failure.json
  packs/spell-effects/spell-effect-sages-curse-success.json
Labels: pr: data update

#15880 Update Weapon Storm's description to include area
  packs/pathfinder-monster-core/aeolaeka.json
  packs/prey-for-death-bestiary/the-first-blade.json
  packs/prey-for-death-bestiary/valkyrie-of-gorum.json
  packs/prey-for-death-bestiary/valkyrie-tempest.json
  packs/spells/weapon-storm.json
Labels: pr: data update

#15877 Remove Invulnerable Juggernaut feat
  packs/feats/invulnerable-juggernaut.json
Labels: pr: data update

#15874 Remove AC penalty and add Temporary Hit Points to Share Rage
  packs/feat-effects/effect-share-rage.json
Labels: pr: data update

#15891 update healing dice roll for Rejuvenating Flames spell
  packs/spells/rejuvenating-flames.json
Labels: pr: data update

#15892 Add description alterations for Tap Into Blood
  packs/classfeatures/bloodline-shadow.json
  packs/feats/tap-into-blood.json
  static/lang/re-en.json
Labels: pr: data update

#15890 localize Dark Archive spellshape feats
  packs/feats/bizarre-transformation.json
  packs/feats/cryptic-spell.json
  packs/feats/into-the-future.json
  packs/feats/ley-line-conduit.json
  packs/feats/timeline-splitting-spell.json
  packs/feats/unlimited-potential.json
  packs/feats/what-could-have-been.json
  static/lang/re-en.json
Labels: pr: data update

#15889 Trim down Weight of Experience Choice Set
  packs/feats/weight-of-experience.json
Labels: pr: data update

#15888 brush up text on Inventor feats.
  packs/feats/haphazard-repair.json
  packs/feats/searing-restoration.json
Labels: pr: data update

#15884 Allow Dirty Trick to be taken beyond level 1
  packs/feats/dirty-trick.json
Labels: pr: data update

#15883 Add missing item sources
  packs/classfeatures/alchemical-expertise.json
  packs/classfeatures/double-brew.json
  packs/feat-effects/effect-aura-of-determination.json
  packs/feat-effects/effect-aura-of-faith-unholy.json
  packs/feat-effects/effect-demonic-blood-magic.json
  packs/feat-effects/effect-exalted-reaction-desecrator.json
  packs/feat-effects/effect-exalted-reaction-redemption.json
  packs/feat-effects/effect-vivacious-bravado.json
  packs/spell-effects/spell-effect-rejuvenating-touch.json
Labels: pr: data update

#15881 Add automation for Troop Spellcasting
  packs/blood-lords-bestiary/necromancer-troop.json
  packs/pathfinder-bestiary-3/rancorous-priesthood.json
  packs/prey-for-death-bestiary/valkyrie-tempest.json
  packs/strength-of-thousands-bestiary/sun-warrior-brigade.json
  packs/wardens-of-wildwood-bestiary/rancorous-druids.json
Labels: pr: data update

#15875 Add Note on Initiative to Quick Tempered
  packs/actions/quick-tempered.json
Labels: pr: data update

#15897 Update flourish trait description
  static/lang/en.json
Labels: pr: data update

#15907 Correct Hammer Gun ranged usage damage type
  packs/equipment/hammer-gun.json
Labels: pr: data update

#15905 Add EphemeralEffect to Grandmother Spider - Major Curse
  packs/boons-and-curses/effect-grandmother-spiders-underdog.json
  packs/boons-and-curses/grandmother-spider-major-curse.json
Labels: pr: data update

#15902 Update Magical Scrounger feat
  packs/feats/magical-scrounger.json
  packs/journals/archetypes.json
Labels: pr: data update

#15901 Add effects for Revel in Retribution
  packs/spell-effects/effect-revel-in-retribution-temp-hp.json
  packs/spell-effects/effect-revel-in-retribution.json
  packs/spells/revel-in-retribution.json
  static/lang/re-en.json
Labels: pr: data update

#15899 Add DC to Oracle feats according to PFS clarification
  packs/feats/debilitating-dichotomy.json
  packs/feats/trial-by-skyfire.json
Labels: pr: data update

#15898 Use tag-based Choice Set for Blessing of the Devoted
  packs/classfeatures/blessed-armament.json
  packs/classfeatures/blessed-shield.json
  packs/classfeatures/blessed-swiftness.json
  packs/classfeatures/blessing-of-the-devoted.json
  packs/feats/expand-aura.json
Labels: pr: data update

#15895 add sorcerer to sorcerous potency class feature
  packs/classfeatures/sorcerous-potency.json
Labels: pr: data update

#15857 Lower the color intensity of the Light spell effect
  packs/spell-effects/spell-effect-light.json
Labels: pr: data update

#15860 Set several class feats to use the proper class DC
  packs/actions/spinning-crush.json
  packs/feat-effects/stance-steam-knight.json
  packs/feats/collateral-thrash.json
  packs/feats/dazing-blow.json
  packs/feats/dragons-rage-breath.json
  packs/feats/hell-of-1-000-000-needles.json
  packs/feats/one-millimeter-punch.json
  packs/feats/regurgitate-mutagen.json
  packs/feats/roiling-mudslide.json
  packs/feats/scouring-rage.json
  packs/feats/silencing-strike.json
  packs/feats/steam-knight.json
  packs/feats/thrash.json
  packs/feats/turn-the-wheel-of-seasons.json
  packs/feats/wild-witchs-armaments.json
  static/lang/re-en.json
Labels: pr: data update

#15908 Brush up Spell Effect: Qi Form
  packs/spell-effects/spell-effect-qi-form.json
Labels: pr: data update

#15916 Choker-Arm Mutagen fix to account for size changes
  packs/equipment-effects/effect-choker-arm-mutagen-greater.json
  packs/equipment-effects/effect-choker-arm-mutagen-lesser.json
  packs/equipment-effects/effect-choker-arm-mutagen-major.json
  packs/equipment-effects/effect-choker-arm-mutagen-moderate.json
Labels: pr: data update

#15929 Prevent healing from becoming damage via modifiers
  src/module/actor/base.ts
Labels: pr: bugfix

#15919 correct text for Elbow Breaker feat to PC2
  packs/feats/elbow-breaker.json
Labels: pr: data update
