Repository foundryvtt/pf2e, pull requests merged in 2024-09, with the labels that each got.

#16357 Correct typo in Remaster Journal
  packs/journals/remaster-changes.json
Labels: pr: data update

#16354 Update Sentinel and Champion Dedication armor proficiency Rule Elements
  packs/feats/champion-dedication.json
  packs/feats/sentinel-dedication.json
Labels: pr: data update

#16353 Brush up Dash of Herbs Kineticist feat
  packs/feats/dash-of-herbs.json
Labels: pr: data update

#16350 Use `rollerRole` on remaining `resolve()` inline checks
  packs/feat-effects/effect-fey-blood-magic.json
  packs/feats/winter-sleet.json
  packs/rage-of-elements-bestiary/living-magma.json
  packs/sky-kings-tomb-bestiary/giant-leech.json
Labels: pr: data update

#16349 fix typo in effect envenom fangs
  packs/feat-effects/effect-envenom-fangs.json
Labels: pr: data update

#16347 Tag feats granting ancestral spells for select feats and heritages
  packs/feats/bark-and-tendril.json
  packs/feats/call-of-the-green-man.json
  packs/feats/extraplanar-supplication.json
  packs/feats/flourish-and-ruin.json
  packs/feats/regrowth.json
  packs/feats/stonewalker.json
  packs/feats/unhampered-passage.json
  packs/heritages/elf/seer-elf.json
Labels: pr: data update

#16344 Replace Granted spells by Sorcerous Gifts in desc of diabolic bloodline
  packs/classfeatures/bloodline-diabolic.json
Labels: pr: data update

#16343 fix typo in feat-effect great tengu form
  packs/feat-effects/effect-great-tengu-form.json
Labels: pr: data update

#16341 Fix typo in Stance: Twisting Petal Stance description
  packs/feat-effects/stance-twisting-petal-stance.json
Labels: pr: data update

#16340 Fix typo in Align Qi description
  packs/feats/align-qi.json
Labels: pr: data update

#16338 brush up Pathfinder Society Boons
  packs/pathfinder-society-boons/adversary-lore.json
  packs/pathfinder-society-boons/bequeathal-rare.json
  packs/pathfinder-society-boons/bequeathal-uncommon.json
  packs/pathfinder-society-boons/bequeathal-unique.json
  packs/pathfinder-society-boons/bring-them-back-alive.json
  packs/pathfinder-society-boons/career-change.json
  packs/pathfinder-society-boons/crafters-workshop.json
  packs/pathfinder-society-boons/curse-breaker.json
  packs/pathfinder-society-boons/evolving-destiny.json
Labels: pr: data update

#16336 Add unique icons to equipment items
  packs/equipment/bagpipes-of-turmoil-greater.json
  packs/equipment/bagpipes-of-turmoil-major.json
  packs/equipment/bagpipes-of-turmoil.json
  packs/equipment/bloodline-robe.json
  packs/equipment/brazier-of-harmony.json
  packs/equipment/gamtu-hat.json
  packs/equipment/hallajin-key.json
  packs/equipment/heckling-tools.json
  packs/equipment/instinct-crown-fury.json
  packs/equipment/liars-board.json
  packs/equipment/mask-of-the-cursed-eye.json
  packs/equipment/nightbreeze-machine.json
  packs/equipment/plated-duster.json
  packs/equipment/spiral-chimes.json
  packs/equipment/starless-scope.json
  packs/equipment/tanglefoot-extruder.json
  packs/equipment/toshigami-blossom.json
  packs/equipment/trackless-greater.json
  packs/equipment/trackless.json
  packs/equipment/voice-from-the-grave.json
  packs/kingmaker-bestiary/castruccio-irovetti.json
  packs/kingmaker-bestiary/darivan.json
  packs/pfs-season-1-bestiary/meleeka-sanvara-3-4.json
  packs/pfs-season-4-bestiary/pups.json
Labels: pr: data update

#16335 Convert additional instances of inline damage to the new format
  packs/blog-bestiary/ailuran.json
  packs/blog-bestiary/duhgik.json
  packs/blog-bestiary/lisavet.json
  packs/blood-lords-bestiary/ostovite-nest.json
  packs/crown-of-the-kobold-king-bestiary/pendulum-blades.json
  packs/journals/hero-point-deck.json
  packs/npc-gallery/cult-leader.json
  packs/npc-gallery/physician.json
  packs/paizo-pregens/ekene.json
  packs/paizo-pregens/grimmnir.json
  packs/paizo-pregens/jaithe.json
  packs/paizo-pregens/melvok.json
  packs/paizo-pregens/muruwa.json
  packs/paizo-pregens/simeek.json
  packs/paizo-pregens/yacob.json
  packs/paizo-pregens/zakzak.json
  packs/paizo-pregens/zathri.json
  packs/paizo-pregens/zindarel.json
  packs/pathfinder-bestiary/ghoul.json
  packs/pathfinder-dark-archive/distortion-mirror.json
  packs/pathfinder-dark-archive/exhaling-portal.json
  packs/pfs-season-1-bestiary/deeply-flawed-ritual.json
  packs/pfs-season-1-bestiary/flawed-ritual.json
  packs/rage-of-elements-bestiary/olobigonde.json
  packs/rusthenge-bestiary/vloriak.json
Labels: pr: data update

#16334 Add Nagaji language to Yaoguai
  packs/ancestries/yaoguai.json
Labels: pr: data update

#16367 Fix typo in prereq for brilliant flash
  packs/feats/brilliant-flash.json
Labels: pr: data update

#16370 Update Action Cost for Majestic Presence
  packs/feats/majestic-presence.json
Labels: pr: data update

#16366 Update and correct several Archetype Journal entries
  packs/journals/archetypes.json
Labels: pr: data update

#16377 Fix Ainamuuren's Horns cold damage partial
  packs/gatewalkers-bestiary/ainamuuren.json
Labels: pr: data update

#15818 Allow `@Embed` of Items
  src/module/item/base/document.ts
  src/module/item/campaign-feature/document.ts
  src/module/item/feat/document.ts
Labels: pr: enhancement

#16391 Show active token image rather than the prototype token
  src/module/chat-message/document.ts
Labels: pr: bugfix

#16394 Audit Captivator and Familiar Sage archetypes
  packs/actions/blazing-conflagration.json
  packs/familiar-abilities/lightning-armillary.json
  packs/familiar-abilities/lightning-needles.json
  packs/feat-effects/effect-familiars-resolve.json
  packs/feat-effects/effect-lightning-armillary.json
  packs/feats/bark-and-tendril.json
  packs/feats/cultivator-dedication.json
  packs/feats/cultivators-keen-eye.json
  packs/feats/extraplanar-supplication.json
  packs/feats/flourish-and-ruin.json
  packs/feats/golden-dragons-bounty.json
  packs/feats/lotus-above-the-wind.json
  packs/feats/phoenixs-flight.json
  packs/feats/the-bitter-scholars-promotion.json
  packs/feats/three-pecks-of-dew.json
  packs/feats/tricksterbane-oath.json
  packs/feats/vexing-tempest.json
  packs/feats/wisteria-and-peony-reunion.json
  static/lang/re-en.json
Labels: pr: data update

#16389 Brush up Fortuitous Shift
  packs/feats/fortuitous-shift.json
Labels: pr: data update

#16388 Update Trigger requirements for Liberating Steps to match PC2
  packs/actions/liberating-step.json
Labels: pr: data update

#16387 Add `Evolution` trait to the Airborne Form feat
  packs/feats/airborne-form.json
Labels: pr: data update

#16386 Add `injury` trait and unique icon to Choleric Contagion
  packs/equipment/choleric-contagion.json
Labels: pr: data update

#16381 Add automation for NPC Ambush
  packs/pathfinder-bestiary/giant-moray-eel.json
  packs/pathfinder-monster-core/giant-moray-eel.json
  packs/pfs-season-6-bestiary/whippoorwill-giant-moray-eel.json
  packs/rage-of-elements-bestiary/olobigonde.json
  packs/tian-xia-world-guide-bestiary/gau-cho-rong.json
Labels: pr: data update

#16380 add entries for Clawdancer and Shieldmarshal dedications to the Archetypes journal
  packs/feats/clawdancer-dedication.json
  packs/feats/shieldmarshal-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#16378 Update slugs for Animal Skin and Scaly Hide feats to work correctly with Mystic Armor
  packs/feats/animal-skin.json
  packs/feats/scaly-hide.json
Labels: pr: data update

#16375 Add Note reminder to Uncanny Pounce
  packs/curtain-call-bestiary/anguish-siktempora.json
  packs/pathfinder-bestiary-3/hatred-siktempora.json
  packs/pathfinder-bestiary-3/love-siktempora.json
  packs/pathfinder-bestiary-3/misery-siktempora.json
  packs/pathfinder-bestiary-3/triumph-siktempora.json
  packs/strength-of-thousands-bestiary/contemplative-meditant.json
  packs/strength-of-thousands-bestiary/contemplative-mentor.json
Labels: pr: data update

#16374 Add automation for NPC ability Terrain Advantage
  packs/agents-of-edgewatch-bestiary/shikwashim-mercenary.json
  packs/book-of-the-dead-bestiary/iruxi-ossature.json
  packs/kingmaker-bestiary/lizardfolk-warrior.json
  packs/pathfinder-bestiary/lizardfolk-defender.json
  packs/pathfinder-bestiary/lizardfolk-scout.json
  packs/pathfinder-monster-core/lizardfolk-defender.json
  packs/pathfinder-monster-core/lizardfolk-scout.json
Labels: pr: data update

#16371 Update Speed rune localization to Quickstrike
  static/lang/en.json
Labels: pr: data update

#16361 Update icon for Zoophonia class feature
  packs/classfeatures/zoophonia.json
Labels: pr: data update

#16359 Condense Spell Repertoire Class Feature
  build/uuid-redirects.json
  packs/classes/bard.json
  packs/classes/oracle.json
  packs/classes/psychic.json
  packs/classes/sorcerer.json
  packs/classes/summoner.json
  packs/classfeatures/bloodline-spells.json
  packs/classfeatures/spell-repertoire.json
  static/lang/re-en.json
Labels: pr: data update

#16328 Automate Starlit Sentinel archetype
  packs/actions/starlit-transformation.json
  packs/feat-effects/effect-blade-of-the-heart.json
  packs/feat-effects/effect-starlit-transformation.json
  packs/feats/majestic-proclamation.json
  packs/feats/sentinels-orbit.json
  packs/feats/special-sentinel-technique.json
  packs/feats/starlit-sentinel-dedication.json
  packs/journals/archetypes.json
  packs/spells/luminous-stardust-healing.json
  packs/spells/shining-starlight-attack.json
  static/lang/re-en.json
Labels: pr: data update

#16390 Fix choice set homebrew item dropzone for button lists
  packs/feats/pitborn.json
  src/module/rules/rule-element/choice-set/prompt.ts
Labels: pr: bugfix, pr: data update

#16379 Update Catharsis Emotion class feature RE to account for case sensitive localization
  packs/classfeatures/catharsis-emotion.json
Labels: pr: data update

#16398 Fix types of token image path fields
  src/module/chat-message/document.ts
  src/module/scene/token-document/document.ts
  types/foundry/common/data/data.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: bugfix, pr: types update

#16393 Scale up dynamic tokens in chat messages
  src/module/chat-message/document.ts
  types/foundry/client-esm/canvas/module.d.ts
  types/foundry/client-esm/canvas/tokens/module.ts
  types/foundry/client-esm/canvas/tokens/ring-config.d.ts
  types/foundry/client/config.d.ts
Labels: ui/ux

#16396 Add missing entries to the Archetype journal and add links to feats
  packs/feats/ostilli-host-dedication.json
  packs/feats/petrifying-gaze-mimicry.json
  packs/feats/swarmkeeper-dedication.json
  packs/feats/thlipit-contestant-dedication.json
  packs/feats/werecreature-dedication.json
  packs/feats/wild-mimic-dedication.json
  packs/feats/winged-warrior-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#16400 Remove duplicate Adventure-specific Actions from General Actions
  build/uuid-redirects.json
  packs/actions/de-animating-gestures-false.json
  packs/actions/de-animating-gestures-true.json
  packs/actions/dream-research.json
  packs/actions/mesmerizing-performance.json
Labels: pr: data update

#16360 Automate Qi-Infused Fabric and Unsheathing the Sword Light
  packs/classfeatures/aloof-firmament.json
  packs/classfeatures/studious-spells.json
  packs/classfeatures/unfurling-brocade.json
  packs/feats/distant-waterbirds-poise.json
  packs/feats/unsheathing-the-sword-light.json
  packs/feats/vermillion-threads.json
  static/lang/re-en.json
Labels: pr: data update

#16372 Update additional instances of inline damage to new format
  packs/extinction-curse-bestiary/flea-swarm.json
  packs/gatewalkers-bestiary/myroga.json
  packs/gatewalkers-bestiary/protosoul.json
  packs/iconics/jirelle-level-1.json
  packs/iconics/jirelle-level-3.json
  packs/iconics/jirelle-level-5.json
  packs/iconics/lem-level-3.json
  packs/iconics/lem-level-5.json
  packs/iconics/seoni-level-1.json
  packs/iconics/seoni-level-3.json
  packs/iconics/seoni-level-5.json
  packs/iconics/yoon-level-3.json
  packs/iconics/yoon-level-5.json
  packs/kingmaker-bestiary/kressle.json
  packs/npc-gallery/apothecary.json
  packs/npc-gallery/nyctessa.json
  packs/paizo-pregens/kangir.json
  packs/pathfinder-bestiary-2/peryton.json
  packs/pathfinder-bestiary-2/ravener.json
  packs/pathfinder-bestiary/ghast.json
  packs/pathfinder-bestiary/imp.json
  packs/pathfinder-bestiary/leaf-leshy.json
  packs/rusthenge-bestiary/vloriak.json
Labels: pr: data update

#16399 Automate TXCG Inventor Feats
  packs/feat-effects/effect-geobukseon-retaliation.json
  packs/feat-effects/effect-protective-pose.json
  packs/feats/celestial-cacophony.json
  packs/feats/duo-dragon-kick.json
  packs/feats/geobukseon-retaliation.json
  packs/feats/guardian-lion-roar.json
  packs/feats/meditate-on-this.json
  packs/feats/oil-fire.json
  packs/feats/protective-pose.json
  packs/feats/silk-bracelet.json
  packs/feats/xidao-sea-mine-drop.json
Labels: pr: data update

#16401 Update source for Infiltration Downtime activities to Pathfinder GM Core
  packs/actions/bribe-contact.json
  packs/actions/forge-documents.json
  packs/actions/gain-contact.json
  packs/actions/gossip.json
  packs/actions/scout-location.json
  packs/actions/secure-disguises.json
Labels: pr: data update

#16407 Fix some token names
  packs/bestiary-effects/effect-surge-forward.json
  packs/curtain-call-bestiary/father-skinsaw.json
  packs/equipment/potion-of-disguise-moderate.json
  packs/feats/celestial-magic.json
  packs/feats/fiendish-magic.json
  packs/feats/solidarity.json
  packs/journals/archetypes.json
  packs/pfs-season-6-bestiary/bloodthirsty-apparitions-5-6.json
  packs/pfs-season-6-bestiary/puddles-phantom-5-6.json
  packs/pfs-season-6-bestiary/rain-soaked-crowd-5-6.json
  static/lang/re-en.json
Labels: pr: data update

#16402 Fix typo in Tengu Feather Fan description
  packs/equipment/tengu-feather-fan.json
  packs/pathfinder-monster-core/tengu-sneak.json
Labels: pr: data update

#16411 Update Dueling actions source to Pathfinder GM Core
  packs/actions/bullying-press.json
  packs/actions/change-tradition-focus.json
  packs/actions/deceptive-sidestep.json
  packs/actions/dueling-counter.json
  packs/actions/sense-weakness.json
Labels: pr: data update

#16412 Audit TXCG equipment and add effect for Eternal Torch
  packs/equipment-effects/effect-rolling-flight.json
  packs/equipment/caress-of-the-great-serpent.json
  packs/equipment/cloak-of-waves-clouds.json
  packs/equipment/gakgung.json
  packs/equipment/heavenly-rolling-flames.json
  packs/equipment/staff-of-sun-wukong.json
  packs/equipment/tri-bladed-katar.json
  packs/equipment/twisting-gale.json
  packs/feat-effects/effect-eternal-torch.json
  packs/feats/eternal-torch.json
  static/lang/re-en.json
Labels: pr: data update

#16413 Add effect for Elemental Bulwark
  packs/feat-effects/effect-elemental-bulwark.json
  packs/feats/elemental-bulwark.json
Labels: pr: data update

#16414 Tag several ancestry feats as granting ancestral spells
  packs/feats/ancestors-rage.json
  packs/feats/animal-summoner.json
  packs/feats/bone-caller.json
  packs/feats/bone-investiture.json
  packs/feats/boneyards-call.json
  packs/feats/breath-like-honey.json
  packs/feats/catrinas-presence.json
  packs/feats/cautious-curiosity.json
  packs/feats/distant-cackle.json
  packs/feats/draconic-veil.json
  packs/feats/duskwalker-magic.json
  packs/feats/elemental-wrath.json
  packs/feats/enthralling-allure.json
  packs/feats/fade-away.json
  packs/feats/favor-of-heaven.json
  packs/feats/fearsome-form.json
  packs/feats/first-world-adept.json
  packs/feats/form-of-the-dragon.json
  packs/feats/fossil-rider.json
  packs/feats/grandmothers-wisdom.json
  packs/feats/greater-than-the-sum.json
  packs/feats/heroes-call.json
  packs/feats/homeward-bound.json
  packs/feats/mariners-fire.json
  packs/feats/morrignas-spider-affinity.json
  packs/feats/natural-illusionist.json
  packs/feats/night-magic.json
  packs/feats/primal-rampage.json
  packs/feats/rat-magic.json
  packs/feats/resist-ruin.json
  packs/feats/sense-thoughts.json
  packs/feats/shokis-argument.json
  packs/feats/stonegate.json
  packs/feats/storms-lash.json
  packs/feats/symphony-of-blood.json
  packs/feats/trickster-tengu.json
  packs/feats/wildborn-adept.json
  packs/heritages/kholo/sweetbreath-kholo.json
  packs/heritages/kholo/witch-kholo.json
  packs/heritages/tengu/mountainkeeper-tengu.json
Labels: pr: data update

#16395 Automate Elemental Medicine feats
  packs/feat-effects/effect-prepare-elemental-medicine.json
  packs/feat-effects/stance-intensified-element-stance.json
  packs/feats/acupuncturist.json
  packs/feats/energy-fortification.json
  packs/feats/intensified-element-stance.json
  packs/feats/prepare-elemental-medicine.json
  packs/feats/temperature-adjustment.json
  static/lang/re-en.json
Labels: pr: data update

#16409 Clean up formatting and links on TXCG Monk feats
  packs/feat-effects/effect-adamantine-body.json
  packs/feat-effects/stance-kaiju-stance.json
  packs/feats/adamantine-body.json
  packs/feats/five-gods-ram.json
  packs/feats/momentous-charge.json
  packs/feats/scattering-in-spring.json
  packs/feats/wake-of-devastation.json
  packs/feats/whirling-in-the-summer-storm.json
  packs/feats/world-breaking-footfall.json
Labels: pr: data update

#16419 Add area information to Punishing Winds
  packs/spells/punishing-winds.json
Labels: pr: data update

#16417 Include advanced weapons in Mauler Dedication's critical specialization
  packs/feats/mauler-dedication.json
Labels: pr: data update

#16424 Unify effect for Bon Mot
  build/uuid-redirects.json
  packs/feat-effects/effect-bon-mot-critical-success.json
  packs/feat-effects/effect-bon-mot.json
  packs/feats/bon-mot.json
  packs/iconics/jirelle-level-3.json
  packs/iconics/jirelle-level-5.json
  static/lang/action-en.json
Labels: pr: data update

#16422 Fix Flamboyant Leap requirements formatting
  packs/feats/flamboyant-leap.json
Labels: pr: data update

#16432 Erase pre-remaster sentence in tempest form
  packs/spells/tempest-form.json
Labels: pr: data update

#16431 Update Champion and Sentinel dedication to account for armor expertise class feature
  packs/feats/champion-dedication.json
  packs/feats/sentinel-dedication.json
Labels: pr: data update

#16427 Update Seraptis Actor proficiencies
  packs/pathfinder-monster-core/seraptis.json
Labels: pr: data update

#16420 Add effects for Mentor of Legends and Siphon Torment, and tag several ancestral spell feats
  packs/feat-effects/effect-azarketi-purification.json
  packs/feat-effects/effect-mentor-of-legends.json
  packs/feat-effects/effect-siphon-torment.json
  packs/feats/aberration-kinship.json
  packs/feats/aboleth-transmutation.json
  packs/feats/agathion-magic.json
  packs/feats/ancestors-transformation.json
  packs/feats/apprentice-sea-witch.json
  packs/feats/arise-ye-worthy.json
  packs/feats/asura-magic.json
  packs/feats/azarketi-purification.json
  packs/feats/captivating-curiosity.json
  packs/feats/devilish-wiles.json
  packs/feats/emissary-assistance.json
  packs/feats/emotionless.json
  packs/feats/fey-cantrips.json
  packs/feats/fey-disguise.json
  packs/feats/fey-magic.json
  packs/feats/garuda-magic.json
  packs/feats/into-the-labyrinth.json
  packs/feats/invisible-trickster.json
  packs/feats/jalmeri-rakshasa-magic.json
  packs/feats/labyrinthine-echoes.json
  packs/feats/mentor-of-legends.json
  packs/feats/merge-with-the-source.json
  packs/feats/miraculous-medic.json
  packs/feats/nodal-regeneration.json
  packs/feats/pierce-the-light.json
  packs/feats/qlippoth-magic.json
  packs/feats/rakshasa-magic.json
  packs/feats/rokoan-arts.json
  packs/feats/sea-witch.json
  packs/feats/shadows-assault.json
  packs/feats/shadowy-disguise.json
  packs/feats/siphon-torment.json
  packs/feats/skirt-the-light.json
  packs/feats/speaker-in-training.json
  packs/feats/speakers-defense.json
  packs/feats/thrown-voice.json
  packs/feats/towering-growth.json
  packs/feats/tranquil-sanctuary.json
  packs/feats/underwater-volcano.json
  packs/feats/velstrac-magic.json
  packs/heritages/centaur/budding-speaker-centaur.json
  packs/heritages/fetchling/bright-fetchling.json
  packs/heritages/minotaur/ghost-bull-minotaur.json
  packs/heritages/sprite/grig.json
  packs/heritages/surki/elytron-surki.json
  static/lang/re-en.json
Labels: pr: data update

#16448 Correct Action Cost for Work Yourself Up feat
  packs/feats/work-yourself-up.json
Labels: pr: data update

#16446 Correct labels in Improved Invigorating Elixir localization
  static/lang/re-en.json
Labels: pr: data update

#16444 Update Black Tear Cutthroat actor Dagger strikes
  packs/kingmaker-bestiary/black-tear-cutthroat.json
Labels: pr: data update

#16443 Add Lost Omens Firebrand dedication feats to archetype journal
  packs/feats/acknowledge-fan.json
  packs/feats/cutting-flattery.json
  packs/feats/feeling-your-oats.json
  packs/feats/youre-an-embarrassment.json
  packs/journals/archetypes.json
Labels: pr: data update

#16440 Remove vestigial horn statistics from Dragon Form spell effect
  packs/spell-effects/spell-effect-dragon-form-adamantine.json
  packs/spell-effects/spell-effect-dragon-form-conspirator.json
  packs/spell-effects/spell-effect-dragon-form-diabolic.json
  packs/spell-effects/spell-effect-dragon-form-empyreal.json
  packs/spell-effects/spell-effect-dragon-form-fortune.json
  packs/spell-effects/spell-effect-dragon-form-horned.json
  packs/spell-effects/spell-effect-dragon-form-mirage.json
  packs/spell-effects/spell-effect-dragon-form-omen.json
Labels: pr: data update

#16436 Move unleash psyche's toggle to spellcasting tab
  packs/feat-effects/effect-unleash-psyche.json
Labels: pr: data update

#16435 Add Note automation to Devrin's Dazzling Diversion
  packs/feats/devrins-dazzling-diversion.json
Labels: pr: data update

#16434 Prevent Awakened Animal's fist Strike from overriding other Strikes
  packs/ancestryfeatures/animal-attack.json
  packs/feats/tooth-and-claw.json
Labels: pr: data update

#16433 Remove link to SF2e Suppressed condition from Talisman Dabbler journal page
  packs/journals/archetypes.json
Labels: pr: data update

#16428 Brush up automation for Assisting Shot
  build/uuid-redirects.json
  packs/feat-effects/effect-assisting-shot-critical-hit.json
  packs/feat-effects/effect-assisting-shot.json
  packs/feats/assisting-shot.json
  static/lang/re-en.json
Labels: pr: data update

#16410 Update additional instances of inline damage to new format
  packs/abomination-vaults-bestiary/aller-rosk.json
  packs/blood-lords-bestiary/ghoul-crocodile.json
  packs/extinction-curse-bestiary/xilvirek.json
  packs/monsters-of-myth-bestiary/somnalu.json
  packs/monsters-of-myth-bestiary/temteki.json
  packs/paizo-pregens/lavanna-saltspray.json
  packs/pathfinder-bestiary-3/squirming-swill.json
  packs/pathfinder-dark-archive/k-h-w-s-echo.json
  packs/pathfinder-monster-core/dero-magister.json
  packs/pathfinder-monster-core/fungus-leshy.json
  packs/pathfinder-monster-core/thulgant.json
  packs/pfs-season-1-bestiary/webhekiz-3-4.json
  packs/pfs-season-1-bestiary/webhekiz-5-6.json
  packs/pfs-season-1-bestiary/zombie-warhorse.json
  packs/stolen-fate-bestiary/xiuli-cachu.json
  packs/the-slithering-bestiary/cursebreaker.json
Labels: pr: data update

#16449 Add unique icons to equipment items and NPC items
  packs/crown-of-the-kobold-king-bestiary/edgrin-galesong.json
  packs/equipment-effects/effect-catch-pole.json
  packs/equipment/armory-bracelet-greater.json
  packs/equipment/armory-bracelet-lesser.json
  packs/equipment/armory-bracelet-major.json
  packs/equipment/armory-bracelet-minor.json
  packs/equipment/armory-bracelet-moderate.json
  packs/equipment/cassisian-helmet.json
  packs/equipment/catch-pole.json
  packs/equipment/curious-teardrop.json
  packs/equipment/extra-lung.json
  packs/equipment/galvanic-mortal-coil.json
  packs/equipment/grub-gloves-greater.json
  packs/equipment/grub-gloves-lesser.json
  packs/equipment/grub-gloves-moderate.json
  packs/equipment/instinct-crown-animal.json
  packs/equipment/instinct-crown-dragon.json
  packs/equipment/instinct-crown-giant.json
  packs/equipment/instinct-crown-spirit.json
  packs/equipment/instinct-crown-superstition.json
  packs/equipment/jahan-waystone.json
  packs/equipment/raven-band.json
  packs/equipment/smoke-veil.json
  packs/equipment/superior-catch-pole.json
  packs/equipment/ursine-avenger-hood.json
  packs/equipment/versatile-tinderbox.json
  packs/equipment/wand-of-purification-2nd-rank-spell.json
  packs/equipment/wand-of-purification-3rd-rank-spell.json
  packs/equipment/wand-of-purification-4th-rank-spell.json
  packs/equipment/wand-of-purification-5th-rank-spell.json
  packs/equipment/wand-of-purification-6th-rank-spell.json
  packs/equipment/wand-of-purification-7th-rank-spell.json
  packs/equipment/wand-of-purification-8th-rank-spell.json
  packs/equipment/wand-of-purification-9th-rank-spell.json
  packs/strength-of-thousands-bestiary/takulu-ot.json
Labels: pr: data update, pr: static assets

#16430 Fix incorrect link in Wild Winds Stance
  packs/spells/wild-winds-stance.json
Labels: pr: data update

#16450 Correct spelling of Concealment
  packs/blood-lords-bestiary/button-mash.json
  packs/classfeatures/bloodline-harrow.json
  packs/feats/obscured-emergence.json
  packs/spells/wild-winds-stance.json
  packs/stolen-fate-bestiary/raven-nicoletta.json
  packs/wardens-of-wildwood-bestiary/the-bee-man-of-bellis.json
  static/lang/re-en.json
Labels: pr: data update

#16415 Avoid disabled modifiers suppressing enabled ones
  src/module/actor/modifiers.ts
  src/module/system/statistic/base.ts
Labels: pr: bugfix

#16453 Use core helpers in `isImageFilePath` and `isVideoFilePath`
  src/util/misc.ts
  types/foundry/client/core/image.d.ts
Labels: pr: refactor

#16454 Generalize some localization entries from Aura RE form
  src/module/item/base/sheet/rule-element-form/aura.ts
  src/module/rules/rule-element/aura.ts
  static/lang/re-en.json
  static/templates/items/rules/aura.hbs
Labels: pr: refactor

#16337 Redirect select actors to their Monster Core/Bestiary equivalent
  build/uuid-redirects.json
  packs/menace-under-otari-bestiary/animated-armor-bb.json
  packs/menace-under-otari-bestiary/boar-bb.json
  packs/npc-gallery/azarketi-crab-catcher.json
  packs/npc-gallery/azarketi-tide-tamer.json
  packs/pathfinder-bestiary-2/army-ant-swarm.json
  packs/pathfinder-bestiary-2/wereboar.json
  packs/pathfinder-bestiary/awakened-tree.json
  packs/pathfinder-bestiary/axiomite.json
  packs/pathfinder-bestiary/boar.json
  packs/quest-for-the-frozen-flame-bestiary/corrupted-elder-tree.json
  packs/the-slithering-bestiary/alchemical-golem-slithering.json
Labels: pr: data update

#16408 Remove weapon predicates from Athletic Strategist
  packs/feats/athletic-strategist.json
Labels: pr: data update

#16467 Internally rename CraftingEntry to CraftingAbility
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/crafting/index.ts
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/migration/migrations/774-unpersist-crafting-entries.ts
Labels: pr: refactor

#16465 Fix description and add effect for Prognostic Veil's Twist the Skeins of Fate
  packs/equipment-effects/effect-twist-the-skeins-of-fate.json
  packs/equipment/prognostic-veil-greater.json
  packs/equipment/prognostic-veil.json
Labels: pr: data update

#16475 Remove fire trait from Icy Deflection and brush up automation
  packs/pathfinder-bestiary-2/ice-yai.json
  packs/pathfinder-monster-core/snow-oni.json
Labels: pr: data update

#16457 Add support for changing token ring subject via TokenImage RE
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/item/base/sheet/rule-element-form/token-image.ts
  src/module/rules/rule-element/token-image.ts
  src/module/rules/synthetics.ts
  src/module/scene/token-document/document.ts
  static/lang/re-en.json
  static/templates/items/rules/token-image.hbs
Labels: pr: enhancement

#16472 Update Alchemist Goggles and automate Berserker's Cloak
  packs/classfeatures/animal-instinct.json
  packs/equipment-effects/effect-alchemist-goggles.json
  packs/equipment/alchemist-goggles-greater.json
  packs/equipment/alchemist-goggles-major.json
  packs/equipment/alchemist-goggles.json
  packs/equipment/berserkers-cloak-greater.json
  packs/equipment/berserkers-cloak.json
  packs/equipment/cloth-of-nullification.json
  packs/equipment/urn-of-ashes.json
  static/lang/re-en.json
Labels: pr: data update

#16478 Add injury and mental traits to Warpwobble Poison
  packs/equipment/warpwobble-poison.json
Labels: pr: data update

#16469 Add effects for Malleable Clay, Predator's Claw, Tiger Menuki
  packs/equipment-effects/effect-malleable-clay.json
  packs/equipment-effects/effect-predators-claw.json
  packs/equipment-effects/effect-tiger-menuki.json
  packs/equipment/malleable-clay.json
  packs/equipment/predators-claw.json
  packs/equipment/tiger-menuki.json
Labels: pr: data update

#16464 Replace level for rank in unlimited potential
  packs/feats/unlimited-potential.json
Labels: pr: data update

#16463 Correct price and level of Energy Adaptive rune
  src/module/item/physical/runes.ts
Labels: pr: data update

#16489 Add inline acrobatics action and circumstance bonus to Acrobatic Performer
  packs/feats/acrobatic-performer.json
Labels: pr: data update

#16488 Replace level by rank in catharsis emotion
  packs/classfeatures/catharsis-emotion.json
Labels: pr: data update

#16486 Correct description of Shadow Signet
  packs/equipment/shadow-signet.json
Labels: pr: data update

#16482 Split certain crafting functions and defer use of async
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/crafting/crafting.ts
  src/module/actor/character/crafting/index.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/rules/helpers.ts
  src/module/rules/rule-element/crafting-entry.ts
Labels: pr: refactor

#16499 Move Werecreature Dedication automation from effect to feat
  packs/feats/werecreature-dedication.json
Labels: pr: data update

#16498 Add some base types to Animal Attack
  packs/ancestryfeatures/animal-attack.json
Labels: pr: data update

#16493 Restrict Mutant Physique's effets to Bestial Mutagen Strikes only
  packs/ancestryfeatures/horns-sarangay.json
  packs/classfeatures/animal-instinct.json
  packs/equipment-effects/effect-bestial-mutagen-greater.json
  packs/equipment-effects/effect-bestial-mutagen-lesser.json
  packs/equipment-effects/effect-bestial-mutagen-major.json
  packs/equipment-effects/effect-bestial-mutagen-moderate.json
  packs/equipment/berserkers-cloak-greater.json
  packs/equipment/berserkers-cloak.json
  packs/feat-effects/effect-kishin-rage.json
  packs/feats/crown-of-bone.json
  packs/feats/mutant-physique.json
  packs/feats/oni-weapon-familiarity.json
  packs/heritages/versatile-heritages/hungerseed.json
Labels: pr: data update

#16502 Remove unneeded martial weapon restriction from Oni Weapon Familiarity predicate
  packs/feats/oni-weapon-familiarity.json
Labels: pr: data update

#16496 Update Ghoul Hide to Player Core 2
  packs/equipment/ghoul-hide.json
  packs/equipment/sanguine-pendant-greater.json
  packs/equipment/sanguine-pendant.json
  packs/equipment/sash-of-prowess-greater.json
  packs/equipment/sash-of-prowess.json
Labels: pr: data update

#16494 Add effect for Mummified Bat and update some talisman descriptions
  packs/equipment-effects/effect-mummified-bat.json
  packs/equipment/basilisk-eye.json
  packs/equipment/bloodseeker-beak-greater.json
  packs/equipment/bloodseeker-beak.json
  packs/equipment/brine-dragon-scale.json
  packs/equipment/crying-angel-pendant.json
  packs/equipment/dazing-coil.json
  packs/equipment/dispelling-sliver.json
  packs/equipment/fear-gem.json
  packs/equipment/flame-navette.json
  packs/equipment/hunters-bane.json
  packs/equipment/iron-cube.json
  packs/equipment/iron-cudgel.json
  packs/equipment/iron-equalizer.json
  packs/equipment/jade-cat.json
  packs/equipment/monkey-pin.json
  packs/equipment/mummified-bat.json
  packs/equipment/murderers-knot.json
  packs/equipment/salve-of-antiparalysis-greater.json
  packs/equipment/salve-of-antiparalysis.json
  packs/equipment/savior-spike.json
  packs/equipment/swift-block-cabochon.json
Labels: pr: data update

#16492 Add some inline damage and healing links
  packs/book-of-the-dead-bestiary/ecorche.json
  packs/menace-under-otari-bestiary/wight-bb.json
  packs/pathfinder-bestiary-2/grendel.json
  packs/pathfinder-bestiary-2/void-zombie.json
  packs/pathfinder-bestiary/grim-reaper.json
  packs/pathfinder-monster-core/grim-reaper.json
  packs/pathfinder-monster-core/tomb-jelly.json
  packs/pfs-season-3-bestiary/raseri-kanton-skeleton.json
  packs/strength-of-thousands-bestiary/aspect-of-immortality.json
Labels: pr: data update

#16491 Restrict Explosion of Power's Damage Alteration to its own inline damage
  packs/feats/explosion-of-power.json
Labels: pr: data update

#16468 Add Roll Options for Bard composition spell effects tracking
  packs/spell-effects/spell-effect-courageous-anthem.json
  packs/spell-effects/spell-effect-hymn-of-healing.json
  packs/spell-effects/spell-effect-rallying-anthem.json
  packs/spell-effects/spell-effect-silvers-refrain.json
  packs/spell-effects/spell-effect-song-of-strength.json
  packs/spell-effects/spell-effect-triple-time.json
  packs/spell-effects/spell-effect-uplifting-overture.json
  packs/spells/silvers-refrain.json
  packs/spells/uplifting-overture.json
Labels: pr: data update

#16462 Fix description formatting in several PFS actors
  packs/pfs-season-6-bestiary/apple-turnover.json
  packs/pfs-season-6-bestiary/blood-soaked-flytrap.json
  packs/pfs-season-6-bestiary/bloodsick-wild-dog.json
  packs/pfs-season-6-bestiary/puddles-phantom-5-6.json
  packs/pfs-season-6-bestiary/puddles-phantom.json
  packs/pfs-season-6-bestiary/sudden-drop.json
  packs/pfs-season-6-bestiary/veteran-pure-legionnaire.json
Labels: pr: data update

#16490 Fix rule elements on Bone Missile
  packs/feats/bone-missile.json
Labels: pr: data update

#16504 Fix rules on Conspirator Dragons
  packs/pathfinder-monster-core/conspirator-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-adult.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient.json
  packs/pathfinder-monster-core/conspirator-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-young.json
  packs/prey-for-death-bestiary/vatumledor.json
Labels: pr: data update

#16503 Fix automation of Kitsune Change Shape
  packs/ancestries/kitsune.json
  packs/ancestryfeatures/change-shape.json
  packs/feats/myriad-forms.json
  packs/heritages/kitsune/celestial-envoy-kitsune.json
  packs/heritages/kitsune/dark-fields-kitsune.json
  packs/heritages/kitsune/earthly-wilds-kitsune.json
  packs/heritages/kitsune/empty-sky-kitsune.json
  packs/heritages/kitsune/frozen-wind-kitsune.json
  packs/heritages/kitsune/palace-echoes-kitsune.json
Labels: pr: data update

#16511 Fix prices of "Greater Helm of Zeal" and "Greater Sash of Prowess"
  packs/equipment/helm-of-zeal-greater.json
  packs/equipment/sash-of-prowess-greater.json
Labels: pr: data update

#16505 Automate Unholy Plate and update Warleader's Bulwark effect
  packs/equipment-effects/effect-command-bravery.json
  packs/equipment-effects/effect-holy-chain.json
  packs/equipment/holy-chain.json
  packs/equipment/unholy-plate.json
  packs/equipment/warleaders-bulwark-greater.json
  packs/equipment/warleaders-bulwark.json
  static/lang/re-en.json
Labels: pr: data update

#16500 Add stance effect for Stretching Reach
  packs/feat-effects/stance-stretching-reach.json
  packs/feats/stretching-reach.json
Labels: pr: data update

#16514 Remove no-longer-needed `ActorDelta#prepareData` override
  src/module/scene/token-document/actor-delta.ts
Labels: pr: refactor

#16516 Add creature traits to hazards
  src/module/system/settings/homebrew/data.ts
  src/scripts/config/traits.ts
Labels: pr: data update

#16513 Remove non-unified effects for Shifting Form and Traveler's Transit
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-shifting-form-claws.json
  packs/spell-effects/spell-effect-shifting-form-climb-speed.json
  packs/spell-effects/spell-effect-shifting-form-darkvision.json
  packs/spell-effects/spell-effect-shifting-form-scent.json
  packs/spell-effects/spell-effect-shifting-form-speed.json
  packs/spell-effects/spell-effect-shifting-form-swim-speed.json
  packs/spell-effects/spell-effect-travelers-transit-climb.json
  packs/spell-effects/spell-effect-travelers-transit-fly.json
  packs/spell-effects/spell-effect-travelers-transit-swim.json
  packs/spell-effects/spell-effect-travelers-transit.json
Labels: pr: data update

#16518 Add agile trait to Durnolith claw attack
  packs/wardens-of-wildwood-bestiary/durnolith.json
Labels: pr: data update

#16519 Update publication source for currency
  packs/equipment/copper-pieces.json
  packs/equipment/gold-pieces.json
  packs/equipment/platinum-pieces.json
  packs/equipment/silver-pieces.json
Labels: pr: data update

#16522 Remove Exploding Shield duplicate activation
  packs/equipment/exploding-shield.json
Labels: pr: data update

#16523 Update Moderate Drakeheart Mutagen publication to PC2
  packs/equipment/drakeheart-mutagen-moderate.json
Labels: pr: data update

#16524 Fix save type of Banshee's Wail
  packs/pathfinder-monster-core/banshee.json
Labels: pr: data update

#16525 Add missing Item Alteration for Redemption cause Exalted Reaction
  packs/classfeatures/exalted-reaction.json
Labels: pr: data update

#16526 Condense Elemental Gift and Evolution Surge effects
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-elemental-gift-air.json
  packs/spell-effects/spell-effect-elemental-gift-earth.json
  packs/spell-effects/spell-effect-elemental-gift-fire.json
  packs/spell-effects/spell-effect-elemental-gift-water.json
  packs/spell-effects/spell-effect-evolution-surge-amphibious.json
  packs/spell-effects/spell-effect-evolution-surge-climb.json
  packs/spell-effects/spell-effect-evolution-surge-fly.json
  packs/spell-effects/spell-effect-evolution-surge-huge.json
  packs/spell-effects/spell-effect-evolution-surge-large.json
  packs/spell-effects/spell-effect-evolution-surge-scent.json
  packs/spell-effects/spell-effect-evolution-surge-sight.json
  packs/spell-effects/spell-effect-evolution-surge-speed.json
Labels: pr: data update

#16527 Fix Stunning Snare critical success formatting
  packs/equipment/stunning-snare.json
Labels: pr: data update

#16528 Fix some missing emphasis in descriptions
  packs/blog-bestiary/firebrand-brass-dragon-ancient.json
  packs/journals/archetypes.json
  packs/pathfinder-bestiary-2/sandpoint-devil.json
Labels: pr: data update

#16529 Remove old label from Tricky Liniment effect link
  packs/equipment-effects/effect-tricky-liniment.json
  packs/equipment/tricky-liniment.json
Labels: pr: data update

#16530 Update NPC Blood Frenzy to be self effect
  packs/pathfinder-bestiary/bunyip.json
  packs/pathfinder-bestiary/sea-devil-baron.json
  packs/pathfinder-bestiary/sea-devil-brute.json
  packs/pathfinder-bestiary/sea-devil-scout.json
  packs/pfs-season-1-bestiary/sea-devil-invader.json
  packs/pfs-season-2-bestiary/baron-utomo-3-4.json
  packs/pfs-season-2-bestiary/baron-utomo-5-6.json
  packs/pfs-season-2-bestiary/saddleback-bunyip.json
  packs/pfs-season-2-bestiary/sea-devil-impaler.json
  packs/pfs-season-2-bestiary/the-saboteur-3-4.json
  packs/pfs-season-2-bestiary/the-saboteur-5-6.json
Labels: pr: data update

#16531 Update Oni Form to be self effect
  packs/feats/oni-form.json
Labels: pr: data update

#16458 Automate Fortissimo Composition
  packs/spell-effects/spell-effect-fortissimo-composition.json
  packs/spells/fortissimo-composition.json
Labels: pr: data update

#16533 Update additional instances of inline damage to the new format
  packs/age-of-ashes-bestiary/falrok.json
  packs/age-of-ashes-bestiary/lazurite-infused-stone-golem.json
  packs/bestiary-family-ability-glossary/ghast-consume-flesh.json
  packs/blood-lords-bestiary/straugh.json
  packs/blood-lords-bestiary/urglid.json
  packs/kingmaker-bestiary/tulvak.json
  packs/npc-gallery/demonologist.json
  packs/npc-gallery/despot.json
  packs/paizo-pregens/zane-ikundi.json
  packs/pathfinder-bestiary-2/morlock.json
  packs/pathfinder-bestiary-2/vanth.json
  packs/pathfinder-bestiary/gourd-leshy.json
  packs/pathfinder-bestiary/stone-golem.json
Labels: pr: data update

#16520 Re-add kaiju trait to hazard traits
  src/scripts/config/traits.ts
Labels: pr: data update

#16539 Correct spell link for Fleshforged Conformer Wear Flesh ability
  packs/impossible-lands-bestiary/fleshforged-conformer.json
Labels: pr: data update

#16535 Add Critical Specialization RE to Bard composition effects
  packs/classfeatures/bard-weapon-expertise.json
  packs/classfeatures/spell-repertoire.json
Labels: pr: data update

#16540 Fix Unstoppable Juggernaut and automate Superstition's Raging Resistance
  packs/classfeatures/animal-instinct.json
  packs/classfeatures/decay-instinct.json
  packs/classfeatures/dragon-instinct.json
  packs/classfeatures/fury-instinct.json
  packs/classfeatures/giant-instinct.json
  packs/classfeatures/ligneous-instinct.json
  packs/classfeatures/spirit-instinct.json
  packs/classfeatures/superstition-instinct.json
  packs/feats/unstoppable-juggernaut.json
  static/lang/re-en.json
Labels: pr: data update

#16546 Replace lower-resolution system icons with identical core icons
  packs/age-of-ashes-bestiary/candlarons-echo.json
  packs/age-of-ashes-bestiary/emaliza-zandivar.json
  packs/age-of-ashes-bestiary/mengkare.json
  packs/agents-of-edgewatch-bestiary/ilsetsya-wyrmtouched.json
  packs/bestiary-effects/effect-crystalline-dust-form.json
  packs/blood-lords-bestiary/intellect-assemblage.json
  packs/blood-lords-bestiary/matron-uldrula.json
  packs/blood-lords-bestiary/shadow-leydroth.json
  packs/book-of-the-dead-bestiary/provincial-jiang-shi.json
  packs/campaign-effects/resonant-reflection-reflection-of-light.json
  packs/campaign-effects/resonant-reflection-reflection-of-stone.json
  packs/classfeatures/bloodline-elemental.json
  packs/feat-effects/effect-elemental-blood-magic-self.json
  packs/feats/foxfire.json
  packs/feats/venom-spit.json
  packs/heritages/nagaji/hooded-nagaji.json
  packs/kingmaker-bestiary/avatar-of-the-lantern-king.json
  packs/kingmaker-bestiary/fetch-behemoth.json
  packs/kingmaker-bestiary/fetch-stalker.json
  packs/kingmaker-bestiary/ilthuliak.json
  packs/kingmaker-bestiary/irovettis-fetch.json
  packs/kingmaker-bestiary/nyrissa.json
  packs/kingmaker-bestiary/phomandala.json
  packs/kingmaker-bestiary/the-wriggling-man.json
  packs/kingmaker-bestiary/thresholder-mystic.json
  packs/outlaws-of-alkenstar-bestiary/brighite-herexen.json
  packs/paizo-pregens/takemiru.json
  packs/pathfinder-bestiary-2/leydroth.json
  packs/pathfinder-bestiary-2/olethrodaemon.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/draconal-red.json
  packs/pathfinder-bestiary/pleroma.json
  packs/rage-of-elements-bestiary/austral-the-south-wind.json
  packs/spell-effects/aura-protectors-sphere.json
  packs/spell-effects/spell-effect-contagious-idea-pleasant-thought.json
  packs/spell-effects/spell-effect-nature-incarnate-green-man.json
  packs/spell-effects/spell-effect-nature-incarnate-kaiju.json
  packs/spell-effects/spell-effect-nature-incarnate.json
  packs/spell-effects/spell-effect-protectors-sphere.json
  packs/spells/contagious-idea.json
  packs/spells/delay-consequence.json
  packs/spells/diamond-dust.json
  packs/spells/disjunction.json
  packs/spells/divine-armageddon.json
  packs/spells/eidolons-wrath.json
  packs/spells/geyser.json
  packs/spells/ghostly-tragedy.json
  packs/spells/ghostly-transcription.json
  packs/spells/interstellar-void.json
  packs/spells/moonburst.json
  packs/spells/nature-incarnate.json
  packs/spells/nullify.json
  packs/spells/ode-to-ouroboros.json
  packs/spells/oneiric-mire.json
  packs/spells/overflowing-sorrow.json
  packs/spells/pillars-of-sand.json
  packs/spells/protectors-sphere.json
  packs/spells/redistribute-potential.json
  packs/stolen-fate-bestiary/speaker-of-svaryr.json
Labels: pr: data update

#16544 Correct typo in Revolutionary Innovation class feature description
  packs/classfeatures/revolutionary-innovation.json
Labels: pr: data update

#16552 Automate Deadly Grace feat
  packs/feats/deadly-grace.json
Labels: pr: data update

#16542 Release Notes 6.4.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#16558 Fix typo in Archer Dedication localization
  packs/feats/archer-dedication.json
Labels: pr: data update

#16564 Add effect for Taper of Sanctification
  packs/equipment-effects/effect-taper-of-sanctification.json
  packs/equipment/taper-of-sanctification.json
Labels: pr: data update

#16559 Remove non-unified effects for Primal Summons
  packs/spell-effects/spell-effect-primal-summons-air.json
  packs/spell-effects/spell-effect-primal-summons-earth.json
  packs/spell-effects/spell-effect-primal-summons-fire.json
  packs/spell-effects/spell-effect-primal-summons-water.json
Labels: pr: data update

#16556 Automate Smoothing Aeon Stone's penalty suppression
  packs/equipment/aeon-stone-smoothing.json
Labels: pr: data update

#16562 Automate Dire Growth feat for Werecreature dedication
  packs/feats/dire-growth.json
Labels: pr: data update

#16553 Add spell effect for Anointed Ground
  packs/spell-effects/spell-effect-anointed-ground.json
  packs/spells/anointed-ground.json
Labels: pr: data update

#16545 Update additional instances of inline damage to the new format.
  packs/blood-lords-bestiary/mithral-golem.json
  packs/pathfinder-bestiary-3/blood-hag.json
  packs/pathfinder-bestiary-3/caulborn.json
  packs/pathfinder-bestiary-3/clockwork-dragon.json
  packs/pathfinder-bestiary-3/corrupted-relic.json
  packs/pathfinder-bestiary-3/duende.json
  packs/pathfinder-bestiary-3/fossil-golem.json
  packs/pathfinder-bestiary-3/hesperid-queen.json
  packs/pathfinder-bestiary-3/hesperid.json
  packs/pathfinder-bestiary-3/kimenhul.json
  packs/pathfinder-bestiary-3/leng-ghoul.json
  packs/pathfinder-bestiary-3/lifeleecher-brawler.json
  packs/pathfinder-bestiary-3/mithral-golem.json
  packs/pathfinder-bestiary-3/popobawa.json
  packs/pathfinder-bestiary-3/seaweed-leshy.json
  packs/pathfinder-bestiary-3/skinstitch.json
  packs/pathfinder-bestiary-3/valkyrie.json
  packs/pathfinder-bestiary-3/vine-leshy.json
  packs/pathfinder-bestiary-3/winter-hag.json
  packs/pathfinder-bestiary-3/wizard-sponge-crypt.json
  packs/pathfinder-bestiary-3/wizard-sponge-fey-domain.json
  packs/pathfinder-bestiary-3/wizard-sponge-fiendish-temple.json
  packs/pathfinder-bestiary-3/wizard-sponge-toxic-lair.json
  packs/pathfinder-bestiary-3/wizard-sponge-underwater.json
  packs/pathfinder-bestiary-3/wizard-sponge.json
  packs/pfs-season-4-bestiary/coven-winter-hag.json
Labels: pr: data update

#16567 Update Expert Disassembly description to PC2
  packs/feats/expert-disassembly.json
Labels: pr: data update

#16570 Enable Martial Weapon expertise for Swashbuckler in Weapon Expertise class feature
  packs/classfeatures/weapon-expertise.json
Labels: pr: data update

#16576 Implement dice upgrade for Diamond Fists
  packs/feats/deadly-grace.json
  packs/feats/diamond-fists.json
Labels: pr: data update

#16578 Restore Godless Healing Feat
  packs/feats/godless-healing.json
Labels: pr: data update

#16566 Correct typo in Spit Ambient Magic inline damage roll
  packs/actions/spit-ambient-magic.json
Labels: pr: data update

#16579 Fix description of Fortuitous Shift
  packs/feats/fortuitous-shift.json
Labels: pr: data update

#16574 Fix some incorrect inline damage formulas
  packs/equipment/knapsack-of-halflingkind-greater.json
  packs/equipment/knapsack-of-halflingkind.json
  packs/equipment/panacea-fruit.json
  packs/equipment/tallowheart-mass.json
  packs/equipment/therapeutic-snap-peas.json
  packs/pfs-season-4-bestiary/deimostride-9-10.json
  packs/pfs-season-4-bestiary/weak-clacking-skull-swarm.json
  packs/pfs-season-5-bestiary/elite-sewer-ooze-pfs-q18.json
  packs/sky-kings-tomb-bestiary/glacial-worm.json
  static/lang/re-en.json
Labels: pr: data update

#16555 Use Damage Alteration to increase die size in Clay Sphere effect
  packs/equipment-effects/effect-clay-sphere-weapon-damage-increase.json
Labels: pr: data update

#16568 Fix some formatting
  packs/equipment/wooden-nickel.json
  packs/familiar-abilities/grasping-tendrils.json
  packs/familiar-abilities/purify-air.json
  packs/familiar-abilities/verdant-burst.json
Labels: pr: data update

#16563 Add check to Party swap method to avoid non-initiative actors
  src/module/encounter/combatant.ts
Labels: pr: bugfix
