Repository foundryvtt/pf2e, pull requests merged in 2024-06, with the labels that each got.

#14917 Fix path to "The Common Language" selected option in homebrew settings
  static/templates/system/settings/homebrew.hbs
Labels: pr: bugfix

#14910 Use kit items as testbed for `TypeDataModel`-based system data
  build/lib/compendium-pack.ts
  src/module/data.ts
  src/module/item/base/data/schema.ts
  src/module/item/base/data/system.ts
  src/module/item/base/document.ts
  src/module/item/kit/data.ts
  src/module/item/kit/document.ts
  src/module/item/physical/data.ts
  src/module/item/physical/schema.ts
  src/module/migration/migrations/841-v11-uuid-format.ts
  src/module/system/schema-data-fields.ts
  src/scripts/hooks/init.ts
  types/foundry/client/config.d.ts
Labels: pr: refactor

#14902 Make Ranger Weapon Expertise give critical specialization to unarmed Strikes
  packs/classfeatures/ranger-weapon-expertise.json
Labels: pr: data update

#14919 Import `DataField` types in kit/data.ts from module instead of file path
  src/module/item/kit/data.ts
Labels: pr: types update

#14921 Convert melee items to use `TypeDataModel`-based system data
  build/lib/extractor.ts
  src/module/actor/sheet/base.ts
  src/module/item/melee/data.ts
  src/module/item/melee/document.ts
  src/module/item/melee/sheet.ts
  src/module/item/weapon/document.ts
  src/module/migration/migrations/885-convert-alignment-damage.ts
  src/scripts/hooks/init.ts
Labels: pr: refactor

#14918 Rename SkillLongForm to SkillSlug and remove more abbreviation data
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/character/types.ts
  src/module/actor/creature/data.ts
  src/module/actor/creature/document.ts
  src/module/actor/data/base.ts
  src/module/actor/familiar/document.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/skills-editor.ts
  src/module/actor/party/sheet.ts
  src/module/actor/types.ts
  src/module/actor/values.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/module/item/background/data.ts
  src/module/item/class/data.ts
  src/module/item/class/document.ts
  src/module/item/deity/data.ts
  src/module/item/deity/sheet.ts
  src/module/item/identification.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/migration/migrations/749-assurance-res.ts
  src/module/migration/migrations/914-move-perception-senses.ts
  src/module/migration/migrations/927-class-background-skill-longform.ts
  src/module/migration/migrations/928-character-skills-longform.ts
  src/module/recall-knowledge.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/battle-form/types.ts
  src/module/rules/rule-element/fixed-proficiency.ts
  src/module/rules/rule-element/special-statistic.ts
  src/module/system/action-macros/general/recall-knowledge.ts
  src/module/system/settings/homebrew/helpers.ts
Labels: pr: refactor

#14929 Update `Token` type for v12
  src/module/canvas/token/object.ts
  src/module/scene/helpers.ts
  src/module/scene/token-document/clown-car.ts
  types/foundry/client/pixi/placeable.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/common/constants.d.ts
Labels: pr: types update, pr: foundry v12

#14925 Localize attach button
  static/lang/en.json
  static/templates/items/item-attacher.hbs
Labels: pr: bugfix

#14930 Make retrieving mergeable roll options to toggle more consistent
  src/module/rules/rule-element/roll-option/rule-element.ts
Labels: pr: bugfix

#14945 Handle choice set skill options with the 929 migration
  packs/backgrounds/able-carter.json
  packs/backgrounds/construction-occultist.json
  packs/backgrounds/food-trader.json
  packs/backgrounds/money-counter.json
  packs/backgrounds/propaganda-promoter.json
  packs/feats/molten-wit.json
  src/module/migration/migrations/929-more-skills-longform.ts
Labels: pr: bugfix, pr: data update

#14946 Fix sourceId in wand on Padli
  packs/abomination-vaults-bestiary/padli.json
Labels: pr: data update

#14947 Fix Shielding Wave to apply either acid or fire resistance
  packs/feat-effects/effect-shielding-wave.json
Labels: pr: data update

#14948 Avoid using `blank` property in `selectOptions` helper for JSON data
  src/module/item/deity/sheet.ts
  static/templates/items/deity-details.hbs
Labels: pr: bugfix, pr: foundry v12

#14950 Handle upgrade dice in roll inspector and "none" showing even if there are dice
  src/module/chat-message/roll-inspector.ts
  src/module/system/damage/dialog.ts
  src/module/system/damage/helpers.ts
  static/templates/chat/roll-inspector.hbs
Labels: ui/ux

#14955 Add properties in V12's `DocumentStatsField`
  types/foundry/common/data/fields.d.ts
Labels: pr: types update

#14953 Remove move trait from Gylou's Reflexive Grab
  packs/pathfinder-bestiary-2/gylou.json
  packs/pathfinder-monster-core/gylou.json
Labels: pr: data update

#14949 Remove superfluous predicate in Ocean's Bite
  packs/feats/oceans-bite.json
Labels: pr: data update

#14944 Brush up Rusted Door
  packs/rusthenge-bestiary/rusted-door.json
Labels: pr: data update

#14943 Update Glass Shield and Fire Shield
  packs/spell-effects/spell-effect-fire-shield.json
  packs/spells/glass-shield.json
Labels: pr: data update

#14937 Update Chilling Darkness to use target traits rather than overlay
  packs/spells/chilling-darkness.json
  packs/spells/holy-light.json
Labels: pr: data update

#14936 Fix dual onslaught prerequisites
  packs/feats/dual-onslaught.json
Labels: pr: data update

#14934 Add overlay to Cry of Destruction
  packs/spells/cry-of-destruction.json
Labels: pr: data update

#14932 Fix damage formatting in Falling Portcullis
  packs/kingmaker-bestiary/falling-portcullis.json
Labels: pr: data update

#14895 Fix incr. familiar prerequisites for familiar master
  packs/feats/incredible-familiar-familiar-master.json
Labels: pr: data update

#14924 Fix malformed HTML in Reveal Hidden Self
  packs/feats/reveal-hidden-self.json
Labels: pr: data update

#14928 Add spell effect for Mind of Menace
  packs/pathfinder-dark-archive/mother-mitera.json
  packs/spell-effects/spell-effect-mind-of-menace.json
  packs/spells/mind-of-menace.json
Labels: pr: data update

#14961 Move impulse junction notes to feat description alterations
  packs/classfeatures/air-gate.json
  packs/classfeatures/earth-gate.json
  packs/classfeatures/metal-gate.json
  packs/classfeatures/water-gate.json
  packs/classfeatures/wood-gate.json
Labels: pr: data update

#14962 Update spell effect for Distracting Decoy to include off-guard grant
  packs/spell-effects/spell-effect-distracting-decoy-critical-failure.json
  packs/spell-effects/spell-effect-distracting-decoy.json
  packs/spells/distracting-decoy.json
  packs/spells/slime-spit.json
Labels: pr: data update

#14969 Release Notes 6.0.0 Beta 3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14972 Update kingdom to prosemirror and fix settlement expand/collapse behavior
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/styles/actor/party/kingdom/_ongoing.scss
  src/styles/actor/party/kingdom/_world.scss
  static/templates/actors/party/kingdom/partials/settlement.hbs
  static/templates/actors/party/kingdom/tabs/ongoing.hbs
Labels: pr: bugfix, kingmaker

#14975 Use current UUID format exclusively
  src/module/actor/base.ts
  src/module/apps/compendium-browser/loader.ts
  src/module/migration/migrations/720-update-spell-descriptions.ts
  src/module/migration/migrations/747-fixed-heightening.ts
  src/module/system/module-art.ts
  types/foundry/client/data/collections/compendium-collection.d.ts
Labels: pr: bugfix, pr: types update, pr: foundry v12

#14959 Make Strike attribute resolvable
  src/module/rules/rule-element/strike.ts
Labels: pr: enhancement

#14981 Update icon for Serum of Sex Shift
  static/icons/equipment/consumables/potions/serum-of-sex-shift.webp
Labels: pr: static assets

#14985 Add missing action and fix skill on SoG NPC
  packs/season-of-ghosts-bestiary/ren-mei-li.json
Labels: pr: data update

#14984 Change Spore Order to correct skill training
  packs/classfeatures/spore-order.json
Labels: pr: data update

#14255 Remake item transfer dialog, gms can now gift items and receive warnings when funds are insufficient rather than fail silently.
  src/module/actor/base.ts
  src/module/actor/item-transfer.ts
  src/module/actor/loot/document.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/loot/move-loot-popup.ts
  src/module/actor/sheet/popups/item-transfer-dialog.ts
  src/module/actor/sheet/popups/loot-npcs-popup.ts
  src/scripts/socket.ts
  src/styles/actor/_index.scss
  src/styles/actor/_item-transfer-dialog.scss
  static/lang/en.json
  static/templates/popups/item-transfer-dialog.hbs
  static/templates/popups/loot/move-loot-popup.hbs
Labels: pr: enhancement

#14990 Add "axes" as resistance type
  src/module/actor/data/iwr.ts
  src/scripts/config/iwr.ts
  static/lang/en.json
Labels: pr: enhancement

#14991 Add support for drag/drop repositioning of regions
  src/module/canvas/region.ts
  src/module/scene/region-document/document.ts
  src/scripts/hooks/init.ts
  types/foundry/client/data/documents/region-document.d.ts
  types/foundry/client/pixi/layers/base/placeables-layer.d.ts
  types/foundry/client/pixi/placeable.d.ts
  types/foundry/client/pixi/placeables/region.d.ts
Labels: pr: enhancement

#14982 Fix minor issues with bestiary ability glossary items
  packs/bestiary-ability-glossary-srd/trample.json
  packs/bestiary-family-ability-glossary/ghost-corrupting-gaze.json
Labels: pr: data update

#14983 Add Max Badge Value to Mutilating Bite
  packs/bestiary-effects/effect-mutilating-bite.json
Labels: pr: data update

#14986 Change references to Strength value in text to modifier
  packs/equipment/rite-of-reinforcement-exoskeleton.json
  packs/equipment/titan-nagaji-scales.json
  packs/equipment/tough-skin.json
  packs/feats/reinforced-chassis.json
  packs/feats/tough-skin.json
  packs/heritages/athamaru/coral-athamaru.json
  packs/heritages/conrasu/rite-of-reinforcement.json
  packs/heritages/nagaji/titan-nagaji.json
  packs/heritages/surki/hardshell-surki.json
Labels: pr: data update, remaster

#14992 Fix description formatting of Siren Song
  packs/feats/siren-song.json
Labels: pr: data update

#14995 Fix vision mode initialization before the canvas is ready
  src/module/canvas/token/object.ts
Labels: pr: bugfix, pr: foundry v12

#14997 Exempt generated NPC attacks from trait filtering if weapon is RE-generated
  src/module/item/weapon/document.ts
  src/module/rules/rule-element/strike.ts
Labels: pr: enhancement

#15000 Unconditionally super up in `TokenDocumentPF2e#prepareBaseData`
  src/module/scene/token-document/document.ts
Labels: pr: bugfix, pr: foundry v12

#14999 Fix Pagulin survival variant
  packs/highhelm-bestiary/pagulin.json
Labels: pr: data update

#14994 Add Illusion to NPC Attack Traits
  src/scripts/config/traits.ts
Labels: pr: enhancement

#14996 Fix description of Metamorphosis
  packs/spells/metamorphosis.json
Labels: pr: data update

#14987 Add damage button to Thermal Nimbus matching choice of damage type
  packs/feat-effects/effect-thermal-nimbus-cold.json
  packs/feat-effects/effect-thermal-nimbus-fire.json
  packs/feats/thermal-nimbus.json
Labels: pr: data update

#15005 Add `LaxArrayField` to prune invalid elements from arrays
  src/module/item/melee/data.ts
  src/module/system/schema-data-fields.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: bugfix

#15006 Add safeguard to prevent setting invalid token dimensions from invalid actor size
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#15004 Use CreatureSize RE instead of AE-like in Fleshwarp ancestry
  packs/ancestries/fleshwarp.json
Labels: pr: data update

#15007 Fix incorrect med to medicine conversions in some selections
  build/run-migration.ts
  packs/paizo-pregens/jaithe.json
  src/module/migration/migrations/929-remove-skill-abbreviations.ts
  src/module/migration/migrations/930-choice-set-medium.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: bugfix, pr: data migration

#14939 Brush up some bestiary automation for Howl of the Wild
  packs/bestiary-effects/effect-grab-debris.json
  packs/bestiary-effects/effect-static-field.json
  packs/howl-of-the-wild-bestiary/scroungefeather.json
  packs/howl-of-the-wild-bestiary/shotalashu.json
  packs/howl-of-the-wild-bestiary/sky-fisher.json
  packs/howl-of-the-wild-bestiary/soniphak.json
  packs/howl-of-the-wild-bestiary/sporeback-frog.json
  packs/howl-of-the-wild-bestiary/stonefish-swarm.json
  packs/howl-of-the-wild-bestiary/stonefish.json
  packs/howl-of-the-wild-bestiary/stony-bat.json
  packs/howl-of-the-wild-bestiary/stony-goat.json
  packs/howl-of-the-wild-bestiary/storm-snake.json
  packs/howl-of-the-wild-bestiary/sunscale-serpent.json
  packs/howl-of-the-wild-bestiary/swordfish.json
  src/module/actor/creature/values.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#14968 Improve automation of Fire Shield
  packs/spell-effects/spell-effect-fire-shield.json
  packs/spells/fire-shield.json
  static/lang/re-en.json
Labels: pr: data update

#14979 Fix automation of Awakened Animal and Swimming Animal heritage
  packs/ancestries/awakened-animal.json
  packs/heritages/awakened-animal/swimming-animal.json
Labels: pr: data update

#15011 Add publication title for Open the Wall of Ghosts
  packs/spells/open-the-wall-of-ghosts.json
Labels: pr: data update

#15013 Show roll mode indicator in damage rolls
  static/templates/dice/damage-tooltip.hbs
Labels: pr: enhancement

#15014 Handle `SceneConfigPF2e#_onChangeInput` events with blank environment value
  src/module/scene/sheet.ts
Labels: pr: bugfix

#15015 Add campaign effect for Stoop
  packs/campaign-effects/effect-stoop.json
Labels: pr: data update, kingmaker

#15010 Add Howl of the Wild barbarian instinct options
  packs/classfeatures/animal-instinct.json
  packs/feat-effects/effect-web.json
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#15016 Update `MultiSelectInputConfig` types
  types/foundry/client-esm/applications/forms/fields.d.ts
Labels: pr: types update

#15017 Fix path for second Clan Lore skill
  packs/feats/clan-lore.json
Labels: pr: data update

#15008 Remove `ProseMirrorMenuPF2e` subclass and patch some `ProseMirrorMenu` methdos instead
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/item/base/sheet/sheet.ts
  src/module/journal-entry/sheet.ts
  src/module/system/prosemirror-menu.ts
  src/scripts/hooks/get-prosemirror-menu-dropdowns.ts
  src/scripts/hooks/index.ts
  src/scripts/🐵🩹.ts
  types/foundry/common/prosemirror/menu.d.ts
Labels: pr: refactor, pr: foundry v12

#15022 Fix detection of stowed within recursive containers
  src/module/item/physical/document.ts
Labels: pr: bugfix

#15021 Show invested icon within non-stowing containers
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#15019 Migrate choice set selections recursively (remigrate if you're on master)
  src/module/migration/migrations/929-remove-skill-abbreviations.ts
  src/module/migration/migrations/930-choice-set-medium.ts
Labels: pr: bugfix

#15025 Set `source` in config of `PointVisionSourcePF2e#hearing`
  src/module/canvas/perception/point-vision-source.ts
  types/foundry/client/pixi/core/shapes/source-polygon.d.ts
Labels: pr: bugfix

#15026 Update token config templates to latest core version
  static/templates/scene/token/partials/appearance.hbs
  static/templates/scene/token/partials/lighting.hbs
Labels: pr: foundry v12

#15031 Fix set of malformed source IDs in wands
  packs/age-of-ashes-bestiary/scarlet-triad-mage.json
  packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
  packs/pfs-season-1-bestiary/doctor-velshun-5-6.json
  packs/pfs-season-1-bestiary/doctor-velshun-7-8.json
  packs/pfs-season-2-bestiary/chesjilawa-jadwiga-karina-5-6.json
  packs/pfs-season-2-bestiary/chesjilawa-jadwiga-karina-7-8.json
Labels: pr: data update

#15030 Release Notes 6.0.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#15039 Prevent table creation and addition with result sizes that are too large
  src/module/apps/compendium-browser/tabs/base.ts
  static/lang/en.json
Labels: pr: enhancement

#15048 Include thrown traits in `isRanged` test for melee items
  src/module/item/melee/document.ts
Labels: pr: bugfix

#15056 Fix Striking RE
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#15054 Do not show item purchase give button to players
  src/module/actor/sheet/popups/item-transfer-dialog.ts
  src/styles/actor/_item-transfer-dialog.scss
  static/templates/popups/item-transfer-dialog.hbs
Labels: pr: bugfix

#15051 Update table result type to v12 definition
  types/foundry/common/constants.d.ts
  types/foundry/common/documents/table-result.d.ts
Labels: pr: types update

#15024 Fix localized string location for Spell Effect: Fire Shield
  static/lang/re-en.json
Labels: pr: data update

#15023 Brush up some bestiary automation for Howl of the Wild
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-abysium.json
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-adamantine.json
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-djezet.json
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-inubrix.json
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-noqual.json
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-orichalcum.json
  packs/bestiary-family-ability-glossary/stargut-hydra-skymetal-metamorphosis-siccatite.json
  packs/howl-of-the-wild-bestiary/mocking-chorus.json
  packs/howl-of-the-wild-bestiary/prismhydra.json
  packs/howl-of-the-wild-bestiary/stargut-hydra.json
  packs/howl-of-the-wild-bestiary/tyrafdir.json
  static/lang/re-en.json
Labels: pr: data update

#15027 Add spell effect for Hippocampus Retreat
  packs/spell-effects/spell-effect-hippocampus-retreat.json
  packs/spells/hippocampus-retreat.json
Labels: pr: data update

#15029 Add links to Summon Warden of the Wild description
  packs/spells/summon-warden-of-the-wild.json
Labels: pr: data update

#15047 add Grab Ability to Unrisen (BotD) actor
  packs/book-of-the-dead-bestiary/unrisen.json
Labels: pr: data update

#15046 Update Shisagishin to add Grab to its melee attack
  packs/season-of-ghosts-bestiary/shisagishin.json
Labels: pr: data update

#15045 Add custom resistance exception for Iron Warden
  packs/pathfinder-monster-core/iron-warden.json
  static/lang/re-en.json
Labels: pr: data update

#15044 correct Fire Giant's (Monster Core) Flame Attack
  packs/pathfinder-monster-core/fire-giant.json
Labels: pr: data update

#15041 Remove broken spell link from Mahathallah
  packs/deities/mahathallah.json
Labels: pr: data update

#15036 Update relic descriptions
  packs/adventure-specific-actions/feral-claws.json
  packs/adventure-specific-actions/flare-bolt.json
  packs/adventure-specific-actions/form-of-fury.json
  packs/adventure-specific-actions/heat-haze.json
  packs/adventure-specific-actions/searing-wave.json
Labels: pr: data update

#15062 Fix typo in terrain localization
  static/lang/en.json
Labels: pr: data update

#15059 Show damage type override label in dialog
  src/module/system/damage/dialog.ts
  src/module/system/damage/helpers.ts
  static/lang/en.json
Labels: pr: bugfix

#15055 Fix Token Image RE form converting path to an array
  src/module/rules/rule-element/token-image.ts
  src/styles/item/_rules.scss
  static/templates/items/rules/partials/resolvable-value.hbs
  static/templates/items/rules/token-image.hbs
Labels: pr: bugfix, pr: foundry v12

#15061 Allow motion sense to be imprecise or vague
  src/module/actor/creature/values.ts
Labels: pr: bugfix

#15068 Fill container when editing hazard source code
  src/styles/actor/hazard/_index.scss
Labels: pr: bugfix, ui/ux

#15071 Add missing inline check to Ring Bell action
  packs/actions/ring-bell.json
  packs/pfs-season-5-bestiary/arrogant-entodemonologist.json
  packs/pfs-season-5-bestiary/blood-shadow-mirror.json
  packs/pfs-season-5-bestiary/deskari-cultist.json
  packs/pfs-season-5-bestiary/deskari-effigy.json
  packs/pfs-season-5-bestiary/deskari-fantatic.json
  packs/pfs-season-5-bestiary/elite-hound-of-tindalos.json
  packs/pfs-season-5-bestiary/empowered-deskari-effigy.json
  packs/pfs-season-5-bestiary/entodemonologist.json
  packs/pfs-season-5-bestiary/greater-blood-shadow-mirror.json
  packs/pfs-season-5-bestiary/hardened-locust-knight.json
  packs/pfs-season-5-bestiary/husk-shield.json
  packs/pfs-season-5-bestiary/jamimpi.json
  packs/pfs-season-5-bestiary/locust-knight.json
  packs/pfs-season-5-bestiary/locust-swarm.json
  packs/pfs-season-5-bestiary/paper-locust-swarm.json
  packs/pfs-season-5-bestiary/paper-locust-tornado.json
  packs/pfs-season-5-bestiary/ravenous-locust-swarm.json
  packs/pfs-season-5-bestiary/resolved-jamimpi.json
  packs/pfs-season-5-bestiary/shining-shooting-sphere.json
  packs/pfs-season-5-bestiary/shooting-sphere.json
  packs/pfs-season-5-bestiary/the-inscrutable-librarian.json
  packs/pfs-season-5-bestiary/the-librarian.json
Labels: pr: data update

#15073 Tidy up some formatting
  packs/feats/claw-and-talon-flow.json
  packs/pfs-season-5-bestiary/blood-shadow-mirror.json
  packs/pfs-season-5-bestiary/deskari-effigy.json
  packs/pfs-season-5-bestiary/elite-hound-of-tindalos.json
  packs/pfs-season-5-bestiary/empowered-deskari-effigy.json
  packs/pfs-season-5-bestiary/greater-blood-shadow-mirror.json
  packs/pfs-season-5-bestiary/jamimpi.json
  packs/pfs-season-5-bestiary/paper-locust-swarm.json
  packs/pfs-season-5-bestiary/paper-locust-tornado.json
  packs/pfs-season-5-bestiary/resolved-jamimpi.json
  packs/pfs-season-5-bestiary/shining-shooting-sphere.json
  packs/pfs-season-5-bestiary/shooting-sphere.json
  packs/pfs-season-5-bestiary/the-inscrutable-librarian.json
  packs/pfs-season-5-bestiary/the-librarian.json
Labels: pr: data update

#15070 Add ancestry features to centaur
  packs/ancestries/centaur.json
  packs/ancestryfeatures/mount.json
  packs/ancestryfeatures/robust.json
Labels: pr: data update

#15075 Fix item alteration override markdown
  src/module/item/helpers.ts
Labels: pr: bugfix

#15074 Fix duration for Spell Effect: Incendiary Aura
  packs/spell-effects/spell-effect-incendiary-aura.json
  packs/spells/incendiary-aura.json
Labels: pr: data update

#15077 Clean up x/y setter code in `RegionDocumentPF2e`
  src/module/scene/region-document/document.ts
Labels: pr: refactor

#15082 Update tinymce package to version used in FVTT V12
  package-lock.json
  package.json
Labels: pr: housekeeping, pr: types update

#15080 Remove optimizations in system detection modes
  src/module/canvas/perception/modes.ts
Labels: pr: refactor, pr: foundry v12

#15081 Ensure `EnvironmentCanvasGroup` is initialized with prepared environment data
  src/module/canvas/group/environment.ts
  src/module/scene/helpers.ts
  src/scripts/hooks/init.ts
  src/scripts/hooks/load.ts
Labels: pr: bugfix, pr: foundry v12

#15058 Omit invalid character skills from system data
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/sheet.ts
Labels: pr: refactor, pr: delay merge

#15086 Type for Macro.execute() can accept additional properties for scope
  types/foundry/client/data/documents/macro.d.ts
Labels: pr: types update

#15087 Fix Token Light rule element localization paths
  static/templates/items/rules/token-light.hbs
Labels: pr: bugfix

#15084 Add venomous trait automation
  src/module/system/damage/weapon.ts
Labels: pr: enhancement

#15089 Call subitems' secondary data preparation methods
  src/module/item/physical/document.ts
  src/module/item/weapon/document.ts
Labels: pr: bugfix

#15090 Fix inconsistent line heights with inline links and content links
  src/styles/_globals.scss
Labels: ui/ux

#15095 Add surki language
  src/module/actor/creature/values.ts
  static/lang/en.json
Labels: pr: data update

#15088 Release Notes 6.0.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#15098 Fix auras not being drawn when a token is created
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#15101 Update Release 6.0.2 notes
  CHANGELOG.md
Labels: pr: housekeeping

#15102 Set defaults for type params in JournalEntryPage
  types/foundry/client/config.d.ts
  types/foundry/client/data/documents/journal-entry-page.d.ts
Labels: pr: types update

#15094 Fix selector for Eye for Masonry
  packs/feats/eye-for-masonry.json
Labels: pr: data update

#14940 Update Rule Elements UI setting to manage access by user role
  build/run-migration.ts
  src/global.ts
  src/module/item/base/sheet/sheet.ts
  src/module/migration/migrations/931-expand-re-permissions.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/system/settings/index.ts
  static/lang/en.json
Labels: pr: enhancement

#15107 Remove newline in Venomtail Kobold
  packs/heritages/kobold/venomtail-kobold.json
Labels: pr: data update

#15110 Fix default value of "minimumRulesUI" setting
  src/global.ts
  src/module/item/base/sheet/sheet.ts
  src/module/system/settings/index.ts
Labels: pr: bugfix

#15112 Fix data prep for self cyclical containers
  src/module/item/container/document.ts
Labels: pr: bugfix

#15114 Cleanup region-related types
  src/global.ts
  src/module/actor/helpers.ts
  src/module/scene/index.ts
  src/module/scene/region-behavior/document.ts
  src/module/scene/region-behavior/environment.ts
  src/module/scene/region-behavior/types.ts
  src/module/scene/region-document/document.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/data/documents/region-behavior.d.ts
  types/foundry/client/data/documents/region-document.d.ts
Labels: pr: types update

#15109 Remove duplicate Critical Success in Hallucination description
  packs/spells/hallucination.json
Labels: pr: data update

#15118 add Ulgrem Axaan Ichor Trail ability
  packs/bestiary-family-ability-glossary/ulgrem-axaan-ichor-trail.json
Labels: pr: data update

#15108 Replace earth with water in the description of Spell Effect: Elemental Form (Water)
  packs/spell-effects/spell-effect-elemental-form-water.json
Labels: pr: data update

#15085 Add automation for Ankhrav Duster
  packs/equipment-effects/effect-caustic-jabs.json
  packs/equipment/ankhrav-duster.json
  packs/equipment/hive-mother-bottle.json
  packs/equipment/sargassum-phial.json
Labels: pr: data update

#15123 Fix synchronize darkness for current scene default option when changing the world default
  src/module/system/settings/world-clock.ts
Labels: pr: bugfix

#15122 Release Notes 6.0.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#15125 Remove rule for success note from Greater Rooting rune
  src/module/item/physical/runes.ts
Labels: pr: data update

#15129 Link up `Actor#toggleStatusEffect` with `ActorPF2e#toggleCondition`
  src/module/actor/base.ts
Labels: pr: enhancement

#15130 Trim down `ActorPF2e.createDialog`
  src/module/actor/base.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/item/base/document.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/common/packages/base-system.d.ts
Labels: pr: refactor

#15009 Move inline check/action/template listeners to global handlers
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/apps/effects-panel.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base/sheet/sheet.ts
  src/module/system/text-editor.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-dialog.ts
  src/scripts/hooks/render-journal-text-page-sheet.ts
  src/scripts/hooks/setup.ts
  src/scripts/ui/inline-roll-links.ts
  src/scripts/ui/user-visibility.ts
Labels: pr: enhancement

#15134 Fix Leukodaemon's Breath Weapon description
  packs/pathfinder-bestiary/leukodaemon.json
Labels: pr: data update

#15133 Add Spirit of the Beast spell link to the feat
  packs/feats/spirit-of-the-beast.json
  packs/spell-effects/spell-effect-spirit-of-the-beast.json
  packs/spells/spirit-of-the-beast.json
Labels: pr: data update

#15128 Fix typos in spell descriptions
  packs/howl-of-the-wild-bestiary/alicorn.json
  packs/spells/hedge-prison.json
  packs/spells/maze-of-locked-doors.json
  packs/spells/telepathy.json
  packs/spells/veil-of-confidence.json
  packs/wardens-of-wildwood-bestiary/unaasi.json
Labels: pr: data update

#15127 Replace level with rank in Unimpeded Stride description
  packs/spells/unimpeded-stride.json
Labels: pr: data update

#15097 Add custom weakness for Cursed Guardian's Deadeye's Shame
  packs/kingmaker-bestiary/cursed-guardian.json
Labels: pr: data update, kingmaker

#15106 Automate Curse Maelstrom Archetype features
  packs/actions/expel-maelstrom.json
  packs/feat-effects/effect-curse-maelstrom-state.json
  packs/feat-effects/effect-expel-maelstrom-failure-or-critical-failure.json
  packs/feat-effects/effect-expel-maelstrom-misfortune.json
  packs/feat-effects/effect-expel-maelstrom-success.json
  packs/feats/curse-maelstrom-dedication.json
  packs/feats/torrential-backlash.json
Labels: pr: data update

#15144 Prevent strike MAP adjustments from being applied twice
  src/module/actor/character/document.ts
Labels: pr: bugfix

#15143 Bring rune hiding on armor sheets in line with weapon sheets
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/item/armor/sheet.ts
  src/module/item/physical/runes.ts
  static/templates/items/armor-details.hbs
Labels: pr: bugfix

#15146 Remove em tag in Wyrm Drinker spell list
  packs/equipment/wyrm-drinker.json
Labels: pr: data update

#15153 Add "check:roll:total:natural:" roll option for backward compatibility
  src/module/system/check/check.ts
Labels: pr: bugfix

#15154 Fix regression with actor fallback and kingdom rolls in chat messages
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#15156 Fix rendering of invisible creatures when see-invisibility mode is in use
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#15158 Fix `isItemUuid` helper for V12
  src/util/uuid.ts
  types/foundry/client/data/collections/compendium-collection.d.ts
Labels: pr: bugfix

#15162 Remove workaround of upstream token border coloration
  src/module/canvas/token/object.ts
Labels: pr: foundry v12

#15163 Prevent ae-likes from processing paths that start with "data."
  src/module/rules/rule-element/ae-like.ts
Labels: pr: foundry v12

#15164 Handle AE-like paths starting with "data." in migration 928
  src/module/migration/migrations/928-character-skills-longform.ts
Labels: pr: data migration

#15165 Update NPM dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#15167 Release Notes 6.0.4
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#15176 Update loading roll parser source for peggy v4
  src/module/system/damage/roll.ts
  vite.config.ts
Labels: pr: bugfix, pr: housekeeping

#15159 Provide `item:` roll options for inline saving throws
  src/module/actor/roll-context/base.ts
  src/module/actor/roll-context/types.ts
  src/module/system/statistic/statistic.ts
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: enhancement

#15180 Fix regression with chat message inline saves and fix resolution in party exploration
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#15155 Use real `ActiveEffect`s instead of mostly-interface-matching `TokenEffect` class
  src/module/active-effect.ts
  src/module/actor/base.ts
  src/module/actor/token-effect.ts
  src/module/rules/rule-element/token-effect-icon.ts
  src/module/rules/synthetics.ts
  types/foundry/client/data/documents/active-effect.d.ts
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/common/documents/active-effect.d.ts
Labels: pr: refactor

#15183 Include sub items in choice sets
  src/module/actor/helpers.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix
