Repository foundryvtt/pf2e, pull requests merged in 2024-07, with the labels that each got.

#15312 Brush up Tarantula Ampoule for Howl of the Wild
  packs/equipment/tarantula-ampoule.json
  packs/pathfinder-monster-core/giant-tarantula.json
Labels: pr: data update

#15297 Fix damage type and kinds of Field of Life spell
  packs/spells/field-of-life.json
Labels: pr: data update

#15294 Brushup Winged Warrior feats
  packs/feats/feathered-flechettes.json
  packs/feats/gusting-spell.json
  packs/feats/pluck-from-the-sky.json
  packs/feats/sunbird-glare.json
  static/lang/re-en.json
Labels: pr: data update

#15288 Make inline damage roll for Cauterize Wounds immutable
  packs/spells/cauterize-wounds.json
Labels: pr: data update

#15287 Update Distracting Explosion and Electrify Armor unstable DC to 15
  packs/feats/distracting-explosion.json
  packs/feats/electrify-armor.json
Labels: pr: data update

#15267 Brush up worn items for Howl of the Wild
  packs/equipment-effects/effect-watery-form.json
  packs/equipment/amphisbaena-handwraps.json
  packs/equipment/amulet-of-the-hellcat.json
  packs/equipment/dweomerveil.json
  packs/equipment/high-contrast-goggles.json
  packs/equipment/mantle-of-the-tikbalang.json
  packs/equipment/orm-choker.json
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#15315 Fix encounter tracker turn coloration
  src/module/apps/sidebar/encounter-tracker.ts
Labels: pr: bugfix, ui/ux

#15289 Add icons to Surki effects
  packs/feat-effects/effect-repel-ambient-magic.json
  packs/feat-effects/effect-turn-aside-ambient-magic.json
Labels: pr: data update

#15293 Brushup Wild Mimic feats
  packs/feats/electrogenesis.json
  packs/feats/emergency-regeneration.json
  packs/feats/ferocity-mimicry.json
  packs/feats/lassoing-lash.json
  packs/feats/petrifying-gaze-mimicry.json
  packs/feats/rend-mimicry.json
  packs/feats/roar-mimicry.json
  packs/feats/trample-mimicry.json
  packs/feats/wild-speech.json
Labels: pr: data update

#15254 Support retrieving sub items from messages (nested uuid variant)
  src/module/chat-message/document.ts
  src/module/item/physical/document.ts
Labels: pr: enhancement

#15243 Update choice REs for labelled objects and support choices in predicates
  packs/feats/skill-training.json
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: enhancement

#15320 Ensure spell slot index is valid when casting
  src/module/item/spellcasting-entry/document.ts
Labels: pr: bugfix

#15200 Add item and origin to appliedDamage messages
  src/module/actor/base.ts
  src/module/chat-message/data.ts
Labels: pr: enhancement

#15324 Add simple token drag measurement support
  src/global.ts
  src/module/canvas/index.ts
  src/module/canvas/layer/token.ts
  src/module/canvas/ruler.ts
  src/module/system/settings/index.ts
  src/scripts/hooks/canvas-ready.ts
  src/scripts/hooks/load.ts
  src/scripts/register-keybindings.ts
  src/scripts/set-game-pf2e.ts
  static/lang/en.json
Labels: pr: enhancement

#15323 Fix errata'd price for Trollhound Pick
  packs/equipment/trollhound-pick.json
Labels: pr: data update

#15325 Fix drag/drop of multiple selected regions
  src/module/canvas/region.ts
  types/foundry/client/pixi/placeable.d.ts
Labels: pr: bugfix

#15329 Refine detection of drag-measurement targets
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
  src/scripts/hooks/canvas-ready.ts
  src/scripts/register-keybindings.ts
  types/foundry/client/config.d.ts
Labels: pr: bugfix

#15330 Fix drag measurement quirk when ending drag at starting grid square
  src/module/canvas/token/object.ts
  src/scripts/hooks/canvas-ready.ts
Labels: pr: bugfix

#15331 Fix `resolveValue`'s handling of arrays
  src/module/rules/rule-element/base.ts
Labels: pr: bugfix

#15326 Consolidate separate "New (Melee/Ranged) Attack" buttons on NPC sheet
  src/module/actor/sheet/base.ts
  static/templates/actors/npc/tabs/main.hbs
Labels: ui/ux

#15333 Fix regression with npc lores not extracting modifier adjustments
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#15334 Split homebrew files
  src/module/system/settings/homebrew/damage.ts
  src/module/system/settings/homebrew/languages.ts
  src/module/system/settings/homebrew/menu.ts
Labels: pr: refactor

#15336 Fix application of two-hand trait from strike adjustments to weapon damage dice
  src/module/actor/character/document.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/helpers.ts
Labels: pr: bugfix

#15340 Fix tagify tags overflow in item sheet header and allow `,` delimiter in feat sheet prerequesites
  src/module/item/feat/sheet.ts
  src/styles/item/_header.scss
  src/util/tags.ts
Labels: pr: bugfix

#15337 Measure along with actual token drag
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
  src/scripts/hooks/canvas-ready.ts
  types/foundry/client/pixi/core/interaction/mouse-handler.d.ts
  types/foundry/client/pixi/layers/base/placeables-layer.d.ts
  types/foundry/client/pixi/layers/controls/layer.d.ts
  types/foundry/client/pixi/layers/controls/ruler.d.ts
Labels: pr: refactor

#15344 Don't autoscale new actors if prototype token is initially set to non-default
  src/module/actor/base.ts
Labels: pr: enhancement

#15343 Brush up spell catalysts for Howl of the Wild
  packs/equipment-effects/effect-amphisbaena-spittle.json
  packs/equipment/alicorn-hair.json
  packs/equipment/amphisbaena-spittle.json
  packs/equipment/broken-rams-thorn.json
  packs/equipment/chaos-falcon-feather.json
  packs/equipment/dischoran-rubble.json
  packs/equipment/hippogriff-feather.json
  packs/equipment/kirin-echo-chime.json
  packs/equipment/kushtaka-relic.json
  packs/equipment/ogre-spider-filament.json
  packs/equipment/silvered-marp-fur.json
  packs/equipment/skyfisher-vapors.json
  packs/equipment/wemmuth-trinket.json
  packs/equipment/witchwarg-fur.json
  packs/equipment/wolliped-fleece.json
Labels: pr: data update

#15339 Brush up adventuring gear for Howl of the Wild
  packs/equipment-effects/effect-animal-blind.json
  packs/equipment-effects/effect-catch-pole.json
  packs/equipment-effects/effect-portable-animal-blind.json
  packs/equipment/animal-blind.json
  packs/equipment/animal-call.json
  packs/equipment/catch-pole.json
  packs/equipment/field-guide.json
  packs/equipment/flower-press.json
  packs/equipment/giant-catch-pole.json
  packs/equipment/land-delvers-chair.json
  packs/equipment/oilskin-pouch.json
  packs/equipment/portable-animal-blind.json
  packs/equipment/superior-catch-pole.json
  packs/equipment/supramarine-chair.json
  packs/equipment/travelers-chair.json
  packs/equipment/trundle-wheel.json
Labels: pr: data update

#15345 Add inline damage links to Vibrant Thorns
  packs/extinction-curse-bestiary/herecite-of-zevgavizeb.json
  packs/extinction-curse-bestiary/xulgath-deepmouth.json
  packs/spells/vibrant-thorns.json
Labels: pr: data update

#15328 Fix widen the gap prerequisites
  packs/feats/widen-the-gap.json
Labels: pr: data update

#15327 Fix reverse engineering prerequisite
  packs/feats/reverse-engineering.json
Labels: pr: data update

#15346 Remove check for `event.buttons` in ruler drag-cancel handler
  src/module/canvas/ruler.ts
Labels: pr: bugfix

#15313 Fix Pernicious Spore Bomb (Lesser) RE text
  packs/equipment/pernicious-spore-bomb-lesser.json
  static/lang/re-en.json
Labels: pr: data update

#15318 Fix error in Strix journal
  packs/journals/ancestries.json
Labels: pr: data update

#15338 Automate Cooperative Soul
  packs/feats/cooperative-soul.json
Labels: pr: data update

#15348 Prevent token dragging when using ruler tool
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#15342 Include weapon-compatible traits when generating weapon from shield
  src/module/item/shield/document.ts
Labels: pr: bugfix

#15351 Fix regression with resolvables on nested arrays
  src/module/rules/rule-element/base.ts
Labels: pr: bugfix

#15233 Add icons to some of the built-in action implementations
  src/module/system/action-macros/acrobatics/balance.ts
  src/module/system/action-macros/acrobatics/maneuver-in-flight.ts
  src/module/system/action-macros/acrobatics/squeeze.ts
  src/module/system/action-macros/acrobatics/tumble-through.ts
  src/module/system/action-macros/athletics/climb.ts
  src/module/system/action-macros/athletics/disarm.ts
  src/module/system/action-macros/athletics/force-open.ts
  src/module/system/action-macros/athletics/grapple.ts
  src/module/system/action-macros/athletics/high-jump.ts
  src/module/system/action-macros/athletics/long-jump.ts
  src/module/system/action-macros/athletics/reposition.ts
  src/module/system/action-macros/athletics/shove.ts
  src/module/system/action-macros/athletics/swim.ts
  src/module/system/action-macros/athletics/trip.ts
  src/module/system/action-macros/basic/escape.ts
  src/module/system/action-macros/basic/seek.ts
  src/module/system/action-macros/basic/sense-motive.ts
  src/module/system/action-macros/deception/create-a-diversion.ts
  src/module/system/action-macros/deception/feint.ts
  src/module/system/action-macros/deception/impersonate.ts
  src/module/system/action-macros/deception/lie.ts
  src/module/system/action-macros/diplomacy/gather-information.ts
  src/module/system/action-macros/diplomacy/make-an-impression.ts
  src/module/system/action-macros/diplomacy/request.ts
  src/module/system/action-macros/exploration/avoid-notice.ts
  src/module/system/action-macros/exploration/sense-direction.ts
  src/module/system/action-macros/exploration/track.ts
  src/module/system/action-macros/general/decipher-writing.ts
  src/module/system/action-macros/general/subsist.ts
  src/module/system/action-macros/intimidation/coerce.ts
  src/module/system/action-macros/intimidation/demoralize.ts
  src/module/system/action-macros/medicine/administer-first-aid.ts
  src/module/system/action-macros/medicine/treat-disease.ts
  src/module/system/action-macros/medicine/treat-poison.ts
  src/module/system/action-macros/nature/command-an-animal.ts
  src/module/system/action-macros/performance/perform.ts
  src/module/system/action-macros/society/create-forgery.ts
  src/module/system/action-macros/stealth/conceal-an-object.ts
  src/module/system/action-macros/stealth/hide.ts
  src/module/system/action-macros/stealth/sneak.ts
  src/module/system/action-macros/thievery/disable-device.ts
  src/module/system/action-macros/thievery/palm-an-object.ts
  src/module/system/action-macros/thievery/pick-a-lock.ts
  src/module/system/action-macros/thievery/steal.ts
Labels: pr: enhancement

#15291 Add Action Frequency Tracking to Familiar and NPC sheets
  src/module/actor/familiar/sheet.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/data-types.ts
  src/styles/actor/_red-action-boxes.scss
  static/templates/actors/npc/partials/action.hbs
Labels: pr: enhancement

#15352 Add `isSecret` getter to `TokenDocument` type definition
  types/foundry/client/data/documents/token-document.d.ts
Labels: pr: types update

#15350 Ensure lore skill slugs end with -lore to prevent conflicts
  src/module/actor/character/document.ts
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#15360 Set default `delimiters` value to `,` in `tagify` helper function
  src/util/tags.ts
Labels: pr: bugfix

#15361 Make `Region` configurable type param of `Canvas`
  src/module/canvas/index.ts
  src/module/canvas/region.ts
  src/module/scene/document.ts
  src/module/scene/region-document/document.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/pixi/board.d.ts
  types/foundry/common/documents/region.d.ts
Labels: pr: types update

#15141 Add support for additional skills from module flags
  src/module/system/settings/homebrew/damage.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/helpers.ts
  src/module/system/settings/homebrew/menu.ts
Labels: pr: enhancement

#15359 Fix name of "Familiar of Parasitic Might"
  packs/familiar-abilities/familiar-of-parasitic-might.json
Labels: pr: data update

#15354 Add automation for Worm Caller Dedication's Inexorable feat
  packs/feats/inexorable.json
Labels: pr: data update

#15353 Automate immobilized immunity for NPC Inexorable ability
  packs/blood-lords-bestiary/shadow-worm.json
  packs/pathfinder-bestiary/azure-worm.json
  packs/pathfinder-bestiary/crimson-worm.json
  packs/pathfinder-bestiary/purple-worm.json
  packs/pfs-season-3-bestiary/languid-purple-worm.json
  packs/sky-kings-tomb-bestiary/glacial-worm.json
  packs/sky-kings-tomb-bestiary/gray-worm.json
  packs/strength-of-thousands-bestiary/aspect-of-hunger.json
  packs/strength-of-thousands-bestiary/gluttonworm.json
Labels: pr: data update

#15366 Update some pixi-related types with recent upstream changes
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/layers/grid/layer.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/common/grid/base.d.ts
Labels: pr: types update

#15368 Fix token defaults not being taken up on compendium-actor imports
  src/module/actor/helpers.ts
Labels: pr: bugfix

#15365 Add environment feature region behavior (just with difficult terrain for now)
  src/module/canvas/region.ts
  src/module/scene/index.ts
  src/module/scene/region-behavior/document.ts
  src/module/scene/region-behavior/environment-feature.ts
  src/module/scene/region-behavior/environment.ts
  src/module/scene/region-behavior/index.ts
  src/module/scene/region-behavior/types.ts
  src/module/scene/region-behavior/values.ts
  src/scripts/hooks/i18n-init.ts
  src/scripts/hooks/load.ts
  src/scripts/hooks/ready.ts
  static/lang/en.json
  static/system.json
Labels: pr: enhancement

#14452 Add roll option and aelike re support to hazards
  src/module/actor/base.ts
  src/module/actor/creature/document.ts
  src/module/actor/party/document.ts
  src/module/actor/vehicle/document.ts
  src/styles/actor/hazard/_index.scss
  static/templates/actors/hazard/sheet.hbs
Labels: pr: enhancement

#15369 Prevent parties from being created or moved into folders
  src/module/actor/base.ts
  src/module/actor/party/document.ts
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/common/documents/actor.d.ts
Labels: pr: bugfix

#15370 Use `ModifierPF2e#signedValue` where appropriate
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
  src/module/system/damage/formula.ts
Labels: pr: refactor

#15371 Fix detection of item drops on tokens
  src/scripts/hooks/drop-canvas-data.ts
Labels: pr: bugfix

#15321 Include `@Check` traits as item traits
  src/scripts/ui/inline-roll-links.ts
Labels: pr: enhancement

#15375 Fix typos in Grazing Deer hazard
  packs/one-shot-bestiary/grazing-deer.json
Labels: pr: data update

#15373 Fix typo in Favored Prey
  packs/feats/favored-prey.json
Labels: pr: data update

#15258 Automate Revolutionary Innovation
  packs/classfeatures/attack-refiner.json
  packs/classfeatures/automated-impediments.json
  packs/classfeatures/deadly-strike.json
  packs/classfeatures/energy-barrier.json
  packs/classfeatures/enhanced-damage.json
  packs/classfeatures/extensible-weapon.json
  packs/classfeatures/impossible-alloy.json
  packs/classfeatures/incredible-resistance.json
  packs/classfeatures/momentum-retainer.json
  packs/classfeatures/multisensory-mask.json
  packs/classfeatures/omnirange-stabilizers.json
  packs/classfeatures/perfect-fortification.json
  packs/classfeatures/physical-protections.json
  packs/classfeatures/revolutionary-innovation.json
  packs/classfeatures/rune-capacity.json
Labels: pr: data update

#15381 Restore z-cycling of token stacks
  src/module/canvas/index.ts
  src/module/canvas/layer/token.ts
  src/module/canvas/token/object.ts
  src/scripts/register-keybindings.ts
  static/lang/en.json
Labels: pr: enhancement

#15379 Add `splitListString` helper for consistent splitting of roll link parameters
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
  src/util/misc.ts
Labels: pr: bugfix

#15382 Add build process for including UUID redirects
  build/uuid-redirects.json
  packs/feat-effects/effect-overdrive-success.json
  src/global.ts
  src/scripts/hooks/init.ts
  types/foundry/client/config.d.ts
  vite.config.ts
Labels: pr: enhancement, pr: housekeeping

#15241 Fix rule elements on Nephilim Lore
  packs/feats/nephilim-lore.json
Labels: pr: data update

#15385 Fix the case of several feats
  packs/blood-lords-bestiary/decrosia.json
  packs/blood-lords-bestiary/iron-taviah.json
  packs/blood-lords-bestiary/rust-hag.json
  packs/blood-lords-bestiary/sahni-bride-of-the-sea.json
  packs/book-of-the-dead-bestiary/pale-sovereign.json
  packs/equipment/chronomancer-staff.json
  packs/equipment/curious-teardrop.json
  packs/feats/between-the-scales.json
  packs/feats/form-of-the-bat.json
  packs/feats/reptile-rider.json
  packs/feats/skill-training.json
  packs/feats/symphony-of-blood.json
  packs/feats/voice-of-the-night.json
  packs/quest-for-the-frozen-flame-bestiary/summer-hora-queen.json
  packs/quest-for-the-frozen-flame-bestiary/summer-hora.json
  packs/sky-kings-tomb-bestiary/heartbroken-dream.json
  packs/spells/curse-of-lost-time.json
Labels: pr: data update

#15386 Update which token is hovered after z-cycling stacks
  src/module/canvas/layer/token.ts
Labels: pr: enhancement, ui/ux

#15387 Refine click behavior following token z-cycling
  src/module/canvas/layer/token.ts
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#15376 Replace lower-resolution icon for Purge Sins
  packs/feats/purge-sins.json
Labels: pr: data update

#15384 Fix Thaumaturge Tome Implement description
  packs/classfeatures/tome.json
Labels: pr: data update

#15355 Automate Concussive trait via damage "redirection"
  src/module/actor/army/document.ts
  src/module/actor/character/elemental-blast.ts
  src/module/item/affliction/document.ts
  src/module/item/physical/runes.ts
  src/module/item/spell/document.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/dialog.ts
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/types.ts
  src/module/system/damage/weapon.ts
  src/module/system/text-editor.ts
  static/lang/en.json
  static/templates/chat/damage/iwr-breakdown.hbs
Labels: pr: enhancement

#15377 Add automation for Erastil - Moderate Boon
  packs/boons-and-curses/erastil-moderate-boon.json
Labels: pr: data update

#15391 add grant item to Clawdancer dedication
  packs/actions/claw-stance.json
  packs/actions/talon-stance.json
  packs/feats/clawdancer-dedication.json
Labels: pr: data update

#15392 add special statistic rule element to Verdant Core deviant class
  packs/classfeatures/verdant-core-deviant-classification.json
Labels: pr: data update

#15393 update aid DC for Recall the Teachings action
  packs/actions/recall-the-teachings.json
Labels: pr: data update

#15395 Fix display of background item rarity
  src/module/item/base/sheet/sheet.ts
Labels: pr: bugfix

#15401 Set ephemeral effect context data upon extraction
  src/module/actor/roll-context/base.ts
  src/module/rules/helpers.ts
Labels: pr: bugfix

#15400 Fix regression from chat messages referring to compendium items
  src/module/chat-message/document.ts
Labels: pr: bugfix

#15403 Make various small corrections to PIXI-related types
  types/foundry/client/pixi/board.d.ts
  types/foundry/client/pixi/layers/controls/ruler.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/grid/base.d.ts
Labels: pr: types update

#15404 Widen drag-measure ruler when measuring with larger tokens
  src/module/canvas/effect-area-square.ts
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
  src/scripts/register-keybindings.ts
Labels: pr: enhancement

#15402 Force party actors to retain actor link
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  static/lang/en.json
Labels: pr: bugfix

#15396 Add content from Curtain Call Player's Guide
  packs/backgrounds/always-chosen-last.json
  packs/backgrounds/amateur-director.json
  packs/backgrounds/art-tutor.json
  packs/backgrounds/bully-or-baiter.json
  packs/backgrounds/sideshow-scion.json
  packs/backgrounds/supportive-sponsor.json
  packs/backgrounds/town-troublemaker.json
  packs/backgrounds/wandering-libertine.json
  packs/campaign-effects/persona-trait.json
  packs/deities/the-curtain-call.json
  src/module/item/background/types.ts
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: source: adventure path, pr: data entry

#15407 Minor whitespace cleanup for actions on npc sheet
  src/styles/actor/_red-action-boxes.scss
  src/styles/actor/character/_actions.scss
  src/styles/actor/tabs/_actions.scss
  src/styles/actor/vehicle/_index.scss
  static/lang/en.json
  static/templates/actors/npc/partials/action.hbs
  static/templates/actors/partials/action.hbs
Labels: ui/ux

#15408 Add toggle to hide strikes from stowed weapons
  src/module/actor/character/sheet.ts
  src/module/actor/data/base.ts
  src/styles/actor/_index.scss
  static/lang/en.json
  static/templates/actors/character/partials/strike.hbs
  static/templates/actors/character/tabs/actions.hbs
Labels: pr: enhancement

#15409 Remove `ActorDirectoryPF2e#_render`
  src/module/apps/sidebar/actor-directory.ts
  types/foundry/client/apps/app.d.ts
  types/foundry/client/apps/sidebar/document-directory.d.ts
Labels: pr: refactor

#15417 Allow Marvelous Medicines to be used when not held
  packs/equipment/marvelous-medicines-greater.json
  packs/equipment/marvelous-medicines.json
Labels: pr: data update

#15416 Make Resonating Fork (Major) attack roll in line with others
  packs/equipment/resonating-fork-major.json
Labels: pr: data update

#15394 Add public notes to Gallowdead
  packs/book-of-the-dead-bestiary/gallowdead.json
Labels: pr: data update

#15398 update Weapon Property Rune localization
  static/lang/en.json
Labels: pr: data update

#15406 Fix Sceaduinar's spell list and give it void healing
  packs/pathfinder-bestiary-2/sceaduinar.json
Labels: pr: data update

#15410 add feet in bramble bush range
  packs/spells/bramble-bush.json
Labels: pr: data update

#15413 Fix Major Inflammation Flask description and publication data
  packs/equipment/inflammation-flask-greater.json
  packs/equipment/inflammation-flask-major.json
  packs/equipment/inflammation-flask-moderate.json
Labels: pr: data update

#15414 Brush up some Player Core general feats
  packs/feats/breath-control.json
  packs/feats/experienced-professional.json
  packs/feats/fast-recovery.json
  packs/feats/lengthy-diversion.json
  packs/feats/oddity-identification.json
  packs/feats/schooled-in-secrets.json
  packs/feats/streetwise.json
  packs/feats/student-of-the-canon.json
  packs/feats/subtle-theft.json
  packs/feats/terrain-stalker.json
  static/lang/re-en.json
Labels: pr: data update

#15423 Separate `PanningDirection` and `MovementDirection` types
  types/foundry/client/keyboard/client-keybindings.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/grid/base.d.ts
  types/foundry/common/grid/gridless.d.ts
  types/foundry/common/grid/hexagonal.d.ts
  types/foundry/common/grid/square.d.ts
  types/foundry/common/module.d.ts
Labels: pr: types update

#15419 Remove gap between name and buttons for unready strikes
  src/styles/actor/character/_actions.scss
  src/styles/actor/tabs/_actions.scss
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/actors/character/partials/strike.hbs
Labels: ui/ux

#15420 Correct usage and description of Silver Salve
  packs/equipment/silver-salve.json
Labels: pr: data update

#15275 add rule elements to remaining Player Core Spellshape feats
  packs/feat-effects/effect-current-spell.json
  packs/feats/call-and-response.json
  packs/feats/cast-down.json
  packs/feats/conceal-spell.json
  packs/feats/current-spell-elementalist.json
  packs/feats/current-spell.json
  packs/feats/ebb-and-flow.json
  packs/feats/echoing-channel.json
  packs/feats/form-control.json
  packs/feats/garland-spell.json
  packs/feats/healing-transformation.json
  packs/feats/heroic-recovery.json
  packs/feats/ley-line-conduit.json
  packs/feats/martyr.json
  packs/feats/melodious-spell.json
  packs/feats/remediate.json
  packs/feats/snowdrift-spell.json
  packs/feats/sow-spell.json
  packs/feats/split-hex.json
  packs/feats/thunderclap-spell.json
  packs/feats/widen-spell.json
  static/lang/re-en.json
Labels: pr: data update

#15429 add missing Perception bonuses to select NPCs
  packs/menace-under-otari-bestiary/pugwampi-bb.json
  packs/monsters-of-myth-bestiary/kuworsys.json
  packs/npc-gallery/burglar.json
  packs/npc-gallery/guard.json
  packs/npc-gallery/jailer.json
  packs/npc-gallery/physician.json
  packs/outlaws-of-alkenstar-bestiary/atticus.json
  packs/pathfinder-bestiary-3/deimavigga.json
  packs/pathfinder-bestiary-3/nyktera.json
  packs/pathfinder-bestiary/balisse.json
  packs/pathfinder-bestiary/kolyarut.json
  packs/pathfinder-monster-core/balisse.json
  packs/pathfinder-monster-core/pugwampi.json
  packs/rage-of-elements-bestiary/faydhaan-shuyookh.json
  packs/strength-of-thousands-bestiary/pugwampi-sot.json
Labels: pr: data update

#15428 Change styling of stowed strikes toggle
  src/styles/actor/_index.scss
  static/lang/en.json
  static/templates/actors/character/tabs/actions.hbs
Labels: ui/ux

#15436 Include point sources in `testCollision` calls lacking them
  src/module/canvas/measured-template.ts
  src/module/canvas/token/aura/util.ts
  types/foundry/client/data/documents/client-document.d.ts
Labels: pr: enhancement

#15442 Shrink down token footprint calculation
  src/module/canvas/helpers.ts
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
  types/foundry/client/pixi/placeable.d.ts
  types/foundry/client/pixi/placeables/template.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
Labels: pr: enhancement

#15443 Allow GMs to move tokens through walls when drag-measuring
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
  src/module/system/settings/index.ts
Labels: pr: bugfix

#15445 Favor `R.isPlainObject` in `DamageRoll`
  src/module/system/damage/roll.ts
Labels: pr: refactor

#15446 Remove `ItemDirectoryPF2e#_render`
  src/module/apps/sidebar/item-directory.ts
Labels: pr: refactor

#15448 Set `RulerPF2e##snap` sufficiently early in `#startDragMeasurement`
  src/module/canvas/ruler.ts
Labels: pr: bugfix

#15447 Ensure type match for override-mode AE-likes
  src/module/rules/rule-element/ae-like.ts
Labels: pr: enhancement

#15444 Fix outputting of `IntermediateDie` expressions
  src/module/system/damage/terms.ts
Labels: pr: bugfix

#15453 Restore spacebar to move when using ruler tool with drag measurement disabled
  src/module/canvas/ruler.ts
Labels: pr: bugfix

#15434 update instances of `/r` for `@Damage` for en.json
  static/lang/en.json
Labels: pr: data update

#15438 Add resistance to demon attacks to Pickled Demon Tongue effects
  packs/equipment-effects/effect-pickled-demon-tongue-armor-greater.json
  packs/equipment-effects/effect-pickled-demon-tongue-armor-major.json
  packs/equipment-effects/effect-pickled-demon-tongue-armor.json
  packs/equipment-effects/effect-pickled-demon-tongue-weapon-greater.json
  packs/equipment-effects/effect-pickled-demon-tongue-weapon-major.json
  packs/equipment-effects/effect-pickled-demon-tongue-weapon.json
  static/lang/re-en.json
Labels: pr: data update

#15451 Fix Note visibility for Shanrigol's Shred Flesh
  packs/abomination-vaults-bestiary/shanrigol-behemoth.json
  packs/abomination-vaults-bestiary/shanrigol-heap.json
  packs/pfs-season-3-bestiary/shanrigol-mound.json
Labels: pr: data update

#15435 update instances of `/r` for `@Damage` for re-en.json
  static/lang/re-en.json
Labels: pr: data update

#15455 localize remaining Elementalist Class Archtype spellshape feats
  packs/feats/burning-spell.json
  packs/feats/dousing-spell.json
  packs/feats/growth-spell.json
  packs/feats/reverberating-spell.json
  packs/feats/rockslide-spell.json
  packs/feats/wind-tossed-spell.json
  static/lang/re-en.json
Labels: pr: data update

#15459 Add automation to Firearms Expert
  packs/feats/firearm-expert.json
Labels: pr: data update

#15461 Add type definition for `ItemSheetV2`
  types/foundry/client-esm/applications/sheets/item-sheet.d.ts
  types/foundry/client-esm/applications/sheets/module.d.ts
Labels: pr: types update

#15456 Fix regression with updating lore skills if name collision avoidance occured
  src/module/actor/character/document.ts
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#15431 Update Raise Symbol to handle unified Emblazon Armament
  packs/feat-effects/effect-raise-symbol.json
  packs/feats/raise-symbol.json
Labels: pr: data update

#15465 Add automation for Hamatula's Impaling Barb
  packs/pathfinder-bestiary-2/hamatula.json
Labels: pr: data update

#15378 Add implement choiceset rules to Intense Implement feat
  packs/feats/intense-implement.json
Labels: pr: data update

#15418 Add Eye Gems spellcasting entry for Demilich
  packs/pathfinder-bestiary/demilich.json
Labels: pr: data update

#15467 Fix regression in damage `DiceTerm` classification
  src/module/system/damage/roll.ts
Labels: pr: bugfix

#15468 Add type definitions for `TextureTransitionFilter` and its usage
  types/foundry/client/data/documents/token-document.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/client/pixi/webgl/base.d.ts
  types/foundry/client/pixi/webgl/shaders/filters/index.d.ts
  types/foundry/client/pixi/webgl/shaders/filters/transition.d.ts
  types/foundry/client/pixi/webgl/shaders/index.d.ts
Labels: pr: types update

#15470 Separate procedures for ruler highlighting hex and non-hex grids
  src/module/canvas/ruler.ts
Labels: pr: bugfix

#15469 Add animation options to `TokenImageRuleElement`
  src/module/canvas/token/object.ts
  src/module/rules/rule-element/token-image.ts
  src/module/rules/synthetics.ts
  src/module/scene/token-document/document.ts
Labels: pr: enhancement

#15471 Fix bleed damage typo in re-en.json
  static/lang/re-en.json
Labels: pr: data update

#15475 Keep last-used animation for tokens for later use
  src/module/scene/token-document/document.ts
  types/foundry/client/pixi/core/interaction/canvas-animation.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/client/pixi/webgl/shaders/filters/transition.d.ts
Labels: pr: enhancement

#15477 Fix regression with character strike name not wrapping
  src/styles/actor/character/_actions.scss
  src/styles/actor/tabs/_actions.scss
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/actors/character/partials/strike.hbs
Labels: pr: bugfix, ui/ux

#15481 undo breaking changes in en.json
  static/lang/en.json
Labels: pr: data update

#15483 Fix unicode word boundaries in `sluggify`
  src/util/misc.ts
Labels: pr: bugfix

#15490 Remove usage of `R.filter`
  src/module/system/damage/weapon.ts
Labels: pr: refactor

#15488 Remove redundant construction of enriched content patterns
  src/scripts/hooks/init.ts
Labels: pr: bugfix

#15491 Loosen `typeof` equality check for override AE-likes
  src/module/rules/rule-element/ae-like.ts
Labels: pr: bugfix

#15489 Fix predicate and value of RE on Effect: Emblazon Energy
  packs/feat-effects/effect-emblazon-energy.json
Labels: pr: data update

#15415 Fix abilities on The Librarian and variant
  packs/pfs-season-5-bestiary/the-inscrutable-librarian.json
  packs/pfs-season-5-bestiary/the-librarian.json
Labels: pr: data update

#15473 Add mergeable to Debilitating Strike
  packs/classfeatures/debilitating-strike.json
  packs/classfeatures/double-debilitation.json
Labels: pr: data update

#15460 Brush up deity Minor Curses
  packs/boons-and-curses/abadar-minor-curse.json
  packs/boons-and-curses/alseta-minor-curse.json
  packs/boons-and-curses/arazni-minor-curse.json
  packs/boons-and-curses/asmodeus-minor-curse.json
  packs/boons-and-curses/besmara-minor-curse.json
  packs/boons-and-curses/brigh-minor-curse.json
  packs/boons-and-curses/calistria-minor-curse.json
  packs/boons-and-curses/casandalee-minor-curse.json
  packs/boons-and-curses/cayden-cailean-minor-curse.json
  packs/boons-and-curses/chaldira-minor-curse.json
  packs/boons-and-curses/desna-minor-curse.json
  packs/boons-and-curses/erastil-minor-curse.json
  packs/boons-and-curses/ghlaunder-minor-curse.json
  packs/boons-and-curses/gorum-minor-curse.json
  packs/boons-and-curses/gozreh-minor-curse.json
  packs/boons-and-curses/grandmother-spider-minor-curse.json
  packs/boons-and-curses/groetus-minor-curse.json
  packs/boons-and-curses/gruhastha-minor-curse.json
  packs/boons-and-curses/hei-feng-minor-curse.json
  packs/boons-and-curses/iomedae-minor-curse.json
  packs/boons-and-curses/iomedae-moderate-curse.json
  packs/boons-and-curses/kazutal-minor-curse.json
  packs/boons-and-curses/kurgess-minor-curse.json
  packs/boons-and-curses/lamashtu-minor-curse.json
  packs/boons-and-curses/milani-minor-curse.json
  packs/boons-and-curses/nethys-minor-curse.json
  packs/boons-and-curses/nivi-rhombodazzle-minor-curse.json
  packs/boons-and-curses/nocticula-minor-curse.json
  packs/boons-and-curses/norgorber-minor-curse.json
  packs/boons-and-curses/pharasma-minor-curse.json
  packs/boons-and-curses/rovagug-minor-curse.json
  packs/boons-and-curses/sarenrae-minor-curse.json
  packs/boons-and-curses/shelyn-minor-curse.json
  packs/boons-and-curses/shizuru-minor-curse.json
  packs/boons-and-curses/sivanah-minor-curse.json
  packs/boons-and-curses/torag-minor-curse.json
  packs/boons-and-curses/tsukiyo-minor-curse.json
  packs/boons-and-curses/urgathoa-minor-curse.json
  packs/boons-and-curses/zon-kuthon-minor-curse.json
  static/lang/re-en.json
Labels: pr: data update

#15452 Add action to Resonant Reflection Campaign items.
  packs/actions/activate-resonant-reflection.json
  packs/campaign-effects/resonant-reflection-reflection-of-life.json
  packs/campaign-effects/resonant-reflection-reflection-of-light.json
  packs/campaign-effects/resonant-reflection-reflection-of-stone.json
  packs/campaign-effects/resonant-reflection-reflection-of-storm.json
  packs/campaign-effects/resonant-reflection-reflection-of-water.json
  static/lang/re-en.json
Labels: pr: data update

#15480 Brush up deity Major Curses
  packs/boons-and-curses/abadar-major-curse.json
  packs/boons-and-curses/alseta-major-curse.json
  packs/boons-and-curses/arazni-major-curse.json
  packs/boons-and-curses/asmodeus-major-curse.json
  packs/boons-and-curses/besmara-major-curse.json
  packs/boons-and-curses/brigh-major-curse.json
  packs/boons-and-curses/calistria-major-curse.json
  packs/boons-and-curses/casandalee-major-curse.json
  packs/boons-and-curses/cayden-cailean-major-curse.json
  packs/boons-and-curses/chaldira-major-curse.json
  packs/boons-and-curses/desna-major-curse.json
  packs/boons-and-curses/erastil-major-curse.json
  packs/boons-and-curses/ghlaunder-major-curse.json
  packs/boons-and-curses/gorum-major-curse.json
  packs/boons-and-curses/gozreh-major-curse.json
  packs/boons-and-curses/grandmother-spider-major-curse.json
  packs/boons-and-curses/groetus-major-curse.json
  packs/boons-and-curses/gruhastha-major-curse.json
  packs/boons-and-curses/hei-feng-major-curse.json
  packs/boons-and-curses/iomedae-major-curse.json
  packs/boons-and-curses/kazutal-major-curse.json
  packs/boons-and-curses/kurgess-major-curse.json
  packs/boons-and-curses/lamashtu-major-curse.json
  packs/boons-and-curses/milani-major-curse.json
  packs/boons-and-curses/nethys-major-curse.json
  packs/boons-and-curses/nivi-rhombodazzle-major-curse.json
  packs/boons-and-curses/nocticula-major-curse.json
  packs/boons-and-curses/norgorber-major-curse.json
  packs/boons-and-curses/pharasma-major-curse.json
  packs/boons-and-curses/rovagug-major-curse.json
  packs/boons-and-curses/sarenrae-major-curse.json
  packs/boons-and-curses/shelyn-major-curse.json
  packs/boons-and-curses/shizuru-major-curse.json
  packs/boons-and-curses/sivanah-major-curse.json
  packs/boons-and-curses/torag-major-curse.json
  packs/boons-and-curses/tsukiyo-major-curse.json
  packs/boons-and-curses/urgathoa-major-curse.json
  packs/boons-and-curses/zon-kuthon-major-curse.json
  static/lang/re-en.json
Labels: pr: data update

#15493 Miscellaneous fixes
  packs/curtain-call-bestiary/honor-guard.json
  packs/equipment/crooners-cravat.json
Labels: pr: data update

#15492 Brush up deity Moderate Boons
  packs/boons-and-curses/abadar-moderate-boon.json
  packs/boons-and-curses/alseta-moderate-boon.json
  packs/boons-and-curses/arazni-moderate-boon.json
  packs/boons-and-curses/asmodeus-moderate-boon.json
  packs/boons-and-curses/besmara-moderate-boon.json
  packs/boons-and-curses/brigh-moderate-boon.json
  packs/boons-and-curses/calistria-moderate-boon.json
  packs/boons-and-curses/casandalee-moderate-boon.json
  packs/boons-and-curses/cayden-cailean-moderate-boon.json
  packs/boons-and-curses/chaldira-moderate-boon.json
  packs/boons-and-curses/desna-moderate-boon.json
  packs/boons-and-curses/erastil-moderate-boon.json
  packs/boons-and-curses/ghlaunder-moderate-boon.json
  packs/boons-and-curses/gorum-moderate-boon.json
  packs/boons-and-curses/gozreh-moderate-boon.json
  packs/boons-and-curses/grandmother-spider-moderate-boon.json
  packs/boons-and-curses/groetus-moderate-boon.json
  packs/boons-and-curses/gruhastha-moderate-boon.json
  packs/boons-and-curses/hei-feng-moderate-boon.json
  packs/boons-and-curses/iomedae-moderate-boon.json
  packs/boons-and-curses/kazutal-moderate-boon.json
  packs/boons-and-curses/kurgess-moderate-boon.json
  packs/boons-and-curses/lamashtu-moderate-boon.json
  packs/boons-and-curses/milani-moderate-boon.json
  packs/boons-and-curses/nethys-moderate-boon.json
  packs/boons-and-curses/nivi-rhombodazzle-moderate-boon.json
  packs/boons-and-curses/nocticula-moderate-boon.json
  packs/boons-and-curses/norgorber-moderate-boon.json
  packs/boons-and-curses/pharasma-moderate-boon.json
  packs/boons-and-curses/rovagug-moderate-boon.json
  packs/boons-and-curses/sarenrae-moderate-boon.json
  packs/boons-and-curses/shelyn-moderate-boon.json
  packs/boons-and-curses/shizuru-moderate-boon.json
  packs/boons-and-curses/sivanah-moderate-boon.json
  packs/boons-and-curses/torag-moderate-boon.json
  packs/boons-and-curses/tsukiyo-moderate-boon.json
  packs/boons-and-curses/urgathoa-moderate-boon.json
  packs/boons-and-curses/zon-kuthon-moderate-boon.json
Labels: pr: data update

#15494 Fix regression in bactrian/dromedary sluggification
  src/util/misc.ts
Labels: pr: bugfix

#15495 Run extractPacks all
  packs/actions/activate-resonant-reflection.json
  packs/boons-and-curses/iomedae-major-curse.json
  packs/campaign-effects/resonant-reflection-reflection-of-stone.json
  packs/classfeatures/debilitating-strike.json
  packs/classfeatures/double-debilitation.json
Labels: pr: data update

#15497 Conditionally show Show/Hide Stowed on PC sheet Actions panel
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  static/templates/actors/character/tabs/actions.hbs
Labels: ui/ux

#15500 add `Merfolk` trait to Kraken's Call feat.
  packs/feats/krakens-call.json
Labels: pr: data update

#14499 Allow ItemAlteration Hardness to use non-integer alteration values
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
Labels: pr: enhancement, pr: delay merge

#15502 Update Gorum's Minor Curse to alter armor and shield hardness
  packs/boons-and-curses/gorum-minor-curse.json
Labels: pr: data update

#15498 Release Notes 6.1.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#15509 Fix missing space character in Administer First Aid action description
  static/lang/action-en.json
Labels: pr: data update

#15510 Fix drawing of highlights from other users' drag measurements
  src/module/canvas/ruler.ts
Labels: pr: bugfix

#15508 correct typo in Spit Ambient Magic damage formula.
  packs/actions/spit-ambient-magic.json
Labels: pr: data update

#15511 Fix tiny tokens not traversing waypoints during drag measurement
  src/module/canvas/ruler.ts
Labels: pr: bugfix

#15514 Adjust drag measurement feature to play nice(r) with modules
  src/module/canvas/ruler.ts
  src/module/canvas/token/object.ts
  src/module/system/settings/index.ts
  src/scripts/hooks/init.ts
  src/scripts/hooks/load.ts
  src/scripts/register-keybindings.ts
Labels: pr: enhancement
