Repository foundryvtt/pf2e, pull requests merged in 2024-10, with the labels that each got.

#16724 Fix regression with editing the first rule element
  src/module/item/base/sheet/sheet.ts
Labels: pr: bugfix

#16725 Refresh GM Screen and update journal entries
  packs/journals/gm-screen.json
Labels: pr: data update

#16723 Correct spelling on Virtuous Tanuki heritage
  packs/heritages/tanuki/virtuous-tanuki.json
  packs/journals/ancestries.json
Labels: pr: data update

#16721 Redirect additional Pathfinder Bestiary actors to their Monster Core equivalents
  build/uuid-redirects.json
Labels: pr: data update

#16726 Merge crafting abilities partial into crafting tab
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/sheet.ts
  src/scripts/register-templates.ts
  static/templates/actors/character/tabs/crafting.hbs
  static/templates/actors/crafting-entry-list.hbs
Labels: pr: refactor

#16729 Add `Volley 60 feet` to traits and localization.
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update, sf2e playtest

#16727 Split Weapon Siphon effects
  packs/equipment-effects/effect-weapon-siphon-bomb-fitted.json
  packs/equipment-effects/effect-weapon-siphon.json
  packs/equipment/weapon-siphon.json
Labels: pr: data update

#16728 Redirect even more Pathfinder Bestiary actors to their Monster Core equivalents
  build/uuid-redirects.json
Labels: pr: data update

#16734 Brush up some RoE immunities and weaknesses
  packs/rage-of-elements-bestiary/elemental-thicket.json
  packs/rage-of-elements-bestiary/kizidhar-shuyookh.json
  packs/rage-of-elements-bestiary/kizidhar.json
  packs/rage-of-elements-bestiary/painted-stag.json
Labels: pr: data update

#16735 Add effect for Blessed Swiftness' defense bonuses to allies
  packs/classfeatures/blessed-swiftness.json
  packs/classfeatures/champions-aura.json
  packs/feat-effects/effect-aura-of-despair.json
  packs/feat-effects/effect-blessed-swiftness.json
  packs/feats/divine-health.json
  static/lang/re-en.json
Labels: pr: data update

#16738 Automate Backfire Mantle bonus to saves
  packs/equipment/backfire-mantle-greater.json
  packs/equipment/backfire-mantle.json
Labels: pr: data update

#16733 Fix inline checks for Paradox Engine
  packs/shadows-at-sundown-bestiary/paradox-engine.json
Labels: pr: data update

#16744 Add effect for Pentagonal Seventh Prism
  packs/equipment-effects/effect-seventh-prism-pentagonal.json
  packs/equipment/seventh-prism-pentagonal.json
  packs/equipment/seventh-prism-triangular.json
Labels: pr: data update

#16742 Fix level for wand of purification (5th rank spell)
  packs/equipment/wand-of-purification-5th-rank-spell.json
Labels: pr: data update

#16741 Fix some mismatched parentheses
  packs/pathfinder-bestiary-2/spriggan-bully.json
  packs/pathfinder-bestiary-3/mithral-golem.json
Labels: pr: data update

#16748 Rename `ActionTrait` type to `AbilityTrait`
  src/module/actor/actions/base.ts
  src/module/actor/actions/types.ts
  src/module/actor/army/values.ts
  src/module/actor/character/document.ts
  src/module/actor/character/elemental-blast.ts
  src/module/actor/helpers.ts
  src/module/actor/roll-context/base.ts
  src/module/actor/roll-context/types.ts
  src/module/actor/sheet/base.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/item/ability/data.ts
  src/module/item/ability/document.ts
  src/module/item/ability/types.ts
  src/module/item/base/types.ts
  src/module/item/physical/data.ts
  src/module/item/physical/runes.ts
  src/module/migration/migrations/828-prune-invalid-traits.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/synthetics.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/rolls.ts
  src/module/system/statistic/statistic.ts
  src/module/system/text-editor.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: types update

#15824 Add Send to Party in loot sheet
  src/module/actor/helpers.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/sheet/popups/loot-npcs-popup.ts
  static/lang/en.json
  static/templates/actors/loot/sidebar.hbs
Labels: pr: enhancement

#16720 Fix ChoiceSet on Aldori Duelist Dedication
  packs/feats/aldori-duelist-dedication.json
Labels: pr: data update

#16740 Conserve compendium source for embedded items when extracting
  build/lib/compendium-pack.ts
  build/lib/extractor.ts
Labels: pr: bugfix, pr: housekeeping

#16749 Convert ability system data to `TypeDataModel`
  src/module/item/ability/data.ts
  src/module/item/ability/document.ts
  src/module/item/ability/helpers.ts
  src/module/item/ability/sheet.ts
  src/scripts/hooks/load.ts
  static/template.json
Labels: pr: refactor

#16752 Add `Traits` journal entry to GM screen
  packs/journals/gm-screen.json
Labels: pr: data update

#16751 Update Effect: Silvertongue Mutagen
  packs/equipment-effects/effect-silvertongue-mutagen-greater.json
  packs/equipment-effects/effect-silvertongue-mutagen-lesser.json
  packs/equipment-effects/effect-silvertongue-mutagen-major.json
  packs/equipment-effects/effect-silvertongue-mutagen-moderate.json
Labels: pr: data update

#16747 Fix description for kindling familiar ability
  packs/familiar-abilities/kindling.json
Labels: pr: data update

#16743 Also set defaults for sub items when running migration script
  build/run-migration.ts
  packs/spells/leaden-steps.json
  packs/spells/weapon-trance.json
Labels: pr: bugfix, pr: housekeeping

#16756 Utilize more of `TypeDataModel` with ability items
  src/module/chat-message/listeners/cards.ts
  src/module/item/ability/data.ts
  src/module/item/ability/document.ts
  src/module/item/ability/sheet.ts
  src/module/item/base/data/schema.ts
  src/module/item/base/sheet/sheet.ts
  src/scripts/config/index.ts
  src/util/misc.ts
  static/lang/en.json
  static/templates/actors/party/regions/exploration.hbs
  static/templates/compendium-browser/compendium-browser.hbs
  static/templates/items/action-details.hbs
  static/templates/items/action-sidebar.hbs
  static/templates/items/partials/ability-activation.hbs
  static/templates/items/partials/self-applied-effect.hbs
  types/foundry/common/abstract/type-data.d.ts
Labels: pr: refactor

#16755 Fix some extract and migrate regressions and delaraius's wand
  build/lib/compendium-pack.ts
  build/run-migration.ts
  packs/curtain-call-bestiary/delaraius-solzakarr.json
Labels: pr: bugfix, pr: data update

#16754 Localize traits journal and add player screen page
  packs/journals/gm-screen.json
Labels: pr: data update

#16762 Add automation for PFS1 Skeletal Mage's Widen Spell
  packs/pfs-season-1-bestiary/skeletal-mage.json
Labels: pr: data update

#16761 Fix prerequisites for Vernai Training
  packs/feats/vernai-training.json
Labels: pr: data update

#16760 Brush up Masquerade Scarf
  packs/equipment/masquerade-scarf-greater.json
  packs/equipment/masquerade-scarf.json
Labels: pr: data update

#16764 Update Elixir of Life descriptions
  packs/equipment/elixir-of-life-lesser.json
  packs/equipment/elixir-of-life-major.json
  packs/equipment/elixir-of-life-minor.json
  packs/equipment/elixir-of-life-moderate.json
  packs/equipment/elixir-of-life-true.json
Labels: pr: data update

#16766 Fix html in description of pot of tea
  packs/familiar-abilities/specific-familiary-abilities/pot-of-tea.json
Labels: pr: data update

#16772 Add choice of skill and clean up Pocket Library spell effect
  packs/spell-effects/spell-effect-pocket-library.json
  packs/spells/pocket-library.json
Labels: pr: data update

#16770 Remove select Pathfinder Bestiary (1 and 2) actors
  packs/equipment/serpent-oil-moderate.json
  packs/equipment/wondrous-figurine-candy-constrictor.json
  packs/feats/call-the-worm.json
  packs/journals/archetypes.json
  packs/pathfinder-bestiary-2/grindylow.json
  packs/pathfinder-bestiary/astral-deva.json
  packs/pathfinder-bestiary/azure-worm.json
  packs/pathfinder-bestiary/ball-python.json
  packs/pathfinder-bestiary/brain-collector.json
  packs/pathfinder-bestiary/bugbear-thug.json
  packs/pathfinder-bestiary/caligni-creeper.json
  packs/pathfinder-bestiary/crimson-worm.json
  packs/pathfinder-bestiary/deep-gnome-rockwarden.json
  packs/pathfinder-bestiary/deep-gnome-scout.json
  packs/pathfinder-bestiary/deep-gnome-warrior.json
  packs/pathfinder-bestiary/duergar-bombardier.json
  packs/pathfinder-bestiary/duergar-sharpshooter.json
  packs/pathfinder-bestiary/duergar-taskmaster.json
  packs/pathfinder-bestiary/faceless-stalker.json
  packs/pathfinder-bestiary/faerie-dragon.json
  packs/pathfinder-bestiary/gnoll-cultist.json
  packs/pathfinder-bestiary/gnoll-hunter.json
  packs/pathfinder-bestiary/gnoll-sergeant.json
  packs/pathfinder-bestiary/invisible-stalker.json
  packs/pathfinder-bestiary/lemure.json
  packs/pathfinder-bestiary/lillend.json
  packs/pathfinder-bestiary/minotaur.json
  packs/pathfinder-bestiary/nessian-warhound.json
  packs/pathfinder-bestiary/orc-warchief.json
  packs/pathfinder-bestiary/orc-warrior.json
  packs/pathfinder-bestiary/pit-fiend.json
  packs/pathfinder-bestiary/purple-worm.json
  packs/pathfinder-bestiary/tiefling-adept.json
  packs/pathfinder-bestiary/vampire-spawn-rogue.json
  packs/pathfinder-bestiary/veiled-master.json
  packs/pathfinder-bestiary/winter-wolf.json
  packs/rollable-tables/hills-dangers.json
  packs/the-slithering-bestiary/stalker-summoning-rune.json
Labels: pr: data update

#16783 Restore blank option to ability category
  src/module/item/ability/document.ts
  static/templates/items/action-sidebar.hbs
Labels: pr: bugfix

#16789 Fix ItemAlteration removing the wrong trait if it does not exist
  src/module/rules/rule-element/item-alteration/alteration.ts
Labels: pr: bugfix

#16785 Brush up musical instruments
  packs/equipment-effects/effect-strum-of-thunder.json
  packs/equipment/arachnolute.json
  packs/equipment/arboreals-revenge.json
  packs/equipment/bagpipes-of-turmoil-greater.json
  packs/equipment/bagpipes-of-turmoil-major.json
  packs/equipment/bagpipes-of-turmoil.json
  packs/equipment/busine-of-divine-reinforcements.json
  packs/equipment/cauthooj-bagpipes.json
  packs/equipment/composer-staff-greater.json
  packs/equipment/composer-staff-major.json
  packs/equipment/composer-staff.json
  packs/equipment/conch-of-otherworldly-seas.json
  packs/equipment/drum-of-upheaval.json
  packs/equipment/drums-of-war-greater.json
  packs/equipment/drums-of-war-major.json
  packs/equipment/drums-of-war.json
  packs/equipment/entertainers-lute-greater.json
  packs/equipment/entertainers-lute-major.json
  packs/equipment/entertainers-lute.json
  packs/equipment/fiddle-of-the-maestro.json
  packs/equipment/folding-drums.json
  packs/equipment/guiding-cajon-drum.json
  packs/equipment/halcyon-heart.json
  packs/equipment/horn-of-blasting.json
  packs/equipment/horn-of-the-sun-aurochs.json
  packs/equipment/lacquered-waist-drum.json
  packs/equipment/maestros-instrument-greater.json
  packs/equipment/maestros-instrument-lesser.json
  packs/equipment/maestros-instrument-moderate.json
  packs/equipment/marvelous-calliope.json
  packs/equipment/memory-guitar.json
  packs/equipment/musical-instrument-virtuoso-handheld.json
  packs/equipment/musical-instrument-virtuoso-heavy.json
  packs/equipment/phantom-piano.json
  packs/equipment/pipes-of-compulsion-greater.json
  packs/equipment/pipes-of-compulsion-major.json
  packs/equipment/pipes-of-compulsion.json
  packs/equipment/resonant-guitar.json
  packs/equipment/seers-flute-greater.json
  packs/equipment/seers-flute-major.json
  packs/equipment/seers-flute.json
  packs/equipment/spirit-singer-handheld.json
  packs/equipment/spirit-singer-incredible-handheld.json
  packs/equipment/spirit-singer-incredible.json
  packs/equipment/spirit-singer.json
  packs/equipment/spurned-lute.json
  packs/equipment/tricksters-mandolin-greater.json
  packs/equipment/tricksters-mandolin-major.json
  packs/equipment/tricksters-mandolin.json
  packs/equipment/violin-of-the-waves.json
  static/lang/re-en.json
Labels: pr: data update

#16746 Add effects for Dazzling Rosary, Necrotic Cap and Wemmuth Trinket
  packs/equipment-effects/effect-dazzling-rosary.json
  packs/equipment-effects/effect-necrotic-cap.json
  packs/equipment-effects/effect-wemmuth-trinket.json
  packs/equipment/dazzling-rosary-greater.json
  packs/equipment/dazzling-rosary.json
  packs/equipment/necrotic-cap-greater.json
  packs/equipment/necrotic-cap-lesser.json
  packs/equipment/necrotic-cap-major.json
  packs/equipment/necrotic-cap-moderate.json
  packs/equipment/wemmuth-trinket.json
  static/lang/re-en.json
Labels: pr: data update

#16773 Add fly speed to Winged Owlbear
  packs/kingmaker-bestiary/winged-owlbear.json
Labels: pr: data update

#16775 Clean up Dust of Disappearance formatting
  packs/equipment/dust-of-disappearance.json
Labels: pr: data update

#16778 Fix silvanshee collar description to use Charisma modifier
  packs/equipment/silvanshee-collar.json
Labels: pr: data update

#16781 Update Radiant Mantle's emission angle
  packs/pathfinder-bestiary-3/gliminal.json
Labels: pr: data update

#16784 Add Ursine Avenger Hood to Archetype journal
  packs/journals/archetypes.json
Labels: pr: data update

#16777 Brush up Caligni assassin
  packs/sky-kings-tomb-bestiary/caligni-assassin.json
Labels: pr: data update

#16790 Fix drag/drop reordering of crafting formulas
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#16793 (Iconics) Move source UUIDs of embedded items to `_stats` object
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/iconics/daji-level-1.json
  packs/iconics/daji-level-3.json
  packs/iconics/daji-level-5.json
  packs/iconics/droogami-level-1.json
  packs/iconics/droogami-level-3.json
  packs/iconics/droogami-level-5.json
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/iconics/feiya-level-1.json
  packs/iconics/feiya-level-3.json
  packs/iconics/feiya-level-5.json
  packs/iconics/fumbus-level-1.json
  packs/iconics/fumbus-level-3.json
  packs/iconics/fumbus-level-5.json
  packs/iconics/harsk-level-1.json
  packs/iconics/harsk-level-3.json
  packs/iconics/harsk-level-5.json
  packs/iconics/jirelle-level-1.json
  packs/iconics/jirelle-level-3.json
  packs/iconics/jirelle-level-5.json
  packs/iconics/korakai-level-1.json
  packs/iconics/korakai-level-3.json
  packs/iconics/korakai-level-5.json
  packs/iconics/kyra-level-1.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/iconics/lem-level-1.json
  packs/iconics/lem-level-3.json
  packs/iconics/lem-level-5.json
  packs/iconics/lini-level-1.json
  packs/iconics/lini-level-3.json
  packs/iconics/lini-level-5.json
  packs/iconics/merisiel-level-1.json
  packs/iconics/merisiel-level-3.json
  packs/iconics/merisiel-level-5.json
  packs/iconics/quinn-level-1.json
  packs/iconics/quinn-level-3.json
  packs/iconics/quinn-level-5.json
  packs/iconics/sajan-level-1.json
  packs/iconics/sajan-level-3.json
  packs/iconics/sajan-level-5.json
  packs/iconics/seelah-level-1.json
  packs/iconics/seelah-level-3.json
  packs/iconics/seelah-level-5.json
  packs/iconics/seoni-level-1.json
  packs/iconics/seoni-level-3.json
  packs/iconics/seoni-level-5.json
  packs/iconics/valeros-level-1.json
  packs/iconics/valeros-level-3.json
  packs/iconics/valeros-level-5.json
  packs/iconics/yoon-level-1.json
  packs/iconics/yoon-level-3.json
  packs/iconics/yoon-level-5.json
Labels: pr: data update

#16791 Fix refreshing items embedded in compendium actors
  src/module/item/base/document.ts
Labels: pr: bugfix

#16794 Preserve `_stats.compendiumSource` in embedded items on build
  build/lib/compendium-pack.ts
Labels: pr: bugfix, pr: housekeeping

#16797 Add missing prerequisite to Spectral Advance
  packs/feats/spectral-advance.json
Labels: pr: data update

#16798 Update Apex item descriptions to use Remaster terms
  packs/equipment/avalanche-boots.json
  packs/equipment/belt-of-giant-strength.json
  packs/equipment/bracers-of-hammers.json
  packs/equipment/dragon-handwraps.json
  packs/equipment/sacred-valkyrie-helm.json
  packs/equipment/sandals-of-the-stag.json
  packs/equipment/titans-grasp.json
Labels: pr: data update

#16799 Refrain from broadcasting drag measurement of GM-hidden tokens
  src/module/canvas/ruler.ts
Labels: pr: enhancement

#16804 Include "system.usage" as index field for item-filter choice sets
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#16807 Condense River Drake tail lash effects
  build/uuid-redirects.json
  packs/bestiary-effects/effect-tail-lash-skill-check.json
  packs/bestiary-effects/effect-tail-lash.json
  packs/kingmaker-bestiary/ilthuliak.json
  packs/pathfinder-bestiary/black-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary/black-dragon-adult.json
  packs/pathfinder-bestiary/black-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/black-dragon-ancient.json
  packs/pathfinder-bestiary/black-dragon-young-spellcaster.json
  packs/pathfinder-bestiary/black-dragon-young.json
  packs/pathfinder-bestiary/river-drake.json
  packs/pathfinder-monster-core/river-drake.json
  packs/pfs-season-6-bestiary/demonic-ocean-drake.json
  packs/pfs-season-6-bestiary/demonic-river-drake.json
  packs/quest-for-the-frozen-flame-bestiary/venexuss-chosen.json
  packs/seven-dooms-for-sandpoint-bestiary/scarhorn.json
Labels: pr: data update

#16806 Remove select Pathfinder Bestiary Actors and update links
  packs/abomination-vaults-bestiary/dreshkan.json
  packs/agents-of-edgewatch-bestiary/summoning-rune-cinder-rat.json
  packs/equipment/wondrous-figurine-onyx-dog.json
  packs/paizo-pregens/bottlespeaker-level-4.json
  packs/paizo-pregens/bottlespeaker.json
  packs/pathfinder-bestiary/ankhrav.json
  packs/pathfinder-bestiary/balisse.json
  packs/pathfinder-bestiary/basilisk.json
  packs/pathfinder-bestiary/boggard-scout.json
  packs/pathfinder-bestiary/boggard-swampseer.json
  packs/pathfinder-bestiary/catfolk-pouncer.json
  packs/pathfinder-bestiary/cinder-rat.json
  packs/pathfinder-bestiary/cloud-giant.json
  packs/pathfinder-bestiary/crag-linnorm.json
  packs/pathfinder-bestiary/crocodile.json
  packs/pathfinder-bestiary/daeodon.json
  packs/pathfinder-bestiary/dhampir-wizard.json
  packs/pathfinder-bestiary/dire-wolf.json
  packs/pathfinder-bestiary/dragon-turtle.json
  packs/pathfinder-bestiary/dryad-queen.json
  packs/pathfinder-bestiary/dryad.json
  packs/pathfinder-bestiary/electric-eel.json
  packs/pathfinder-bestiary/elemental-tsunami.json
  packs/pathfinder-bestiary/flash-beetle.json
  packs/pathfinder-bestiary/frost-drake.json
  packs/pathfinder-bestiary/frost-giant.json
  packs/pathfinder-bestiary/fungus-leshy.json
  packs/pathfinder-bestiary/goblin-dog.json
  packs/pathfinder-bestiary/goblin-pyro.json
  packs/pathfinder-bestiary/goblin-war-chanter.json
  packs/pathfinder-bestiary/goblin-warrior.json
  packs/pathfinder-bestiary/gogiteth.json
  packs/pathfinder-bestiary/goliath-spider.json
  packs/pathfinder-bestiary/gorilla.json
  packs/pathfinder-bestiary/gourd-leshy.json
  packs/pathfinder-bestiary/graveknight.json
  packs/pathfinder-bestiary/great-cyclops.json
  packs/pathfinder-bestiary/great-white-shark.json
  packs/pathfinder-bestiary/greater-nightmare.json
  packs/pathfinder-bestiary/greater-shadow.json
  packs/pathfinder-bestiary/greedspawn.json
  packs/pathfinder-bestiary/griffon.json
  packs/pathfinder-bestiary/grikkitog.json
  packs/pathfinder-bestiary/grim-reaper.json
  packs/pathfinder-bestiary/grothlut.json
  packs/pathfinder-bestiary/guard-dog.json
  packs/pathfinder-bestiary/guthallath.json
  packs/pathfinder-bestiary/harpy.json
  packs/rollable-tables/forest-dangers.json
  packs/rollable-tables/hills-dangers.json
  packs/rollable-tables/plains-dangers.json
  packs/spells/gray-shadow.json
  packs/strength-of-thousands-bestiary/spider-summoning-rune.json
Labels: pr: data update

#16803 Refresh copies of musical instruments
  packs/abomination-vaults-bestiary/kragala.json
  packs/abomination-vaults-bestiary/nox.json
  packs/blood-lords-bestiary/harmony-in-agony.json
  packs/curtain-call-bestiary/fallenta.json
  packs/equipment/cloud-pouch.json
  packs/equipment/sentinel-horn.json
  packs/fists-of-the-ruby-phoenix-bestiary/laruhao.json
  packs/fists-of-the-ruby-phoenix-bestiary/razu.json
  packs/iconics/lem-level-5.json
  packs/kingmaker-bestiary/annamede-belavarah.json
  packs/kingmaker-bestiary/linzi-level-7.json
  packs/pathfinder-bestiary-2/trumpet-archon.json
  packs/pathfinder-monster-core/kanya.json
  packs/pfs-season-3-bestiary/thomil-bolyrius-3-4.json
  packs/pfs-season-3-bestiary/thomil-bolyrius-5-6.json
  packs/rollable-tables/6th-level-permanent-items.json
  packs/seven-dooms-for-sandpoint-bestiary/arika-avertin.json
  packs/stolen-fate-bestiary/drustan.json
  packs/strength-of-thousands-bestiary/iobane-magus.json
  packs/strength-of-thousands-bestiary/mpondo.json
  packs/the-enmity-cycle-bestiary/zridi.json
Labels: pr: data update

#16802 Add SVG icon for Tanuki ancestry
  packs/ancestries/tanuki.json
  static/icons/default-icons/alternatives/ancestries/tanuki.svg
Labels: pr: data update

#16801 Tidy description of Healer's Gloves
  packs/equipment/healers-gloves-greater.json
  packs/equipment/healers-gloves.json
Labels: pr: data update

#16800 Add effect for Stag's Helm
  packs/equipment-effects/effect-stags-helm.json
  packs/equipment/stags-helm.json
  packs/kingmaker-bestiary/the-stag-lord.json
Labels: pr: data update

#16792 Brush up several Equipment effects
  packs/equipment-effects/aura-demons-knot.json
  packs/equipment-effects/aura-elysian-dew.json
  packs/equipment-effects/effect-ablative-armor-plating-greater.json
  packs/equipment-effects/effect-ablative-armor-plating-lesser.json
  packs/equipment-effects/effect-ablative-armor-plating-major.json
  packs/equipment-effects/effect-ablative-armor-plating-moderate.json
  packs/equipment-effects/effect-ablative-armor-plating-true.json
  packs/equipment-effects/effect-aeon-stone-black-pearl.json
  packs/equipment-effects/effect-aeon-stone-resonance-amplifying.json
  packs/equipment-effects/effect-aeon-stone-resonance-black-disc.json
  packs/equipment-effects/effect-aeon-stone-resonance-pearly-white-spindle.json
  packs/equipment-effects/effect-amphisbaena-spittle.json
  packs/equipment-effects/effect-ancestral-geometry-save-type.json
  packs/equipment-effects/effect-antidote-greater.json
  packs/equipment-effects/effect-antidote-lesser.json
  packs/equipment-effects/effect-antidote-major.json
  packs/equipment-effects/effect-antidote-moderate.json
  packs/equipment-effects/effect-antiplague-greater.json
  packs/equipment-effects/effect-antiplague-lesser.json
  packs/equipment-effects/effect-antiplague-major.json
  packs/equipment-effects/effect-antiplague-moderate.json
  packs/equipment-effects/effect-applereed-mutagen-greater.json
  packs/equipment-effects/effect-applereed-mutagen-lesser.json
  packs/equipment-effects/effect-applereed-mutagen-moderate.json
  packs/equipment-effects/effect-apricot-of-bestial-might.json
  packs/equipment-effects/effect-arboreals-revenge-speed-penalty.json
  packs/equipment-effects/effect-architects-pattern-book.json
  packs/equipment-effects/effect-aromatic-ammunition.json
  packs/equipment-effects/effect-ascendant-dragon-spirit.json
  packs/equipment-effects/effect-auric-noodles.json
  packs/equipment-effects/effect-demons-knot.json
  packs/equipment/amphisbaena-spittle.json
Labels: pr: data update

#16780 Update instances of inline damage to the newer format
  packs/curtain-call-bestiary/emriss.json
  packs/howl-of-the-wild-bestiary/virtuosic-lyrebird.json
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/iconics/feiya-level-1.json
  packs/iconics/feiya-level-3.json
  packs/iconics/feiya-level-5.json
  packs/iconics/fumbus-level-1.json
  packs/iconics/fumbus-level-3.json
  packs/iconics/fumbus-level-5.json
  packs/iconics/harsk-level-3.json
  packs/iconics/harsk-level-5.json
  packs/iconics/korakai-level-1.json
  packs/iconics/korakai-level-3.json
  packs/iconics/korakai-level-5.json
  packs/iconics/kyra-level-1.json
  packs/iconics/lem-level-3.json
  packs/iconics/lini-level-1.json
  packs/iconics/lini-level-3.json
  packs/iconics/lini-level-5.json
  packs/iconics/merisiel-level-3.json
  packs/iconics/merisiel-level-5.json
  packs/iconics/sajan-level-1.json
  packs/iconics/sajan-level-3.json
  packs/iconics/sajan-level-5.json
  packs/iconics/seelah-level-1.json
  packs/iconics/seelah-level-3.json
  packs/iconics/seelah-level-5.json
  packs/iconics/seoni-level-5.json
  packs/iconics/valeros-level-1.json
  packs/iconics/valeros-level-3.json
  packs/iconics/valeros-level-5.json
  packs/iconics/yoon-level-1.json
  packs/pathfinder-monster-core/brimorak.json
  packs/pathfinder-monster-core/changeling-exile.json
  packs/pathfinder-monster-core/diabolic-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/diabolic-dragon-adult.json
  packs/pathfinder-monster-core/diabolic-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/diabolic-dragon-ancient.json
  packs/pathfinder-monster-core/diabolic-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/diabolic-dragon-young.json
  packs/pathfinder-monster-core/fire-scamp.json
  packs/pathfinder-monster-core/goblin-pyro.json
  packs/pathfinder-monster-core/ifrit.json
  packs/pathfinder-monster-core/lizardfolk-stargazer.json
  packs/pathfinder-monster-core/umbral-gnome-rockwarden.json
  packs/prey-for-death-bestiary/rhysaphine.json
  packs/rage-of-elements-bestiary/gennayn.json
  packs/rage-of-elements-bestiary/ifrit-shuyookh.json
Labels: pr: data update

#16805 Clean up Campaign Effects compendium and brush up hope or despair effect.
  build/uuid-redirects.json
  packs/adventure-specific-actions/_folders.json
  packs/bestiary-effects/effect-manipulate-luck-drusilla-good.json
  packs/blood-lords-bestiary/drusilla.json
  packs/campaign-effects/extinction-curse/resonant-reflection-reflection-of-life.json
  packs/campaign-effects/extinction-curse/resonant-reflection-reflection-of-light.json
  packs/campaign-effects/extinction-curse/resonant-reflection-reflection-of-stone.json
  packs/campaign-effects/extinction-curse/resonant-reflection-reflection-of-storm.json
  packs/campaign-effects/extinction-curse/resonant-reflection-reflection-of-water.json
Labels: pr: data update

#16808 Sort UUID redirects
  build/uuid-redirects.json
Labels: pr: data update

#16810 Internally rename crafting ability selector to slug and name to label
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/crafting/crafting.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/rules/rule-element/crafting-entry.ts
  static/templates/actors/character/tabs/crafting.hbs
Labels: pr: refactor

#16811 Turn on `@typescript-eslint/no-unused-vars`
  build/lib/level-database.ts
  eslint.config.js
  src/module/actor/actions/types.ts
  src/module/item/consumable/spell-consumables.ts
  tests/module/migration.test.ts
  types/foundry/client/core/image.d.ts
  types/foundry/client/data/documents/combatant.d.ts
  types/foundry/common/documents/combatant.d.ts
Labels: pr: housekeeping

#16820 Fix Revel in Retribution's spell effects name
  packs/spell-effects/spell-effect-revel-in-retribution-temp-hp.json
  packs/spell-effects/spell-effect-revel-in-retribution.json
  packs/spells/revel-in-retribution.json
  static/lang/re-en.json
Labels: pr: data update

#16824 Add Gelid Shard archetype to Archetype journal
  packs/journals/archetypes.json
Labels: pr: data update

#16765 Fix possible aura sizes for Bless aura effect
  packs/spell-effects/aura-bless.json
  packs/spell-effects/spell-effect-bless.json
Labels: pr: data update

#16822 Identify the correct statistic when using a pre-existing roll for initiative
  src/module/actor/initiative.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/encounter/document.ts
Labels: pr: bugfix

#16814 Update text in Spinebreaker and Submission Hold feats to match PC2
  packs/feats/spinebreaker.json
  packs/feats/submission-hold.json
Labels: pr: data update

#16818 Correct Animal Instinct's Tyrannosaurus Tail damage type
  packs/classfeatures/animal-instinct.json
Labels: pr: data update

#16830 Add Divine Access class feature to Oracle journal entry
  packs/journals/classes.json
Labels: pr: data update

#16831 Condense effects for Treat Disease and Treat Poison
  build/uuid-redirects.json
  packs/actions/skill-actions/treat-disease.json
  packs/actions/skill-actions/treat-poison.json
  packs/equipment-effects/effect-treat-disease-critical-failure.json
  packs/equipment-effects/effect-treat-disease-critical-success.json
  packs/equipment-effects/effect-treat-disease-success.json
  packs/equipment-effects/effect-treat-poison-critical-failure.json
  packs/equipment-effects/effect-treat-poison-critical-success.json
  packs/equipment-effects/effect-treat-poison-success.json
  packs/other-effects/effect-treat-disease.json
  packs/other-effects/effect-treat-poison.json
  static/lang/action-en.json
Labels: pr: data update

#16812 Condense Healer's Gel effect
  build/uuid-redirects.json
  packs/equipment-effects/effect-greater-healers-gel.json
  packs/equipment-effects/effect-healers-gel.json
  packs/equipment-effects/effect-lesser-healers-gel.json
  packs/equipment-effects/effect-moderate-healers-gel.json
  packs/equipment/healers-gel-greater.json
  packs/equipment/healers-gel-lesser.json
  packs/equipment/healers-gel-moderate.json
  static/lang/re-en.json
Labels: pr: data update

#16833 Add content from Triumph of the Tusk Player's Guide
  packs/backgrounds/badlands-scout.json
  packs/backgrounds/belkzen-anthropologist.json
  packs/backgrounds/empty-hand-loyalist.json
  packs/backgrounds/foreign-diplomat.json
  packs/backgrounds/sally-guard-neophyte.json
  packs/backgrounds/self-made.json
  packs/backgrounds/trade-representative.json
  packs/deities/cyth-vsug.json
  packs/deities/grask-uldeth.json
  packs/deities/jukha.json
  packs/deities/ketephys.json
  packs/deities/mahja-firehair.json
  packs/deities/nulgreth.json
  packs/deities/rull.json
  packs/deities/uirch.json
  packs/deities/varg.json
  packs/deities/wulgren.json
Labels: pr: data update

#16816 Add damage choice and effect for Dragon Throat Scale
  packs/equipment-effects/effect-dragon-throat-scale.json
  packs/equipment/dragon-throat-scale.json
Labels: pr: data update

#16840 Make effects panel scrollable
  src/module/actor/army/document.ts
  src/module/actor/army/sheet.ts
  src/module/actor/character/document.ts
  src/module/actor/character/elemental-blast.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/helpers.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/effects-panel.ts
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base/document.ts
  src/module/item/effect/data.ts
  src/module/item/spell/document.ts
  src/module/system/action-macros/helpers.ts
  src/module/system/check/check.ts
  src/module/system/statistic/statistic.ts
  src/module/system/text-editor.ts
  src/scripts/hooks/load.ts
  src/scripts/macros/perception-for-selected-tokens.ts
  src/scripts/macros/stealth-for-selected-tokens.ts
  src/scripts/macros/treat-wounds.ts
  src/scripts/sheet-util.ts
  src/scripts/ui/inline-roll-links.ts
  src/styles/system/_effects-panel.scss
  src/util/sheet.ts
  static/templates/system/effects-panel.hbs
  static/templates/system/effects/panel.hbs
  static/templates/system/effects/tooltip.hbs
Labels: ui/ux

#16828 Brush up Old Thornbarker's Sycophantic Scamps
  packs/wardens-of-wildwood-bestiary/old-thornbarker.json
Labels: pr: data update

#16852 Brush up Deity's Strike
  packs/spells/deitys-strike.json
Labels: pr: data update

#16851 Fix resistance value for Adamantine Body
  packs/feat-effects/effect-adamantine-body.json
Labels: pr: data update

#16847 Fix spells missing compendium source
  packs/curtain-call-bestiary/blackfingers.json
  packs/curtain-call-bestiary/delaraius-solzakarr.json
  packs/curtain-call-bestiary/echopsyvne.json
  packs/curtain-call-bestiary/father-skinsaw.json
  packs/curtain-call-bestiary/gray-master.json
  packs/curtain-call-bestiary/kimingio.json
  packs/curtain-call-bestiary/mask-of-blackfingers.json
  packs/curtain-call-bestiary/mask-of-father-skinsaw.json
  packs/curtain-call-bestiary/mask-of-gray-master.json
  packs/curtain-call-bestiary/mask-of-the-reaper.json
  packs/curtain-call-bestiary/prince-of-propaganda.json
  packs/curtain-call-bestiary/reaper-of-reputation.json
  packs/curtain-call-bestiary/risen-nemesis.json
  packs/curtain-call-bestiary/simandu.json
  packs/curtain-call-bestiary/venomfist.json
  packs/curtain-call-bestiary/zimiezek.json
  packs/pfs-season-6-bestiary/puddles-phantom-5-6.json
  packs/pfs-season-6-bestiary/puddles-phantom.json
Labels: pr: data update

#16846 Remove some invalid traits
  packs/adventure-specific-actions/holy-light.json
  packs/bestiary-family-ability-glossary/lich-steal-soul.json
  packs/blood-lords-bestiary/unstable-fiendflame-cage.json
Labels: pr: data update

#16839 Fixed some mismatched parentheses
  packs/equipment/elixir-of-life-minor.json
  packs/equipment/serpent-oil-lesser.json
  packs/equipment/viper-arrow.json
  packs/iconics/valeros-level-5.json
  packs/pfs-season-4-bestiary/evasive-vampire-count.json
  packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
Labels: pr: data update

#16854 Add missing traits to Minor Surging Serum
  packs/equipment/surging-serum-minor.json
Labels: pr: data update

#16843 Add Note for Envenom Companion
  packs/spell-effects/spell-effect-envenom-companion.json
  static/lang/re-en.json
Labels: pr: data update

#16853 Add Spell Effect for Acid Grip
  packs/spell-effects/spell-effect-acid-grip.json
  packs/spells/acid-grip.json
Labels: pr: data update

#16855 Add labeled badge to Sewer Ooze's Filth Wave effect
  packs/bestiary-effects/effect-filth-wave.json
Labels: pr: data update

#16397 Update Effect: Fortify Shield
  packs/feat-effects/effect-fortify-shield.json
Labels: pr: data update

#16856 Fix selectors of Curse of Ancestral Meddling
  packs/feat-effects/effect-curse-of-ancestral-meddling.json
Labels: pr: data update

#16857 Add backlink to Fortify Shield
  packs/feat-effects/effect-fortify-shield.json
Labels: pr: data update

#16858 Fix a malformed link
  packs/agents-of-edgewatch-bestiary/frefferth.json
  packs/agents-of-edgewatch-bestiary/skitterstitch.json
Labels: pr: data update

#16809 Brush up select Bestiary Effects
  packs/bestiary-effects/effect-aspers-elemental-aura.json
  packs/bestiary-effects/effect-black-cat-curse.json
  packs/bestiary-effects/effect-bosuns-command-attack-bonus.json
  packs/bestiary-effects/effect-bosuns-command-speed-bonus.json
  packs/bestiary-effects/effect-bosuns-command.json
  packs/bestiary-effects/effect-bravado-aversion.json
  packs/bestiary-effects/effect-guides-warning.json
  packs/bestiary-effects/effect-guiding-words.json
  packs/bestiary-effects/effect-guildmasters-lead.json
  packs/bestiary-effects/effect-hope-vulnerability.json
  packs/bestiary-effects/effect-inspiring-display.json
  packs/bestiary-effects/effect-inspiring-presence-empyreal-dragon.json
  packs/bestiary-effects/effect-stoke-the-fervent-high-tormentor.json
  packs/bestiary-effects/effect-stoke-the-fervent.json
  packs/npc-gallery/bosun.json
  packs/pfs-season-3-bestiary/iron-ring-bosun.json
  packs/pfs-season-3-bestiary/vaggas-the-bosun.json
  static/lang/re-en.json
Labels: pr: data update

#16826 Update Grapple actions to use newer format on select items
  packs/actions/skill-actions/grapple.json
  packs/age-of-ashes-bestiary/hermean-mutant.json
  packs/age-of-ashes-bestiary/rusty-mae.json
  packs/agents-of-edgewatch-bestiary/carvey.json
  packs/agents-of-edgewatch-bestiary/skinsaw-seamer.json
  packs/blood-lords-bestiary/eseneth.json
  packs/blood-lords-bestiary/iron-taviah.json
  packs/blood-lords-bestiary/rival-necromancer.json
  packs/blood-lords-bestiary/sallowdrudge.json
  packs/blood-lords-bestiary/zombie-rival-necromancer.json
  packs/feats/lassoing-lash.json
Labels: pr: data update

#16863 Restrict Kashrishi's Empathic Sense to non-mindless creatures
  packs/ancestryfeatures/empathic-sense.json
Labels: pr: data update

#16869 Update NPM dependencies
  eslint.config.js
  package-lock.json
  package.json
  tsconfig.json
  types/foundry/tsconfig.json
Labels: pr: housekeeping

#16868 Change action cost from 1 to 2 Con for Rit - Spit Venom
  packs/pathfinder-monster-core/con-rit.json
Labels: pr: data update

#16878 Fix duration of Champion's extra damage effect
  packs/feat-effects/effect-champions-extra-damage.json
Labels: pr: data update

#16881 Update descriptions on select equipment effects and add icons
  packs/equipment-effects/effect-choker-arm-mutagen-greater.json
  packs/equipment-effects/effect-choker-arm-mutagen-lesser.json
  packs/equipment-effects/effect-choker-arm-mutagen-major.json
  packs/equipment-effects/effect-choker-arm-mutagen-moderate.json
  packs/equipment-effects/effect-clockwork-goggles-greater.json
  packs/equipment-effects/effect-clockwork-goggles-major.json
  packs/equipment-effects/effect-clockwork-goggles.json
  packs/equipment-effects/effect-cloud-buns-greater.json
  packs/equipment-effects/effect-cloud-buns.json
  packs/equipment-effects/effect-cognitive-mutagen-greater.json
  packs/equipment-effects/effect-cognitive-mutagen-lesser.json
  packs/equipment-effects/effect-cognitive-mutagen-major.json
  packs/equipment-effects/effect-cognitive-mutagen-moderate.json
  packs/equipment-effects/effect-cold-iron-blanch-greater.json
  packs/equipment-effects/effect-cold-iron-blanch-lesser.json
  packs/equipment-effects/effect-cold-iron-blanch-moderate.json
  packs/equipment-effects/effect-conduct-energy.json
  packs/equipment-effects/effect-containment-contraption.json
  packs/equipment-effects/effect-covenant-tea.json
  packs/equipment-effects/effect-crackling-bubble-gum-failure.json
  packs/equipment-effects/effect-crackling-bubble-gum.json
  packs/equipment-effects/effect-crown-of-the-kobold-king.json
  packs/equipment-effects/effect-crushing-greater.json
  packs/equipment-effects/effect-crushing.json
  packs/equipment-effects/effect-deck-of-destiny.json
  packs/equipment-effects/effect-demon-dust-stage-1.json
  packs/equipment-effects/effect-demon-dust-stage-2.json
  packs/equipment-effects/effect-demortification-oil.json
  packs/equipment-effects/effect-desolation-locket-armor-greater.json
  packs/equipment-effects/effect-desolation-locket-armor-major.json
  packs/equipment-effects/effect-desolation-locket-armor.json
  packs/equipment-effects/effect-diplomats-badge.json
  packs/equipment-effects/effect-diplomats-charcuterie.json
  packs/equipment-effects/effect-disarm-success.json
  packs/equipment-effects/effect-draft-of-stellar-radiance.json
  packs/equipment-effects/effect-dragon-pearl.json
  packs/equipment-effects/effect-dragonfly-potion.json
  packs/equipment-effects/effect-dragons-blood-pudding-greater.json
  packs/equipment-effects/effect-dragons-blood-pudding-major.json
  packs/equipment-effects/effect-dragons-blood-pudding-moderate.json
  packs/equipment-effects/effect-dragons-eye-charm.json
  packs/equipment-effects/effect-dueling-cape.json
  packs/equipment-effects/effect-earplugs.json
  packs/equipment-effects/effect-ghost-fowl-porridge.json
  packs/equipment-effects/effect-ghost-lantern.json
  packs/equipment-effects/effect-glaive-of-the-artist.json
  packs/equipment-effects/effect-hexing-jar.json
  packs/equipment-effects/effect-holy-chain.json
  packs/equipment-effects/effect-holy-steam-ball.json
  packs/equipment-effects/effect-immortal-bastion.json
  packs/equipment/crown-of-the-kobold-king.json
  packs/equipment/diplomats-charcuterie.json
  packs/equipment/dragon-pearl.json
  packs/equipment/ghost-fowl-porridge.json
  packs/equipment/hexing-jar.json
Labels: pr: data update

#16877 Add Strike failure note to Energizing Lattice effect
  packs/equipment-effects/effect-energizing-lattice.json
  packs/equipment/climbing-kit-extreme.json
  packs/equipment/confabulator.json
  packs/equipment/energizing-lattice.json
  packs/feat-effects/effect-liberating-step-vs-aberration.json
  packs/feat-effects/effect-liberating-step-vs-dragon.json
  packs/feat-effects/effect-liberating-step-vs-fiend.json
  packs/feat-effects/effect-liberating-step-vs-undead.json
  packs/feat-effects/effect-protective-mentor-boon-admired-pfs.json
  packs/feat-effects/effect-protective-mentor-boon-liked-pfs.json
  packs/feat-effects/effect-protective-mentor-boon-revered-pfs.json
  packs/feats/dragon-grip.json
  packs/feats/emberkin.json
  packs/feats/know-the-beat.json
  static/lang/re-en.json
Labels: pr: data update

#16874 Brush up Asper's Elemental Aura effect description
  packs/bestiary-effects/effect-aspers-elemental-aura.json
  packs/bestiary-effects/effect-bosuns-command.json
Labels: pr: data update

#16872 Localize labels in Twitchy feat and adjust initiative modifier
  packs/feats/twitchy.json
  static/lang/re-en.json
Labels: pr: data update

#16859 Fix selector vs selectors for some AdjustModifier REs
  packs/kingmaker-features/army-tactics/cavalry-experts.json
  packs/spell-effects/spell-effect-veil-of-dreams.json
Labels: pr: data update

#16845 Remove and redirect condensed Dragon Breath spells
  build/uuid-redirects.json
  packs/spells/dragon-breath-black-brine-or-copper.json
  packs/spells/dragon-breath-blue-or-bronze.json
  packs/spells/dragon-breath-brass.json
  packs/spells/dragon-breath-cloud.json
  packs/spells/dragon-breath-crystal-or-forest.json
  packs/spells/dragon-breath-gold-magma-or-red.json
  packs/spells/dragon-breath-green.json
  packs/spells/dragon-breath-sea.json
  packs/spells/dragon-breath-silver-or-white.json
  packs/spells/dragon-breath-sky.json
  packs/spells/dragon-breath-sovereign.json
  packs/spells/dragon-breath-umbral.json
  packs/spells/dragon-breath-underworld.json
  packs/spells/dragon-breath.json
Labels: pr: data update

#16838 Restore Fire Shield's Rules Elements to function properly
  packs/spell-effects/spell-effect-fire-shield.json
Labels: pr: data update

#16834 Condense Thermal Nimbus effects
  build/uuid-redirects.json
  packs/feat-effects/effect-kinetic-aura.json
  packs/feat-effects/effect-thermal-nimbus-fire.json
  packs/feat-effects/effect-thermal-nimbus.json
  packs/feat-effects/stance-thermal-nimbus.json
Labels: pr: data update

#16832 Condense Aura of Faith effects and enable Champion's Aura by default
  build/uuid-redirects.json
  packs/classfeatures/champions-aura.json
  packs/feat-effects/effect-aura-of-faith-unholy.json
  packs/feat-effects/effect-aura-of-faith.json
  packs/feats/aura-of-faith.json
Labels: pr: data update

#16883 Add effect for Sixth Pillar Mastery
  packs/feat-effects/effect-sixth-pillar-mastery.json
  packs/feats/sixth-pillar-mastery.json
  static/lang/re-en.json
Labels: pr: data update

#16871 Add inline healing rolls to Vital Beacon
  packs/spell-effects/spell-effect-vital-beacon.json
  packs/spells/vital-beacon.json
Labels: pr: data update

#16836 Add Fortitude Save to Envenom Companion spell
  packs/spells/dinosaur-fort.json
  packs/spells/envenom-companion.json
  packs/spells/shambling-horror.json
Labels: pr: data update

#16885 Fix verbiage of Self Destruct feat for clarity
  packs/feats/self-destruct.json
Labels: pr: data update

#16886 Fix ability frequencies rejecting 0
  src/module/actor/sheet/base.ts
  src/module/item/ability/data.ts
Labels: pr: bugfix

#16870 Update Remeda to latest
  build/lib/extractor.ts
  build/run-migration.ts
  package-lock.json
  package.json
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/actor/familiar/document.ts
  src/module/actor/helpers.ts
  src/module/actor/npc/document.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/item/ability/sheet.ts
  src/module/item/affliction/document.ts
  src/module/item/feat/document.ts
  src/module/item/feat/sheet.ts
  src/module/item/shield/sheet.ts
  src/module/migration/migrations/927-class-background-skill-longform.ts
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/ae-like.ts
  src/module/rules/rule-element/damage-alteration/rule-element.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  src/module/system/settings/homebrew/data.ts
  src/module/system/settings/homebrew/languages.ts
  src/module/system/settings/homebrew/menu.ts
  src/module/system/tag-selector/languages.ts
  src/scripts/config/traits.ts
  src/scripts/hooks/init.ts
Labels: pr: housekeeping

#16887 Reduce remaining action uses when clicking the use button
  src/module/actor/character/sheet.ts
  src/module/actor/familiar/sheet.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/module/actor/sheet/helpers.ts
  src/module/actor/vehicle/sheet.ts
  src/module/chat-message/helpers.ts
  src/scripts/macros/hotbar.ts
  static/templates/actors/npc/partials/action.hbs
  static/templates/actors/partials/action.hbs
Labels: pr: enhancement

#16890 Improve some AppV2-related types
  eslint.config.js
  src/module/user/sheet.ts
  types/foundry/client-esm/applications/_types.d.ts
  types/foundry/client-esm/applications/api/application.d.ts
  types/foundry/client-esm/applications/api/document-sheet.d.ts
  types/foundry/client-esm/applications/api/handlebars-application.ts
  types/foundry/client-esm/applications/sheets/item-sheet.d.ts
  types/foundry/client-esm/applications/sheets/user-config.d.ts
Labels: pr: types update

#16891 Improve usability of ApplicationV2 type with mixins
  types/foundry/build/generate-client-base-mixes.ts
  types/foundry/client-esm/applications/api/application.d.ts
  types/foundry/client-esm/applications/api/document-sheet.d.ts
  types/foundry/client-esm/applications/api/module.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/client-document.d.ts
  types/foundry/util.d.ts
Labels: pr: types update

#16889 Remove duplicate "same-as" processing of linked martial proficiencies
  src/module/actor/character/document.ts
Labels: pr: bugfix

#16893 Add effects for Bomber's Eye Elixir
  packs/equipment-effects/effect-bombers-eye-elixir-cover-reduction.json
  packs/equipment-effects/effect-bombers-eye-elixir.json
  packs/equipment/bombers-eye-elixir-greater.json
  packs/equipment/bombers-eye-elixir-lesser.json
  static/lang/re-en.json
Labels: pr: data update

#16900 Condense Blood Booster Item Effect and update some item effect descriptions
  build/uuid-redirects.json
  packs/equipment-effects/effect-applereed-mutagen-greater.json
  packs/equipment-effects/effect-applereed-mutagen-lesser.json
  packs/equipment-effects/effect-applereed-mutagen-moderate.json
  packs/equipment-effects/effect-blood-booster-greater.json
  packs/equipment-effects/effect-blood-booster-lesser.json
  packs/equipment-effects/effect-blood-booster-moderate.json
  packs/equipment-effects/effect-blood-booster.json
  packs/equipment/blood-booster-greater.json
  packs/equipment/blood-booster-lesser.json
  packs/equipment/blood-booster-moderate.json
  static/lang/re-en.json
Labels: pr: data update

#16894 Update additional instances of inline damage to the newer format
  packs/abomination-vaults-bestiary/canker-cultist.json
  packs/abomination-vaults-bestiary/corpselight.json
  packs/abomination-vaults-bestiary/mister-beak.json
  packs/abomination-vaults-bestiary/morlock-cultist.json
  packs/abomination-vaults-bestiary/nhakazarin.json
  packs/abomination-vaults-bestiary/padli.json
  packs/abomination-vaults-bestiary/urdefhan-blood-mage.json
  packs/abomination-vaults-bestiary/volluk-azrinae.json
  packs/abomination-vaults-bestiary/witchfire-warden.json
  packs/abomination-vaults-bestiary/ysondkhelir.json
  packs/age-of-ashes-bestiary/crucidaemon.json
  packs/blood-lords-bestiary/kepgeda-the-hag-nailed.json
  packs/blood-lords-bestiary/matron-uldrula.json
  packs/book-of-the-dead-bestiary/ghul.json
  packs/crown-of-the-kobold-king-bestiary/hymmir-urath.json
  packs/crown-of-the-kobold-king-bestiary/id-ooze.json
  packs/extinction-curse-bestiary/kirosthrek.json
  packs/extinction-curse-bestiary/shanchek.json
  packs/extinction-curse-bestiary/smiler.json
  packs/extinction-curse-bestiary/stirvyn-banyan.json
  packs/extinction-curse-bestiary/xulgath-thoughtmaw.json
  packs/fists-of-the-ruby-phoenix-bestiary/syu-tak-nwa-level-16.json
  packs/gatewalkers-bestiary/elder-thing-researcher.json
  packs/impossible-lands-bestiary/kashrishi-evaluator.json
  packs/kingmaker-bestiary/elga-verniex.json
  packs/kingmaker-bestiary/leng-envoy.json
  packs/kingmaker-bestiary/nugrah.json
  packs/kingmaker-bestiary/tartuccio.json
  packs/malevolence-bestiary/esobok-ghoul.json
  packs/menace-under-otari-bestiary/ghoul-stalker-bb.json
  packs/monsters-of-myth-bestiary/somnalu-oculus.json
  packs/pathfinder-monster-core/ghoul-stalker.json
  packs/pathfinder-monster-core/imp.json
  packs/pfs-introductions-bestiary/ghoul-pfs-intro-2.json
  packs/pfs-season-1-bestiary/elite-ghast-pfs-1-07.json
  packs/pfs-season-1-bestiary/marcon-tinol-1-2.json
  packs/pfs-season-1-bestiary/marcon-tinol-3-4.json
  packs/pfs-season-3-bestiary/ghast-arctic.json
  packs/pfs-season-3-bestiary/ghast-heretical.json
  packs/pfs-season-4-bestiary/grace-of-the-owl.json
  packs/pfs-season-4-bestiary/overtaxed-vrisk.json
  packs/pfs-season-4-bestiary/suhko-1-2.json
  packs/pfs-season-4-bestiary/suhko-3-4.json
  packs/pfs-season-4-bestiary/urdefhan-blood-mage-pfs-4-11.json
  packs/pfs-season-5-bestiary/barnacle-barnaby-5-6.json
  packs/pfs-season-6-bestiary/averill-quint-3-4.json
  packs/pfs-season-6-bestiary/pathfinder-protector.json
  packs/pfs-season-6-bestiary/whippoorwill-pathfinder-protector.json
  packs/rusthenge-bestiary/vlorian-cythnigot.json
  packs/rusthenge-bestiary/zaiox.json
  packs/seven-dooms-for-sandpoint-bestiary/glorkus.json
  packs/seven-dooms-for-sandpoint-bestiary/goblin-ghoul.json
  packs/sky-kings-tomb-bestiary/enraged-dream.json
  packs/sky-kings-tomb-bestiary/soulbound-doll-sky-kings-tomb.json
  packs/sky-kings-tomb-bestiary/ulat-kini-mindreaver.json
  packs/stolen-fate-bestiary/kannijo.json
  packs/strength-of-thousands-bestiary/king-of-biting-ants.json
Labels: pr: data update

#16864 Add template to Bloodsiphon's Death Burst
  packs/abomination-vaults-bestiary/bloodsiphon.json
Labels: pr: data update

#16903 Brush up rule elements on Monstrous Peacemaker
  packs/feats/monstrous-peacemaker.json
Labels: pr: data update

#16750 Add `remaster` table class to `_globals.css`
  src/styles/_globals.scss
Labels: ui/ux

#16905 Include "system.runes" as index field for item-filter choice sets
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#16899 Recharge turn and round abilities as the encounter changes turns
  src/module/actor/base.ts
  src/module/actor/spellcasting.ts
  src/module/actor/types.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/scripts/macros/rest-for-the-night.ts
Labels: pr: enhancement

#16910 Apply remaster theme to tables in GM Screen and Remaster Changes Journals
  packs/journals/gm-screen.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#16907 Condense effects for Mudrock Snare
  build/uuid-redirects.json
  packs/equipment-effects/effect-dragonfly-potion.json
  packs/equipment-effects/effect-immolation-clan-pistol.json
  packs/equipment-effects/effect-mudrock-snare-failure.json
  packs/equipment-effects/effect-mudrock-snare-success.json
  packs/equipment-effects/effect-mudrock-snare.json
  packs/equipment/mudrock-snare.json
Labels: pr: data update

#16914 Fix spells missing compendium source
  packs/triumph-of-the-tusk-bestiary/floodslain-mage.json
  packs/triumph-of-the-tusk-bestiary/orc-doomsayer.json
  packs/triumph-of-the-tusk-bestiary/stormblood-tiger.json
  packs/triumph-of-the-tusk-bestiary/tooth-fairy-leader.json
Labels: pr: data update

#16913 Fix some token names
  packs/pfs-season-6-bestiary/adolescent-kirin.json
  packs/pfs-season-6-bestiary/empowered-bloodmoon-3-4.json
  packs/pfs-season-6-bestiary/greased-floor-3-4.json
Labels: pr: data update

#16917 Fix Solar Rejuvenation healing formula
  packs/feats/solar-rejuvenation.json
  static/lang/re-en.json
Labels: pr: data update

#16919 Fix name of consumable effect
  packs/equipment-effects/effect-sakuras-sprig.json
  packs/equipment/sakuras-sprig.json
Labels: pr: data update

#16865 Initial implementation of SpecialResource rule element
  src/module/actor/base.ts
  src/module/actor/character/data.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/data.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/helpers.ts
  src/module/actor/sheet/base.ts
  src/module/actor/spellcasting.ts
  src/module/actor/types.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/special-resource.ts
  src/module/rules/synthetics.ts
  src/module/scene/token-document/document.ts
  src/scripts/macros/rest-for-the-night.ts
  src/styles/actor/character/_sidebar.scss
  static/lang/en.json
  static/lang/re-en.json
  static/templates/actors/character/partials/header.hbs
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/character/tabs/spellcasting.hbs
Labels: pr: enhancement

#16924 Allow alternative handwraps to function like Handwraps of Mighty Blows
  packs/equipment/amphisbaena-handwraps.json
  packs/equipment/dragon-handwraps.json
  packs/equipment/handwraps-of-mighty-blows.json
  src/module/actor/character/document.ts
  src/module/item/weapon/types.ts
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: bugfix

#16895 Fix Crash/Freeze when missing @Damage closing bracket
  src/scripts/hooks/init.ts
Labels: pr: bugfix

#16911 Organize character feat collection classes and interfaces
  src/global.ts
  src/module/actor/army/document.ts
  src/module/actor/character/document.ts
  src/module/actor/character/feats/collection.ts
  src/module/actor/character/feats/group.ts
  src/module/actor/character/feats/index.ts
  src/module/actor/character/feats/types.ts
  src/module/actor/character/sheet.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/item/campaign-feature/document.ts
  src/module/item/class/document.ts
  src/module/item/feat/document.ts
Labels: pr: refactor

#16920 Add automation for Hard to Target
  packs/feat-effects/effect-cast-down.json
  packs/triumph-of-the-tusk-bestiary/skinslough.json
Labels: pr: data update

#16927 Fix order of initialization checks in prepareData overrides
  src/module/actor/army/document.ts
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/actor/hazard/document.ts
  src/module/encounter/combatant.ts
  src/module/encounter/document.ts
  src/module/item/base/document.ts
  src/util/dom.ts
Labels: pr: bugfix

#16928 Restore visibility of compendium directory in V13
  static/templates/sidebar/compendium-directory.hbs
Labels: pr: bugfix

#16931 Remove dead code from refactored helper
  src/module/canvas/measured-template.ts
Labels: pr: bugfix

#16934 Add v13 check to data-group attribute in `CompendiumDirectory` template
  src/module/apps/sidebar/compendium-directory.ts
  static/templates/sidebar/compendium-directory.hbs
Labels: pr: bugfix

#16939 Fix regression with saving prepared crafting formulas
  src/module/actor/character/crafting/ability.ts
Labels: pr: bugfix

#16929 Add automation for Kun's Heart of Darkness
  packs/abomination-vaults-bestiary/mulventok.json
  packs/book-of-the-dead-bestiary/gallowdead.json
  packs/book-of-the-dead-bestiary/minister-of-tumult.json
  packs/kingmaker-bestiary/gromog.json
  packs/pathfinder-bestiary/bunyip.json
  packs/pfs-season-2-bestiary/saddleback-bunyip.json
  packs/tian-xia-world-guide-bestiary/kun.json
Labels: pr: data update

#16936 Add automation for Shadow Stride
  packs/gatewalkers-bestiary/the-looksee-man.json
  packs/pathfinder-bestiary-2/fetchling-scout.json
  packs/pfs-season-3-bestiary/onyx-alliance-commander.json
  packs/pfs-season-3-bestiary/onyx-alliance-officer.json
  packs/pfs-season-3-bestiary/onyx-alliance-scout.json
  packs/pfs-season-3-bestiary/veteran-onyx-alliance-scout.json
Labels: pr: data update

#16941 Show DC for Steady Spellcasting
  packs/feats/combat-reading.json
  packs/feats/steady-spellcasting-magus.json
  packs/feats/steady-spellcasting.json
  packs/kingmaker-bestiary/linzi-level-7.json
Labels: pr: data update

#16943 Add effect for Steel Yourself!
  packs/feat-effects/effect-steel-yourself.json
  packs/feats/steel-yourself.json
Labels: pr: data update

#16938 Update Hex trait description to use Player Core text.
  static/lang/en.json
Labels: pr: data update

#16896 Add an "ABC Picker" as an alternative to opening compendiums from PC sheets
  eslint.config.js
  package-lock.json
  package.json
  src/module/actor/character/apps/abc-picker/app.svelte
  src/module/actor/character/apps/abc-picker/app.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/system/svelte/mixin.svelte.ts
  src/scripts/hooks/load.ts
  src/styles/_application.scss
  src/styles/main.scss
  static/lang/en.json
  static/templates/actors/character/tabs/character.hbs
  tsconfig.json
  types/foundry/client-esm/applications/_types.d.ts
  types/foundry/client/apps/app.d.ts
  types/foundry/client/core/searchfilter.d.ts
  vite.config.ts
Labels: pr: enhancement

#16948 Add spellcasting entry to Noppera-Bo Occultist
  packs/season-of-ghosts-bestiary/noppera-bo-occultist.json
Labels: pr: data update

#16955 Fix vision on some FOTRP NPCs
  packs/fists-of-the-ruby-phoenix-bestiary/ghost-monk.json
  packs/fists-of-the-ruby-phoenix-bestiary/ji-yook-level-9.json
  packs/fists-of-the-ruby-phoenix-bestiary/kannitri.json
  packs/fists-of-the-ruby-phoenix-bestiary/old-man-statue.json
  packs/fists-of-the-ruby-phoenix-bestiary/takatorra-level-9.json
  packs/fists-of-the-ruby-phoenix-bestiary/yabin-the-just-level-9.json
Labels: pr: data update

#16957 Add effect roll options of "parent:origin" and "parent:origin:item" if applicable
  src/module/item/abstract-effect/document.ts
Labels: pr: enhancement

#16921 Add effect for Cauterize Wounds
  packs/spell-effects/spell-effect-cauterize-wounds.json
  packs/spells/cauterize-wounds.json
Labels: pr: data update

#16933 Condense Bloodseeker Beak equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-bloodseeker-beak-greater.json
  packs/equipment-effects/effect-bloodseeker-beak.json
  packs/equipment/bloodseeker-beak-greater.json
Labels: pr: data update
