Repository foundryvtt/pf2e, pull requests merged in 2024-02, with the labels that each got.

#13438 Populate `_id` field of spells embedded in old scrolls and wands
  build/run-migration.ts
  packs/abomination-vaults-bestiary/jafaki.json
  packs/age-of-ashes-bestiary/voz-lirayne.json
  packs/blood-lords-bestiary/rumin-purgo.json
  packs/crown-of-the-kobold-king-bestiary/narlynark.json
  packs/extinction-curse-bestiary/cavnakash.json
  packs/extinction-curse-bestiary/dyzallin-shraen.json
  packs/extinction-curse-bestiary/mistress-dusklight.json
  packs/extinction-curse-bestiary/stirvyn-banyan.json
  packs/gatewalkers-bestiary/etward-ritalson.json
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-5.json
  packs/iconics/feiya-level-5.json
  packs/iconics/korakai-level-1.json
  packs/iconics/korakai-level-5.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/kingmaker-bestiary/castruccio-irovetti.json
  packs/kingmaker-bestiary/gurija.json
  packs/kingmaker-bestiary/kereek.json
  packs/kingmaker-bestiary/lickweed.json
  packs/kingmaker-bestiary/linzi-level-7.json
  packs/kingmaker-bestiary/malgorzata-niska.json
  packs/kingmaker-bestiary/tartuccio.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/outlaws-of-alkenstar-bestiary/dewey-daystar.json
  packs/paizo-pregens/bottlespeaker.json
  packs/paizo-pregens/elsir-syniras.json
  packs/paizo-pregens/eteleon.json
  packs/paizo-pregens/grimmnir.json
  packs/paizo-pregens/izni.json
  packs/paizo-pregens/jaithe.json
  packs/paizo-pregens/kellsti.json
  packs/paizo-pregens/lavanna-saltspray.json
  packs/paizo-pregens/zeah.json
  packs/pathfinder-bestiary-3/quintessivore.json
  packs/pfs-season-5-bestiary/ghessa-5-6.json
  packs/pfs-season-5-bestiary/ghessa.json
  packs/rusthenge-bestiary/meitremar.json
  packs/season-of-ghosts-bestiary/heh-shan-bao.json
  packs/stolen-fate-bestiary/trexima-butoi.json
  src/module/migration/migrations/917-scroll-wand-spell-ids.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: data update

#13440 Show all scrolls/wands in activations subtab, allow to be drawn
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  static/lang/action-en.json
  static/templates/actors/partials/spell-collection.hbs
Labels: pr: enhancement

#13435 Update Blood Magic effect descriptions
  packs/classfeatures/bloodline-hag.json
  packs/feat-effects/effect-aberrant-blood-magic.json
  packs/feat-effects/effect-angelic-blood-magic.json
  packs/feat-effects/effect-demonic-blood-magic.json
  packs/feat-effects/effect-diabolic-blood-magic-self.json
  packs/feat-effects/effect-draconic-blood-magic.json
  packs/feat-effects/effect-elemental-blood-magic-self.json
  packs/feat-effects/effect-genie-blood-magic.json
  packs/feat-effects/effect-imperial-blood-magic.json
  packs/feat-effects/effect-nymph-blood-magic.json
  packs/feat-effects/effect-psychopomp-blood-magic-self.json
  packs/feat-effects/effect-shadow-blood-magic.json
  packs/feat-effects/effect-wyrmblessed-blood-magic.json
Labels: pr: data update

#13439 Automate Witch's Patron Familiar Ability notes upon casting a hex
  packs/classfeatures/baba-yaga-patron.json
  packs/classfeatures/faiths-flamekeeper.json
  packs/classfeatures/mosquito-witch-patron.json
  packs/classfeatures/silence-in-snow.json
  packs/classfeatures/spinner-of-threads.json
  packs/classfeatures/starless-shadow.json
  packs/classfeatures/the-inscribed-one.json
  packs/classfeatures/the-resentment.json
  packs/classfeatures/wilding-steward.json
  packs/feat-effects/effect-familiar-of-balanced-luck.json
  packs/feat-effects/effect-familiar-of-keen-senses.json
  packs/feat-effects/effect-familiar-of-restored-spirit.json
  static/lang/re-en.json
Labels: pr: data update

#13443 Have spellcasting toggles scroll with collections
  src/styles/actor/character/_spellcasting.scss
  static/templates/actors/character/tabs/spellcasting.hbs
Labels: ui/ux

#13445 Prevent (harmless) error after drag/drop of cantrips in prepared entries
  src/module/actor/creature/sheet.ts
Labels: pr: bugfix

#13446 Prevent item-casting spell drag/drop
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/partials/spell-collection.hbs
Labels: pr: bugfix

#13444 Automate Kinetic Activation and Scroll Thaumaturgy
  packs/feats/kinetic-activation.json
  packs/feats/scroll-thaumaturgy.json
Labels: pr: data update

#13448 Run extractPacks all
  packs/classes/cleric.json
  packs/equipment/dragons-eye-charm.json
  packs/equipment/fluid-form-staff-greater.json
  packs/equipment/staff-of-arcane-might-major.json
  packs/equipment/staff-of-the-dead-major.json
  packs/equipment/wyrm-drinker.json
Labels: pr: data update

#13450 Subtract cost amount instead of always 1 when consuming focus points
  src/module/item/spellcasting-entry/document.ts
Labels: pr: bugfix

#13449 Add noisy to Ghoul Hide when worn by an elf
  packs/equipment/ghoul-hide.json
Labels: pr: data update

#13452 Withhold showing stowed scrolls/wands in activations tab
  src/module/actor/creature/document.ts
Labels: ui/ux

#13451 Release Notes 5.13.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#13453 Update vite-plugin-checker
  package-lock.json
  package.json
Labels: pr: housekeeping

#13464 Fix some formatting
  packs/boons-and-curses/besmara-major-boon.json
  packs/equipment/accursed-staff-greater.json
  packs/equipment/accursed-staff-major.json
  packs/equipment/accursed-staff.json
  packs/equipment/dragonprism-staff-greater.json
  packs/equipment/dragonprism-staff.json
  packs/equipment/false-death.json
  packs/equipment/jaathooms-scarf.json
  packs/equipment/preserving-greater.json
  packs/equipment/skinsaw-mask.json
  packs/feats/shadow-magic.json
  packs/journals/archetypes.json
  packs/journals/gm-screen.json
  packs/kingmaker-bestiary/shambler.json
  packs/pathfinder-bestiary-3/adult-underworld-dragon.json
  packs/pathfinder-bestiary-3/ancient-underworld-dragon.json
  packs/pathfinder-bestiary-3/deimavigga.json
  packs/pathfinder-bestiary-3/elder-sphinx.json
  packs/pathfinder-bestiary-3/kurobozu.json
  packs/pathfinder-bestiary-3/young-underworld-dragon.json
  packs/pathfinder-bestiary/shambler.json
  packs/pfs-season-5-bestiary/ghessa-5-6.json
  packs/pfs-season-5-bestiary/ghessa.json
  packs/season-of-ghosts-bestiary/shrine-maiden.json
  packs/season-of-ghosts-bestiary/the-chewer.json
  packs/spells/bit-of-luck.json
  packs/spells/freeze-time.json
  packs/spells/planar-tether.json
  packs/spells/seize-soul.json
  packs/spells/temporal-ward.json
  packs/spells/thunderburst.json
  packs/spells/weapon-surge.json
Labels: pr: data update

#13463 Remove em tags from spell links
  packs/equipment/arboreal-staff.json
  packs/equipment/dawnflower-beads.json
  packs/equipment/final-rest.json
  packs/equipment/fluid-form-staff-greater.json
  packs/equipment/fluid-form-staff-major.json
  packs/equipment/fluid-form-staff.json
  packs/equipment/ghost-dust.json
  packs/equipment/mentalists-staff-major.json
  packs/equipment/potion-of-undetectability.json
  packs/equipment/staff-of-arcane-might-greater.json
  packs/equipment/staff-of-arcane-might-major.json
  packs/equipment/staff-of-summoning-greater.json
  packs/equipment/staff-of-summoning-major.json
  packs/equipment/staff-of-summoning.json
  packs/equipment/staff-of-the-dead-greater.json
  packs/equipment/staff-of-the-dead-major.json
  packs/equipment/staff-of-the-unblinking-eye-greater.json
  packs/equipment/staff-of-the-unblinking-eye-major.json
  packs/equipment/staff-of-the-unblinking-eye.json
  packs/equipment/wyrm-drinker.json
  packs/extinction-curse-bestiary/hallowed-wheel.json
  packs/feats/kinetic-activation.json
  packs/feats/summon-wood-elemental.json
  packs/journals/archetypes.json
  packs/night-of-the-gray-death-bestiary/planar-eviction-trap.json
  packs/one-shot-bestiary/doatara-the-priest.json
  packs/pathfinder-bestiary-3/sturzstromer.json
  packs/spell-effects/spell-effect-gecko-grip.json
  packs/spell-effects/spell-effect-protection.json
  packs/spell-effects/spell-effect-sure-strike.json
  packs/strength-of-thousands-bestiary/spider-summoning-rune.json
Labels: pr: data update

#13461 Add cursebound trait to spells cast with Mystery Conduit on
  packs/feats/mystery-conduit.json
Labels: pr: data update

#13462 Brushup RE Sheltering Slab
  packs/feats/sheltering-slab.json
Labels: pr: data update

#13466 Set tradition in Kinetic Activation spellcasting ability
  packs/feats/kinetic-activation.json
Labels: pr: data update

#13467 Update description and formatting of Potion of Disguise
  packs/equipment/potion-of-disguise-greater.json
  packs/equipment/potion-of-disguise-lesser.json
  packs/equipment/potion-of-disguise-moderate.json
Labels: pr: data update

#13468 Add adamantine trait to Underworld Dragon claw attack
  packs/pathfinder-bestiary-3/adult-underworld-dragon-spellcaster.json
  packs/pathfinder-bestiary-3/adult-underworld-dragon.json
  packs/pathfinder-bestiary-3/ancient-underworld-dragon-spellcaster.json
  packs/pathfinder-bestiary-3/ancient-underworld-dragon.json
  packs/pathfinder-bestiary-3/young-underworld-dragon-spellcaster.json
  packs/pathfinder-bestiary-3/young-underworld-dragon.json
Labels: pr: data update

#13475 Restore visiblity of manually-created spellcasting entries
  src/module/actor/creature/sheet.ts
  src/module/item/spellcasting-entry/document.ts
  static/templates/actors/partials/spell-collection.hbs
Labels: pr: bugfix

#13479 Show prepared descriptions in all item chat cards
  static/templates/chat/action-card.hbs
  static/templates/chat/affliction-card.hbs
  static/templates/chat/armor-card.hbs
  static/templates/chat/backpack-card.hbs
  static/templates/chat/campaign-feature-card.hbs
  static/templates/chat/condition-card.hbs
  static/templates/chat/consumable-card.hbs
  static/templates/chat/effect-card.hbs
  static/templates/chat/equipment-card.hbs
  static/templates/chat/feat-card.hbs
  static/templates/chat/shield-card.hbs
  static/templates/chat/treasure-card.hbs
  static/templates/chat/weapon-card.hbs
Labels: pr: bugfix

#13485 Retrieve action roll options when generating inline damage labels
  src/module/system/text-editor.ts
Labels: pr: bugfix

#13480 Add upgrade notes to Halfling Luck
  packs/feats/guiding-luck.json
  packs/feats/incredible-luck-halfling.json
  packs/feats/shared-luck-halfling.json
  static/lang/re-en.json
Labels: pr: data update

#13354 Add healing links to Sacred Ground predicated on Divine Font type
  packs/feats/sacred-ground.json
  static/lang/re-en.json
Labels: pr: data update

#13456 Correctly set all Feat Max Taking values
  packs/feats/additional-companion.json
  packs/feats/advanced-warden.json
  packs/feats/deeper-dabbler.json
  packs/feats/divine-access.json
  packs/feats/ganzi-gaze.json
  packs/feats/heightened-captivation.json
  packs/feats/macabre-virtuoso.json
  packs/feats/major-lesson.json
  packs/feats/reclaimant-plea.json
  packs/feats/soul-arsenal.json
  packs/feats/specialized-beastmaster-companion.json
  packs/feats/specialized-companion-druid.json
  packs/feats/specialized-mount.json
  packs/feats/stronger-debilitating-venom.json
  packs/feats/ubiquitous-gadgets.json
  packs/feats/vigilant-benediction.json
  packs/feats/wilderness-spotter.json
Labels: pr: data update

#13477 Append aura shut off reminder note to overflow impulses
  packs/classfeatures/kinetic-aura.json
  static/lang/re-en.json
Labels: pr: data update

#13482 Fix description of mysterious breadth
  packs/feats/mysterious-breadth.json
Labels: pr: data update

#13471 Brush up Vision of Weakness spell effect
  packs/spell-effects/spell-effect-vision-of-weakness.json
Labels: pr: data update

#13483 Prevent unidentified scrolls and wands from appearing in activations subtab
  src/module/actor/creature/document.ts
Labels: pr: bugfix

#13472 Disable flanking for GM-hidden tokens
  src/global.ts
  src/module/canvas/token/object.ts
  src/scripts/set-game-pf2e.ts
Labels: pr: bugfix

#13493 Release Notes 5.13.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#13494 Update copyright until April-July 2024
  static/licenses/OpenGameLicense.md
Labels: source: adventure path, pr: housekeeping, source: pathfinder society, source: rulebooks, source: lost omens, source: adventure

#13492 Replace note on Sticky Bomb feat with flat modifier
  packs/feats/sheltering-slab.json
  packs/feats/sticky-bomb.json
Labels: pr: data update

#13491 Add upgrade notes and predicated bonuses to Nanite Surge
  packs/feat-effects/effect-nanite-surge-bonus.json
  packs/feats/consistent-surge.json
  packs/feats/offensive-subroutine.json
  packs/feats/protective-subroutine.json
  static/lang/re-en.json
Labels: pr: data update

#13500 Refresh Shobhad Sniper's copy of Shobhad Longrifle
  packs/strength-of-thousands-bestiary/shobhad-sniper.json
Labels: pr: data update

#13495 Add create bonus feat button to kingdom
  src/module/actor/party/kingdom/sheet.ts
  static/templates/actors/party/kingdom/tabs/features.hbs
Labels: pr: enhancement

#13503 Add icon to Illuminated Folio and update description
  packs/equipment-effects/effect-illuminated-folio.json
  packs/equipment/illuminated-folio.json
Labels: pr: data update

#13502 Add icon to effect for Arachnid Harness and localize label
  packs/equipment-effects/effect-arachnid-harness.json
  packs/equipment/arachnid-harness-greater.json
  packs/equipment/arachnid-harness.json
  static/lang/re-en.json
Labels: pr: data update

#13501 Brush up Elysian Dew descriptions and add icon
  packs/equipment-effects/aura-elysian-dew.json
  packs/equipment-effects/effect-elysian-dew.json
  packs/equipment/elysian-dew.json
Labels: pr: data update

#13498 Fix token name for Vivielle Ramslay
  packs/outlaws-of-alkenstar-bestiary/vivielle-ramslay.json
Labels: pr: data update

#13497 Fix malformed links to Marvelous Mount in Staff of Summoning
  packs/equipment/staff-of-summoning-greater.json
  packs/equipment/staff-of-summoning-major.json
  packs/equipment/staff-of-summoning.json
Labels: pr: data update

#13499 Standardize selector for Jabali's Dice
  packs/equipment/black-hole-armor.json
  packs/equipment/jabalis-dice.json
Labels: pr: data update

#13504 Add link to Invisibility from Mislead
  packs/spells/mislead.json
Labels: pr: data update

#13508 Fix regression in spellcasting entry drag/drop
  src/module/apps/compendium-browser/index.ts
  src/styles/actor/character/_spellcasting.scss
  static/templates/actors/character/tabs/spellcasting.hbs
  static/templates/actors/partials/spell-collection.hbs
Labels: pr: bugfix

#13511 Add Magical Trait to Strikes granted by Morph spell effects
  packs/spell-effects/spell-effect-animal-feature-claws.json
  packs/spell-effects/spell-effect-animal-feature-jaws.json
  packs/spell-effects/spell-effect-dragon-claws.json
  packs/spell-effects/spell-effect-gluttons-jaw.json
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart-icy-claws.json
  packs/spell-effects/spell-effect-mantle-of-the-magma-heart-fiery-grasp.json
  packs/spell-effects/spell-effect-mantle-of-the-unwavering-heart.json
  packs/spell-effects/spell-effect-moon-frenzy.json
  packs/spell-effects/spell-effect-shifting-form.json
  packs/spell-effects/spell-effect-untamed-shift.json
Labels: pr: data update

#13512 Change spell level into spell rank in re-en
  static/lang/re-en.json
Labels: pr: data update

#13516 Fix level of Life's Flowing River
  packs/spells/lifes-flowing-river.json
Labels: pr: data update

#13514 Fix price of Bravery Baldric (Haste)
  packs/equipment/bravery-baldric-fleet.json
  packs/equipment/bravery-baldric-flight.json
  packs/equipment/bravery-baldric-haste.json
  packs/equipment/bravery-baldric-restoration-greater.json
  packs/equipment/bravery-baldric-restoration.json
  packs/equipment/bravery-baldric-stoneskin.json
Labels: pr: data update

#13517 Remove damage partial from Life's Flowing River and add inline damage links
  packs/spells/lifes-flowing-river.json
Labels: pr: data update

#13522 Add icons to some equipment
  packs/equipment-effects/effect-desolation-locket-armor-greater.json
  packs/equipment-effects/effect-desolation-locket-armor-major.json
  packs/equipment-effects/effect-desolation-locket-armor.json
  packs/equipment-effects/effect-desolation-locket-weapon.json
  packs/equipment/bracers-of-devotion.json
  packs/equipment/courtiers-pillow-book.json
  packs/equipment/gingerbread-house.json
  packs/equipment/remote-trigger.json
  packs/equipment/splendid-skull-mask.json
Labels: pr: data update

#13524 Fill some more icon gaps
  packs/classfeatures/inventor-weapon-expertise.json
  packs/classfeatures/inventor-weapon-mastery.json
  packs/equipment/battle-lute.json
  packs/equipment/drums-of-war-greater.json
  packs/equipment/drums-of-war-major.json
  packs/equipment/drums-of-war.json
  packs/equipment/entertainers-lute-greater.json
  packs/equipment/entertainers-lute-major.json
  packs/equipment/entertainers-lute.json
  packs/equipment/smoke-fan-greater.json
  packs/equipment/smoke-fan.json
  static/icons/equipment/held-items/entertainers-lute.webp
  static/icons/equipment/held-items/fiddle-of-the-maestro.webp
  static/icons/equipment/held-items/smoke-fan.webp
  static/icons/equipment/other/magic-pots/walking-cauldron.webp
Labels: pr: data update, pr: static assets

#13528 Move kingdom mod computation to a later step
  src/module/actor/party/kingdom/model.ts
Labels: pr: enhancement, kingmaker

#13521 Add Reinforced Stock as base weapon type
  packs/equipment/reinforced-stock.json
  static/lang/en.json
Labels: pr: data update

#13540 Allow senses RE to apply to NPCs
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/rules/rule-element/sense.ts
Labels: pr: bugfix

#13539 Correct precision damage getting halved by critical success
  src/module/system/damage/iwr.ts
Labels: pr: bugfix

#13533 Always create RitualSpellcasting instances
  src/module/actor/base.ts
  src/module/item/spellcasting-entry/rituals.ts
Labels: pr: enhancement, ui/ux

#13132 Add recall knowledge action object
  src/module/system/action-macros/general/recall-knowledge.ts
  src/module/system/action-macros/index.ts
  static/lang/action-en.json
Labels: pr: enhancement

#13543 Fix identification of mystified mundane items
  src/module/actor/sheet/popups/identify-popup.ts
  src/module/item/identification.ts
Labels: pr: bugfix

#13534 Grant Deadly Simplicity with Warpriest's First Doctrine
  packs/classfeatures/first-doctrine-warpriest.json
Labels: pr: data update

#13545 Don't defer ritual creation
  src/module/item/spellcasting-entry/rituals.ts
Labels: pr: refactor

#13542 Update Geas description
  packs/abomination-vaults-bestiary/drow-cavern-seer.json
  packs/agents-of-edgewatch-bestiary/miogimo.json
  packs/kingmaker-bestiary/avatar-of-the-lantern-king.json
  packs/kingmaker-bestiary/niodrhast.json
  packs/kingmaker-bestiary/nyrissa.json
  packs/pathfinder-bestiary-2/marut.json
  packs/pathfinder-bestiary-2/neothelid.json
  packs/pathfinder-bestiary-2/norn.json
  packs/pathfinder-bestiary-2/theletos.json
  packs/pathfinder-bestiary-2/zelekhut.json
  packs/pathfinder-bestiary-3/crossroads-guardian.json
  packs/pathfinder-bestiary/balisse.json
  packs/pathfinder-bestiary/kolyarut.json
  packs/pathfinder-bestiary/veiled-master.json
  packs/spells/geas.json
  packs/stolen-fate-bestiary/diskrasia-the-sharp.json
  packs/stolen-fate-bestiary/fabrina-the-spinster.json
  packs/stolen-fate-bestiary/hala-the-rod.json
  packs/strength-of-thousands-bestiary/tatterthread.json
Labels: pr: data update

#13530 Update publication data of some PC1 class feats
  packs/feats/dueling-parry-fighter.json
  packs/feats/slam-down.json
  packs/feats/sneak-adept.json
  packs/feats/tactical-reflexes.json
Labels: pr: data update

#13526 Remove class kits
  packs/equipment/class-kit-alchemist.json
  packs/equipment/class-kit-barbarian.json
  packs/equipment/class-kit-bard.json
  packs/equipment/class-kit-champion.json
  packs/equipment/class-kit-cleric.json
  packs/equipment/class-kit-druid.json
  packs/equipment/class-kit-fighter.json
  packs/equipment/class-kit-investigator.json
  packs/equipment/class-kit-monk.json
  packs/equipment/class-kit-oracle.json
  packs/equipment/class-kit-ranger.json
  packs/equipment/class-kit-rogue.json
  packs/equipment/class-kit-sorcerer.json
  packs/equipment/class-kit-swashbuckler.json
  packs/equipment/class-kit-witch.json
  packs/equipment/class-kit-wizard.json
Labels: pr: data update

#13547 Show spontaneous spells as expended when max slots is 0
  src/module/item/spellcasting-entry/collection.ts
Labels: pr: bugfix

#13548 Fix variant overlay data of Falling Stars spell
  packs/spells/falling-stars.json
Labels: pr: data update

#13531 Automate addition of swarm condition immunities, update construct immunities
  src/module/actor/creature/helpers.ts
Labels: pr: enhancement

#13549 Slightly reduce size of checkboxes in roll-option toggles
  src/styles/actor/_index.scss
Labels: ui/ux

#13550 Define types for stored passive spell defense
  src/module/actor/sheet/base.ts
  src/module/item/spell/data.ts
  src/module/migration/migrations/882-spell-data-reorganization.ts
  src/module/migration/migrations/894-no-lay-on-hands-vs-undead.ts
  src/module/migration/migrations/897-clear-lay-on-hands-damage.ts
Labels: pr: refactor, pr: types update

#13551 Prefer `arr.length === 0` over `!arr.length`
  src/module/actor/character/attribute-builder.ts
  src/module/actor/inventory/index.ts
  src/module/actor/party/sheet.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/item/abc/document.ts
  src/module/item/base/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/helpers.ts
  src/scripts/macros/edit-persistent.ts
Labels: pr: refactor

#13552 Read from stored passive defense during spell data preparation
  src/module/item/spell/document.ts
Labels: pr: enhancement

#13553 Fix wiping spell defenses when cleared in sheet
  src/module/item/spell/document.ts
Labels: pr: bugfix

#13541 Handle spellcasting for creatures only
  src/module/actor/base.ts
  src/module/actor/creature/document.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/item/consumable/document.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/document.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: refactor

#13555 Correct passive defense of attack spells targeting fortitude DC
  packs/spells/black-tentacles.json
  packs/spells/murderous-vine.json
  packs/spells/ravenous-darkness.json
Labels: pr: data update

#13556 Fix Celestial Staff and Hell Staff to be specific items
  packs/equipment/celestial-staff.json
  packs/equipment/hell-staff.json
Labels: pr: data update

#13557 Fix Delay Affliction to deliver healing
  packs/spells/delay-affliction.json
Labels: pr: data update

#13554 Make passive spell defenses available for editing
  src/module/item/spell/sheet.ts
  static/templates/items/spell-details.hbs
Labels: pr: enhancement

#13558 Remove self-referential link to Overdrive
  packs/actions/overdrive.json
Labels: pr: data update

#13562 Add icons to some equipment
  packs/equipment/affinity-stones.json
  packs/equipment/cube-of-force.json
  packs/equipment/highhelm-drill-mark-i.json
  packs/equipment/highhelm-drill-mark-ii.json
  packs/equipment/highhelm-drill-mark-iii.json
  packs/equipment/smugglers-sack-type-i.json
  packs/equipment/smugglers-sack-type-ii.json
  packs/equipment/smugglers-sack-type-iii.json
  packs/equipment/smugglers-sack-type-iv.json
  packs/equipment/smugglers-sack-type-v.json
  packs/equipment/tome-of-scintillating-sleet.json
Labels: pr: data update

#13560 Make available roll options of effect origins' originating items
  src/module/actor/base.ts
  src/module/chat-message/data.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/effect/document.ts
  src/module/item/spell/document.ts
  src/scripts/system/dragstart-handler.ts
Labels: pr: enhancement

#13559 Fix formatting in Air Domain journal
  packs/journals/domains.json
Labels: pr: data update

#13564 Make `origin.rollOptions` flag property optional
  src/module/item/abstract-effect/data.ts
  src/module/item/abstract-effect/document.ts
Labels: pr: bugfix

#13567 Add Faerie Fire to Remaster Changes Journal
  packs/journals/remaster-changes.json
Labels: pr: data update

#13566 Add effect roll options with check context data
  src/module/item/abstract-effect/document.ts
Labels: pr: enhancement

#13570 replace level by rank in summerland spell desc
  packs/spells/summerland-spell.json
Labels: pr: data update

#13569 Replace spell level by rank in Imprisonment spell
  packs/spells/imprisonment.json
Labels: pr: data update

#13571 Fix automation for Man-Feller
  packs/crown-of-the-kobold-king-bestiary/king-merlokrep.json
  packs/equipment/man-feller.json
Labels: pr: data update

#13577 Only reduce labels in REs if identical to parent name
  src/module/rules/rule-element/base.ts
  static/lang/re-en.json
Labels: pr: bugfix

#13578 Add `getName` method to `DelegatedCollection`
  src/util/delegated-collection.ts
Labels: pr: enhancement

#13583 Remove duplicate handler for toggling of versatile weapon traits
  src/module/actor/character/sheet.ts
Labels: pr: bugfix

#13579 If possible, avoid re-IDing subitems when attaching/detaching
  src/module/apps/item-attacher.ts
  src/module/item/physical/helpers.ts
Labels: pr: bugfix

#13580 Accommodate subitems in certain rule elements
  src/module/rules/rule-element/adjust-strike.ts
  src/module/rules/rule-element/grant-item/helpers.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: bugfix

#13582 Change Nature's Bounty damage kind to healing
  packs/spells/natures-bounty.json
Labels: pr: data update

#13576 Brush up automation of Enlarged Chassis and Scion Transformation
  packs/feats/enlarged-chassis.json
  packs/feats/scion-transformation.json
Labels: pr: data update

#13586 Fix Summon Healing Servitor to be both damage and healing and add effect
  packs/spell-effects/spell-effect-summon-healing-servitor.json
  packs/spells/summon-healing-servitor.json
  packs/spells/vitality-lash.json
Labels: pr: data update

#13585 Extend archer archetype feat support to weapons in crossbow group
  packs/feats/archer-dedication.json
  packs/feats/archers-aim.json
  packs/feats/quick-shot.json
  packs/feats/staggering-fire.json
Labels: pr: data update

#13561 Move general amp-related REs to Psi Cantrips and Amps class feature
  packs/classfeatures/conscious-mind.json
  packs/classfeatures/psi-cantrips-and-amps.json
Labels: pr: data update

#13523 Add light automation and effect for Ghost Lantern
  packs/equipment-effects/effect-ghost-lantern.json
  packs/equipment/ghost-lantern.json
Labels: pr: data update

#13587 Correct duration for Soothing Words to match Player Core
  packs/spell-effects/spell-effect-soothing-words.json
  packs/spells/soothing-words.json
Labels: pr: data update

#13588 Add effect for Hallowed Ground
  packs/spell-effects/spell-effect-hallowed-ground.json
  packs/spells/hallowed-ground.json
Labels: pr: data update

#13591 Add note to Serpent Dagger
  packs/equipment/serpent-dagger.json
  static/lang/re-en.json
Labels: pr: data update

#13592 Attempt to guess whether spells are melee/ranged and set roll options
  src/module/actor/base.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/spell/document.ts
Labels: pr: enhancement

#13594 Fix occultism value for Weight of Experience
  packs/feats/weight-of-experience.json
Labels: pr: data update

#13595 Fix Shredskin immunity to critical hits (except slashing)
  packs/agents-of-edgewatch-bestiary/shredskin.json
  packs/book-of-the-dead-bestiary/shredskin.json
Labels: pr: data update

#13590 Emit unrecognized damage type on Strike RE validation failure
  src/module/rules/rule-element/strike.ts
Labels: pr: enhancement

#13536 Finish Psychic amp and spell modifications
  packs/classfeatures/the-distant-grasp.json
  packs/classfeatures/the-oscillating-wave.json
  packs/spell-effects/spell-effect-glimpse-weakness.json
  packs/spell-effects/spell-effect-guidance.json
  static/lang/re-en.json
Labels: pr: data update

#13598 Fix item alterations applying to all spells when loading spell variants
  src/module/item/spell/document.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: bugfix

#13599 Prevent usage select from appearing in treasure-sheet sidebar
  packs/equipment/small-cold-iron-cauldron-with-onyx.json
  packs/equipment/splendid-lyre-of-world-famous-lyrist.json
  src/module/migration/migrations/905-unpersist-usage.ts
  static/templates/items/physical-sidebar.hbs
Labels: pr: bugfix

#13597 Add custom immunity for Smog Giant
  packs/outlaws-of-alkenstar-bestiary/smog-giant.json
  static/lang/re-en.json
Labels: pr: data update

#13596 Brush up Darkside Mirrors
  packs/extinction-curse-bestiary/imperious-darkside-mirror.json
  packs/fists-of-the-ruby-phoenix-bestiary/dimensional-darkside-mirror.json
  packs/hazards/darkside-mirror.json
Labels: pr: data update

#13601 Import by type in @actor/base.ts where possible
  src/module/actor/base.ts
Labels: pr: housekeeping, pr: refactor

#13603 Replace some system icons with identical core copies, adjust others
  packs/equipment/air-repeater.json
  packs/equipment/blowgun-darts.json
  packs/equipment/long-air-repeater.json
  static/icons/equipment/consumables/ammunition/blowgun-darts.webp
  static/icons/equipment/weapons/dueling-pistol.webp
  static/icons/features/classes/devise-a-stratagem.webp
  static/icons/features/classes/gunslinger-weapon-mastery.webp
  static/icons/spells/angelic-wings.webp
Labels: pr: data update, pr: static assets

#13605 Add icon for crackling bubblegum
  packs/actions/overdrive.json
  packs/classes/psychic.json
  packs/equipment-effects/effect-crackling-bubble-gum-failure.json
  packs/equipment-effects/effect-crackling-bubble-gum.json
  packs/equipment/crackling-bubble-gum-greater.json
  packs/equipment/crackling-bubble-gum-lesser.json
  packs/equipment/crackling-bubble-gum-major.json
  packs/equipment/crackling-bubble-gum-moderate.json
  static/icons/equipment/consumables/other-consumables/crackling-bubblegum.webp
Labels: pr: data update, pr: static assets

#13606 Release Notes 5.13.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#13612 Select better icons for Subconscious Suggestion and Share Lore
  packs/agents-of-edgewatch-bestiary/miogimo.json
  packs/agents-of-edgewatch-bestiary/zealborn.json
  packs/blood-lords-bestiary/rumin-purgo.json
  packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
  packs/fists-of-the-ruby-phoenix-bestiary/gumiho.json
  packs/gatewalkers-bestiary/equendia.json
  packs/kingmaker-bestiary/castruccio-irovetti.json
  packs/kingmaker-bestiary/ngara.json
  packs/kingmaker-bestiary/quintessa-maray.json
  packs/monsters-of-myth-bestiary/kallas-devil.json
  packs/night-of-the-gray-death-bestiary/conqueror-worm.json
  packs/pathfinder-bestiary-2/chernobue.json
  packs/pathfinder-bestiary-2/gosreg.json
  packs/pathfinder-bestiary-2/spirit-naga.json
  packs/pathfinder-bestiary-2/worm-that-walks-cultist.json
  packs/pathfinder-bestiary-3/adult-sovereign-dragon-spellcaster.json
  packs/pathfinder-bestiary-3/ancient-sovereign-dragon-spellcaster.json
  packs/season-of-ghosts-bestiary/argyrzei.json
  packs/season-of-ghosts-bestiary/hong-meigui.json
  packs/shadows-at-sundown-bestiary/scarlet-walker.json
  packs/spells/share-lore.json
  packs/spells/subconscious-suggestion.json
  packs/stolen-fate-bestiary/kannijo.json
  packs/strength-of-thousands-bestiary/king-of-biting-ants.json
Labels: pr: data update

#13616 Fix resolving `diceNumber` overrides
  src/module/rules/rule-element/damage-dice.ts
Labels: pr: bugfix

#13610 Add missing amp automation for Daze and fix Ignition's amp scaling
  packs/classfeatures/the-oscillating-wave.json
  packs/classfeatures/the-silent-whisper.json
Labels: pr: data update

#13618 Replace lower-resolution system icons with identical core icons
  packs/bestiary-effects/effect-dust-eternal.json
  packs/bestiary-effects/effect-no-quarter.json
  packs/bestiary-effects/effect-pinpoint-weakness.json
  packs/equipment/cassock-of-devotion.json
  packs/equipment/corruption-cassock.json
  packs/equipment/elegant-cloth-doll.json
  packs/feat-effects/effect-aldori-parry.json
  packs/feat-effects/stance-paragons-guard.json
  packs/kingmaker-bestiary/aldori-sister.json
  packs/kingmaker-bestiary/jamandi-aldori.json
  packs/pfs-season-4-bestiary/determined-dura-1-2.json
  packs/pfs-season-4-bestiary/determined-dura-3-4.json
  packs/pfs-season-4-bestiary/determined-halran-1-2.json
  packs/pfs-season-4-bestiary/determined-halran-3-4.json
  packs/pfs-season-4-bestiary/determined-rhenei-1-2.json
  packs/pfs-season-4-bestiary/determined-rhenei-3-4.json
  packs/pfs-season-4-bestiary/determined-thisnabel-1-2.json
  packs/pfs-season-4-bestiary/determined-thisnabel-3-4.json
  packs/pfs-season-4-bestiary/dura-1-2.json
  packs/pfs-season-4-bestiary/dura-3-4.json
  packs/pfs-season-4-bestiary/halran-1-2.json
  packs/pfs-season-4-bestiary/halran-3-4.json
  packs/pfs-season-4-bestiary/rhenei-1-2.json
  packs/pfs-season-4-bestiary/rhenei-3-4.json
  packs/pfs-season-4-bestiary/thisnabel-1-2.json
  packs/pfs-season-4-bestiary/thisnabel-3-4.json
  packs/rollable-tables/11th-level-permanent-items.json
  packs/rollable-tables/minor-art-object.json
  packs/spells/control-sand.json
  packs/spells/heroic-feat.json
Labels: pr: data update

#13607 Fill in miscellaneous type gaps
  types/foundry/client/application/sidebar/sidebar.d.ts
  types/foundry/client/core/hooks.d.ts
  types/foundry/client/pixi/board.d.ts
Labels: pr: types update

#13619 Fix missing versatile piercing for Bestial Manifestation claw attack
  packs/feats/bestial-manifestation.json
Labels: pr: data update

#13620 Release Notes 5.13.4
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#13623 Remove redundant retrieval of actor in `getCheckDC` inline roll links helper
  src/module/system/text-editor.ts
Labels: pr: bugfix

#13626 Fix sources of Season of Ghosts rituals
  packs/spells/destroy-mindscape.json
  packs/spells/mindscape-shift.json
Labels: pr: data update

#13628 Automate Parallel Breakthrough feat
  packs/feats/parallel-breakthrough.json
  static/lang/re-en.json
Labels: pr: data update

#13630 Fix rank of base spellcasting proficiency and innate spells
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
Labels: pr: bugfix

#13632 Add missing area to Safe Passage description
  packs/spells/safe-passage.json
Labels: pr: data update

#13627 Fix variable-cost action glyphs in Spell Compendium
  src/module/apps/compendium-browser/tabs/spell.ts
Labels: pr: bugfix

#13635 Fix skirmisher army level
  packs/kingmaker-bestiary/armies/basic-skirmishers.json
Labels: pr: data update, kingmaker

#13643 Remove ability to directly edit spellcasting proficiency from proficiencies tab
  static/templates/actors/character/tabs/proficiencies.hbs
Labels: ui/ux

#13639 Fix prerequisites for Rallying Anthem remaster
  packs/feats/defensive-coordination.json
  packs/feats/martial-performance.json
  packs/feats/rallying-anthem.json
  packs/feats/shared-assault.json
  packs/iconics/lem-level-1.json
Labels: pr: data update, remaster

#13644 Remove ability to directly edit proficiencies in spellcasting tab
  static/templates/actors/character/tabs/spellcasting.hbs
Labels: ui/ux

#13640 Remove management of spell proficiency from spellcasting entries
  src/module/item/spellcasting-entry/document.ts
Labels: pr: refactor

#12197 Add kingmaker Appendix Armies and show usable tactics in actions lists
  packs/kingmaker-bestiary/armies/basic-skirmishers.json
  packs/kingmaker-bestiary/armies/greengripe-bombardiers.json
  packs/kingmaker-bestiary/armies/lizardfolk-defenders.json
  packs/kingmaker-bestiary/armies/mbotuu-frog-riders.json
  packs/kingmaker-bestiary/armies/nomen-scouts.json
  packs/kingmaker-bestiary/armies/sootscale-warriors.json
  packs/kingmaker-bestiary/armies/tiger-lord-berserkers.json
  src/module/actor/army/sheet.ts
  src/styles/actor/army/_index.scss
  static/templates/actors/army/sheet.hbs
Labels: pr: data entry, ui/ux, kingmaker

#13647 Fix bonus type for Nourishing Gate
  packs/feats/nourishing-gate.json
Labels: pr: data update

#13645 Fix application of precision resistance
  src/module/system/damage/helpers.ts
  src/module/system/damage/iwr.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
Labels: pr: bugfix

#13649 Clean up enriched HTML in Splinter Faith
  packs/feats/splinter-faith.json
Labels: pr: data update

#13651 Update Luck Blade descriptions
  packs/equipment/luck-blade-wishing.json
  packs/equipment/luck-blade.json
  packs/rollable-tables/17th-level-permanent-items.json
  packs/rollable-tables/19th-level-permanent-items.json
Labels: pr: data update

#13650 Fix sticky bomb applying when not toggled, account for expanded splash
  packs/feats/sticky-bomb.json
  src/module/actor/helpers.ts
Labels: pr: data update

#13648 Pass along indication that persistent damage came from a critical hit
  src/module/actor/base.ts
  src/module/item/condition/data.ts
  src/module/item/condition/document.ts
  src/module/system/damage/iwr.ts
Labels: pr: bugfix

#13652 Clean up enriched HTML in Shatter Mind
  packs/spells/shatter-mind.json
Labels: pr: data update

#13654 Remove double "of" in Spawn Wight Soldier description
  packs/book-of-the-dead-bestiary/wight-commander.json
  packs/pfs-season-4-bestiary/elite-smokesight-wight-commander.json
  packs/pfs-season-4-bestiary/smokesight-wight-commander.json
Labels: pr: data update

#13655 Release Notes 5.13.5
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#13657 Fix level in thoughtform summoning
  static/lang/re-en.json
Labels: pr: data update

#13653 Clean up enriched HTML in Pitax Horde
  packs/kingmaker-bestiary/armies/pitax-horde.json
Labels: pr: data update, kingmaker

#13663 Disallow NPC attack traits from being added to weapons from sheets
  src/module/item/weapon/sheet.ts
Labels: pr: bugfix

#13669 Fix non-hero point rerolls
  src/module/system/check/check.ts
Labels: pr: bugfix

#13672 Add roll links to Hide and Sneak actions
  packs/actions/hide.json
  packs/actions/sneak.json
Labels: pr: data update, remaster

#13665 Fix inclusion of crossbows in Singular Expertise
  packs/classfeatures/singular-expertise.json
Labels: pr: data update

#13673 Release Notes 5.13.6
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping
