Repository foundryvtt/pf2e, pull requests merged in 2024-05, with the labels that each got.

#14563 Fix typo in Artisan's Toolkit description
  packs/equipment/artisans-toolkit.json
Labels: pr: data update

#14567 Fix duration of Guided by the Stars effect
  packs/feat-effects/effect-guided-by-the-stars.json
Labels: pr: data update

#14558 Do not show megaton strike toggle for construct innovation inventors
  packs/feats/megaton-strike.json
Labels: pr: data update

#14554 Add missing Monster Core Trample Strikes
  packs/pathfinder-monster-core/mukradi.json
  packs/pathfinder-monster-core/rhinoceros.json
  packs/pathfinder-monster-core/woolly-rhinoceros.json
Labels: pr: data update

#14557 Fix some stringified values
  packs/abomination-vaults-bestiary/dread-wisp.json
  packs/abomination-vaults-bestiary/dune-candle.json
  packs/abomination-vaults-bestiary/groetan-candle.json
  packs/abomination-vaults-bestiary/sacuishu.json
  packs/abomination-vaults-bestiary/spellvoid.json
  packs/abomination-vaults-bestiary/will-o-the-deep.json
  packs/agents-of-edgewatch-bestiary/gloaming-will-o-wisp.json
  packs/bestiary-effects/effect-fiery-form.json
  packs/bestiary-effects/effect-nanite-surge-glow.json
  packs/deities/srikalis-sritaming-and-sribaril.json
  packs/equipment/false-death.json
  packs/equipment/ghost-scarf.json
  packs/equipment/skyfang-crystal.json
  packs/feat-effects/effect-nanite-surge.json
  packs/hazards/perilous-flash-flood.json
  packs/heritages/fetchling/bright-fetchling.json
  packs/kingmaker-bestiary/ancient-wisp.json
  packs/kingmaker-bestiary/spirit-of-stisshak.json
  packs/pathfinder-bestiary/will-o-wisp.json
  packs/pathfinder-monster-core/vidileth.json
  packs/pathfinder-monster-core/will-o-wisp.json
  packs/pfs-season-2-bestiary/urkhas-3-4.json
  packs/pfs-season-2-bestiary/urkhas-5-6.json
  packs/spells/scorching-blast.json
Labels: pr: data update

#14559 Fix ChoiceSet labels for Effect: Deck of Destiny and Effect: Recall Under Pressure
  packs/actions/recall-under-pressure.json
  packs/equipment-effects/effect-deck-of-destiny.json
  packs/feat-effects/effect-recall-under-pressure.json
Labels: pr: data update

#14566 Add missing ability names to a couple of Abominations Vaults characters
  packs/abomination-vaults-bestiary/salaisa-malthulas.json
  packs/abomination-vaults-bestiary/wrin-sivinxi.json
Labels: pr: data update

#14544 Brush Up of action Familiar Focus
  packs/familiar-abilities/familiar-focus.json
Labels: pr: data update

#14568 Update the description of Avatar
  packs/spells/avatar.json
Labels: pr: data update

#14570 Fix token config `Infinity` warning
  src/module/canvas/perception/point-vision-source.ts
  src/module/scene/token-document/data.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix, pr: foundry v12

#14579 Run predicates on choice sets options loaded from a path
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: enhancement

#14571 Fix some minor description errors
  packs/abomination-vaults-bestiary/shanrigol-heap.json
  packs/fists-of-the-ruby-phoenix-bestiary/elder-cauthooj.json
  packs/pathfinder-bestiary-2/froghemoth.json
  packs/pathfinder-bestiary/cauthooj.json
  packs/pathfinder-bestiary/shuln.json
  packs/pfs-season-3-bestiary/shanrigol-mound.json
Labels: pr: data update

#14578 Add inline Intimidation check to Spiritual Disruptor
  packs/season-of-ghosts-bestiary/spiritual-disruptor.json
Labels: pr: data update

#14577 Fix ignored choicesets not disabling other rule elements
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#14569 Finish up converting deprecated handlebars helpers
  src/module/item/base/sheet/rule-element-form/flat-modifier.ts
  src/module/item/deity/sheet.ts
  src/module/item/effect/sheet.ts
  src/module/item/feat/sheet.ts
  src/module/item/spell/sheet.ts
  src/module/scene/sheet.ts
  static/templates/items/deity-details.hbs
  static/templates/items/effect-sidebar.hbs
  static/templates/items/feat-details.hbs
  static/templates/items/rules/flat-modifier.hbs
  static/templates/items/rules/partials/resolvable-value.hbs
  static/templates/items/rules/token-image.hbs
  static/templates/items/rules/token-light.hbs
  static/templates/items/spell-details.hbs
  static/templates/items/spell-overlay.hbs
  static/templates/scene/sheet-partials.hbs
  static/templates/scene/token/partials/appearance.hbs
  static/templates/scene/token/partials/lighting.hbs
Labels: pr: foundry v12

#14583 Prevent players from controlling (selecting) lootable tokens
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#14581 Fix centering for wrapped text in prerequisites and spellcasting
  src/styles/actor/_spell-collection.scss
  src/styles/actor/_spell-preparation.scss
  src/styles/item/_feat-sheet.scss
  src/styles/item/_sidebar.scss
Labels: ui/ux

#14585 Restore target marks for ephemerals, and include both origin and target marks
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#14586 Remove familiar from former master on change
  src/module/actor/familiar/document.ts
Labels: pr: bugfix

#14451 Show effect badge label in message when formula is rolled
  src/module/item/effect/document.ts
Labels: pr: enhancement

#14580 Restore surface cantrips for Psi Development archetype psychics
  packs/classfeatures/the-distant-grasp.json
  packs/classfeatures/the-infinite-eye.json
  packs/classfeatures/the-oscillating-wave.json
  packs/classfeatures/the-silent-whisper.json
  packs/classfeatures/the-tangible-dream.json
  packs/classfeatures/the-unbound-step.json
Labels: pr: data update

#14590 Add necessary types for `ProseMirror` dropdown extensions
  types/foundry/client/core/hooks.d.ts
  types/foundry/client/foundry/index.d.ts
  types/foundry/common/prosemirror/dropdown.d.ts
  types/foundry/common/prosemirror/menu.d.ts
  types/foundry/common/prosemirror/module.d.ts
  types/foundry/common/prosemirror/plugin.d.ts
  types/foundry/scripts/prose-mirror.d.ts
Labels: pr: types update, pr: foundry v12

#14591 Fix `TokenLayerPF2e#cycleStack`
  src/module/canvas/layer/token.ts
  src/module/canvas/status-effects.ts
Labels: pr: foundry v12

#14592 (In3luki) Move ChatMessagePF2e appliedDamage flag to system data
  src/module/actor/base.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/data.ts
  src/module/chat-message/document.ts
  types/foundry/common/documents/chat-message.d.ts
Labels: pr: refactor, pr: foundry v12

#14428 Include travel speed rates in party sheet
  src/module/actor/party/sheet.ts
  src/styles/actor/party/_index.scss
  src/styles/actor/party/_inventory.scss
  static/lang/en.json
  static/templates/actors/party/regions/exploration.hbs
Labels: pr: enhancement, ui/ux

#14594 Handle disabled RollOption toggles when merged
  src/module/rules/rule-element/roll-option/rule-element.ts
Labels: pr: bugfix

#14593 Process user visibility and register inline roll links for expanded descriptions
  src/module/chat-message/listeners/cards.ts
Labels: pr: bugfix

#14595 Avoid always revealing actor name for inline rolls of hazard routines
  src/module/system/damage/damage.ts
  src/module/system/text-editor.ts
Labels: pr: bugfix

#14596 Propagate real inline damage traits like holy to item:trait:X options to support IWR
  src/module/system/text-editor.ts
Labels: pr: bugfix

#14597 Allow duplicates of a linked actor to flank amongst themselves
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#14600 Revert setting `Document#_stats#coreVersion` in the pack builder
  build/lib/compendium-pack.ts
Labels: pr: foundry v12

#14603 Normalize search queries with diacritics in compendium sidebar and browser
  src/module/apps/compendium-browser/tabs/base.ts
  src/module/apps/sidebar/compendium-directory.ts
  types/foundry/client/core/searchfilter.d.ts
Labels: pr: enhancement

#14605 Fix use consumable label
  src/module/actor/npc/document.ts
  src/module/chat-message/listeners/cards.ts
Labels: localization, pr: bugfix

#14609 Add damage traits to armor and shield traits
  src/scripts/config/traits.ts
Labels: pr: data update

#14602 Fix order of Argyrzei's Silver Blade damage partials
  packs/season-of-ghosts-bestiary/argyrzei.json
Labels: pr: data update

#14608 Add inline damage roll to Algriever Venom
  packs/season-of-ghosts-bestiary/algriever.json
Labels: pr: data update

#14607 Add inline Diplomacy check to No Cause For Alarm
  packs/feats/no-cause-for-alarm.json
  packs/paizo-pregens/jadren-tagar.json
Labels: pr: data update

#14589 Fix Devourer's Devour Soul save DC
  packs/abomination-vaults-bestiary/beluthus.json
  packs/pathfinder-bestiary-2/devourer.json
Labels: pr: data update

#14610 Update Forbidding Ward to use a TokenMark rather than a RollOption toggle
  packs/spell-effects/spell-effect-forbidding-ward.json
Labels: pr: data update

#14606 Add unified effect for Tempest Form
  packs/spell-effects/spell-effect-tempest-form.json
  packs/spells/tempest-form.json
  static/lang/re-en.json
Labels: pr: data update

#14612 Fix name of Shadow of Sezruth
  packs/pfs-season-5-bestiary/shadow-of-sezruth.json
Labels: pr: data update

#14611 Release Notes 5.15.2
  CHANGELOG.md
Labels: pr: housekeeping

#14613 Update system version in manifest to 5.15.2
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14617 Fix spell description being centered
  src/styles/actor/_spell-collection.scss
  src/styles/actor/_spell-preparation.scss
Labels: pr: bugfix

#14624 Grant spellcasting proficiency to Monks with Ki Spells
  packs/classes/monk.json
  packs/classfeatures/graceful-legend.json
  packs/classfeatures/ki-spells.json
  packs/classfeatures/monk-expertise.json
  packs/journals/archetypes.json
  packs/spells/abundant-step.json
  packs/spells/clinging-shadows-stance.json
  packs/spells/empty-body.json
  packs/spells/ki-blast.json
  packs/spells/ki-form.json
  packs/spells/ki-rush.json
  packs/spells/ki-strike.json
  packs/spells/medusas-wrath.json
  packs/spells/quivering-palm.json
  packs/spells/shadows-web.json
  packs/spells/wholeness-of-body.json
  packs/spells/wild-winds-stance.json
  packs/spells/wind-jump.json
  packs/spells/wronged-monks-wrath.json
Labels: pr: data update

#14627 Revert "Move ChatMessagePF2e appliedDamage flag to system data"
  src/module/actor/base.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/data.ts
  src/module/chat-message/document.ts
  types/foundry/common/documents/chat-message.d.ts
Labels: pr: foundry v12

#14626 Add missing amp damage for Redistribute Potential
  packs/classfeatures/the-oscillating-wave.json
Labels: pr: data update

#14632 Fix minor typo on Ritualist archetype's journal entry
  packs/journals/archetypes.json
Labels: pr: data update

#14635 Set spellcasting proficiency to trained if at least one entry exists
  src/module/actor/creature/document.ts
Labels: pr: bugfix

#14649 Fix highlighting for cone and custom circle templates
  src/module/canvas/helpers.ts
  src/module/canvas/layer/template.ts
  src/module/canvas/measured-template.ts
  types/foundry/client/pixi/layers/base/placeables-layer.d.ts
Labels: pr: foundry v12

#14647 Start on some of the type changes for 12.321
  types/foundry/client-esm/applications/elements/prosemirror-editor.d.ts
  types/foundry/client-esm/applications/elements/string-tags.d.ts
  types/foundry/client-esm/canvas/edges/edge.d.ts
  types/foundry/client-esm/canvas/sources/base-light-source.d.ts
  types/foundry/client-esm/canvas/sources/rendered-effect-source.d.ts
  types/foundry/client/config.d.ts
  types/foundry/client/data/documents/combat.d.ts
  types/foundry/client/pixi/board.d.ts
  types/foundry/client/pixi/core/interaction/mouse-handler.d.ts
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/layers/base/interaction-layer.d.ts
  types/foundry/client/pixi/layers/controls/ruler.d.ts
Labels: pr: types update, pr: foundry v12

#14645 Fix triggerbrand salvo prerequisites
  packs/feats/triggerbrand-salvo.json
Labels: pr: data update

#14644 Fix malevolent mannequins description
  packs/hazards/malevolent-mannequins.json
Labels: pr: data update

#14643 Fix Harlo Krant's bag of holding
  packs/book-of-the-dead-bestiary/harlo-krant.json
Labels: pr: data update

#14650 Remove prerequisites from Ghost Hunter Dedication description
  packs/feats/ghost-hunter-dedication.json
Labels: pr: data update

#14654 Fix traditions of Cursed Metamorphosis
  packs/pathfinder-monster-core/cuckoo-hag.json
  packs/pathfinder-monster-core/dryad-queen.json
  packs/pathfinder-monster-core/fortune-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/fortune-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/gongorinan.json
  packs/pathfinder-monster-core/iron-hag.json
  packs/pathfinder-monster-core/keketar.json
  packs/pathfinder-monster-core/norn.json
  packs/pathfinder-monster-core/sea-hag.json
  packs/pathfinder-monster-core/sweet-hag.json
  packs/seven-dooms-for-sandpoint-bestiary/kaleb-valdemars-body.json
  packs/seven-dooms-for-sandpoint-bestiary/tiluatchek.json
  packs/spells/cursed-metamorphosis.json
Labels: pr: data update

#14637 Extend sidebar compendium search to support Babele originalName
  src/module/apps/sidebar/compendium-directory.ts
Labels: pr: enhancement

#14662 Lock configuration of certain core grid settings
  src/scripts/hooks/index.ts
  src/scripts/hooks/ready.ts
  src/scripts/hooks/render-settings-config.ts
  static/lang/en.json
  types/foundry/client/core/hooks.d.ts
Labels: pr: foundry v12

#14665 Add missing skills for some NPCs
  packs/pfs-season-5-bestiary/acrid-corrosive-slime.json
  packs/pfs-season-5-bestiary/corrosive-slime.json
Labels: pr: data update

#14652 Add Hero Point Deck effects
  packs/journals/hero-point-deck.json
  packs/other-effects/effect-ancestral-might.json
  packs/other-effects/effect-aura-of-protection.json
  packs/other-effects/effect-called-foe.json
  packs/other-effects/effect-catch-your-breath.json
  packs/other-effects/effect-class-might.json
  packs/other-effects/effect-critical-moment.json
  packs/other-effects/effect-daring-attempt.json
  packs/other-effects/effect-desperate-swing.json
  packs/other-effects/effect-endure-the-onslaught.json
  packs/other-effects/effect-fluid-motion.json
  packs/other-effects/effect-impossible-shot.json
  packs/other-effects/effect-rage-and-fury.json
  packs/other-effects/effect-spark-of-courage.json
  packs/other-effects/effect-strike-true.json
  static/lang/re-en.json
Labels: pr: data update

#14661 Improve automation of Strix flight feats
  packs/feat-effects/effect-juvenile-flight.json
  packs/feats/fledgling-flight.json
  packs/feats/fully-flighted.json
Labels: pr: data update

#14669 Restore floaty text for sheet updates
  src/module/actor/base.ts
Labels: pr: foundry v12

#14670 Update character _preUpdate logic for v12
  src/module/actor/character/document.ts
Labels: pr: foundry v12

#14672 Update `FamiliarPF2e#_preUpdate´ and the `normalizeActionChangeData` helper for v12
  src/module/actor/familiar/document.ts
  src/module/item/ability/helpers.ts
Labels: pr: foundry v12

#14671 Add PF2e menu to prosemirror editor
  package-lock.json
  package.json
  src/module/item/base/sheet/sheet.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/prosemirror-menu.ts
  types/foundry/client/apps/form.d.ts
  types/foundry/common/prosemirror/menu.d.ts
  types/foundry/common/prosemirror/module.d.ts
  types/foundry/common/prosemirror/plugin.d.ts
  types/foundry/scripts/prose-mirror.d.ts
Labels: pr: foundry v12

#14659 Fix spell heighten rank for npcs above level 20
  src/module/item/spell/document.ts
Labels: pr: bugfix

#14675 Update spell update/create cleanup
  src/module/item/spell/document.ts
Labels: pr: foundry v12

#14676 Rerender token vision when RBV setting is changed
  src/module/scene/sheet.ts
  src/module/system/settings/automation.ts
  static/templates/scene/sheet-partials.hbs
Labels: pr: bugfix, pr: foundry v12

#14677 Show prepared values instead of source in token config when RBV is enabled
  src/module/scene/helpers.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
Labels: pr: enhancement, pr: foundry v12

#14686 Reduce impact of RBV's darkvision brightening to default settings
  src/module/canvas/perception/modes.ts
Labels: pr: enhancement, pr: foundry v12

#14683 Fix Tekko-Kagi casing in Base Weapon List
  static/lang/en.json
Labels: pr: data update

#14685 Correct text of Injection Trait
  static/lang/en.json
Labels: pr: data update

#14684 Fix save type for Sprinkle Pixie Dust
  packs/feats/fledgling-flight.json
  packs/pfs-season-5-bestiary/enraged-firmagor.json
  packs/pfs-season-5-bestiary/firmagor.json
  packs/wardens-of-wildwood-bestiary/izurran.json
  packs/wardens-of-wildwood-bestiary/shadebound-pixie-guard.json
  packs/wardens-of-wildwood-bestiary/sylvarindarian.json
Labels: pr: data update

#14682 Add Secondary Casters to Consecrate
  packs/spells/consecrate.json
Labels: pr: data update

#14681 Add AE-Like to Bort's Blessing for Language
  packs/equipment/borts-blessing.json
Labels: pr: data update

#14689 Add traits to Vorpal Rune's inline save
  packs/equipment/vorpal.json
  static/lang/en.json
Labels: pr: data update

#14690 Improve prosemirror dropdown menu
  src/module/actor/sheet/base.ts
  src/module/item/base/sheet/sheet.ts
  src/module/journal-entry/sheet.ts
  src/module/system/prosemirror-menu.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/prosemirror-menu.ts
  types/foundry/common/prosemirror/menu.d.ts
  types/foundry/common/utils/helpers.d.ts
  types/foundry/scripts/prose-mirror.d.ts
Labels: pr: enhancement, pr: foundry v12

#14688 Release Notes 6.0.0-beta1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping, pr: foundry v12

#14695 Add effect for Hand of the Apprentice
  packs/spell-effects/spell-effect-hand-of-the-apprentice.json
  packs/spells/hand-of-the-apprentice.json
Labels: pr: data update

#14701 Refresh copies of Hand of the Apprentice
  packs/agents-of-edgewatch-bestiary/grabble-forden.json
  packs/blog-bestiary/morlibint.json
  packs/fists-of-the-ruby-phoenix-bestiary/mage-of-many-styles.json
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/quest-for-the-frozen-flame-bestiary/ardissa-prendergant.json
  packs/sky-kings-tomb-bestiary/bronwyl-holloward.json
  packs/spell-effects/spell-effect-hand-of-the-apprentice.json
  packs/spells/consecrate.json
  packs/spells/hand-of-the-apprentice.json
Labels: pr: data update

#14700 Restore blank select option to weapon sheet range dropdown
  static/templates/items/weapon-details.hbs
Labels: pr: bugfix, pr: foundry v12

#14697 Add automation for the Mechanical Symbiosis background
  packs/backgrounds/mechanical-symbiosis.json
  static/lang/re-en.json
Labels: pr: data update

#14705 Avoid canvas error when creating a world for the first time
  src/scripts/hooks/ready.ts
Labels: pr: bugfix, pr: foundry v12

#14707 Fix character sheet biographies and use prosemirror in character, npc, and hazard sheets
  src/module/actor/hazard/sheet.ts
  src/styles/actor/character/_biography.scss
  src/styles/actor/hazard/_index.scss
  src/styles/actor/npc/_index.scss
  src/styles/item/_index.scss
  static/templates/actors/character/tabs/biography.hbs
  static/templates/actors/hazard/sheet.hbs
  static/templates/actors/npc/simple-sheet.hbs
  static/templates/actors/npc/tabs/notes.hbs
Labels: pr: enhancement, ui/ux, pr: foundry v12

#14715 Fix missing splash trait
  packs/equipment/defoliation-bomb-greater.json
  packs/equipment/defoliation-bomb-lesser.json
  packs/equipment/defoliation-bomb-major.json
  packs/equipment/defoliation-bomb-moderate.json
  packs/spells/hedge-prison.json
  packs/wardens-of-wildwood-bestiary/bloodletting-snare.json
  packs/wardens-of-wildwood-bestiary/consuming-cabinet.json
  packs/wardens-of-wildwood-bestiary/eyelet-swarm.json
  packs/wardens-of-wildwood-bestiary/eyelet.json
  packs/wardens-of-wildwood-bestiary/khasprickle.json
  packs/wardens-of-wildwood-bestiary/luruvin.json
  packs/wardens-of-wildwood-bestiary/ogre-bully.json
  packs/wardens-of-wildwood-bestiary/punish-the-impertinent.json
  packs/wardens-of-wildwood-bestiary/putrifer.json
  packs/wardens-of-wildwood-bestiary/ruzadoyas-chosen.json
  packs/wardens-of-wildwood-bestiary/shadebound-pixie-guard.json
  packs/wardens-of-wildwood-bestiary/shadow-roil.json
  packs/wardens-of-wildwood-bestiary/shadow-sage.json
  packs/wardens-of-wildwood-bestiary/unaasi.json
Labels: pr: data update

#14713 Fix spell attack and DC for Faithless Ecclesiarch
  packs/book-of-the-dead-bestiary/faithless-ecclesiarch.json
Labels: pr: data update

#14716 Fix `PrototypeToken#texture#src` not being set correctly in `BaseActor#_preCreate`
  src/module/actor/base.ts
Labels: pr: bugfix, pr: foundry v12

#14714 Fix visibility of `hidden`, `undetected` or `unnoticed` tokens and ambient darkness luminosity in new scenes
  src/module/canvas/perception/modes.ts
  src/module/canvas/token/object.ts
  src/module/scene/document.ts
  types/foundry/client/pixi/perception/detection-mode.d.ts
Labels: pr: bugfix, pr: foundry v12

#14712 Changes nameAttr to valueAttr in TokenLight RE template
  static/templates/items/rules/token-light.hbs
Labels: pr: bugfix, pr: foundry v12

#14666 Fix several missing links in class features
  packs/classfeatures/blight-soul-deviant-classification.json
  packs/classfeatures/verdant-core-deviant-classification.json
Labels: pr: data update

#14718 (In3luki) Avoid prosemirror detecting inline header as h4
  src/module/system/prosemirror-menu.ts
Labels: pr: bugfix, pr: foundry v12

#14709 Continue to improve prosemirror dropdown menu
  src/module/actor/sheet/base.ts
  src/module/item/base/sheet/sheet.ts
  src/module/system/prosemirror-menu.ts
  src/styles/_globals.scss
  src/styles/mixins/_typography.scss
Labels: pr: enhancement, pr: foundry v12

#14723 Assign default skill ranks in data prep instead of template
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  static/template.json
Labels: pr: refactor, pr: foundry v12

#14722 Remove some unnecessary formatting of Deep Backgrounds and Archetypes journals
  packs/journals/archetypes.json
  packs/journals/deep-backgrounds.json
Labels: pr: data update

#14674 Add automation to Pitborn
  packs/feats/pitborn.json
  static/lang/re-en.json
Labels: pr: data update

#14732 Pull out base region types and shape data from #14728
  types/foundry/common/constants.d.ts
  types/foundry/common/data/data.d.ts
  types/foundry/common/documents/region-behavior.d.ts
  types/foundry/common/documents/region.d.ts
Labels: pr: types update, pr: foundry v12

#14733 Add `TypedSchemaField` type
  types/foundry/common/data/fields.d.ts
Labels: pr: types update, pr: foundry v12

#14739 Remove two Testing 3 workarounds
  src/module/actor/base.ts
  src/module/scene/document.ts
Labels: pr: foundry v12

#14737 Update types and system subclass of `ClientDatabaseBackend`
  src/module/system/client-backend.ts
  types/foundry/client/core/socket.d.ts
  types/foundry/client/data/abstract/client-backend.d.ts
  types/foundry/common/abstract/_types.d.ts
  types/foundry/common/abstract/backend.d.ts
  types/foundry/common/abstract/module.d.ts
  types/foundry/common/abstract/socket.d.ts
  types/foundry/common/types.d.ts
Labels: pr: foundry v12

#14741 Fix deterministic damage rolls
  src/module/system/damage/roll.ts
Labels: pr: bugfix, pr: foundry v12

#14743 Add some minor type updates for 12.323
  types/foundry/client-esm/applications/elements/document-tags.d.ts
  types/foundry/client-esm/applications/elements/form-element.d.ts
  types/foundry/client-esm/applications/elements/range-picker.d.ts
  types/foundry/client-esm/applications/elements/string-tags.d.ts
  types/foundry/client-esm/applications/forms/fields.d.ts
  types/foundry/client-esm/canvas/sources/point-darkness-source.d.ts
  types/foundry/client-esm/canvas/sources/point-vision-source.d.ts
  types/foundry/client/application/form-application/document-sheet/macro-config.d.ts
  types/foundry/client/apps/form.d.ts
  types/foundry/client/data/collections/scenes.d.ts
  types/foundry/client/pixi/board.d.ts
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/layers/base/interaction-layer.d.ts
  types/foundry/client/pixi/layers/effects/visibility.d.ts
  types/foundry/client/pixi/perception/vision-mode.d.ts
  types/foundry/client/pixi/placeable.d.ts
Labels: pr: types update, pr: foundry v12

#14745 Avoid padding and wrapping around GM Notes
  src/styles/item/_index.scss
Labels: ui/ux, pr: foundry v12

#14719 Release Notes 6.0.0-beta2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping, pr: foundry v12

#14730 Fix NPC copies of Meteor Swarm
  packs/age-of-ashes-bestiary/ilgreth.json
  packs/age-of-ashes-bestiary/mengkare.json
  packs/fists-of-the-ruby-phoenix-bestiary/mafika-ayuwari.json
  packs/kingmaker-bestiary/avatar-of-the-lantern-king.json
  packs/pathfinder-bestiary-2/bastion-archon.json
  packs/pathfinder-bestiary-2/lerritan.json
  packs/pathfinder-bestiary-3/elysian-titan.json
  packs/pathfinder-bestiary-3/hesperid-queen.json
  packs/pathfinder-bestiary-3/thanatotic-titan.json
  packs/pathfinder-bestiary/pit-fiend.json
  packs/stolen-fate-bestiary/obcisidaemon.json
  packs/strength-of-thousands-bestiary/unshadowed-haibram.json
Labels: pr: data update

#14736 Update Celestial Peach (Rejuvenation) to remove duplicate spells
  packs/equipment/celestial-peach-rejuvenation.json
Labels: pr: data update

#14740 Add creature trait descriptions from Monster Core
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#14747 Fix character biography h3 styling bleeding into content
  src/styles/actor/character/_biography.scss
Labels: ui/ux

#14744 Add compatible removed aasimar and tiefling feats as nephilim feats
  packs/feats/agathion-magic.json
  packs/feats/asura-magic.json
  packs/feats/beastbrood.json
  packs/feats/call-of-elysium.json
  packs/feats/celestial-strikes.json
  packs/feats/devil-in-plain-sight.json
  packs/feats/devilish-wiles.json
  packs/feats/dominion-aura.json
  packs/feats/emberkin.json
  packs/feats/faultspawn.json
  packs/feats/fiendish-strikes.json
  packs/feats/final-form.json
  packs/feats/finest-trick.json
  packs/feats/flame-jump.json
  packs/feats/garuda-magic.json
  packs/feats/garudas-squall.json
  packs/feats/healers-halo.json
  packs/feats/idol-threat.json
  packs/feats/idyllkin.json
  packs/feats/jalmeri-rakshasa-magic.json
  packs/feats/light-from-darkness.json
  packs/feats/plumekith.json
  packs/feats/purge-sins.json
  packs/feats/qlippoth-magic.json
  packs/feats/radiate-glory.json
  packs/feats/rakshasa-magic.json
  packs/feats/reveal-hidden-self.json
  packs/feats/riftmarked.json
  packs/feats/shackleborn.json
  packs/feats/towering-presence.json
  packs/feats/tranquil-sanctuary.json
  packs/feats/truespeech.json
  packs/feats/velstrac-magic.json
  packs/pathfinder-monster-core/phistophilus.json
  packs/season-of-ghosts-bestiary/heh-shan-bao-level-13.json
Labels: pr: data update

#14729 Add missing links to grapple action on several PFS NPCs
  packs/pfs-season-5-bestiary/blue-scarf-heavy.json
  packs/pfs-season-5-bestiary/blue-scarf-tough.json
  packs/pfs-season-5-bestiary/enraged-firmagor.json
  packs/pfs-season-5-bestiary/firmagor.json
Labels: pr: data update

#14720 Fix several minor typos in NPC abilities
  packs/pathfinder-bestiary/succubus.json
  packs/pathfinder-bestiary/terotricus.json
  packs/pathfinder-bestiary/will-o-wisp.json
  packs/pathfinder-monster-core/aeolaeka.json
  packs/pathfinder-monster-core/magma-worm.json
  packs/pathfinder-monster-core/python.json
  packs/pathfinder-monster-core/seraptis.json
  packs/pathfinder-monster-core/will-o-wisp.json
  packs/pathfinder-monster-core/xulgath-skulker.json
  packs/pathfinder-monster-core/yamaraj.json
Labels: pr: data update

#14748 Add unified effects for Emblazon Antimagic, Emblazon Armament, and Emblazon Energy
  packs/feat-effects/effect-emblazon-antimagic-weapon.json
  packs/feat-effects/effect-emblazon-antimagic.json
  packs/feat-effects/effect-emblazon-armament.json
  packs/feat-effects/effect-emblazon-energy.json
  packs/feats/emblazon-antimagic.json
  packs/feats/emblazon-armament.json
  packs/feats/emblazon-energy.json
  static/lang/re-en.json
Labels: pr: data update

#14749 Remove Light from Darkness
  packs/feats/light-from-darkness.json
Labels: pr: data update

#14751 Fix source of Effect: Emblazon Antimagic
  packs/feat-effects/effect-emblazon-antimagic.json
Labels: pr: data update

#14753 Restore second paragraph of Winter Sleet
  packs/book-of-the-dead-bestiary/disembodied-voices.json
  packs/feats/winter-sleet.json
Labels: pr: data update

#14754 Fix Afflicted Irnakurse's conditions
  packs/abomination-vaults-bestiary/afflicted-irnakurse.json
Labels: pr: data update

#14759 Remove traits from Jabberwock's Claws That Catch
  packs/kingmaker-bestiary/lesser-jabberwock.json
  packs/pathfinder-bestiary-2/jabberwock.json
Labels: pr: data update

#14758 Fix regeneration value for Irovetti's Fetch
  packs/kingmaker-bestiary/irovettis-fetch.json
Labels: pr: data update

#14752 Update `foundry.data.fields` for v12
  types/foundry/common/constants.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/active-effect.d.ts
Labels: pr: types update, pr: foundry v12

#14760 Remove vitality immunity from ofalth zombie
  packs/agents-of-edgewatch-bestiary/ofalth-zombie.json
Labels: pr: data update

#14750 Release Notes 5.15.4
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14766 Fix SpecialStatistic rules on Seugathi NPCs
  packs/abomination-vaults-bestiary/jafaki.json
  packs/abomination-vaults-bestiary/observation-deck-seugathi-researcher.json
  packs/abomination-vaults-bestiary/seugathi-reality-warper.json
  packs/abomination-vaults-bestiary/seugathi-researcher.json
  packs/abomination-vaults-bestiary/seugathi-servant.json
  packs/pfs-season-5-bestiary/weak-cacophonous-hound-echo.json
  packs/pfs-season-5-bestiary/weak-cosmic-amoeba.json
  packs/pfs-season-5-bestiary/weak-hound-echo.json
Labels: pr: data update

#14780 Fix Winter Sleet Stance for errata
  packs/feat-effects/stance-winter-sleet.json
Labels: pr: data update

#14779 Change elemental ability to match player core
  packs/familiar-abilities/elemental.json
Labels: pr: data update

#14773 Fix localization key for Animal and Angel traits descriptions
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#14781 Add base system actor and item classes to `CONFIG.PF2E`
  src/module/actor/base.ts
  src/scripts/config/index.ts
Labels: pr: enhancement, pr: foundry v12

#14771 Lower remaining DC 17 unstable checks to 15
  packs/feats/clockwork-celerity.json
  packs/feats/explosive-leap.json
  packs/feats/haphazard-repair.json
  packs/feats/negate-damage.json
Labels: pr: data update

#14782 Update Inner Fire feat name
  packs/feats/inner-fire-naari.json
Labels: pr: data update

#14786 Allow class traits on ability items again
  packs/actions/unleash-psyche.json
  src/module/item/ability/sheet.ts
Labels: pr: bugfix, pr: foundry v12

#14787 Fix action count normalizing to empty string
  src/module/item/ability/helpers.ts
Labels: pr: bugfix, pr: foundry v12

#14795 Block the existance of item and actor module sub-types
  src/module/actor/base.ts
  src/module/item/base/document.ts
  src/scripts/config/index.ts
Labels: pr: foundry v12

#14796 Fix typo in Dismiss action description
  packs/actions/dismiss.json
Labels: pr: data update

#14792 Add support for canGangUp: eidolon
  src/module/actor/data/base.ts
  src/module/canvas/token/object.ts
Labels: pr: enhancement, pr: foundry v12

#14798 Localize Howl of the Wild's Witch Patrons and Wild Witch Armaments
  packs/bestiary-effects/effect-conduct.json
  packs/classfeatures/devourer-of-decay.json
  packs/classfeatures/ripple-in-the-deep.json
  packs/classfeatures/whisper-of-wings.json
  static/lang/re-en.json
Labels: pr: data update

#14800 Fix some malformed links
  packs/equipment/hodag-leather.json
  packs/howl-of-the-wild-bestiary/almiraj.json
  packs/howl-of-the-wild-bestiary/apothecary-bee.json
  packs/howl-of-the-wild-bestiary/blooming-guardian.json
  packs/howl-of-the-wild-bestiary/chaos-falcon.json
  packs/howl-of-the-wild-bestiary/concert-frog.json
  packs/howl-of-the-wild-bestiary/fangtooth-school.json
  packs/howl-of-the-wild-bestiary/flynkett.json
  packs/howl-of-the-wild-bestiary/ghost-ape.json
  packs/howl-of-the-wild-bestiary/giant-fangtooth.json
  packs/howl-of-the-wild-bestiary/majungasaurus.json
  packs/howl-of-the-wild-bestiary/mist-bear.json
  packs/howl-of-the-wild-bestiary/mocking-chorus.json
  packs/howl-of-the-wild-bestiary/prismhydra.json
  packs/howl-of-the-wild-bestiary/rift-chameleon.json
  packs/howl-of-the-wild-bestiary/royal-basilisk.json
  packs/howl-of-the-wild-bestiary/sporeback-frog.json
  packs/howl-of-the-wild-bestiary/stargut-hydra.json
  packs/howl-of-the-wild-bestiary/stonefish-swarm.json
  packs/howl-of-the-wild-bestiary/stonefish.json
  packs/howl-of-the-wild-bestiary/stony-bat.json
  packs/howl-of-the-wild-bestiary/swordfish.json
  packs/howl-of-the-wild-bestiary/thruneosaurus-rex.json
  packs/howl-of-the-wild-bestiary/titanosaur.json
  packs/howl-of-the-wild-bestiary/tyrafdir.json
  packs/howl-of-the-wild-bestiary/virtuosic-lyrebird.json
  packs/howl-of-the-wild-bestiary/weremoose.json
Labels: pr: data update

#14799 Release Notes 5.16.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14802 Set initial values for all `ObjectField`s in `BattleFormRuleElement`
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/battle-form/schema.ts
Labels: pr: foundry v12

#14805 Make it possible to get mapped source/model types from `TypedSchemaField`
  types/foundry/common/constants.d.ts
  types/foundry/common/data/data.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/region.d.ts
Labels: pr: types update, pr: foundry v12

#14808 Fix source for trench digging
  packs/actions/trench-digging.json
Labels: pr: data update

#14804 Replace STX characters with hyphens
  packs/equipment/nightmares-lament.json
  packs/howl-of-the-wild-bestiary/magnegor.json
  packs/howl-of-the-wild-bestiary/scroungefeather.json
  packs/howl-of-the-wild-bestiary/storm-snake.json
  packs/howl-of-the-wild-bestiary/taldan-cave-squirrel.json
Labels: pr: data update

#14803 Fix invalid secondary casters in Awaken Portal ritual
  packs/spells/awaken-portal.json
Labels: pr: data update

#14811 Fix pair of issues with markdown conversion
  src/module/item/helpers.ts
Labels: pr: bugfix

#14806 Remove cycle-token-stack keybinding and `TokenLayerPF2e`
  src/module/canvas/index.ts
  src/module/canvas/layer/token.ts
  src/module/canvas/token/object.ts
  src/scripts/hooks/init.ts
  src/scripts/register-keybindings.ts
  static/lang/en.json
Labels: pr: refactor, pr: foundry v12

#14816 Update `Ruler` type for v12
  types/foundry/client/config.d.ts
  types/foundry/client/pixi/layers/controls/ruler.d.ts
Labels: pr: types update, pr: foundry v12

#14728 Start filling out scene region types
  package-lock.json
  package.json
  src/global.ts
  types/foundry/build/generate-client-base-mixes.ts
  types/foundry/client-esm/canvas/module.d.ts
  types/foundry/client-esm/canvas/regions/geometry.d.ts
  types/foundry/client-esm/canvas/regions/mesh.d.ts
  types/foundry/client-esm/canvas/regions/module.d.ts
  types/foundry/client-esm/canvas/regions/polygon-tree.d.ts
  types/foundry/client-esm/canvas/regions/shape.d.ts
  types/foundry/client-esm/data/module.d.ts
  types/foundry/client-esm/data/region-behaviors/adjust-darkness-level.d.ts
  types/foundry/client-esm/data/region-behaviors/base.d.ts
  types/foundry/client-esm/data/region-behaviors/execute-macro.d.ts
  types/foundry/client-esm/data/region-behaviors/execute-script.d.ts
  types/foundry/client-esm/data/region-behaviors/module.d.ts
  types/foundry/client-esm/data/region-behaviors/pause-game.d.ts
  types/foundry/client-esm/data/region-behaviors/suppress-weather.d.ts
  types/foundry/client-esm/data/region-behaviors/teleport-token.d.ts
  types/foundry/client-esm/data/region-behaviors/toggle-behavior.d.ts
  types/foundry/client/config.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
  types/foundry/client/data/documents/index.d.ts
  types/foundry/client/data/documents/region-behavior.d.ts
  types/foundry/client/data/documents/region-document.d.ts
  types/foundry/client/data/documents/scene.d.ts
  types/foundry/client/foundry/data/index.d.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/placeables/index.d.ts
  types/foundry/client/pixi/placeables/region.d.ts
  types/foundry/client/pixi/webgl/shaders/index.d.ts
  types/foundry/client/pixi/webgl/shaders/region.d.ts
  types/foundry/common/abstract/type-data.d.ts
  types/foundry/common/documents/module.d.ts
  types/foundry/common/documents/region-behavior.d.ts
  types/foundry/common/documents/region.d.ts
  types/foundry/common/documents/scene.d.ts
Labels: pr: types update, pr: foundry v12

#14812 Add missing Howl of the Wild localization
  packs/ancestryfeatures/awakened-mind.json
  packs/equipment/constricting-whip-tail.json
  packs/other-effects/effect-aura-of-protection.json
  static/lang/re-en.json
Labels: pr: data update

#14822 Differentiate the descriptions of colored dracolisks' abilities
  packs/pathfinder-bestiary-2/black-dracolisk.json
  packs/pathfinder-bestiary-2/blue-dracolisk.json
  packs/pathfinder-bestiary-2/green-dracolisk.json
  packs/pathfinder-bestiary-2/red-dracolisk.json
  packs/pathfinder-bestiary-2/white-dracolisk.json
Labels: pr: data update

#14824 Fix grant item RE form error with resolvable UUIDs
  src/module/item/base/sheet/rule-element-form/grant-item.ts
Labels: pr: bugfix, pr: foundry v12

#14823 Add some REs and Effects to Clawdancer, Thlipit, and Winged Warrior
  packs/feat-effects/stance-claw-stance.json
  packs/feat-effects/stance-talon-stance.json
  packs/feats/battering-wings.json
  packs/feats/clawdancer-dedication.json
  packs/feats/powerful-lash.json
  packs/feats/thlipit-contestant-dedication.json
  static/lang/re-en.json
Labels: pr: data update

#14827 Catch errors thrown by `fu.parseUuid` in the `UUIDUtils` helper methods
  src/util/uuid.ts
Labels: pr: bugfix, pr: foundry v12

#14829 Add effect for Aeon Stone (Pink Rhomboid)
  packs/equipment-effects/effect-aeon-stone-pink-rhomboid.json
  packs/equipment/aeon-stone-pink-rhomboid.json
Labels: pr: data update
