Repository foundryvtt/pf2e, pull requests merged in 2024-04, with the labels that each got.

#14274 Migrate away links to defunct ancestry vision features
  build/run-migration.ts
  src/module/migration/migrations/926-remove-vision-feature-links.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration

#14363 Fix damage type of Spider Sting
  packs/abomination-vaults-bestiary/belcorra-haruvex.json
  packs/agents-of-edgewatch-bestiary/copper-hand-illusionist.json
  packs/agents-of-edgewatch-bestiary/grabble-forden.json
  packs/agents-of-edgewatch-bestiary/venom-mage.json
  packs/agents-of-edgewatch-bestiary/water-elemental-vessel-i2.json
  packs/agents-of-edgewatch-bestiary/water-elemental-vessel.json
  packs/crown-of-the-kobold-king-bestiary/narlynark.json
  packs/extinction-curse-bestiary/corrupted-priest.json
  packs/fists-of-the-ruby-phoenix-bestiary/syu-tak-nwa-level-20.json
  packs/kingmaker-bestiary/darivan.json
  packs/kingmaker-bestiary/defaced-naiad-queen.json
  packs/kingmaker-bestiary/foras.json
  packs/kingmaker-bestiary/melianse.json
  packs/npc-gallery/necromancer.json
  packs/paizo-pregens/jaithe.json
  packs/pathfinder-bestiary-2/lunar-naga.json
  packs/pathfinder-monster-core/changeling-exile.json
  packs/pathfinder-monster-core/sweet-hag.json
  packs/pfs-season-1-bestiary/blue-streak-mage-7-8.json
  packs/pfs-season-1-bestiary/kip-the-druid-1-2.json
  packs/pfs-season-1-bestiary/kip-the-druid-3-4.json
  packs/season-of-ghosts-bestiary/noppera-bo-impersonator-primal.json
  packs/spells/spider-sting.json
  packs/strength-of-thousands-bestiary/grippli-jinxer.json
  packs/strength-of-thousands-bestiary/kurshkin.json
  packs/strength-of-thousands-bestiary/reborn-sun-mage.json
Labels: pr: data update

#14362 Use Item Alteration for Spellstrike recharge reminder in Conflux Spells
  packs/actions/spellstrike.json
  packs/spells/cascade-countermeasure.json
  packs/spells/dimensional-assault.json
  packs/spells/fabricated-truth.json
  packs/spells/force-fang.json
  packs/spells/hasted-assault.json
  packs/spells/runic-impression.json
  packs/spells/shielding-strike.json
  packs/spells/shooting-star.json
  packs/spells/spinning-staff.json
  packs/spells/thunderous-strike.json
  static/lang/re-en.json
Labels: pr: data update

#14364 Add Goodberry to renamed spells
  packs/journals/remaster-changes.json
Labels: pr: data update

#14367 Fix leak when updating party stash
  src/module/actor/party/document.ts
Labels: pr: bugfix

#14370 Avoid filtering homebrew creature traits from ability items
  src/module/item/ability/sheet.ts
Labels: pr: bugfix

#14374 Fix "consumAmmo" in an Omit type
  src/module/system/rolls.ts
Labels: pr: types update

#14365 Add template to Transmute Rock And Mud and update description to use lists rather than bullets
  packs/extinction-curse-bestiary/pin-tingwheely.json
  packs/fists-of-the-ruby-phoenix-bestiary/nai-yan-fei.json
  packs/spells/transmute-rock-and-mud.json
  packs/strength-of-thousands-bestiary/ssumzili.json
Labels: pr: data update

#14371 Fix missing exceptions for Zecui's Harden Chitin resistance
  packs/pathfinder-monster-core/zecui.json
Labels: pr: data update

#14378 Also show GM Notes in item summaries
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/item/helpers.ts
  src/styles/actor/_item-summary.scss
  static/templates/actors/partials/item-summary.hbs
Labels: pr: enhancement

#14382 (redeux) Add Routine to Helpful Wisp Swarm (PFS 5-13)
  packs/pfs-season-5-bestiary/extremely-helpful-wisp-swarm.json
  packs/pfs-season-5-bestiary/helpful-wisp-swarm.json
Labels: pr: data update

#14375 Add automation for Gallop
  packs/actions/gallop.json
  packs/kingmaker-bestiary/windchaser.json
  packs/outlaws-of-alkenstar-bestiary/daelum.json
  packs/pathfinder-bestiary/pegasus.json
  packs/pathfinder-bestiary/riding-horse.json
  packs/pathfinder-bestiary/riding-pony.json
  packs/pathfinder-bestiary/skeletal-horse.json
  packs/pathfinder-bestiary/war-horse.json
  packs/pathfinder-bestiary/war-pony.json
  packs/pathfinder-monster-core/pegasus.json
  packs/pathfinder-monster-core/pukwudgie.json
  packs/pathfinder-monster-core/riding-horse.json
  packs/pathfinder-monster-core/riding-pony.json
  packs/pathfinder-monster-core/skeletal-horse.json
  packs/pathfinder-monster-core/war-horse.json
  packs/pathfinder-monster-core/war-pony.json
  packs/pfs-season-1-bestiary/desert-wind.json
  packs/pfs-season-1-bestiary/skeletal-mount.json
  packs/pfs-season-1-bestiary/zombie-riding-horse.json
  packs/pfs-season-1-bestiary/zombie-warhorse.json
  packs/pfs-season-2-bestiary/brittle-skeletal-horse.json
  packs/travel-guide-bestiary/baccali-alpaca.json
Labels: pr: data update

#14376 Fix hair trigger prerequisite
  packs/feats/hair-trigger.json
Labels: pr: data update

#14384 Add description alteration for Dragons Breath
  packs/ancestryfeatures/draconic-exemplar.json
  packs/feats/dragons-breath.json
  static/lang/re-en.json
Labels: pr: data update

#14387 Include item options in target context clones
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#14392 Fix styling of action traits on familiar sheet
  src/styles/actor/_index.scss
  src/styles/actor/npc/_index.scss
Labels: pr: bugfix

#14391 Scale scatter damage with number of weapon damage dice
  src/module/item/weapon/data.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#14388 Fix item description on Age of Ashes NPC
  packs/age-of-ashes-bestiary/emaliza-zandivar.json
Labels: pr: data update

#14385 Add 2024 April Fools blog creature
  packs/backgrounds/osprey-scion.json
  packs/bestiary-effects/effect-enraging-whistle.json
  packs/bestiary-effects/effect-leaders-command.json
  packs/blog-bestiary/wordsmith.json
  packs/pfs-season-5-bestiary/assassins-guild-grenadier.json
  packs/pfs-season-5-bestiary/assassins-guild-rogue.json
  packs/pfs-season-5-bestiary/bandit-leader.json
  packs/pfs-season-5-bestiary/bandit.json
  packs/pfs-season-5-bestiary/beastmaster-cultist.json
  packs/pfs-season-5-bestiary/blessed-uirch-of-the-burning-suns.json
  packs/pfs-season-5-bestiary/burning-sun-orc.json
  packs/pfs-season-5-bestiary/burning-sun-warrior.json
  packs/pfs-season-5-bestiary/cultist-of-sezelrian.json
  packs/pfs-season-5-bestiary/empowered-daeodon.json
  packs/pfs-season-5-bestiary/experienced-bandit-leader.json
  packs/pfs-season-5-bestiary/experienced-cultist-of-sezelrian.json
  packs/pfs-season-5-bestiary/flaming-sphere-rune-5-6.json
  packs/pfs-season-5-bestiary/flaming-sphere-rune.json
  packs/pfs-season-5-bestiary/ghostknife-gardener.json
  packs/pfs-season-5-bestiary/ghostknife-infiltrator.json
  packs/pfs-season-5-bestiary/possessed-daeodons-7-8.json
  packs/pfs-season-5-bestiary/possessed-daeodons.json
  packs/pfs-season-5-bestiary/sezelrian-warg.json
  packs/pfs-season-5-bestiary/sronwa-5-6.json
  packs/pfs-season-5-bestiary/sronwa.json
  packs/pfs-season-5-bestiary/titanic-flytrap.json
  packs/pfs-season-5-bestiary/tough-assassins-guild-rogue.json
  packs/pfs-season-5-bestiary/tough-bandit.json
  packs/pfs-season-5-bestiary/tough-ghostknife-gardener.json
  packs/pfs-season-5-bestiary/tough-ghostknife-infiltrator.json
  packs/pfs-season-5-bestiary/tough-titanic-flytrap.json
  packs/pfs-season-5-bestiary/trained-beastmaster-cultist.json
  packs/pfs-season-5-bestiary/uirch-of-the-burning-suns.json
Labels: pr: data update

#14399 Fix build after predicate rename
  tests/module/system/predication.test.ts
Labels: pr: housekeeping

#14393 Fix description of Flawed Orb of Gold Dragonkind
  packs/age-of-ashes-bestiary/emaliza-zandivar.json
  packs/equipment/flawed-orb-of-gold-dragonkind.json
Labels: pr: data update

#14408 Fix predicating parent roll options in modifier clones
  src/module/actor/modifiers.ts
Labels: pr: bugfix

#14400 Fix action cost and inline damage of Vloriak's Spew Rusted Shards
  packs/rusthenge-bestiary/vloriak.json
Labels: pr: data update

#14407 Remove incorrect Agathion trait from Hryngar Forgepriest
  packs/sky-kings-tomb-bestiary/hryngar-forgepriest.json
Labels: pr: data update

#14414 Add effect links to Sanguine Mutagen
  packs/equipment-effects/effect-sanguine-mutagen-greater.json
  packs/equipment-effects/effect-sanguine-mutagen-major.json
  packs/equipment-effects/effect-sanguine-mutagen-moderate.json
  packs/equipment/sanguine-mutagen-greater.json
  packs/equipment/sanguine-mutagen-lesser.json
  packs/equipment/sanguine-mutagen-major.json
  packs/equipment/sanguine-mutagen-moderate.json
Labels: pr: data update

#14417 Correct level of standard-grade adamantine armor
  src/module/item/physical/materials.ts
Labels: pr: data update

#14422 Correct Glimpse Weakness scaling and fix other data errors
  packs/feats/settlement-scholastics.json
  packs/pathfinder-monster-core/shining-child.json
  packs/season-of-ghosts-bestiary/heh-shan-bao.json
  packs/spell-effects/spell-effect-glimpse-weakness.json
  packs/spells/winters-breath.json
Labels: pr: data update

#14425 Add metal and wood domains to journals
  packs/journals/domains.json
Labels: pr: data update

#14427 Fix links in Smoke Ball (Lesser)
  packs/equipment/smoke-ball-greater.json
  packs/equipment/smoke-ball-lesser.json
Labels: pr: data update

#14420 Clean up some archetype journal formatting
  packs/bestiary-effects/effect-exalt-the-little-ones.json
  packs/bestiary-effects/effect-primal-sink.json
  packs/equipment/arboreal-wand-rank-2.json
  packs/equipment/arboreal-wand-rank-3.json
  packs/equipment/arboreal-wand-rank-4.json
  packs/equipment/arboreal-wand-rank-5.json
  packs/equipment/arboreal-wand-rank-6.json
  packs/equipment/arboreal-wand-rank-7.json
  packs/equipment/beekeepers-smoker.json
  packs/equipment/canopy-bulwark.json
  packs/equipment/primal-pollen.json
  packs/equipment/skitter-knot-greater.json
  packs/equipment/skitter-knot-lesser.json
  packs/equipment/skitter-knot-major.json
  packs/feats/canopy-predator.json
  packs/feats/death-from-above.json
  packs/feats/sense-the-strike.json
  packs/feats/underbrush-trailblazer.json
  packs/feats/verduran-ambush.json
  packs/feats/verduran-shadow-dedication.json
  packs/journals/archetypes.json
  packs/spells/bee-mans-summons.json
  packs/spells/commune-with-corazal.json
  packs/wardens-of-wildwood-bestiary/alyce-quinley.json
  packs/wardens-of-wildwood-bestiary/arboreal-sapling.json
  packs/wardens-of-wildwood-bestiary/arboreal-sapstriker.json
  packs/wardens-of-wildwood-bestiary/arboreal-shepherd.json
  packs/wardens-of-wildwood-bestiary/azhana.json
  packs/wardens-of-wildwood-bestiary/bee-covered-ohancanu.json
  packs/wardens-of-wildwood-bestiary/bee-induced-panic.json
  packs/wardens-of-wildwood-bestiary/besieged-logging-crew.json
  packs/wardens-of-wildwood-bestiary/bystander.json
  packs/wardens-of-wildwood-bestiary/chetamog.json
  packs/wardens-of-wildwood-bestiary/cythnophorian.json
  packs/wardens-of-wildwood-bestiary/emorga-all-seer.json
  packs/wardens-of-wildwood-bestiary/hateful-bear.json
  packs/wardens-of-wildwood-bestiary/hateful-hodag.json
  packs/wardens-of-wildwood-bestiary/hateful-logger.json
  packs/wardens-of-wildwood-bestiary/inrik-vanderholl.json
  packs/wardens-of-wildwood-bestiary/lloyd-the-leaper.json
  packs/wardens-of-wildwood-bestiary/myristicas-despair.json
  packs/wardens-of-wildwood-bestiary/ohancanu.json
  packs/wardens-of-wildwood-bestiary/otis.json
  packs/wardens-of-wildwood-bestiary/sarracenias-ire.json
  packs/wardens-of-wildwood-bestiary/sigrid-jandevik.json
  packs/wardens-of-wildwood-bestiary/silene.json
  packs/wardens-of-wildwood-bestiary/splintershank.json
  packs/wardens-of-wildwood-bestiary/stormdrinker.json
  packs/wardens-of-wildwood-bestiary/the-bee-man-of-bellis.json
  packs/wardens-of-wildwood-bestiary/tumbo.json
  packs/wardens-of-wildwood-bestiary/twigjack-bramble.json
  packs/wardens-of-wildwood-bestiary/usher.json
  packs/wardens-of-wildwood-bestiary/wraithvine-offshoot.json
  packs/wardens-of-wildwood-bestiary/wraithvine.json
  static/lang/re-en.json
  static/system.json
Labels: pr: data update

#14426 Add effect for Lava Leap
  packs/feat-effects/effect-lava-leap.json
  packs/feats/lava-leap.json
Labels: pr: data update

#14436 Fix defenses and size of Mighty Bul-Gae
  packs/stolen-fate-bestiary/mighty-bul-gae.json
Labels: pr: data update

#14437 Fix skill bonuses for Immense Mandragora
  packs/agents-of-edgewatch-bestiary/lusca.json
  packs/kingmaker-bestiary/immense-mandragora.json
  packs/kingmaker-bestiary/mandragora-swarm.json
  packs/pathfinder-bestiary-2/mandragora.json
  packs/pathfinder-bestiary-3/piranha-swarm.json
  packs/pathfinder-bestiary/bunyip.json
  packs/pathfinder-bestiary/great-white-shark.json
  packs/pathfinder-monster-core/great-white-shark.json
  packs/pfs-season-1-bestiary/great-white-shark-pfs-1-12.json
  packs/pfs-season-2-bestiary/bloodthirsty-razortoothed-shark.json
  packs/pfs-season-2-bestiary/bruorsivi-mandragora.json
  packs/pfs-season-2-bestiary/lesser-bruorsivi-mandragora.json
  packs/pfs-season-2-bestiary/razortoothed-shark.json
  packs/pfs-season-2-bestiary/saddleback-bunyip.json
  packs/pfs-season-5-bestiary/germinated-mandragora.json
  packs/sky-kings-tomb-bestiary/gray-worm.json
  packs/strength-of-thousands-bestiary/giant-tsetse-fly.json
Labels: pr: data update

#14438 Prevent loss of modifier adjustments from property runes
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#14447 Fix validation of override mode damage dice faces item alterations
  src/module/rules/rule-element/item-alteration/schemas.ts
Labels: pr: bugfix

#14237 Add world time setting for imperial calendar
  src/module/apps/world-clock/app.ts
  src/module/system/settings/world-clock.ts
  src/scripts/config/index.ts
Labels: pr: enhancement, pr: delay merge

#14446 Make minor formatting and grammar changes in Bestiary 2 item descriptions
  packs/equipment-effects/effect-soulspark-candle.json
  packs/pathfinder-bestiary-2/brine-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/brine-dragon-ancient.json
  packs/pathfinder-bestiary-2/coil-spy.json
  packs/pathfinder-bestiary-2/emperor-cobra.json
  packs/pathfinder-bestiary-2/green-dracolisk.json
  packs/pathfinder-bestiary-2/ice-yai.json
  packs/pathfinder-bestiary-2/interlocutor.json
  packs/pathfinder-bestiary-2/magma-scorpion.json
  packs/pathfinder-bestiary-2/planetar.json
  packs/pathfinder-bestiary-2/sunflower-leshy.json
  packs/pathfinder-bestiary-2/umbral-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-adult.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient.json
  packs/pathfinder-bestiary-2/vrykolakas-ancient.json
  packs/pathfinder-bestiary-2/vrykolakas-master.json
  packs/pathfinder-bestiary-2/weretiger.json
  packs/pathfinder-bestiary/night-hag.json
  packs/spell-effects/spell-effect-fey-form-unicorn.json
  packs/spells/blazing-fissure.json
  packs/spells/fey-form.json
Labels: pr: data update

#14442 Fix some malformed links
  packs/pfs-season-5-bestiary/bandit.json
  packs/pfs-season-5-bestiary/elite-trained-vulkariki-eidolon.json
  packs/pfs-season-5-bestiary/possessed-daeodons-7-8.json
  packs/pfs-season-5-bestiary/sharktopus-eidolon.json
  packs/pfs-season-5-bestiary/tough-bandit.json
  packs/pfs-season-5-bestiary/trained-sharktopus-eidolon.json
  packs/pfs-season-5-bestiary/trained-vulkariki-eidolon.json
  packs/pfs-season-5-bestiary/vulkariki-eidolon.json
Labels: pr: data update

#14435 Remove broken spell links from granted deity spells
  packs/deities/adanye.json
  packs/deities/chaldira.json
  packs/deities/erecura.json
  packs/deities/sivanah.json
  packs/deities/winlas.json
Labels: pr: data update

#14433 Add effect, area, and leveled damage link for Volcanic Eruption
  packs/agents-of-edgewatch-bestiary/agradaemon.json
  packs/agents-of-edgewatch-bestiary/water-elemental-vessel-i2.json
  packs/agents-of-edgewatch-bestiary/water-elemental-vessel.json
  packs/extinction-curse-bestiary/saurian-worldwatcher.json
  packs/mwangi-expanse-bestiary/maliadi.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/marrmora.json
  packs/pathfinder-bestiary-3/hesperid-queen.json
  packs/pathfinder-bestiary-3/lampad-queen.json
  packs/pathfinder-bestiary-3/living-rune-primal.json
  packs/pathfinder-bestiary-3/tolokand.json
  packs/pathfinder-monster-core/adamantine-dragon-ancient-spellcaster.json
  packs/pfs-season-3-bestiary/eltha-embercall-11-12-28-cp.json
  packs/rage-of-elements-bestiary/ifrit-shuyookh.json
  packs/spell-effects/spell-effect-volcanic-eruption.json
  packs/spells/volcanic-eruption.json
  packs/strength-of-thousands-bestiary/unshadowed-anchor-root.json
Labels: pr: data update

#14419 Add traits for Tian Xia World Guide
  packs/spells/perfection-of-essence.json
  packs/spells/power-of-the-beasts.json
  packs/spells/seed-of-mercy.json
  packs/spells/the-unseeing-blade-master.json
  packs/spells/wild-allegiance.json
  packs/tian-xia-world-guide-bestiary/animated-bamboo-figurine.json
  packs/tian-xia-world-guide-bestiary/animated-kite.json
  packs/tian-xia-world-guide-bestiary/animated-wine-vessel.json
  packs/tian-xia-world-guide-bestiary/aoyin.json
  packs/tian-xia-world-guide-bestiary/aso-berang.json
  packs/tian-xia-world-guide-bestiary/bul-gae.json
  packs/tian-xia-world-guide-bestiary/catterpillar-carriage.json
  packs/tian-xia-world-guide-bestiary/five-color-orchid-mantis.json
  packs/tian-xia-world-guide-bestiary/gau-cho-rong.json
  packs/tian-xia-world-guide-bestiary/giant-orchid-mantis.json
  packs/tian-xia-world-guide-bestiary/hopping-head.json
  packs/tian-xia-world-guide-bestiary/ijhyeojin.json
  packs/tian-xia-world-guide-bestiary/imugi.json
  packs/tian-xia-world-guide-bestiary/inkdrop.json
  packs/tian-xia-world-guide-bestiary/jiidon.json
  packs/tian-xia-world-guide-bestiary/joseung-saja.json
  packs/tian-xia-world-guide-bestiary/kun.json
  packs/tian-xia-world-guide-bestiary/manananggal.json
  packs/tian-xia-world-guide-bestiary/nue.json
  packs/tian-xia-world-guide-bestiary/orchid-mantis-swarm.json
  packs/tian-xia-world-guide-bestiary/peng.json
  packs/tian-xia-world-guide-bestiary/pixiu.json
  packs/tian-xia-world-guide-bestiary/shui-gui.json
  packs/tian-xia-world-guide-bestiary/the-great-flood.json
  packs/tian-xia-world-guide-bestiary/yeongno.json
  packs/vehicles/atakebune.json
  packs/vehicles/baochuan.json
  packs/vehicles/djong.json
  packs/vehicles/geobukseon.json
  packs/vehicles/karakoa.json
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
  static/system.json
Labels: pr: data entry, source: lost omens

#14449 Fix level of Waldgeist
  packs/backgrounds/fey-friend.json
  packs/backgrounds/green-faith-pilgrim.json
  packs/backgrounds/moot-guard.json
  packs/backgrounds/tree-friend.json
  packs/backgrounds/verduran-city-folk.json
  packs/backgrounds/wood-warden.json
  packs/book-of-the-dead-bestiary/waldgeist.json
  packs/pfs-season-5-bestiary/blessed-uirch-of-the-burning-suns.json
  packs/pfs-season-5-bestiary/uirch-of-the-burning-suns.json
  packs/wardens-of-wildwood-bestiary/bee-induced-panic.json
  packs/wardens-of-wildwood-bestiary/bystander.json
  packs/wardens-of-wildwood-bestiary/lloyd-the-leaper.json
  packs/wardens-of-wildwood-bestiary/sigrid-jandevik.json
  packs/wardens-of-wildwood-bestiary/splintershank.json
  packs/wardens-of-wildwood-bestiary/wraithvine-offshoot.json
  packs/wardens-of-wildwood-bestiary/wraithvine.json
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#14453 Fix some sources
  packs/pfs-season-5-bestiary/baby-brine-shark.json
  packs/spells/perfection-of-essence.json
  packs/spells/power-of-the-beasts.json
  packs/spells/seed-of-mercy.json
  packs/spells/the-unseeing-blade-master.json
  packs/spells/wild-allegiance.json
  packs/tian-xia-world-guide-bestiary/animated-bamboo-figurine.json
  packs/tian-xia-world-guide-bestiary/animated-kite.json
  packs/tian-xia-world-guide-bestiary/animated-wine-vessel.json
  packs/tian-xia-world-guide-bestiary/aoyin.json
  packs/tian-xia-world-guide-bestiary/aso-berang.json
  packs/tian-xia-world-guide-bestiary/bul-gae.json
  packs/tian-xia-world-guide-bestiary/caterpillar-carriage.json
  packs/tian-xia-world-guide-bestiary/five-color-orchid-mantis.json
  packs/tian-xia-world-guide-bestiary/gau-cho-rong.json
  packs/tian-xia-world-guide-bestiary/giant-orchid-mantis.json
  packs/tian-xia-world-guide-bestiary/hopping-head.json
  packs/tian-xia-world-guide-bestiary/ijhyeojin.json
  packs/tian-xia-world-guide-bestiary/imugi.json
  packs/tian-xia-world-guide-bestiary/inkdrop.json
  packs/tian-xia-world-guide-bestiary/jiidon.json
  packs/tian-xia-world-guide-bestiary/joseung-saja.json
  packs/tian-xia-world-guide-bestiary/kun.json
  packs/tian-xia-world-guide-bestiary/manananggal.json
  packs/tian-xia-world-guide-bestiary/nue.json
  packs/tian-xia-world-guide-bestiary/orchid-mantis-swarm.json
  packs/tian-xia-world-guide-bestiary/peng.json
  packs/tian-xia-world-guide-bestiary/pixiu.json
  packs/tian-xia-world-guide-bestiary/shui-gui.json
  packs/tian-xia-world-guide-bestiary/the-great-flood.json
  packs/tian-xia-world-guide-bestiary/yeongno.json
  packs/vehicles/atakebune.json
  packs/vehicles/baochuan.json
  packs/vehicles/djong.json
  packs/vehicles/geobukseon.json
  packs/vehicles/karakoa.json
Labels: pr: data update

#14454 Set default level in party check level-based DC's to average party level.
  src/scripts/macros/check-prompt/prompt.ts
  static/templates/gm/check-prompt.hbs
Labels: pr: enhancement

#14389 Monster Core data corrections H-J
  packs/bestiary-effects/effect-take-them-down.json
  packs/pathfinder-monster-core/harpy.json
  packs/pathfinder-monster-core/hobgoblin-archer.json
  packs/pathfinder-monster-core/hobgoblin-general.json
  packs/pathfinder-monster-core/hobgoblin-soldier.json
  packs/pathfinder-monster-core/hryngar-bombardier.json
  packs/pathfinder-monster-core/hryngar-sharpshooter.json
  packs/pathfinder-monster-core/hunting-spider.json
  packs/pathfinder-monster-core/ice-linnorm.json
  packs/pathfinder-monster-core/imp.json
  packs/pathfinder-monster-core/island-oni.json
  packs/pathfinder-monster-core/jaathoom.json
  packs/pathfinder-monster-core/jabali.json
Labels: pr: data update

#14457 Fix Ghostly Resistance definitions
  packs/feats/ghostly-resistance.json
Labels: pr: data update

#14458 Fix deity skill getting set to invalid values
  src/module/item/deity/sheet.ts
Labels: pr: bugfix

#14460 Tweak some deities
  packs/deities/baekho.json
  packs/deities/mugura-and-nrithu.json
  packs/deities/phi-deva.json
  packs/deities/srikalis-sritaming-and-sribaril.json
  packs/deities/the-lady-of-the-north-star.json
Labels: pr: data entry

#14459 Fix traits data not being omitted from certain item types
  src/module/item/base/sheet/sheet.ts
Labels: pr: bugfix

#14462 Release Notes 5.15.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14463 Update vite, codemirror, and subdependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#14467 Update cassisian helmet to add area damage
  packs/equipment/cassisian-helmet.json
Labels: pr: data update

#14461 Fix Simeek Attribute Modifiers
  packs/paizo-pregens/simeek.json
Labels: pr: data update

#14465 fix compendium folder for Tian Xia world guide Compendium
  static/system.json
Labels: pr: data update

#14472 Set grid manifest settings to the new v12 format
  static/system.json
Labels: pr: foundry v12

#14481 Start updating `Canvas` and `Grid` types for v12. Fix `MeasuredTemplate`s
  src/module/apps/scene-darkness-adjuster.ts
  src/module/canvas/effect-area-square.ts
  src/module/canvas/helpers.ts
  src/module/canvas/layer/template.ts
  src/module/canvas/measured-template.ts
  src/module/canvas/token/aura/map.ts
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/object.ts
  src/module/scene/document.ts
  src/module/scene/token-document/clown-car.ts
  src/module/scene/token-document/document.ts
  src/module/system/settings/index.ts
  src/scripts/hooks/canvas-init.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/ready.ts
  types/foundry/client/foundry/index.d.ts
  types/foundry/client/pixi/board.d.ts
  types/foundry/client/pixi/canvas-layer/grid-layer.d.ts
  types/foundry/client/pixi/core/shapes/index.d.ts
  types/foundry/client/pixi/core/shapes/polygon-helpers.d.ts
  types/foundry/client/pixi/edges/collision.d.ts
  types/foundry/client/pixi/edges/edge.d.ts
  types/foundry/client/pixi/edges/edges.d.ts
  types/foundry/client/pixi/edges/module.d.ts
  types/foundry/client/pixi/edges/vertex.d.ts
  types/foundry/client/pixi/fog-manager.d.ts
  types/foundry/client/pixi/grid/base.d.ts
  types/foundry/client/pixi/grid/module.d.ts
  types/foundry/client/pixi/groups/canvas-group.d.ts
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/groups/environment.d.ts
  types/foundry/client/pixi/groups/index.d.ts
  types/foundry/client/pixi/groups/interface.d.ts
  types/foundry/client/pixi/groups/overlay.d.ts
  types/foundry/client/pixi/groups/rendered.ts
  types/foundry/client/pixi/index.d.ts
  types/foundry/client/pixi/layers/base/placeables-layer.d.ts
  types/foundry/client/pixi/module.d.ts
  types/foundry/client/pixi/perception/color-manager.d.ts
  types/foundry/client/pixi/perception/index.d.ts
  types/foundry/client/pixi/scene-manager.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/data/data.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/scene.d.ts
Labels: pr: types update, pr: foundry v12

#14473 Replace all instances of `Math.clamped` with `Math.clamp`
  src/module/actor/army/document.ts
  src/module/actor/army/sheet.ts
  src/module/actor/base.ts
  src/module/actor/character/attribute-builder.ts
  src/module/actor/character/crafting/entry.ts
  src/module/actor/character/crafting/formula.ts
  src/module/actor/character/document.ts
  src/module/actor/character/elemental-blast.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/actor/modifiers.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/skills-editor.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/sheet/base.ts
  src/module/apps/compendium-browser/index.ts
  src/module/apps/effects-panel.ts
  src/module/canvas/helpers.ts
  src/module/canvas/token/object.ts
  src/module/item/ability/helpers.ts
  src/module/item/affliction/document.ts
  src/module/item/ancestry/document.ts
  src/module/item/consumable/document.ts
  src/module/item/container/document.ts
  src/module/item/deity/sheet.ts
  src/module/item/effect/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/weapon/document.ts
  src/module/migration/migrations/914-move-perception-senses.ts
  src/module/rules/rule-element/aura.ts
  src/module/rules/rule-element/crit-spec.ts
  src/module/rules/rule-element/damage-alteration/alteration.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/martial-proficiency.ts
  src/module/rules/rule-element/strike.ts
  src/module/rules/rule-element/substitute-roll.ts
  src/module/scene/sheet.ts
  src/module/system/action-macros/ancestry/automaton/arcane-slam.ts
  src/module/system/action-macros/athletics/whirling-throw.ts
  src/module/system/check/check.ts
  src/module/system/degree-of-success.ts
  src/module/system/statistic/hit-points.ts
  src/module/system/statistic/statistic.ts
  src/scripts/macros/earn-income/calculate.ts
  src/scripts/macros/xp/index.ts
  tests/setup.ts
  types/foundry/common/primitives/math.d.ts
Labels: pr: foundry v12

#14482 Update MeasuredTemplate, Placeable, and MouseInteractionManager types for V12
  types/foundry/client/pixi/core/interaction/mouse-handler.d.ts
  types/foundry/client/pixi/placeable.d.ts
  types/foundry/client/pixi/placeables/index.d.ts
  types/foundry/client/pixi/placeables/template.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
Labels: pr: types update, pr: foundry v12

#14474 Remove `TextEditor._enrichContentLinks` override
  src/module/system/text-editor.ts
Labels: pr: foundry v12

#14485 Update grid properties of system schema for v12
  src/module/canvas/token/aura/renderer.ts
  types/foundry/common/packages/base-system.d.ts
Labels: pr: foundry v12

#14484 Update TextEditor typing and remove async option
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/item-transfer.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/npc/document.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/party/kingdom/builder.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/item-summary-renderer.ts
  src/module/apps/effects-panel.ts
  src/module/apps/migration-summary.ts
  src/module/canvas/status-effects.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/helpers.ts
  src/module/item/physical/sheet.ts
  src/module/item/spell/document.ts
  src/module/system/text-editor.ts
  src/scripts/macros/hotbar.ts
  types/foundry/client/ui/editor.d.ts
Labels: pr: foundry v12

#14489 Fix template HMR
  src/scripts/hooks/load.ts
  types/foundry/client/misc.d.ts
Labels: pr: foundry v12

#14488 Record latest supported core schema version when building packs
  build/lib/compendium-pack.ts
Labels: pr: foundry v12

#14479 Add inline damage link to Fire Ray
  packs/iconics/kyra-level-1.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/pfs-season-5-bestiary/blessed-uirch-of-the-burning-suns.json
  packs/pfs-season-5-bestiary/uirch-of-the-burning-suns.json
  packs/spells/fire-ray.json
Labels: pr: data update

#14480 Fix logic of Fury Instinct Raging Resistance
  packs/classfeatures/fury-instinct.json
Labels: pr: data update

#14487 Fix Electrify Armor inline damage roll
  packs/feats/electrify-armor.json
Labels: pr: data update

#14486 Minor grammar and formatting fixes in Bestiary 3
  packs/night-of-the-gray-death-bestiary/gray-death.json
  packs/pathfinder-bestiary-3/gurgist-mauler.json
  packs/pathfinder-bestiary-3/nosferatu-overlord.json
  packs/pathfinder-bestiary-3/nucol.json
  packs/pathfinder-bestiary-3/owb-prophet.json
  packs/pathfinder-bestiary-3/sky-dragon-ancient.json
  packs/pathfinder-bestiary-3/sovereign-dragon-adult.json
  packs/pathfinder-bestiary-3/sovereign-dragon-ancient.json
  packs/pathfinder-bestiary-3/viper-swarm.json
Labels: pr: data update

#14490 Move dice classes to `foundry.dice.terms` namespace
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/degree-of-success.ts
  src/module/system/check/check.ts
  src/module/system/damage/formula.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  src/module/system/degree-of-success.ts
  src/scripts/dice.ts
  types/foundry/client/config.d.ts
  types/foundry/client/foundry/index.d.ts
  types/foundry/client/roll-term/base.d.ts
  types/foundry/client/roll-term/dice-term/base.d.ts
  types/foundry/client/roll-term/dice-term/coin.d.ts
  types/foundry/client/roll-term/dice-term/die.d.ts
  types/foundry/client/roll-term/dice-term/fate-die.d.ts
  types/foundry/client/roll-term/function-term.d.ts
  types/foundry/client/roll-term/index.d.ts
  types/foundry/client/roll-term/math-term.d.ts
  types/foundry/client/roll-term/module.d.ts
  types/foundry/client/roll-term/numeric-term.d.ts
  types/foundry/client/roll-term/operator-term.d.ts
  types/foundry/client/roll-term/parenthetical-term.d.ts
  types/foundry/client/roll-term/pool-term.d.ts
  types/foundry/client/roll-term/string-term.d.ts
  types/foundry/client/roll-term/terms.d.ts
  types/foundry/client/roll.d.ts
Labels: pr: types update, pr: foundry v12

#14494 Begin converting deprecated select handlebars helper to selectOptions
  static/templates/actors/character/tabs/pfs.hbs
  static/templates/actors/familiar/sheet.hbs
  static/templates/actors/hazard/partials/header.hbs
  static/templates/actors/npc/partials/header.hbs
  static/templates/actors/npc/simple-sheet.hbs
  static/templates/items/action-sidebar.hbs
  static/templates/items/ancestry-sidebar.hbs
  static/templates/items/armor-details.hbs
  static/templates/items/physical-sidebar.hbs
  static/templates/items/rules-panel.hbs
  static/templates/items/sheet.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: foundry v12

#14464 Automate Keen Follower feat
  packs/feats/keen-follower.json
  packs/other-effects/effect-follow-the-expert.json
Labels: pr: data update

#14492 Fix Cilios's Fist attack effect to be Blinding Rot
  packs/crown-of-the-kobold-king-bestiary/cilios.json
Labels: pr: data update

#14493 Add a 5th slot to Kyra (Level 5)'s Divine Font
  packs/iconics/kyra-level-5.json
Labels: pr: data update

#14497 Fix aura rule element
  src/module/rules/rule-element/aura.ts
Labels: pr: foundry v12

#14500 Fix non-rarity trait selection appearing in class sheet
  src/module/item/class/document.ts
Labels: pr: bugfix

#14502 Fix aura RE form error
  src/module/item/base/sheet/rule-element-form/aura.ts
Labels: pr: foundry v12

#14510 Fix parsing damage rolls with `MathTerms` and remove deprecated `async` option for roll evaluation
  roll-grammar.peggy
  src/module/actor/base.ts
  src/module/actor/party/kingdom/model.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/item/effect/document.ts
  src/module/rules/rule-element/fast-healing.ts
  src/module/scene/token-document/document.ts
  src/module/system/action-macros/crafting/repair.ts
  src/module/system/check/check.ts
  src/module/system/check/roll.ts
  src/module/system/damage/damage.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  src/module/system/text-editor.ts
  src/scripts/dice.ts
  src/scripts/macros/encouraging-words.ts
  src/scripts/macros/treat-wounds.ts
  types/foundry/client/game.d.ts
  types/foundry/client/roll-term/base.d.ts
  types/foundry/client/roll-term/function-term.d.ts
  types/foundry/client/roll.d.ts
  types/foundry/common/packages/base-system.d.ts
Labels: pr: foundry v12

#14501 Fix status effect icons
  src/module/active-effect.ts
  src/module/actor/base.ts
  src/module/actor/creature/document.ts
  src/module/actor/token-effect.ts
  src/module/canvas/status-effects.ts
  src/module/encounter/combatant.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/config.d.ts
  types/foundry/client/data/documents/actor.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/common/documents/active-effect.d.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: foundry v12

#14503 Fix damage dialog rollmode display
  src/module/system/damage/dialog.ts
Labels: pr: bugfix

#14511 Restore basic RBV canvas vision in v12
  src/module/canvas/ambient-light.ts
  src/module/canvas/token/object.ts
  src/module/scene/ambient-light-document.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/pixi/placeables/light.d.ts
  types/foundry/client/pixi/placeables/sound.d.ts
  types/foundry/common/documents/ambient-light.d.ts
  types/foundry/common/documents/scene.d.ts
  types/foundry/common/documents/token.d.ts
  types/foundry/common/packages/base-system.d.ts
Labels: pr: foundry v12

#14515 Start converting VisionSource/LightSource/etc to new V12 structure
  src/module/canvas/perception/hearing-source.ts
  src/module/canvas/perception/modes.ts
  types/foundry/client-esm/canvas/sources/base-effect-source.d.ts
  types/foundry/client-esm/canvas/sources/base-light-source.d.ts
  types/foundry/client-esm/canvas/sources/global-light-source.d.ts
  types/foundry/client-esm/canvas/sources/module.ts
  types/foundry/client-esm/canvas/sources/point-darkness-source.d.ts
  types/foundry/client-esm/canvas/sources/point-effect-source-mixes.d.ts
  types/foundry/client-esm/canvas/sources/point-light-source.d.ts
  types/foundry/client-esm/canvas/sources/point-movement-source.d.ts
  types/foundry/client-esm/canvas/sources/point-sound-source.d.ts
  types/foundry/client-esm/canvas/sources/point-vision-source.d.ts
  types/foundry/client-esm/canvas/sources/rendered-effect-source.d.ts
  types/foundry/client/pixi/module.d.ts
  types/foundry/client/pixi/placeables/light.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
  types/foundry/client/pixi/sources/base-source.d.ts
  types/foundry/client/pixi/sources/index.d.ts
  types/foundry/client/pixi/sources/light-source.d.ts
  types/foundry/client/pixi/sources/sound-source.d.ts
  types/foundry/client/pixi/sources/vision-source.d.ts
  types/foundry/client/pixi/webgl/shaders/sampler.d.ts
Labels: pr: foundry v12

#14516 Move dice and edges definition files to `client-esm` folder to better reflect the Foundry data structure
  src/module/system/check/check.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/roll.ts
  src/module/system/damage/terms.ts
  src/module/system/degree-of-success.ts
  types/foundry/client-esm/canvas/edges/collision.d.ts
  types/foundry/client-esm/canvas/edges/edge.d.ts
  types/foundry/client-esm/canvas/edges/edges.d.ts
  types/foundry/client-esm/canvas/edges/module.d.ts
  types/foundry/client-esm/canvas/edges/vertex.d.ts
  types/foundry/client-esm/dice/module.d.ts
  types/foundry/client-esm/dice/terms/coin.d.ts
  types/foundry/client-esm/dice/terms/dice-term.d.ts
  types/foundry/client-esm/dice/terms/die.d.ts
  types/foundry/client-esm/dice/terms/fate-die.d.ts
  types/foundry/client-esm/dice/terms/function-term.d.ts
  types/foundry/client-esm/dice/terms/module.d.ts
  types/foundry/client-esm/dice/terms/numeric-term.d.ts
  types/foundry/client-esm/dice/terms/operator-term.d.ts
  types/foundry/client-esm/dice/terms/parenthetical-term.d.ts
  types/foundry/client-esm/dice/terms/pool-term.d.ts
  types/foundry/client-esm/dice/terms/roll-term.d.ts
  types/foundry/client-esm/dice/terms/string-term.d.ts
  types/foundry/client/foundry/index.d.ts
  types/foundry/client/pixi/module.d.ts
  types/foundry/client/roll-term/index.d.ts
  types/foundry/client/roll-term/module.d.ts
  types/foundry/client/roll-term/terms.d.ts
  types/foundry/client/roll.d.ts
Labels: pr: types update, pr: foundry v12

#14509 Convert more instances of the deprecated select handlebars helper to selectOptions
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/spellcasting-dialog.ts
  src/module/item/physical/sheet.ts
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/spellcasting-dialog.hbs
  static/templates/items/armor-details.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: foundry v12

#14517 Restore hearing detection for V12
  src/module/canvas/perception/hearing-source.ts
  src/module/canvas/perception/modes.ts
  src/module/canvas/perception/point-vision-source.ts
  src/module/canvas/token/object.ts
  src/scripts/hooks/init.ts
  types/foundry/client-esm/canvas/sources/base-effect-source.d.ts
  types/foundry/client-esm/canvas/sources/point-darkness-source.d.ts
  types/foundry/client-esm/canvas/sources/point-effect-source-mixes.d.ts
  types/foundry/client-esm/canvas/sources/point-light-source.d.ts
  types/foundry/client-esm/canvas/sources/point-sound-source.d.ts
  types/foundry/client/config.d.ts
  types/foundry/client/pixi/layers/effects/visibility.d.ts
  types/foundry/client/pixi/perception/detection-mode.d.ts
Labels: pr: foundry v12

#14518 Fix issue with `PointVisionSource.blindedColorRGB` and some types
  src/module/canvas/perception/point-vision-source.ts
  types/foundry/client/config.d.ts
  types/foundry/client/pixi/core/shapes/source-polygon.d.ts
  types/foundry/client/pixi/perception/clockwise-sweep.d.ts
  types/foundry/client/pixi/perception/vision-mode.d.ts
  types/foundry/client/pixi/placeables/index.d.ts
  types/foundry/client/pixi/placeables/sound.d.ts
  types/foundry/client/pixi/placeables/token.d.ts
Labels: pr: types update, pr: foundry v12

#14519 Fix status effect title bar and base image opacity in token HUD
  src/module/canvas/status-effects.ts
  src/styles/ui/_token-hud.scss
Labels: pr: foundry v12

#14521 Add new fields for v12 token config
  static/templates/scene/token/partials/appearance.hbs
  static/templates/scene/token/partials/identity.hbs
  static/templates/scene/token/partials/lighting.hbs
  static/templates/scene/token/sheet.hbs
Labels: pr: foundry v12

#14520 Convert all select handlebars helper in weapon sheet to selectOptions
  src/module/item/base/sheet/sheet.ts
  src/module/item/physical/sheet.ts
  src/module/item/weapon/sheet.ts
  static/templates/items/mystify-panel.hbs
  static/templates/items/physical-sidebar.hbs
  static/templates/items/weapon-details.hbs
  static/templates/partials/publication-data.hbs
Labels: pr: foundry v12

#14523 Begin creating types of application V2
  types/foundry/client-esm/applications/api/application.d.ts
  types/foundry/client-esm/applications/api/document-sheet.d.ts
  types/foundry/client-esm/applications/api/module.d.ts
  types/foundry/client-esm/applications/module.d.ts
  types/foundry/client-esm/applications/types.d.ts
  types/foundry/client/foundry/applications/index.d.ts
  types/foundry/client/foundry/index.d.ts
  types/foundry/index.d.ts
Labels: pr: types update, pr: foundry v12

#14525 Update and add grid types and move files to `common/grid/`
  src/module/canvas/token/object.ts
  types/foundry/client-esm/canvas/module.d.ts
  types/foundry/client-esm/canvas/scene-manager.d.ts
  types/foundry/client/foundry/index.d.ts
  types/foundry/client/pixi/grid/hexagonal-grid.d.ts
  types/foundry/client/pixi/grid/index.d.ts
  types/foundry/client/pixi/grid/module.d.ts
  types/foundry/client/pixi/grid/square-grid.d.ts
  types/foundry/client/pixi/groups/effects.d.ts
  types/foundry/client/pixi/module.d.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/grid/base.d.ts
  types/foundry/common/grid/grid-hex.d.ts
  types/foundry/common/grid/gridless.d.ts
  types/foundry/common/grid/hexagonal.d.ts
  types/foundry/common/grid/module.d.ts
  types/foundry/common/grid/square.d.ts
  types/foundry/index.d.ts
Labels: pr: types update, pr: foundry v12

#14524 Add `omit` and `pick` Handlebars helpers and revert some changes in weapon sheet
  src/module/item/weapon/sheet.ts
  src/scripts/handlebars.ts
  static/templates/items/weapon-details.hbs
Labels: pr: foundry v12

#14512 Add suboption for Hidden to wisp's Go Dark
  packs/abomination-vaults-bestiary/dread-wisp.json
  packs/abomination-vaults-bestiary/dune-candle.json
  packs/abomination-vaults-bestiary/groetan-candle.json
  packs/abomination-vaults-bestiary/sacuishu.json
  packs/abomination-vaults-bestiary/spellvoid.json
  packs/abomination-vaults-bestiary/will-o-the-deep.json
  packs/agents-of-edgewatch-bestiary/gloaming-will-o-wisp.json
  packs/kingmaker-bestiary/ancient-wisp.json
  packs/kingmaker-bestiary/spirit-of-stisshak.json
  packs/pathfinder-bestiary/will-o-wisp.json
  packs/pathfinder-monster-core/will-o-wisp.json
  packs/pfs-season-2-bestiary/urkhas-3-4.json
  packs/pfs-season-2-bestiary/urkhas-5-6.json
Labels: pr: data update

#14513 Add automation for Martyr
  packs/feats/martyr.json
  static/lang/re-en.json
Labels: pr: data update

#14533 Fix aura RE form
  src/module/item/base/sheet/rule-element-form/aura.ts
  src/styles/item/_rules.scss
  static/templates/items/rules/aura.hbs
Labels: pr: foundry v12

#14536 Refresh application v2 windows when hot reloading
  src/scripts/hooks/load.ts
Labels: pr: foundry v12

#14534 Fix Otyugh Filth Fever stage 1 duration
  packs/pathfinder-bestiary/otyugh.json
Labels: pr: data update

#14537 Restore darkvision vision mode
  src/module/canvas/perception/modes.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/pixi/perception/vision-mode.d.ts
Labels: pr: foundry v12

#14538 Bump `SUPPORTED_CORE_SCHEMA_VERSION` in pack builder
  build/lib/compendium-pack.ts
Labels: pr: foundry v12

#14540 Add types for new custom `HTMLElement`s and form field functions
  types/foundry/client-esm/applications/elements/color-picker.d.ts
  types/foundry/client-esm/applications/elements/document-tags.d.ts
  types/foundry/client-esm/applications/elements/file-picker.d.ts
  types/foundry/client-esm/applications/elements/form-element.d.ts
  types/foundry/client-esm/applications/elements/hue-slider.d.ts
  types/foundry/client-esm/applications/elements/module.d.ts
  types/foundry/client-esm/applications/elements/multi-select.d.ts
  types/foundry/client-esm/applications/elements/prosemirror-editor.d.ts
  types/foundry/client-esm/applications/elements/range-picker.d.ts
  types/foundry/client-esm/applications/elements/string-tags.d.ts
  types/foundry/client-esm/applications/forms/fields.d.ts
  types/foundry/client-esm/applications/module.d.ts
  types/foundry/client/ui/filepicker.d.ts
Labels: pr: types update, pr: foundry v12

#14532 Convert more select helpers to selectOptions
  src/module/actor/character/document.ts
  src/module/actor/data/base.ts
  src/module/actor/hazard/sheet.ts
  src/module/actor/hazard/types.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/scripts/macros/travel/travel-speed-sheet.ts
  static/templates/actors/army/sheet.hbs
  static/templates/actors/character/partials/strike.hbs
  static/templates/actors/hazard/partials/header.hbs
  static/templates/actors/hazard/partials/sidebar.hbs
  static/templates/actors/loot/sheet.hbs
  static/templates/gm/travel/travel-speed-sheet.hbs
  static/templates/items/class-details.hbs
Labels: pr: foundry v12

#14545 Run CI on pull requests for the `v12` branch
  .github/workflows/ci.yml
Labels: pr: housekeeping, pr: foundry v12

#14549 Convert remaining select helpers that don't require `getData` changes
  static/templates/items/feat-sidebar.hbs
  static/templates/items/lore-details.hbs
  static/templates/items/melee-details.hbs
  static/templates/items/partials/ability-activation.hbs
  static/templates/items/partials/apex.hbs
  static/templates/items/partials/duration.hbs
  static/templates/items/persistent-damage-dialog.hbs
  static/templates/items/rules/fast-healing.hbs
  static/templates/items/rules/flat-modifier.hbs
  static/templates/items/shield-details.hbs
  static/templates/items/spell-details.hbs
  static/templates/items/spell-overlay.hbs
  static/templates/popups/casting-item-create-dialog.hbs
  static/templates/system/settings/basic-setting.hbs
  static/templates/system/settings/homebrew.hbs
  static/templates/system/settings/variant-rules.hbs
  static/templates/system/settings/world-clock/index.hbs
  static/templates/system/tag-selector/senses.hbs
Labels: pr: foundry v12

#14535 Update user config overrides for v12
  src/module/user/sheet.ts
  static/templates/user/sheet.hbs
  types/foundry/build/generate-client-base-mixes.ts
  types/foundry/client-esm/applications/api/application.d.ts
  types/foundry/client-esm/applications/api/handlebars-application.d.ts
  types/foundry/client-esm/applications/api/module.d.ts
  types/foundry/client-esm/applications/module.d.ts
  types/foundry/client-esm/applications/sheets/module.d.ts
  types/foundry/client-esm/applications/sheets/user-config.d.ts
  types/foundry/client-esm/applications/types.d.ts
  types/foundry/client/application/form-application/document-sheet-config.d.ts
  types/foundry/client/application/form-application/document-sheet/index.d.ts
  types/foundry/client/application/form-application/document-sheet/user-config.d.ts
  types/foundry/client/apps/app.d.ts
  types/foundry/client/foundry/applications/sheets.d.ts
Labels: pr: types update, pr: foundry v12

#14527 [3XC4L1B3R ] Add Twin Trait Damage Support
  src/module/system/damage/weapon.ts
  static/lang/en.json
Labels: pr: enhancement

#14553 Handle `ChatMessage` deprecations
  src/module/actor/army/document.ts
  src/module/actor/base.ts
  src/module/actor/character/crafting/helpers.ts
  src/module/actor/character/helpers.ts
  src/module/actor/item-transfer.ts
  src/module/actor/sheet/popups/distribute-coins-popup.ts
  src/module/actor/sheet/popups/identify-popup.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/canvas/status-effects.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/base/document.ts
  src/module/rules/rule-element/fast-healing.ts
  src/scripts/macros/check-prompt/prompt.ts
  src/scripts/macros/earn-income/helpers.ts
  src/scripts/macros/encouraging-words.ts
  src/scripts/macros/hotbar.ts
  src/scripts/macros/raise-a-shield.ts
  src/scripts/macros/rest-for-the-night.ts
  src/scripts/macros/steel-your-resolve.ts
  src/scripts/macros/treat-wounds.ts
  types/foundry/common/constants.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/common/documents/chat-message.d.ts
Labels: pr: foundry v12

#14546 Convert more select helpers to selectOptions
  src/module/actor/character/sheet.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/hazard/types.ts
  src/module/actor/loot/sheet.ts
  src/module/actor/party/kingdom/builder.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/sheet/data-types.ts
  src/module/actor/vehicle/sheet.ts
  src/module/item/affliction/sheet.ts
  src/module/item/ancestry/sheet.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/consumable/sheet.ts
  src/module/item/physical/sheet.ts
  src/module/item/weapon/sheet.ts
  static/templates/actors/character/partials/proficiencylevels-dropdown.hbs
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/npc/partials/sidebar.hbs
  static/templates/actors/npc/tabs/spells.hbs
  static/templates/actors/party/kingdom/builder.hbs
  static/templates/actors/party/kingdom/partials/settlement.hbs
  static/templates/actors/party/kingdom/tabs/activities.hbs
  static/templates/actors/vehicle/sidebar.hbs
  static/templates/actors/vehicle/vehicle-header.hbs
  static/templates/chat/check-modifiers-dialog.hbs
  static/templates/chat/damage/damage-modifier-dialog.hbs
  static/templates/chat/roll-dialog.hbs
  static/templates/compendium-browser/filters.hbs
  static/templates/items/activation-panel.hbs
  static/templates/items/affliction-details.hbs
  static/templates/items/affliction-sidebar.hbs
  static/templates/items/ancestry-sidebar.hbs
  static/templates/items/armor-details.hbs
  static/templates/items/backpack-details.hbs
  static/templates/items/campaign-feature-sidebar.hbs
  static/templates/items/consumable-details.hbs
Labels: pr: foundry v12

#14550 Fix combat tracker config and `actorsDeadAtZero` option
  src/module/actor/base.ts
  src/scripts/hooks/close-combat-tracker-config.ts
  src/scripts/hooks/render-combat-tracker-config.ts
  static/templates/sidebar/encounter-tracker/config.hbs
Labels: pr: foundry v12

#14561 Remove features deprecated until version v12
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/actor/initiative.ts
  src/module/item/physical/coins.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/system/statistic/statistic.ts
  src/scripts/config/index.ts
Labels: pr: foundry v12

#14470 Support resolvables in actor traits form
  src/module/item/base/sheet/rule-element-form/actor-traits.ts
Labels: pr: bugfix

#14564 Update party actor styling for v12
  src/styles/ui/sidebar/_actor-directory.scss
Labels: pr: foundry v12
