Repository foundryvtt/pf2e, pull requests merged in 2024-11, with the labels that each got.

#17104 Convert Rewrite Fate into an action and GrantItems to the Mythic Callings to add it
  packs/actions/rewrite-fate.json
  packs/classfeatures/acrobats-calling.json
  packs/classfeatures/artisans-calling.json
  packs/classfeatures/bookkeepers-calling.json
  packs/classfeatures/caretakers-calling.json
  packs/classfeatures/demagogues-calling.json
  packs/classfeatures/guardians-calling.json
  packs/classfeatures/handlers-calling.json
  packs/classfeatures/hunters-calling.json
  packs/classfeatures/sages-calling.json
  packs/classfeatures/thespians-calling.json
  packs/classfeatures/thiefs-calling.json
Labels: pr: data update

#17103 Incorporate errata for War of the Immortals from the Variant Rules PDF
  packs/feats/exemplar-dedication.json
  packs/feats/exultant-blood-magic.json
  packs/feats/surging-blood-magic.json
Labels: pr: data update

#17105 Organize Archetypes journal
  packs/journals/archetypes.json
Labels: pr: data update

#17102 Update select Feat names to use Chicago-style title format
  packs/feat-effects/effect-channel-the-godmind.json
  packs/feat-effects/effect-cut-from-the-air.json
  packs/feats/a-thousand-cries-for-help.json
  packs/feats/aegis-for-the-innocent.json
  packs/feats/all-in-my-head.json
  packs/feats/all-shall-end-in-flames.json
  packs/feats/arms-that-cut-the-waves.json
  packs/feats/army-of-one.json
  packs/feats/behold-a-pale-horse.json
  packs/feats/bloom-of-health.json
  packs/feats/break-the-causal-chain.json
  packs/feats/break-the-cycle.json
  packs/feats/breath-of-the-dragon-dragon-disciple.json
  packs/feats/bring-into-the-fold.json
  packs/feats/call-and-response.json
  packs/feats/call-of-the-green-man.json
  packs/feats/call-the-hunt.json
  packs/feats/call-the-worm.json
  packs/feats/call-to-battle.json
  packs/feats/channel-the-godmind.json
  packs/feats/claws-of-the-dragon.json
  packs/feats/cloak-of-poison.json
  packs/feats/coating-of-slime.json
  packs/feats/consult-the-stars.json
  packs/feats/correct-the-story.json
  packs/feats/creature-of-myth.json
  packs/feats/cry-of-rebellion.json
  packs/feats/cut-from-the-air.json
  packs/feats/death-from-above-eternal-legend.json
  packs/feats/decree-of-banishment.json
  packs/feats/decree-of-execution.json
  packs/feats/decree-of-prosperity.json
  packs/feats/decree-of-war.json
  packs/feats/defy-the-darkness.json
  packs/feats/dig-up-secrets.json
  packs/feats/ears-that-hear-the-truth.json
  packs/feats/earth-to-heavens-strike.json
  packs/feats/smash-from-the-air.json
  packs/journals/archetypes.json
Labels: pr: data update

#17101 Use toggle to tag unarmed attack as a weapon ikon
  packs/classfeatures/gleaming-blade.json
  packs/classfeatures/hands-of-the-wildling.json
  packs/classfeatures/titans-breaker.json
  packs/feats/vow-of-mortal-defiance.json
  static/lang/re-en.json
Labels: pr: data update

#17098 Fix browsing mythic callings when one isn't set
  src/module/actor/character/feats/group.ts
Labels: pr: bugfix

#17097 Add effects for Arcane Explosion and Diadem of Divine Radiance
  packs/spell-effects/spell-effect-arcane-explosion.json
  packs/spell-effects/spell-effect-diadem-of-divine-radiance.json
  packs/spells/arcane-explosion.json
  packs/spells/diadem-of-divine-radiance.json
Labels: pr: data update

#17096 Fix Fracture Mountain's immanence damage adjustment
  packs/actions/fracture-mountains.json
Labels: pr: data update

#17094 Brush up some WoI nephilim feats
  packs/actions/find-fault.json
  packs/feats/arise-ye-worthy.json
  packs/feats/bestial-manifestation.json
  packs/feats/debilitating-bomb.json
  packs/feats/extraplanar-cloud.json
  packs/feats/extraplanar-haze.json
  packs/feats/faultspawn.json
  packs/feats/glory-and-valor.json
  packs/feats/incredible-familiar.json
  packs/feats/intuitive-crafting.json
  packs/feats/irrepressible-halfling.json
  packs/feats/irrepressible-nephilim.json
  packs/feats/pandemonium-eruption.json
  packs/feats/proteankin.json
  packs/feats/resilient-physiology.json
  packs/feats/towering-presence.json
Labels: pr: data update

#17090 Brush up additional Equipment Effects descriptions and add icons
  packs/equipment-effects/effect-staff-of-illumination.json
  packs/equipment-effects/effect-static-snare.json
  packs/equipment-effects/effect-statue-skin-salve.json
  packs/equipment-effects/effect-stone-body-mutagen-greater.json
  packs/equipment-effects/effect-stone-body-mutagen-lesser.json
  packs/equipment-effects/effect-stone-body-mutagen-moderate.json
  packs/equipment-effects/effect-stone-fist-elixir.json
  packs/equipment-effects/effect-thorn-triad-armor-greater.json
  packs/equipment-effects/effect-thorn-triad-armor-major.json
  packs/equipment-effects/effect-thorn-triad-armor.json
  packs/equipment-effects/effect-thorn-triad-weapon-greater.json
  packs/equipment-effects/effect-thorn-triad-weapon-major.json
  packs/equipment-effects/effect-thorn-triad-weapon.json
  packs/equipment-effects/effect-thousand-year-dragonroot.json
  packs/equipment-effects/effect-throne-card.json
  packs/equipment-effects/effect-thundering-fury-dadao.json
  packs/equipment-effects/effect-thurible-of-revelation-greater.json
  packs/equipment-effects/effect-thurible-of-revelation-moderate.json
  packs/equipment-effects/effect-thurible-of-revelation.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing-greater.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing-lesser.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing-moderate.json
  packs/equipment-effects/effect-topology-protoplasm.json
  packs/equipment-effects/effect-trackers-stew.json
  packs/equipment-effects/effect-tremorsensors.json
  packs/equipment-effects/effect-trinity-geode-armor-greater.json
  packs/equipment-effects/effect-trinity-geode-armor-major.json
  packs/equipment-effects/effect-trinity-geode-armor.json
  packs/equipment-effects/effect-trinity-geode-weapon-greater.json
  packs/equipment-effects/effect-trinity-geode-weapon-major.json
  packs/equipment-effects/effect-trinity-geode-weapon.json
  packs/equipment-effects/effect-tritons-conch.json
  packs/equipment-effects/effect-tteokguk-of-time-advancement.json
  packs/equipment-effects/effect-twist-the-skeins-of-fate.json
  packs/equipment-effects/effect-ugly-cutes-gift.json
  packs/equipment-effects/effect-vashus-ninth-life-diehard.json
  packs/equipment-effects/effect-vashus-ninth-life.json
  packs/equipment-effects/effect-vaultbreakers-harness.json
  packs/equipment-effects/effect-vengeful-demons-tears.json
  packs/equipment-effects/effect-vermin-repellent-agent-greater.json
  packs/equipment-effects/effect-vermin-repellent-agent-lesser.json
  packs/equipment-effects/effect-vermin-repellent-agent-major.json
  packs/equipment-effects/effect-vermin-repellent-agent-moderate.json
  packs/equipment-effects/effect-viper-rapier.json
  packs/equipment/trackers-stew.json
Labels: pr: data update

#17109 Make Energized Spark's suboptions mergeable
  packs/feats/energized-spark.json
Labels: pr: data update

#17108 Release Notes 6.6.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#17115 Add PFS glyph icon
  static/icons/pathfinder-society/pfs-glyph.webp
Labels: pr: static assets

#17116 Add Wither Away and fix Virulent Strike
  packs/feats/virulent-strike.json
  packs/feats/wither-away.json
Labels: pr: data update

#17120 Fix persistent damage and range for Earth's Bile
  packs/spells/earths-bile.json
Labels: pr: data update

#17121 Add effect for Safe Passage
  packs/iconics/samo-level-5.json
  packs/spell-effects/spell-effect-safe-passage.json
  packs/spells/safe-passage.json
  packs/wardens-of-wildwood-bestiary/emorga-all-seer.json
Labels: pr: data update

#17125 Fix ancestry slugs on Kholo and Tripkee heritages
  packs/heritages/kholo/ant-kholo.json
  packs/heritages/kholo/cave-kholo.json
  packs/heritages/kholo/dog-kholo.json
  packs/heritages/kholo/great-kholo.json
  packs/heritages/kholo/sweetbreath-kholo.json
  packs/heritages/kholo/winter-kholo.json
  packs/heritages/kholo/witch-kholo.json
  packs/heritages/tripkee/poisonhide-tripkee.json
  packs/heritages/tripkee/riverside-tripkee.json
  packs/heritages/tripkee/snaptongue-tripkee.json
  packs/heritages/tripkee/stickytoe-tripkee.json
  packs/heritages/tripkee/thickskin-tripkee.json
  packs/heritages/tripkee/windweb-tripkee.json
Labels: pr: data update

#17128 Fill gaps in crafting ability data created via RE, same with Talisman Esoterica feat
  packs/feats/talisman-esoterica.json
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/data.ts
  src/module/rules/rule-element/crafting-ability.ts
Labels: pr: bugfix, pr: data update

#17138 Fix a typo in description of come and get me
  packs/feats/come-and-get-me.json
Labels: pr: data update

#17124 Update additional instances of inline damage to the new format
  packs/age-of-ashes-bestiary/hezle.json
  packs/age-of-ashes-bestiary/scarlet-triad-enforcer.json
  packs/agents-of-edgewatch-bestiary/barnacle-ghoul.json
  packs/agents-of-edgewatch-bestiary/ravenile-rager.json
  packs/blood-lords-bestiary/creeping-crone.json
  packs/blood-lords-bestiary/drusilla.json
  packs/blood-lords-bestiary/ghoul-gnawer.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/blood-lords-bestiary/matron-uldrula.json
  packs/blood-lords-bestiary/shabti-votary.json
  packs/blood-lords-bestiary/shoki.json
  packs/blood-lords-bestiary/vanth-warrior.json
  packs/extinction-curse-bestiary/ginjana-mindkeeper.json
  packs/kingmaker-bestiary/nilak.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/kingmaker-bestiary/zorek.json
  packs/monsters-of-myth-bestiary/grogrisant.json
  packs/monsters-of-myth-bestiary/taljjae-the-grandmother.json
  packs/npc-gallery/priest-of-pharasma.json
  packs/paizo-pregens/savshin-starwatcher.json
  packs/pathfinder-bestiary/guardian-naga.json
  packs/pfs-season-3-bestiary/debased-relic.json
  packs/pfs-season-4-bestiary/travel-worn-lurker-in-light.json
  packs/pfs-season-5-bestiary/arcadian-lurker-in-light.json
  packs/pfs-season-5-bestiary/jamimpi.json
  packs/pfs-season-5-bestiary/resolved-jamimpi.json
  packs/quest-for-the-frozen-flame-bestiary/jesseri-the-hailstorm.json
  packs/sky-kings-tomb-bestiary/stoneriver.json
  packs/strength-of-thousands-bestiary/terwa-star-reader.json
Labels: pr: data update

#17140 Add `release.generation` check to retrieval of setting moved in V13
  src/module/actor/sheet/base.ts
Labels: pr: foundry v13

#17127 Brush up select Equipment and Feat effects
  packs/equipment-effects/effect-voice-of-oceans.json
  packs/equipment-effects/effect-wand-of-fey-flames.json
  packs/equipment-effects/effect-warding-statuette-armor-greater.json
  packs/equipment-effects/effect-warding-statuette-armor.json
  packs/equipment-effects/effect-whispering-staff-ally.json
  packs/equipment-effects/effect-whispering-staff-enemy.json
  packs/equipment-effects/effect-winged-sandals.json
  packs/equipment-effects/effect-wyrm-claw-armor-greater.json
  packs/equipment-effects/effect-wyrm-claw-armor-major.json
  packs/equipment-effects/effect-wyrm-claw-armor.json
  packs/feat-effects/effect-accept-echo.json
  packs/feat-effects/effect-alloy-flesh-and-steel.json
  packs/feat-effects/effect-ancestral-influence.json
  packs/feat-effects/effect-anoint-ally.json
  packs/feat-effects/effect-arcane-propulsion.json
  packs/feat-effects/effect-armor-tampered-with-critical-success.json
  packs/feat-effects/effect-armor-tampered-with-success.json
  packs/feat-effects/effect-assisting-shot.json
  packs/feat-effects/effect-augment-senses.json
  packs/feat-effects/effect-aura-junction-air.json
  packs/feat-effects/effect-aura-of-preservation.json
  packs/feat-effects/effect-benefactors-majesty.json
  packs/feat-effects/effect-benevolent-spirit-deck.json
  packs/feat-effects/effect-blizzard-evasion.json
  packs/feat-effects/effect-bone-spikes.json
  packs/feat-effects/effect-bone-swarm.json
  packs/feat-effects/effect-born-to-the-trees.json
  packs/feat-effects/effect-brightness-seeker.json
  packs/feat-effects/effect-cant-fall-here.json
  packs/feat-effects/effect-catfolk-dance.json
  packs/feat-effects/effect-celestial-yaoguai-might.json
  packs/feat-effects/effect-ceremony-of-protection.json
  packs/feat-effects/effect-change-shape-werecreature.json
  packs/feat-effects/effect-combat-mentor-boon-pfs.json
  packs/feat-effects/effect-consume-energy-augment-strike.json
  packs/feat-effects/effect-control-tower.json
  packs/feat-effects/effect-creeping-ashes.json
  packs/feat-effects/effect-cringe.json
  packs/feat-effects/effect-curse-of-engulfing-flames.json
  packs/feat-effects/effect-curse-of-outpouring-life.json
  packs/feat-effects/effect-curse-of-the-perpetual-storm.json
  packs/feat-effects/effect-curse-of-turbulent-moments.json
  packs/feat-effects/effect-cut-from-the-air.json
  packs/feat-effects/effect-daydream-trance.json
  packs/feat-effects/effect-defensive-instincts.json
  packs/feat-effects/effect-deitys-protection.json
  packs/feat-effects/effect-demonic-blood-magic.json
Labels: pr: data update

#17147 Add fallback font-family for `[data-pf2-glyph]` css selector
  src/styles/_globals.scss
Labels: pr: bugfix

#17143 Update Triumph of the Tusk backgrounds to use Remaster terminology
  packs/backgrounds/badlands-scout.json
  packs/backgrounds/belkzen-anthropologist.json
  packs/backgrounds/empty-hand-loyalist.json
  packs/backgrounds/foreign-diplomat.json
  packs/backgrounds/self-made.json
  packs/backgrounds/trade-representative.json
Labels: pr: data update

#17148 Fix action cost of Nymph's Grace focus spell
  packs/spells/nymphs-grace.json
Labels: pr: data update

#17142 Consolidate Chromatic Jellyfish Oil Effect
  build/uuid-redirects.json
  packs/equipment-effects/effect-chromatic-jellyfish-oil-greater.json
  packs/equipment-effects/effect-chromatic-jellyfish-oil-lesser.json
  packs/equipment-effects/effect-chromatic-jellyfish-oil-moderate.json
  packs/equipment-effects/effect-chromatic-jellyfish-oil.json
  packs/equipment-effects/effect-wine-of-the-blood.json
  packs/equipment/chromatic-jellyfish-oil-greater.json
  packs/equipment/chromatic-jellyfish-oil-lesser.json
  packs/equipment/chromatic-jellyfish-oil-moderate.json
Labels: pr: data update

#17151 Convert additional instances of inline damage to the new format
  packs/age-of-ashes-bestiary/rinnarv-bontimar.json
  packs/age-of-ashes-bestiary/tixitog.json
  packs/agents-of-edgewatch-bestiary/kharnass-lesser-glyph.json
  packs/blood-lords-bestiary/eseneth.json
  packs/blood-lords-bestiary/ghoul-antipaladin.json
  packs/blood-lords-bestiary/ghoul-razorclaw.json
  packs/blood-lords-bestiary/harmony-in-agony.json
  packs/blood-lords-bestiary/hyrune-loxenna.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/blood-lords-bestiary/opkherab.json
  packs/blood-lords-bestiary/pyrogeist.json
  packs/blood-lords-bestiary/vampire-guardian.json
  packs/blood-lords-bestiary/vampire-rival-necromancer.json
  packs/blood-lords-bestiary/weeping-jack.json
  packs/blood-lords-bestiary/yurgak.json
  packs/extinction-curse-bestiary/vavakia.json
  packs/kingmaker-bestiary/bloom-cultist.json
  packs/kingmaker-bestiary/darivan.json
  packs/kingmaker-bestiary/the-misbegotten-troll.json
  packs/pfs-season-4-bestiary/bolger-trusk-5-6.json
  packs/pfs-season-4-bestiary/bolger-trusk-7-8.json
  packs/pfs-season-4-bestiary/evasive-vampire-count.json
  packs/pfs-season-4-bestiary/weak-evasive-vampire-count.json
  packs/pfs-season-6-bestiary/averill-quint-5-6.json
  packs/seven-dooms-for-sandpoint-bestiary/kanker.json
  packs/seven-dooms-for-sandpoint-bestiary/wolgur-wrabs.json
  packs/sky-kings-tomb-bestiary/corrupted-blade-spirit.json
  packs/stolen-fate-bestiary/diskrasia-the-sharp.json
  packs/stolen-fate-bestiary/fabrina-the-spinster.json
  packs/stolen-fate-bestiary/hala-the-rod.json
  packs/stolen-fate-bestiary/ndede.json
  packs/strength-of-thousands-bestiary/tatterthread.json
Labels: pr: data update

#17155 Add missing implementation of WoI multiclass archetypes
  packs/feats/animist-dedication.json
  packs/feats/basic-glory.json
  packs/feats/expert-animist-spellcasting.json
  packs/feats/master-animist-spellcasting.json
  packs/feats/spiritual-awakening.json
Labels: pr: data update

#17153 Remove Shrink the Span feat
  packs/feats/shrink-the-span.json
Labels: pr: data update

#17146 Add support for damage tag alterations
  src/module/rules/rule-element/damage-alteration/alteration.ts
  src/module/rules/rule-element/damage-alteration/rule-element.ts
  src/module/system/damage/types.ts
Labels: pr: enhancement

#17158 Add tags to validation for damage alterations
  src/module/rules/rule-element/damage-alteration/rule-element.ts
Labels: pr: bugfix

#17162 Add ability for features to disable other features
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/character/feats/group.ts
  src/module/actor/character/feats/types.ts
  src/module/item/ability/helpers.ts
  src/module/item/ability/sheet.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/deity/sheet.ts
  src/module/item/feat/data.ts
  src/module/item/feat/document.ts
  src/module/item/feat/helpers.ts
  src/module/item/feat/sheet.ts
  src/module/sheet/helpers.ts
  static/lang/en.json
  static/templates/items/deity-details.hbs
  static/templates/items/feat-details.hbs
Labels: pr: enhancement

#17163 Automate Monk Expertise spellcasting upgrade
  packs/classfeatures/monk-expertise.json
  packs/feats/jalmeri-heavenseeker-dedication.json
Labels: pr: data update

#17131 Change sakura's sprig to remaster terms
  packs/equipment/sakuras-sprig.json
Labels: pr: data update

#17133 Add automation for The Bigger They Are
  packs/feat-effects/effect-the-bigger-they-are.json
  packs/feats/the-bigger-they-are.json
  static/lang/re-en.json
Labels: pr: data update

#17139 Complete the missing Tian Xia Character Guide Archetypes in the `Archetypes` Journal
  packs/journals/archetypes.json
Labels: pr: data update

#17144 Brush up Class Journal Entries - Alchemist to Cleric
  packs/journals/classes.json
Labels: pr: data update

#17152 Brush up some Hellknight Order benefits
  packs/classfeatures/order-of-the-godclaw.json
  packs/feats/blessing-of-the-five.json
  packs/feats/disillusionment.json
  packs/feats/fear-no-law-fear-no-one.json
  packs/feats/locate-lawbreakers.json
  packs/feats/reveal-beasts.json
  packs/feats/seek-injustice.json
  packs/feats/shackles-of-law.json
  packs/feats/sturdy-bindings.json
Labels: pr: data update

#17154 Implement Crash Against Me's resistance and add notes on triggering attacks
  packs/actions/crash-against-me.json
  packs/classfeatures/skin-hard-as-horn.json
  packs/feat-effects/effect-crash-against-me-clang.json
  packs/feat-effects/effect-crash-against-me-note.json
  packs/feat-effects/effect-crash-against-me.json
  static/lang/re-en.json
Labels: pr: data update

#17161 Tag Flowing Spirit Strike damage allowing Energized Spark's alteration
  packs/actions/flowing-spirit-strike.json
Labels: pr: data update

#17164 Suppress Surprise Attack and Shield Block from Avenger and Warrior of Legend archetypes
  packs/classfeatures/avenger.json
  packs/classfeatures/warrior-of-legend.json
Labels: pr: data update

#17169 Add PFS Glyph to select Pathfinder Society Boons
  packs/pathfinder-society-boons/evolving-destiny.json
  packs/pathfinder-society-boons/heroic-aegis.json
  packs/pathfinder-society-boons/inherited-wayfinder.json
  packs/pathfinder-society-boons/lantern-lodge-gear.json
  packs/pathfinder-society-boons/nexus-house-gear.json
  packs/pathfinder-society-boons/open-road-lodge-gear.json
  packs/pathfinder-society-boons/pathfinder-society-second-edition-replay.json
  packs/pathfinder-society-boons/penitent-pathfinder.json
  packs/pathfinder-society-boons/second-chance.json
  packs/pathfinder-society-boons/steady-hand.json
  packs/pathfinder-society-boons/treasure-bundle-insurance.json
  packs/pathfinder-society-boons/ward-against-fiends.json
  packs/pathfinder-society-boons/world-traveler.json
Labels: pr: data update

#17171 Fix processing of concussive trait in damage application
  src/module/system/damage/iwr.ts
Labels: pr: bugfix

#17173 fix issue with PFS boons not displaying on character sheet
  static/templates/actors/character/tabs/pfs.hbs
Labels: pr: bugfix

#17159 Fix `DamageContext##findMatchingCheckContext`
  src/module/actor/roll-context/damage.ts
Labels: pr: bugfix

#17179 Correct level of Avalanche Strike in Marshal archetype journal page
  packs/journals/archetypes.json
Labels: pr: data update

#16959 Add effects for Albatross Curse
  packs/spell-effects/spell-effect-albatross-curse-critical-failure.json
  packs/spell-effects/spell-effect-albatross-curse-failure.json
  packs/spells/albatross-curse.json
Labels: pr: data update

#17168 Brush up select Class journal Entries (Druid to Investigator) and Armor Expertise class feature
  packs/classfeatures/armor-expertise.json
  packs/journals/classes.json
Labels: pr: data update

#17180 Correct Fracture Mountains immanence damage adjustment
  packs/actions/fracture-mountains.json
  packs/classfeatures/titans-breaker.json
Labels: pr: data update

#17185 Update predicate on Mental Buffer feat
  packs/feats/mental-buffer.json
Labels: pr: data update

#17187 Fix predicate on Barrow's Edge existing weapon choice set
  packs/classfeatures/barrows-edge.json
  packs/feat-effects/effect-shadow-sheath-weapon.json
Labels: pr: data update

#17183 Update additional instances of inline damage to the new format
  packs/blood-lords-bestiary/vampire-taviah.json
  packs/blood-lords-bestiary/zombie-horse.json
  packs/book-of-the-dead-bestiary/bone-croupier.json
  packs/book-of-the-dead-bestiary/minister-of-tumult.json
  packs/book-of-the-dead-bestiary/provincial-jiang-shi.json
  packs/book-of-the-dead-bestiary/vetalarana-manipulator.json
  packs/classfeatures/chalice.json
  packs/crown-of-the-kobold-king-bestiary/charge-of-the-spear-legion.json
  packs/crown-of-the-kobold-king-bestiary/narlynark.json
  packs/crown-of-the-kobold-king-bestiary/the-last-crucible.json
  packs/curtain-call-bestiary/izhkarial.json
  packs/deities/jin-li.json
  packs/deities/kalekot.json
  packs/deities/lubaiko.json
  packs/deities/luhar.json
  packs/deities/marishi.json
  packs/deities/mazludeh.json
  packs/deities/picoperi.json
  packs/deities/thisamet.json
  packs/deities/tlehar.json
Labels: pr: data update

#17166 Convert UUIDs for suppressed features
  build/lib/compendium-pack.ts
  packs/classfeatures/avenger.json
  packs/classfeatures/warrior-of-legend.json
Labels: pr: housekeeping

#17191 Include damage type in base weapon splash damage when building formulas
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#17189 Condense Brewer's Regret equipment effect
  build/uuid-redirects.json
  packs/equipment-effects/effect-brewers-regret-greater.json
  packs/equipment-effects/effect-brewers-regret.json
  packs/equipment/brewers-regret-greater.json
Labels: pr: data update

#17192 Fix unlocalized string in npc sheet
  static/templates/actors/partials/spell-collection.hbs
Labels: localization

#17186 Brush up additional entries in the Class Journal (Kineticist to Psychic) and class features
  packs/classfeatures/oracle-spellcasting.json
  packs/classfeatures/psychic-spellcasting.json
  packs/journals/classes.json
Labels: pr: data update

#17198 Correct Thunder God's Fan prerequisite to match Player Core 2
  packs/feats/thunder-gods-fan.json
Labels: pr: data update

#17197 Change Eternal Legend Dedication to be a class feat
  packs/feats/eternal-legend-dedication.json
Labels: pr: data update

#17200 Add prerequisites to Animist Dedication feats and update select Archetype journal entries to use `@Embed`
  packs/feats/animist-dedication.json
  packs/feats/animists-power.json
  packs/feats/apparition-magic.json
  packs/feats/basic-animist-spellcasting.json
  packs/feats/expert-animist-spellcasting.json
  packs/feats/master-animist-spellcasting.json
  packs/feats/spiritual-awakening.json
  packs/journals/archetypes.json
Labels: pr: data update

#17190 Fix npc variant skill labels not accounting for already enabled variants
  src/module/actor/npc/document.ts
Labels: pr: bugfix

#17207 Show color coded degree of success in chat damage messages
  src/module/system/damage/damage.ts
  src/styles/ui/sidebar/chat/_check.scss
  static/templates/chat/action/header.hbs
Labels: pr: enhancement

#17210 Add base weapon type to Fighting Stick
  packs/equipment/fighting-stick.json
Labels: pr: data update

#17209 Add missing concentrate and manipulate traits to Phoenix Ward
  packs/spells/phoenix-ward.json
Labels: pr: data update

#17201 Localize Quick Climb and Quick Swim notes and update the latter's value
  packs/feats/quick-climb.json
  packs/feats/quick-swim.json
  static/lang/re-en.json
Labels: pr: data update

#17211 Update conscious mind Damage Dice overrides to Damage Alteration
  packs/classfeatures/barrows-edge.json
  packs/classfeatures/the-distant-grasp.json
  packs/classfeatures/the-oscillating-wave.json
  packs/classfeatures/the-silent-whisper.json
  packs/classfeatures/the-tangible-dream.json
  packs/classfeatures/the-unbound-step.json
Labels: pr: data update

#17208 Predicate Unleash Psyche's bonus on `psi-cantrip` tag
  packs/feat-effects/effect-unleash-psyche.json
Labels: pr: data update

#17216 Brush up additional Class and Archetype journal entries
  packs/feats/druid-dedication.json
  packs/feats/exemplar-dedication.json
  packs/journals/archetypes.json
  packs/journals/classes.json
Labels: pr: data update

#17030 Add spell variants for flurry of claws and rename old spell effect
  packs/fists-of-the-ruby-phoenix-bestiary/yabin-the-just-level-13.json
  packs/fists-of-the-ruby-phoenix-bestiary/yabin-the-just-level-9.json
  packs/kingmaker-bestiary/phomandala.json
  packs/spell-effects/spell-effect-dragon-claws.json
  packs/spells/flurry-of-claws.json
Labels: pr: data update

#17221 Brush up effect for Deep Freeze
  packs/feat-effects/effect-deep-freeze.json
Labels: pr: data update

#17219 Update 1st-level rollable tables
  packs/rollable-tables/1st-level-consumables.json
  packs/rollable-tables/1st-level-permanent-items.json
Labels: pr: data update

#17220 Update 2nd-level rollable tables
  packs/rollable-tables/2nd-level-consumables.json
  packs/rollable-tables/2nd-level-permanent-items.json
Labels: pr: data update

#17217 Update additional instances of inline damage to the newer format
  packs/deities/uvuko.json
  packs/deities/walkena.json
  packs/deities/yelayne.json
  packs/equipment/grub-gloves-greater.json
  packs/equipment/grub-gloves-lesser.json
  packs/equipment/grub-gloves-moderate.json
  packs/equipment/singing-shortbow-greater.json
  packs/equipment/singing-shortbow.json
  packs/equipment/the-waxworks.json
  packs/equipment/wand-of-splintered-sorrows-rank-2.json
  packs/equipment/wand-of-splintered-sorrows-rank-4.json
  packs/equipment/wand-of-splintered-sorrows-rank-6.json
  packs/equipment/wand-of-splintered-sorrows-rank-8.json
  packs/extinction-curse-bestiary/ulthadar.json
  packs/extinction-curse-bestiary/urushil.json
  packs/extinction-curse-bestiary/zinogyvaz.json
  packs/feats/ambush-bladderwort.json
  packs/fists-of-the-ruby-phoenix-bestiary/kannitri.json
  packs/gatewalkers-bestiary/pholebis.json
  packs/gatewalkers-bestiary/yaiafineti.json
  packs/iconics/feiya-level-1.json
  packs/iconics/feiya-level-3.json
  packs/iconics/feiya-level-5.json
Labels: pr: data update

#17226 Update 3rd-level rollable tables
  packs/rollable-tables/3rd-level-consumables.json
  packs/rollable-tables/3rd-level-permanent-items.json
Labels: pr: data update

#17225 Add Game Hunter (Target) effect
  packs/feat-effects/effect-game-hunter-critical-failure.json
  packs/feat-effects/effect-game-hunter-failure.json
  packs/feats/game-hunter-dedication.json
  static/lang/re-en.json
Labels: pr: data update

#17232 Add effect links to Game Hunter
  packs/feat-effects/effect-game-hunter-critical-failure.json
  packs/feat-effects/effect-game-hunter-failure.json
  packs/feats/game-hunter-dedication.json
Labels: pr: data update

#17227 Update 4th-level rollable tables
  packs/rollable-tables/4th-level-consumables-items.json
  packs/rollable-tables/4th-level-permanent-items.json
Labels: pr: data update

#17229 Update 6th-level rollable tables
  packs/rollable-tables/6th-level-consumables-items.json
  packs/rollable-tables/6th-level-permanent-items.json
Labels: pr: data update

#17235 Fix immunities of Animated Armor
  packs/pathfinder-monster-core/animated-armor.json
Labels: pr: data update

#17238 Add some equipment effects
  packs/equipment-effects/effect-purple-pepper-powder.json
  packs/equipment-effects/effect-shift-scales.json
  packs/equipment/purple-pepper-powder.json
  packs/equipment/zetogeki-hide-armor.json
Labels: pr: data update

#17237 Fix malformed Embed
  packs/journals/classes.json
Labels: pr: data update

#17245 Only show a single empty slot with remaining count when prepared crafting
  src/module/actor/character/crafting/ability.ts
  src/styles/actor/character/_crafting.scss
  static/lang/en.json
  static/templates/actors/character/tabs/crafting.hbs
Labels: ui/ux

#17228 Update 5th-level rollable tables
  packs/rollable-tables/5th-level-consumables-items.json
  packs/rollable-tables/5th-level-permanent-items.json
Labels: pr: data update

#17248 Fix Assurance grant of Farmhand background
  packs/backgrounds/farmhand.json
  packs/spell-effects/spell-effect-enlarge.json
Labels: pr: data update

#17249 Replace `FixedProficiency` RE on Object Memory spell effect
  packs/spell-effects/spell-effect-object-memory-weapon.json
  static/lang/re-en.json
Labels: pr: data update

#17170 Refactor Sneak Attack to be tag-based and add missing Avenger features
  packs/actions/mark-for-death.json
  packs/classfeatures/avenger.json
  packs/classfeatures/ruffian.json
  packs/classfeatures/sneak-attack.json
  packs/feats/shadow-sneak-attack.json
  packs/feats/sly-striker.json
Labels: pr: data update

#17250 Predicate Avenger's sneak attack on Hunted Prey toggle
  packs/classfeatures/avenger.json
Labels: pr: data update

#17247 Fix width of inputs in choice set prompts
  src/styles/system/_choice-set-prompt.scss
Labels: pr: bugfix, ui/ux

#17260 Fix various War of Immortals sources
  packs/bestiary-family-ability-glossary/mythic-undying-myth.json
  packs/classfeatures/sages-calling.json
  packs/classfeatures/warrior-of-legend.json
  packs/equipment-effects/effect-smoky-protections.json
  packs/equipment/wandering-pipe.json
  packs/feat-effects/effect-a-challenge-for-heroes.json
  packs/feat-effects/effect-eye-catching-spot.json
  packs/feats/become-shadow.json
  packs/feats/fight-through-oblivion.json
  packs/feats/godling-dedication.json
  packs/feats/mythic-refocus.json
Labels: pr: data update

#17257 Replace some NPCs Reactive Strike action with the one from the Bestiary Ability Glossary
  packs/howl-of-the-wild-bestiary/mocking-chorus.json
  packs/howl-of-the-wild-bestiary/prismhydra.json
  packs/howl-of-the-wild-bestiary/sunscale-serpent.json
  packs/howl-of-the-wild-bestiary/tyrafdir.json
  packs/howl-of-the-wild-bestiary/wereshark.json
  packs/quest-for-the-frozen-flame-bestiary/desiak.json
Labels: pr: data update

#17259 Add `ConditionTypeCursebound` to en.json
  static/lang/en.json
Labels: pr: data update

#17258 Update Cytillesh Oil damage rolls to match Player Core 2
  packs/equipment/cytillesh-oil.json
Labels: pr: data update

#17262 Fix xulgath leader weakening strike
  packs/pathfinder-monster-core/xulgath-leader.json
Labels: pr: data update

#17264 Fix Marshal Dedication skill Choice Set values
  packs/feat-effects/effect-marshals-aura.json
  packs/feats/marshal-dedication.json
Labels: pr: data update

#17265 Brush up description for Effect: Marshal's Aura
  packs/feat-effects/effect-marshals-aura.json
Labels: pr: data update

#17266 Add effects for Absorb Shock and Electric Surge
  packs/bestiary-effects/effect-absorb-shock.json
  packs/bestiary-effects/effect-electric-surge.json
  packs/kingmaker-bestiary/shambler.json
  packs/pathfinder-bestiary/shambler.json
  packs/wardens-of-wildwood-bestiary/stormdrinker.json
Labels: pr: data update

#17263 Fix missing spaces in embedded prereqs
  src/module/item/campaign-feature/document.ts
  src/module/item/feat/document.ts
Labels: pr: bugfix

#17268 Add life link healing
  packs/spells/life-link.json
Labels: pr: data update

#17267 Add spell effect for Runic Weapon
  packs/spell-effects/spell-effect-runic-impression.json
  packs/spells/runic-impression.json
Labels: pr: data update

#17255 Release Notes 6.6.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#17271 Fix browsing divine intercessions and pfs boons
  src/module/actor/character/feats/group.ts
  src/module/actor/character/sheet.ts
  src/module/apps/compendium-browser/index.ts
  static/templates/actors/character/tabs/effects.hbs
  static/templates/actors/character/tabs/pfs.hbs
Labels: pr: bugfix

#17027 Add "size sensitivity" to physical-item pricing, utilize in compendium browser
  src/module/actor/data/size.ts
  src/module/actor/sheet/base.ts
  src/module/apps/compendium-browser/index.ts
  src/module/item/physical/data.ts
  src/module/item/physical/document.ts
  src/module/item/physical/helpers.ts
  src/module/item/physical/schema.ts
  src/module/item/treasure/document.ts
Labels: pr: enhancement

#17272 Add "Calling" feature category, migrate callings
  build/run-migration.ts
  packs/classfeatures/acrobats-calling.json
  packs/classfeatures/artisans-calling.json
  packs/classfeatures/bookkeepers-calling.json
  packs/classfeatures/caretakers-calling.json
  packs/classfeatures/demagogues-calling.json
  packs/classfeatures/guardians-calling.json
  packs/classfeatures/handlers-calling.json
  packs/classfeatures/hunters-calling.json
  packs/classfeatures/sages-calling.json
  packs/classfeatures/thespians-calling.json
  packs/classfeatures/thiefs-calling.json
  src/module/item/feat/document.ts
  src/module/item/feat/sheet.ts
  src/module/item/feat/values.ts
  src/module/migration/migrations/934-mythic-calling-category.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data migration, pr: data update

#17273 Fix reroll using a hero point erroneously displaying for a mythic character
  src/module/actor/character/document.ts
  src/module/actor/character/feats/collection.ts
Labels: pr: bugfix

#17110 Preserve token ring on extraction and fix Nahoa and Samo tokens
  build/lib/extractor.ts
  packs/iconics/nahoa-level-1.json
  packs/iconics/nahoa-level-3.json
  packs/iconics/nahoa-level-5.json
  packs/iconics/samo-level-1.json
  packs/iconics/samo-level-3.json
  packs/iconics/samo-level-5.json
Labels: pr: data update, pr: enhancement

#17137 Fix non-alchemical items DC not showing in item identification dialog
  src/module/actor/sheet/popups/identify-popup.ts
  src/module/item/identification.ts
  static/templates/actors/identify-item.hbs
Labels: pr: bugfix

#17275 Add action cost to Wing Buffet
  packs/feats/wing-buffet.json
Labels: pr: data update

#17281 Change file with `PrimarySpriteMesh` class definition to d.ts file
  types/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.ts
Labels: pr: types update

#17282 Update `Quadtree` class and move to correct location
  types/foundry/client/pixi/core/containers/index.d.ts
  types/foundry/client/pixi/core/containers/quadtree.d.ts
  types/foundry/client/pixi/helpers/index.d.ts
Labels: pr: types update, pr: foundry v12

#17276 Fix minor RE localization errors
  static/lang/re-en.json
Labels: pr: data update

#16999 Convert familiar system data to `TypeDataModel`
  src/module/actor/base.ts
  src/module/actor/creature/data.ts
  src/module/actor/data/base.ts
  src/module/actor/data/model.ts
  src/module/actor/familiar/data.ts
  src/module/actor/familiar/document.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/module/data.ts
  src/module/item/ability/data.ts
  src/module/item/base/data/model.ts
  src/module/item/kit/data.ts
  src/module/item/melee/data.ts
  src/scripts/hooks/load.ts
  static/template.json
  types/foundry/client/config.d.ts
Labels: pr: refactor

#17039 Implement remaster styled advanced alchemy and Double, Double
  packs/feats/advanced-alchemy.json
  packs/feats/advanced-herbalism.json
  packs/feats/cauldron.json
  packs/feats/double-double.json
  packs/feats/herbalist-dedication.json
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/sheet.ts
  src/module/item/feat/document.ts
  src/module/rules/rule-element/crafting-ability.ts
  src/module/rules/rule-element/special-resource.ts
  static/lang/en.json
  static/lang/re-en.json
  static/templates/actors/character/tabs/crafting.hbs
Labels: pr: data update, pr: enhancement

#17284 Convert loot system data to `TypeDataModel`
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  src/module/actor/loot/data.ts
  src/module/actor/loot/document.ts
  src/module/migration/migrations/812-restructure-iwr.ts
  src/module/migration/migrations/882-spell-data-reorganization.ts
  src/module/migration/migrations/885-convert-alignment-damage.ts
  src/scripts/hooks/load.ts
  static/template.json
  types/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.ts
  types/foundry/common/data/fields.d.ts
Labels: pr: refactor

#17286 Adjust Armor Proficiency Choice Set to not be ignored
  packs/feats/armor-proficiency.json
  packs/feats/champion-dedication.json
Labels: pr: data update

#17287 Update additional instances of inline damage to the new format
  packs/iconics/feiya-level-5.json
  packs/kingmaker-bestiary/the-knurly-witch.json
  packs/pathfinder-monster-core/conspirator-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/cythnigot.json
  packs/pathfinder-monster-core/dero-magister.json
  packs/pathfinder-monster-core/gosreg.json
  packs/pathfinder-monster-core/lamia-matriarch.json
  packs/pathfinder-monster-core/phantom-beast.json
  packs/pathfinder-monster-core/raja-krodha.json
  packs/pfs-season-2-bestiary/teflar.json
  packs/season-of-ghosts-bestiary/akashti.json
  packs/season-of-ghosts-bestiary/argyrzei.json
  packs/season-of-ghosts-bestiary/false-governor.json
  packs/season-of-ghosts-bestiary/ijda.json
  packs/season-of-ghosts-bestiary/meokdan.json
  packs/season-of-ghosts-bestiary/noppera-bo-impersonator-occult.json
  packs/seven-dooms-for-sandpoint-bestiary/iazmilor.json
  packs/seven-dooms-for-sandpoint-bestiary/jordus-munt.json
  packs/wardens-of-wildwood-bestiary/izurran.json
Labels: pr: data update

#17293 Fix Disrupt Opposed Magic requirements formatting
  packs/feats/disrupt-opposed-magic.json
Labels: pr: data update

#17291 Convert party system data to `TypeDataModel`
  src/module/actor/party/data.ts
  src/module/actor/party/document.ts
  src/module/actor/party/invalid-campaign.ts
  src/module/actor/party/kingdom/builder.ts
  src/module/actor/party/kingdom/helpers.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/kingdom/types.ts
  src/module/actor/party/kingdom/values.ts
  src/module/actor/party/types.ts
  static/template.json
Labels: pr: refactor

#15578 Convert army system data to data model
  src/module/actor/army/data.ts
  src/module/actor/army/document.ts
  src/module/actor/army/types.ts
  src/module/actor/data/base.ts
  src/scripts/hooks/load.ts
  static/template.json
Labels: pr: refactor

#17294 Update Avenger and Spelldrinker's description to errata
  packs/classfeatures/avenger.json
  packs/feats/spelldrinker.json
Labels: pr: data update

#17302 Update Revitalizing Finisher Temporary HP formula
  packs/feat-effects/effect-revitalizing-finisher.json
Labels: pr: data update

#17306 Batch create and delete items when daily crafting
  src/module/actor/character/crafting/crafting.ts
  src/module/actor/helpers.ts
  src/module/actor/inventory/index.ts
Labels: pr: enhancement

#17313 Fix action cost of Spear Dancer
  packs/feats/spear-dancer.json
Labels: pr: data update

#17314 Ensure presence of resources in familiar system data
  src/module/actor/creature/document.ts
  src/module/actor/familiar/document.ts
  src/module/scene/helpers.ts
Labels: pr: bugfix

#17310 Add resource consumption support to daily prep crafting
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/crafting/crafting.ts
  src/module/actor/character/document.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/rules/rule-element/crafting-ability.ts
  static/lang/en.json
  static/templates/actors/character/tabs/crafting.hbs
Labels: pr: enhancement

#17317 Assign `PartySystemData` in load hook
  src/scripts/hooks/load.ts
Labels: pr: bugfix

#17298 Update 8th-level rollable tables
  packs/rollable-tables/8th-level-consumables-items.json
  packs/rollable-tables/8th-level-permanent-items.json
Labels: pr: data update

#17299 Update 9th-level rollable tables
  packs/rollable-tables/9th-level-consumables-items.json
  packs/rollable-tables/9th-level-permanent-items.json
Labels: pr: data update

#17300 Update 10th-level rollable tables
  packs/rollable-tables/10th-level-consumables-items.json
  packs/rollable-tables/10th-level-permanent-items.json
Labels: pr: data update

#17320 Update 11th-level rollable tables
  packs/rollable-tables/11th-level-consumables-items.json
  packs/rollable-tables/11th-level-permanent-items.json
Labels: pr: data update

#17321 Update 12th-level rollable tables
  packs/rollable-tables/12th-level-consumables-items.json
  packs/rollable-tables/12th-level-permanent-items.json
Labels: pr: data update

#17322 Update 13th-level rollable tables
  packs/rollable-tables/13th-level-consumables-items.json
  packs/rollable-tables/13th-level-permanent-items.json
Labels: pr: data update

#17323 Update 14th-level rollable tables
  packs/rollable-tables/14th-level-consumables-items.json
  packs/rollable-tables/14th-level-permanent-items.json
Labels: pr: data update

#17324 Update 15th-level rollable tables
  packs/rollable-tables/15th-level-consumables-items.json
  packs/rollable-tables/15th-level-permanent-items.json
Labels: pr: data update

#17325 Update 16th-level rollable tables
  packs/rollable-tables/16th-level-consumables-items.json
  packs/rollable-tables/16th-level-permanent-items.json
Labels: pr: data update

#17326 Update 17th-level rollable tables
  packs/rollable-tables/17th-level-consumables-items.json
  packs/rollable-tables/17th-level-permanent-items.json
Labels: pr: data update

#17327 Update 18th-level rollable tables
  packs/rollable-tables/18th-level-consumables.json
  packs/rollable-tables/18th-level-permanent-items.json
Labels: pr: data update

#17328 Update 19th-level rollable tables
  packs/rollable-tables/19th-level-consumables-items.json
  packs/rollable-tables/19th-level-permanent-items.json
Labels: pr: data update

#17330 Update 20-level rollable tables
  packs/rollable-tables/20th-level-consumable-items.json
  packs/rollable-tables/20th-level-permanent-items.json
Labels: pr: data update

#17331 Update Major Art Objects rollable table
  packs/rollable-tables/major-art-object.json
Labels: pr: data update

#17334 Replace selector with domain in Swashbuckler styles' bravado Roll Option
  packs/classfeatures/battledancer.json
  packs/classfeatures/braggart.json
  packs/classfeatures/fencer.json
  packs/classfeatures/gymnast.json
  packs/classfeatures/rascal.json
  packs/classfeatures/wit.json
Labels: pr: data update

#17341 Brush up Malevolence effect
  packs/campaign-effects/malevolence/malevolence.json
Labels: pr: data update

#17339 Add Marked for Death's roll option to its Sneak Attack damage predicate
  packs/actions/mark-for-death.json
Labels: pr: data update

#17354 Fix DC of Divine Revulsion for Redcap Cavalry
  packs/sky-kings-tomb-bestiary/redcap-cavalry.json
Labels: pr: data update

#17359 Correct Spectral Advance spell rank
  packs/spells/spectral-advance.json
Labels: pr: data update

#17349 Fix greater composer staff item bonus to performance
  packs/equipment/composer-staff-greater.json
Labels: pr: data update

#17346 Apply `@Embed` in Class Journals (Sorcerer to Wizard)
  packs/journals/classes.json
Labels: pr: data update

#17363 Show rarity in ABC picker options
  src/module/actor/character/apps/abc-picker/app.svelte
  src/module/actor/character/apps/abc-picker/app.ts
Labels: pr: enhancement, ui/ux

#17357 Add missing thievery check to Repelling Surge hazard
  packs/sky-kings-tomb-bestiary/repelling-surge.json
Labels: pr: data update

#17365 Fix fast healing on Bandersnatch
  packs/pathfinder-monster-core/bandersnatch.json
Labels: pr: data update

#17364 Fix item macros for actions without use buttons and support modifier keys
  src/module/chat-message/helpers.ts
  src/scripts/macros/hotbar.ts
Labels: pr: bugfix
