Repository foundryvtt/pf2e, pull requests merged in 2024-03, with the labels that each got.

#14021 Skip `_preUpdate`/calling RE update triggers on no-diff/non-recursiveactor updates
  src/module/actor/army/document.ts
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
Labels: pr: bugfix

#14009 Fix labels and slugs in Finisher migration
  packs/iconics/jirelle-level-1.json
  packs/iconics/jirelle-level-5.json
  packs/paizo-pregens/zathri.json
  src/module/migration/migrations/922-swashbuckler-finisher-suboptions.ts
Labels: pr: data migration, pr: data update

#14019 Brushup several spells
  packs/spells/aqueous-orb.json
  packs/spells/blister.json
  packs/spells/blistering-invective.json
  packs/spells/blood-vendetta.json
  packs/spells/bursting-bloom.json
  packs/spells/call-the-blood.json
  packs/spells/coral-eruption.json
  packs/spells/dehydrate.json
  packs/spells/dive-and-breach.json
  packs/spells/falling-stars.json
  packs/spells/fearful-feast.json
  packs/spells/firework-blast.json
  packs/spells/freezing-rain.json
  packs/spells/grisly-growths.json
  packs/spells/horizon-thunder-sphere.json
  packs/spells/life-draining-roots.json
  packs/spells/mad-monkeys.json
  packs/spells/manifold-lives.json
  packs/spells/noxious-vapors.json
  packs/spells/phantom-orchestra.json
  packs/spells/pollen-pods.json
  packs/spells/poltergeists-fury.json
  packs/spells/purifying-veil.json
  packs/spells/shadows-web.json
  packs/spells/signal-skyrocket.json
  packs/spells/stifling-stillness.json
Labels: pr: data update

#14020 Remove duplicate link to Cleanse Affliction from Holy Prayer Beads (Greater)
  packs/equipment/holy-prayer-beads-greater.json
  packs/equipment/holy-prayer-beads.json
Labels: pr: data update

#14024 Construct actors and items with proxies in `preImportFromJSON`
  src/module/actor/base.ts
  src/module/doc-helpers.ts
  src/module/item/base/document.ts
Labels: pr: bugfix

#14022 Add markdown support to item description addenda
  package-lock.json
  package.json
  src/module/item/helpers.ts
  static/templates/items/partials/addendum.hbs
  types/foundry/client/index.d.ts
  types/foundry/common/data/fields.d.ts
  types/foundry/package.json
Labels: pr: enhancement

#14029 Fix Spellstriker Staff to be specific item
  packs/equipment/spellstriker-staff-greater.json
  packs/equipment/spellstriker-staff-major.json
  packs/equipment/spellstriker-staff.json
Labels: pr: data update

#14025 Referesh copies of some spells
  packs/abomination-vaults-bestiary/urdefhan-blood-mage.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/blood-lords-bestiary/rival-necromancer.json
  packs/blood-lords-bestiary/skeleton-rival-necromancer.json
  packs/blood-lords-bestiary/vampire-rival-necromancer.json
  packs/blood-lords-bestiary/zombie-rival-necromancer.json
  packs/impossible-lands-bestiary/fleshforged-conformer.json
  packs/outlaws-of-alkenstar-bestiary/i.json
  packs/pathfinder-dark-archive/mother-mitera.json
  packs/pfs-season-4-bestiary/grace-of-the-owl.json
  packs/pfs-season-4-bestiary/nathatel-3-4.json
  packs/pfs-season-4-bestiary/nathatel-5-6.json
  packs/pfs-season-4-bestiary/nathatel-7-8.json
  packs/pfs-season-4-bestiary/nathatel.json
  packs/pfs-season-4-bestiary/suhko-3-4.json
  packs/pfs-season-4-bestiary/undead-nathatel.json
  packs/quest-for-the-frozen-flame-bestiary/turkek.json
  packs/rusthenge-bestiary/theiltemar.json
  packs/sky-kings-tomb-bestiary/bronwyl-holloward.json
  packs/sky-kings-tomb-bestiary/enraged-dream.json
  packs/sky-kings-tomb-bestiary/four-tooth.json
  packs/sky-kings-tomb-bestiary/hagegraf-royal-guard.json
  packs/sky-kings-tomb-bestiary/hryngar-assassin.json
  packs/sky-kings-tomb-bestiary/hryngar-battlepriest.json
  packs/sky-kings-tomb-bestiary/hryngar-forgepriest.json
  packs/sky-kings-tomb-bestiary/hryngar-kings-agent.json
  packs/sky-kings-tomb-bestiary/hryngar-officer.json
  packs/sky-kings-tomb-bestiary/hryngar-rager.json
  packs/sky-kings-tomb-bestiary/hryngar-skull-collector.json
  packs/sky-kings-tomb-bestiary/hryngar-veteran.json
  packs/sky-kings-tomb-bestiary/narseigus-wormcaller.json
  packs/sky-kings-tomb-bestiary/ulat-kini-mindreaver.json
  packs/spells/blister.json
  packs/strength-of-thousands-bestiary/serpentfolk-venom-caller.json
Labels: pr: data update

#14026 Correct Caustic Blast persistent damage
  packs/iconics/ezren-level-1.json
  packs/spells/caustic-blast.json
Labels: pr: data update

#14027 Make shield auxiliary actions available when in stances that restrict strikes
  src/module/actor/character/document.ts
  src/module/actor/data/base.ts
  src/module/actor/helpers.ts
  src/module/rules/rule-element/strike.ts
  static/templates/actors/character/partials/strike.hbs
Labels: pr: bugfix

#14010 Automate various Swashbuckler features
  packs/actions/confident-finisher.json
  packs/actions/opportune-riposte.json
  packs/classfeatures/continuous-flair.json
  packs/classfeatures/eternal-confidence.json
  packs/classfeatures/exemplary-finisher.json
  packs/feat-effects/effect-continuous-flair.json
  packs/feat-effects/effect-exemplary-finisher-wit.json
  packs/feats/felicitous-riposte.json
  packs/feats/impossible-riposte.json
  packs/feats/precise-finisher.json
  static/lang/re-en.json
Labels: pr: data update

#14032 Add EpemeralEffect to Tumble Behind
  packs/feats/tumble-behind-rogue.json
  packs/feats/tumble-behind-swashbuckler.json
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#14008 Brush up description of Devil's Trident
  packs/equipment/devils-trident.json
Labels: pr: data update

#14036 Add foundational framework for effect spinoff rule elements
  src/module/actor/actions/types.ts
  src/module/item/consumable/document.ts
  src/module/item/physical/document.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/effect-spinoff/rule-element.ts
  src/module/rules/rule-element/effect-spinoff/spinoff.ts
  static/lang/re-en.json
Labels: pr: enhancement

#14041 Move consume-item event handler to main actor-sheet listener
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/item-summary-renderer.ts
  static/templates/actors/partials/item-summary.hbs
Labels: pr: refactor

#14034 Fix several items to be specific
  packs/age-of-ashes-bestiary/immortal-ichor.json
  packs/equipment/beast-staff-greater.json
  packs/equipment/beast-staff-major.json
  packs/equipment/beast-staff.json
  packs/equipment/chronomancer-staff.json
  packs/equipment/gray-prince.json
  packs/equipment/hyldarfs-fang.json
  packs/equipment/ladys-spiral.json
  packs/equipment/lionfish-spear-greater.json
  packs/equipment/lionfish-spear.json
  packs/equipment/obsidian-edge-greater.json
  packs/equipment/obsidian-edge-major.json
  packs/equipment/obsidian-edge-true.json
  packs/equipment/obsidian-edge.json
  packs/equipment/pirate-staff.json
  packs/equipment/piston-gauntlets.json
  packs/equipment/scalding-gauntlets-greater.json
  packs/equipment/scalding-gauntlets-major.json
  packs/equipment/scalding-gauntlets-true.json
  packs/equipment/scalding-gauntlets.json
  packs/equipment/skysunder.json
  packs/equipment/staff-of-arcane-might-greater.json
  packs/equipment/staff-of-arcane-might-major.json
  packs/equipment/staff-of-arcane-might.json
  packs/equipment/victory-plate-greater.json
  packs/equipment/victory-plate.json
  packs/equipment/zealot-staff.json
  packs/feats/sacral-lord.json
Labels: pr: data update

#14039 Fix the rank for the spell cast by dragonfire halfbow
  packs/equipment/dragonfire-halfbow.json
Labels: pr: data update

#14040 Fix html in description of purgatory emissary's staff
  packs/equipment/purgatory-emissarys-staff.json
Labels: pr: data update

#14042 Remove double linebreaks from compendium items and actors
  packs/bestiary-family-ability-glossary/cryptid-primeval-grasp-for-life.json
  packs/bestiary-family-ability-glossary/ghoul-ghoul-whispers.json
  packs/bestiary-family-ability-glossary/vampire-basic-vampire-weaknesses.json
  packs/deities/pharasma.json
  packs/equipment/dawnsilver-chunk.json
  packs/equipment/dawnsilver-ingot.json
  packs/equipment/orichalcum-chunk.json
  packs/equipment/orichalcum-ingot.json
  packs/equipment/silver-chunk.json
  packs/equipment/silver-ingot.json
  packs/equipment/tyrants-writs.json
  packs/equipment/unbreakable-heart.json
  packs/feats/extended-kinesis.json
  packs/journals/domains.json
  packs/pfs-season-4-bestiary/bugbear-trickster.json
  packs/pfs-season-5-bestiary/enraged-shurrizih.json
  packs/pfs-season-5-bestiary/shurrizih.json
  packs/rage-of-elements-bestiary/jann-shuyookh.json
  packs/rage-of-elements-bestiary/kizidhar-shuyookh.json
  packs/rage-of-elements-bestiary/kizidhar.json
  packs/rage-of-elements-bestiary/lithic-locus.json
  packs/rage-of-elements-bestiary/vault-builder.json
  packs/spells/enthrall.json
  packs/spells/mantle-of-heavens-slopes.json
  packs/spells/one-with-plants.json
  packs/spells/one-with-stone.json
  packs/spells/wooden-double.json
  packs/stolen-fate-bestiary/fabled-harrowkin.json
  packs/stolen-fate-bestiary/simple-harrowkin.json
  packs/stolen-fate-bestiary/storied-harrowkin.json
  packs/stolen-fate-bestiary/the-betrayal.json
  packs/stolen-fate-bestiary/the-courtesan.json
  packs/stolen-fate-bestiary/the-cricket.json
  packs/stolen-fate-bestiary/the-crows.json
  packs/stolen-fate-bestiary/the-dance.json
  packs/stolen-fate-bestiary/the-fool.json
  packs/stolen-fate-bestiary/the-inquisitor.json
  packs/stolen-fate-bestiary/the-joke.json
  packs/stolen-fate-bestiary/the-peacock.json
  packs/stolen-fate-bestiary/the-queen-mother.json
  packs/stolen-fate-bestiary/the-teamster.json
  packs/stolen-fate-bestiary/the-trader.json
  packs/stolen-fate-bestiary/the-twin.json
  packs/stolen-fate-bestiary/the-unicorn.json
  packs/stolen-fate-bestiary/the-wanderer.json
  packs/stolen-fate-bestiary/the-winged-serpent.json
  packs/the-enmity-cycle-bestiary/sand-wolf.json
  packs/the-enmity-cycle-bestiary/scrapborn.json
Labels: pr: data update

#14046 Include range among index properties retrieved for choice sets
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#14043 Correct Awaken Portal secondary casters and extract spoilers from the description into GM description
  packs/abomination-vaults-bestiary/chafkhem.json
  packs/spells/awaken-portal.json
Labels: pr: data update

#14038 Pass event to `rollItemMacro`
  src/module/apps/hotbar.ts
  src/module/chat-message/helpers.ts
  src/module/item/base/document.ts
  src/scripts/macros/hotbar.ts
Labels: pr: enhancement

#14047 Fix language in consumable usage messages
  src/module/item/consumable/document.ts
Labels: pr: bugfix

#14048 Enable IWR automation by default
  src/module/system/settings/automation.ts
Labels: pr: data update

#14051 Add more vetting of melee/range weapon traits
  src/module/item/weapon/document.ts
  src/module/item/weapon/values.ts
Labels: pr: enhancement

#14049 Fix localized strings for Brain Collector's Brain Blisters
  packs/pathfinder-bestiary/brain-collector.json
  packs/pfs-season-5-bestiary/steadied-dohv-dranna.json
Labels: pr: data update

#14052 Reorganize weapon-group sets
  src/module/item/weapon/document.ts
  src/module/item/weapon/values.ts
Labels: pr: refactor

#14053 Add Sanctified as NPC attack trait
  src/scripts/config/traits.ts
Labels: pr: data update

#14054 Use `CompendiumIndexData.uuid` instead of constructing it manually in `CompendiumBrowserTab#loadData`
  src/module/apps/compendium-browser/tabs/action.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/campaign-feature.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
  src/module/apps/compendium-browser/tabs/spell.ts
Labels: pr: bugfix

#14057 Ensure presence of some "self:action:" roll options in checks and damage rolls
  packs/actions/elemental-blast.json
  src/module/actor/character/elemental-blast.ts
  src/module/actor/roll-context/base.ts
  src/module/item/spell/document.ts
Labels: pr: bugfix

#14059 Add single for aura, death note, and self-effect indicator in `AbilityViewData`
  src/module/actor/familiar/sheet.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/sheet/data-types.ts
Labels: pr: bugfix

#14055 Add Aura Junction Metal effect
  packs/feat-effects/effect-aura-junction-metal.json
  packs/feat-effects/effect-kinetic-aura.json
Labels: pr: data update

#14062 Fill in item addition/deletion management to `MigrationRunner.ensureSchemaVersion`
  src/module/migration/runner/index.ts
Labels: pr: bugfix

#14063 Add `ParentedDataModelConstructionOptions` type
  src/module/rules/rule-element/base.ts
  types/foundry/common/abstract/data.d.ts
  types/foundry/common/utils/helpers.d.ts
Labels: pr: types update

#14065 Upgrade Selfish Shield resistance based on Divine Smite
  packs/feat-effects/effect-ongoing-selfishness.json
  packs/feat-effects/effect-selfish-shield.json
Labels: pr: data update

#14066 Add magical traditions as non-damage IWR types
  src/module/actor/data/iwr.ts
  src/scripts/config/iwr.ts
  static/lang/en.json
Labels: pr: data update

#14067 Set warden spell feats to be takable an unlimited number of times
  packs/feats/advanced-warden.json
  packs/feats/initiate-warden.json
  packs/feats/masterful-warden.json
  packs/feats/peerless-warden.json
Labels: pr: data update

#14069 Automate amp feats
  packs/classfeatures/the-distant-grasp.json
  packs/classfeatures/the-infinite-eye.json
  packs/classfeatures/the-oscillating-wave.json
  packs/classfeatures/the-silent-whisper.json
  packs/classfeatures/the-tangible-dream.json
  packs/classfeatures/the-unbound-step.json
  packs/feats/homing-beacon.json
  packs/feats/inertial-barrier.json
  packs/feats/mental-balm.json
  packs/feats/remove-presence.json
  packs/feats/shatter-space.json
  packs/feats/target-of-psychic-ire.json
  packs/feats/warp-space.json
  packs/feats/whispering-steps.json
  static/lang/re-en.json
Labels: pr: data update

#14074 Correct Source of Ring of Truth and Scouting Eye
  packs/spells/ring-of-truth.json
  packs/spells/scouting-eye.json
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#14075 Update Control Weather and Consecrate rituals' publications
  packs/spells/consecrate.json
  packs/spells/control-weather.json
Labels: pr: data update

#14079 Fix pair of types using/extending `DataField`
  types/foundry/common/documents/setting.d.ts
  types/foundry/common/packages/sub-types.d.ts
Labels: pr: types update

#14080 Add automation for kobold Hurried Retreat movement bonus
  packs/crown-of-the-kobold-king-bestiary/kapmek.json
  packs/kingmaker-bestiary/kereek.json
  packs/kingmaker-bestiary/prazil.json
  packs/pathfinder-bestiary/kobold-scout.json
  packs/pathfinder-bestiary/kobold-warrior.json
  packs/pfs-season-1-bestiary/kobold-scout-1-14.json
  packs/pfs-season-1-bestiary/kobold-scout-pfs-1-11.json
  packs/pfs-season-1-bestiary/kobold-warrior-1-14.json
  packs/pfs-season-1-bestiary/kobold-warrior-pfs-1-11.json
  packs/pfs-season-2-bestiary/kobold-warrior-pfs-2-11.json
  packs/pfs-season-3-bestiary/kobold-scout-pfs-3-99.json
  packs/pfs-season-3-bestiary/kobold-warrior-pfs-3-99.json
  packs/pfs-season-5-bestiary/tok-loyalist-3-4.json
  packs/pfs-season-5-bestiary/tok-loyalist.json
  packs/pfs-season-5-bestiary/trapmaster-tok-3-4.json
  packs/pfs-season-5-bestiary/trapmaster-tok.json
  packs/sky-kings-tomb-bestiary/fazil.json
  packs/troubles-in-otari-bestiary/kobold-trapmaster.json
Labels: pr: data update

#14078 Make some NPC rolls blind
  packs/bestiary-family-ability-glossary/vampire-strigoi-strigoi-weaknesses.json
  packs/blood-lords-bestiary/button-mash.json
  packs/shadows-at-sundown-bestiary/aliriel.json
  packs/shadows-at-sundown-bestiary/bishop-keppira-dbear.json
  packs/shadows-at-sundown-bestiary/strigoi-progenitor.json
  packs/shadows-at-sundown-bestiary/strigoi-servant.json
Labels: pr: data update

#14077 Fix damage type for Foretold Ruin's routine
  packs/pfs-season-2-bestiary/foretold-ruin-1-2.json
  packs/pfs-season-2-bestiary/foretold-ruin-3-4.json
Labels: pr: data update

#14076 Fix several issues in BB actors
  packs/menace-under-otari-bestiary/basilisk-bb.json
  packs/menace-under-otari-bestiary/black-kobold-dragon-mage-bb.json
  packs/menace-under-otari-bestiary/blue-kobold-dragon-mage-bb.json
  packs/menace-under-otari-bestiary/caligni-dancer-bb.json
  packs/menace-under-otari-bestiary/caligni-hunter-bb.json
  packs/menace-under-otari-bestiary/caligni-skulker-bb.json
  packs/menace-under-otari-bestiary/green-kobold-dragon-mage-bb.json
  packs/menace-under-otari-bestiary/kobold-scout-bb.json
  packs/menace-under-otari-bestiary/kobold-trapmaster-bb.json
  packs/menace-under-otari-bestiary/kobold-warrior-bb.json
  packs/menace-under-otari-bestiary/red-kobold-dragon-mage-bb.json
  packs/menace-under-otari-bestiary/white-kobold-dragon-mage-bb.json
  packs/menace-under-otari-bestiary/wight-bb.json
Labels: pr: data update

#14085 Fix token name for Conference Z's Victims (9-10)
  packs/pfs-season-5-bestiary/conference-zs-victims-9-10.json
Labels: pr: data update

#14084 Refresh Bronze Bull Pendant
  packs/equipment-effects/effect-bronze-bull-pendant.json
  packs/equipment/bronze-bull-pendant.json
  packs/rollable-tables/2nd-level-consumables.json
Labels: pr: data update

#14088 Set default trait dictionary in `ItemPF2e.traitChatData` to `validTraits`
  src/module/item/base/document.ts
Labels: pr: bugfix

#14090 Copy traits from actions to self-applied effects
  src/module/chat-message/listeners/cards.ts
  src/scripts/config/traits.ts
Labels: pr: bugfix

#14093 Fix regression in retrieval of modifiers in `StatisticCheck#roll`
  src/module/actor/helpers.ts
  src/module/system/statistic/statistic.ts
Labels: pr: bugfix

#14099 Fix vertical centering of PC sheet proficiency-rank select elements
  src/styles/actor/character/_proficiency-ranks.scss
Labels: pr: bugfix

#14100 Fix localization of "Speed" labels in travel duration dialog
  static/templates/gm/travel/travel-speed-sheet.hbs
Labels: pr: bugfix

#14104 Handle lack of affliction item type in effects panel
  src/module/apps/effects-panel.ts
  src/module/item/base/document.ts
Labels: pr: bugfix

#14106 Pass inflated choices when retrieving ChoiceSet preselections
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix

#14105 Remove unneeded "eq" predication operations
  packs/feats/basic-lesson.json
  packs/feats/cultural-adaptability.json
  packs/feats/game-hunter-dedication.json
Labels: pr: data update

#14096 Fix Fresh Produce void resistance
  packs/feat-effects/effect-fresh-produce.json
Labels: pr: data update

#14094 Fix Ijda's spellcasting
  packs/season-of-ghosts-bestiary/ijda.json
Labels: pr: data update

#14089 Restore localization of kinetic aura size labels
  packs/feat-effects/effect-kinetic-aura.json
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#14107 Ensure name adjustments have access to inflated choices
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: bugfix

#14108 Make `eq` predication operator marginally more useful
  src/module/system/predication.ts
Labels: pr: enhancement

#14113 Switch localizable strings used for Mechanical Torch and Glowing Lantern Fruit
  packs/equipment-effects/effect-glowing-lantern-fruit-lantern-light.json
  packs/equipment/mechanical-torch.json
Labels: pr: data update

#14112 Make minisearch instances able to process words in non-roman scripts
  src/module/apps/compendium-browser/tabs/base.ts
  src/module/apps/sidebar/compendium-directory.ts
  src/scripts/hooks/ready.ts
Labels: pr: enhancement

#14111 Correct quantity of level-1+ alchemical ammo producible via Munitions Crafter
  packs/feats/munitions-crafter.json
Labels: pr: data update

#14114 Brush up Soothing Mist
  packs/spells/soothing-mist.json
Labels: pr: data update

#14122 Add Winged Sandals to remaster journal
  packs/equipment-effects/effect-winged-sandals.json
  packs/equipment/winged-sandals.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#14119 Add Seven Dooms for Sandpoint player's Guide content
  packs/backgrounds/cathedral-child.json
  packs/backgrounds/curious-apprentice.json
  packs/backgrounds/eager-scofflaw.json
  packs/backgrounds/lost-coast-local.json
  packs/backgrounds/militia-member.json
  packs/backgrounds/newcomer.json
  packs/backgrounds/runelord-scholar.json
  packs/backgrounds/scarnetti-connected.json
Labels: pr: data update

#14118 Add unified effect for Animal Feature
  packs/spell-effects/spell-effect-animal-feature.json
  packs/spells/animal-feature.json
  static/lang/re-en.json
Labels: pr: data update

#14121 Support Babele's `originalName` property in compendium browser search
  src/module/apps/compendium-browser/tabs/action.ts
  src/module/apps/compendium-browser/tabs/bestiary.ts
  src/module/apps/compendium-browser/tabs/campaign-feature.ts
  src/module/apps/compendium-browser/tabs/equipment.ts
  src/module/apps/compendium-browser/tabs/feat.ts
  src/module/apps/compendium-browser/tabs/hazard.ts
  src/module/apps/compendium-browser/tabs/spell.ts
Labels: pr: enhancement

#14110 Retrieve updated check/damage domains from context clones
  src/module/actor/character/document.ts
  src/module/actor/modifiers.ts
  src/module/actor/roll-context/base.ts
  src/module/actor/roll-context/types.ts
Labels: pr: bugfix

#14124 Fix Twin Distraction Class DC
  packs/feats/twin-distraction.json
Labels: pr: data update

#14101 Fix bulk of Jiu huan dao and remove Nine-ring sword
  packs/equipment/jiu-huan-dao.json
  packs/equipment/nine-ring-sword.json
Labels: pr: data update

#14128 Rename all instances of and references to "Nine-Ring Sword" to "Jiu Huan Doa"
  build/run-migration.ts
  packs/deities/hei-feng.json
  src/module/migration/migrations/924-jiu-huan-dao.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  static/lang/en.json
Labels: pr: data migration, pr: data update

#14130 Fix migration number of nine ring sword migration
  src/module/migration/migrations/924-jiu-huan-dao.ts
Labels: pr: bugfix

#14131 Add fallback for browsers lacking `Intl.Segmenter`
  src/module/apps/compendium-browser/tabs/base.ts
  src/module/apps/sidebar/compendium-directory.ts
Labels: pr: bugfix

#14132 Adjust some remaster localizations
  packs/bestiary-ability-glossary-srd/stench.json
  packs/bestiary-family-ability-glossary/ghoul-ghoul-whispers.json
  packs/bestiary-family-ability-glossary/vampire-basic-vampire-weaknesses.json
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#14102 Remove the legacy Healing version of Touch of Corruption
  build/run-migration.ts
  packs/blood-lords-bestiary/ghoul-antipaladin.json
  packs/blood-lords-bestiary/seldeg-bheldis.json
  packs/book-of-the-dead-bestiary/fallen-champion.json
  packs/npc-gallery/antipaladin.json
  packs/pfs-season-3-bestiary/tyrannical-interrogator.json
  packs/spell-effects/spell-effect-touch-of-corruption-healing.json
  packs/spells/touch-of-corruption-healing.json
  packs/spells/touch-of-corruption.json
  packs/stolen-fate-bestiary/drustan.json
  packs/the-enmity-cycle-bestiary/vulpinal-twin.json
  src/module/migration/migrations/925-touch-of-corruption.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: data update

#14133 Fix localization path to "Material Effects" label in consumable template
  static/templates/items/consumable-details.hbs
Labels: pr: bugfix

#14134 Touch up BB Pregens - ORC update
  packs/paizo-pregens/ezren-beginner-box.json
  packs/paizo-pregens/kyra-beginner-box.json
  packs/paizo-pregens/merisiel-beginner-box.json
  packs/paizo-pregens/valeros-beginner-box.json
Labels: pr: data update

#14135 Fix Marshal stance effects to merge with the parent stance
  packs/feat-effects/stance-dread-marshal-stance.json
  packs/feat-effects/stance-inspiring-marshal-stance.json
  packs/feats/dread-marshal-stance.json
  packs/feats/inspiring-marshal-stance.json
  packs/feats/marshal-dedication.json
Labels: pr: data update

#14137 Run extractPacks all
  packs/abomination-vaults-bestiary/chafkhem.json
  packs/equipment/tyrants-writs.json
  packs/equipment/unbreakable-heart.json
  packs/feats/extended-kinesis.json
  packs/pfs-season-5-bestiary/enraged-shurrizih.json
  packs/pfs-season-5-bestiary/shurrizih.json
  packs/rage-of-elements-bestiary/jann-shuyookh.json
  packs/rage-of-elements-bestiary/kizidhar-shuyookh.json
  packs/rage-of-elements-bestiary/kizidhar.json
  packs/rage-of-elements-bestiary/lithic-locus.json
  packs/rage-of-elements-bestiary/vault-builder.json
  packs/spells/awaken-portal.json
  packs/spells/mantle-of-heavens-slopes.json
  packs/spells/one-with-plants.json
  packs/spells/one-with-stone.json
Labels: pr: data update

#14136 Update BB adventure kobolds for remaster
  packs/menace-under-otari-bestiary/kobold-boss-zolgran-bb.json
  packs/menace-under-otari-bestiary/kobold-trapmaster-bb.json
Labels: pr: data update

#14139 Fix formatting of Kobold Trapmaster (BB)'s Quick Trap description
  packs/menace-under-otari-bestiary/kobold-trapmaster-bb.json
Labels: pr: data update

#14140 Fix havoc wreaked in en.json by laptop keyboard hilarity
  static/lang/en.json
Labels: pr: data update

#14138 Release Notes 5.14.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14141 Fix elemental gate auras
  packs/classfeatures/air-gate.json
  packs/classfeatures/fire-gate.json
  packs/classfeatures/metal-gate.json
  packs/classfeatures/water-gate.json
  packs/classfeatures/wood-gate.json
Labels: pr: data update

#14142 Fix resolution of damage domains in `DamageRollContext`
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#14143 Fix typos in localization strings
  static/lang/re-en.json
Labels: pr: data update

#14144 Fix amping spells for psychic dedication
  packs/feats/psychic-dedication.json
Labels: pr: data update

#14145 Release Notes 5.14.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14160 Fix some regressions in constructing roll contexts
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#14151 Correct Agitate save as not Basic
  packs/spells/agitate.json
Labels: pr: data update

#14165 Wipe `system.location.value` when creating and constructing consumable spells
  src/module/item/consumable/document.ts
  src/module/item/consumable/spell-consumables.ts
Labels: pr: bugfix

#14153 Fix focus point cost of Psychic Dedication amps
  packs/feats/psychic-dedication.json
Labels: pr: data update

#14158 Add Haagenti to Deities
  packs/deities/haagenti.json
Labels: pr: data update

#14169 Fix Bulk of chest
  packs/equipment/chest.json
Labels: pr: data update

#14147 Update Character Sidebar's Shield Max HP label's width
  src/styles/actor/character/_sidebar.scss
Labels: ui/ux

#14173 Fix NPC sheet initiative only showing perception
  src/module/actor/npc/types.ts
  static/templates/actors/npc/partials/sidebar.hbs
  static/templates/actors/npc/simple-sheet.hbs
Labels: pr: bugfix

#14163 Correct Escape Fulu activation action cost
  packs/equipment/escape-fulu.json
Labels: pr: data update

#14168 Automate invisibility grant for wisp's Go Dark
  packs/abomination-vaults-bestiary/dread-wisp.json
  packs/abomination-vaults-bestiary/dune-candle.json
  packs/abomination-vaults-bestiary/groetan-candle.json
  packs/abomination-vaults-bestiary/sacuishu.json
  packs/abomination-vaults-bestiary/spellvoid.json
  packs/abomination-vaults-bestiary/will-o-the-deep.json
  packs/agents-of-edgewatch-bestiary/gloaming-will-o-wisp.json
  packs/kingmaker-bestiary/ancient-wisp.json
  packs/kingmaker-bestiary/spirit-of-stisshak.json
  packs/pathfinder-bestiary/will-o-wisp.json
  packs/pfs-season-2-bestiary/urkhas-3-4.json
  packs/pfs-season-2-bestiary/urkhas-5-6.json
Labels: pr: data update

#14178 Prevent gaining vision from controlled tokens without at least observer ownership
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#14179 Set RecordField as unresolved if anything was unresolved
  src/module/system/schema-data-fields.ts
Labels: pr: bugfix

#14180 Hide disabled damage dice and modifiers in Parallel Breakthrough
  packs/feats/parallel-breakthrough.json
Labels: pr: data update

#14181 Exclude alternate amps from Parallel Breakthrough
  packs/classfeatures/the-silent-whisper.json
  packs/feats/parallel-breakthrough.json
Labels: pr: data update

#14183 Finish patching of token vision acquisition restriction
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#14149 Fix Party's Hexploration Speed missing localization
  static/templates/actors/party/regions/exploration.hbs
Labels: pr: bugfix

#14185 Emphasise spell names in Spell Trickster's description alterations
  static/lang/re-en.json
Labels: pr: data update

#14184 Release Notes 5.14.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14187 Fix Clockwork Belimarius
  packs/rusthenge-bestiary/clockwork-belimarius.json
Labels: pr: data update

#14191 Avoid declaring tokens to be vision sources when sight is disabled
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#14192 Restore range penalties to strike attack rolls
  src/module/actor/character/document.ts
  src/module/actor/helpers.ts
  static/lang/en.json
Labels: pr: bugfix

#14152 Show impulse junction note on elemental blast attack roll instead of damage roll
  packs/classfeatures/air-gate.json
  packs/classfeatures/earth-gate.json
  packs/classfeatures/metal-gate.json
  packs/classfeatures/water-gate.json
  packs/classfeatures/wood-gate.json
Labels: pr: data update

#14194 Fix issue causing kickback trait to be removed from some weapons
  src/module/item/weapon/values.ts
Labels: pr: bugfix

#14193 Release Notes 5.14.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14182 Add effects for Inertial Barrier and Mental Balm
  packs/feat-effects/effect-inertial-barrier.json
  packs/feat-effects/effect-mental-balm.json
  packs/feats/inertial-barrier.json
  packs/feats/mental-balm.json
  static/lang/re-en.json
Labels: pr: data update

#14189 Brush up some Spell Trickster automation
  packs/feat-effects/effect-animate-net.json
  packs/feat-effects/effect-shining-arms.json
  packs/feats/animate-net.json
  packs/feats/lingering-flames.json
  packs/feats/shining-arms.json
  static/lang/re-en.json
Labels: pr: data update

#14198 FIx missing category for some BB NPCs
  packs/menace-under-otari-bestiary/caligni-hunter-bb.json
  packs/menace-under-otari-bestiary/forest-troll-bb.json
Labels: pr: data update

#14197 Fix price of Root Boots
  packs/equipment/root-boots.json
Labels: pr: data update

#14199 Resolve injected properties in `RollTwice` RE selectors
  src/module/rules/rule-element/roll-twice.ts
Labels: pr: enhancement

#14204 Remove attack trait from Dive and Breach
  packs/spells/dive-and-breach.json
Labels: pr: data update

#14210 Fix action type of Arms of the Drowned's Rising Waters and fix rarity
  packs/season-of-ghosts-bestiary/arms-of-the-drowned.json
Labels: pr: data update

#14217 Fix scholastic identification prerequisites
  packs/feats/scholastic-identification.json
Labels: pr: data update

#14219 Fix shoving sweep prerequisites
  packs/feats/shoving-sweep.json
Labels: pr: data update

#14218 Fix edgewatch detective prerequisite
  packs/feats/sense-alignment.json
Labels: pr: data update

#14222 Fix some malformed links
  packs/bestiary-effects/effect-curse-of-boiling-blood.json
  packs/bestiary-family-ability-glossary/nymph-queen-tied-to-the-land.json
  packs/equipment/hag-eye.json
  static/lang/re-en.json
Labels: pr: data update

#14228 Update Cassisian Helmet to unholy predicate
  packs/equipment/cassisian-helmet.json
Labels: pr: data update

#14220 Omit common language from party sheet languages
  src/module/actor/party/sheet.ts
Labels: pr: bugfix

#14216 Handle alchemical trait in IWR
  src/module/actor/data/iwr.ts
  src/scripts/config/iwr.ts
Labels: pr: data update

#14233 Update data-whose attributes to reflect roller/opposer language
  static/templates/chat/check/roll.hbs
Labels: pr: bugfix

#14234 Fix scroll and sizing on npc loot sheet (the actor one)
  src/styles/actor/_inventory.scss
  src/styles/actor/npc/_inventory.scss
  static/templates/actors/npc/loot-sheet.hbs
  static/templates/actors/npc/tabs/inventory.hbs
Labels: pr: bugfix

#14213 Add slugs to FlatModifier REs targeted by AdjustModifier REs
  packs/classfeatures/catharsis-emotion-love.json
  packs/equipment/kinburis-sandals-of-bounding.json
  packs/feats/dragonslayer-oath.json
  packs/feats/esoteric-oath.json
  packs/feats/fiendsbane-oath.json
  packs/feats/intimidating-prowess.json
  packs/feats/ravenings-desperation.json
  packs/feats/shining-oath.json
  packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
  packs/kingmaker-bestiary/valerie-level-9.json
Labels: pr: data update

#14126 Add biconditional predication operator
  src/module/system/predication.ts
  tests/module/system/predication.test.ts
Labels: pr: enhancement

#14235 Add missing trait to several Fist of the Ruby Phoenix actors
  packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/ran-to-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/shino-hakusa-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/syu-tak-nwa-level-20.json
  packs/pfs-season-5-bestiary/riotous-mushrooms.json
  packs/pfs-season-5-bestiary/tanuki-mastermind.json
  packs/pfs-season-5-bestiary/tanuki-prankster.json
  packs/pfs-season-5-bestiary/tanuki-trickster.json
  packs/pfs-season-5-bestiary/topiary-beast.json
  packs/pfs-season-5-bestiary/topiary-monster.json
  packs/pfs-season-5-bestiary/unruly-mushrooms.json
  src/module/actor/creature/values.ts
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#14232 Populate some empty predicates
  packs/blood-lords-bestiary/granite-vulture.json
  packs/equipment-effects/effect-greater-potion-of-stable-form.json
  packs/equipment-effects/effect-potion-of-stable-form.json
  packs/equipment/the-deck-of-destiny.json
  packs/extinction-curse-bestiary/deghuun-child-of-mhar.json
  packs/feat-effects/effect-aura-of-life.json
  packs/feats/necromantic-resistance-undead-slayer.json
  packs/feats/necromantic-tenacity.json
  packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/ran-to-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/shino-hakusa-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/syndara-the-sculptor.json
  packs/fists-of-the-ruby-phoenix-bestiary/syu-tak-nwa-level-20.json
  packs/heritages/discarded-fleshwarp.json
  packs/pathfinder-bestiary-3/stone-lion-cub.json
  packs/pathfinder-bestiary-3/stone-lion.json
  packs/stolen-fate-bestiary/raven-nicoletta.json
Labels: pr: data update

#14238 Use original `Statistic`s when resolving roll contexts
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#14236 Add inline template to Scorching Column
  packs/feats/scorching-column.json
Labels: pr: data update

#14241 Fix some sources
  packs/pfs-season-5-bestiary/riotous-mushrooms.json
  packs/pfs-season-5-bestiary/tanuki-mastermind.json
  packs/pfs-season-5-bestiary/tanuki-prankster.json
  packs/pfs-season-5-bestiary/tanuki-trickster.json
  packs/pfs-season-5-bestiary/topiary-beast.json
  packs/pfs-season-5-bestiary/topiary-monster.json
  packs/pfs-season-5-bestiary/unruly-mushrooms.json
  packs/seven-dooms-for-sandpoint-bestiary/fires-of-abraxas.json
Labels: pr: data update

#14240 Add missing spells to Fluid Form Staff (Major)
  packs/equipment/fluid-form-staff-major.json
Labels: pr: data update

#14243 Fix retrieval of action traits in item summaries
  src/module/item/ability/document.ts
Labels: pr: bugfix

#14244 Release Notes 5.14.4
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#14245 Move Curse of Outpouring Life toggle to spellcasting
  packs/feat-effects/effect-curse-of-outpouring-life.json
  packs/seven-dooms-for-sandpoint-bestiary/greedspawn.json
Labels: pr: data update

#14246 Correct publication data on Player Core spells
  packs/spells/planar-tether.json
  packs/spells/vanishing-tracks.json
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#14257 Fix familiar level 0 in world actors and party errors based off initialization order
  src/module/actor/familiar/document.ts
  src/module/actor/party/document.ts
  src/scripts/hooks/ready.ts
Labels: pr: bugfix

#14262 Fix rolling army skills and initiative
  src/module/actor/army/document.ts
  src/module/system/statistic/statistic.ts
  static/lang/kingmaker-en.json
Labels: pr: bugfix

#14263 Fix formatting for feint army tactical war action
  packs/kingmaker-features/army-war-actions-tactical/feint.json
Labels: pr: data update, kingmaker

#14261 Add "Meet the Iconic" Backstories to Official Iconic Characters
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/iconics/ezren-level-1.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/iconics/feiya-level-1.json
  packs/iconics/feiya-level-5.json
  packs/iconics/fumbus-level-1.json
  packs/iconics/fumbus-level-3.json
  packs/iconics/fumbus-level-5.json
  packs/iconics/harsk-level-1.json
  packs/iconics/harsk-level-5.json
  packs/iconics/jirelle-level-1.json
  packs/iconics/jirelle-level-5.json
  packs/iconics/korakai-level-1.json
  packs/iconics/korakai-level-5.json
  packs/iconics/kyra-level-1.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/iconics/lem-level-1.json
  packs/iconics/lem-level-5.json
  packs/iconics/lini-level-1.json
  packs/iconics/lini-level-5.json
  packs/iconics/merisiel-level-1.json
  packs/iconics/merisiel-level-3.json
  packs/iconics/merisiel-level-5.json
  packs/iconics/quinn-level-1.json
  packs/iconics/quinn-level-5.json
  packs/iconics/sajan-level-1.json
  packs/iconics/sajan-level-5.json
  packs/iconics/seelah-level-1.json
  packs/iconics/seelah-level-5.json
  packs/iconics/seoni-level-1.json
  packs/iconics/seoni-level-5.json
  packs/iconics/valeros-level-1.json
  packs/iconics/valeros-level-3.json
  packs/iconics/valeros-level-5.json
  static/licenses/OpenGameLicense.md
Labels: pr: data update, source: blog

#14259 Fix Enervating Wail's damage formula
  packs/feats/enervating-wail.json
Labels: pr: data update

#14258 Add missing conscious mind info in class feature and classes journal
  packs/classfeatures/conscious-mind.json
  packs/journals/classes.json
Labels: pr: data update

#14266 Update Poltergeist Telekinetic Object and Telekinetic Storm
  packs/age-of-ashes-bestiary/saggorak-poltergeist.json
  packs/fists-of-the-ruby-phoenix-bestiary/watchtower-poltergeist.json
  packs/pathfinder-bestiary/poltergeist.json
  packs/pfs-season-3-bestiary/poltergeist-holy-hand.json
Labels: pr: data update

#14267 Fix sandpoint devil's accursed breath
  packs/pathfinder-bestiary-2/sandpoint-devil.json
Labels: pr: data update

#14269 Preserve creation order in nested grants
  src/module/rules/rule-element/grant-item/rule-element.ts
Labels: pr: bugfix
