Repository foundryvtt/pf2e, pull requests merged in 2025-03, with the labels that each got.

#18382 Add Thrown 50 ft trait
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#18373 Fix `ItemAttacher` always selecting first option in select element
  src/module/apps/item-attacher.ts
Labels: pr: bugfix

#18388 Update NPM dependencies
  package-lock.json
  package.json
  src/module/actor/base.ts
  src/module/apps/compendium-browser/browser.ts
  src/module/item/physical/document.ts
  src/module/rules/rule-element/base.ts
  types/foundry/client/pixi/placeables/primary-canvas-objects/primary-canvas-object.ts
  types/foundry/client/pixi/placeables/primary-canvas-objects/primary-sprite-mesh.d.ts
  vite.config.ts
Labels: pr: housekeeping

#18386 Localize Hunt Prey "First Attack" on NPCs
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/tanessa-fleer.json
  packs/feat-effects/effect-hunters-edge-precision.json
  packs/kingmaker-bestiary/aldori-sister.json
  packs/npc-gallery/hunter.json
  packs/npc-gallery/poacher.json
  packs/npc-gallery/tracker.json
  packs/pfs-season-2-bestiary/2-10/scorched-earth-orc-scout-5-6.json
  packs/pfs-season-2-bestiary/2-10/scorched-earth-orc-scout-7-8.json
  packs/pfs-season-2-bestiary/2-12/aspis-veteran-guard.json
  packs/pfs-season-2-bestiary/2-20/ash-archer.json
  packs/pfs-season-3-bestiary/3-08/tadrun-1-2.json
  packs/pfs-season-3-bestiary/3-08/tadrun-3-4.json
  packs/pfs-season-3-bestiary/3-16/ninth-army-soldier.json
  packs/pfs-season-3-bestiary/3-99/shobhad-hunter-5-6.json
  packs/pfs-season-3-bestiary/3-99/shobhad-hunter-7-8.json
  packs/pfs-season-4-bestiary/4-99/elven-hunter.json
  packs/pfs-season-4-bestiary/4-99/recon-patroller.json
  packs/quest-for-the-frozen-flame-bestiary/book-1-broken-tusk-moon/pakano.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/ajbal-kimon.json
  packs/wardens-of-wildwood-bestiary/book-1-packbreaker/inrik-vanderholl.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/koata-inuu.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/wildwood-sentry.json
Labels: pr: data update

#18385 Correct name of Bramble Champion Construct
  packs/strength-of-thousands-bestiary/book-1-kindled-magic/bramble-champion-construct.json
Labels: pr: data update

#18379 Add support for token ring `effects` field in `TokenImage` RE
  src/module/rules/rule-element/token-image.ts
  src/module/rules/synthetics.ts
  src/module/scene/token-document/document.ts
  types/foundry/common/documents/token.d.ts
Labels: pr: enhancement

#18381 Add translation to item currency values and parsing
  src/module/item/physical/coins.ts
Labels: localization

#18343 Add GrantItem RE for Raise a Shield to Shields of the Spirit spell effect
  packs/spell-effects/spell-effect-shields-of-the-spirit.json
Labels: pr: data update

#18397 Fix registration of GM Vision keybind for macs
  src/scripts/register-keybindings.ts
  types/foundry/client/keyboard/keyboard-manager.d.ts
Labels: pr: bugfix

#18282 Type updates
  src/global.ts
  types/foundry/client-esm/applications/api/dialog.d.ts
  types/foundry/client-esm/applications/api/module.d.ts
  types/foundry/client/apps/av/cameras.d.ts
  types/foundry/client/apps/av/index.d.ts
  types/foundry/client/apps/client-settings.d.ts
  types/foundry/client/apps/index.d.ts
  types/foundry/client/apps/templates.d.ts
  types/foundry/client/config.d.ts
  types/foundry/client/ui/index.d.ts
  types/foundry/common/utils/helpers.d.ts
  types/foundry/common/utils/module.d.ts
  types/foundry/common/utils/semaphore.d.ts
Labels: pr: types update

#18395 Update selector to `will` for Ultimatum of Liberation effect
  packs/feat-effects/effect-ultimatum-of-liberation.json
Labels: pr: data update

#18380 Correct Heightening for Roses Thorn's and update/remove select spell inline damage
  packs/spells/percussive-impact.json
  packs/spells/phantasmal-calamity.json
  packs/spells/phantom-orchestra.json
  packs/spells/poltergeists-fury.json
  packs/spells/prying-survey.json
  packs/spells/pulverizing-wake.json
  packs/spells/purple-worm-sting.json
  packs/spells/qi-blast.json
  packs/spells/quench.json
  packs/spells/radiant-beam.json
  packs/spells/rainbows-end.json
  packs/spells/ray-of-corruption.json
  packs/spells/repelling-pulse.json
  packs/spells/rime-slick.json
  packs/spells/roses-thorns.json
  packs/spells/rouse-skeletons.json
  packs/spells/rust-cloud.json
  packs/spells/sanguine-mist.json
Labels: pr: data update

#18406 Move Detective Readiness modifier RE into its feat
  packs/actions/pursue-a-lead.json
  packs/feats/detectives-readiness.json
Labels: pr: data update

#18408 Automate Awakened Yaoguai Heritage Feat
  packs/feats/awakened-yaoguai-heritage.json
  static/lang/re-en.json
Labels: pr: data update

#18409 Push priority of weapon innovation fire damage toggle to after overdrive roll options
  packs/classfeatures/weapon-innovation.json
Labels: pr: data update

#18410 Remove inline damage rolls from select spells
  packs/spells/lucky-number.json
  packs/spells/mantle-of-the-melting-heart.json
  packs/spells/marvelous-mount.json
  packs/spells/moonburst.json
  packs/spells/morass-of-ages.json
  packs/spells/moths-supper.json
  packs/spells/murderous-vine.json
  packs/spells/noise-blast.json
  packs/spells/noxious-metals.json
  packs/spells/noxious-vapors.json
  packs/spells/ordained-purpose.json
  packs/spells/organsight.json
Labels: pr: data update

#18398 Fix some localized strings
  packs/campaign-effects/pathfinder-society/effect-exotic-edge.json
  packs/campaign-effects/pathfinder-society/effect-heroic-inspiration.json
  packs/feats/security.json
  packs/spell-effects/spell-effect-shields-of-the-spirit.json
  static/lang/re-en.json
Labels: pr: data update

#18378 Fix talisman usages
  packs/equipment/alloy-orb-exquisite-high-grade.json
  packs/equipment/alloy-orb-high-grade.json
  packs/equipment/alloy-orb-low-grade.json
  packs/equipment/alloy-orb-standard-grade.json
  packs/equipment/bloodseeker-beak-greater.json
  packs/equipment/dragontooth-trophy.json
  packs/equipment/ensnaring-disk.json
  packs/equipment/fortifying-pebble.json
  packs/equipment/ghostbane-fulu.json
  packs/equipment/inventors-fulu.json
  packs/equipment/iron-cudgel.json
  packs/equipment/iron-equalizer.json
  packs/equipment/liquid-gold-greater.json
  packs/equipment/liquid-gold.json
  packs/equipment/persistent-lodestone.json
  packs/equipment/privacy-ward-fulu-chamber.json
  packs/equipment/privacy-ward-fulu-hallway.json
  packs/equipment/privacy-ward-fulu-room.json
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data update

#18419 Update Runelord journal entry to match LO Rival Academies update
  packs/journals/archetypes.json
Labels: pr: data update

#18418 Add localized text for select LO Rival Academies effects and feats
  packs/feat-effects/effect-cozy-campfire.json
  packs/feat-effects/effect-in-lightning-life.json
  packs/feat-effects/effect-offer-story.json
  packs/feat-effects/effect-raging-stories.json
  packs/feat-effects/effect-rod-of-rule.json
  packs/feat-effects/effect-ruthless-orator.json
  packs/feat-effects/effect-tributary-circulation.json
  packs/feat-effects/stance-flood-stance.json
  packs/feat-effects/stance-stunt-performer-stance.json
  packs/feat-effects/stance-waterfowl-stance.json
  static/lang/re-en.json
Labels: pr: data update

#18421 Use an `onDown` callback instead of `onUp` for GM vision keybinding
  src/scripts/register-keybindings.ts
Labels: pr: bugfix

#18420 Add proper predicate to Detective's Readiness saving throw RE
  packs/feats/detectives-readiness.json
Labels: pr: data update

#18425 Correct broken `Recall Knowledge` links for select Lost Omens Rival Academies items
  packs/classfeatures/echoes-of-the-scrolls.json
  packs/classfeatures/echoes-of-the-spells.json
  packs/equipment/fiendbreaker-heroic.json
  packs/feats/archetype/campfire-chronicler/illuminating-stories.json
  packs/feats/archetype/campfire-chronicler/tales-of-the-road.json
  packs/feats/archetype/kitharodian-actor/animal-actor.json
  packs/feats/archetype/lepidstadt-surgeon/rise-my-creature.json
  packs/feats/class/monk/lessons-of-flux.json
Labels: pr: data update

#18424 Redirect select troop actors from Pathfinder Bestiary 3 to Pathfinder NPC Core
  build/uuid-redirects.json
  packs/pathfinder-bestiary-3/city-guard-squadron.json
  packs/pathfinder-bestiary-3/hellknight-cavalry-brigade.json
  packs/pathfinder-bestiary-3/rancorous-priesthood.json
Labels: pr: data update

#18426 Add Lost Omens Rival Academies dedications to Archetype's journal and apply `@Embed` to the Zephyr Guard journal entry
  packs/journals/archetypes.json
Labels: pr: data update

#18427 Add missing prerequisites to Sympathetic Portrayal feat
  packs/feats/archetype/kitharodian-actor/sympathetic-portrayal.json
Labels: pr: data update

#18428 Add label to Runelord's Martial Proficiency
  packs/classfeatures/runelord.json
  packs/classfeatures/school-of-thassilonian-rune-magic.json
  static/lang/re-en.json
Labels: pr: data update

#18429 Release Notes 6.10.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#18430 Remove duplicate @ symbol in Major Frost Vial success RE
  static/lang/re-en.json
Labels: pr: data update

#18434 Correct `Read Aura` link in the Greed (Runelord) class feature
  packs/classfeatures/echoes-of-the-scrolls.json
  packs/classfeatures/echoes-of-the-spells.json
  packs/classfeatures/greed.json
  packs/feats/archetype/kitharodian-actor/animal-actor.json
  packs/feats/archetype/lepidstadt-surgeon/rise-my-creature.json
  packs/feats/class/monk/lessons-of-flux.json
Labels: pr: data update

#18438 Condense `Pickled Demon Tongue` Spellheart equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-pickled-demon-tongue-armor-greater.json
  packs/equipment-effects/effect-pickled-demon-tongue-armor-major.json
  packs/equipment-effects/effect-pickled-demon-tongue-armor.json
  packs/equipment-effects/effect-pickled-demon-tongue-weapon-greater.json
  packs/equipment-effects/effect-pickled-demon-tongue-weapon-major.json
  packs/equipment-effects/effect-pickled-demon-tongue-weapon.json
  packs/equipment/pickled-demon-tongue-greater.json
  packs/equipment/pickled-demon-tongue-major.json
Labels: pr: data update

#18435 Add missing equipment publication data
  packs/equipment/branch-attendants-mask.json
  packs/equipment/hidden-pocket-outfit.json
  packs/equipment/illusory-backdrop.json
  packs/equipment/inspiring-spotlight-mounted.json
  packs/equipment/inspiring-spotlight-portable.json
  packs/equipment/malefic-mirror.json
  packs/equipment/pranksters-perpetual-pieplate.json
Labels: pr: data update

#18433 Replace <br /> tags with paragraphs where appropriate
  packs/backgrounds/sign-bound.json
  packs/bestiary-effects/effect-fiddle.json
  packs/campaign-effects/seven-dooms-for-sandpoint/effect-consecrated-altar-to-ydersius.json
  packs/classfeatures/flame-order.json
  packs/classfeatures/stone-order.json
  packs/classfeatures/wave-order.json
  packs/deities/pantheons/the-offering-plate.json
  packs/equipment-effects/effect-saurian-spike-armor.json
  packs/equipment/blast-suit.json
  packs/equipment/elixir-of-gender-transformation-lesser.json
  packs/equipment/kalmaugs-journal.json
  packs/feats/conceal-spell.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/koto-zekora.json
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/etward-ritalson.json
  packs/iconics/ezren-level-5.json
  packs/journals/archetypes.json
  packs/kingmaker-features/kingdom-features/ruin-resistance.json
  packs/pfs-season-3-bestiary/bounties/explosive-rat.json
  packs/pfs-season-4-bestiary/4-14/allegro.json
  packs/spell-effects/spell-effect-dragon-form-empyreal.json
  packs/spell-effects/spell-effect-dragon-form-fortune.json
  packs/spell-effects/spell-effect-dragon-form-mirage.json
  packs/spell-effects/spell-effect-dragon-form-omen.json
  packs/vehicles/siege-tower.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/phytohydra.json
Labels: pr: data update

#18436 Correct description text for the Simulacrum's key ring item
  packs/one-shot-bestiary/dinner-at-lionlodge/simulacrum.json
Labels: pr: data update

#18437 Correct formatting for Auldengrund Grimcarver's Simulacrum ritual
  packs/one-shot-bestiary/dinner-at-lionlodge/auldegrund-grimcarver.json
Labels: pr: data update

#18442 Update broken links in Troop Defenses' localization
  static/lang/en.json
Labels: pr: data update

#18448 Set data-dtype="Number" in hidden action-cost field
  static/templates/items/partials/ability-activation.hbs
Labels: pr: bugfix

#18441 Correct Rancorous Priesthood's max focus pool points
  packs/pathfinder-npc-core/devotee/rancorous-priesthood.json
Labels: pr: data update

#18450 Update `ActiveEffect` type definition
  types/foundry/client/data/documents/active-effect.d.ts
  types/foundry/client/data/documents/client-base-mixes.d.ts
Labels: pr: types update, pr: foundry v12

#18443 Condense `Polished Demon Horn` spellheart equipment effects and update predicate traits for `Obsidian Goggles` Rule Elements
  build/uuid-redirects.json
  packs/equipment-effects/effect-polished-demon-horn-armor-greater.json
  packs/equipment-effects/effect-polished-demon-horn-armor-major.json
  packs/equipment-effects/effect-polished-demon-horn-armor.json
  packs/equipment-effects/effect-polished-demon-horn-weapon-greater.json
  packs/equipment-effects/effect-polished-demon-horn-weapon-major.json
  packs/equipment-effects/effect-polished-demon-horn-weapon.json
  packs/equipment/obsidian-goggles-greater.json
  packs/equipment/obsidian-goggles-major.json
  packs/equipment/polished-demon-horn-greater.json
  packs/equipment/polished-demon-horn-major.json
  packs/equipment/polished-demon-horn.json
Labels: pr: data update

#18456 Restore preparation of subfeature key attribute options
  src/module/item/feat/document.ts
Labels: pr: bugfix

#18462 Add creature identification skills for dream, shade, and time
  src/module/recall-knowledge.ts
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#18455 Push Slinger's Precision Martial Proficiency priority to after other proficiency upgrades
  packs/classfeatures/slingers-precision.json
Labels: pr: data update

#18451 Remove Shields of the Spirit effect if shield is no longer raised
  packs/spell-effects/spell-effect-shields-of-the-spirit.json
Labels: pr: data update

#18432 Add rules to handle Armored Stealth penalty adjustment
  packs/feats/armored-stealth.json
Labels: pr: data update

#18463 Correct predicates for `Flurry Edge` MAP Rule Elements
  packs/classfeatures/flurry.json
Labels: pr: data update

#18461 Fix mystifying compendium items when alt dragging
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#18466 Release Notes 6.10.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#18474 Fix fated duel description
  packs/feats/fated-duel.json
Labels: pr: data update

#18465 Condense Potency Crystal equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-potency-crystal-greater.json
  packs/equipment-effects/effect-potency-crystal-major.json
  packs/equipment-effects/effect-potency-crystal.json
  packs/equipment-effects/effect-saurian-spike-armor.json
  packs/equipment/elixir-of-gender-transformation-lesser.json
  packs/equipment/fiendbreaker-heroic.json
  packs/equipment/potency-crystal-greater.json
  packs/equipment/potency-crystal-major.json
Labels: pr: data update

#18469 Preselect Assurance choice for some backgrounds
  packs/backgrounds/adventure-paths/abomination-vaults/eldritch-anatomist.json
  packs/backgrounds/adventure-paths/fists-of-the-ruby-phoenix/abadars-avenger.json
  packs/backgrounds/goblinblood-orphan.json
  packs/backgrounds/lumber-consortium-laborer.json
  packs/backgrounds/star-athlete.json
Labels: pr: data update

#18475 Move `AbilityTraitToggles` "data preparation" out of constructor
  src/module/item/ability/data.ts
  src/module/item/ability/trait-toggles.ts
  src/module/item/feat/data.ts
Labels: pr: bugfix

#18476 Release Notes 6.10.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#18478 Add effect to Wrathful Storm
  packs/spell-effects/spell-effect-wrathful-storm.json
  packs/spells/wrathful-storm.json
Labels: pr: data update

#18449 Show NPC and Effects in simple npc sheets
  src/styles/actor/npc/_effects.scss
  src/styles/actor/npc/_index.scss
  static/templates/actors/npc/simple-sheet.hbs
Labels: pr: bugfix

#18477 Brush up Elementalist Class Archetype journal entry
  packs/classfeatures/elemental-magic.json
  packs/classfeatures/elemental-school.json
  packs/journals/archetypes.json
Labels: pr: data update

#18481 Remove Improved Grab from Fungal Flytrap's Focused Assault
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/fungal-flytrap.json
Labels: pr: data update

#18482 Fix Kholo Weapon Familiarity
  packs/feats/kholo-weapon-familiarity.json
Labels: pr: data update

#18486 Add Lead Constitution to Gunslinger's granted features
  packs/classes/gunslinger.json
Labels: pr: data update

#18488 Update Entreat Spirit effect to choose an int-, wis-, or cha-based skill
  packs/spell-effects/spell-effect-entreat-spirit.json
Labels: pr: data update

#18487 Update Bands of Force's Flat Modifier slug
  packs/equipment/assassins-bracers-type-i.json
  packs/equipment/assassins-bracers-type-ii.json
  packs/equipment/assassins-bracers-type-iii.json
  packs/equipment/bands-of-force-greater.json
  packs/equipment/bands-of-force-major.json
  packs/equipment/bands-of-force.json
Labels: pr: data update

#18490 Fix spell category filter in Compendium Browser
  src/module/apps/compendium-browser/tabs/spell.ts
Labels: pr: bugfix

#18485 Remove remaining rule element-based implementation of Apex items
  packs/equipment/dragon-handwraps.json
  packs/equipment/whispering-staff.json
Labels: pr: data update

#18489 Update Reinforced Chassis AC bonus alteration to be additive with other increases
  packs/feats/reinforced-chassis.json
Labels: pr: data update

#18492 Add missing spell statistics to Demonologist
  packs/pathfinder-npc-core/mystic/demonologist.json
Labels: pr: data update

#18500 Add effect for Coven Spell's status damage to spells
  packs/feat-effects/effect-coven-spell.json
  packs/feats/coven-spell.json
Labels: pr: data update

#18498 Update Tempest Gaze rule elements to add description instead of override.
  packs/feats/tempest-gaze.json
Labels: pr: data update

#18496 Add missing price to Steadfast Sentinel
  packs/equipment/steadfast-sentinel.json
Labels: pr: data update

#18494 Add links to Fireball in Firestarter Pellets
  packs/equipment/firestarter-pellets-greater.json
  packs/equipment/firestarter-pellets-major.json
  packs/equipment/firestarter-pellets.json
Labels: pr: data update

#18503 Update Illusory Shroud spell effect description
  packs/spell-effects/spell-effect-illusory-shroud.json
Labels: pr: data update

#18499 Correct Exploding Bloom Pods' Burst failure condition
  packs/kingmaker-bestiary/exploding-bloom-pods.json
Labels: pr: data update

#18497 Add Aid degree of success adjustment to Headbands of Translocation
  packs/equipment/headbands-of-translocation.json
  static/lang/re-en.json
Labels: pr: data update

#18505 Add effect for Sage's Analysis
  packs/bestiary-effects/effect-conduct-the-experiment.json
  packs/bestiary-effects/effect-sages-analysis.json
  packs/pathfinder-npc-core/scholar/sage.json
Labels: pr: data update

#18501 Add missing spell statistics to additional NPC Core Actors
  packs/pathfinder-npc-core/ancestry-npcs/catfolk/catfolk-name-collector.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/forlorn-artist.json
  packs/pathfinder-npc-core/ancestry-npcs/halfling/halfling-yarnspinner.json
  packs/pathfinder-npc-core/official/watchmage-squadron.json
  packs/pathfinder-npc-core/scholar/departmental-chair.json
Labels: pr: data update

#18504 Add PFS 3/25 clarifications for Rival Academies
  packs/familiar-abilities/familiar-of-obscuring-snowfall.json
  packs/feats/aeon-resonance.json
  packs/feats/archetype/campfire-chronicler/listeners-boon.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/koto-zekora.json
  packs/pfs-season-3-bestiary/bounties/explosive-rat.json
  packs/spells/kgalaserkes-axes.json
  packs/spells/loves-sacrifice.json
  packs/spells/personal-runewell.json
  packs/spells/the-parrots-whisper.json
  packs/spells/the-queens-rainbow.json
  packs/vehicles/siege-tower.json
Labels: pr: data update

#18506 Fix minor typo in Far-Flung Fetch
  packs/spells/far-flung-fetch.json
Labels: pr: data update

#18515 Fix spell variants always fixed heightening when cast without a rank
  src/module/item/spell/document.ts
Labels: pr: bugfix

#18516 Condense Potion of Acid Resistance equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-potion-of-acid-resistance-greater.json
  packs/equipment-effects/effect-potion-of-acid-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-acid-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-acid-resistance.json
  packs/equipment/potion-of-acid-resistance-greater.json
  packs/equipment/potion-of-acid-resistance-lesser.json
  packs/equipment/potion-of-acid-resistance-moderate.json
Labels: pr: data update

#18510 Fix activation wording on high level Symbol of Conflict
  packs/equipment/symbol-of-conflict-greater.json
  packs/equipment/symbol-of-conflict-major.json
Labels: pr: data update

#18513 Update Class Archetype class features automation and corresponding journal entries text
  packs/classfeatures/avenger.json
  packs/classfeatures/battle-creed.json
  packs/classfeatures/bloodrager.json
  packs/classfeatures/palatine-detective.json
  packs/classfeatures/runelord.json
  packs/classfeatures/seneschal.json
  packs/classfeatures/vindicator.json
  packs/classfeatures/warrior-of-legend.json
  packs/classfeatures/wellspring-magic.json
  packs/journals/archetypes.json
Labels: pr: data update

#18520 Add `location` to Class Archetype level 2 dedication feats
  packs/feats/archetype/avenger-dedication.json
  packs/feats/archetype/battle-harbinger-dedication.json
  packs/feats/archetype/bloodrager-dedication.json
  packs/feats/archetype/palatine-detective-dedication.json
  packs/feats/archetype/runelord-dedication.json
  packs/feats/archetype/seneschal-witch-dedication.json
  packs/feats/archetype/vindicator-dedication.json
  packs/feats/archetype/warrior-of-legend-dedication.json
  packs/feats/archetype/wellspring-mage-dedication.json
Labels: pr: data update

#18526 Condense Potion of Cold Resistance equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-potion-of-cold-resistance-greater.json
  packs/equipment-effects/effect-potion-of-cold-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-cold-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-cold-resistance.json
  packs/equipment/potion-of-cold-resistance-greater.json
  packs/equipment/potion-of-cold-resistance-lesser.json
  packs/equipment/potion-of-cold-resistance-moderate.json
Labels: pr: data update

#18524 Fix scaling on Shard Strike bleed damage
  packs/feats/class/kineticist/shard-strike.json
Labels: pr: data update

#18517 Suppress abilities granted by features suppressed by a class archetype
  src/module/actor/character/sheet.ts
  src/module/item/ability/document.ts
  src/module/item/feat/helpers.ts
Labels: pr: bugfix

#18529 Add NPC attitude-tracking effect
  packs/campaign-effects/_folders.json
  packs/campaign-effects/pathfinder-player-core/effect-attitude.json
  packs/journals/gm-screen.json
  packs/other-effects/effect-aquatic-combat.json
  packs/other-effects/effect-mounted.json
Labels: pr: data update

#18532 Remove player facing links to All-Around Vision glossary item
  packs/feat-effects/effect-watchful-gaze.json
  packs/feats/ancestry/goloma/watchful-gaze.json
  packs/feats/archetype/chronoskimmer/superimpose-time-duplicates.json
Labels: pr: data update

#18533 Tag Runelord sin and curriculum spells for Rod of Rule and Sinbladed Spell automation
  packs/classfeatures/envy.json
  packs/classfeatures/gluttony.json
  packs/classfeatures/greed.json
  packs/classfeatures/lust.json
  packs/classfeatures/pride.json
  packs/classfeatures/runelord.json
  packs/classfeatures/school-of-thassilonian-rune-magic.json
  packs/classfeatures/sloth.json
  packs/classfeatures/wrath.json
  packs/feat-effects/effect-rod-of-rule.json
  packs/feats/archetype/runelord/sinbladed-spell.json
  static/lang/re-en.json
Labels: pr: data update

#18536 Correct Mage Killer actor name
  packs/pathfinder-npc-core/mercenary/mage-killer.json
Labels: pr: data update

#18530 Condense Fanged Rune and Potion of Electricity Resistance equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-fanged-rune-animal-form-greater.json
  packs/equipment-effects/effect-fanged-rune-animal-form-major.json
  packs/equipment-effects/effect-fanged-rune-animal-form.json
  packs/equipment-effects/effect-potion-of-electricity-resistance-greater.json
  packs/equipment-effects/effect-potion-of-electricity-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-electricity-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-electricity-resistance.json
  packs/equipment/fanged-greater.json
  packs/equipment/fanged-major.json
  packs/equipment/potion-of-electricity-resistance-greater.json
  packs/equipment/potion-of-electricity-resistance-lesser.json
  packs/equipment/potion-of-electricity-resistance-moderate.json
Labels: pr: data update

#18519 Add damage to Hypnopompic Terrors spell
  packs/spells/hypnopompic-terrors.json
Labels: pr: data update

#18542 Improve automation of Vapor Form spell effect
  packs/spell-effects/spell-effect-vapor-form.json
Labels: pr: data update

#18543 Implement Wellspring Magic grant as class archetype choice and add brush up Elemental Magic and Flexible Spell Preparation choice grants
  packs/classfeatures/elemental-magic.json
  packs/classfeatures/flexible-spell-preparation.json
  packs/classfeatures/wellspring-magic.json
Labels: pr: data update

#18547 Correct text on Goblin Get Gang's `Goblins Bound and Goblins Swing!` ability
  packs/pathfinder-npc-core/ancestry-npcs/goblin/goblin-get-gang.json
Labels: pr: data update

#18551 Add effect for Hero Point Deck's Press On and fix Class Might's Flat Modifier
  packs/journals/hero-point-deck.json
  packs/other-effects/effect-class-might.json
  packs/other-effects/effect-press-on.json
Labels: pr: data update

#18549 Condense Potion of Fire Resistance equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-potion-of-fire-resistance-greater.json
  packs/equipment-effects/effect-potion-of-fire-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-fire-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-fire-resistance.json
  packs/equipment/potion-of-fire-resistance-greater.json
  packs/equipment/potion-of-fire-resistance-lesser.json
  packs/equipment/potion-of-fire-resistance-moderate.json
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/vintalax-the-rotting-god.json
Labels: pr: data update

#18554 Fix description of revolutionary innovation
  packs/classfeatures/revolutionary-innovation.json
Labels: pr: data update

#18555 fix a typo in witch lessons
  packs/classfeatures/witch-lessons.json
Labels: pr: data update

#18556 Update Dragon Form Spell heightening text to match Player Core and add scaling to Breath Weapon inlines
  packs/spell-effects/spell-effect-dragon-form-adamantine.json
  packs/spell-effects/spell-effect-dragon-form-conspirator.json
  packs/spell-effects/spell-effect-dragon-form-diabolic.json
  packs/spell-effects/spell-effect-dragon-form-empyreal.json
  packs/spell-effects/spell-effect-dragon-form-fortune.json
  packs/spell-effects/spell-effect-dragon-form-horned.json
  packs/spell-effects/spell-effect-dragon-form-mirage.json
  packs/spell-effects/spell-effect-dragon-form-omen.json
  packs/spells/dragon-form.json
Labels: pr: data update

#18558 Remove self-reference from Tumble Through action description
  packs/actions/skill-actions/tumble-through.json
Labels: pr: data update

#18562 Grant Spellstrike with Spellstriker feat
  packs/feats/archetype/magus/spellstriker.json
Labels: pr: data update

#18541 Clean up Champion deity rule elements
  packs/classfeatures/deity-champion.json
Labels: pr: data update

#18540 Cleanup Eldritch Trickster implementation
  packs/classfeatures/eldritch-trickster.json
  packs/feats/archetype/animist/animist-dedication.json
  packs/feats/archetype/bard/bard-dedication.json
  packs/feats/archetype/cleric/cleric-dedication.json
  packs/feats/archetype/druid/druid-dedication.json
  packs/feats/archetype/exemplar/exemplar-dedication.json
  packs/feats/archetype/magus/magus-dedication.json
  packs/feats/archetype/oracle/oracle-dedication.json
  packs/feats/archetype/psychic/psychic-dedication.json
  packs/feats/archetype/sorcerer/sorcerer-dedication.json
  packs/feats/archetype/summoner/summoner-dedication.json
  packs/feats/archetype/witch/witch-dedication.json
  packs/feats/archetype/wizard/wizard-dedication.json
Labels: pr: data update

#18557 Condense Insight Coffee equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-insight-coffee-greater.json
  packs/equipment-effects/effect-insight-coffee-lesser.json
  packs/equipment-effects/effect-insight-coffee-moderate.json
  packs/equipment-effects/effect-insight-coffee.json
  packs/equipment/insight-coffee-greater.json
  packs/equipment/insight-coffee-lesser.json
  packs/equipment/insight-coffee-moderate.json
  static/lang/re-en.json
Labels: pr: data update

#18563 Brush up some NPC Core actors
  packs/bestiary-effects/effect-temper-armament.json
  packs/night-of-the-gray-death-bestiary/pageant-troupe.json
  packs/pathfinder-npc-core/ancestry-npcs/catfolk/leaping-thief.json
  packs/pathfinder-npc-core/ancestry-npcs/catfolk/lucky-courser.json
  packs/pathfinder-npc-core/ancestry-npcs/dwarf/dwarf-battalion.json
  packs/pathfinder-npc-core/ancestry-npcs/dwarf/dwarf-general.json
  packs/pathfinder-npc-core/ancestry-npcs/dwarf/dwarf-smith.json
  packs/pathfinder-npc-core/ancestry-npcs/dwarf/spirit-priest.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/aiuvarin-translator.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/demonbane-warrior.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/elven-court-guard.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/forlorn-artist.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/woodland-scouts.json
  packs/pathfinder-npc-core/ancestry-npcs/goblin/goblin-get-gang.json
  packs/pathfinder-npc-core/ancestry-npcs/halfling/bill-band.json
  packs/pathfinder-npc-core/ancestry-npcs/hobgoblin/hobgoblin-battalion.json
  packs/pathfinder-npc-core/ancestry-npcs/leshy/corn-leshy-throng.json
  packs/pathfinder-npc-core/ancestry-npcs/orc/orc-skullcrushers.json
  packs/pathfinder-npc-core/courtier/courtesan.json
  packs/pathfinder-npc-core/courtier/envoy.json
  packs/pathfinder-npc-core/criminal/bandit-gang.json
  packs/pathfinder-npc-core/devotee/high-priest-of-pharasma.json
  packs/pathfinder-npc-core/devotee/penitent-of-calistria.json
  packs/pathfinder-npc-core/devotee/rancorous-priesthood.json
  packs/pathfinder-npc-core/maverick/unsanctioned-sheriff.json
  packs/pathfinder-npc-core/mercenary/mercenary-band.json
  packs/pathfinder-npc-core/military/conscript-squad.json
  packs/pathfinder-npc-core/military/heavy-cavalry.json
  packs/pathfinder-npc-core/military/hellknight-cavalry-brigade.json
  packs/pathfinder-npc-core/military/line-infantry.json
  packs/pathfinder-npc-core/military/phalanx-formation.json
  packs/pathfinder-npc-core/military/standard-bearer.json
  packs/pathfinder-npc-core/official/arrester-squadron.json
  packs/pathfinder-npc-core/official/city-guard-squadron.json
  packs/pathfinder-npc-core/official/grand-inquisitor.json
  packs/pathfinder-npc-core/official/watchmage-squadron.json
  packs/pathfinder-npc-core/performer/court-jester.json
  packs/pathfinder-npc-core/performer/mime.json
  packs/pathfinder-npc-core/performer/traveling-actor.json
  packs/pathfinder-npc-core/villain/champion-of-rovagug.json
  packs/pathfinder-npc-core/villain/deluded-mob.json
  packs/pathfinder-npc-core/villain/interrogator.json
  packs/pathfinder-npc-core/villain/propagandist.json
  packs/pfs-season-5-bestiary/5-02/azlanti-elemental-nexus.json
  packs/pfs-season-6-bestiary/6-06/zombie-leshy-horde.json
  packs/pfs-season-6-bestiary/6-07/divine-oozeshard.json
  packs/pfs-season-6-bestiary/6-07/oozeshard.json
  packs/prey-for-death-bestiary/gorumite-infantry.json
  packs/sky-kings-tomb-bestiary/book-2-cult-of-the-cave-worm/mist-projector-trap.json
  packs/sky-kings-tomb-bestiary/book-2-cult-of-the-cave-worm/rolling-stone-cylinder-trap.json
  packs/sky-kings-tomb-bestiary/book-3-heavy-is-the-crown/hryngar-assassin.json
  packs/spells/unbearable-cacophony.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/leshy-mob.json
Labels: pr: data update

#18560 Move trait Adjust Strike rule elements to Item Alteration
  packs/bestiary-effects/effect-impersonated-ability.json
  packs/bestiary-effects/effect-invoke-rune.json
  packs/blog-bestiary/mari-lwyd.json
  packs/boons-and-curses/erastil-moderate-boon.json
  packs/boons-and-curses/gorum-moderate-curse.json
  packs/classfeatures/mystic-strikes.json
  packs/classfeatures/twisting-tree.json
  packs/equipment/fighters-fork.json
  packs/equipment/shield-augmentation.json
  packs/equipment/skysunder.json
  packs/feat-effects/effect-bone-spikes.json
  packs/feat-effects/effect-castigating-weapon.json
  packs/feat-effects/effect-elemental-assault.json
  packs/feat-effects/effect-mutate-weapon.json
  packs/feat-effects/stance-flood-stance.json
  packs/feat-effects/stance-waterfowl-stance.json
  packs/feat-effects/stance-wolf-stance.json
  packs/feats/ancestry/ghoran/murderous-thorns.json
  packs/feats/ancestry/goblin/fang-sharpener.json
  packs/feats/ancestry/halfling/toppling-dance.json
  packs/feats/ancestry/kobold/dragonblood-paragon.json
  packs/feats/ancestry/lizardfolk/iruxi-armaments.json
  packs/feats/ancestry/versatile-heritages/nephilim/bestial-manifestation.json
  packs/feats/archetype/ghost-eater/ghost-eater-dedication.json
  packs/feats/archetype/lich/hand-of-the-lich.json
  packs/feats/archetype/verduran-shadow/death-from-above.json
  packs/feats/archetype/warrior-of-legend/warrior-of-legend-dedication.json
  packs/feats/class/barbarian/follow-up-assault.json
  packs/feats/class/fighter/overwhelming-blow.json
  packs/feats/class/monk/wolf-drag.json
  packs/feats/class/shared-class-feats/agile-shield-grip.json
  packs/heritages/surki/breaker-surki.json
  packs/howl-of-the-wild-bestiary/warden-of-oceans-and-rivers.json
  packs/kingmaker-bestiary/gromog.json
  packs/night-of-the-gray-death-bestiary/gray-gardener-assassin.json
  packs/night-of-the-gray-death-bestiary/zintaya-calbieste.json
  packs/outlaws-of-alkenstar-bestiary/book-1-punks-in-a-powder-keg/clockwork-hunter.json
  packs/paizo-pregens/a-few-flowers-more/popcorn-level-4.json
  packs/paizo-pregens/a-fistful-of-flowers/popcorn.json
  packs/pathfinder-bestiary-2/shocker-lizard.json
  packs/pathfinder-bestiary-3/fossil-golem.json
  packs/pathfinder-monster-core/cacodaemon.json
  packs/pathfinder-monster-core/cassisian.json
  packs/pathfinder-monster-core/venedaemon.json
  packs/pathfinder-monster-core/vordine.json
  packs/pathfinder-npc-core/laborer/innkeeper.json
  packs/pfs-season-5-bestiary/5-12/topiary-beast.json
  packs/pfs-season-5-bestiary/5-12/topiary-monster.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/burning-mammoth-commando.json
  packs/spell-effects/spell-effect-apex-companion.json
  packs/spell-effects/spell-effect-qi-form.json
  packs/spell-effects/spell-effect-untwisting-iron-augmentation.json
  packs/stolen-fate-bestiary/book-1-the-choosing/arodeth.json
  packs/strength-of-thousands-bestiary/book-1-kindled-magic/urbel.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/abendego-brute.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/ajbal-kimon.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/bharlen-sajor.json
  packs/triumph-of-the-tusk-bestiary/book-3-destroyers-doom/orc-raider.json
Labels: pr: data update

#18561 Fix handling of `allowNoSelection` in ChoiceSet REs
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/system/schema-data-fields.ts
Labels: pr: bugfix

#18565 Fix description of Investigator in journals
  packs/journals/classes.json
Labels: pr: data update

#18564 Delete Perpetual potency class feature in Alchemist Class in journals
  packs/journals/classes.json
Labels: pr: data update

#18571 Correct Eshmok actor's Spell DC
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/eshmok.json
Labels: pr: data update

#18502 Get origin data when dragging effects from the actor sheet
  src/scripts/helpers.ts
  src/scripts/system/dragstart-handler.ts
  src/scripts/ui/inline-roll-links.ts
Labels: pr: bugfix

#18578 Skip failing embedded consumable spells during data preparation
  src/module/item/consumable/document.ts
Labels: pr: bugfix

#18580 Fix description in arboreal's revenge
  packs/equipment/arboreals-revenge.json
Labels: pr: data update

#18569 Add damage note to the Confused condition
  packs/conditions/confused.json
  static/lang/en.json
Labels: pr: data update

#18584 Organize select Feats into folders
  packs/feats/_folders.json
  packs/feats/archetype/sanguimancer/blood-shield.json
  packs/feats/archetype/sanguimancer/exsanguinate.json
  packs/feats/archetype/sanguimancer/sanguimancer-dedication.json
  packs/feats/archetype/sanguimancer/transfusion.json
  packs/feats/archetype/sanguimancer/venipuncture.json
  packs/feats/general/bloodsense.json
  packs/feats/general/sanguine-tenacity.json
  packs/feats/skill/vasodilation.json
Labels: pr: data update

#18572 Condense Potion of Sonic Resistance and Resonating Fork - Armor equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-potion-of-sonic-resistance-greater.json
  packs/equipment-effects/effect-potion-of-sonic-resistance-lesser.json
  packs/equipment-effects/effect-potion-of-sonic-resistance-moderate.json
  packs/equipment-effects/effect-potion-of-sonic-resistance.json
  packs/equipment-effects/effect-resonating-fork-armor-greater.json
  packs/equipment-effects/effect-resonating-fork-armor-major.json
  packs/equipment-effects/effect-resonating-fork-armor.json
  packs/equipment/potion-of-sonic-resistance-greater.json
  packs/equipment/potion-of-sonic-resistance-lesser.json
  packs/equipment/potion-of-sonic-resistance-moderate.json
  packs/equipment/resonating-fork-greater.json
  packs/equipment/resonating-fork-major.json
  packs/equipment/shield-augmentation.json
Labels: pr: data update

#18585 Fix regression due to private variable in document
  src/module/item/consumable/document.ts
Labels: pr: bugfix

#18576 Add `Hunting Spider Venom` to Remaster changes journal and improve grammar on class kit entry
  packs/journals/remaster-changes.json
Labels: pr: data update

#18586 Add TraitDescriptionShade in en.json
  static/lang/en.json
Labels: pr: data update

#18592 Updated Vishkanyan to Vishkanya in the languages
  static/lang/en.json
Labels: pr: data update

#18590 Link Powerful Leap and Quick Jump in Leap the Falls
  packs/feats/class/exemplar/leap-the-falls.json
Labels: pr: data update

#18593 Use melee and ranged selectors instead of predicates where possible
  packs/actions/vital-shot.json
  packs/agents-of-edgewatch-bestiary/book-4-assault-on-hunting-lodge-seven/jonis-flakfatter.json
  packs/bestiary-effects/effect-adaptive-strike.json
  packs/bestiary-effects/effect-blade-barrage.json
  packs/bestiary-effects/effect-harrowing-misfortune.json
  packs/bestiary-family-ability-glossary/zombie-shock-arcing-strikes.json
  packs/classfeatures/curse-of-inclement-headwinds.json
  packs/classfeatures/thief.json
  packs/equipment-effects/effect-energy-mutagen-greater.json
  packs/equipment-effects/effect-energy-mutagen-lesser.json
  packs/equipment-effects/effect-energy-mutagen-major.json
  packs/equipment-effects/effect-energy-mutagen-moderate.json
  packs/equipment-effects/effect-fury-cocktail-greater.json
  packs/equipment-effects/effect-fury-cocktail-lesser.json
  packs/equipment-effects/effect-fury-cocktail-moderate.json
  packs/extinction-curse-bestiary/book-5-lord-of-the-black-sands/raptor-guard-wight.json
  packs/feat-effects/effect-curse-of-the-perpetual-storm.json
  packs/feat-effects/effect-metallic-skin.json
  packs/feat-effects/stance-arcane-cascade.json
  packs/feat-effects/stance-point-blank-stance.json
  packs/feats/class/gunslinger/snipers-aim.json
  packs/feats/class/gunslinger/triggerbrand-salvo.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/takatorra-level-9.json
  packs/iconics/korakai-level-1.json
  packs/iconics/korakai-level-3.json
  packs/iconics/korakai-level-5.json
  packs/iconics/merisiel-level-1.json
  packs/iconics/merisiel-level-3.json
  packs/iconics/merisiel-level-5.json
  packs/kingmaker-bestiary/akiros-ismort.json
  packs/kingmaker-bestiary/pavetta-stroon-drelev.json
  packs/other-effects/effect-aquatic-combat.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/anjelique-loveless.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/vewslog.json
  packs/paizo-pregens/a-few-flowers-more/popcorn-level-4.json
  packs/paizo-pregens/a-few-flowers-more/reaching-rings-level-4.json
  packs/paizo-pregens/a-fistful-of-flowers/popcorn.json
  packs/paizo-pregens/a-fistful-of-flowers/reaching-rings.json
  packs/paizo-pregens/beginner-box/merisiel-beginner-box.json
  packs/paizo-pregens/little-trouble-in-big-absalom/quizrel.json
  packs/paizo-pregens/mark-of-the-mantis/zeah.json
  packs/paizo-pregens/sundered-waves/kaako-ashfeather.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/ivarsa.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level.json
  packs/spell-effects/spell-effect-divine-vessel.json
  packs/spell-effects/spell-effect-enlarge-companion.json
  packs/spell-effects/spell-effect-enlarge-heightened-4th.json
  packs/spell-effects/spell-effect-wrathful-storm.json
  packs/stolen-fate-bestiary/book-1-the-choosing/blade-magus.json
  packs/stolen-fate-bestiary/book-1-the-choosing/harpy-warbird.json
  packs/stolen-fate-bestiary/book-1-the-choosing/queen-kawlinawk.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/storied-harrowkin.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/wereant-poisoner.json
Labels: pr: data update

#18594 Update eslint deps, use `@eslint/json` instead of `eslint-plugin-json`
  .gitignore
  eslint.config.js
  eslint.json.config.js
  package-lock.json
  package.json
  src/module/actor/party/kingdom/builder.ts
  src/scripts/handlebars.ts
  src/scripts/macros/travel/travel-speed-sheet.ts
  src/util/misc.ts
  types/foundry/client/pixi/layers/base/placeables-layer.d.ts
  types/foundry/client/pixi/layers/placeables/lighting.d.ts
  types/foundry/client/pixi/layers/placeables/template.d.ts
  types/foundry/client/pixi/layers/placeables/walls.d.ts
  vite.config.ts.timestamp-1739057933273-a347b5142ef3c.mjs
Labels: pr: housekeeping

#18595 Implement Horn of Plenty's daily crafting
  packs/classfeatures/horn-of-plenty.json
Labels: pr: data update

#18600 Add Asmodeus' divine font
  packs/deities/core-gods/asmodeus.json
Labels: pr: data update

#18602 Add resistance on a success to Anima Invocation's spell effect
  packs/spell-effects/spell-effect-anima-invocation.json
Labels: pr: data update

#18608 Update Change Formation icon to Two Actions
  packs/bestiary-ability-glossary-srd/change-formation.json
Labels: pr: data update

#18603 Add Sanguinomancer entry to the Archetype journal
  packs/feats/archetype/sanguimancer/sanguimancer-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18607 Fix Enlarge and Enlarge Companion effects to apply bonus to all melee damage
  packs/spell-effects/spell-effect-enlarge-companion.json
  packs/spell-effects/spell-effect-enlarge-heightened-4th.json
  packs/spell-effects/spell-effect-enlarge.json
Labels: pr: data update

#18596 Condense Rime Crystal spellheart equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-rime-crystal-armor-greater.json
  packs/equipment-effects/effect-rime-crystal-armor-major.json
  packs/equipment-effects/effect-rime-crystal-armor.json
  packs/equipment-effects/effect-rime-crystal-weapon-greater.json
  packs/equipment-effects/effect-rime-crystal-weapon-major.json
  packs/equipment-effects/effect-rime-crystal-weapon.json
  packs/equipment/rime-crystal-greater.json
  packs/equipment/rime-crystal-major.json
Labels: pr: data update

#18605 Fix trait in summoning handscroll
  packs/equipment/summoning-handscroll.json
Labels: pr: data update

#18611 Change instances of metamagic in descriptions to spellshape
  packs/crown-of-the-kobold-king-bestiary/drazmorg-the-damned.json
  packs/equipment/amazing-pop-up-book.json
  packs/equipment/architects-pattern-book.json
  packs/equipment/book-of-lingering-blaze.json
  packs/equipment/codex-of-destruction-and-renewal.json
  packs/equipment/communion-mat.json
  packs/equipment/djezet-dose.json
  packs/equipment/dragons-breath-1st-level-spell.json
  packs/equipment/dragons-breath-2nd-level-spell.json
  packs/equipment/dragons-breath-3rd-level-spell.json
  packs/equipment/dragons-breath-4th-level-spell.json
  packs/equipment/dragons-breath-5th-level-spell.json
  packs/equipment/dragons-breath-6th-level-spell.json
  packs/equipment/dragons-breath-7th-level-spell.json
  packs/equipment/dragons-breath-8th-level-spell.json
  packs/equipment/dragons-breath-9th-level-spell.json
  packs/equipment/dreamstone.json
  packs/equipment/illuminated-folio.json
  packs/equipment/in-the-shadows-of-toil.json
  packs/equipment/instructions-for-lasting-agony.json
  packs/equipment/juubuns-one-thousand-poems.json
  packs/equipment/kindled-tome.json
  packs/equipment/reflexive-tattoo.json
  packs/equipment/star-chart-tattoo.json
  packs/equipment/tyrants-writs.json
  packs/equipment/warding-tablets.json
  packs/feats/archetype/magaambyan-attendant/cascade-bearers-flexibility.json
  packs/feats/archetype/spellmaster/recover-spell.json
Labels: pr: data update

#18613 Condense Lastwall soup equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-lastwall-soup-greater.json
  packs/equipment-effects/effect-lastwall-soup-improved.json
  packs/equipment-effects/effect-lastwall-soup.json
  packs/equipment/lastwall-soup-greater.json
  packs/equipment/lastwall-soup-improved.json
Labels: pr: data update

#18609 Add Strategic Strike dice number increase to Palatine Strike
  packs/feats/archetype/palatine-detective/palatine-strike.json
Labels: pr: data update

#18628 Condense Sanguine Fang equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-sanguine-fang-armor-greater.json
  packs/equipment-effects/effect-sanguine-fang-armor-major.json
  packs/equipment-effects/effect-sanguine-fang-armor.json
  packs/equipment-effects/effect-sanguine-fang-weapon-greater.json
  packs/equipment-effects/effect-sanguine-fang-weapon-major.json
  packs/equipment-effects/effect-sanguine-fang-weapon.json
  packs/equipment/sanguine-fang-greater.json
  packs/equipment/sanguine-fang-major.json
  packs/equipment/sanguine-fang.json
Labels: pr: data update

#18623 Update `Ranger Expertise` class feature to account for Vindicator Class Archetype
  packs/classfeatures/ranger-expertise.json
Labels: pr: data update

#18604 Add Stunning Appearance Note automation for Startling Appearance (Vigilante)
  packs/feats/archetype/vigilante/stunning-appearance.json
Labels: pr: data update

#18614 Add some missing condition links
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/black-whale-guard-f3.json
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/black-whale-guard.json
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/ixusoth.json
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/myrucarx.json
  packs/feats/class/fighter/shatter-defenses.json
  packs/pathfinder-bestiary-3/hyakume.json
Labels: pr: data update

#18615 Remove check and speed penalty, and strength requirement from Reinforced Chassis
  packs/equipment/reinforced-chassis.json
Labels: pr: data update

#18616 Brush up Bonds of Iron NPC ability
  packs/age-of-ashes-bestiary/book-3-tomorrow-must-burn/rusty-mae.json
  packs/blood-lords-bestiary/book-2-graveclaw/iron-taviah.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/vampire-taviah.json
  packs/kingmaker-bestiary/jaggedbriar-hag.json
  packs/kingmaker-bestiary/the-knurly-witch.json
  packs/pathfinder-bestiary/annis-hag.json
  packs/pathfinder-monster-core/iron-hag.json
  packs/pfs-season-1-bestiary/1-06/annis-hag-1-06.json
Labels: pr: data update

#18618 Add immobilize on critical success to Tangle Vine effect
  packs/spell-effects/spell-effect-tangle-vine.json
Labels: pr: data update

#18619 Add increased Oath of the Defender's champion's resistance
  packs/feat-effects/effect-oath-of-the-defender.json
Labels: pr: data update

#18621 Add weaver of webs source for remove condition
  packs/war-of-immortals-bestiary/weaver-of-webs.json
Labels: pr: data update

#18622 Add traits to Omen Dragon's `Challenge Fate` ability
  packs/pathfinder-monster-core/omen-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-adult.json
  packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-ancient.json
  packs/pathfinder-monster-core/omen-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-young.json
Labels: pr: data update

#18635 Add automation to Sojiruh's Manifest Armor ability
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/sojiruh.json
Labels: pr: data update

#18641 Link self effect to Reflective Ripple Stance
  packs/feats/class/monk/reflective-ripple-stance.json
Labels: pr: data update

#18642 Fix resistances for Dragon Shape feat
  packs/feats/class/druid/reactive-transformation.json
  packs/spell-effects/spell-effect-untamed-form.json
Labels: pr: data update

#18647 Show spell traditions in description for unowned actors
  src/module/item/spell/document.ts
Labels: pr: bugfix

#18646 Fix action type and cost of Distracting Performance
  packs/feats/skill/distracting-performance.json
Labels: pr: data update

#18643 Condense Saurian Spike spellheart equipment effects and brush up Lightweave Scarf (armor) effect
  build/uuid-redirects.json
  packs/equipment-effects/effect-lightweave-scarf-armor.json
  packs/equipment-effects/effect-saurian-spike-armor-greater.json
  packs/equipment-effects/effect-saurian-spike-armor-major.json
  packs/equipment-effects/effect-saurian-spike-armor.json
  packs/equipment/saurian-spike-greater.json
  packs/equipment/saurian-spike-major.json
Labels: pr: data update

#18649 Fix ammo consumption of repeating double-barrel weapons
  src/module/item/consumable/document.ts
Labels: pr: bugfix
