Repository foundryvtt/pf2e, pull requests merged in 2025-08, with the labels that each got.

#19749 Condense Taunt's Bodyguard Adjust Modifier rule elements
  packs/feat-effects/effect-taunt.json
  static/lang/re-en.json
Labels: pr: data update

#19750 Update classes journal with Commander and Guardian
  packs/classes/commander.json
  packs/classes/guardian.json
  packs/journals/classes.json
Labels: pr: data update

#19751 Sort usages list in item sheet
  src/module/item/physical/sheet.ts
Labels: localization

#19779 Fix jabali's rarity
  packs/pathfinder-monster-core/jabali.json
Labels: pr: data update

#19782 Localize name alteration value in item alteration
  src/module/rules/rule-element/item-alteration/alteration.ts
Labels: pr: enhancement

#19783 Fix Kingdom collection
  src/module/actor/party/kingdom/chat.ts
  src/module/actor/party/kingdom/model.ts
  src/module/apps/sidebar/chat-log.ts
  static/lang/kingmaker-en.json
  static/templates/actors/party/kingdom/collection.hbs
Labels: pr: bugfix, kingmaker

#19781 Add spell effect for Shielding Formation
  packs/spell-effects/spell-effect-shielding-formation.json
  packs/spells/focus/shielding-formation.json
  static/lang/re-en.json
Labels: pr: data update

#19780 Add class description to Battlecry! iconics and fix path to token texture
  packs/iconics/grimmyr-level-1.json
  packs/iconics/grimmyr-level-3.json
  packs/iconics/grimmyr-level-5.json
  packs/iconics/ulka-level-1.json
  packs/iconics/ulka-level-3.json
  packs/iconics/ulka-level-5.json
Labels: pr: data update

#19775 Condense Devil Form spell effect
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-devil-form-coarti.json
  packs/spell-effects/spell-effect-devil-form-levaloch.json
  packs/spell-effects/spell-effect-devil-form-sarglagon.json
  packs/spell-effects/spell-effect-devil-form-vordine.json
  packs/spell-effects/spell-effect-devil-form.json
  packs/spells/6th-rank/devil-form.json
  static/lang/re-en.json
Labels: pr: data update

#19765 Add inline healing roll to Rallying Banner
  packs/feats/class/commander/rallying-banner.json
Labels: pr: data update

#19759 Convert `Wand of Dumbfounding Doom` to proper magic wand type
  packs/equipment/wand-of-clinging-rime-7th-rank.json
  packs/equipment/wand-of-contagious-frailty.json
  packs/equipment/wand-of-dumbfounding-doom-3rd-rank.json
  packs/equipment/wand-of-dumbfounding-doom-4th-rank.json
  packs/equipment/wand-of-dumbfounding-doom-5th-rank.json
  packs/equipment/wand-of-dumbfounding-doom-6th-rank.json
  packs/equipment/wand-of-dumbfounding-doom-7th-rank.json
  packs/equipment/wand-of-dumbfounding-doom-8th-rank.json
  packs/equipment/wand-of-dumbfounding-doom-9th-rank.json
Labels: pr: data update

#19753 Run migrations on current content
  packs/equipment/hydra-head-club.json
  packs/equipment/protectors-final-gift.json
  packs/gatewalkers-bestiary/book-1-the-seventh-arch/captain-salah.json
  packs/gatewalkers-bestiary/book-1-the-seventh-arch/leiko.json
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/deniigi.json
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/innumma.json
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/ulikuq.json
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/valmar.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/akki.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/animated-panoply.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/ekleios.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/phermeina.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/sappil.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/sedacthy-scout.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/yasmenei.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/amnerion.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/eumenid.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/firehoof-minotaur.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/vornen.json
  packs/spells/focus/crown-of-prophets.json
  packs/spells/focus/gift-of-the-anemos.json
Labels: pr: data update

#19778 Add effect to `Mantle of the Melting Heart`
  packs/spell-effects/spell-effect-mantle-of-the-melting-heart.json
  packs/spells/5th-rank/mantle-of-the-melting-heart.json
  static/lang/re-en.json
Labels: pr: data update

#17894 Add Heart of Ice and Heart of Fire effects for Mantle of Frozen and Magma Heart spells
  packs/spell-effects/spell-effect-mantle-of-the-frozen-heart.json
  packs/spell-effects/spell-effect-mantle-of-the-magma-heart.json
  static/lang/re-en.json
Labels: pr: data update

#19728 Update effect links in the static language file
  build/uuid-redirects.json
  static/lang/re-en.json
Labels: pr: data update

#19757 Fix the rune in the major version of the jyoti's feather
  packs/equipment/jyotis-feather-major.json
Labels: pr: data update

#19786 Address remaining errors in Foundry type definitions
  src/global.ts
  src/module/actor/creature/sense.ts
  src/module/canvas/perception/point-vision-source.ts
  types/foundry/client/applications/apps/document-sheet-config.d.mts
  types/foundry/client/applications/sheets/_module.d.mts
  types/foundry/client/applications/sheets/template-config.d.mts
  types/foundry/client/canvas/containers/_module.d.mts
  types/foundry/client/canvas/containers/advanced/full-canvas-mixin.d.mts
  types/foundry/client/canvas/containers/advanced/full-container-mixin.d.mts
  types/foundry/client/canvas/containers/elements/particles/leaves.d.mts
  types/foundry/client/canvas/containers/elements/particles/particle-effect.d.mts
  types/foundry/client/canvas/layers/effects/background-effects.d.mts
  types/foundry/client/canvas/layers/effects/coloration-effects.d.mts
  types/foundry/client/canvas/layers/effects/darkness-effects.d.mts
  types/foundry/client/canvas/layers/effects/illumination-effects.d.mts
  types/foundry/client/canvas/layers/effects/weather-effects.d.mts
  types/foundry/client/canvas/rendering/mixins/fragment-channel-mixin.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/documents/abstract/client-document.d.mts
  types/foundry/client/documents/measured-template.d.mts
  types/foundry/client/global.d.mts
  types/foundry/common/abstract/data.d.mts
  types/foundry/common/abstract/document.d.mts
  types/foundry/common/documents/token.d.mts
  types/foundry/common/packages/base-package.d.mts
Labels: pr: types update

#19785 Add effects for Naval and Mountaineering Training Tactics
  packs/actions/mountaineering-training.json
  packs/actions/naval-training.json
  packs/feat-effects/effect-mountaineering-training.json
  packs/feat-effects/effect-naval-training.json
Labels: pr: data update

#19787 Release Notes 7.3.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19788 Update NPM dependencies
  package-lock.json
  package.json
  src/module/item/base/sheet/sheet.ts
  vite.config.ts
Labels: pr: housekeeping

#19789 Add reserved class traits to `readModuleHomebrewSettings`
  src/module/system/settings/homebrew/helpers.ts
Labels: pr: bugfix

#19792 Fix build on windows
  package-lock.json
  package.json
  vite.config.ts
Labels: pr: housekeeping

#19804 Remove AC details text from Losko actor
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/losko.json
Labels: pr: data update

#19806 Fix missing and incorrect sources
  packs/actions/crescent-spray.json
  packs/actions/engineers-efficiency.json
  packs/actions/mobbing-assault.json
  packs/actions/raise-the-horde.json
  packs/actions/spread-propaganda.json
  packs/battlecry-bestiary/kobold-trap-squad.json
  packs/battlecry-bestiary/viking-guard.json
  packs/bestiary-effects/effect-guard-charge.json
  packs/bestiary-effects/effect-hasty-traps.json
  packs/equipment-effects/effect-toothy-knife.json
  packs/equipment/dawnfire-beacon.json
  packs/equipment/doomsweeper.json
  packs/equipment/generals-word.json
  packs/equipment/standard-of-the-sure-footed.json
  packs/feat-effects/effect-aesir-blood-magic.json
  packs/feat-effects/effect-dismal-harvest.json
  packs/feat-effects/effect-nanite-surge-bonus.json
  packs/feat-effects/effect-shield-from-arrows.json
  packs/feat-effects/effect-shield-your-eyes.json
  packs/feats/general/shield-block.json
  packs/spell-effects/spell-effect-conquering-soldiers-depart.json
  packs/spell-effects/spell-effect-curse-of-recoil-critical-failure.json
  packs/spell-effects/spell-effect-curse-of-recoil-failure.json
  packs/vehicles/pathfinder-battlecry/combat-kite.json
  packs/vehicles/pathfinder-battlecry/nighthawk.json
Labels: pr: data update

#19803 Audit automation and formatting on Jotunborn feats
  packs/feat-effects/effect-plane-stepping-dash.json
  packs/feat-effects/stance-jotuns-battle-stance.json
  packs/feats/ancestry/jotunborn/level-1/caretakers-restoration.json
  packs/feats/ancestry/jotunborn/level-1/jotunborn-lore.json
  packs/feats/ancestry/jotunborn/level-1/jotunborn-weapon-familiarity.json
  packs/feats/ancestry/jotunborn/level-1/plane-stepping-dash.json
  packs/feats/ancestry/jotunborn/level-13/iivlars-boundary-break.json
  packs/feats/ancestry/jotunborn/level-13/jotuns-restoration.json
  packs/feats/ancestry/jotunborn/level-17/jotuns-heart.json
  packs/feats/ancestry/jotunborn/level-17/jotuns-transposition.json
  packs/feats/ancestry/jotunborn/level-5/planar-resilience.json
  packs/feats/ancestry/jotunborn/level-5/pounding-leap.json
  packs/feats/ancestry/jotunborn/level-9/iivlars-deflection.json
  packs/feats/ancestry/jotunborn/level-9/plane-step.json
  packs/heritages/jotunborn/weaver-jotunborn.json
  static/lang/re-en.json
Labels: pr: data update

#19795 Convert `Wand of Hawthorn` equipment type to magic wand
  packs/equipment/wand-of-hawthorn-2nd-rank.json
  packs/equipment/wand-of-hawthorn-4th-rank.json
  packs/equipment/wand-of-hawthorn-6th-rank.json
  packs/equipment/wand-of-hawthorn-8th-rank.json
Labels: pr: data update

#19797 Condense `Fey Form` spell effects
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-devil-form.json
  packs/spell-effects/spell-effect-fey-form-dryad.json
  packs/spell-effects/spell-effect-fey-form-elananx.json
  packs/spell-effects/spell-effect-fey-form-naiad.json
  packs/spell-effects/spell-effect-fey-form-redcap.json
  packs/spell-effects/spell-effect-fey-form-unicorn.json
  packs/spell-effects/spell-effect-fey-form.json
  packs/spells/4th-rank/fey-form.json
  packs/spells/6th-rank/devil-form.json
  static/lang/re-en.json
Labels: pr: data update

#19800 Add `area-effect`, `area-damage`, `damage-effect`, and `inflicts:` options to additional select items and NPC abilities
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/seugathi-reality-warper.json
  packs/age-of-ashes-bestiary/book-2-cult-of-cinders/charau-ka-dragon-priest.json
  packs/battlecry-bestiary/clockwork-runner-pack.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/drowned-mummy.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/gray-master.json
  packs/howl-of-the-wild-bestiary/blooming-guardian.json
  packs/kingmaker-bestiary/the-knurly-witch.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/broken-centurion.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/clockwork-buccaneer.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/glass-buccaneer.json
  packs/pathfinder-bestiary-2/bralani.json
  packs/pathfinder-bestiary-2/lerritan.json
  packs/pathfinder-bestiary-3/peri.json
  packs/pathfinder-monster-core/cloud-giant.json
  packs/pathfinder-monster-core/ifrit.json
  packs/pathfinder-monster-core/witchwarg.json
  packs/pfs-season-6-bestiary/6-16/screaming-grub-necromancer.json
  packs/pfs-season-6-bestiary/quests/arrogant-foroxicks.json
  packs/prey-for-death-bestiary/rhysaphine.json
  packs/quest-for-the-frozen-flame-bestiary/book-1-broken-tusk-moon/kadlaka.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/tar-zombie-mammoth.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/tar-zombie-predator.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/tar-zombie-snatcher.json
  packs/rage-of-elements-bestiary/blustering-gale.json
  packs/seven-dooms-for-sandpoint-bestiary/minargul.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/miranette.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/sun-warrior-brigade.json
  packs/triumph-of-the-tusk-bestiary/book-1-the-resurrection-flood/floodslain-mage.json
  packs/triumph-of-the-tusk-bestiary/book-1-the-resurrection-flood/floodslain-orc.json
  packs/triumph-of-the-tusk-bestiary/book-1-the-resurrection-flood/floodslain-wolf.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/ruzadoya-swiftmane.json
Labels: pr: data update

#19811 Also check source name when retrieving context clone weapon during rolls
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#19823 Fix more type errors, update types package.json
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  types/foundry/client/utils/helpers.d.mts
  types/foundry/package.json
Labels: pr: refactor, pr: types update

#19827 Update typescript to 5.9.2
  package-lock.json
  package.json
  src/util/uuid.ts
  tests/module/migration.test.ts
Labels: pr: housekeeping

#19807 Add Toggle Compendium Browser keybinding
  src/scripts/register-keybindings.ts
  static/lang/en.json
Labels: pr: enhancement

#19829 Add notification to PC sheet when no armor is equipped but one is equippable
  src/module/actor/character/document.ts
  src/module/actor/character/helpers.ts
  src/module/actor/character/sheet.ts
  src/module/actor/sheet/data-types.ts
  static/templates/actors/partials/item-line.hbs
Labels: pr: enhancement

#19831 Fix the level of primal howl feat
  packs/feats/class/druid/primal-howl.json
Labels: pr: data update

#19832 Use modifier instead of total DC on inline DC AdjustModifier upgrades
  packs/feats/archetype/crossbow-infiltrator/lethargy-poisoner.json
  packs/feats/archetype/guerrilla/level-4/snare-expert.json
Labels: pr: data update

#19845 Fix grant type error
  src/module/item/condition/document.ts
Labels: pr: types update

#19839 Set key attribute on multiclass dedication class DC subfeatures
  packs/feats/archetype/commander/commander-dedication.json
  packs/feats/archetype/guardian/guardian-dedication.json
  packs/feats/archetype/thaumaturge/thaumaturge-dedication.json
Labels: pr: data update

#19849 Fix type instantiation error in `TokenDocumentPF2e`
  src/module/scene/token-document/document.ts
  types/foundry/client/applications/sheets/combatant-config.d.mts
  types/foundry/client/canvas/placeables/token.d.mts
Labels: pr: types update

#19850 Fix accessing `showdown` global
  tsconfig.json
  types/foundry/client/global.d.mts
Labels: pr: types update

#19851 Fix remaining type errors, turn back on type checking in vite config
  src/module/actor/party/data.ts
  src/module/actor/party/document.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/apps/sidebar/item-directory.ts
  src/module/canvas/perception/point-vision-source.ts
  src/module/canvas/token/aura/util.ts
  types/foundry/client/canvas/geometry/clockwise-sweep.d.mts
  types/foundry/client/config.d.mts
  vite.config.ts
Labels: pr: bugfix, pr: types update

#19721 Add support for weapon, armor, and shield grade
  build/run-migration.ts
  packs/equipment/mindrender-baton.json
  packs/equipment/rod-of-razors.json
  packs/kingmaker-bestiary/castruccio-irovetti.json
  src/module/actor/character/automatic-bonus-progression.ts
  src/module/item/armor/data.ts
  src/module/item/armor/document.ts
  src/module/item/armor/sheet.ts
  src/module/item/physical/helpers.ts
  src/module/item/physical/types.ts
  src/module/item/shield/data.ts
  src/module/item/shield/document.ts
  src/module/item/shield/sheet.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/module/migration/migrations/942-equipment-grade.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/scripts/config/index.ts
  src/scripts/config/traits.ts
  static/lang/en.json
  static/template.json
  static/templates/items/armor-details.hbs
  static/templates/items/shield-details.hbs
  static/templates/items/weapon-details.hbs
  types/foundry/client/applications/api/dialog.d.mts
Labels: pr: enhancement, sf2e

#19717 Convert item alteration validators from switch/case to dictionary
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/handlers.ts
  src/module/rules/rule-element/item-alteration/helper.ts
Labels: pr: refactor

#19852 Add `area-damage`, `area-effect`, `damage-effect`, and `inflicts:` options to additional select items and NPC abilities
  packs/battlecry-bestiary/boggard-scouting-party.json
  packs/battlecry-bestiary/clockwork-runner-pack.json
  packs/battlecry-bestiary/drake-flight.json
  packs/battlecry-bestiary/fleshwarp-amalgam.json
  packs/battlecry-bestiary/giant-ant-army.json
  packs/battlecry-bestiary/halfling-lucky-draw.json
  packs/battlecry-bestiary/hell-hound-pack.json
  packs/battlecry-bestiary/vanth-guardian-flock.json
  packs/battlecry-bestiary/wight-battalion.json
  packs/blog-bestiary/urok.json
  packs/book-of-the-dead-bestiary/last-guard.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/speiroikos.json
  packs/pathfinder-bestiary-3/nightmarchers.json
  packs/pathfinder-bestiary-3/pufferfish.json
  packs/pfs-season-6-bestiary/6-19/the-husk-of-deskari-13-14.json
  packs/pfs-season-6-bestiary/6-19/the-husk-of-deskari.json
  packs/rage-of-elements-bestiary/rakkatak.json
  packs/sky-kings-tomb-bestiary/book-3-heavy-is-the-crown/hryngar-breccia-squad.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/gold-defender-garrison.json
  packs/triumph-of-the-tusk-bestiary/book-2-hoof-cinder-and-storm/aurochs-herd.json
  packs/wardens-of-wildwood-bestiary/book-1-packbreaker/stormdrinker.json
Labels: pr: data update

#19863 Add `area-damage`, `area-effect`, `damage-effect`, and `inflicts:` options to select items and NPC abilities
  packs/battlecry-bestiary/clockwork-infantry.json
  packs/battlecry-bestiary/druid-circle.json
  packs/battlecry-bestiary/hobgoblin-veteran-regiment.json
  packs/battlecry-bestiary/leukodaemon-plague.json
  packs/battlecry-bestiary/monk-cadre.json
  packs/battlecry-bestiary/ofalth-stampede.json
  packs/battlecry-bestiary/ratfolk-shank-squad.json
  packs/battlecry-bestiary/skeleton-mob.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/urbulinex.json
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/onturat.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/planar-terra-cotta-squadron.json
  packs/night-of-the-gray-death-bestiary/pageant-troupe.json
  packs/pathfinder-bestiary-3/terra-cotta-garrison.json
  packs/pathfinder-monster-core/skulltaker.json
  packs/prey-for-death-bestiary/einherji-host.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/tokainen.json
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/lukarazyll.json
Labels: pr: data update

#19873 Correct Horus' divine font to heal
  packs/deities/in-memoriam/horus.json
Labels: pr: data update

#19853 Delete Pathfinder Bestiary `Terotricus` actor and redirect to the Monster Core equivalent
  build/uuid-redirects.json
  packs/pathfinder-bestiary/terotricus.json
  packs/pathfinder-monster-core/terotricus.json
Labels: pr: data update

#19875 Show disabled Elemental Blast attack for kineticists without Kinetic Aura effect
  src/module/actor/character/elemental-blast.ts
  src/module/actor/character/sheet.ts
  src/module/sheet/helpers.ts
  static/lang/re-en.json
  static/templates/actors/character/partials/elemental-blast.hbs
Labels: pr: enhancement

#19704 Add installed usage and sf2e weapon/armor upgrades
  src/module/actor/sheet/base.ts
  src/module/apps/item-attacher.ts
  src/module/item/armor/document.ts
  src/module/item/base/data/values.ts
  src/module/item/equipment/document.ts
  src/module/item/equipment/sheet.ts
  src/module/item/physical/document.ts
  src/module/item/physical/helpers.ts
  src/module/item/physical/sheet.ts
  src/module/item/physical/usage.ts
  src/module/item/weapon/document.ts
  src/module/sheet/helpers.ts
  src/scripts/config/index.ts
  src/scripts/config/usage.ts
  static/lang/en.json
  static/templates/items/item-attacher.hbs
Labels: pr: enhancement, sf2e

#19883 Omit level from mythic point rerolls if Proficiency without Level is enabled
  src/module/system/check/check.ts
Labels: pr: bugfix

#19884 Adjust Compendium Browser settings CSS for v13
  src/styles/system/_compendium-browser-settings.scss
Labels: pr: bugfix

#19879 Update Spirit Turtle's Unbalancing Stomp to use Damage Alteration.
  packs/battlecry-bestiary/omox-slime-pool.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/spirit-turtle.json
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/protosoul.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/neshkefru.json
  packs/pfs-season-1-bestiary/1-15/hogweed-leshy-1-2.json
  packs/pfs-season-1-bestiary/1-15/hogweed-leshy-3-4.json
  packs/pfs-season-1-bestiary/1-15/plum-leshy-1-2.json
  packs/pfs-season-1-bestiary/1-15/plum-leshy-3-4.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/animated-treasure-swarm.json
Labels: pr: data update

#19854 Fix AdjustModifier rules targeting Parry
  packs/feats/ancestry/dwarf/protective-sheath.json
  packs/feats/archetype/spirit-warrior/flowing-palm-deflection.json
  packs/feats/class/guardian/raise-haft.json
  packs/iconics/grimmyr-level-3.json
  packs/iconics/grimmyr-level-5.json
Labels: pr: data update

#19855 Grant Tactics feature with Commander Dedication
  packs/classfeatures/tactics.json
  packs/feats/archetype/commander/commander-dedication.json
Labels: pr: data update

#19862 Convert `Wand of Noisome Acid` equipment items to magic wands
  packs/equipment/wand-of-noisome-acid-2nd-rank.json
  packs/equipment/wand-of-noisome-acid-4nd-rank.json
  packs/equipment/wand-of-noisome-acid-6th-rank.json
  packs/equipment/wand-of-noisome-acid-8th-rank.json
Labels: pr: data update

#19876 Add effect for Hellshadow's Clinging Smoke
  packs/bestiary-effects/effect-clinging-smoke.json
  packs/curtain-call-bestiary/book-1-stage-fright/hellshadow.json
Labels: pr: data update

#19885 Convert legal notice to `ApplicationV2`
  src/global.ts
  src/module/apps/legal-notice.ts
  src/module/apps/license-viewer/app.ts
  src/scripts/hooks/render-settings.ts
  src/scripts/set-game-pf2e.ts
  src/styles/system/_index.scss
  src/styles/system/license-viewer/_index.scss
  static/lang/en.json
  static/templates/packs/license-viewer.hbs
  types/foundry/client/applications/api/dialog.d.mts
Labels: pr: refactor

#19813 Set location keys on War Mage and Munitions Master dedication feats
  packs/feats/archetype/munitions-master/munitions-master-dedication.json
  packs/feats/archetype/war-mage/war-mage-dedication.json
Labels: pr: data update

#19814 Fix crossbow infiltrator feat sorces
  packs/feats/archetype/crossbow-infiltrator/lethargy-poisoner.json
  packs/feats/archetype/crossbow-infiltrator/repeating-hand-crossbow-training.json
Labels: pr: data update

#19818 Update roll syntax for Fortune's Coin to use `coin flip`
  packs/equipment/fortunes-coin-platinum.json
  packs/equipment/fortunes-coin.json
Labels: pr: data update

#19820 Remove non-exclusive class archetypes from early class feature selection
  packs/classfeatures/animistic-practice.json
  packs/classfeatures/arcane-school.json
  packs/classfeatures/bloodline.json
  packs/classfeatures/cause.json
  packs/classfeatures/conscious-mind.json
  packs/classfeatures/doctrine.json
  packs/classfeatures/druidic-order.json
  packs/classfeatures/elemental-magic.json
  packs/classfeatures/flexible-spell-preparation.json
  packs/classfeatures/gunslingers-way.json
  packs/classfeatures/hunters-edge.json
  packs/classfeatures/hybrid-study.json
  packs/classfeatures/innovation.json
  packs/classfeatures/instinct.json
  packs/classfeatures/light-mortar-innovation.json
  packs/classfeatures/methodology.json
  packs/classfeatures/muses.json
  packs/classfeatures/mystery.json
  packs/classfeatures/patron.json
  packs/classfeatures/research-field.json
  packs/classfeatures/rogues-racket.json
  packs/classfeatures/seneschal.json
  packs/classfeatures/subconscious-mind.json
  packs/classfeatures/swashbucklers-style.json
  packs/classfeatures/wellspring-magic.json
  packs/feats/archetype/barbarian/barbarian-dedication.json
  packs/feats/archetype/bard/bard-dedication.json
  packs/feats/archetype/champion/champion-dedication.json
  packs/feats/archetype/druid/druid-dedication.json
  packs/feats/archetype/gunslinger/gunslinger-dedication.json
  packs/feats/archetype/inventor/inventor-dedication.json
  packs/feats/archetype/investigator/investigator-dedication.json
  packs/feats/archetype/oracle/oracle-dedication.json
  packs/feats/archetype/psychic/psychic-dedication.json
  packs/feats/archetype/sorcerer/sorcerer-dedication.json
  packs/feats/archetype/swashbuckler/swashbuckler-dedication.json
  packs/feats/archetype/witch/witch-dedication.json
  packs/feats/class/druid/order-explorer.json
  static/lang/re-en.json
Labels: pr: data update

#19842 Widen Clue In's Flat Modifier selector to apply to any check
  packs/feat-effects/effect-clue-in.json
  packs/feats/class/investigator/detectives-readiness.json
Labels: pr: data update

#19888 Convert `Wand of Paralytic Shock` to magic wand
  packs/equipment/wand-of-paralytic-shock-3rd-rank.json
  packs/equipment/wand-of-paralytic-shock-7th-rank.json
Labels: pr: data update

#19892 Fix flanking detection failing for tiny creatures in some positions
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#19891 Fix level of lightspeed assault
  packs/feats/miscellaneous/deviant/lightspeed-assault.json
Labels: pr: data update

#19897 Add time trait to IWR
  src/module/actor/data/iwr.ts
  src/scripts/config/iwr.ts
  src/scripts/config/traits.ts
  static/lang/en.json
Labels: pr: data update

#19901 Discard duplicate `Steel Shield` equipment item
  packs/equipment/steel-shield-copy.json
Labels: pr: data update

#19912 Correct source for Quick Draw player feat
  packs/feats/class/shared-class-feats/quick-draw.json
Labels: pr: data update

#19914 Remove inline roll from `Attached` trait description
  static/lang/en.json
Labels: pr: data update

#19917 Convert `Wand of Shocking Haze` and `Wand of Shrouded Step` into magic wands
  packs/equipment/wand-of-shocking-haze.json
  packs/equipment/wand-of-shrouded-step.json
Labels: pr: data update

#19911 Brush up instances of Protean Anatomy
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/hegessik.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/hestriviniaas.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/ilsetsya-wyrmtouched.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/izfiitar.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/overdrive-imentesh.json
  packs/battlecry-bestiary/protean-tumult.json
  packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/grandmama.json
  packs/pathfinder-bestiary-2/akizendri.json
  packs/pathfinder-bestiary-2/imentesh.json
  packs/pathfinder-bestiary/naunet.json
  packs/pathfinder-monster-core/azuretzi.json
  packs/pathfinder-monster-core/keketar.json
  packs/pathfinder-monster-core/voidworm.json
  packs/pfs-season-1-bestiary/1-21/mr-chitters-5-6.json
  packs/pfs-season-1-bestiary/1-21/mr-chitters-7-8.json
  packs/pfs-season-1-bestiary/1-21/voidworm-ouroboros.json
  packs/pfs-season-2-bestiary/2-09/the-scholar-of-sorts-1-2.json
  packs/pfs-season-2-bestiary/2-09/the-scholar-of-sorts-3-4.json
  packs/pfs-season-3-bestiary/3-18/pelagastr-tail.json
  packs/pfs-season-3-bestiary/3-18/thick-pelagastr-tail.json
  packs/prey-for-death-bestiary/alktherisa-and-omprisgor.json
Labels: pr: data update

#19900 Condense effects for Cosmic Form
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-angel-form-choral.json
  packs/spell-effects/spell-effect-cosmic-form-moon.json
  packs/spell-effects/spell-effect-cosmic-form-sun.json
  packs/spell-effects/spell-effect-cosmic-form.json
  packs/spell-effects/spell-effect-nature-incarnate.json
  packs/spells/7th-rank/cosmic-form.json
  static/lang/re-en.json
Labels: pr: data update

#19896 Convert `Wand of Pernicious Poison` to magic wand
  packs/equipment/wand-of-pernicious-poison-1st-rank.json
  packs/equipment/wand-of-pernicious-poison-6th-rank.json
Labels: pr: data update

#19895 Condense Daemon Form spell effects and correct Kithangian size in Demon Form spell effect
  build/uuid-redirects.json
  packs/spell-effects/spell-effect-daemon-form-lacridaemon.json
  packs/spell-effects/spell-effect-daemon-form-leukodaemon.json
  packs/spell-effects/spell-effect-daemon-form-meladaemon.json
  packs/spell-effects/spell-effect-daemon-form-venedaemon.json
  packs/spell-effects/spell-effect-daemon-form.json
  packs/spell-effects/spell-effect-demon-form.json
  packs/spells/6th-rank/daemon-form.json
  static/lang/re-en.json
Labels: pr: data update

#19919 Add Special Statistics and Roll Options to Fulcrum Lens items
  packs/equipment/crimson-fulcrum-lens.json
  packs/equipment/emerald-fulcrum-lens.json
  packs/equipment/fulcrum-lattice.json
  packs/equipment/ochre-fulcrum-lens.json
  static/lang/re-en.json
Labels: pr: data update

#19878 Add actor to Phantasmal Protagonist and spell effect for temporary Hit Points
  packs/kingmaker-bestiary/phantasmal-protagonist.json
  packs/spell-effects/spell-effect-thematic-action-ally.json
  packs/spells/4th-rank/phantasmal-protagonist.json
  static/lang/re-en.json
Labels: pr: data update

#19809 Condense various Parry feat effects
  packs/equipment-effects/effect-parry.json
  packs/feats/class/fighter/dueling-parry.json
  packs/feats/class/gunslinger/defensive-armaments.json
  packs/feats/class/shared-class-feats/twin-parry.json
  packs/feats/class/swashbuckler/extravagant-parry.json
  static/lang/re-en.json
Labels: pr: data update

#19920 Update Demontangle actor to Remaster variant
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/demontangle.json
Labels: pr: data update

#19921 Increase duration of Effect: Devise a Stratagem to expire on next turn start
  packs/feat-effects/effect-devise-a-stratagem.json
Labels: pr: data update

#19922 Update Protosoul actor to match Remaster changes
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/protosoul.json
Labels: pr: data update

#19924 Add tokens for Battlecry! Iconics
  packs/iconics/grimmyr-level-1.json
  packs/iconics/grimmyr-level-3.json
  packs/iconics/grimmyr-level-5.json
  packs/iconics/ulka-level-1.json
  packs/iconics/ulka-level-3.json
  packs/iconics/ulka-level-5.json
  static/icons/iconics/Grimmyr.webp
  static/icons/iconics/GrimmyrSubject.webp
  static/icons/iconics/Ulka.webp
  static/icons/iconics/UlkaSubject.webp
Labels: pr: data update

#19923 Add heightening info to Collective Transposition
  packs/spells/6th-rank/collective-transposition.json
Labels: pr: data update

#19928 Fix dynamic autoscaling for unlinked tokens
  src/module/actor/base.ts
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#19938 Add `highest` property to actor resistance and weakness arrays
  src/module/actor/army/data.ts
  src/module/actor/base.ts
  src/module/actor/data/base.ts
  src/module/actor/hazard/data.ts
  src/module/actor/loot/data.ts
  src/module/actor/party/data.ts
  src/module/actor/vehicle/data.ts
Labels: pr: enhancement

#19794 Fix TokenImage form opacity and scale inputs
  src/module/item/base/sheet/rule-element-form/token-image.ts
Labels: pr: bugfix

#19943 Fix regression with editing non-physical items
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#19950 Add `area-damage`, `area-effect`, `damage-effect`, and `inflicts:` options to select NPC abilities
  packs/actions/crescent-spray.json
  packs/age-of-ashes-bestiary/book-6-broken-promises/candlarons-echo.json
  packs/agents-of-edgewatch-bestiary/book-1-devil-at-the-dreaming-palace/siege-shard.json
  packs/bestiary-family-ability-glossary/ghost/ghost-frightful-moan.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/vice-chancellor-vikroti-stroh.json
  packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/facade.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/venomfist.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/ghost-monk.json
  packs/howl-of-the-wild-bestiary/blooming-guardian.json
  packs/kingmaker-bestiary/elder-elemental-tsunami.json
  packs/kingmaker-bestiary/ghostly-guard.json
  packs/kingmaker-bestiary/jin-durwhimmer.json
  packs/lost-omens-bestiary/monsters-of-myth/cuetzmonquali.json
  packs/menace-under-otari-bestiary/ghost-commoner-bb.json
  packs/pathfinder-bestiary-2/frost-worm.json
  packs/pathfinder-monster-core/elemental-tsunami.json
  packs/pathfinder-monster-core/ghost-commoner.json
  packs/pathfinder-monster-core/ghost-mage.json
  packs/pfs-season-1-bestiary/1-11/ghost-of-diggen-thrune-1-2.json
  packs/pfs-season-1-bestiary/1-11/ghost-of-diggen-thrune-3-4.json
  packs/pfs-season-3-bestiary/3-02/eloises-ghost-1-2.json
  packs/pfs-season-3-bestiary/3-02/eloises-ghost-3-4.json
  packs/pfs-season-4-bestiary/4-99/recon-scout.json
  packs/pfs-season-5-bestiary/5-11/287s-powerful-ghost.json
  packs/pfs-season-6-bestiary/6-13/spirit-hound.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/pakano-level-12.json
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/ghost.json
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/yuni.json
  packs/seven-dooms-for-sandpoint-bestiary/nualia.json
  packs/strength-of-thousands-bestiary/book-5-doorway-to-the-red-star/tollvych.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/phytomancer-ghost.json
Labels: pr: data update

#19941 Fix some inline roll options
  packs/battlecry-bestiary/angelic-chorus.json
  packs/battlecry-bestiary/arboreal-copse.json
  packs/battlecry-bestiary/druid-circle.json
  packs/battlecry-bestiary/gnome-cannon-corps.json
  packs/battlecry-bestiary/scamp-whirlwind.json
  packs/equipment/booming-bell.json
  packs/equipment/semaphore-of-slanders.json
Labels: pr: data update

#19926 Fix missing compendiumSource for some spell copies
  packs/actions/mirrored-wall.json
  packs/battlecry-bestiary/angelic-chorus.json
  packs/battlecry-bestiary/apprentice-magician-clique.json
  packs/battlecry-bestiary/archon-bastion.json
  packs/battlecry-bestiary/druid-circle.json
  packs/battlecry-bestiary/halfling-lucky-draw.json
  packs/battlecry-bestiary/leukodaemon-plague.json
  packs/battlecry-bestiary/lich-legion.json
  packs/battlecry-bestiary/mitflit-vermin-cavalry.json
  packs/battlecry-bestiary/omox-slime-pool.json
  packs/battlecry-bestiary/protean-tumult.json
  packs/battlecry-bestiary/redcap-brigade.json
  packs/battlecry-bestiary/scamp-avalanche.json
  packs/battlecry-bestiary/scamp-flood.json
  packs/battlecry-bestiary/scamp-inferno.json
  packs/battlecry-bestiary/scamp-shrapnel.json
  packs/battlecry-bestiary/scamp-tangle.json
  packs/battlecry-bestiary/scamp-whirlwind.json
  packs/battlecry-bestiary/sinswarm.json
  packs/battlecry-bestiary/vanth-guardian-flock.json
  packs/battlecry-bestiary/vordine-legion.json
  packs/equipment/fireproof-gloves-greater.json
  packs/equipment/fireproof-gloves.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/brave-wanderer.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/ruvior.json
  packs/pathfinder-bestiary-3/terra-cotta-garrison.json
  packs/pfs-season-6-bestiary/6-99/invigorated-sotroz.json
  packs/pfs-season-6-bestiary/6-99/sotroz.json
  packs/spell-effects/spell-effect-daemon-form.json
  packs/spell-effects/spell-effect-monstrosity-form.json
  packs/vehicles/pathfinder-battlecry/cooks-caravan.json
  packs/vehicles/pathfinder-battlecry/mobile-command-post.json
  packs/vehicles/pathfinder-battlecry/necro-roamer.json
  packs/vehicles/pathfinder-battlecry/siege-dragon.json
  packs/vehicles/pathfinder-battlecry/two-person-submersible.json
Labels: pr: data update

#19929 Convert `Wand of Teeming Ghosts` into magic wand equipment type
  packs/equipment/wand-of-teeming-ghosts-2nd-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-2nd-rank.json
  packs/equipment/wand-of-teeming-ghosts-3rd-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-3rd-rank.json
  packs/equipment/wand-of-teeming-ghosts-4th-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-4th-rank.json
  packs/equipment/wand-of-teeming-ghosts-5th-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-5th-rank.json
  packs/equipment/wand-of-teeming-ghosts-6th-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-6th-rank.json
  packs/equipment/wand-of-teeming-ghosts-7th-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-7th-rank.json
  packs/equipment/wand-of-teeming-ghosts-8th-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-8th-rank.json
  packs/equipment/wand-of-teeming-ghosts-9th-rank-spell.json
  packs/equipment/wand-of-teeming-ghosts-9th-rank.json
Labels: pr: data update

#19934 Update select Abomination Vaults actors
  packs/abomination-vaults-bestiary/book-1-ruins-of-gauntlight/jaul-mezmin.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/afflicted-irnakurse.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/chafkhem.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/deep-end-sarglagon.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/drill-field-barbazu.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/gibtanius.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/gibtas-bounder.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/gulzash.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/murschen.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/galudu.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/quara-orshendiel.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/voidbracken-chuul.json
  static/lang/re-en.json
Labels: pr: data update

#19972 Move `HandlebarsApplicationMixin` type to definition file
  src/module/apps/compendium-browser/loader.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/api/handlebars-application.d.mts
  types/foundry/client/applications/api/handlebars-application.mts
  types/foundry/client/applications/sheets/item-sheet.d.mts
  types/foundry/client/documents/collections/_module.d.mts
  types/foundry/client/documents/collections/compendium-collection.d.mts
  types/foundry/client/documents/scene.d.mts
  types/foundry/client/documents/token.d.mts
  types/foundry/common/utils/collection.d.mts
Labels: pr: types update

#19971 Have `PricePF2e.fromString` accept unitless numeric strings
  src/module/item/physical/coins.ts
  src/module/item/physical/schema.ts
Labels: pr: enhancement

#19962 Convert `Wand of Toxic Blades` to magic wand equipment type
  packs/equipment/wand-of-toxic-blades-6th-rank.json
  packs/equipment/wand-of-toxic-blades-7th-rank.json
  packs/equipment/wand-of-toxic-blades-8th-rank.json
Labels: pr: data update

#19976 Add automation for Relinquish Control and Instinctive Maneuvers
  packs/feat-effects/effect-blessed-counterstrike.json
  packs/feat-effects/effect-relinquish-control.json
  packs/feats/class/animist/instinctive-maneuvers.json
  packs/feats/class/animist/relinquish-control.json
Labels: pr: data update

#19978 Correct attack label and minor formatting for `Angel Form` spell effect
  packs/spell-effects/spell-effect-angel-form.json
Labels: pr: data update

#19963 Correct `Rain-Scribe`'s speed
  packs/npc-gallery/rain-scribe.json
Labels: pr: data update

#19982 Remove duplicate prompts for wellspring mage
  packs/classfeatures/wellspring-magic.json
Labels: pr: data update

#19846 Show DC for `/act` inlines with custom label
  src/module/system/text-editor.ts
Labels: pr: enhancement

#19983 Release Notes 7.4.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19985 Add missing link to Aura of Sophistry localization
  static/lang/re-en.json
Labels: pr: data update

#19994 Fix issues with Kit sheet
  src/module/item/kit/document.ts
  src/module/item/kit/sheet.ts
Labels: pr: bugfix

#20003 Correct Deity Choice Set on `Mortal Dedication` dedication feat
  packs/feats/archetype/mortal-herald/mortal-herald-dedication.json
Labels: pr: data update

#19999 Brush up Medic's Armband
  packs/equipment-effects/effect-do-no-harm.json
  packs/equipment/medics-armband-greater.json
  packs/equipment/medics-armband.json
Labels: pr: data update

#19988 Convert `Wand of Crackling Lightning` to magic wand
  packs/equipment/wand-of-crackling-lightning-3rd-rank-spell.json
  packs/equipment/wand-of-crackling-lightning-4th-rank-spell.json
  packs/equipment/wand-of-crackling-lightning-6th-rank-spell.json
  packs/equipment/wand-of-crackling-lightning-8th-rank-spell.json
Labels: pr: data update

#19984 Add missing inline saving throw links to Dread Gaze and Feral Possession
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/graem.json
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/grinlowe.json
  packs/pathfinder-bestiary-2/vrykolakas-ancient.json
  packs/pathfinder-bestiary-2/vrykolakas-master.json
  packs/pathfinder-monster-core/sea-hag.json
Labels: pr: data update

#19981 Convert `Wand of Traitorous Thoughts` and `Wand of Wearying Dance` to magic wands
  packs/equipment/wand-of-traitorous-thoughts.json
  packs/equipment/wand-of-wearying-dance.json
Labels: pr: data update

#19979 Fix Munitions Crafter allowing any ammunition to be created
  packs/feats/class/gunslinger/munitions-crafter.json
Labels: pr: data update

#19977 Fix reach distance for Cosmic Form fist Strike
  packs/spell-effects/spell-effect-cosmic-form.json
Labels: pr: data update

#20009 Release Notes 7.4.2
  .github/workflows/cd.yml
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#20019 Fix opening Elemental Blast item from PC sheet
  src/module/actor/character/elemental-blast.ts
Labels: pr: bugfix

#20028 Set `PhysicalItemPF2e#system#temporary`
  src/module/item/physical/document.ts
Labels: pr: bugfix

#20027 Add Lich Legion's Frightful Presence DC
  packs/battlecry-bestiary/lich-legion.json
Labels: pr: data update

#20029 Correct Animate Dream's spell list and resistances (Gatewalkers version)
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/animate-dream.json
Labels: pr: data update

#20042 Fix placement of document/token-movement types
  src/global.ts
  types/foundry/client/_types.d.mts
  types/foundry/client/applications/apps/combat-tracker-config.d.mts
  types/foundry/client/applications/sidebar/apps/controls-config.d.mts
  types/foundry/client/av/master.d.mts
  types/foundry/client/canvas/layers/grid.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/data/terrain-data.d.mts
  types/foundry/client/documents/_types.d.mts
  types/foundry/client/documents/scene.d.mts
  types/foundry/client/helpers/client-settings.d.mts
  types/foundry/client/helpers/interaction/client-keybindings.d.mts
  types/foundry/client/helpers/interaction/keyboard-manager.d.mts
  types/foundry/common/_types.d.mts
Labels: pr: types update

#20049 Add Commander trait to Reactive Strike
  packs/feats/class/shared-class-feats/reactive-strike.json
Labels: pr: data update

#20053 Convert Wand of the Snowfields into magic wand equipment type
  packs/equipment/wand-of-the-snowfields-5th-rank-spell.json
  packs/equipment/wand-of-the-snowfields-7th-rank-spell.json
Labels: pr: data update

#20050 Convert Wand of Smoldering Fireballs into magic wand equipment type
  packs/equipment/wand-of-smoldering-fireballs-3rd-rank-spell.json
  packs/equipment/wand-of-smoldering-fireballs-5th-rank-spell.json
  packs/equipment/wand-of-smoldering-fireballs-7th-rank-spell.json
  packs/equipment/wand-of-smoldering-fireballs-9th-rank-spell.json
Labels: pr: data update

#20047 Resolve strike damage modifier value in `BattleFormRuleElement`
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: enhancement

#20001 Add automation for Vorens' Adroit Duelist
  packs/agents-of-edgewatch-bestiary/book-4-assault-on-hunting-lodge-seven/waxworks-onslaught-trap.json
  packs/bestiary-effects/effect-dueling-dance.json
  packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/vorens.json
  static/lang/re-en.json
Labels: pr: data update

#20005 Convert some inline `line` templates to `square`, and some `burst` to `cylinder`
  packs/age-of-ashes-bestiary/book-1-hellknight-hill/town-hall-fire.json
  packs/equipment/cold-comfort-greater.json
  packs/equipment/cold-comfort-lesser.json
  packs/equipment/gravity-inverter.json
  packs/equipment/mat-of-resilience-greater.json
  packs/equipment/mat-of-resilience.json
  packs/equipment/volcanic-vigor-greater.json
  packs/equipment/volcanic-vigor.json
  packs/feats/class/kineticist/living-bonfire.json
  packs/feats/class/kineticist/usurp-the-lunar-reins.json
  packs/feats/class/kineticist/weight-of-stone.json
  packs/feats/class/shared-class-feats/eerie-proclamation.json
  packs/feats/class/shared-class-feats/holy-light.json
  packs/pfs-season-1-bestiary/1-15/raging-forest-fire.json
  packs/pfs-season-1-bestiary/1-15/smoldering-forest-fire.json
  packs/quest-for-the-frozen-flame-bestiary/book-2-lost-mammoth-valley/forest-fire.json
Labels: pr: data update

#20010 Convert Wand of Hopeless Night into magic wand
  packs/equipment/wand-of-hopeless-night-2nd-rank-spell.json
  packs/equipment/wand-of-hopeless-night-4th-rank-spell.json
Labels: pr: data update

#20015 Brush up Paskis Nine-Knives
  packs/triumph-of-the-tusk-bestiary/book-3-destroyers-doom/paskis-nine-knives.json
Labels: pr: data update

#20026 Convert Wand of Slaughter to magic wand equipment type.
  packs/equipment/wand-of-slaughter-7th-rank-spell.json
  packs/equipment/wand-of-slaughter-8th-rank-spell.json
  packs/equipment/wand-of-slaughter-9th-rank-spell.json
Labels: pr: data update

#20058 Convert additional instances of action macros into `/act` syntax and refresh feats on select Pregens
  packs/actions/avoid-notice.json
  packs/actions/pick-a-lock.json
  packs/actions/skill-actions/craft.json
  packs/actions/skill-actions/shove.json
  packs/actions/skill-actions/squeeze.json
  packs/age-of-ashes-bestiary/book-1-hellknight-hill/grauladon.json
  packs/age-of-ashes-bestiary/book-5-against-the-scarlet-triad/scarlet-triad-boss.json
  packs/agents-of-edgewatch-bestiary/book-1-devil-at-the-dreaming-palace/flying-guillotine.json
  packs/agents-of-edgewatch-bestiary/book-1-devil-at-the-dreaming-palace/summoning-rune-barbazu-devil.json
  packs/agents-of-edgewatch-bestiary/book-1-devil-at-the-dreaming-palace/summoning-rune-cinder-rat.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/shimmernewt.json
  packs/extinction-curse-bestiary/book-1-the-show-must-go-on/vermlek.json
  packs/fall-of-plaguestone/the-amalgam.json
  packs/feats/class/inventor/tamper.json
  packs/feats/class/rogue/sly-disarm.json
  packs/iconics/amiri-level-1.json
  packs/iconics/amiri-level-3.json
  packs/iconics/amiri-level-5.json
  packs/iconics/jirelle-level-1.json
  packs/iconics/jirelle-level-3.json
  packs/iconics/jirelle-level-5.json
  packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
  packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
  packs/kingmaker-bestiary/phantasmal-protagonist.json
  packs/kingmaker-bestiary/valerie-level-9.json
  packs/paizo-pregens/dinner-at-lionlodge/takemiru.json
  packs/paizo-pregens/little-trouble-in-big-absalom/grimmnir.json
  packs/paizo-pregens/the-slithering/zathri.json
  packs/pathfinder-bestiary-2/doprillu.json
  packs/pathfinder-bestiary-2/jabberwock.json
  packs/pathfinder-bestiary/bronze-dragon-ancient.json
  packs/pathfinder-bestiary/uthul.json
  packs/pfs-season-2-bestiary/2-13/mechanical-jaws-1-2.json
  packs/pfs-season-2-bestiary/2-13/mechanical-jaws-3-4.json
  packs/pfs-season-4-bestiary/4-99/festering-vermlek.json
  packs/pfs-season-4-bestiary/4-99/veteran-vermlek.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/sickened-doprillu.json
  static/lang/en.json
Labels: pr: data update

#20056 Convert Wand of the Spider into magic wand equipment type
  packs/equipment/wand-of-the-spider-2nd-rank-spell.json
  packs/equipment/wand-of-the-spider-4th-rank-spell.json
Labels: pr: data update

#20063 Release Notes 7.4.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#20069 Correct typos on select PFS Season 7 actors
  packs/pfs-season-7-bestiary/7-01/bubbling-pile-of-orts.json
  packs/pfs-season-7-bestiary/7-01/in-a-pickle.json
  packs/pfs-season-7-bestiary/7-01/in-a-right-pickle.json
  packs/pfs-season-7-bestiary/7-01/pile-of-orts.json
Labels: pr: data update

#20066 Priorize array fields for arrays when failing validation in DataUnionField
  src/module/system/schema-data-fields.ts
Labels: pr: enhancement

#20074 Prefer `PointerEnter` over `MouseEvent`
  src/module/actor/character/sheet.ts
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/creature/spell-preparation-sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/popups/manage-attack-proficiencies.ts
  src/module/apps/compendium-browser/components/app.svelte
  src/module/apps/item-attacher.ts
  src/module/apps/pick-a-thing-prompt.ts
  src/module/canvas/status-effects.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/cards.ts
  src/module/item/kit/sheet.ts
  src/module/item/melee/document.ts
  src/module/item/spell/document.ts
  src/module/rules/rule-element/choice-set/prompt.ts
  src/module/sheet/helpers.ts
  src/module/system/action-macros/crafting/repair.ts
  src/module/system/rolls.ts
  src/module/system/statistic/statistic.ts
  src/scripts/dice.ts
  src/scripts/ui/inline-roll-links.ts
  types/foundry/client/applications/html-secret.d.mts
  types/foundry/client/applications/ux/context-menu.d.mts
  types/foundry/client/applications/ux/html-secret.d.mts
  types/foundry/client/applications/ux/text-editor.d.mts
  types/foundry/client/appv1/api/application-v1.d.mts
  types/foundry/client/appv1/api/dialog-v1.d.mts
  types/foundry/client/appv1/sheets/journal-sheet.d.mts
  types/foundry/client/canvas/board.d.mts
  types/foundry/common/prosemirror/dropdown.d.mts
  types/foundry/common/prosemirror/menu.d.mts
Labels: pr: refactor, pr: types update

#20082 Fix `onApplyActiveEffects` RE phase from executing twice on armies
  src/module/actor/army/document.ts
Labels: pr: bugfix

#20086 Fix return type of `ApplicationV2#_onFirstRender`
  src/module/actor/character/apps/formula-picker/app.ts
  src/module/apps/compendium-browser/browser.ts
  types/foundry/client/applications/api/application.d.mts
Labels: pr: types update

#20085 Show distance instead of cost in drag measurement waypoint labels
  src/module/canvas/token/ruler.ts
  src/scripts/hooks/load.ts
  static/templates/scene/token/waypoint-label.hbs
  types/foundry/client/_types.d.mts
  types/foundry/client/canvas/placeables/tokens/base-ruler.d.mts
  types/foundry/client/canvas/placeables/tokens/ruler.d.mts
  types/foundry/client/config.d.mts
Labels: pr: enhancement

#20088 Set scale for drag-measurement waypoint labels to counter `HeadsUpDisplayContainer`'s
  src/module/canvas/token/ruler.ts
  src/scripts/hooks/canvas-ready.ts
  src/styles/canvas/_index.scss
  src/styles/canvas/token/_index.scss
  src/styles/canvas/token/_ruler.scss
  src/styles/main.scss
  types/foundry/client/canvas/placeables/tokens/ruler.d.mts
Labels: pr: enhancement

#20087 Make attack toggles (versatile, etc.) wrap
  src/styles/actor/character/_actions.scss
  static/templates/actors/character/partials/elemental-blast.hbs
  static/templates/actors/character/partials/strike.hbs
Labels: ui/ux

#20084 Correct Crime Kingpin's Sneak Attack damage dice total
  packs/pathfinder-npc-core/criminal/crime-kingpin.json
Labels: pr: data update
