Repository foundryvtt/pf2e, pull requests merged in 2025-09, with the labels that each got.

#20073 Unify handling of battle-form omission of some REs
  src/module/actor/character/data.ts
  src/module/actor/character/document.ts
  src/module/canvas/layer/token.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/battle-form/values.ts
  src/module/rules/rule-element/damage-dice.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/roll-note.ts
Labels: pr: bugfix

#20094 Update `Color` types
  types/foundry/common/utils/color.d.mts
Labels: pr: types update

#20089 Limit Damage Alterations on psychic conscious mind to base damage
  packs/classfeatures/the-distant-grasp.json
  packs/classfeatures/the-oscillating-wave.json
  packs/classfeatures/the-silent-whisper.json
Labels: pr: data update

#20099 Pass along `options` in `CharacterPF2e#getStatistic`
  src/module/actor/character/document.ts
Labels: pr: bugfix

#20070 Add support for resolvable value traits
  src/module/rules/rule-element/item-alteration/handlers.ts
  src/module/system/schema-data-fields.ts
Labels: pr: enhancement

#20100 Avoid rendering action glyphs on waypoints with zero cost
  src/module/canvas/token/ruler.ts
Labels: pr: bugfix

#20102 Fix reported value of roll-option toggle macros
  src/module/rules/rule-element/roll-option/rule-element.ts
Labels: pr: bugfix

#20107 Limit Crunch to only upgrade jaws base damage dice faces
  packs/feats/ancestry/gnoll/crunch.json
Labels: pr: data update

#20109 Add Dawn of the Frogs content and create Standalone Adventures compendium
  packs/standalone-adventures/_folders.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-1-mystery-at-the-old-mill/swamp-beetle.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-1-mystery-at-the-old-mill/young-monitor-lizard.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-2-swamp-stalkers/giant-swamp-fly.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-2-swamp-stalkers/leather-cap.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-2-swamp-stalkers/two-tusk.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-3-a-dirge-for-dunmire/boggard-guard.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-3-a-dirge-for-dunmire/hidden-crossbow-trap.json
  packs/standalone-adventures/dawn-of-the-frogs/adventure-3-a-dirge-for-dunmire/zungur.json
  static/system.json
Labels: pr: data entry

#20116 Correct upstream ruler measurement of tiny-token movement
  src/module/canvas/token/object.ts
  src/module/canvas/token/ruler.ts
  src/module/scene/token-document/document.ts
  src/styles/canvas/token/_ruler.scss
Labels: pr: bugfix

#20120 Make text shadow of drag measurement action glyphs slightly more pronounced
  src/styles/canvas/token/_ruler.scss
Labels: ui/ux

#20119 Rename Standalone Adventures compendium to Dawn of the Frogs
  packs/standalone-adventures/_folders.json
  packs/standalone-adventures/adventure-1-mystery-at-the-old-mill/swamp-beetle.json
  packs/standalone-adventures/adventure-1-mystery-at-the-old-mill/young-monitor-lizard.json
  packs/standalone-adventures/adventure-2-swamp-stalkers/giant-swamp-fly.json
  packs/standalone-adventures/adventure-2-swamp-stalkers/leather-cap.json
  packs/standalone-adventures/adventure-2-swamp-stalkers/two-tusk.json
  packs/standalone-adventures/adventure-3-a-dirge-for-dunmire/boggard-guard.json
  packs/standalone-adventures/adventure-3-a-dirge-for-dunmire/hidden-crossbow-trap.json
  packs/standalone-adventures/adventure-3-a-dirge-for-dunmire/zungur.json
  static/system.json
Labels: pr: data update

#20118 Restrict ruler measurement increments to whole grid-square lengths
  src/module/canvas/index.ts
  src/module/canvas/ruler.ts
  src/scripts/hooks/load.ts
  types/foundry/client/canvas/interaction/ruler/base-ruler.d.mts
  types/foundry/common/grid/square.d.mts
  types/foundry/common/primitives/array.d.mts
  types/foundry/common/utils/helpers.d.mts
Labels: pr: enhancement

#20078 Add Magic Immunity automation to select Will-o-Wisp actors
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/dread-wisp.json
  packs/agents-of-edgewatch-bestiary/book-4-assault-on-hunting-lodge-seven/gloaming-will-o-wisp.json
  packs/kingmaker-bestiary/ancient-wisp.json
  packs/pathfinder-monster-core/will-o-wisp.json
  static/lang/re-en.json
Labels: pr: data update

#20127 Update Maneuver in Flight description to remaster
  packs/actions/skill-actions/maneuver-in-flight.json
Labels: pr: data update

#20128 Change distance text into waypoint-style label
  src/module/canvas/token/object.ts
  src/module/canvas/token/ruler.ts
  src/scripts/hooks/canvas-ready.ts
  src/styles/canvas/token/_ruler.scss
  src/util/dom.ts
Labels: ui/ux

#20133 Fix pricing of armor improvements
  src/module/item/physical/helpers.ts
Labels: pr: bugfix

#20138 Fix sourcing of cost for waypoint labels
  src/module/canvas/token/ruler.ts
Labels: pr: bugfix

#20144 Pull some minor fixes and types updates from terrain-bumps PR
  src/module/canvas/layer/token.ts
  src/module/canvas/token/ruler.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/_types.d.mts
  types/foundry/client/applications/ui/hotbar.d.mts
  types/foundry/client/canvas/geometry/shapes/ray.d.mts
  types/foundry/client/canvas/placeables/token.d.mts
  types/foundry/common/constants.d.mts
  types/foundry/common/grid/_types.d.mts
  types/foundry/common/grid/base.d.mts
  types/foundry/common/grid/gridless.d.mts
  types/foundry/common/grid/hexagonal.d.mts
  types/foundry/common/grid/square.d.mts
Labels: pr: types update

#20148 Revert "Fix filtering `SpellcastingEntry`s in `Actor#prepareData`"
  src/module/actor/base.ts
  src/module/item/spellcasting-entry/document.ts
Labels: pr: bugfix

#20151 Fix Runic Body and Runic Weapon not working in ABP
  packs/spell-effects/spell-effect-protective-wards.json
  packs/spell-effects/spell-effect-runic-body.json
  packs/spell-effects/spell-effect-runic-weapon.json
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/handlers.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: bugfix

#20177 Add "travel" token-movement action
  src/module/canvas/token/ruler.ts
  src/module/scene/token-document/document.ts
  src/scripts/hooks/load.ts
  static/lang/en.json
Labels: pr: enhancement

#20183 Update types to include user query feature
  types/foundry/client/applications/api/dialog.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/data/region-behaviors/teleport-token.d.mts
  types/foundry/client/utils/helpers.d.mts
  types/foundry/common/documents/_module.d.mts
Labels: pr: types update

#20170 Correct errors in Heraldic Proclamation rule elements
  packs/feats/archetype/mortal-herald/heraldic-proclamation.json
  packs/feats/archetype/mortal-herald/marked-for-rebuke.json
  static/lang/re-en.json
Labels: pr: data update

#20182 Add deception to selectors for Tallusian's Rubble ability
  packs/claws-of-the-tyrant-bestiary/2-ashes-for-ozem/tallusian.json
  static/lang/re-en.json
Labels: pr: data update

#20190 Move hot reload initialization to separate static method
  src/scripts/hooks/load.ts
Labels: pr: refactor

#20191 Make `foundryApp` property optional in `SvelteApplicationRenderContext
  src/module/apps/compendium-browser/browser.ts
  src/module/apps/compendium-browser/tabs/base.svelte.ts
  src/module/apps/sidebar/compendium-directory.ts
  src/module/canvas/token/movement/terrain-data.ts
  src/module/sheet/mixin.svelte.ts
  types/foundry/client/applications/_module.d.mts
  types/foundry/client/applications/api/application.d.mts
Labels: pr: refactor

#20195 Update `ApplicationRenderContext` type, fix AppV2 API conflicts with `UserConfigPF2e`
  src/module/apps/effects-panel.ts
  src/module/apps/pick-a-thing-prompt.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/apps/world-clock/app.ts
  src/module/item/condition/persistent-damage-editor.ts
  src/module/system/settings/world-clock.ts
  src/module/user/sheet.ts
  static/templates/user/sheet.hbs
  types/foundry/client/applications/_types.d.mts
Labels: pr: bugfix, pr: types update

#20205 Fix name of Ancestor Statue
  packs/sky-kings-tomb-bestiary/book-1-mantle-of-gold/ancestor-statue.json
Labels: pr: data update

#20204 Fix acuity of Bloodsense feat
  packs/feats/general/bloodsense.json
Labels: pr: data update

#20217 Add cursebound condition to en.json
  static/lang/en.json
Labels: pr: data update

#20218 Move insertion of token-distance label to "renderHeadsUpDisplayContainer" hook
  src/module/canvas/layer/token.ts
  src/module/canvas/token/object.ts
  src/scripts/hooks/canvas-ready.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-hud-container.ts
  types/foundry/client/applications/apps/combat-tracker-config.d.mts
  types/foundry/client/applications/hud/placeable-hud.d.mts
  types/foundry/client/applications/hud/token-hud.d.mts
Labels: pr: bugfix

#20189 Add vidya-game trade window
  src/module/actor/army/sheet.ts
  src/module/actor/character/sheet.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/helpers.ts
  src/module/actor/inventory/index.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/actor/party/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/popups/item-transfer-dialog.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/apps/trade-dialog/app.svelte
  src/module/apps/trade-dialog/app.ts
  src/module/canvas/drop-canvas-data.ts
  src/module/item/base/sheet/sheet.ts
  src/module/rules/rule-element/choice-set/prompt.ts
  src/module/user/document.ts
  src/scripts/hooks/drop-canvas-data.ts
  src/scripts/hooks/load.ts
  src/scripts/system/dragstart-handler.ts
  src/styles/actor/_item-transfer-dialog.scss
  static/lang/en.json
  static/templates/popups/item-transfer-dialog.hbs
  types/foundry/client/helpers/hooks.d.mts
  types/foundry/client/helpers/interaction/keyboard-manager.d.mts
Labels: pr: enhancement

#20215 Add Jotunborn journal entry
  packs/journals/ancestries.json
Labels: pr: data update

#20233 Use prose-mirror editor in loot sheet, leverage `{{formInput}}` HBS helper
  src/module/actor/loot/data.ts
  src/module/actor/loot/sheet.ts
  src/module/system/text-editor.ts
  src/styles/actor/loot/_index.scss
  static/templates/actors/loot/sheet.hbs
  static/templates/actors/loot/sidebar.hbs
Labels: pr: enhancement

#20232 Move actor subtypes with data models to system.json, declare html fields
  src/module/actor/army/data.ts
  src/module/actor/hazard/data.ts
  src/module/actor/loot/data.ts
  src/module/actor/party/data.ts
  src/module/actor/vehicle/data.ts
  static/system.json
  static/template.json
Labels: pr: housekeeping

#20235 Brush up Siktemporas
  packs/bestiary-effects/effect-scream-of-despair.json
  packs/bestiary-effects/effect-winning-smile.json
  packs/curtain-call-bestiary/book-1-stage-fright/anguish-siktempora.json
  packs/pathfinder-bestiary-3/hatred-siktempora.json
  packs/pathfinder-bestiary-3/love-siktempora.json
  packs/pathfinder-bestiary-3/misery-siktempora.json
  packs/pathfinder-bestiary-3/triumph-siktempora.json
Labels: pr: data update

#20237 Add Sense Motive bonus to Conspirator Dragon actors
  packs/pathfinder-monster-core/conspirator-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-adult.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient.json
  packs/pathfinder-monster-core/conspirator-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-young.json
Labels: pr: data update

#20234 Fix the DCs of coven spells for legacy hags
  packs/pathfinder-bestiary-3/blood-hag.json
  packs/pathfinder-bestiary-3/moon-hag.json
  packs/pathfinder-bestiary-3/storm-hag.json
  packs/pathfinder-bestiary-3/winter-hag.json
  packs/pathfinder-bestiary/night-hag.json
Labels: pr: data update

#20239 Restore roll option added for each speed a creature has
  src/module/actor/creature/document.ts
  src/module/rules/rule-element/base-speed.ts
Labels: pr: bugfix

#20238 Add client setting to control whether and when token distances are displayed
  src/global.ts
  src/module/canvas/token/object.ts
  src/module/system/settings/index.ts
  src/scripts/set-game-pf2e.ts
  static/lang/en.json
Labels: pr: enhancement

#20241 Preload FA Duotone font
  src/scripts/hooks/ready.ts
Labels: pr: enhancement

#20244 Guard against Firefox's partially-implemented `IteratorObject`s when preloading fonts
  src/scripts/hooks/ready.ts
Labels: pr: bugfix

#20246 Ensure trade is properly aborted on receiver's end when declining request
  src/module/apps/trade-dialog/app.ts
Labels: pr: bugfix

#20247 Avoid premature destruction of `Sortable` objects when dropping elements on canvas
  src/module/actor/creature/sheet.ts
  src/module/actor/sheet/base.ts
  src/module/apps/trade-dialog/app.ts
  src/util/destroyables.ts
Labels: pr: bugfix

#20249 Include speed `type` in `otherSpeeds` deprecation path
  src/module/actor/creature/document.ts
Labels: pr: bugfix

#20253 Fix typo in select element of loot sheet
  static/templates/actors/loot/sheet.hbs
Labels: pr: bugfix

#20254 Show action cost in label of final planned waypoint
  src/module/canvas/token/ruler.ts
  src/styles/canvas/token/_ruler.scss
  types/foundry/client/canvas/placeables/tokens/ruler.d.mts
Labels: pr: enhancement, ui/ux

#20257 Release Notes 7.5.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#20263 Fix the extra precision damage of the item Mantis Embrace's Crushing Embrace
  packs/equipment/mantis-embrace.json
Labels: pr: data update

#20270 Fix most issues with calculation of derived speeds
  src/module/actor/character/document.ts
  src/module/actor/character/helpers.ts
  src/module/actor/creature/document.ts
  src/module/rules/rule-element/base-speed.ts
  src/module/system/statistic/speed.ts
  static/lang/en.json
Labels: pr: bugfix

#20271 Ignore check/speed penalties from battle forms via modifier adjustments
  src/module/rules/rule-element/battle-form/rule-element.ts
Labels: pr: bugfix

#20274 Include distance roll options in roll-context actor clones
  src/module/actor/roll-context/base.ts
Labels: pr: enhancement

#20275 Fix extraction of adjustments of non-synthetic speed modifiers
  src/module/actor/creature/document.ts
  src/module/system/statistic/speed.ts
Labels: pr: bugfix

#20276 Link action to Reset World Time button in World Clock settings
  src/module/system/settings/world-clock.ts
  static/templates/system/settings/world-clock/confirm-reset.hbs
Labels: pr: bugfix

#20281 Don't load packs with lower than LIMITED ownership for compendium browser
  src/module/apps/compendium-browser/browser.ts
Labels: pr: bugfix

#20286 Avoid some issues from too-closely managing hover distance line
  src/module/canvas/layer/token.ts
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#20278 Limit AE purges during migrations
  src/module/migration/runner/index.ts
Labels: pr: bugfix

#20288 Fix filtering of some disabled sources in the Compendium Browser
  src/module/apps/compendium-browser/loader.ts
Labels: pr: bugfix

#20291 Correct Choir Politic Patron Skill to Society
  packs/classfeatures/choir-politic.json
Labels: pr: data update

#20294 Guard against modules assigning frozen point objects to `RulerPF2e#path`
  src/module/canvas/ruler.ts
Labels: pr: refactor

#20304 Automate Officer's Education
  packs/feats/class/commander/officers-education.json
Labels: pr: data update

#20298 Fix some missing NPC `compendiumSource`
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/blue-viper-level-20.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/gumiho.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/shino-hakusa-level-20.json
  packs/lost-omens-bestiary/shining-kingdoms/bibliodaemon.json
  packs/lost-omens-bestiary/shining-kingdoms/lamp-blighter.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/skeletal-champion.json
  packs/myth-speaker-bestiary/book-3-titanbane/painted-soldier.json
  packs/pfs-season-6-bestiary/6-03/captain-pitros-nanaeil.json
  packs/pfs-season-6-bestiary/6-03/pure-legionnaire.json
  packs/pfs-season-6-bestiary/6-03/resolved-captain-pitros-nanaeil.json
  packs/pfs-season-6-bestiary/6-03/veteran-pure-legionnaire.json
  packs/pfs-season-6-bestiary/6-18/master-bodyguard.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-captain.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-novice.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-trainee.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-veteran.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple.json
  packs/pfs-season-6-bestiary/6-99/empowered-rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/enraged-rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/ghoul-commando.json
  packs/pfs-season-6-bestiary/6-99/rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/tired-dockhand.json
  packs/pfs-season-7-bestiary/7-02/athamaru-pirate.json
  packs/standalone-adventures/adventure-3-a-dirge-for-dunmire/boggard-guard.json
  packs/standalone-adventures/adventure-3-a-dirge-for-dunmire/zungur.json
Labels: pr: data update

#20300 Add automation and inline scaling damage to Blazing Spirit
  packs/feats/class/animist/blazing-spirit.json
Labels: pr: data update

#20319 Update Settlement Scholastics to Player Core 2
  packs/feats/archetype/archaeologist/settlement-scholastics.json
  packs/feats/class/commander/officers-education.json
Labels: pr: data update

#20325 Add frequency to select Monster Core dragon actors
  packs/pathfinder-monster-core/mirage-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/mirage-dragon-adult.json
  packs/pathfinder-monster-core/mirage-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/mirage-dragon-ancient.json
  packs/pathfinder-monster-core/omen-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-adult.json
  packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-ancient.json
Labels: pr: data update

#20316 Fix primal sink
  packs/bestiary-effects/effect-primal-sink.json
Labels: pr: data update

#20321 Add inline action macros to Scholastic Identification
  packs/feats/archetype/archaeologist/archaeologists-luck.json
  packs/feats/archetype/archaeologist/scholastic-identification.json
Labels: pr: data update

#20329 Treat advanced bows and crossbows as martial weapons with Archer Dedication
  packs/feats/archetype/archer/archer-dedication.json
Labels: pr: data update

#20330 Update Dhalavei 1st rank granted spell per Divine Mysteries web supplement
  packs/deities/vudrani-gods/dhalavei.json
Labels: pr: data update

#20324 Release Notes 7.5.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#20334 Fix Plunderer of the Hive's Riches description in re-en.json
  static/lang/re-en.json
Labels: pr: data update

#20307 Append Will save to mindshifted feats
  packs/feats/class/psychic/cranial-detonation.json
  packs/feats/class/psychic/dark-personas-presence.json
  packs/feats/class/psychic/psi-burst.json
  packs/feats/class/psychic/psi-catastrophe.json
  packs/feats/class/psychic/violent-unleash.json
  static/lang/re-en.json
Labels: pr: data update

#20310 Add note to Mythic Casting regarding PFS 6-09's allowance for kineticist impulses
  packs/feats/mythic/mythic-casting.json
Labels: pr: data update

#20311 Allow Raise Haft's parry trait granting to work with any weapon held in 2 hands
  packs/feats/class/guardian/raise-haft.json
Labels: pr: data update

#20313 Rename Battle Harbinger's Divine Font to Battle Font
  packs/classfeatures/battle-creed.json
  static/lang/re-en.json
Labels: pr: data update

#20314 Lower priority of Celestial Armaments' Token Light
  packs/feat-effects/effect-celestial-armaments.json
Labels: pr: data update

#20315 Remove acid damage and automate temporary Hit Points effect from Untwisting Iron Buffer
  packs/spell-effects/spell-effect-untwisting-iron-augmentation.json
  packs/spell-effects/spell-effect-untwisting-iron-buffer.json
  packs/spells/focus/untwisting-iron-buffer.json
Labels: pr: data update

#20332 Update rule elements and formatting on Goloma ancestry feats and heritages
  packs/feats/ancestry/goloma/ambush-awareness.json
  packs/feats/ancestry/goloma/goloma-courage.json
  packs/feats/ancestry/goloma/protective-claws.json
  packs/feats/ancestry/goloma/see-the-unseen.json
  packs/feats/ancestry/goloma/true-gaze.json
  packs/heritages/goloma/insightful-goloma.json
  packs/heritages/goloma/vicious-goloma.json
Labels: pr: data update

#20327 Fix some missing pregen `compendiumSource`
  packs/equipment-effects/effect-clay-sphere-weapon-damage-increase.json
  packs/iconics/grimmyr-level-1.json
  packs/iconics/grimmyr-level-3.json
  packs/iconics/grimmyr-level-5.json
  packs/iconics/korakai-level-1.json
  packs/iconics/korakai-level-3.json
  packs/iconics/korakai-level-5.json
  packs/iconics/quinn-level-1.json
  packs/iconics/quinn-level-3.json
  packs/iconics/quinn-level-5.json
  packs/iconics/seelah-level-3.json
  packs/iconics/ulka-level-1.json
  packs/iconics/ulka-level-3.json
  packs/iconics/ulka-level-5.json
  packs/paizo-pregens/dinner-at-lionlodge/takemiru.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/brave-wanderer.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/kiana.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/ruvior.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/sizkmi.json
Labels: pr: data update

#20320 Add Divine Warden of Brigh from Paizo Blog
  packs/battlecry-bestiary/clockwork-infantry.json
  packs/battlecry-bestiary/clockwork-runner-pack.json
  packs/bestiary-family-ability-glossary/clockwork-creature/clockwork-creature-wind-up.json
  packs/blog-bestiary/divine-warden-of-brigh.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/clockwork-corpse.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/clockwork-sentry.json
  packs/vehicles/pathfinder-battlecry/backpack-balloon.json
  packs/vehicles/pathfinder-battlecry/caisson.json
Labels: pr: data entry, pr: data update, source: blog

#20335 Add content from the RotRL Player's Guide
  packs/actions/hunt-runelord.json
  packs/backgrounds/_folders.json
  packs/backgrounds/adventure-paths/revenge-of-the-runelords/distant-traveler.json
  packs/backgrounds/adventure-paths/revenge-of-the-runelords/escaped-from-time.json
  packs/backgrounds/adventure-paths/revenge-of-the-runelords/heroic-ancestry.json
  packs/backgrounds/adventure-paths/revenge-of-the-runelords/local-savior.json
  packs/backgrounds/adventure-paths/revenge-of-the-runelords/runelord-researcher.json
  packs/backgrounds/adventure-paths/revenge-of-the-runelords/runelord-survivor.json
  packs/classfeatures/_folders.json
  packs/classfeatures/curse-of-inclement-headwinds.json
  packs/classfeatures/mythic-callings/acrobats-calling.json
  packs/classfeatures/mythic-callings/artisans-calling.json
  packs/classfeatures/mythic-callings/bookkeepers-calling.json
  packs/classfeatures/mythic-callings/caretakers-calling.json
  packs/classfeatures/mythic-callings/demagogues-calling.json
  packs/classfeatures/mythic-callings/guardians-calling.json
  packs/classfeatures/mythic-callings/handlers-calling.json
  packs/classfeatures/mythic-callings/hunters-calling.json
  packs/classfeatures/mythic-callings/revenge-of-the-runelords/doomsayers-calling.json
  packs/classfeatures/mythic-callings/revenge-of-the-runelords/dreamers-calling.json
  packs/classfeatures/mythic-callings/revenge-of-the-runelords/runelords-calling.json
  packs/classfeatures/mythic-callings/revenge-of-the-runelords/sagas-calling.json
  packs/classfeatures/mythic-callings/sages-calling.json
  packs/classfeatures/mythic-callings/thespians-calling.json
  packs/classfeatures/mythic-callings/thiefs-calling.json
  packs/feat-effects/effect-distant-traveler.json
  packs/feat-effects/effect-hunt-runelord.json
  packs/feat-effects/effect-runelord-researcher.json
  static/icons/features/classes/sihedron.webp
  static/lang/re-en.json
Labels: source: adventure path, pr: data entry

#20337 Update sidebar's proficiency ranks to fix localization styling regression
  src/module/scene/token-document/sheets/mixin.ts
  src/styles/actor/character/_proficiency-ranks.scss
Labels: pr: bugfix

#20342 Move `ItemType` definition to `@item/types.ts`
  build/lib/extractor.ts
  build/run-migration.ts
  src/module/actor/army/document.ts
  src/module/actor/base.ts
  src/module/actor/character/apps/abc-picker/app.ts
  src/module/actor/character/apps/formula-picker/app.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/actor/familiar/document.ts
  src/module/actor/hazard/document.ts
  src/module/actor/loot/document.ts
  src/module/actor/npc/document.ts
  src/module/actor/party/document.ts
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/types.ts
  src/module/actor/values.ts
  src/module/actor/vehicle/document.ts
  src/module/apps/compendium-browser/browser.ts
  src/module/chat-message/data.ts
  src/module/item/base/data/index.ts
  src/module/item/base/data/system.ts
  src/module/item/base/document.ts
  src/module/item/condition/data.ts
  src/module/item/helpers.ts
  src/module/item/types.ts
  src/module/item/values.ts
  src/module/rules/rule-element/choice-set/data.ts
  src/module/rules/rule-element/item-alteration/handlers.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: types update

#20347 Fix the description of orator's filibuster
  packs/feats/archetype/field-propagandist/level-8/orators-filibuster.json
Labels: pr: data update

#20277 Convert variant-rules settings menu to `ApplicationV2`
  src/module/system/settings/index.ts
  src/module/system/settings/variant-rules.ts
  src/module/system/settings/world-clock.ts
  src/styles/settings/_variant-rules.scss
  static/lang/en.json
  static/templates/system/settings/variant-rules.hbs
  types/foundry/client/applications/_types.d.mts
  types/foundry/common/data/fields.d.mts
Labels: pr: enhancement

#20297 Add support for automatic generation of RE forms
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/base-speed.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/damage-alteration/rule-element.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/dexterity-modifier-cap.ts
  src/module/rules/rule-element/flat-modifier.ts
  src/module/rules/rule-element/multiple-attack-penalty.ts
  src/module/rules/rule-element/roll-option/data.ts
  src/module/rules/rule-element/roll-option/rule-element.ts
  src/module/rules/rule-element/substitute-roll.ts
  src/module/rules/rule-element/token-mark/rule-element.ts
  src/module/rules/rule-element/token-name.ts
  src/module/system/schema-data-fields.ts
  src/scripts/hooks/i18n-init.ts
  src/styles/item/_rules.scss
  static/lang/re-en.json
  static/templates/items/rules/default.hbs
  static/templates/items/rules/partials/outer.hbs
  types/foundry/client/applications/forms/fields.d.mts
  types/foundry/client/helpers/localization.d.mts
  types/foundry/common/abstract/data.d.mts
  types/foundry/common/abstract/document.d.mts
  types/foundry/common/data/_types.d.mts
  types/foundry/common/data/fields.d.mts
Labels: pr: enhancement

#20352 Make `StringField` variant-rules settings required
  src/module/system/settings/variant-rules.ts
Labels: pr: bugfix

#20357 Fix some hidden inputs not being JSON-deserializable in autogenerated RE forms
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/rules/rule-element/base.ts
  src/module/rules/rule-element/damage-alteration/rule-element.ts
  src/module/rules/rule-element/data.ts
Labels: pr: bugfix

#20360 Upgrade Snare DCs to class DC with Snarecrafter Dedication and Powerful Snares
  packs/feats/archetype/guerrilla/level-4/snare-expert.json
  packs/feats/archetype/snarecrafter/snarecrafter-dedication.json
  packs/feats/class/ranger/powerful-snares.json
Labels: pr: data update

#20351 Fix the automation of Effect:Augmented Body
  packs/spell-effects/spell-effect-augmented-body.json
Labels: pr: data update

#20362 Check that consumable is owned before accessing `#embeddedSpell`
  src/module/item/consumable/sheet.ts
Labels: pr: bugfix

#20361 Correct resistance granted by Inked Panoply
  packs/feat-effects/effect-infused-with-belkzens-might.json
  packs/feats/archetype/loremaster/loremaster-dedication.json
  packs/feats/archetype/loremaster/orthographic-mastery.json
  packs/feats/archetype/tattooed-historian/inked-panoply.json
  packs/journals/archetypes.json
Labels: pr: data update

#20365 Add support for configuring npc attacks as area/auto fire
  src/module/item/melee/data.ts
  src/module/item/melee/sheet.ts
  src/module/item/melee/types.ts
  src/module/item/melee/values.ts
  static/lang/action-en.json
  static/lang/en.json
  static/templates/items/melee-details.hbs
Labels: pr: enhancement
