Repository foundryvtt/pf2e, pull requests merged in 2025-02, with the labels that each got.

#18167 Fix few area-effect checks
  packs/kingmaker-bestiary/armies/troll-marauders.json
  packs/kingmaker-bestiary/lintwerth.json
  packs/kingmaker-bestiary/minognos-ushad.json
  packs/kingmaker-bestiary/rezatha.json
  packs/pathfinder-bestiary-2/ice-mephit.json
Labels: pr: data update

#18173 Use source values when computing kingdom army levelups
  src/module/actor/army/document.ts
Labels: pr: bugfix, kingmaker

#18178 Resolve item alteration id for singleItem and additionalItems
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: bugfix

#18175 Update predicate for Daydream Trance
  packs/feat-effects/effect-daydream-trance.json
Labels: pr: data update

#18182 Correct rarity tag on Grub Gloves
  packs/equipment/grub-gloves-greater.json
  packs/equipment/grub-gloves-lesser.json
  packs/equipment/grub-gloves-moderate.json
Labels: pr: data update

#18162 Restrict Regalia's flanking override to paragon benefit
  packs/feat-effects/effect-regalia.json
Labels: pr: data update

#18188 Add vitality weakness to Arms of the Drowned hazard
  packs/season-of-ghosts-bestiary/arms-of-the-drowned.json
Labels: pr: data update

#18189 Adjust aura for Warsworn
  packs/pathfinder-bestiary-2/ravener.json
  packs/pathfinder-monster-core/warsworn.json
Labels: pr: data update

#18198 Remove Dazzling Brilliance from variant glass golem
  packs/abomination-vaults-bestiary/nhimbaloths-cutter.json
Labels: pr: data update

#18197 Add missing prerequisite to Empiricist's Eye
  packs/feats/empiricists-eye.json
Labels: pr: data update

#18196 Apply Flowing Spirit Strike's penalty to gleaming blade only
  packs/actions/flowing-spirit-strike.json
Labels: pr: data update

#18187 Add missing details to Magus' Arcane Spellcasting class feature
  packs/classfeatures/arcane-spellcasting-magus.json
  packs/classfeatures/wizard-spellcasting.json
Labels: pr: data update

#18199 Link effect in Heroic Recovery's spellshape Item Alteration
  packs/feats/heroic-recovery.json
Labels: pr: data update

#18172 Update Aquatic Combat Effect to match Player Core and Errata changes
  packs/other-effects/effect-aquatic-combat.json
  static/lang/re-en.json
Labels: pr: data update

#18170 Update Emotionally Unaware penalty so it doesn't apply on initiative rolls
  packs/ancestryfeatures/emotionally-unaware.json
Labels: pr: data update

#18168 Add automation for Frost Fair Yanyuedao
  packs/equipment-effects/effect-dragon-chill.json
  packs/equipment/frost-fair-yanyuedao.json
  static/lang/re-en.json
Labels: pr: data update

#18148 Correct critical failure persistant damage for Whispers of the Void
  packs/spells/whispers-of-the-void.json
Labels: pr: data update

#18200 Add spell effect for Scintillating Safeguard
  packs/blood-lords-bestiary/shabti-votary.json
  packs/spell-effects/spell-effect-scintillating-safeguard.json
  packs/spells/scintillating-safeguard.json
  packs/spore-war-bestiary/alzarius.json
Labels: pr: data update

#18122 Update Crunch to use DamageAlteration
  packs/feats/crunch.json
Labels: pr: data update

#18190 Clear stack group if switching from the ammo category
  src/module/item/consumable/document.ts
Labels: pr: bugfix

#18203 Fix action cost of Darkened Forest Form and Discomfiting Whispers
  packs/spells/darkened-forest-form.json
  packs/spells/discomfiting-whispers.json
Labels: pr: data update

#18206 Add localization changes for Guns & Gears Remaster
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update, remaster

#18208 Update Reinforced Chassis physical armor to be unarmored
  packs/equipment/reinforced-chassis.json
Labels: pr: data update

#18211 Correct action cost for Fire Scamp's Flame Breath action
  packs/pathfinder-monster-core/fire-scamp.json
Labels: pr: data update

#18210 Add change shape ability to ifrit
  packs/pathfinder-monster-core/ifrit.json
Labels: pr: data update

#18215 Implement 2/25 PFS Rulings & Clarifications
  packs/actions/coughing-dragon.json
  packs/actions/jumping-jenny.json
  packs/classfeatures/studious-spells.json
  packs/equipment/book-of-lingering-blaze.json
  packs/equipment/grim-sandglass-greater.json
  packs/equipment/grim-sandglass-major.json
  packs/equipment/grim-sandglass.json
  packs/equipment/summoning-handscroll.json
  packs/feats/dual-weapon-reload.json
  packs/feats/sleek-reposition.json
  packs/heritages/surki/lantern-surki.json
  packs/journals/archetypes.json
Labels: pr: data update

#18217 Adding missing 7th rank entries to Atmospheric Staff (Major)
  packs/equipment/atmospheric-staff-greater.json
  packs/equipment/atmospheric-staff-lesser.json
  packs/equipment/atmospheric-staff-major.json
  packs/equipment/atmospheric-staff.json
Labels: pr: data update

#18213 Increase batch size of Fireworks Display with Expert Fireworks Crafter
  packs/feats/expert-fireworks-crafter.json
Labels: pr: data update

#18209 Update range increment of Advanced Rangefinder to remaster
  packs/classfeatures/advanced-rangefinder.json
Labels: pr: data update

#18220 Remove expired copies of an effect when adding a new one
  src/module/item/base/document.ts
Labels: pr: enhancement

#18218 Update Blast Resistance DoS adjustment automation
  packs/feats/blast-resistance.json
  static/lang/re-en.json
Labels: pr: data update

#18185 Add effect to Bone Flense spell
  packs/spell-effects/effect-bone-flense-damage.json
  packs/spell-effects/effect-bone-flense-reaction.json
  packs/spells/bone-flense.json
  static/lang/re-en.json
Labels: pr: data update

#18222 Update Mithral Tree to Dawnsilver Tree in localization
  static/lang/en.json
Labels: pr: data update

#18225 Update description of Razor Prongs modification
  packs/classfeatures/razor-prongs.json
Labels: pr: data update

#18180 Add some links and emphasis for harm and heal spells
  packs/agents-of-edgewatch-bestiary/clockwork-amalgam.json
  packs/blog-bestiary/lisavet.json
  packs/equipment-effects/effect-healers-gel.json
  packs/equipment/grave-token.json
  packs/equipment/healers-gel-greater.json
  packs/equipment/healers-gel-lesser.json
  packs/equipment/healers-gel-moderate.json
  packs/equipment/staff-of-healing-greater.json
  packs/equipment/staff-of-healing-major.json
  packs/equipment/staff-of-healing-true.json
  packs/equipment/staff-of-healing.json
  packs/familiar-abilities/verdant-burst.json
  packs/feat-effects/effect-curse-of-outpouring-life.json
  packs/feats/channel-smite.json
  packs/feats/leshy-familiar-secrets.json
  packs/feats/void-siphon.json
  packs/pfs-season-1-bestiary/1-03/ralthiss-1-2.json
  packs/pfs-season-1-bestiary/1-03/ralthiss-3-4.json
  packs/pfs-season-3-bestiary/3-05/uncle-jeb-3-4.json
  packs/rusthenge-bestiary/ordwi.json
  packs/seven-dooms-for-sandpoint-bestiary/abstalar-zantus.json
  packs/spell-effects/spell-effect-angelic-halo.json
  static/lang/re-en.json
Labels: pr: data update

#18240 Fix Slinger's Precision using description from Singular Expertise
  packs/classfeatures/slingers-precision.json
Labels: pr: data update

#18239 Restore missing frequency to Dance of Thunder description
  packs/feats/dance-of-thunder.json
Labels: pr: data update

#18238 Add initiative selector to Scout's Warning
  packs/feat-effects/effect-scouts-warning.json
Labels: pr: data update

#18237 Fix incorrect casting time on Trade Death for Life
  packs/spells/trade-death-for-life.json
Labels: pr: data update

#18236 Fix Inventors innovations not matching individual modification items; Fix Heavy Construction strength requirements
  packs/actions/overdrive.json
  packs/classfeatures/breakthrough-innovation.json
  packs/classfeatures/dynamic-weighting.json
  packs/classfeatures/heavy-construction.json
  packs/classfeatures/perfect-fortification.json
  packs/classfeatures/razor-prongs.json
  packs/classfeatures/revolutionary-innovation.json
  packs/classfeatures/rune-capacity.json
Labels: pr: data update

#18235 Fix a typo in the enter spirit trance action description
  packs/actions/enter-spirit-trance.json
Labels: pr: data update

#18234 Release Notes 6.9.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
  vite.config.ts.timestamp-1739057933273-a347b5142ef3c.mjs
Labels: pr: housekeeping

#18186 Add effect to Tangling Creepers spell
  packs/spell-effects/spell-effect-tangling-creepers.json
  packs/spells/tangling-creepers.json
  packs/spells/tempest-of-shades.json
Labels: pr: data update

#18248 Restrict slinger's precision damage dice to non-repeating firearms
  packs/classfeatures/slingers-precision.json
Labels: pr: data update

#18243 Improve Arcane Slam enhancement formatting
  packs/feats/arcane-slam.json
Labels: pr: data update

#18249 Remove superfluous RE from Burning Mammoth Longshield's copy of Shield Boss
  packs/quest-for-the-frozen-flame-bestiary/burning-mammoth-longshield.json
Labels: pr: data update

#18242 Add `/act` to Glue Bomb Escape DCs
  packs/equipment/glue-bomb-greater.json
  packs/equipment/glue-bomb-lesser.json
  packs/equipment/glue-bomb-major.json
  packs/equipment/glue-bomb-moderate.json
Labels: pr: data update

#18166 Fix the description of apparition's reflection feat
  packs/feats/apparitions-reflection.json
Labels: pr: data update

#18252 Include "Black Powder (Dose)" in Munitions Crafter's Crafting Ability
  packs/equipment/black-powder-dose.json
  packs/feats/munitions-crafter.json
Labels: pr: data update

#18257 Update Unstable critical failure damage to remaster
  static/lang/re-en.json
Labels: pr: data update

#18258 Condense Glue Bomb equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-glue-bomb-greater.json
  packs/equipment-effects/effect-glue-bomb-lesser.json
  packs/equipment-effects/effect-glue-bomb-major.json
  packs/equipment-effects/effect-glue-bomb-moderate.json
  packs/equipment-effects/effect-glue-bomb.json
  packs/equipment/glue-bomb-greater.json
  packs/equipment/glue-bomb-lesser.json
  packs/equipment/glue-bomb-major.json
  packs/equipment/glue-bomb-moderate.json
  packs/pfs-season-1-bestiary/1-06/pine-brute.json
  packs/prey-for-death-bestiary/shirota.json
  packs/seven-dooms-for-sandpoint-bestiary/tunch.json
Labels: pr: data update

#18259 Apply description alterations to select Ranger feats
  packs/feats/animal-companion-ranger.json
  packs/feats/masterful-companion.json
  packs/feats/shared-prey.json
  packs/feats/triple-threat.json
Labels: pr: data update

#18260 Remove inline damage from Needle of Vengeance
  packs/spells/needle-of-vengeance.json
Labels: pr: data update

#18263 Add class predicate to Oracle Ashes mystery
  packs/classfeatures/ashes.json
Labels: pr: data update

#18264 Add class predicate to Oracle Time mystery
  packs/classfeatures/time.json
Labels: pr: data update

#18266 Fix vampire mastermind's dominate ability
  packs/pathfinder-monster-core/vampire-mastermind.json
Labels: pr: data update

#18265 Fix some BattleForm ranged attack increments
  packs/spell-effects/spell-effect-devil-form-erinys.json
  packs/spell-effects/spell-effect-devil-form-osyluth.json
  packs/spell-effects/spell-effect-insect-form-spider.json
Labels: pr: data update

#18268 Apply damage alterations to elemental-blast damage
  src/module/actor/character/elemental-blast.ts
  src/module/item/spell/document.ts
  src/module/system/damage/helpers.ts
  src/module/system/damage/weapon.ts
Labels: pr: bugfix

#18273 Remove reference to array in `map` callback
  src/module/item/spell/document.ts
Labels: pr: bugfix

#18276 Fix spell dc data of Dewey Daystar
  packs/outlaws-of-alkenstar-bestiary/dewey-daystar.json
Labels: pr: data update

#18271 Automate Improved Elemental Blast
  packs/actions/elemental-blast.json
  packs/classfeatures/fire-gate.json
  packs/feats/improved-elemental-blast.json
Labels: pr: data update

#18274 Add automation to Cloud Dragon's Deflecting Cloud reaction
  packs/pathfinder-bestiary-2/cloud-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-adult.json
  packs/pathfinder-bestiary-2/cloud-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-ancient.json
  packs/pathfinder-bestiary-2/cloud-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-young.json
Labels: pr: data update

#18272 Downgrade unstable flat check DC to 13 if Crafting proficiency rank is legendary
  static/lang/re-en.json
Labels: pr: data update

#18267 Condense Frost Vial equipment effects
  packs/age-of-ashes-bestiary/ingnovim-tluss.json
  packs/age-of-ashes-bestiary/zuferian.json
  packs/agents-of-edgewatch-bestiary/amateur-chemist.json
  packs/agents-of-edgewatch-bestiary/diobel-sweeper-tough.json
  packs/blood-lords-bestiary/pesgahi-the-poisoner.json
  packs/equipment-effects/effect-frost-vial-greater.json
  packs/equipment-effects/effect-frost-vial-lesser.json
  packs/equipment-effects/effect-frost-vial-major.json
  packs/equipment-effects/effect-frost-vial-moderate.json
  packs/equipment-effects/effect-frost-vial.json
  packs/equipment/frost-vial-greater.json
  packs/equipment/frost-vial-lesser.json
  packs/equipment/frost-vial-major.json
  packs/equipment/frost-vial-moderate.json
  packs/extinction-curse-bestiary/darklands-alchemical-golem.json
  packs/extinction-curse-bestiary/thessekka.json
  packs/fall-of-plaguestone/the-sculptor.json
  packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-14.json
  packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-16.json
  packs/fists-of-the-ruby-phoenix-bestiary/blue-viper-level-20.json
  packs/iconics/fumbus-level-5.json
  packs/npc-gallery/grave-robber.json
  packs/npc-gallery/reckless-scientist.json
  packs/paizo-pregens/savshin-starwatcher.json
  packs/pathfinder-bestiary/alchemical-golem.json
  packs/pfs-season-1-bestiary/1-00/bijan-and-zaynap-ohrlavi.json
  packs/pfs-season-3-bestiary/3-99/reckless-akitonian-scientist.json
  packs/pfs-season-4-bestiary/4-99/elven-grave-robber.json
  packs/pfs-season-5-bestiary/5-14/assassins-guild-grenadier.json
  packs/seven-dooms-for-sandpoint-bestiary/aliver-pillbug-podiker.json
Labels: pr: data update

#18281 Convert 'dc' field string values to integers
  packs/agents-of-edgewatch-bestiary/baatamidar.json
  packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
  packs/agents-of-edgewatch-bestiary/blunes-illusory-toady.json
  packs/agents-of-edgewatch-bestiary/camarach.json
  packs/agents-of-edgewatch-bestiary/daemonic-infector.json
  packs/agents-of-edgewatch-bestiary/daemonic-rumormonger.json
  packs/agents-of-edgewatch-bestiary/daemonic-skinner.json
  packs/agents-of-edgewatch-bestiary/ghaele-of-kharnas.json
  packs/agents-of-edgewatch-bestiary/hundun-chaos-mage.json
  packs/agents-of-edgewatch-bestiary/overdrive-imentesh.json
  packs/agents-of-edgewatch-bestiary/sordesdaemon.json
  packs/agents-of-edgewatch-bestiary/ulressia-the-blessed.json
  packs/agents-of-edgewatch-bestiary/veksciralenix.json
  packs/outlaws-of-alkenstar-bestiary/follower-of-shumfallow.json
  packs/pfs-season-2-bestiary/2-16/burned-out-efreet.json
  packs/pfs-season-2-bestiary/2-16/corvius-vayn-5-6.json
  packs/pfs-season-2-bestiary/2-16/perizia-5-6.json
  packs/pfs-season-2-bestiary/2-16/planar-nixie.json
  packs/pfs-season-2-bestiary/2-18/vermlek-centaur-3-4.json
Labels: pr: data update

#18284 Update Frost Vials localization notes
  static/lang/re-en.json
Labels: pr: data update

#18283 Correct traits on Ripnugget's Devastating Blast ability
  packs/seven-dooms-for-sandpoint-bestiary/ripnugget.json
Labels: pr: data update

#18278 Add inline damage rolls and variants to Prismatic Spray
  packs/spells/prismatic-spray.json
Labels: pr: data update

#18291 Add effect for Umbral Dragon's Drain Vigor
  packs/bestiary-effects/effect-drain-vigor.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient.json
Labels: pr: data update

#18293 Fix malformed Promises in `processPreUpdateActorHooks` helper
  src/module/rules/helpers.ts
Labels: pr: bugfix

#18289 Fix difficult terrain size in Lesser Pernicious Spore Bomb description
  packs/equipment/pernicious-spore-bomb-lesser.json
Labels: pr: data update

#18297 Use `LaxArrayField` for traits in `FeatSystemData`
  src/module/actor/vehicle/data.ts
  src/module/item/feat/data.ts
Labels: pr: bugfix

#18296 Correct trait formatting in Declare Anathema feat
  packs/feats/declare-anathema.json
Labels: pr: data update

#18232 Omit showing effects that hide token icons from the effects panel
  src/module/apps/effects-panel.ts
Labels: pr: enhancement

#18176 Add support for disabling special resource renewal
  src/module/actor/base.ts
  src/module/rules/rule-element/special-resource.ts
  src/module/system/schema-data-fields.ts
Labels: pr: enhancement

#18301 Add some item roll options of original weapon usage to alternate usage clones
  src/module/item/base/document.ts
  src/module/item/weapon/document.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
Labels: pr: enhancement

#18302 Change some `FeatSystemData` properties back to arrays
  src/module/item/feat/data.ts
  src/module/item/feat/document.ts
  src/module/item/feat/sheet.ts
Labels: pr: bugfix

#18306 Fix processing of `system.maxTakable` property in `FeatSheetPF2e`
  src/module/item/feat/sheet.ts
Labels: pr: bugfix

#18300 Fix formatting of the kingmaker army outflank condition
  packs/kingmaker-features/army-conditions/engaged.json
  packs/kingmaker-features/army-conditions/outflanked.json
  packs/kingmaker-features/army-war-actions-tactical/outflank.json
Labels: pr: data update, kingmaker

#18307 Fix missing closing parenthesis on Zoudou
  packs/season-of-ghosts-bestiary/zoudou-the-zealous.json
Labels: pr: data update

#18308 Support sending army war actions to chat
  static/lang/kingmaker-en.json
  static/templates/actors/army/sheet.hbs
Labels: pr: enhancement, kingmaker

#18309 Fix updating army description and swap to prosemirror
  src/module/actor/army/data.ts
  src/module/actor/army/sheet.ts
  src/styles/actor/army/_index.scss
  static/templates/actors/army/sheet.hbs
Labels: pr: bugfix, kingmaker

#18310 Fix incrementing and decrementing army effects
  static/templates/actors/army/sheet.hbs
Labels: pr: bugfix, kingmaker

#18312 Set `actorLink: true` when unloading clown car
  src/module/scene/token-document/clown-car.ts
Labels: pr: bugfix

#18311 Remove remaining instances of "Open" trait, fix rarity leaking into some feat traits
  packs/blood-lords-bestiary/rival-corpsekiller.json
  packs/blood-lords-bestiary/skeleton-rival-corpsekiller.json
  packs/extinction-curse-bestiary/urdefhan-hunter.json
  packs/feats/mortal-herald-dedication.json
  packs/feats/penetrating-shot.json
  packs/feats/pivot-strike.json
  packs/feats/ravenous-charge.json
  packs/feats/seneschal-witch-dedication.json
  packs/feats/warrior-of-legend-dedication.json
  packs/kingmaker-bestiary/amiri-level-1-kingmaker.json
  packs/kingmaker-bestiary/amiri-level-11-kingmaker.json
  packs/paizo-pregens/jadren-tagar.json
  packs/paizo-pregens/kalaggi-nakutu.json
  packs/pathfinder-bestiary-2/shoggti.json
Labels: pr: data update

#18305 Add initiative note for Shift Immanence
  packs/actions/shift-immanence.json
  static/lang/re-en.json
Labels: pr: data update

#18299 Add inline check for Scare to Death's critical success Fortitude save
  packs/feats/scare-to-death.json
Labels: pr: data update

#18298 Update select Bomb Notes and Dread Ampoule Notes Rule Elements
  packs/equipment/dread-ampoule-greater.json
  packs/equipment/dread-ampoule-lesser.json
  packs/equipment/dread-ampoule-major.json
  packs/equipment/dread-ampoule-moderate.json
  packs/equipment/dwarven-daisy-lesser.json
  packs/equipment/dwarven-daisy-moderate.json
  static/lang/re-en.json
Labels: pr: data update

#18280 Remove (or add) inline checks for spells
  packs/spells/aberrant-whispers.json
  packs/spells/acid-storm.json
  packs/spells/acidic-burst.json
  packs/spells/agonizing-despair.json
  packs/spells/airburst.json
  packs/spells/anathematic-reprisal.json
  packs/spells/ancient-dust.json
  packs/spells/anima-invocation-modified.json
  packs/spells/animated-assault.json
  packs/spells/arrow-salvo.json
  packs/spells/ash-cloud.json
  packs/spells/asterism.json
  packs/spells/awaken-entropy.json
  packs/spells/awaken-portal.json
  packs/spells/beheading-buzz-saw.json
  packs/spells/black-tentacles.json
  packs/spells/blastback.json
  packs/spells/blessed-boundary.json
  packs/spells/blood-feast.json
  packs/spells/bloodspray-curse.json
  packs/spells/bone-spray.json
  packs/spells/bounty-of-the-sky.json
  packs/spells/bramble-bush.json
  packs/spells/breath-of-drought.json
  packs/spells/buffeting-winds.json
  packs/spells/burning-blossoms.json
  packs/spells/chilling-spray.json
  packs/spells/chthonian-wrath.json
  packs/spells/cone-of-cold.json
  packs/spells/consuming-darkness.json
  packs/spells/coral-eruption.json
  packs/spells/cry-of-destruction.json
  packs/spells/cyclone-rondo.json
Labels: pr: data update

#18316 Update Necklace of Knives and Druidic orders
  packs/classfeatures/flame-order.json
  packs/classfeatures/stone-order.json
  packs/classfeatures/wave-order.json
  packs/equipment/necklace-of-knives.json
Labels: pr: data update

#18253 Apply `Token Mark` to Hunt Prey action and associated feats and effects
  packs/actions/hunt-prey.json
  packs/equipment/hunters-arrowhead.json
  packs/feat-effects/effect-hunt-prey.json
  packs/feat-effects/effect-hunters-edge-flurry.json
  packs/feat-effects/effect-hunters-edge-outwit.json
  packs/feat-effects/effect-hunters-edge-precision.json
  packs/feat-effects/effect-masterful-hunters-edge-flurry.json
  packs/feat-effects/effect-masterful-hunters-edge-outwit.json
  packs/feat-effects/effect-masterful-hunters-edge-precision.json
  packs/feats/bounty-hunter-dedication.json
  packs/feats/dance-of-thunder.json
  packs/feats/game-hunter-dedication.json
  packs/feats/hamstringing-strike.json
  packs/feats/hunters-aim.json
Labels: pr: data update

#18325 Fix initial value of `VehicleSystemData#attributes#emitsSound`
  src/module/actor/vehicle/data.ts
Labels: pr: bugfix

#18326 Fix format of kneel before the rightful heir
  packs/feats/kneel-before-the-rightful-heir.json
Labels: pr: data update

#18322 Update Temporal Distortion description to match LODM
  packs/spells/temporal-distortion.json
Labels: pr: data update

#18321 Add missing "fear effects" immunity to Scarecrow actor
  packs/pathfinder-monster-core/scarecrow.json
Labels: pr: data update

#18314 Convert campaign feature to data model
  src/module/item/campaign-feature/data.ts
  src/module/item/campaign-feature/document.ts
  src/scripts/hooks/load.ts
  static/template.json
Labels: pr: refactor, kingmaker

#18332 Fix ghostshot wrapping usage
  packs/equipment/ghostshot-wrapping.json
Labels: pr: data update

#18331 Change usage for sniper's bead
  packs/equipment/snipers-bead-greater.json
  packs/equipment/snipers-bead-major.json
  packs/equipment/snipers-bead.json
Labels: pr: data update

#18337 Correct ternary syntax on Entreaty Spirit spell effect
  packs/spell-effects/spell-effect-entreat-spirit.json
Labels: pr: data update

#18338 Remove `dedication` trait from Spell-Woven Shot feat
  packs/feats/spell-woven-shot.json
Labels: pr: data update

#18333 Add missing hooded lantern interact automation
  packs/equipment/lantern-hooded.json
Labels: pr: data update

#18317 Implement Slinger's Precision's combination weapon's melee configuration proficiency
  packs/classfeatures/slingers-precision.json
Labels: pr: data update

#18341 Correct localization path for `Of Verse Unbroken` critical specialization
  packs/classfeatures/of-verse-unbroken.json
Labels: pr: data update

#18335 Include item roll options in cloned statistic used for inline `against` expressions
  src/module/system/text-editor.ts
Labels: pr: bugfix

#18342 Hide aura texture when token is GM hidden
  src/module/canvas/token/aura/renderer.ts
  src/module/canvas/token/object.ts
Labels: pr: bugfix

#18353 Fix silver tripod usage
  packs/equipment/silver-tripod.json
Labels: pr: data update

#18346 Add effect to Read Aura cantrip
  packs/spell-effects/effect-read-aura.json
  packs/spells/read-aura.json
Labels: pr: data update

#18354 Consume requested amount of ammunition when reducing quantity
  src/module/item/consumable/document.ts
Labels: pr: bugfix

#18318 Fix shadow blast saves and add damage rolls
  packs/spells/shadow-blast.json
Labels: pr: data update

#18355 Include `originalName` in ABC picker searches
  src/module/actor/character/apps/abc-picker/app.svelte
  src/module/actor/character/apps/abc-picker/app.ts
Labels: pr: enhancement

#18356 Allow use of search inputs by observers on non-editable actor sheets
  src/module/actor/sheet/base.ts
Labels: pr: bugfix

#18358 Correct Read Aura Spell Effect name
  packs/spell-effects/spell-effect-read-aura.json
  packs/spells/read-aura.json
Labels: pr: data update

#18330 Update Sanguine Klar items to include their runes
  packs/equipment/sanguine-klar-greater.json
  packs/equipment/sanguine-klar.json
Labels: pr: data update

#18360 Add scaling to Curse of Death
  packs/spells/curse-of-death.json
Labels: pr: data update

#18364 Add NPCs and one effect for Quest 23
  packs/campaign-effects/pathfinder-society/effect-pompous-rage.json
  packs/pfs-season-6-bestiary/quests/arrogant-foroxicks.json
  packs/pfs-season-6-bestiary/quests/disillusioned-oloranvis-elvanna.json
  packs/pfs-season-6-bestiary/quests/experienced-irrisen-bandit.json
  packs/pfs-season-6-bestiary/quests/foroxicks.json
  packs/pfs-season-6-bestiary/quests/irrisen-bandit.json
  packs/pfs-season-6-bestiary/quests/oloranvis-elvanna.json
  packs/pfs-season-6-bestiary/quests/young-warg.json
Labels: pr: data entry, source: pathfinder society

#18370 Redirect Quetzalcoatlus actor to Monster Core
  build/uuid-redirects.json
  packs/pathfinder-bestiary/quetzalcoatlus.json
Labels: pr: data update

#18368 Update text for Blasting Stone and Frost Vial, and add icon to Alicorn Trigger
  packs/equipment/alicorn-trigger.json
  packs/equipment/blasting-stone-greater.json
  packs/equipment/blasting-stone-lesser.json
  packs/equipment/blasting-stone-major.json
  packs/equipment/blasting-stone-moderate.json
  packs/equipment/bottled-sunlight-greater.json
  packs/equipment/frost-vial-greater.json
  packs/equipment/frost-vial-lesser.json
  packs/equipment/frost-vial-major.json
  packs/equipment/frost-vial-moderate.json
Labels: pr: data update

#18367 Update Goo Grenade Effect
  packs/equipment-effects/effect-goo-grenade.json
Labels: pr: data update

#18366 Update or remove inline rolls for select Spells
  packs/spells/sacred-nimbus.json
  packs/spells/sanguine-mist.json
  packs/spells/scatter-scree.json
  packs/spells/scorching-blast.json
  packs/spells/scouring-pulse.json
  packs/spells/scouring-sand.json
  packs/spells/sepulchral-mask.json
  packs/spells/shadow-illusion.json
  packs/spells/shadow-raid.json
  packs/spells/shadow-siphon.json
  packs/spells/shadows-web.json
  packs/spells/shatter-mind.json
  packs/spells/shining-starlight-attack.json
  packs/spells/shockwave.json
  packs/spells/shroud-of-flame.json
  packs/spells/signal-skyrocket.json
  packs/spells/snowball.json
  packs/spells/songbirds-call.json
  packs/spells/spike-stones.json
  packs/spells/spirit-song.json
  packs/spells/spiritual-torrent.json
  packs/spells/spout.json
  packs/spells/spray-of-stars.json
  packs/spells/stifling-stillness.json
  packs/spells/storm-of-vengeance.json
  packs/spells/sudden-blight.json
  packs/spells/sudden-bolt.json
  packs/spells/sunburst.json
  packs/spells/swampcall.json
  packs/spells/swarming-wasp-stings.json
  packs/spells/telekinetic-bombardment.json
  packs/spells/telekinetic-rend.json
  packs/spells/thunderous-strike.json
  packs/spells/timber.json
  packs/spells/toxic-cloud.json
  packs/spells/tree-of-seasons.json
  packs/spells/unbreaking-wave-advance.json
  packs/spells/untwisting-iron-buffer.json
  packs/spells/untwisting-iron-roots.json
  packs/spells/vampiric-exsanguination.json
  packs/spells/vanishing-tracks.json
  packs/spells/vector-screen.json
  packs/spells/vibrant-vibrato.json
  packs/spells/vision-of-death.json
  packs/spells/visions-of-danger.json
  packs/spells/vitrifying-blast.json
  packs/spells/volcanic-eruption.json
  packs/spells/vomit-swarm.json
  packs/spells/voracious-gestalt.json
  packs/spells/wave-of-despair.json
  packs/spells/weaponize-secret.json
  packs/spells/whirling-flames.json
  packs/spells/whirlpool.json
  packs/spells/whirlwind.json
  packs/spells/wildfire.json
  packs/spells/wronged-monks-wrath.json
  packs/spells/wyvern-sting.json
  packs/spells/ymeris-mark.json
Labels: pr: data update

#18374 Automate Terror Bird's Tearing Clutch damage
  packs/pathfinder-bestiary-3/terror-bird.json
Labels: pr: data update

#18371 Fix spellheart usages
  packs/equipment/five-feather-wreath-greater.json
  packs/equipment/five-feather-wreath-major.json
  packs/equipment/five-feather-wreath.json
  packs/equipment/grim-sandglass-greater.json
  packs/equipment/grim-sandglass-major.json
  packs/equipment/grim-sandglass.json
  packs/equipment/perfect-droplet-greater.json
  packs/equipment/perfect-droplet-major.json
  packs/equipment/perfect-droplet.json
  packs/equipment/spiny-lodestone-greater.json
  packs/equipment/spiny-lodestone-major.json
  packs/equipment/spiny-lodestone.json
  packs/equipment/thorn-triad-greater.json
  packs/equipment/thorn-triad-major.json
  packs/equipment/thorn-triad.json
  packs/equipment/trinity-geode-greater.json
  packs/equipment/trinity-geode-major.json
  packs/equipment/trinity-geode.json
  src/scripts/config/index.ts
  static/lang/en.json
Labels: pr: data update

#18363 Fix Expert Beast Gunner Spellcasting prerequisite
  packs/feats/expert-beast-gunner-spellcasting.json
Labels: pr: data update

#18376 Fix typo in Major Bestial Mutagen
  packs/equipment/bestial-mutagen-major.json
Labels: pr: data update
