Repository foundryvtt/pf2e, pull requests merged in 2025-07, with the labels that each got.

#19558 Add `area damage`, `area-effect` and `damaging-effect` options to additional NPC abilities and items
  packs/curtain-call-bestiary/book-1-stage-fright/azarpal.json
  packs/equipment/poison-fizz-greater.json
  packs/equipment/poison-fizz-lesser.json
  packs/equipment/poison-fizz-moderate.json
  packs/kingmaker-bestiary/hooktongue.json
  packs/lost-omens-bestiary/impossible-lands/clockwork-cannoneer.json
  packs/lost-omens-bestiary/monsters-of-myth/kothogaz-dance-of-disharmony.json
  packs/menace-under-otari-bestiary/horned-dragon-juvenile-bb.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/anjelique-loveless.json
  packs/pathfinder-monster-core/horned-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/horned-dragon-adult.json
  packs/pathfinder-monster-core/horned-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/horned-dragon-ancient.json
  packs/pathfinder-monster-core/horned-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/horned-dragon-young.json
  packs/pathfinder-monster-core/leukodaemon.json
  packs/pfs-season-6-bestiary/6-00/weak-xurgimoth.json
  packs/pfs-season-6-bestiary/6-08/king-rimesnap.json
  packs/pfs-season-6-bestiary/6-08/rimesnap.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/tormonshild.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/tormonwird.json
  packs/the-enmity-cycle-bestiary/jimbilin.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/avathrael-realmshaper.json
Labels: pr: data update

#19544 Select and grant a dedication feat with Social Purview
  packs/feats/archetype/vigilante/social-purview.json
Labels: pr: data update

#19469 Add name and group alterations to ItemAlteration
  src/module/item/base/sheet/sheet.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
  src/module/rules/rule-element/item-alteration/schemas.ts
  static/templates/items/weapon-details.hbs
Labels: pr: enhancement

#19440 Condense Dragon Form effects and add a grant action for Dragon Breath
  build/uuid-redirects.json
  packs/actions/dragon-breath-dragon-form.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/blune-bandersworth.json
  packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/oriole.json
  packs/feats/class/druid/dragon-shape.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/juspix-rammel.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/yabin-the-just-level-13.json
  packs/kingmaker-bestiary/phomandala.json
  packs/kingmaker-bestiary/the-wriggling-man.json
  packs/spell-effects/spell-effect-dragon-form-adamantine.json
  packs/spell-effects/spell-effect-dragon-form-conspirator.json
  packs/spell-effects/spell-effect-dragon-form-diabolic.json
  packs/spell-effects/spell-effect-dragon-form-empyreal.json
  packs/spell-effects/spell-effect-dragon-form-fortune.json
  packs/spell-effects/spell-effect-dragon-form-horned.json
  packs/spell-effects/spell-effect-dragon-form-mirage.json
  packs/spell-effects/spell-effect-dragon-form-omen.json
  packs/spell-effects/spell-effect-dragon-form.json
  packs/spells/6th-rank/dragon-form.json
  static/lang/re-en.json
Labels: pr: data update

#19560 Update Bomber's Field Vials toggle label to be more informative
  static/lang/re-en.json
Labels: pr: data update

#19549 Upgrade base size of Devrin's Cunning Stance to PC2 Marshal aura
  packs/feat-effects/stance-devrins-cunning-stance.json
Labels: pr: data update

#19512 Fix formatting for some inline saves
  packs/agents-of-edgewatch-bestiary/book-2-sixty-feet-under/life-magnet.json
  packs/spells/focus/redistribute-potential.json
Labels: pr: data update

#19563 Correct syntax typo in Beiran's `Icy Japes` ability
  packs/lost-omens-bestiary/shining-kingdoms/beiran.json
Labels: pr: data update

#19570 Prevent check for `activeGM` from aborting simulated token updates
  src/module/scene/token-document/document.ts
Labels: pr: bugfix

#19567 Remove `"adjustName": true` from Choice Sets
  packs/ancestryfeatures/draconic-exemplar.json
  packs/backgrounds/adventure-paths/kingmaker/brevic-noble.json
  packs/backgrounds/magical-experiment.json
  packs/bestiary-effects/effect-fortunes-favor.json
  packs/bestiary-effects/effect-harrowing-misfortune.json
  packs/classfeatures/bloodline-draconic.json
  packs/classfeatures/bloodline-wyrmblessed.json
  packs/feat-effects/effect-leech-clip.json
  packs/feats/class/psychic/parallel-breakthrough.json
  packs/paizo-pregens/dinner-at-lionlodge/kellsti.json
  packs/paizo-pregens/little-trouble-in-big-absalom/grimmnir.json
  packs/paizo-pregens/little-trouble-in-big-absalom/izni.json
  packs/paizo-pregens/little-trouble-in-big-absalom/quizrel.json
  packs/paizo-pregens/little-trouble-in-big-absalom/rhin.json
  packs/paizo-pregens/little-trouble-in-big-absalom/simeek.json
  packs/paizo-pregens/the-slithering/melvok.json
  packs/spell-effects/spell-effect-divine-vessel-9th-level.json
  packs/spell-effects/spell-effect-divine-vessel.json
  packs/spell-effects/spell-effect-harrowing.json
Labels: pr: data update

#19565 Add `area damage`, `area-effect` and `damaging-effect` options to another round of NPC abilities and items
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/agradaemon.json
  packs/blood-lords-bestiary/book-1-zombie-feast/dirge-piper.json
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/pyrogeist.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/echopsyvne.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/egarhowl.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/risen-nemesis.json
  packs/extinction-curse-bestiary/book-1-the-show-must-go-on/xulgath-bilebearer.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/hanas-hundreds.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/sanzuwu.json
  packs/kingmaker-bestiary/numerian-radiant-warden.json
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/gilded-gunner-safecracker.json
  packs/pathfinder-bestiary-2/radiant-warden.json
  packs/pathfinder-bestiary-3/cactus-leshy.json
  packs/pathfinder-bestiary-3/nemhaith.json
  packs/pathfinder-bestiary-3/sepid.json
  packs/pathfinder-monster-core/tor-linnorm.json
  packs/rage-of-elements-bestiary/avalanche-legion.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/clockwork-corpse.json
  packs/shadows-at-sundown-bestiary/profane-ghoul.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/avatar-of-walkena.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/dajermube.json
  packs/wardens-of-wildwood-bestiary/book-1-packbreaker/twigjack-bramble.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/primal-warden-of-zibik.json
Labels: pr: data update

#19571 Add flat modifier and roll option to `Stab and Blast` Gunslinger feat
  packs/feats/class/gunslinger/stab-and-blast.json
Labels: pr: data update

#19580 Correct damage type for `Avenging Wildwood` piercing variant
  packs/spells/2nd-rank/avenging-wildwood.json
Labels: pr: data update

#19581 Update `Surging Serum` text to match Player Core 2
  packs/equipment/surging-serum-greater.json
  packs/equipment/surging-serum-lesser.json
  packs/equipment/surging-serum-major.json
  packs/equipment/surging-serum-minor.json
  packs/equipment/surging-serum-moderate.json
Labels: pr: data update

#19574 Add another round of `area damage`, `area-effect` and `damaging-effect` options to NPC abilities and items
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/sordesdaemon.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/vanth-warrior.json
  packs/book-of-the-dead-bestiary/mummy-prophet-of-set.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/reaper-of-reputation.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/resin-seep-xulgath.json
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/blackfrost-prophet.json
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/mutant-desert-drake.json
  packs/pathfinder-bestiary-2/irlgaunt.json
  packs/pathfinder-bestiary-3/aghash.json
  packs/pathfinder-bestiary-3/ouroboros.json
  packs/pathfinder-bestiary/marid.json
  packs/pathfinder-bestiary/zaramuun.json
  packs/pathfinder-monster-core/desert-drake.json
  packs/pathfinder-monster-core/mummy-pharaoh.json
  packs/pfs-season-2-bestiary/2-21/sezruth-1-2.json
  packs/pfs-season-2-bestiary/2-21/sezruth-3-4.json
  packs/pfs-season-3-bestiary/3-14/khisisi-7-8.json
  packs/pfs-season-5-bestiary/quests/empowered-shadow-of-sezruth.json
  packs/pfs-season-5-bestiary/quests/shadow-of-sezruth.json
  packs/pfs-season-6-bestiary/6-16/amriya.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/markish-aghayarea.json
  packs/triumph-of-the-tusk-bestiary/book-3-destroyers-doom/ungukk-fleshdredge.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/coiled-conifer.json
Labels: pr: data update

#19586 Add even more `area damage`, `area-effect` and `damaging-effect` options to NPC abilities and items
  packs/age-of-ashes-bestiary/book-2-cult-of-cinders/hezle.json
  packs/agents-of-edgewatch-bestiary/book-1-devil-at-the-dreaming-palace/boiling-fountains.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/animated-tea-cart.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/shadowforged-guardian.json
  packs/curtain-call-bestiary/book-1-stage-fright/anguish-siktempora.json
  packs/extinction-curse-bestiary/book-4-siege-of-the-dinosaurs/sodden-sentinel.json
  packs/extinction-curse-bestiary/book-4-siege-of-the-dinosaurs/xulgath-gutrager.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/dancing-night-parade.json
  packs/howl-of-the-wild-bestiary/taldan-cave-squirrel.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/bureaucrat-mob.json
  packs/pathfinder-bestiary-2/calathgar.json
  packs/pathfinder-bestiary-2/shadow-drake.json
  packs/pathfinder-bestiary-2/sunflower-leshy.json
  packs/pathfinder-bestiary-3/azer.json
  packs/pathfinder-bestiary-3/underworld-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/underworld-dragon-ancient.json
  packs/pathfinder-bestiary/uthul.json
  packs/pathfinder-npc-core/official/arrester-squadron.json
  packs/pfs-introductions-bestiary/sun-scorched-shadow-drake.json
  packs/pfs-season-3-bestiary/3-06/umbral-drake.json
  packs/pfs-season-4-bestiary/4-06/infested-clockwork-heap.json
  packs/pfs-season-4-bestiary/4-06/possessed-clockwork-heap.json
  packs/pfs-season-4-bestiary/4-13/growling-shadow-drake.json
  packs/pfs-season-4-bestiary/4-13/menacing-shadow-drake.json
  packs/pfs-season-4-bestiary/4-13/mutant-shadow-drake.json
  packs/rage-of-elements-bestiary/harvest-regiment.json
  packs/rage-of-elements-bestiary/melomach.json
  packs/rage-of-elements-bestiary/oregorger.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/lesser-shadow-scamp.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/conductor.json
Labels: pr: data update

#19589 Brush up some Deviant Feats
  packs/feats/miscellaneous/deviant/blasting-beams.json
  packs/feats/miscellaneous/deviant/consume-energy.json
  packs/feats/miscellaneous/deviant/distant-wandering.json
  packs/feats/miscellaneous/deviant/ghostly-grasp-deviant.json
  packs/feats/miscellaneous/deviant/storming-breath.json
Labels: pr: data update

#19542 Add ItemAlteration Description to Extended Kinesis
  packs/feats/class/kineticist/extended-kinesis.json
  static/lang/re-en.json
Labels: pr: data update

#19551 Update formatting and automation on Anadi ancestry feats and heritages
  packs/ancestries/anadi.json
  packs/ancestryfeatures/fangs.json
  packs/feat-effects/effect-anadi-venom.json
  packs/feats/ancestry/anadi/friendform.json
  packs/feats/ancestry/anadi/hunters-fangs.json
  packs/feats/ancestry/anadi/hybrid-shape.json
  packs/feats/ancestry/anadi/reassuring-presence.json
  packs/feats/ancestry/anadi/strand-strider.json
  packs/feats/ancestry/anadi/web-hunter.json
  packs/feats/ancestry/anadi/web-walker.json
  packs/feats/ancestry/anadi/webslinger.json
  packs/heritages/anadi/adaptive-anadi.json
  packs/heritages/anadi/snaring-anadi.json
  static/lang/re-en.json
Labels: pr: data update

#19592 Fix handling of reach value of zero in CreatureSize RE
  packs/equipment-effects/effect-applereed-mutagen-greater.json
  packs/equipment-effects/effect-applereed-mutagen-lesser.json
  packs/equipment-effects/effect-applereed-mutagen-moderate.json
  src/module/rules/rule-element/creature-size.ts
Labels: pr: bugfix

#19595 Add variable damage automation to select NPC abilities
  packs/pathfinder-bestiary-3/nightmarchers.json
  packs/season-of-ghosts-bestiary/book-1-the-summer-that-never-was/shinigami.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/leshy-mob.json
Labels: pr: data update

#19594 Add another round of `area damage`, `area-effect` and `damaging-effect` options to NPC abilities and items
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/clockwork-sphinx.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/clockwork-shambler-horde.json
  packs/pathfinder-bestiary-2/sacristan.json
  packs/pathfinder-bestiary-3/clockwork-spy.json
  packs/pathfinder-bestiary-3/shambler-troop.json
  packs/pfs-season-1-bestiary/1-24/synthetic-khismar-5-6.json
  packs/pfs-season-1-bestiary/1-24/synthetic-khismar-7-8.json
  packs/pfs-season-3-bestiary/3-07/aydrian-thrune-3-4.json
  packs/pfs-season-3-bestiary/3-07/aydrian-thrune-5-6.json
  packs/pfs-season-3-bestiary/3-09/fast-shambler-troop.json
  packs/pfs-season-6-bestiary/6-06/dread-zombie-leshy-horde.json
  packs/pfs-season-6-bestiary/6-06/zombie-leshy-horde.json
  packs/pfs-season-6-bestiary/6-10/cybernetic-zombie.json
  packs/pfs-season-6-bestiary/6-10/flaring-cybernetic-zombie.json
  packs/pfs-season-6-bestiary/6-10/sparking-cybernetic-zombie.json
  packs/rage-of-elements-bestiary/munsahir-gatecrasher.json
  packs/rage-of-elements-bestiary/munsahir-trooper.json
  packs/rage-of-elements-bestiary/pelegox-cube.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/shadow-tainted-pachycephalosaurus.json
  packs/sky-kings-tomb-bestiary/book-1-mantle-of-gold/xulgath-ravening.json
  packs/sky-kings-tomb-bestiary/book-2-cult-of-the-cave-worm/shambler-troop.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/ticktock.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/avathrael-realmshaper.json
Labels: pr: data update

#19597 Add Trip (acrobatics) action to Tumbling Opportunist
  packs/feats/archetype/acrobat/tumbling-opportunist.json
  packs/feats/class/kineticist/extended-kinesis.json
Labels: pr: data update

#19608 Fix remaster of corpseward pendant
  packs/equipment/corpseward-pendant.json
Labels: pr: data update

#19612 Fix display of melee-sheet damage partials
  src/styles/item/_melee-sheet.scss
  static/templates/items/melee-details.hbs
Labels: pr: bugfix

#19613 Add Feint action to Distracting Spellstrike
  packs/feats/class/magus/distracting-spellstrike.json
Labels: pr: data update

#19614 Improve search performance of ABC picker and fix clearing query
  src/module/actor/character/apps/abc-picker/app.svelte
Labels: pr: bugfix

#19616 Add `area-effect`, `area-damage`, `damage-effect`, and `inflicts:` options to select NPC abilities
  packs/age-of-ashes-bestiary/book-5-against-the-scarlet-triad/aluum-enforcer.json
  packs/age-of-ashes-bestiary/book-5-against-the-scarlet-triad/spiritbound-aluum.json
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/solar-glass-golem.json
  packs/book-of-the-dead-bestiary/pale-sovereign.json
  packs/fall-of-plaguestone/blood-ooze.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/tamikan.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/bul-gae.json
  packs/lost-omens-bestiary/tian-xia-world-guide/bul-gae.json
  packs/pathfinder-bestiary-3/clacking-sea-skull-swarm.json
  packs/pathfinder-bestiary-3/clacking-skull-swarm.json
  packs/pathfinder-monster-core/conspirator-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-adult.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient.json
  packs/pathfinder-monster-core/conspirator-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-young.json
  packs/pfs-season-4-bestiary/4-06/harpy-wailer.json
  packs/pfs-season-4-bestiary/4-15/elite-clacking-skull-swarm.json
  packs/pfs-season-4-bestiary/4-15/weak-clacking-skull-swarm.json
  packs/prey-for-death-bestiary/vatumledor.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/bulbous-blood-ooze.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/guardian-aluum.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/mighty-bul-gae.json
Labels: pr: data update

#19624 Fix chat token images blocking saves posted to chat once more
  src/module/chat-message/document.ts
Labels: pr: bugfix

#19622 Release Notes 7.2.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19621 Add `area-effect`, `area-damage`, `damage-effect`, and `inflicts:` options to select NPC abilities
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/dragons-blood-puffball.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/reaper-skull-puffball.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/ectoplasmic-amalgam.json
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/vavakia.json
  packs/kingmaker-bestiary/bloom-of-lamashtu.json
  packs/lost-omens-bestiary/mwangi-expanse/sié-goluo.json
  packs/lost-omens-bestiary/tian-xia-world-guide/animated-wine-vessel.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/pyronite-ooze.json
  packs/pathfinder-bestiary-2/mudwretch.json
  packs/pathfinder-bestiary-2/sard.json
  packs/pathfinder-dark-archive/k-h-w-s-echo.json
  packs/pfs-season-2-bestiary/2-06/weak-mudwretch.json
  packs/rage-of-elements-bestiary/avalanche-legion.json
  packs/rusthenge-bestiary/vloriak.json
  packs/season-of-ghosts-bestiary/book-3-no-breath-to-cry/shrine-maiden.json
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/sinmold.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/miastrilek.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/spore-thrall.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/zauglagaul.json
  packs/spore-war-bestiary/book-3-a-voice-in-the-blight/vamollaroth.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/mogaran.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/grouloop.json
  packs/strength-of-thousands-bestiary/book-5-doorway-to-the-red-star/gluttonworm.json
Labels: pr: data update

#19623 Add automation and effect to `Flynkett`'s `Kettle Up` ability
  packs/bestiary-effects/effect-kettle-up-boiling.json
  packs/howl-of-the-wild-bestiary/flynkett.json
  static/lang/re-en.json
Labels: pr: data update

#19627 Add `area-effect`, `area-damage`, `damage-effect`, and `inflicts:` options to additional select NPC abilities
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/reaper-skull-puffball.json
  packs/feats/ancestry/leshy/spore-cloud.json
  packs/lost-omens-bestiary/monsters-of-myth/melfesh-monster.json
  packs/one-shot-bestiary/a-fistful-of-flowers/darius.json
  packs/pathfinder-bestiary/hive-mother.json
  packs/pathfinder-bestiary/vrock.json
  packs/pathfinder-dark-archive/verdures-moonflower.json
  packs/pathfinder-monster-core/ankhrav-hive-mother.json
  packs/pathfinder-monster-core/ankhrav.json
  packs/pathfinder-monster-core/fungus-leshy.json
  packs/pathfinder-monster-core/quai-dau-to.json
  packs/pfs-introductions-bestiary/rain-in-cloudy-day.json
  packs/pfs-season-2-bestiary/2-01/abyssal-fungi.json
  packs/pfs-season-2-bestiary/2-01/weakened-abyssal-fungi.json
  packs/pfs-season-2-bestiary/2-15/blighted-fungus-leshy.json
  packs/pfs-season-6-bestiary/6-06/dread-leshy-ghoul.json
  packs/pfs-season-6-bestiary/6-06/leshy-ghoul.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/acid-mist.json
  packs/sky-kings-tomb-bestiary/book-1-mantle-of-gold/hyphae-tyrant.json
  packs/sky-kings-tomb-bestiary/book-1-mantle-of-gold/skibrellon.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/fungal-marsh-giant.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/tanglebriar-regent.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/glitterspore.json
Labels: pr: data update

#19632 Add effect for `Singing Shortbow`'s ability `Song of Soothing`
  packs/equipment-effects/effect-song-of-soothing.json
  packs/equipment/burr-shield.json
  packs/equipment/singing-shortbow-greater.json
  packs/equipment/singing-shortbow.json
Labels: pr: data update

#19631 Update theatrical mutagen (lesser) to remaster
  packs/equipment/theatrical-mutagen-lesser.json
Labels: pr: data update

#19634 Add `area-effect`, `area-damage`, `damage-effect`, and `inflicts:` options to additional select items and NPC abilities
  packs/abomination-vaults-bestiary/book-1-ruins-of-gauntlight/scalathrax.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/kelganth.json
  packs/equipment/staff-of-power.json
  packs/equipment/staff-of-the-magi.json
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/shanchek.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/berberoka.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/grave-spinosaurus.json
  packs/howl-of-the-wild-bestiary/royal-basilisk.json
  packs/howl-of-the-wild-bestiary/storm-snake.json
  packs/kingmaker-bestiary/foras.json
  packs/kingmaker-bestiary/kundal.json
  packs/kingmaker-bestiary/wild-hunt-hound.json
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/mutant-giant-toad.json
  packs/pathfinder-bestiary-2/spinosaurus.json
  packs/pathfinder-bestiary-3/harmona.json
  packs/pathfinder-bestiary-3/valkyrie.json
  packs/pathfinder-monster-core/akhana.json
  packs/pathfinder-monster-core/lyrakien.json
  packs/pfs-season-1-bestiary/quests/storm-acolyte.json
  packs/pfs-season-1-bestiary/quests/storm-warrior-priest.json
  packs/pfs-season-6-bestiary/6-13/giant-stinkbug.json
  packs/prey-for-death-bestiary/valkyrie-of-gorum.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/aeon-stone-swarm.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/svaryr-commander.json
Labels: pr: data update

#19639 Remove unnecessary IIFE in rule element creation
  src/module/rules/index.ts
Labels: pr: refactor

#19635 Automate Sky Dragon's Divine Lightning
  packs/pathfinder-bestiary-3/sky-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/sky-dragon-adult.json
  packs/pathfinder-bestiary-3/sky-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/sky-dragon-ancient.json
Labels: pr: data update

#19629 Add automation to `Cornered Fury`
  packs/feats/ancestry/ratfolk/cornered-fury.json
Labels: pr: data update

#19615 Automate Instinct Crown
  packs/equipment-effects/effect-instinct-crown.json
  packs/equipment/instinct-crown-animal.json
  packs/equipment/instinct-crown-dragon.json
  packs/equipment/instinct-crown-fury.json
  packs/equipment/instinct-crown-giant.json
  packs/equipment/instinct-crown-spirit.json
  packs/equipment/instinct-crown-superstition.json
  static/lang/re-en.json
Labels: pr: data update

#19598 Add effects for `Outcast's Curse` and fix broken Recall Knowledge item link on `Crown of Prophets`
  packs/spell-effects/spell-effect-outcasts-curse-failure.json
  packs/spell-effects/spell-effect-outcasts-curse-success.json
  packs/spells/2nd-rank/funeral-flames.json
  packs/spells/2nd-rank/pyrefowl-rebuke.json
  packs/spells/4th-rank/outcasts-curse.json
  packs/spells/6th-rank/dragon-form.json
  packs/spells/focus/crown-of-prophets.json
  packs/spells/focus/gift-of-the-anemos.json
  packs/spells/ritual/rite-of-cleansing-flame.json
Labels: pr: data update

#19643 Add `area-effect`, `area-damage`, `damage-effect`, and `inflicts:` options to additional select items and NPC abilities
  packs/extinction-curse-bestiary/book-5-lord-of-the-black-sands/iffdahsil.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/flying-mountain-kaminari.json
  packs/howl-of-the-wild-bestiary/warden-of-peaks-and-skies.json
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/i.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/headless-rustler.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/ogre-slug.json
  packs/pathfinder-bestiary-2/living-thunderclap.json
  packs/pathfinder-bestiary-3/eunemvro.json
  packs/pathfinder-bestiary-3/kokogiak.json
  packs/pathfinder-bestiary-3/sea-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/sea-dragon-ancient.json
  packs/pathfinder-bestiary-3/tolokand.json
  packs/pfs-season-3-bestiary/3-99/temporal-echoes-1-2.json
  packs/pfs-season-3-bestiary/3-99/temporal-echoes-3-4.json
  packs/pfs-season-3-bestiary/3-99/temporal-echoes-5-6.json
  packs/pfs-season-3-bestiary/3-99/temporal-echoes-7-8.json
  packs/pfs-season-3-bestiary/bounties/falling-tree.json
  packs/prey-for-death-bestiary/frostripper.json
  packs/prey-for-death-bestiary/valkyrie-tempest.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/graylok-artillerist.json
  packs/rage-of-elements-bestiary/boiling-spring.json
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/yuni.json
  packs/wardens-of-wildwood-bestiary/book-1-packbreaker/arboreal-sapling.json
Labels: pr: data update

#19648 Replace collapsed actions with general minHeight based solution
  src/module/chat-message/document.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/cards.ts
  src/styles/legacy/_chat.scss
  src/styles/ui/sidebar/chat/_action.scss
  src/styles/ui/sidebar/chat/_index.scss
  static/templates/chat/action/collapsed.hbs
Labels: pr: enhancement

#19652 Clear movement history at end of each combatant's turn
  src/module/encounter/document.ts
  types/foundry/client/documents/combat.d.mts
  types/foundry/client/documents/combatant.d.mts
Labels: pr: enhancement

#19659 Fix prefixing of token-mark roll options
  src/module/actor/roll-context/base.ts
  src/module/rules/rule-element/token-mark/rule-element.ts
Labels: pr: bugfix

#19658 Fix some lore localization keys
  packs/equipment/fiendbreaker-heroic.json
  packs/equipment/guiding-star-orb-heroic.json
  packs/equipment/slithermaws-bane-heroic.json
  packs/fall-of-plaguestone/blood-ooze.json
  packs/pathfinder-bestiary-2/calathgar.json
  packs/pathfinder-bestiary-3/clacking-skull-swarm.json
Labels: pr: data update

#19662 Auto collapse spell descriptions
  static/templates/chat/spell-card.hbs
Labels: pr: enhancement

#19340 Preserve certain changes when chaining spell.loadVariant()
  src/module/item/spell/document.ts
Labels: pr: enhancement

#19664 Correct some area-effect and area-damage options
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/dancing-night-parade.json
  packs/lost-omens-bestiary/shining-kingdoms/failed-prophet.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/bureaucrat-mob.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/clockwork-shambler-horde.json
  packs/pathfinder-bestiary-3/sky-dragon-ancient-spellcaster.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/tormonshild.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/cataclysm-beetle.json
Labels: pr: data update

#19666 Fix the category of the Bargainer's Instrument
  packs/equipment/bargainers-instrument.json
Labels: pr: data update

#19645 Update Dedication trait to match Pathfinder Player Core text
  static/lang/en.json
Labels: pr: data update

#19686 Fix Effect: A Challenge for Heroes
  packs/feat-effects/effect-a-challenge-for-heroes.json
Labels: pr: data update

#19687 Strip special keys when migrating to avoid errors
  src/module/migration/runner/index.ts
Labels: pr: bugfix

#19689 Fix base spell variant not getting restored internally
  src/module/chat-message/data.ts
  src/module/item/spell/document.ts
Labels: pr: bugfix

#19681 Stop adding invested trait to armor potency alterations
  src/module/item/physical/document.ts
  src/module/rules/rule-element/item-alteration/alteration.ts
Labels: pr: bugfix

#19630 Add effect to `Inescapable Grasp` feat
  packs/feat-effects/effect-inescapable-grasp.json
  packs/feats/archetype/wrestler/inescapable-grasp.json
  static/lang/re-en.json
Labels: pr: data update

#19649 Add effect to `Humanoid Form` spell
  packs/spell-effects/spell-effect-humanoid-form.json
  packs/spells/2nd-rank/humanoid-form.json
  static/lang/re-en.json
Labels: pr: data update

#19644 Update `Wand of Shardstorm` to spell wands and fix broken links in select rollable tables.
  packs/equipment/wand-of-shardstorm-1st-rank-spell.json
  packs/equipment/wand-of-shardstorm-3rd-rank-spell.json
  packs/equipment/wand-of-shardstorm-5th-rank-spell.json
  packs/equipment/wand-of-shardstorm-7th-rank-spell.json
  packs/rollable-tables/13th-level-permanent-items.json
  packs/rollable-tables/7th-level-permanent-items.json
  packs/rollable-tables/9th-level-permanent-items.json
Labels: pr: data update

#19693 Fix spacing between strike tag rows
  src/styles/_tags.scss
Labels: pr: bugfix, ui/ux

#19694 Update svelte version
  package-lock.json
  package.json
Labels: pr: housekeeping

#19697 change envision for (concentration) in druid's crown
  packs/equipment/druids-crown.json
Labels: pr: data update

#19711 Check consumable trait instead when checking crafting quantity
  src/module/actor/character/crafting/crafting.ts
Labels: pr: enhancement

#19700 Upgrade Energy Emanation damage with Energy Blessed along with a description addendum
  packs/feats/ancestry/dwarf/energy-blessed.json
  packs/pfs-season-6-bestiary/6-99/angry-victims.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-captain.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-novice.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-trainee.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple-veteran.json
  packs/pfs-season-6-bestiary/6-99/dispatch-disciple.json
  packs/pfs-season-6-bestiary/6-99/elite-ghoul-stalker-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/elite-shadow-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/empowered-rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/enraged-rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/extremely-haunted-hollows.json
  packs/pfs-season-6-bestiary/6-99/ghoul-commando.json
  packs/pfs-season-6-bestiary/6-99/haunted-hollows.json
  packs/pfs-season-6-bestiary/6-99/invigorated-sotroz.json
  packs/pfs-season-6-bestiary/6-99/livid-victims.json
  packs/pfs-season-6-bestiary/6-99/rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/somewhat-haunted-hollows.json
  packs/pfs-season-6-bestiary/6-99/sotroz.json
  packs/pfs-season-6-bestiary/6-99/tired-dockhand.json
  packs/pfs-season-6-bestiary/6-99/very-haunted-hollows.json
  packs/pfs-season-6-bestiary/6-99/weak-dispatch-disciple-captain.json
  packs/pfs-season-6-bestiary/6-99/weak-ghoul-soldier-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/weak-ghoul-stalker-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/weak-mummy-guardian-pfs-6-99.json
  packs/pfs-season-6-bestiary/_folders.json
  static/lang/re-en.json
Labels: pr: data update

#19718 Correct typo in `Guardian's Fury` feat roll option
  packs/feats/archetype/ulfen-guard/guards-fury.json
Labels: pr: data update

#19719 Fix speed penalty Rogue debilitation
  packs/actions/brandish-the-gorgons-gaze.json
  packs/actions/debilitating-strike.json
  packs/actions/tangle-in-riddle.json
  packs/actions/unravel-the-future.json
  packs/bestiary-effects/effect-aura-of-sophistry-holy.json
  packs/bestiary-effects/effect-aura-of-sophistry-unholy.json
  packs/bestiary-effects/effect-aura-of-sophistry-weakness.json
  packs/classfeatures/plunderer-of-the-hives-riches.json
  packs/classfeatures/trespasser-in-deaths-realm.json
  packs/equipment/hydra-head-club.json
  packs/equipment/protectors-final-gift.json
  packs/equipment/vortex-pouch.json
  packs/feat-effects/effect-debilitating-strike.json
  packs/feat-effects/effect-enduring-debilitating-strike.json
  packs/feats/class/exemplar/as-a-thousand-soldiers.json
  packs/feats/class/exemplar/follow-the-threads-of-fate.json
  packs/feats/class/exemplar/forward-gaze-into-life.json
  packs/feats/class/exemplar/riddle-the-sphinx.json
  packs/feats/class/exemplar/shield-of-stone.json
  packs/feats/class/exemplar/topple-the-titans.json
  packs/feats/class/rogue/enduring-debilitation.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/amnerion.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/bee-borer.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/eumenid.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/firehoof-minotaur.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/forgotten-dead.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/gigantic-bee-drone.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/gigantic-bee-guard.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/gigantic-bee-royal-guardian.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/keribos.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/lava-spitter.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/neshkefru.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/omorphos.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/precarious-footing.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/pyrkaion.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/skeletal-champion.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/temptation-of-glory.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/vornen.json
  packs/myth-speaker-bestiary/book-2-death-sails-a-wine-dark-sea/withered-flame-drake.json
  packs/pfs-season-6-bestiary/6-20/harbinger-of-ingalor-11-12.json
  packs/pfs-season-6-bestiary/6-20/harbinger-of-ingalor.json
  packs/pfs-season-6-bestiary/6-20/hesla-the-broken-ember-11-12.json
  packs/pfs-season-6-bestiary/6-20/hesla-the-broken-ember.json
  packs/pfs-season-6-bestiary/6-20/riftcarver-11-12.json
  packs/pfs-season-6-bestiary/6-20/riftcarver.json
  packs/pfs-season-6-bestiary/_folders.json
  packs/spells/ritual/labyrinthine-prison.json
  src/scripts/config/traits.ts
  static/lang/en.json
  static/lang/re-en.json
Labels: pr: data update

#19713 Add `The Scourge of Sheerleaf` pregens
  packs/paizo-pregens/_folders.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/brave-wanderer.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/kiana.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/ruvior.json
  packs/paizo-pregens/the-scourge-of-sheerleaf/sizkmi.json
Labels: pr: data entry

#19706 Fix category of Hydrocannon
  packs/equipment/hydrocannon.json
Labels: pr: data update

#19731 Fix wyrm's wingspan price
  packs/equipment/wyrms-wingspan-greater.json
  packs/equipment/wyrms-wingspan-major.json
Labels: pr: data update

#19736 Fix scaling of Improved Elemental Blast
  packs/feats/archetype/kineticist/improved-elemental-blast.json
Labels: pr: data update

#19724 Add effect to Sporescout's Cloak of Subversion action.
  packs/bestiary-effects/effect-cloak-of-subversion.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/sporescout.json
Labels: pr: data update

#19739 Update Debilitating Bomb automation to account for Greater and True Debilitating Bomb
  packs/feat-effects/effect-debilitating-bomb.json
  packs/feats/class/alchemist/debilitating-bomb.json
  packs/feats/class/alchemist/greater-debilitating-bomb.json
  packs/feats/class/alchemist/true-debilitating-bomb.json
  packs/pfs-season-6-bestiary/6-99/elite-ghoul-stalker-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/elite-shadow-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/rowan-the-whispering.json
  packs/pfs-season-6-bestiary/6-99/weak-dispatch-disciple-captain.json
  packs/pfs-season-6-bestiary/6-99/weak-ghoul-soldier-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/weak-ghoul-stalker-pfs-6-99.json
  packs/pfs-season-6-bestiary/6-99/weak-mummy-guardian-pfs-6-99.json
  static/lang/re-en.json
Labels: pr: data update

#19742 Add some Battlecry! localization
  packs/feat-effects/effect-mirrored-wall.json
  packs/feat-effects/effect-sanguine-revitalization.json
  packs/feats/class/alchemist/true-debilitating-bomb.json
  static/lang/re-en.json
Labels: pr: data update

#19743 Add Battlecry! iconics and PFS Rulings and Clarifications
  packs/actions/passage-of-lines.json
  packs/equipment-effects/effect-arcane-standard-greater.json
  packs/equipment-effects/effect-arcane-standard.json
  packs/equipment-effects/effect-cornucopia-of-plenty.json
  packs/equipment/arcane-standard-greater.json
  packs/equipment/arcane-standard.json
  packs/equipment/bloodstained-waistcoat.json
  packs/equipment/cornucopia-of-plenty.json
  packs/equipment/locket-of-love-left-behind.json
  packs/feats/ancestry/jotunborn/level-5/pounding-leap.json
  packs/feats/archetype/bastion/shield-salvation.json
  packs/feats/class/commander/banners-inspiration.json
  packs/feats/class/commander/defensive-swap.json
  packs/feats/class/fighter/improved-reflexive-shield.json
  packs/feats/class/guardian/ring-their-bell.json
  packs/feats/class/guardian/shield-salvation.json
  packs/feats/class/shared-class-feats/improved-reflexive-shield.json
  packs/iconics/grimmyr-level-1.json
  packs/iconics/grimmyr-level-3.json
  packs/iconics/grimmyr-level-5.json
  packs/iconics/ulka-level-1.json
  packs/iconics/ulka-level-3.json
  packs/iconics/ulka-level-5.json
  packs/journals/archetypes.json
  packs/spells/5th-rank/blinding-bottle.json
  packs/spells/focus/let-not-the-fallen-rest.json
  static/icons/iconics/GrimmyrFull.webp
  static/icons/iconics/UlkaFull.webp
Labels: pr: data entry, pr: data update, pr: static assets

#19744 Update Archetype Journal to include Pathfinder Battlecry! content
  packs/feats/archetype/commander/commander-dedication.json
  packs/feats/archetype/field-propagandist/level-2/field-propagandist-dedication.json
  packs/feats/archetype/guardian/guardian-dedication.json
  packs/feats/archetype/guerrilla/level-2/guerrilla-dedication.json
  packs/feats/archetype/iridian-choirmaster/level-2/iridian-choirmaster-dedication.json
  packs/feats/archetype/munitions-master/munitions-master-dedication.json
  packs/feats/archetype/necrologist/level-6/necrologist-dedication.json
  packs/feats/archetype/war-mage/war-mage-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#19747 Correct tag on Defensive Retreat tactic
  packs/actions/defensive-retreat.json
Labels: pr: data update

#19745 Add localization for select Pathfinder Battlecry NPC attacks
  packs/battlecry-bestiary/clockwork-infantry.json
  packs/battlecry-bestiary/fleshwarp-amalgam.json
  static/lang/re-en.json
Labels: pr: data update

#19682 Implement rerolling checks with a mythic point
  src/module/apps/sidebar/chat-log.ts
  src/module/system/check/check.ts
  src/module/system/check/roll.ts
  src/styles/ui/sidebar/chat/_reroll.scss
  static/lang/en.json
Labels: pr: enhancement
