Repository foundryvtt/pf2e, pull requests merged in 2025-10, with the labels that each got.

#20378 Show activity count instead of minimum speed under Exploration Activities in party sheet
  src/module/actor/party/sheet.ts
Labels: pr: bugfix

#20379 Update some elements of rule editing to use V13 DOM toolchain
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/item/base/sheet/sheet.ts
  src/styles/item/_index.scss
  static/templates/items/rules-panel.hbs
  static/templates/items/rules/flat-modifier.hbs
  static/templates/items/rules/partials/outer.hbs
Labels: pr: bugfix, pr: refactor

#20383 Fix array handling in FlatModifier form
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/item/base/sheet/rule-element-form/flat-modifier.ts
  static/templates/items/rules/flat-modifier.hbs
Labels: pr: bugfix

#20380 Remove `isObject` helper
  src/module/actor/actions/single-check.ts
  src/module/actor/data/iwr.ts
  src/module/actor/hazard/document.ts
  src/module/item/physical/document.ts
  src/module/migration/migrations/766-wipe-url-sources.ts
  src/module/migration/migrations/790-multiple-class-dcs.ts
  src/module/migration/migrations/793-make-predicates-arrays.ts
  src/module/migration/migrations/849-delete-broken-threshold.ts
  src/module/migration/migrations/859-material-type-grade.ts
  src/module/migration/migrations/883-banish-alignment.ts
  src/module/migration/migrations/885-convert-alignment-damage.ts
  src/module/rules/rule-element/battle-form/rule-element.ts
  src/module/rules/rule-element/damage-dice.ts
  src/module/rules/rule-element/data.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/module/system/statistic/statistic.ts
  src/util/misc.ts
Labels: pr: refactor

#20382 Remove area trait from actions and convert effect area to tag
  src/module/actor/helpers.ts
  src/module/actor/npc/sheet.ts
  src/module/actor/npc/types.ts
  src/module/item/melee/document.ts
  src/module/system/check/check.ts
  src/module/system/damage/damage.ts
  src/scripts/config/traits.ts
  src/util/tags.ts
  static/templates/actors/npc/partials/attack.hbs
Labels: pr: enhancement, sf2e

#20367 Add ItemAlteration to Leap And Fire that shows the feat information on its prerequisite feat/reaction
  packs/feats/class/gunslinger/leap-and-fire.json
Labels: pr: data update

#20392 Fix migration not returning for SF2e ammo
  src/module/migration/migrations/946-ammo-category.ts
Labels: pr: bugfix

#20375 Fix AC for Effect: A Little Bird Told Me...
  packs/feat-effects/effect-a-little-bird-told-me.json
Labels: pr: data update

#20369 Unify damage for Iron Maiden Trap
  packs/agents-of-edgewatch-bestiary/book-2-sixty-feet-under/iron-maiden-trap.json
Labels: pr: data update

#20374 Add automation to Soaring Wings
  packs/equipment-effects/effect-soaring-wings.json
  packs/equipment/soaring-wings-greater.json
  packs/equipment/soaring-wings-major.json
  packs/equipment/soaring-wings.json
Labels: pr: data update

#20403 Fix value for Effect: Soaring Wings
  packs/equipment-effects/effect-soaring-wings.json
Labels: pr: data update

#20404 Remove and redirect extraneous copy of Sand Racer
  build/uuid-redirects.json
  packs/strength-of-thousands-bestiary/book-5-doorway-to-the-red-star/sand-racer.json
Labels: pr: data update

#20401 Retire and migration away Striking and WeaponPotency REs
  build/run-migration.ts
  packs/boons-and-curses/iomedae-major-boon.json
  packs/equipment-effects/effect-azarim.json
  packs/equipment-effects/effect-oil-of-potency.json
  packs/equipment-effects/effect-potency-crystal.json
  packs/equipment/berserkers-cloak-greater.json
  packs/equipment/berserkers-cloak.json
  packs/equipment/dwarven-thrower.json
  packs/equipment/frost-fair-yanyuedao.json
  packs/equipment/gloom-blade.json
  packs/equipment/lions-shield.json
  packs/equipment/phantom-shroud.json
  packs/equipment/rod-of-razors.json
  packs/equipment/unholy-plate.json
  packs/feat-effects/effect-core-cannon.json
  packs/feat-effects/effect-invoke-offense.json
  packs/iconics/droogami-level-5.json
  packs/iconics/whirp-level-5.json
  packs/kingmaker-bestiary/castruccio-irovetti.json
  packs/spell-effects/spell-effect-augmented-body.json
  packs/spell-effects/spell-effect-conductive-weapon.json
  packs/spell-effects/spell-effect-funeral-flames.json
  packs/spell-effects/spell-effect-magic-stone.json
  packs/spell-effects/spell-effect-runic-body.json
  packs/spell-effects/spell-effect-runic-weapon.json
  packs/spell-effects/spell-effect-shillelagh.json
  packs/spell-effects/spell-effect-wooden-fists.json
  src/module/migration/migrations/945-re-brackets-to-strings.ts
  src/module/migration/migrations/946-ammo-data.ts
  src/module/migration/migrations/947-retire-potency-striking-res.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/rules/index.ts
  src/module/rules/rule-element/item-alteration/handlers.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/striking.ts
  src/module/rules/rule-element/weapon-potency.ts
  static/lang/re-en.json
Labels: pr: data migration, pr: refactor

#20406 Fix size downgrades of Bulk for values greater than 1
  src/module/item/physical/bulk.ts
Labels: pr: bugfix

#20412 Limit Rogue Dedication to skill feats at or below the character's level
  packs/feats/archetype/rogue/rogue-dedication.json
Labels: pr: data update

#20413 Remove incorrect link to Invisible condition in Consult the Spirits
  packs/feats/skill/consult-the-spirits.json
Labels: pr: data update

#20417 Correct action cost of Instant Minefield
  packs/spells/5th-rank/instant-minefield.json
Labels: pr: data update

#20419 Add The Scourge of Sheerleaf NPCs
  packs/one-shot-bestiary/_folders.json
  packs/one-shot-bestiary/the-scourge-of-sheerleaf/armored-cave-bears.json
  packs/one-shot-bestiary/the-scourge-of-sheerleaf/boulder-cage.json
  packs/one-shot-bestiary/the-scourge-of-sheerleaf/zikritrax.json
Labels: pr: data entry
