Repository foundryvtt/pf2e, pull requests merged in 2025-04, with the labels that each got.

#18711 Add automation to Kappa's arm pull
  packs/pathfinder-bestiary-3/kappa.json
Labels: pr: data update

#18717 Automate Sash of Books's Recall Knowledge activation
  packs/equipment-effects/effect-sash-of-books-bonus.json
  packs/equipment-effects/effect-sash-of-books-recall-knowledge.json
  packs/equipment/sash-of-books.json
  static/lang/re-en.json
Labels: pr: data update

#18716 Add notes for half damage on a failure to legendary saves features
  packs/classfeatures/assured-evasion.json
  packs/classfeatures/fortress-of-will.json
  packs/classfeatures/greater-dogged-will.json
  packs/classfeatures/greater-juggernaut.json
  packs/classfeatures/greater-kinetic-durability.json
  packs/classfeatures/greater-mysterious-resolve.json
  packs/classfeatures/greater-natural-reflexes.json
  packs/classfeatures/greater-performers-heart.json
  packs/classfeatures/greater-rogue-reflexes.json
  packs/classfeatures/third-path-to-perfection.json
  static/lang/re-en.json
Labels: pr: data update

#18715 Rename and link Swallow Whole effect to include Engulf
  packs/bestiary-effects/effect-engulf-and-swallow-whole.json
  static/lang/en.json
Labels: pr: data update

#18713 Move Beginner Box Pregens backstory text to the `Backstory` section
  packs/paizo-pregens/beginner-box/ezren-beginner-box.json
  packs/paizo-pregens/beginner-box/kyra-beginner-box.json
  packs/paizo-pregens/beginner-box/merisiel-beginner-box.json
  packs/paizo-pregens/beginner-box/valeros-beginner-box.json
Labels: pr: data update

#18710 Remove dupe society skills action entry in GM Screen
  packs/journals/gm-screen.json
Labels: pr: data update

#18709 Add missing bow group note for Grievous rune
  src/module/item/physical/runes.ts
Labels: pr: data update

#18721 Correct size of Arrester Squadron and Watchmage Squadron to gargantuan
  packs/pathfinder-npc-core/official/arrester-squadron.json
  packs/pathfinder-npc-core/official/watchmage-squadron.json
Labels: pr: data update

#18714 Add description addenda for Irongut Goblin and Virtuous Tanuki when sickened
  packs/conditions/sickened.json
  packs/heritages/goblin/irongut-goblin.json
  packs/heritages/tanuki/virtuous-tanuki.json
  static/lang/re-en.json
Labels: pr: data update

#18722 Add options introduced in the 2025-04-01 Paizo Blog
  packs/actions/tell-me-more.json
  packs/bestiary-effects/effect-cloud-of-allergens.json
  packs/blog-bestiary/_folders.json
  packs/blog-bestiary/foolish-housekeeping-and-other-articles/dust-bunny-swarm.json
  packs/blog-bestiary/foolish-housekeeping-and-other-articles/rt5rrmn.json
  packs/familiar-abilities/specific-familiary-abilities/kick-up-dust.json
  packs/feat-effects/effect-a-little-bird-told-me.json
  packs/feats/_folders.json
  packs/feats/archetype/venture-gossip/a-little-bird-told-me.json
  packs/feats/archetype/venture-gossip/catch-and-kill.json
  packs/feats/archetype/venture-gossip/define-report.json
  packs/feats/archetype/venture-gossip/hey-over-here.json
  packs/feats/archetype/venture-gossip/muckraking.json
  packs/feats/archetype/venture-gossip/venture-gossip-dedication.json
  packs/feats/archetype/venture-gossip/verbose-distraction.json
  packs/feats/general/speedrun-strats.json
  packs/journals/archetypes.json
Labels: pr: data update

#18730 Link various `Bloodstone of Arzani` effects to their corresponding items
  packs/equipment/heart-bloodstone-of-arazni.json
  packs/equipment/liver-bloodstone-of-arazni.json
  packs/equipment/lung-bloodstone-of-arazni.json
Labels: pr: data update

#18729 Condense Soothing Tonic equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-soothing-tonic-greater.json
  packs/equipment-effects/effect-soothing-tonic-lesser.json
  packs/equipment-effects/effect-soothing-tonic-major.json
  packs/equipment-effects/effect-soothing-tonic-moderate.json
  packs/equipment-effects/effect-soothing-tonic.json
  packs/equipment/soothing-tonic-greater.json
  packs/equipment/soothing-tonic-lesser.json
  packs/equipment/soothing-tonic-major.json
  packs/equipment/soothing-tonic-moderate.json
Labels: pr: data update

#18736 Change Beginner Box actor ids to match their Monster Core equivalents
  build/uuid-redirects.json
  packs/menace-under-otari-bestiary/animated-armor-bb.json
  packs/menace-under-otari-bestiary/basilisk-bb.json
  packs/menace-under-otari-bestiary/boar-bb.json
  packs/menace-under-otari-bestiary/brine-shark-bb.json
  packs/menace-under-otari-bestiary/bugbear-prowler-bb.json
  packs/menace-under-otari-bestiary/caligni-dancer-bb.json
  packs/menace-under-otari-bestiary/caligni-hunter-bb.json
  packs/menace-under-otari-bestiary/caligni-skulker-bb.json
  packs/menace-under-otari-bestiary/cinder-rat-bb.json
  packs/menace-under-otari-bestiary/forest-troll-bb.json
  packs/menace-under-otari-bestiary/gargoyle-bb.json
  packs/menace-under-otari-bestiary/ghost-commoner-bb.json
  packs/menace-under-otari-bestiary/ghoul-stalker-bb.json
  packs/menace-under-otari-bestiary/giant-ant-bb.json
  packs/menace-under-otari-bestiary/giant-centipede-bb.json
  packs/menace-under-otari-bestiary/giant-rat-bb.json
  packs/menace-under-otari-bestiary/giant-spider-bb.json
  packs/menace-under-otari-bestiary/giant-viper-bb.json
  packs/menace-under-otari-bestiary/goblin-commando-bb.json
  packs/menace-under-otari-bestiary/goblin-igniter-bb.json
  packs/menace-under-otari-bestiary/goblin-warrior-bb.json
  packs/menace-under-otari-bestiary/harpy-bb.json
  packs/menace-under-otari-bestiary/hell-hound-bb.json
  packs/menace-under-otari-bestiary/hobgoblin-soldier-bb.json
  packs/menace-under-otari-bestiary/kobold-scout-bb.json
  packs/menace-under-otari-bestiary/kobold-warrior-bb.json
  packs/menace-under-otari-bestiary/leopard-bb.json
  packs/menace-under-otari-bestiary/minotaur-hunter-bb.json
  packs/menace-under-otari-bestiary/ogre-warrior-bb.json
  packs/menace-under-otari-bestiary/orc-commander-bb.json
  packs/menace-under-otari-bestiary/orc-scrapper-bb.json
  packs/menace-under-otari-bestiary/orc-veteran-bb.json
  packs/menace-under-otari-bestiary/pugwampi-bb.json
  packs/menace-under-otari-bestiary/reefclaw-bb.json
  packs/menace-under-otari-bestiary/sewer-ooze-bb.json
  packs/menace-under-otari-bestiary/shadow-bb.json
  packs/menace-under-otari-bestiary/skeletal-giant-bb.json
  packs/menace-under-otari-bestiary/skeleton-guard-bb.json
  packs/menace-under-otari-bestiary/sod-hound-bb.json
  packs/menace-under-otari-bestiary/viper-bb.json
  packs/menace-under-otari-bestiary/warg-bb.json
  packs/menace-under-otari-bestiary/wight-bb.json
  packs/menace-under-otari-bestiary/wolf-bb.json
  packs/menace-under-otari-bestiary/xulgath-leader-bb.json
  packs/menace-under-otari-bestiary/xulgath-warrior-bb.json
  packs/menace-under-otari-bestiary/zephyr-hawk-bb.json
  packs/menace-under-otari-bestiary/zombie-shambler-bb.json
Labels: pr: data update

#18678 Use ammo required getter when consuming ammo
  src/module/item/weapon/document.ts
Labels: pr: refactor

#18712 Fix dragging and dropping persistent damage
  src/scripts/system/dragstart-handler.ts
Labels: pr: bugfix

#18739 Add True Target spell effect
  packs/spell-effects/spell-effect-true-target.json
  packs/spells/7th-rank/true-target.json
Labels: pr: data update

#18737 Add True Dragon's Flight speeds
  packs/feats/ancestry/versatile-heritages/dragonblood/true-dragons-flight.json
Labels: pr: data update

#18743 Refresh all copies of True Target
  packs/blog-bestiary/foolish-housekeeping-and-other-articles/rt5rrmn.json
  packs/book-of-the-dead-bestiary/horde-lich.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/mage-of-many-styles.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/joon-seo.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/umbasi.json
  packs/pathfinder-bestiary-2/bastion-archon.json
  packs/pathfinder-bestiary-3/forest-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/sovereign-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-ancient.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/shianshi-waymaker.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/unshadowed-haibram.json
Labels: pr: data update

#18747 Change Barghest Acrobatics skill into Athletics
  packs/pathfinder-monster-core/barghest.json
Labels: pr: data update

#18740 Add Claws of the Tyrant feats to select Archetype Journal feats
  packs/journals/archetypes.json
Labels: pr: data update

#18749 Add inline healing, notes and effect to Lepidstadt Surgeon Dedication
  packs/feat-effects/effect-lepidstadt-surgeon-dedication-stop-bleeding.json
  packs/feats/archetype/lepidstadt-surgeon/lepidstadt-surgeon-dedication.json
  static/lang/re-en.json
Labels: pr: data update

#18750 Fix In Lightning, Life effect formula scaling and link effect in the feat
  packs/feat-effects/effect-in-lightning-life.json
  packs/feats/archetype/lepidstadt-surgeon/in-lightning-life.json
Labels: pr: data update

#18751 Condense Spiny Lodestone equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-spiny-lodestone-armor-greater.json
  packs/equipment-effects/effect-spiny-lodestone-armor-major.json
  packs/equipment-effects/effect-spiny-lodestone-armor.json
  packs/equipment-effects/effect-spiny-lodestone-weapon-greater.json
  packs/equipment-effects/effect-spiny-lodestone-weapon-major.json
  packs/equipment-effects/effect-spiny-lodestone-weapon.json
  packs/equipment/spiny-lodestone-greater.json
  packs/equipment/spiny-lodestone-major.json
Labels: pr: data update

#18745 Support description item alteration addendums in expandable self effect actions
  src/module/chat-message/listeners/cards.ts
  src/module/item/base/document.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/helpers.ts
  src/module/item/spell/document.ts
  src/styles/legacy/_chat.scss
  src/styles/ui/sidebar/chat/_index.scss
Labels: pr: enhancement, pr: refactor

#18753 Brush up multiclass dedication Archetype Journals and select feat text and sources
  packs/feats/archetype/barbarian/advanced-fury.json
  packs/feats/archetype/bard/bard-dedication.json
  packs/feats/archetype/champion/advanced-devotion.json
  packs/feats/archetype/cleric/cleric-dedication.json
  packs/feats/archetype/druid/druid-dedication.json
  packs/feats/archetype/fighter/fighter-dedication.json
  packs/feats/archetype/kineticist/kineticist-dedication.json
  packs/feats/archetype/magus/magus-dedication.json
  packs/feats/archetype/psychic/psychic-dedication.json
  packs/feats/archetype/ranger/master-spotter-ranger.json
  packs/feats/archetype/ranger/ranger-dedication.json
  packs/feats/archetype/rogue/rogue-dedication.json
  packs/feats/archetype/summoner/summoner-dedication.json
  packs/feats/archetype/thaumaturge/thaumaturge-dedication.json
  packs/feats/archetype/witch/witch-dedication.json
  packs/feats/archetype/wizard/wizard-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18763 Remove Fast Movement and Diverse Armor Expert feats
  packs/feats/archetype/champion/diverse-armor-expert.json
  packs/feats/class/barbarian/fast-movement.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#18761 Condense Stalk Goggles equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-stalk-goggles-greater.json
  packs/equipment-effects/effect-stalk-goggles-major.json
  packs/equipment-effects/effect-stalk-goggles.json
  packs/equipment/stalk-goggles-greater.json
  packs/equipment/stalk-goggles-major.json
  packs/gatewalkers-bestiary/book-1-the-seventh-arch/the-looksee-man.json
Labels: pr: data update

#18768 Add icons to Meteor Shield and Constricting Meteor items
  packs/equipment/constricting-meteor.json
  packs/equipment/meteor-shield.json
Labels: pr: data update

#18770 Fix a few enricher syntax typos in creatures and hazards
  packs/pathfinder-monster-core/living-tar.json
  packs/pathfinder-npc-core/ancestry-npcs/dwarf/dwarf-battalion.json
  packs/pfs-season-6-bestiary/6-00/abendegos-squall-1-2.json
  packs/pfs-season-6-bestiary/6-00/abendegos-squall-3-4.json
  packs/pfs-season-6-bestiary/6-00/abendegos-squall-5-6.json
  packs/pfs-season-6-bestiary/6-00/abendegos-squall-7-8.json
  packs/pfs-season-6-bestiary/6-12/thorns-of-the-rose-pit-5-6.json
  packs/pfs-season-6-bestiary/6-13/handheld-quaker-mk-2.json
  packs/war-of-immortals-bestiary/oliphaunt-of-jandelay.json
Labels: pr: data update

#18766 Add traits and publication sources to Class Archetype journal entries and brush up feats
  packs/feats/archetype/elementalist/elementalist-dedication.json
  packs/feats/archetype/flexible-spellcaster/flexible-spellcaster-dedication.json
  packs/feats/archetype/vindicator/call-the-hunt.json
  packs/feats/archetype/vindicator/disrupt-opposed-magic.json
  packs/feats/archetype/vindicator/interrogate.json
  packs/feats/archetype/vindicator/vindicator-dedication.json
  packs/feats/archetype/vindicator/vindicators-judgment.json
  packs/feats/archetype/warrior-of-legend/warrior-of-legend-dedication.json
  packs/feats/archetype/wellspring-mage/interfering-surge.json
  packs/feats/archetype/wellspring-mage/wellspring-mage-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18760 Add effects for Tripartite Omen, Vellumis Excision, and Cenotaph Stance
  packs/feat-effects/effect-tripartite-omen.json
  packs/feat-effects/effect-vellumis-excision.json
  packs/feat-effects/stance-cenotaph-stance.json
  packs/feats/archetype/halcyon-speaker/tripartite-omen.json
  packs/feats/archetype/halcyon-speaker/vellumis-excision.json
  packs/feats/archetype/knight-vigilant/preternatural-polish.json
  packs/feats/archetype/knight-vigilant/rallying-charge.json
  packs/feats/archetype/lastwall-sentry/cenotaph-stance.json
  packs/feats/archetype/magaambyan-attendant/faith-in-the-fallen.json
Labels: pr: data update

#18759 Add missing predicate to initiate benefit Grant Item in Thaumaturge implements
  packs/classfeatures/bell.json
  packs/classfeatures/lantern.json
  packs/classfeatures/mirror.json
  packs/classfeatures/regalia.json
  packs/classfeatures/wand.json
  packs/classfeatures/weapon.json
Labels: pr: data update

#18773 Update damage syntax for Dero's `Vulnerability to Sunlight`
  packs/pathfinder-monster-core/dero-magister.json
  packs/pathfinder-monster-core/dero-stalker.json
  packs/pathfinder-monster-core/dero-strangler.json
Labels: pr: data update

#18771 Extend Unstable note to actions that have the `unstable` trait and add notes RE to Inventor dedication
  packs/classfeatures/explode.json
  packs/feats/archetype/inventor/inventor-dedication.json
Labels: pr: data update

#18767 Remove `Fused Polearm`, `Polearm Tricks` and `School Counterspell` Runelord feats
  build/uuid-redirects.json
  packs/feats/archetype/runelord/fused-polearm.json
  packs/feats/archetype/runelord/polearm-tricks.json
  packs/feats/archetype/runelord/school-counterspell.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#18765 Fix missing `toggleable` in Furious Headbutt
  packs/bestiary-family-ability-glossary/beheaded/beheaded-furious-headbutt.json
Labels: pr: data update

#18764 Add effect link for Sinful Bite
  packs/bestiary-effects/effect-sinful-bite.json
  packs/pathfinder-monster-core/slothspawn.json
Labels: pr: data update

#18762 Brush up Tooth Tug effect
  packs/bestiary-effects/effect-pry.json
  packs/bestiary-effects/effect-tooth-tug.json
  packs/pathfinder-monster-core/tooth-fairy-swarm.json
  packs/pathfinder-monster-core/tooth-fairy.json
  packs/pfs-season-6-bestiary/quests/mischievous-plaguetooth.json
  packs/pfs-season-6-bestiary/quests/plaguetooth.json
  packs/triumph-of-the-tusk-bestiary/book-1-the-resurrection-flood/tooth-fairy-leader.json
  static/lang/re-en.json
Labels: pr: data update

#18724 Include Hero Point Deck rules in its journal
  packs/journals/hero-point-deck.json
Labels: pr: data update

#18725 Add initiative Note to Cloud of Allergens
  packs/blog-bestiary/foolish-housekeeping-and-other-articles/dust-bunny-swarm.json
Labels: pr: data update

#18731 Add predicate to Garrholdion's Belief Fortification
  packs/bestiary-effects/effect-belief-fortification-mark.json
  packs/bestiary-effects/effect-iron-command-extra-damage.json
  packs/bestiary-effects/effect-raise-defenses.json
  packs/blog-bestiary/foolish-housekeeping-and-other-articles/rt5rrmn.json
  packs/claws-of-the-tyrant-bestiary/2-ashes-for-ozem/commander-arsiella-dei.json
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/garrholdion.json
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/onturat.json
  packs/equipment-effects/effect-strength-through-pain.json
  packs/feat-effects/effect-a-little-bird-told-me.json
  packs/feats/archetype/halcyon-speaker/shattered-sacrament.json
  packs/feats/archetype/venture-gossip/a-little-bird-told-me.json
  static/lang/en.json
Labels: pr: data update

#18742 Adding missing category to Oceanius and Glory Arcely's Aura of Righteousness
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/oceanius-and-glory-arcely.json
Labels: pr: data update

#18754 Add some missing trailing periods to remaster changes for heritages and ancestries list
  packs/journals/remaster-changes.json
Labels: pr: data update

#18774 Change Redcap's halberd base damage to piercing
  packs/pathfinder-monster-core/redcap.json
Labels: pr: data update

#18755 Redirect FotRP Manananggal to LO:TXWG
  build/uuid-redirects.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/manananggal.json
  packs/tian-xia-world-guide-bestiary/manananggal.json
Labels: pr: data update

#18777 Only allow dragging to visible tokens
  src/scripts/hooks/drop-canvas-data.ts
Labels: pr: bugfix

#18784 Remove Cooperative Soul's prerequisite per Player Core update
  packs/feats/ancestry/human/cooperative-soul.json
Labels: pr: data update

#18787 Remove alignment traits from select NPC Core Actor
  packs/pathfinder-npc-core/ancestry-npcs/tripkee/tripkee-fiend-keeper.json
  packs/pathfinder-npc-core/criminal/assassin.json
  packs/pathfinder-npc-core/criminal/bandit.json
  packs/pathfinder-npc-core/criminal/burglar.json
  packs/pathfinder-npc-core/criminal/charlatan.json
  packs/pathfinder-npc-core/criminal/fence.json
  packs/pathfinder-npc-core/criminal/grave-robber.json
  packs/pathfinder-npc-core/criminal/master-of-disguise.json
  packs/pathfinder-npc-core/criminal/ruffian.json
  packs/pathfinder-npc-core/devotee/prophet.json
  packs/pathfinder-npc-core/devotee/rancorous-priesthood.json
  packs/pathfinder-npc-core/devotee/zealot-of-asmodeus.json
  packs/pathfinder-npc-core/explorer/poacher.json
  packs/pathfinder-npc-core/military/hellknight-cavalry-brigade.json
  packs/pathfinder-npc-core/mystic/demonologist.json
  packs/pathfinder-npc-core/mystic/necromancer.json
  packs/pathfinder-npc-core/official/archer-sentry.json
  packs/pathfinder-npc-core/official/barrister.json
  packs/pathfinder-npc-core/official/captain-of-the-guard.json
  packs/pathfinder-npc-core/official/city-guard-squadron.json
  packs/pathfinder-npc-core/official/executioner.json
  packs/pathfinder-npc-core/official/guard.json
  packs/pathfinder-npc-core/official/harbormaster.json
  packs/pathfinder-npc-core/official/jailer.json
  packs/pathfinder-npc-core/official/judge.json
  packs/pathfinder-npc-core/official/tax-collector.json
  packs/pathfinder-npc-core/official/warden.json
  packs/pathfinder-npc-core/official/watch-officer.json
  packs/pathfinder-npc-core/seafarer/pirate.json
  packs/pathfinder-npc-core/seafarer/ship-captain.json
  packs/pathfinder-npc-core/villain/champion-of-rovagug.json
  packs/pathfinder-npc-core/villain/despot.json
  packs/pathfinder-npc-core/villain/gang-leader.json
  packs/pathfinder-npc-core/villain/mastermind.json
  packs/pathfinder-npc-core/villain/reckless-scientist.json
  packs/pathfinder-npc-core/villain/saboteur.json
Labels: pr: data update

#18788 Correct `Robust Health` reference in `Paragon Medicine` feat
  packs/feats/skill/paragon-battle-medicine.json
Labels: pr: data update

#18785 Condense Thorn Triad equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-thorn-triad-armor-greater.json
  packs/equipment-effects/effect-thorn-triad-armor-major.json
  packs/equipment-effects/effect-thorn-triad-armor.json
  packs/equipment-effects/effect-thorn-triad-weapon-greater.json
  packs/equipment-effects/effect-thorn-triad-weapon-major.json
  packs/equipment-effects/effect-thorn-triad-weapon.json
  packs/equipment/thorn-triad-greater.json
  packs/equipment/thorn-triad-major.json
Labels: pr: data update

#18793 Add traits and sources to Mythic Destinies and dedication feats in Archetype Journal entries
  packs/feats/archetype/aldori-duelist/aldori-duelist-dedication.json
  packs/feats/archetype/apocalypse-rider/apocalypse-rider-dedication.json
  packs/feats/archetype/archfiend/archfiend-dedication.json
  packs/feats/archetype/ascended-celestial/ascended-celestial-dedication.json
  packs/feats/archetype/beast-lord/beast-lord-dedication.json
  packs/feats/archetype/broken-chain/broken-chain-dedication.json
  packs/feats/archetype/eternal-legend/eternal-legend-dedication.json
  packs/feats/archetype/godling/godling-dedication.json
  packs/feats/archetype/prophesied-monarch/prophesied-monarch-dedication.json
  packs/feats/archetype/wildspell/wildspell-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18794 Fix retrieving origin when saving against an actor without a token
  src/module/system/statistic/statistic.ts
Labels: pr: bugfix

#18795 Add missing properties to Morning Glow
  packs/equipment/morning-glow.json
Labels: pr: data update

#18791 Automate several Campfire Chronicler features
  packs/feat-effects/effect-cozy-campfire.json
  packs/feat-effects/effect-offer-story.json
  packs/feats/archetype/bellflower-tiller/garden-path.json
  packs/feats/archetype/bellflower-tiller/tillers-aid.json
  packs/feats/archetype/butterfly-blade/masterminds-eye.json
  packs/feats/archetype/campfire-chronicler/campfire-chronicler-dedication.json
  packs/feats/archetype/campfire-chronicler/flickering-stories.json
  packs/feats/archetype/campfire-chronicler/illuminating-stories.json
  packs/feats/archetype/campfire-chronicler/raging-stories.json
  packs/feats/archetype/campfire-chronicler/tales-of-the-road.json
  packs/feats/archetype/campfire-chronicler/the-dead-tell-tales.json
  static/lang/re-en.json
Labels: pr: data update

#18781 Add custom Immunity for Phantasmal Minion
  packs/pathfinder-bestiary/phantasmal-minion.json
  static/lang/re-en.json
Labels: pr: data update

#18776 Clean up rule elements on unstable function actions
  packs/classes/inventor.json
  packs/feats/archetype/inventor/inventor-dedication.json
  packs/feats/class/inventor/celestial-cacophony.json
  packs/feats/class/inventor/deep-freeze.json
  packs/feats/class/inventor/distracting-explosion.json
  packs/feats/class/inventor/duo-dragon-kick.json
  packs/feats/class/inventor/electrify-armor.json
  packs/feats/class/inventor/gigaton-strike.json
  packs/feats/class/inventor/guardian-lion-roar.json
  packs/feats/class/inventor/megaton-strike.json
  packs/feats/class/inventor/megavolt.json
  packs/feats/class/inventor/negate-damage.json
  packs/feats/class/inventor/xidao-sea-mine-drop.json
Labels: pr: data update

#18728 Add sanctification and conditional expert Stealth to Red Mantis Assassin dedication
  packs/feats/archetype/red-mantis-assassin/red-mantis-assassin-dedication.json
Labels: pr: data update

#18758 Implement Speak for the Gravelands with Geomancer archetype automation
  packs/feat-effects/effect-terrain-attunement-aquatic.json
  packs/feat-effects/effect-terrain-attunement-arctic.json
  packs/feat-effects/effect-terrain-attunement-gravelands.json
  packs/feat-effects/effect-terrain-attunement-mountain.json
  packs/feat-effects/effect-terrain-attunement-plains.json
  packs/feat-effects/effect-terrain-attunement-underground.json
  packs/feats/archetype/geomancer/attunement-shift.json
  packs/feats/archetype/geomancer/geomancer-dedication.json
  packs/feats/archetype/halcyon-speaker/speak-for-the-gravelands.json
  packs/feats/archetype/magaambyan-attendant/cautious-word.json
  packs/feats/archetype/magaambyan-attendant/crusaders-masquerade.json
  static/lang/re-en.json
Labels: pr: data update

#18796 Condense Thurible of Revelation equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-thurible-of-revelation-greater.json
  packs/equipment-effects/effect-thurible-of-revelation-moderate.json
  packs/equipment-effects/effect-thurible-of-revelation.json
  packs/equipment/thurible-of-revelation-greater.json
  packs/equipment/thurible-of-revelation-moderate.json
Labels: pr: data update

#18799 Refactor spell unprepare to be done by preparing a null spell
  src/module/actor/creature/sheet.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
Labels: pr: refactor

#18757 Show description item alterations for effect panel tooltips
  src/module/apps/effects-panel.ts
  src/styles/system/_effects-panel.scss
Labels: pr: enhancement

#18677 Convert roll inspector to application v2
  src/module/actor/character/apps/formula-picker/app.svelte
  src/module/apps/roll-inspector/app.svelte
  src/module/apps/roll-inspector/app.ts
  src/module/chat-message/document.ts
  src/module/chat-message/roll-inspector.ts
  src/styles/_colors.scss
  src/styles/ui/sidebar/chat/_index.scss
  src/styles/ui/sidebar/chat/_roll-inspector.scss
  static/templates/chat/roll-inspector.hbs
Labels: ui/ux

#18577 Preserve input focus in data-property and data-resource fields in re-render
  src/module/actor/sheet/base.ts
Labels: pr: enhancement

#18808 Correct Neshen's deity Anathema
  packs/deities/empyreal-lords/neshen.json
Labels: pr: data update

#18806 Remove unintended condition link in `Unfolding Tree House`
  packs/equipment/unfolding-tree-house.json
Labels: pr: data update

#18804 Correct Imeckus Stroon's spellcasting label
  packs/kingmaker-bestiary/imeckus-stroon.json
Labels: pr: data update

#17994 Add support for registering spells to staves
  build/lib/compendium-pack.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/equipment/data.ts
  src/module/item/equipment/document.ts
  src/module/item/equipment/sheet.ts
  src/module/item/physical/data.ts
  src/module/item/physical/document.ts
  src/module/item/physical/sheet.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/helpers.ts
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/scripts/register-templates.ts
  src/styles/item/_abc-sheet.scss
  src/styles/item/_index.scss
  src/styles/item/_weapon-sheet.scss
  static/lang/en.json
  static/templates/items/equipment-details.hbs
  static/templates/items/partials/staff-description-append.hbs
  static/templates/items/partials/staff-spells.hbs
  static/templates/items/weapon-details.hbs
Labels: pr: enhancement

#18803 Add traits and source reference to select Dedication feats, and additional Rules entries to the Archetype Journals
  packs/feats/archetype/alkenstar-agent/alkenstar-agent-dedication.json
  packs/feats/archetype/alter-ego/alter-ego-dedication.json
  packs/feats/archetype/animal-trainer/animal-trainer-dedication.json
  packs/feats/archetype/bellflower-tiller/bellflower-dedication.json
  packs/feats/archetype/bright-lion/bright-lion-dedication.json
  packs/feats/archetype/butterfly-blade/butterfly-blade-dedication.json
  packs/feats/archetype/captivator/captivator-dedication.json
  packs/feats/archetype/cathartic-mage/cathartic-mage-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18798 Brush up Memory Maelstrom NPC ability
  packs/pathfinder-bestiary-3/arboreal-archive.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/dimari-diji.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/old-thornbarker.json
Labels: pr: data update

#18811 Fix action type and cost of Aiudara Wraith's Dimensional Shunt
  packs/age-of-ashes-bestiary/book-6-broken-promises/aiudara-wraith.json
Labels: pr: data update

#18816 Remove `attack` trait from Elemental Counter cantrip
  packs/spells/cantrip/elemental-counter.json
Labels: pr: data update

#18797 Add predicate to `Magnetic Shot`'s circumstance bonus
  packs/equipment/magnetic-shot-greater.json
  packs/equipment/magnetic-shot-lesser.json
  packs/equipment/magnetic-shot-moderate.json
Labels: pr: data update

#18823 Add missing price Aurochs Jerky
  packs/equipment/aurochs-jerky.json
Labels: pr: data update

#18825 Fix placement of vite HMR server configuration
  vite.config.ts
Labels: pr: bugfix

#18841 Include minor refactors from staff PR
  src/module/item/base/sheet/sheet.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/helpers.ts
  src/scripts/register-templates.ts
  static/lang/en.json
Labels: pr: refactor

#18836 Correct `Effect: Renewed Vigor` choice set prompt
  packs/feat-effects/effect-renewed-vigor.json
  static/lang/re-en.json
Labels: pr: data update

#18821 Remove Produce Flame Cantrip
  packs/age-of-ashes-bestiary/book-2-cult-of-cinders/hezle.json
  packs/age-of-ashes-bestiary/book-6-broken-promises/ilgreth.json
  packs/agents-of-edgewatch-bestiary/book-3-all-or-nothing/svartalfar-killer.json
  packs/equipment/cantrip-deck-full-pack.json
  packs/equipment/dragons-eye-charm.json
  packs/equipment/flaming-star-greater.json
  packs/equipment/flaming-star-major.json
  packs/equipment/flaming-star.json
  packs/equipment/primordial-flame.json
  packs/equipment/spellstriker-staff-greater.json
  packs/equipment/spellstriker-staff-major.json
  packs/equipment/spellstriker-staff.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/yaganty.json
  packs/feat-effects/effect-rampaging-form.json
  packs/feats/ancestry/human/dragon-spit.json
  packs/feats/ancestry/kitsune/rampaging-form.json
  packs/feats/ancestry/versatile-heritages/naari/inner-fire-naari.json
  packs/kingmaker-bestiary/imeckus-stroon.json
  packs/pfs-season-1-bestiary/1-16/lelzeshin-tier-3-4.json
  packs/pfs-season-1-bestiary/1-16/lelzeshin-tier-5-6.json
  packs/pfs-season-2-bestiary/2-16/corvius-vayn-5-6.json
  packs/pfs-season-2-bestiary/2-16/corvius-vayn-7-8.json
  packs/quest-for-the-frozen-flame-bestiary/book-2-lost-mammoth-valley/venexus.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/ivarsa.json
  packs/spell-effects/spell-effect-fiery-body-9th-level.json
  packs/spells/cantrip/produce-flame.json
  packs/stolen-fate-bestiary/book-1-the-choosing/arodeth.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/onyiji.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/terwa-star-reader.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/reborn-sun-mage.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/reborn-sun-warrior.json
Labels: pr: data update

#18827 Brush up Body of Air description
  packs/feats/class/kineticist/body-of-air.json
Labels: pr: data update

#18829 Correct Inflammation Flask's damage type and update effect automation
  packs/equipment-effects/effect-inflammation-flask.json
  packs/equipment/inflammation-flask-greater.json
  packs/equipment/inflammation-flask-lesser.json
  packs/equipment/inflammation-flask-major.json
  packs/equipment/inflammation-flask-moderate.json
Labels: pr: data update

#18838 Remove Enlarge from Major Clay Sphere
  packs/equipment/clay-sphere-major.json
Labels: pr: data update

#18842 Add effect for Yurgak's Consume Flesh
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/zeal-damned-ghoul.json
  packs/bestiary-effects/effect-consume-flesh.json
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/yurgak.json
Labels: pr: data update

#18844 Update Whirlwind area to be cylinder
  packs/spells/8th-rank/whirlwind.json
Labels: pr: data update

#18843 Correct usage of Rending Gauntlets
  packs/equipment/rending-gauntlets-greater.json
  packs/equipment/rending-gauntlets-lesser.json
  packs/equipment/rending-gauntlets-moderate.json
Labels: pr: data update

#18830 Relabel Rallying Charge feats to indicate the archetypes
  packs/feat-effects/effect-rallying-charge-marshal.json
  packs/feats/archetype/knight-vigilant/rallying-charge-knight-vigilant.json
  packs/feats/archetype/marshal/rallying-charge-marshal.json
  packs/journals/archetypes.json
Labels: pr: data update

#18824 Add effects for Aurochs Jerky and Cindergrass Cloak
  packs/equipment-effects/effect-aurochs-endurance.json
  packs/equipment-effects/effect-aurochs-jerky.json
  packs/equipment-effects/effect-shed-cinders.json
  packs/equipment/aurochs-jerky.json
  packs/equipment/cindergrass-cloak.json
Labels: pr: data update

#18846 Refine styling of roll inspector
  src/module/apps/roll-inspector/app.svelte
  src/styles/_colors.scss
Labels: ui/ux

#18845 Support multiple token marks instead of overriding them
  src/module/actor/roll-context/base.ts
  src/module/rules/rule-element/token-mark/rule-element.ts
  src/module/rules/synthetics.ts
Labels: pr: bugfix

#18815 Add traits and sources to select Archetype journal entries and feats
  packs/feats/archetype/cavalier/cavaliers-banner.json
  packs/feats/archetype/chronoskimmer/chronoskimmer-dedication.json
  packs/feats/archetype/clockwork-reanimator/clockwork-reanimator-dedication.json
  packs/feats/archetype/corpse-tender/corpse-tender-dedication.json
  packs/feats/archetype/crystal-keeper/crystal-keeper-dedication.json
  packs/feats/archetype/dragon-disciple/dragon-disciple-dedication.json
  packs/feats/archetype/drow-shootist/drow-shootist-dedication.json
  packs/feats/archetype/edgewatch-detective/edgewatch-detective-dedication.json
  packs/feats/archetype/eldritch-archer/impossible-volley-eldritch-archer.json
  packs/feats/archetype/eldritch-researcher/eldritch-researcher-dedication.json
  packs/feats/archetype/exorcist/exorcist-dedication.json
  packs/feats/archetype/firebrand-braggart/firebrand-braggart-dedication.json
  packs/feats/archetype/folklorist/folklorist-dedication.json
  packs/feats/class/shared-class-feats/impossible-volley.json
  packs/journals/archetypes.json
Labels: pr: data update

#18850 Remove `free hand` trait from Grasp of Droskar weapon
  packs/equipment/grasp-of-droskar.json
Labels: pr: data update

#18852 Avoid persisting automated weapon property runes when closing the item sheet
  src/module/item/weapon/sheet.ts
  src/styles/_colors.scss
  src/styles/actor/_index.scss
  src/styles/actor/army/_index.scss
  src/styles/actor/npc/_index.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/actor/vehicle/_index.scss
  src/styles/item/_index.scss
  static/templates/items/weapon-details.hbs
Labels: pr: bugfix, ui/ux

#18849 Fix trick magic item spell DC when using trained or expert skills
  src/module/system/statistic/statistic.ts
Labels: pr: bugfix

#18851 Condense Tome of Restorative Cleansing's equipment effect
  build/uuid-redirects.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing-greater.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing-lesser.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing-moderate.json
  packs/equipment-effects/effect-tome-of-restorative-cleansing.json
  packs/equipment/tome-of-restorative-cleansing-greater.json
  packs/equipment/tome-of-restorative-cleansing-lesser.json
  packs/equipment/tome-of-restorative-cleansing-moderate.json
Labels: pr: data update

#18855 Correct `Leng Envoy` Tongues spell tag
  packs/kingmaker-bestiary/leng-envoy.json
Labels: pr: data update

#18531 Support delta inputs for health and shield hp in the character sheet
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/helpers.ts
  static/templates/actors/character/partials/header.hbs
  static/templates/actors/character/partials/sidebar.hbs
Labels: pr: enhancement

#18862 Correct typo in `Wellspring Magic` class feature choice set flag
  packs/classfeatures/wellspring-magic.json
Labels: pr: data update

#18860 Condense Trinity Geode equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-trinity-geode-armor-greater.json
  packs/equipment-effects/effect-trinity-geode-armor-major.json
  packs/equipment-effects/effect-trinity-geode-armor.json
  packs/equipment-effects/effect-trinity-geode-weapon-greater.json
  packs/equipment-effects/effect-trinity-geode-weapon-major.json
  packs/equipment-effects/effect-trinity-geode-weapon.json
  packs/equipment/trinity-geode-greater.json
  packs/equipment/trinity-geode-major.json
Labels: pr: data update

#18858 Add critical specialization automation to Spriggan Warlord's Warlord's Training
  packs/kingmaker-bestiary/agai.json
  packs/pathfinder-bestiary-2/spriggan-warlord.json
Labels: pr: data update

#18856 Add traits and sources to select Dedication entries in the Archetype journal
  packs/feats/archetype/clockwork-reanimator/clockwork-reanimator-dedication.json
  packs/feats/archetype/dragon-disciple/dragon-disciple-dedication.json
  packs/feats/archetype/game-hunter/game-hunter-dedication.json
  packs/feats/archetype/geomancer/geomancer-dedication.json
  packs/feats/archetype/ghost-eater/ghost-eater-dedication.json
  packs/feats/archetype/ghost-hunter/ghost-hunter-dedication.json
  packs/feats/archetype/golden-league-xun/golden-league-xun-dedication.json
  packs/feats/archetype/golem-grafter/golem-grafter-dedication.json
  packs/feats/archetype/gray-gardener/executioner-weapon-training.json
  packs/feats/archetype/gray-gardener/reminder-of-the-greater-fear.json
  packs/feats/archetype/halcyon-speaker/halcyon-speaker-dedication.json
  packs/feats/archetype/hallowed-necromancer/hallowed-necromancer-dedication.json
  packs/feats/archetype/hellknight-armiger/hellknight-armiger-dedication.json
  packs/feats/archetype/hellknight-signifer/hellknight-signifer-dedication.json
  packs/feats/archetype/hellknight/hellknight-dedication.json
  packs/feats/archetype/horizon-walker/horizon-walker-dedication.json
  packs/feats/archetype/jalmeri-heavenseeker/jalmeri-heavenseeker-dedication.json
  packs/feats/archetype/kitharodian-actor/kitharodian-actor-dedication.json
  packs/feats/archetype/knight-reclaimant/knight-reclaimant-dedication.json
  packs/feats/archetype/knight-vigilant/knight-vigilant-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18848 Add custom resistance for Armag Twice-Born
  packs/kingmaker-bestiary/armag-twice-born.json
  static/lang/re-en.json
Labels: pr: data update

#18820 Add automation for Magus's Analysis
  packs/feats/class/magus/maguss-analysis.json
Labels: pr: data update

#18872 Correct size on Metal Scamp actor
  packs/rage-of-elements-bestiary/metal-scamp.json
Labels: pr: data update

#18869 Fix DC and damage of Minognos-Ushad's Wyvern Venom
  packs/kingmaker-bestiary/minognos-ushad.json
Labels: pr: data update

#18870 Add effect for Glimpse Vulnerability
  packs/actions/glimpse-vulnerability.json
  packs/feat-effects/effect-glimpse-vulnerability.json
Labels: pr: data update

#18873 Fix action cost of Breathe Shrapnel
  packs/pfs-season-5-bestiary/5-10/metal-rascal.json
  packs/rage-of-elements-bestiary/metal-scamp.json
Labels: pr: data update

#18865 Fill out more v13 `ApplicationV2` types
  src/module/migration/migrations/726-journal-setting.ts
  src/module/scene/sheet.ts
  src/scripts/hooks/close-combat-tracker-config.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-combat-tracker-config.ts
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/api/document-sheet.d.mts
  types/foundry/client/applications/apps/combat-tracker-config.d.mts
  types/foundry/client/applications/apps/compendium-art-config.d.mts
  types/foundry/client/applications/apps/document-ownership.d.mts
  types/foundry/client/applications/apps/document-sheet-config.d.mts
  types/foundry/client/applications/apps/file-picker.d.mts
  types/foundry/client/applications/apps/grid-config.d.mts
  types/foundry/client/applications/apps/permission-config.d.mts
  types/foundry/client/applications/handlebars.d.mts
  types/foundry/client/applications/html-secret.d.mts
  types/foundry/client/applications/sheets/item-sheet.d.mts
  types/foundry/client/applications/sheets/scene-config.d.mts
  types/foundry/client/canvas/board.d.mts
  types/foundry/client/canvas/placeables/token.d.mts
  types/foundry/client/helpers/hooks.d.mts
Labels: pr: types update, pr: foundry v13

#18875 Fill in more sidebar directory types, fix setting return types
  src/global.ts
  src/module/actor/party/kingdom/chat.ts
  src/module/actor/sheet/base.ts
  src/module/actor/sheet/data-types.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/apps/sidebar/chat-log.ts
  src/module/canvas/token/object.ts
  src/module/chat-message/data.ts
  src/module/item/base/sheet/rule-element-form/base.ts
  src/module/item/base/sheet/sheet.ts
  src/scripts/hooks/hotbar-drop.ts
  src/scripts/hooks/index.ts
  src/scripts/hooks/render-chat-popout.ts
  static/templates/dice/damage-roll.hbs
  types/foundry/client/applications/_types.d.mts
  types/foundry/client/applications/sidebar/_module.d.mts
  types/foundry/client/applications/sidebar/document-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/actor-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/cards-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/combat-tracker.d.mts
  types/foundry/client/applications/sidebar/tabs/compendium-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/journal-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/macro-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/roll-table-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/scene-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/settings.d.mts
  types/foundry/client/applications/ui/hotbar.d.mts
  types/foundry/client/appv1/api/document-sheet-v1.d.mts
  types/foundry/client/appv1/api/form-application-v1.d.mts
  vite.config.ts
Labels: pr: foundry v13

#18877 Brush up Mage Killer
  packs/pathfinder-npc-core/mercenary/mage-killer.json
Labels: pr: data update

#18882 Fix some rendering issues with chat log and damage-roll tooltips
  src/module/apps/sidebar/chat-log.ts
  src/scripts/ui/user-visibility.ts
  src/styles/ui/sidebar/chat/_damage.scss
  src/styles/ui/sidebar/chat/_index.scss
  static/templates/actors/actions/simple/chat-message-flavor.hbs
  static/templates/dice/damage-roll.hbs
  static/templates/dice/damage-tooltip.hbs
Labels: pr: foundry v13

#18881 Remove colors and functions intended to be removed for V13
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/document.ts
  src/styles/_colors.scss
Labels: pr: foundry v13

#18878 Fix several isses in Shades of Blood actors
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/alzira-mustanir.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/animal-pit.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/camazotzs-swarm.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/netherworld-sprigjack.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/netherworld-vampire-bat-swarm.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/trapped-gate.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/danva.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/erissa.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/grusk-the-pusk.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/kalakaigh.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/nalushae-meronis.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/shankfingers.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/vikandian.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/vinn-karskell.json
  static/lang/re-en.json
Labels: pr: data update

#18886 Update Effects Panel to AppV2 and fix inline rolls styling
  src/module/apps/effects-panel.ts
  src/scripts/hooks/canvas-ready.ts
  src/styles/_colors.scss
  src/styles/_globals.scss
  src/styles/system/_effects-panel.scss
  static/templates/system/effects/panel.hbs
Labels: pr: foundry v13

#18883 Add traits and sources to additional Archetype journal entries
  packs/feats/archetype/lastwall-sentry/lastwall-sentry-dedication.json
  packs/feats/archetype/lion-blade/lion-blade-dedication.json
  packs/feats/archetype/living-monolith/living-monolith-dedication.json
  packs/feats/archetype/living-vessel/living-vessel-dedication.json
  packs/feats/archetype/loremaster/loremaster-dedication.json
  packs/feats/archetype/magic-warrior/magic-warrior-dedication.json
  packs/feats/archetype/mammoth-lord/mammoth-lord-dedication.json
  packs/feats/archetype/mind-smith/mind-smith-dedication.json
  packs/feats/archetype/nantambu-chime-ringer/nantambu-chime-ringer-dedication.json
  packs/feats/archetype/oatia-skysage/oatia-skysage-dedication.json
  packs/feats/archetype/oozemorph/oozemorph-dedication.json
  packs/feats/archetype/pactbinder/pactbinder-dedication.json
  packs/feats/archetype/pactbound-initiate/pactbound-dedication.json
  packs/feats/archetype/pathfinder-agent/pathfinder-agent-dedication.json
  packs/feats/archetype/provocator/provocator-dedication.json
  packs/feats/archetype/psychic-duelist/psychic-duelist-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18876 Fill out v13 `ControlsLayer` and `TokenLayer` types
  types/foundry/client/_types.d.mts
  types/foundry/client/applications/hud/placeable-hud.d.mts
  types/foundry/client/applications/hud/token-hud.d.mts
  types/foundry/client/canvas/containers/elements/cursor.d.mts
  types/foundry/client/canvas/containers/elements/grid-highlight.d.mts
  types/foundry/client/canvas/layers/base/canvas-layer.d.mts
  types/foundry/client/canvas/layers/base/interaction-layer.d.mts
  types/foundry/client/canvas/layers/base/placeables-layer.d.mts
  types/foundry/client/canvas/layers/controls.d.mts
  types/foundry/client/canvas/layers/grid.d.mts
  types/foundry/client/canvas/layers/tokens.d.mts
  types/foundry/client/canvas/placeables/token.d.mts
  types/foundry/client/canvas/rendering/filters/transition.d.mts
  types/foundry/client/config.d.mts
Labels: pr: types update, pr: foundry v13

#18897 Fix minor styling issues for v13
  src/styles/_tags.scss
  src/styles/actor/_inventory.scss
  src/styles/actor/familiar/_index.scss
  src/styles/actor/hazard/_index.scss
  src/styles/actor/hazard/_sidebar.scss
  src/styles/actor/loot/_index.scss
  src/styles/actor/npc/_index.scss
  src/styles/actor/npc/_sidebar.scss
  src/styles/actor/party/_index.scss
  src/styles/actor/vehicle/_index.scss
  src/styles/item/_header.scss
  src/styles/item/_sidebar.scss
Labels: ui/ux

#18896 Add effect for Blessed Coins
  packs/campaign-effects/season-of-ghosts/effect-blessed-coins.json
  packs/campaign-effects/season-of-ghosts/effect-spirit-power-passion.json
Labels: pr: data update

#18895 Correct incorrect change of `Feat` to `Level` in Archetype journal entries
  packs/journals/archetypes.json
Labels: pr: data update

#18889 Tidy description formatting of Nugrah's Swift Summon
  packs/kingmaker-bestiary/nugrah.json
Labels: pr: data update

#18900 Update party folders for V13
  src/module/apps/sidebar/actor-directory.ts
  src/scripts/hooks/ready.ts
  src/styles/ui/sidebar/_actor-directory.scss
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/sidebar/document-directory.d.mts
Labels: pr: foundry v13

#18899 Fill out remaining `PlaceablesLayer` types
  types/foundry/client/applications/hud/container.d.mts
  types/foundry/client/applications/ui/region-legend.d.mts
  types/foundry/client/applications/ux/drag-drop.d.mts
  types/foundry/client/canvas/layers/drawings.d.mts
  types/foundry/client/canvas/layers/lighting.d.mts
  types/foundry/client/canvas/layers/notes.d.mts
  types/foundry/client/canvas/layers/region.d.mts
  types/foundry/client/canvas/layers/sounds.d.mts
  types/foundry/client/canvas/layers/templates.d.mts
  types/foundry/client/canvas/layers/tiles.d.mts
  types/foundry/client/canvas/layers/walls.d.mts
  types/foundry/client/canvas/placeables/drawing.d.mts
  types/foundry/client/canvas/placeables/light.d.mts
  types/foundry/client/canvas/placeables/note.d.mts
  types/foundry/client/canvas/placeables/region.d.mts
  types/foundry/client/canvas/placeables/sound.d.mts
  types/foundry/client/canvas/placeables/template.d.mts
  types/foundry/client/canvas/placeables/tile.d.mts
  types/foundry/client/canvas/placeables/wall.d.mts
  types/foundry/client/documents/abstract/canvas-document.d.mts
  types/foundry/client/documents/drawing.d.mts
Labels: pr: types update, pr: foundry v13

#18920 Update `CompendiumBrowser` for v13
  src/module/apps/compendium-browser/components/filters.svelte
  src/module/apps/compendium-browser/components/filters/filter-container.svelte
  src/module/apps/compendium-browser/components/filters/partials/clear-filter-button.svelte
  src/module/apps/compendium-browser/components/filters/traits.svelte
Labels: pr: foundry v13

#18904 fix format of Activate in a few items without <strong>
  packs/curtain-call-bestiary/book-3-bring-the-house-down/blackfingers.json
  packs/curtain-call-bestiary/book-3-bring-the-house-down/reaper-of-reputation.json
  packs/equipment/ashes-of-the-war-god.json
  packs/equipment/comprehension-elixir-greater.json
  packs/equipment/comprehension-elixir-lesser.json
  packs/equipment/cooling-elixir-greater.json
  packs/equipment/cooling-elixir-lesser.json
  packs/equipment/cooling-elixir-moderate.json
  packs/equipment/diglys-oil-of-sympathy-greater.json
  packs/equipment/diglys-oil-of-sympathy-lesser.json
  packs/equipment/diglys-oil-of-sympathy-major.json
  packs/equipment/diglys-oil-of-sympathy-minor.json
  packs/equipment/diglys-oil-of-sympathy-moderate.json
  packs/equipment/essence-of-mandragora.json
  packs/equipment/sportlebore-capsule.json
  packs/equipment/tatzlwyrms-gasp.json
  packs/equipment/vyres-bliss.json
  packs/pathfinder-society-boons/radiant-wayfinder.json
Labels: pr: data update

#18916 Add Hardshell Surki Carapace Armor and link to heritage
  packs/equipment/hardshell-surki-carapace.json
  packs/heritages/surki/hardshell-surki.json
Labels: pr: data update

#18907 Fix senses of Overgrown Viper Vine
  packs/kingmaker-bestiary/overgrown-viper-vine.json
Labels: pr: data update

#18901 Add traits and sources to additional Archetype journal entries
  packs/feats/archetype/reanimator/reanimator-dedication.json
  packs/feats/archetype/runescarred/runescarred-dedication.json
  packs/feats/archetype/scrollmaster/scrollmaster-dedication.json
  packs/feats/archetype/scrounger/expert-disassembly.json
  packs/feats/archetype/shadowcaster/shadowcaster-dedication.json
  packs/feats/archetype/shadowdancer/shadowdancer-dedication.json
  packs/feats/archetype/shieldmarshal/shieldmarshal-dedication.json
  packs/feats/archetype/sixth-pillar/sixth-pillar-dedication.json
  packs/feats/archetype/sleepwalker/sleepwalker-dedication.json
  packs/feats/archetype/snarecrafter/plentiful-snares.json
  packs/journals/archetypes.json
Labels: pr: data update

#18922 Move Fox Arson to use item bonus instead of potency rune
  packs/feats/ancestry/kitsune/fox-arson.json
Labels: pr: data update

#18919 Fix toggling of modifiers in `DamageModifierDialog` and `CheckModifiersDialog`
  src/module/apps/compendium-browser/components/filters/traits.svelte
  src/styles/ui/_roll-modifiers-dialog.scss
  static/templates/chat/check-modifiers-dialog.hbs
  static/templates/chat/damage/damage-modifier-dialog.hbs
Labels: pr: foundry v13

#18903 Fix missing localized string for NPC Shield Max HP
  static/templates/actors/npc/partials/sidebar.hbs
Labels: pr: bugfix

#18924 Brush up some NPC Core actors
  packs/pathfinder-npc-core/ancestry-npcs/dwarf/dwarf-smith.json
  packs/pathfinder-npc-core/ancestry-npcs/elf/aiuvarin-translator.json
  packs/pathfinder-npc-core/ancestry-npcs/gnome/gnome-conservationist.json
  packs/pathfinder-npc-core/ancestry-npcs/goblin/goblin-chef.json
  packs/pathfinder-npc-core/ancestry-npcs/leshy/gourd-leshy-witch.json
  packs/pathfinder-npc-core/ancestry-npcs/leshy/root-leshy-groundskeeper.json
  packs/pathfinder-npc-core/criminal/loan-shark.json
  packs/pathfinder-npc-core/devotee/abbot-of-abadar.json
  packs/pathfinder-npc-core/devotee/pilgrim-of-irori.json
  packs/pathfinder-npc-core/devotee/prophet.json
  packs/pathfinder-npc-core/downtrodden/drunkard.json
  packs/pathfinder-npc-core/engineer/artillerist.json
  packs/pathfinder-npc-core/engineer/demolitionist.json
  packs/pathfinder-npc-core/engineer/driver.json
  packs/pathfinder-npc-core/engineer/dynamo.json
  packs/pathfinder-npc-core/engineer/juggernaut.json
  packs/pathfinder-npc-core/engineer/mechanic.json
  packs/pathfinder-npc-core/engineer/rocketeer.json
  packs/pathfinder-npc-core/seafarer/subaquatic-marauder.json
  packs/pfs-season-1-bestiary/1-17/webhekiz-3-4.json
  packs/pfs-season-1-bestiary/1-17/webhekiz-5-6.json
  static/lang/re-en.json
Labels: pr: data update

#18902 Remove Speedy Rituals feat
  packs/feats/archetype/ritualist/speedy-rituals.json
  packs/journals/remaster-changes.json
Labels: pr: data update

#18927 Remove `TinyMCE` dependency and add stubbed `TinyMCE` types
  package-lock.json
  package.json
  src/module/item/base/sheet/sheet.ts
  types/foundry/client/applications/ux/form-data-extended.d.mts
  types/foundry/client/appv1/api/document-sheet-v1.d.mts
  types/foundry/client/appv1/api/form-application-v1.d.mts
  types/foundry/client/appv1/sheets/journal-page-sheet.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/global.d.mts
  types/foundry/tinymce-stub.d.mts
Labels: pr: foundry v13

#18936 Fix `CompendiumDirectoryPF2e` drag selector
  src/module/apps/sidebar/compendium-directory.ts
Labels: pr: foundry v13

#18940 Restore erroneously removed `buttons` property in xp macro dialog
  src/scripts/macros/xp/dialog.ts
  types/foundry/client/appv1/api/dialog-v1.d.mts
Labels: pr: foundry v13

#18942 Update legacy Guiding Words effect to use TokenMark
  packs/bestiary-effects/effect-guiding-words.json
  packs/pfs-season-2-bestiary/2-04/tewakam-nekotek-3-4.json
  packs/pfs-season-2-bestiary/2-04/tewakam-nekotek-5-6.json
  packs/quest-for-the-frozen-flame-bestiary/book-2-lost-mammoth-valley/varilyn-vare-eridge.json
Labels: pr: data update

#18930 Add source and traits to additional Archetype Journal entries
  packs/feats/archetype/soulforger/soulforger-dedication.json
  packs/feats/archetype/spellmaster/spellmaster-dedication.json
  packs/feats/archetype/staff-acrobat/staff-acrobat-dedication.json
  packs/feats/archetype/stalwart-defender/stalwart-defender-dedication.json
  packs/feats/archetype/stone-brawler/stone-brawler-dedication.json
  packs/feats/archetype/stonebound/stonebound-dedication.json
  packs/feats/archetype/student-of-perfection/student-of-perfection-dedication.json
  packs/feats/archetype/swordmaster/swordmaster-dedication.json
  packs/feats/archetype/time-mage/time-mage-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18945 Fix penalties set to critical false when rolling critical damage
  src/module/system/damage/formula.ts
Labels: pr: bugfix

#18932 Condense equipment effects for Warding Statuette and Wyrm Claw
  build/uuid-redirects.json
  packs/equipment-effects/effect-warding-statuette-armor-greater.json
  packs/equipment-effects/effect-warding-statuette-armor.json
  packs/equipment-effects/effect-warding-statuette-weapon.json
  packs/equipment-effects/effect-wyrm-claw-armor-greater.json
  packs/equipment-effects/effect-wyrm-claw-armor-major.json
  packs/equipment-effects/effect-wyrm-claw-armor.json
  packs/equipment/warding-statuette-greater.json
  packs/equipment/wyrm-claw-greater.json
  packs/equipment/wyrm-claw-major.json
Labels: pr: data update

#18944 Add traits and publication sources to select Archetype Journal entries
  packs/feats/archetype/turpin-rowe-lumberjack/turpin-rowe-lumberjack-dedication.json
  packs/feats/archetype/twilight-speaker/twilight-speaker-dedication.json
  packs/feats/archetype/undead-master/undead-master-dedication.json
  packs/feats/archetype/verduran-shadow/verduran-shadow-dedication.json
  packs/feats/archetype/viking/second-shield.json
  packs/feats/archetype/viking/viking-weapon-familiarity.json
  packs/feats/archetype/worm-caller/worm-caller-dedication.json
  packs/feats/archetype/wrestler/form-lock.json
  packs/feats/archetype/zephyr-guard/zephyr-guard-dedication.json
  packs/journals/archetypes.json
Labels: pr: data update

#18946 Brush up some NPC Core actors
  packs/bestiary-effects/effect-cleansing-earth.json
  packs/pathfinder-npc-core/healer/apothecary.json
  packs/pathfinder-npc-core/healer/humanitarian-hermit.json
  packs/pathfinder-npc-core/healer/local-herbalist.json
  packs/pathfinder-npc-core/healer/peerless-healer.json
  packs/pathfinder-npc-core/healer/physician.json
  packs/pathfinder-npc-core/healer/plague-doctor.json
  packs/pathfinder-npc-core/healer/surgeon.json
  packs/pathfinder-npc-core/healer/therapeutic-healer.json
Labels: pr: data update

#18943 Add holy trait to Anima Invocation spell effect additional damage
  packs/spell-effects/spell-effect-anima-invocation.json
Labels: pr: data update

#18947 Add effect to `Conductive Sphere` Kineticist feat
  packs/feat-effects/effect-conductive-sphere.json
  packs/feats/class/kineticist/conductive-sphere.json
  static/lang/re-en.json
Labels: pr: data update

#18948 Fix glow effect and label of aura effects
  src/styles/system/_effects-panel.scss
Labels: pr: bugfix

#18949 Restore functionality of system `TokenConfig` subclass
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/apps/sidebar/compendium-directory.ts
  src/module/canvas/group/environment.ts
  src/module/encounter/document.ts
  src/module/scene/token-document/sheet.ts
  src/module/system/text-editor.ts
  src/scripts/hooks/setup.ts
  src/styles/scene/_token-config.scss
  src/styles/ui/sidebar/chat/_damage.scss
  static/lang/en.json
  static/templates/scene/token/appearance.hbs
  static/templates/scene/token/partials/appearance.hbs
  static/templates/scene/token/partials/identity.hbs
  static/templates/scene/token/partials/lighting.hbs
  static/templates/scene/token/sheet.hbs
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/sheets/module.d.mts
  types/foundry/client/applications/sheets/token/mixin.mts
  types/foundry/client/applications/sheets/token/prototype-config.d.mts
  types/foundry/client/applications/sheets/token/token-config.d.mts
  types/foundry/client/canvas/groups/_module.d.mts
  types/foundry/client/helpers/client-settings.d.mts
  types/foundry/common/data/data.d.mts
  types/foundry/tsconfig.json
  vite.config.ts
Labels: pr: foundry v13

#18950 Fix display in chat of healing-only rolls
  src/styles/ui/sidebar/chat/_damage.scss
  static/templates/dice/damage-roll.hbs
Labels: pr: bugfix, pr: foundry v13

#18951 Fix display of `@Template` link icons
  src/styles/_globals.scss
Labels: pr: foundry v13

#18952 Remove `property1` and `bonusDamage` fields from `WeaponSystemData`
  src/module/item/weapon/data.ts
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/module/system/damage/weapon.ts
  static/lang/en.json
  static/template.json
  static/templates/items/weapon-details.hbs
Labels: pr: foundry v13

#18954 Remove babele double-hook
  src/scripts/hooks/ready.ts
Labels: pr: foundry v13

#18953 Fill out more v13 types
  types/foundry/client/applications/ux/_module.d.mts
  types/foundry/client/applications/ux/draggable.d.mts
  types/foundry/client/applications/ux/html-secret.d.mts
  types/foundry/client/applications/ux/prosemirror-editor.d.mts
  types/foundry/client/applications/ux/tabs.d.mts
  types/foundry/client/appv1/api/application-v1.d.mts
  types/foundry/client/appv1/api/document-sheet-v1.d.mts
  types/foundry/client/appv1/api/form-application-v1.d.mts
  types/foundry/client/appv1/sheets/adventure-importer.d.mts
  types/foundry/client/appv1/sheets/journal-page-sheet.d.mts
  types/foundry/client/appv1/sheets/journal-sheet.d.mts
Labels: pr: foundry v13

#18955 Fix some reported v13 issues
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/item/base/document.ts
  src/module/rules/rule-element/aura.ts
  src/module/rules/rule-element/token-image.ts
  src/scripts/register-templates.ts
  static/templates/items/rules/token-light.hbs
  types/foundry/client/helpers/media/image-helper.d.mts
Labels: pr: foundry v13
