Repository foundryvtt/pf2e, pull requests merged in 2025-05, with the labels that each got.

#18956 Release Notes 6.12.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#18960 Ensure weapon sheet update of property runes is array
  src/module/item/weapon/document.ts
  src/module/item/weapon/sheet.ts
  src/module/rules/rule-element/adjust-strike.ts
Labels: pr: bugfix

#18961 Release Notes 6.12.1
  CHANGELOG.md
  static/system.json
Labels: pr: housekeeping

#18976 Restore item create opt-groups for V13
  src/scripts/hooks/render-dialog.ts
  types/foundry/client/helpers/hooks.d.mts
Labels: pr: foundry v13

#18975 Fix formatting of Essence Forge description
  packs/equipment/essence-charm.json
  packs/equipment/essence-forge-greater.json
  packs/equipment/essence-forge-lesser.json
  packs/equipment/essence-forge-moderate.json
Labels: pr: data update

#18966 Brush up some NPC Core actors
  packs/bestiary-effects/effect-greased-palms.json
  packs/bestiary-effects/effect-one-for-all.json
  packs/bestiary-effects/effect-tip-the-scales.json
  packs/pathfinder-npc-core/laborer/commoner.json
  packs/pathfinder-npc-core/laborer/construction-worker.json
  packs/pathfinder-npc-core/laborer/dockhand.json
  packs/pathfinder-npc-core/laborer/drover.json
  packs/pathfinder-npc-core/laborer/farmer.json
  packs/pathfinder-npc-core/laborer/fisher.json
  packs/pathfinder-npc-core/laborer/gravedigger.json
  packs/pathfinder-npc-core/laborer/innkeeper.json
  packs/pathfinder-npc-core/laborer/messenger.json
  packs/pathfinder-npc-core/laborer/miner.json
  packs/pathfinder-npc-core/laborer/servant.json
  packs/pathfinder-npc-core/laborer/vermin-catcher.json
  packs/pathfinder-npc-core/martial-artist/black-belt.json
  packs/pathfinder-npc-core/martial-artist/grandmaster.json
  packs/pathfinder-npc-core/martial-artist/martial-student.json
  packs/pathfinder-npc-core/martial-artist/mixed-martial-artist.json
  packs/pathfinder-npc-core/martial-artist/tournament-combatant.json
  packs/pathfinder-npc-core/maverick/arms-dealer.json
  packs/pathfinder-npc-core/maverick/gunwitch.json
  packs/pathfinder-npc-core/maverick/high-roller.json
  packs/pathfinder-npc-core/maverick/musketeer.json
  packs/pathfinder-npc-core/maverick/peerless-duelist.json
  packs/pathfinder-npc-core/maverick/political-upstart.json
  packs/pathfinder-npc-core/maverick/runaway-blueblood.json
  packs/pathfinder-npc-core/maverick/unsanctioned-sheriff.json
  static/lang/re-en.json
Labels: pr: data update

#18978 Reduce divider size in effects panel
  src/styles/system/_effects-panel.scss
Labels: pr: bugfix, ui/ux

#18981 Update NPM dependencies
  package-lock.json
  package.json
Labels: pr: foundry v13

#18982 Fix minimum and verified compatibility version
  static/system.json
Labels: pr: foundry v13

#18985 Fix managed-by-rbv indicators in `SceneConfigPF2e`
  src/module/apps/roll-inspector/app.ts
  src/module/scene/sheet.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  src/module/sheet/mixin.svelte.ts
  src/styles/scene/_sheet.scss
  src/util/dom.ts
  static/lang/en.json
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/elements/file-picker.d.mts
  types/foundry/client/applications/elements/form-element.d.mts
  types/foundry/client/applications/elements/hue-slider.d.mts
  types/foundry/client/applications/elements/module.d.mts
  types/foundry/client/applications/elements/multi-select.d.mts
  types/foundry/client/applications/elements/prosemirror-editor.d.mts
  types/foundry/client/applications/elements/range-picker.d.mts
  types/foundry/client/applications/elements/string-tags.d.mts
  types/foundry/client/applications/sheets/scene-config.d.mts
  types/foundry/client/applications/sheets/user-config.d.mts
  types/foundry/common/data/fields.d.mts
  types/foundry/common/utils/event-emitter.d.mts
  types/foundry/common/utils/event-emitter.mts
  types/foundry/util.d.mts
Labels: pr: foundry v13

#19000 Add `system` CSS layer to Vite HMR
  src/styles/vite-hmr.scss
  vite.config.ts
Labels: pr: foundry v13

#18997 Add effect to `Dinosaur Boots` equipment
  packs/equipment-effects/effect-dinosaur-boots.json
  packs/equipment/dinosaur-boots-greater.json
  packs/equipment/dinosaur-boots.json
Labels: pr: data update

#19006 Fix Blinding of the Needle action cost
  packs/actions/blinding-of-the-needle.json
Labels: pr: data update

#19005 Also wrap importet library CSS in `system` layer for Vite HMR
  vite.config.ts
Labels: pr: foundry v13

#18995 Update character and vehicle sheets for v13
  src/styles/_globals.scss
  src/styles/_tags.scss
  src/styles/actor/_coinage.scss
  src/styles/actor/_index.scss
  src/styles/actor/_item-summary.scss
  src/styles/actor/character/_character.scss
  src/styles/actor/character/_index.scss
  src/styles/actor/vehicle/_index.scss
  static/templates/actors/partials/coinage.hbs
Labels: ui/ux, pr: foundry v13

#18989 Add Fortitude Saving Throw to Wall of Wind
  packs/spells/3rd-rank/wall-of-wind.json
Labels: pr: data update

#18974 Update Tengu Fan Item usage, description text, publication source and add automation to feats.
  packs/equipment/tengu-feather-fan.json
  packs/feats/ancestry/tengu/tengu-feather-fan.json
  packs/feats/ancestry/tengu/thunder-gods-fan.json
  packs/feats/ancestry/tengu/wind-gods-fan.json
  static/lang/re-en.json
Labels: pr: data update

#19015 Remove Harm font from Dalenydra
  packs/deities/empyreal-lords/dalenydra.json
Labels: pr: data update

#19016 Add alternate domains to Zura, update Domains journal, remove duplicate Zura and apply redirects
  build/uuid-redirects.json
  packs/deities/demon-lords/zura.json
  packs/deities/zura.json
  packs/journals/domains.json
Labels: pr: data update

#19018 Fix inclusion of other custom vite HMR plugins
  vite.config.ts
Labels: pr: foundry v13

#18998 Set up automation for `Unleash Yaoguai Might` and `Legendary Monster`
  packs/feat-effects/effect-legendary-monster.json
  packs/feat-effects/effect-unleash-yaoguai-might.json
  packs/feats/ancestry/yaoguai/legendary-monster.json
  packs/feats/ancestry/yaoguai/unleash-yaoguai-might.json
  static/lang/re-en.json
Labels: pr: data update

#19019 Replace deprecated `rangePicker` helper with `<range-picker>` elements
  src/module/item/base/sheet/rule-element-form/token-light.ts
  static/templates/items/rules/aura.hbs
  static/templates/items/rules/token-image.hbs
  static/templates/items/rules/token-light.hbs
Labels: pr: foundry v13

#19012 Restore initialization of `hotbarDrop` hook
  src/scripts/hooks/index.ts
Labels: pr: foundry v13

#19020 Fix dropping a roll option toggle on the hotbar
  src/scripts/hooks/hotbar-drop.ts
Labels: pr: foundry v13

#19021 Fix effect panel aura glow when its the first element
  src/styles/system/_effects-panel.scss
Labels: pr: bugfix

#19023 Correct Saving Throw values for Azlanti Altered Lion variants
  packs/pfs-season-6-bestiary/6-15/azlanti-altered-lion-additional-legs.json
  packs/pfs-season-6-bestiary/6-15/azlanti-altered-lion-armor-plating.json
Labels: pr: data update

#19022 Fix formula picker styling
  src/module/actor/character/apps/formula-picker/app.svelte
  src/module/actor/character/apps/formula-picker/app.ts
  src/styles/_globals.scss
Labels: pr: foundry v13

#18977 Convert AfflictionSystemData to DataModel and update sheet
  src/module/item/abstract-effect/data.ts
  src/module/item/abstract-effect/schema.ts
  src/module/item/abstract-effect/values.ts
  src/module/item/affliction/data.ts
  src/module/item/affliction/document.ts
  src/module/item/affliction/sheet.ts
  src/scripts/hooks/init.ts
  src/scripts/hooks/load.ts
  src/styles/item/_affliction-sheet.scss
  src/styles/item/_index.scss
  static/template.json
  static/templates/items/affliction-details.hbs
  static/templates/items/affliction-sidebar.hbs
Labels: pr: refactor

#18993 Add toggle to `Dire Growth` feat automation
  packs/feats/archetype/werecreature/dire-growth.json
Labels: pr: data update

#18994 Add Automation to `Ceremony of Growth` feat
  packs/feats/ancestry/conrasu/ceremony-of-growth.json
Labels: pr: data update

#19024 Add TraitdescriptionBravado in description in traits.ts
  src/scripts/config/traits.ts
Labels: pr: data update

#19028 Fix affliction errors and import more types
  src/module/item/abstract-effect/data.ts
  src/module/item/affliction/data.ts
  src/module/item/armor/document.ts
  src/module/item/physical/data.ts
  src/module/system/text-editor.ts
Labels: pr: types update

#19031 Address non-passive wheel event listener warning in actor sheet and add a debounce time to delta inputs from wheel events
  src/module/actor/sheet/base.ts
Labels: pr: foundry v13

#19036 Fix showing spell template clear button
  src/module/canvas/layer/template.ts
  src/module/canvas/measured-template.ts
  src/module/chat-message/document.ts
  src/module/chat-message/helpers.ts
  src/module/scene/measured-template-document.ts
  types/foundry/client/canvas/board.d.mts
  types/foundry/client/canvas/sources/base-effect-source.d.mts
  types/foundry/client/canvas/sources/point-movement-source.d.mts
Labels: pr: foundry v13

#19040 Fix data model issues in affliction
  src/module/item/abstract-effect/helpers.ts
  src/module/item/abstract-effect/schema.ts
  src/module/item/affliction/data.ts
Labels: pr: types update

#19042 Refine mixed-in client document types
  types/foundry/client/canvas/placeables/token.d.mts
  types/foundry/client/documents/abstract/canvas-document.d.mts
  types/foundry/client/documents/abstract/client-document.d.mts
  types/foundry/client/documents/active-effect.d.mts
  types/foundry/client/documents/actor-delta.d.mts
  types/foundry/client/documents/actor.d.mts
  types/foundry/client/documents/ambient-light.d.mts
  types/foundry/client/documents/ambient-sound.d.mts
  types/foundry/client/documents/card.d.mts
  types/foundry/client/documents/chat-message.d.mts
  types/foundry/client/documents/combat.d.mts
  types/foundry/client/documents/combatant-group.d.mts
  types/foundry/client/documents/combatant.d.mts
  types/foundry/client/documents/drawing.d.mts
  types/foundry/client/documents/item.d.mts
  types/foundry/client/documents/journal-entry-page.d.mts
  types/foundry/client/documents/journal-entry.d.mts
  types/foundry/client/documents/macro.d.mts
  types/foundry/client/documents/measured-template.d.mts
  types/foundry/client/documents/note.d.mts
  types/foundry/client/documents/playlist-sound.d.mts
  types/foundry/client/documents/playlist.d.mts
  types/foundry/client/documents/region-behavior.d.mts
  types/foundry/client/documents/region.d.mts
  types/foundry/client/documents/roll-table.d.mts
  types/foundry/client/documents/scene.d.mts
  types/foundry/client/documents/setting.d.mts
  types/foundry/client/documents/table-result.d.mts
  types/foundry/client/documents/tile.d.mts
  types/foundry/client/documents/token.d.mts
  types/foundry/client/documents/user.d.mts
  types/foundry/client/documents/wall.d.mts
  types/foundry/client/helpers/document-index.d.mts
  types/foundry/client/utils/_module.d.mts
  types/foundry/common/documents/_module.d.mts
  types/foundry/common/utils/string-tree.d.mts
  types/foundry/common/utils/word-tree.d.mts
Labels: pr: foundry v13

#19046 Fix `TemplateLayerPF2e#getSnappedPoint`
  src/module/canvas/layer/template.ts
  types/foundry/client/canvas/layers/base/placeables-layer.d.mts
Labels: pr: bugfix, pr: foundry v13

#19053 Set compatibility max to 12 in system.json
  static/system.json
Labels: pr: housekeeping

#19049 Add type "status" to the Symbol of Loyalty Effect
  packs/bestiary-effects/effect-symbol-of-loyalty.json
Labels: pr: data update

#19041 Convert EffectSystemData and ConditionSystemData to DataModel
  build/lib/extractor.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/abstract-effect/document.ts
  src/module/item/abstract-effect/helpers.ts
  src/module/item/abstract-effect/schema.ts
  src/module/item/abstract-effect/types.ts
  src/module/item/affliction/data.ts
  src/module/item/affliction/document.ts
  src/module/item/base/data/index.ts
  src/module/item/condition/data.ts
  src/module/item/condition/document.ts
  src/module/item/effect/data.ts
  src/module/item/effect/document.ts
  src/module/item/effect/sheet.ts
  src/module/rules/rule-element/grant-item/rule-element.ts
  src/scripts/hooks/load.ts
  static/lang/en.json
  static/template.json
  static/templates/actors/character/tabs/effects.hbs
  static/templates/items/affliction-sidebar.hbs
  types/foundry/common/abstract/type-data.d.mts
Labels: pr: refactor

#19055 Resize tokens ahead of direct actor size change
  src/module/actor/army/data.ts
  src/module/actor/base.ts
  src/module/actor/npc/document.ts
  src/module/actor/vehicle/data.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/base/document.ts
  src/module/scene/token-document/document.ts
  src/module/scene/token-document/sheet.ts
  types/foundry/client/canvas/placeables/_types.d.mts
  types/foundry/client/canvas/placeables/tokens/ring-config.d.mts
  types/foundry/client/client.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/documents/token.d.mts
  types/foundry/common/abstract/data.d.mts
  types/foundry/common/abstract/document.d.mts
  types/foundry/common/abstract/embedded-collection.d.mts
  types/foundry/common/primitives/_module.d.mts
  types/foundry/common/utils/iterable-weak-set.d.mts
  types/foundry/common/utils/module.d.mts
Labels: pr: foundry v13

#19056 Add NPCs from Quest 24
  packs/pfs-season-6-bestiary/quests/animated-flame.json
  packs/pfs-season-6-bestiary/quests/burning-building.json
  packs/pfs-season-6-bestiary/quests/elite-animated-flame.json
  packs/pfs-season-6-bestiary/quests/weak-animated-flame.json
  packs/pfs-season-6-bestiary/quests/ōmukade.json
Labels: pr: data entry, source: pathfinder society

#19052 Avoid skipping sanctification choice set for deities permitting no sanctification
  packs/classfeatures/deity-champion.json
  packs/classfeatures/deity-cleric.json
Labels: pr: data update

#19048 Add monk to trait to Ki Cutting Sight and add effect
  packs/spell-effects/spell-effect-ki-cutting-sight.json
  packs/spells/focus/ki-cutting-sight.json
Labels: pr: data update

#19045 Improve `MeasuredTemplate` preview rotation UX for cones and lines
  src/module/canvas/layer/template.ts
Labels: pr: foundry v13

#19060 Add precision resistance to Denizen of Leng
  packs/pathfinder-bestiary-2/denizen-of-leng.json
Labels: data error

#19061 Correct Curse Maelstrom Effect effect radius formula
  packs/feat-effects/effect-curse-maelstrom-state.json
Labels: pr: data update

#19054 Update persistent damage editor to app v2
  src/module/actor/base.ts
  src/module/apps/effects-panel.ts
  src/module/canvas/status-effects.ts
  src/module/item/condition/persistent-damage-dialog.ts
  src/module/item/condition/persistent-damage-editor.ts
  src/scripts/macros/edit-persistent.ts
  src/styles/item/_index.scss
  src/styles/item/_persistent-damage-dialog.scss
  src/styles/item/_persistent-damage-editor.scss
  static/lang/en.json
  static/templates/items/persistent-damage-dialog.hbs
  static/templates/items/persistent-damage-editor.hbs
Labels: pr: refactor, pr: foundry v13

#19069 Continue updating items, fix type-only imports
  src/module/actor/base.ts
  src/module/actor/character/elemental-blast.ts
  src/module/actor/helpers.ts
  src/module/actor/party/kingdom/schema.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/item/abstract-effect/data.ts
  src/module/item/affliction/data.ts
  src/module/item/base/document.ts
  src/module/item/condition/data.ts
  src/module/item/condition/persistent-damage-editor.ts
  src/module/item/effect/data.ts
  src/module/item/effect/sheet.ts
  src/module/item/physical/data.ts
  src/module/migration/migrations/935-deity-icon-paths.ts
  src/module/scene/measured-template-document.ts
  src/module/scene/token-document/sheet.ts
  src/scripts/hooks/init.ts
  src/util/misc.ts
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/documents/abstract/client-document.d.mts
  types/foundry/client/helpers/client-settings.d.mts
  types/foundry/client/helpers/hooks.d.mts
  types/foundry/client/helpers/localization.d.mts
  types/foundry/common/utils/helpers.d.mts
Labels: pr: foundry v13

#19039 Move `Offer Story` to action description and remove `Raging Stories` effect
  packs/actions/offer-story.json
  packs/feat-effects/effect-raging-stories.json
Labels: pr: data update

#19038 Suppress Fire Damage and link `Remaining Air` effect to Aquatic Combat effect
  packs/other-effects/effect-aquatic-combat.json
Labels: pr: data update

#19025 Guns & Gears Iconics
  packs/iconics/droven-level-1.json
  packs/iconics/droven-level-3.json
  packs/iconics/droven-level-5.json
  packs/iconics/nhalmika-level-1.json
  packs/iconics/nhalmika-level-3.json
  packs/iconics/nhalmika-level-5.json
  packs/iconics/whirp-level-1.json
  packs/iconics/whirp-level-3.json
  packs/iconics/whirp-level-5.json
  static/icons/iconics/Droven.webp
  static/icons/iconics/DrovenFull.webp
  static/icons/iconics/Nhalmika.webp
  static/icons/iconics/NhalmikaFull.webp
  static/icons/iconics/Whirp.webp
  static/icons/iconics/WhirpFull.webp
Labels: pr: data update

#19075 Fix token art for level 1 Droven Iconic
  packs/iconics/droven-level-1.json
Labels: pr: data update

#19076 Move aura grid type check to scene getter
  src/module/canvas/token/aura/map.ts
  src/module/scene/document.ts
  src/module/scene/helpers.ts
Labels: pr: refactor

#19064 Correct treatment of Aquatic Combat Penalty
  packs/other-effects/effect-aquatic-combat.json
Labels: pr: data update

#19029 Add automation for Fiery Body return damage
  packs/spell-effects/spell-effect-fiery-body-9th-level.json
  packs/spell-effects/spell-effect-fiery-body.json
  static/lang/re-en.json
Labels: pr: data update

#19080 Remove extraneous Hidden link from Test of Strength Hazzard
  packs/kingmaker-bestiary/test-of-strength.json
Labels: pr: data update

#19062 Add missing `area-damage`, `area-effect` and `damage-effect` options to select actions
  packs/actions/lantern-beam.json
  packs/actions/primal-howl.json
  packs/actions/telekinetic-assault.json
  packs/actions/thermal-eruption.json
  packs/bestiary-family-ability-glossary/blackfrost-dead/blackfrost-dead-shattering-death.json
  packs/bestiary-family-ability-glossary/clockwork-creature/clockwork-creature-malfunction-backfire.json
  packs/bestiary-family-ability-glossary/cryptid/cryptid-experimental-energy-wave.json
  packs/bestiary-family-ability-glossary/cryptid/cryptid-mutant-explosive-end.json
  packs/bestiary-family-ability-glossary/divine-warden/divine-warden-divine-destruction.json
  packs/bestiary-family-ability-glossary/floodslain/floodslain-vomit-flotsam.json
  packs/bestiary-family-ability-glossary/ghost/ghost-telekinetic-assault.json
  packs/bestiary-family-ability-glossary/martial-artist/martial-artist-grandmaster-life-burn-aura.json
  packs/bestiary-family-ability-glossary/melfesh-monster/melfesh-monster-corpse-bomb.json
  packs/bestiary-family-ability-glossary/melfesh-monster/melfesh-monster-death-throes.json
  packs/bestiary-family-ability-glossary/melfesh-monster/melfesh-monster-flame-lash.json
  packs/bestiary-family-ability-glossary/nemesis/nemesis-explosive-blast.json
  packs/bestiary-family-ability-glossary/skeleton/skeleton-bone-powder.json
  packs/bestiary-family-ability-glossary/vampire/vampire-strigoi-domain-of-dusk.json
  packs/bestiary-family-ability-glossary/woodblessed/woodblessed-explosive-end.json
  packs/familiar-abilities/lightning-needles.json
Labels: pr: data update

#19081 Remove melee predicate from aquatic combat
  packs/other-effects/effect-aquatic-combat.json
Labels: pr: data update

#19082 Fill in settings menu class type definitions
  types/foundry/client/applications/_module.d.mts
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/api/category-browser.d.mts
  types/foundry/client/applications/dice/_module.d.mts
  types/foundry/client/applications/dice/roll-resolver.d.mts
  types/foundry/client/applications/settings/_module.d.mts
  types/foundry/client/applications/settings/config.d.mts
  types/foundry/client/applications/settings/menus/_module.d.mts
  types/foundry/client/applications/settings/menus/av-config.d.mts
  types/foundry/client/applications/settings/menus/default-sheets-config.d.mts
  types/foundry/client/applications/settings/menus/dice-config.d.mts
  types/foundry/client/applications/settings/menus/font-config.d.mts
  types/foundry/client/applications/settings/menus/prototype-overrides.d.mts
  types/foundry/client/applications/settings/menus/ui-config.d.mts
  types/foundry/client/config.d.mts
  types/foundry/client/documents/setting.d.mts
  types/foundry/client/helpers/client-issues.d.mts
  types/foundry/client/helpers/client-settings.d.mts
  types/foundry/client/packages/_module.d.mts
  types/foundry/client/packages/client-package.mts
  types/foundry/client/packages/module.d.mts
  types/foundry/client/packages/system.d.mts
  types/foundry/client/packages/world.d.mts
  types/foundry/common/packages/base-module.d.mts
  types/foundry/common/packages/base-package.d.mts
  types/foundry/common/packages/base-system.d.mts
  types/foundry/common/packages/base-world.d.mts
  types/foundry/tsconfig.json
Labels: pr: foundry v13

#19065 Convert ClassSystemData to TypeDataModel
  src/module/item/abc/data.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/class/data.ts
  src/module/item/class/sheet.ts
  src/module/model.ts
  src/scripts/hooks/load.ts
  static/lang/en.json
  static/template.json
  static/templates/items/class-details.hbs
  types/foundry/common/data/_types.d.mts
Labels: pr: refactor

#19083 Convert `WorldClockSettings` to `ApplicationV2`
  src/global.ts
  src/module/apps/world-clock/app.ts
  src/module/migration/migrations/936-move-world-created-on.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
  src/module/scene/document.ts
  src/module/scene/sheet.ts
  src/module/system/settings/index.ts
  src/module/system/settings/world-clock.ts
  src/module/user/sheet.ts
  src/scripts/config/index.ts
  src/scripts/hooks/get-scene-control-buttons.ts
  src/scripts/hooks/i18n-init.ts
  src/scripts/set-game-pf2e.ts
  static/lang/en.json
  static/templates/scene/pf2e-panel.hbs
  static/templates/system/settings/world-clock/index.hbs
  static/templates/system/settings/world-clock/settings.hbs
  types/foundry/client/applications/_module.d.mts
  types/foundry/client/applications/api/application.d.mts
  types/foundry/client/applications/api/document-sheet.d.mts
  types/foundry/client/applications/sheets/scene-config.d.mts
  types/foundry/client/applications/sheets/user-config.d.mts
Labels: pr: foundry v13

#19086 Add `area-damage`, `area-effect` and `damage-effect` options to select Feats and localization strings
  packs/feats/ancestry/athamaru/emit-defensive-odor.json
  packs/feats/ancestry/athamaru/offensive-odor.json
  packs/feats/ancestry/elf/demon-slayer.json
  packs/feats/ancestry/kobold/fleeing-shriek.json
  packs/feats/ancestry/merfolk/pummeling-whirlpool.json
  packs/feats/ancestry/nagaji/pit-of-snakes.json
  packs/feats/ancestry/versatile-heritages/duskwalker/yamarajs-grandeur.json
  packs/feats/ancestry/versatile-heritages/nephilim/dominion-aura.json
  packs/feats/archetype/ascended-celestial/aegis-for-the-innocent.json
  packs/feats/archetype/clockwork-reanimator/self-destruct.json
  packs/feats/archetype/ghoul/breath-of-hungry-death.json
  packs/feats/archetype/gladiator/gladiators-roar.json
  packs/feats/archetype/martial-artist/thunder-clap.json
  packs/feats/archetype/mortal-herald/glory-on-high.json
  packs/feats/archetype/mummy/desiccating-inhalation.json
  packs/feats/archetype/tattooed-historian/wrath-of-the-hold.json
  packs/feats/class/alchemist/numbing-spice-exhalation.json
  packs/feats/class/barbarian/impressive-landing.json
  packs/feats/class/druid/garland-spell.json
  packs/feats/class/kineticist/living-bonfire.json
  packs/feats/class/kineticist/rain-of-rust.json
  packs/feats/class/kineticist/the-thousand-lashes-of-the-weeping-willow.json
  packs/feats/class/wizard/explosive-arrival.json
  packs/feats/miscellaneous/deviant/blasting-beams.json
  packs/feats/miscellaneous/deviant/storming-breath.json
  packs/feats/miscellaneous/deviant/tectonic-stomp.json
  packs/feats/miscellaneous/deviant/unleash-the-blight.json
  packs/feats/miscellaneous/deviant/vine-lash.json
  static/lang/re-en.json
Labels: pr: data update

#19084 Update v13 `ProseMirror` types
  types/foundry/common/data/validators.d.mts
  types/foundry/common/prosemirror/_module.d.mts
  types/foundry/common/prosemirror/click-handler.d.mts
  types/foundry/common/prosemirror/content-link-plugin.d.mts
  types/foundry/common/prosemirror/dirty-plugin.d.mts
  types/foundry/common/prosemirror/dom-parser.d.mts
  types/foundry/common/prosemirror/highlight-matches-plugin.d.mts
  types/foundry/common/prosemirror/image-plugin.d.mts
  types/foundry/common/prosemirror/input-rules.d.mts
  types/foundry/common/prosemirror/keymaps.d.mts
  types/foundry/common/prosemirror/menu.d.mts
  types/foundry/common/prosemirror/paste-transformer.d.mts
  types/foundry/common/prosemirror/plugin.d.mts
  types/foundry/common/prosemirror/schema.d.mts
  types/foundry/common/prosemirror/schema/_types.d.mts
  types/foundry/common/prosemirror/schema/attribute-capture.d.mts
  types/foundry/common/prosemirror/schema/core.d.mts
  types/foundry/common/prosemirror/schema/image-link-node.d.mts
  types/foundry/common/prosemirror/schema/image-node.d.mts
  types/foundry/common/prosemirror/schema/link-mark.d.mts
  types/foundry/common/prosemirror/schema/lists.d.mts
  types/foundry/common/prosemirror/schema/marks.d.mts
  types/foundry/common/prosemirror/schema/other.d.mts
  types/foundry/common/prosemirror/schema/schema-definition.d.mts
  types/foundry/common/prosemirror/schema/secret-node.d.mts
  types/foundry/common/prosemirror/schema/tables.d.mts
  types/foundry/common/prosemirror/schema/utils.d.mts
  types/foundry/common/prosemirror/string-serializer.d.mts
Labels: pr: foundry v13

#19090 Brush up The Lonely Warrior
  packs/kingmaker-bestiary/the-lonely-warrior.json
Labels: pr: data update

#19092 Add `area-effect` option to Telekinetic Assault save
  packs/actions/telekinetic-assault.json
Labels: pr: data update

#19093 Update predicate for `Agile Shield Grip` feat
  packs/feats/class/shared-class-feats/agile-shield-grip.json
Labels: pr: data update

#19098 Fix ability to undo applied damage
  src/module/actor/base.ts
Labels: pr: bugfix

#19096 Update `EnrichmentOptionsPF2e` to accept a function as `rollData`
  src/module/actor/base.ts
  src/module/actor/loot/sheet.ts
  src/module/item/base/document.ts
  src/module/item/spell/document.ts
  src/module/system/check/roll.ts
  src/module/system/damage/roll.ts
  src/module/system/rolls.ts
  src/module/system/text-editor.ts
  types/foundry/client/applications/ux/text-editor.d.mts
Labels: pr: foundry v13

#19103 Fix showing damage dice options in roll inspector
  src/module/apps/roll-inspector/app.svelte
Labels: pr: bugfix

#19107 Remove code slated to be removed in V13 stable
  src/module/actor/sheet/base.ts
  src/module/apps/sidebar/actor-directory.ts
  src/module/chat-message/data.ts
  src/module/scene/document.ts
  src/module/scene/token-document/document.ts
  src/module/system/damage/damage.ts
  src/styles/_globals.scss
  src/styles/ui/_token-hud.scss
  types/foundry/client/documents/chat-message.d.mts
Labels: pr: foundry v13

#19108 Add `area-damage`, `area-effect` and `damaging-effect` to select NPC attacks
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/alchemical-horror.json
  packs/book-of-the-dead-bestiary/unrisen.json
  packs/crown-of-the-kobold-king-bestiary/the-disciples.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/darklands-alchemical-golem.json
  packs/extinction-curse-bestiary/book-4-siege-of-the-dinosaurs/giant-aukashungi.json
  packs/fall-of-plaguestone/caustic-wolf.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/planar-terra-cotta-squadron.json
  packs/lost-omens-bestiary/monsters-of-myth/somnalu.json
  packs/lost-omens-bestiary/monsters-of-myth/spectral-devil.json
  packs/pathfinder-bestiary-2/sandpoint-devil.json
  packs/pathfinder-bestiary-3/arboreal-archive.json
  packs/pathfinder-bestiary-3/terra-cotta-garrison.json
  packs/pathfinder-bestiary/alchemical-golem.json
  packs/pathfinder-monster-core/noxious-needler.json
  packs/pfs-season-2-bestiary/2-14/corrupted-wildfire-3-4.json
  packs/pfs-season-2-bestiary/2-14/corrupted-wildfire-5-6.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/ghalzarokh.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/torgral.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/blighted-speaker-in-spores.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/old-thornbarker.json
Labels: pr: data update

#19104 Fix display of NPC Shield health when 3 digits long
  src/styles/actor/npc/_sidebar.scss
  static/templates/actors/npc/partials/sidebar.hbs
Labels: pr: bugfix, ui/ux

#19102 Use same font as V12 for NPC sheet
  src/styles/actor/npc/_index.scss
Labels: ui/ux, pr: foundry v13

#19094 Update v13 `ui` types
  src/global.ts
  types/foundry/client/ui.d.mts
  types/foundry/common/data/data.d.mts
Labels: pr: foundry v13

#19115 Restore Toggle Name Visibility button in `EncounterTracker`
  src/module/actor/base.ts
  src/module/actor/sheet/base.ts
  src/module/apps/sidebar/encounter-tracker.ts
  src/module/encounter/combatant.ts
  types/foundry/client/documents/combatant.d.mts
Labels: pr: foundry v13

#19116 Fix re-rendering auras following embedded item changes
  src/module/scene/token-document/document.ts
Labels: pr: foundry v13

#19118 Remove `Choral` actor and redirect to Monster Core equivalent
  build/uuid-redirects.json
  packs/pathfinder-bestiary/choral.json
Labels: pr: data update

#19120 Remove extraneous character in `Scarecrow` feat description
  packs/feats/archetype/bellflower-tiller/scarecrow.json
Labels: pr: data update

#19124 Use shallower partial in `LootPF2e#prepareBaseData`
  src/module/actor/loot/document.ts
  src/module/item/spell/document.ts
  types/foundry/client/documents/actor.d.mts
Labels: pr: foundry v13

#19126 Fix `ChatMessageFlagsPF2e` type being excessively deep
  src/module/chat-message/data.ts
  src/module/system/check/check.ts
  src/module/system/statistic/statistic.ts
Labels: pr: foundry v13

#19121 Fix Mutant Physique Deadly D10 ItemAlteration
  packs/feats/class/alchemist/mutant-physique.json
Labels: pr: data update

#19095 Replace Animal Instinct tables "(continued)" rows with rowspans
  packs/classfeatures/animal-instinct.json
Labels: pr: data update

#19106 Brush up Elder Outcrop
  packs/bestiary-effects/effect-dust-eternal.json
  packs/rage-of-elements-bestiary/elder-outcrop.json
Labels: pr: data update

#19109 Correct predicates for for several Ranger `Hunted Prey` associated items
  packs/classfeatures/avenger.json
  packs/classfeatures/masterful-hunter-flurry.json
  packs/classfeatures/masterful-hunter-outwit.json
  packs/classfeatures/masterful-hunter.json
  packs/classfeatures/outwit.json
  packs/classfeatures/ranger-weapon-expertise.json
  packs/classfeatures/vindicator.json
  packs/equipment/hunters-anthem.json
Labels: pr: data update

#19111 Tidy formatting of remaster Pantheons list
  packs/journals/remaster-changes.json
  packs/spell-effects/spell-effect-fiery-body-9th-level.json
Labels: pr: data update

#19112 Tidy descriptions of Ogre Spider Venom
  packs/kingmaker-bestiary/trapdoor-ogre-spider.json
  packs/pathfinder-bestiary-2/ogre-spider.json
  packs/pfs-season-2-bestiary/2-18/ogre-spider-pfs-2-18.json
Labels: pr: data update

#19117 Add `Bestiaries` entry to Remaster Changes journal
  packs/journals/remaster-changes.json
Labels: pr: data update

#19114 Add toggle for Wraith's Void's Embrace resistance
  packs/pathfinder-monster-core/wraith.json
Labels: pr: data update

#19128 Remove `Concentrate` trait from Blood Vendetta spell
  packs/spells/2nd-rank/blood-vendetta.json
Labels: pr: data update

#19125 Make `SpellOverlayOverride` type more shallow and remove cyclical reference
  src/module/item/spell/data.ts
  src/module/item/spell/document.ts
Labels: pr: foundry v13

#19131 Move some chat listeners to handlers in `ChatMessagePF2e` and `ChatLogPF2e`
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/crit-fumble-cards.ts
  src/module/chat-message/document.ts
  src/module/chat-message/listeners/degree-of-success.ts
  src/module/chat-message/listeners/index.ts
  static/lang/en.json
  static/templates/chat/persistent-damage-recovery.hbs
  types/foundry/client/applications/ui/notifications.d.mts
Labels: pr: foundry v13

#19133 Move apply-effect handler to `ChatLogPF2e`, fix aura-traits restriction
  packs/feat-effects/effect-kinetic-aura.json
  src/module/apps/sidebar/chat-log.ts
  src/module/chat-message/helpers.ts
  src/module/chat-message/listeners/cards.ts
  src/module/rules/rule-element/aura.ts
  static/templates/chat/action/collapsed.hbs
Labels: pr: foundry v13

#19135 Set party alliance default on newer Iconics
  packs/iconics/nahoa-level-1.json
  packs/iconics/nahoa-level-3.json
  packs/iconics/nahoa-level-5.json
  packs/iconics/samo-level-1.json
  packs/iconics/samo-level-3.json
  packs/iconics/samo-level-5.json
  packs/iconics/yoon-level-1.json
  packs/iconics/yoon-level-3.json
  packs/iconics/yoon-level-5.json
Labels: pr: data update

#19132 Fix description of Change Formation to the correct text
  packs/bestiary-ability-glossary-srd/change-formation.json
Labels: pr: data update

#19136 Add localization for Investigator's Perception Mastery description.
  static/lang/re-en.json
Labels: pr: data update

#19137 Fix regression with crit and crit fail result color
  src/styles/_colors.scss
  src/styles/ui/sidebar/chat/_check.scss
Labels: pr: bugfix, pr: foundry v13

#19129 Add `area-damage`, `area-effect` and `damaging-effect` to additional NPC attacks
  packs/book-of-the-dead-bestiary/combusted.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/desecrated-guardian.json
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/ilakni.json
  packs/howl-of-the-wild-bestiary/alicorn.json
  packs/kingmaker-bestiary/immense-mandragora.json
  packs/lost-omens-bestiary/monsters-of-myth/fafnheir.json
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/gilded-gunner-goon.json
  packs/pathfinder-bestiary-2/olethrodaemon.json
  packs/pathfinder-bestiary-3/blood-hag.json
  packs/pathfinder-bestiary-3/nightmarchers.json
  packs/pathfinder-monster-core/guthallath.json
  packs/pathfinder-monster-core/nuckelavee.json
  packs/pathfinder-monster-core/yamaraj.json
  packs/pathfinder-npc-core/official/watchmage-squadron.json
  packs/pfs-season-2-bestiary/2-15/blighted-fungus-leshy.json
  packs/pfs-season-2-bestiary/2-15/blighted-leaf-leshy.json
  packs/pfs-season-6-bestiary/6-15/empowered-shadow-lesolethe.json
  packs/pfs-season-6-bestiary/6-15/shadow-lesolethe.json
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/guhdggi.json
  packs/shadows-at-sundown-bestiary/bishop-keppira-dbear.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/living-sun-spire.json
  packs/war-of-immortals-bestiary/sublime-breath.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/creeping-cone-swarm.json
Labels: pr: data update

#19113 Automate hurl at the horizon
  packs/feats/class/exemplar/hurl-at-the-horizon.json
Labels: pr: data update

#19146 Add `area-damage`, `area-effect` and `damaging-effect` to even more NPC attacks
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/excorion-paragon.json
  packs/book-of-the-dead-bestiary/gholdako.json
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/saurian-warmonger.json
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/saurian-worldwatcher.json
  packs/lost-omens-bestiary/impossible-lands/clockwork-cannoneer.json
  packs/pathfinder-bestiary-2/ravener-husk.json
  packs/pathfinder-bestiary-2/steam-mephit.json
  packs/pathfinder-bestiary-3/clacking-sea-skull-swarm.json
  packs/pathfinder-bestiary-3/clacking-skull-swarm.json
  packs/pathfinder-bestiary-3/feral-sea-skull-swarm.json
  packs/pathfinder-bestiary-3/feral-skull-swarm.json
  packs/pathfinder-bestiary-3/sorcerous-sea-skull-swarm.json
  packs/pathfinder-bestiary-3/sorcerous-skull-swarm.json
  packs/pfs-season-2-bestiary/2-24/brittle-ravener-husk.json
  packs/pfs-season-2-bestiary/2-24/crumbling-ravener-husk.json
  packs/pfs-season-3-bestiary/3-12/scalding-mephit.json
  packs/pfs-season-4-bestiary/4-15/elite-clacking-skull-swarm.json
  packs/pfs-season-4-bestiary/4-15/weak-clacking-skull-swarm.json
  packs/rage-of-elements-bestiary/solar-crow.json
  packs/sky-kings-tomb-bestiary/book-3-heavy-is-the-crown/hryngar-breccia-squad.json
  packs/strength-of-thousands-bestiary/book-5-doorway-to-the-red-star/sparkeater.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/cataclysm-beetle.json
Labels: pr: data update

#19143 Add Crystal Xorn variant
  packs/lost-omens-bestiary/mwangi-expanse/crystal-xorn.json
Labels: data gap, pr: data entry, source: lost omens

#19030 Add automation for return damage to Furnace form
  packs/feat-effects/effect-furnace-form.json
  static/lang/re-en.json
Labels: pr: data update

#19147 Migrate `Signature Weapon` Yaoguai automation effects to feat
  packs/feats/ancestry/yaoguai/signature-weapon.json
Labels: pr: data update

#19149 Brush up some NPC Core actors
  packs/bestiary-effects/effect-bodyguards-defense.json
  packs/bestiary-effects/effect-hunters-onslaught.json
  packs/pathfinder-npc-core/mercenary/bodyguard.json
  packs/pathfinder-npc-core/mercenary/bounty-hunter.json
  packs/pathfinder-npc-core/mercenary/exiled-revolutionary.json
  packs/pathfinder-npc-core/mercenary/mage-for-hire.json
  packs/pathfinder-npc-core/mercenary/mercenary-band.json
  packs/pathfinder-npc-core/mercenary/siegebreaker.json
Labels: pr: data update

#19148 Update automation for `Spellguard Shield` and add automation to `Reflecting Shield`
  packs/equipment/reflecting-shield.json
  packs/equipment/spellguard-shield.json
  static/lang/re-en.json
Labels: pr: data update

#19151 Fix action cost of Ringing Challenge
  packs/actions/ringing-challenge.json
Labels: pr: data update

#19150 Allow fire impulses to work underwater
  packs/other-effects/effect-aquatic-combat.json
Labels: pr: data update

#19153 Fix stray rsquo in NPC spellcasting entry name
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/rukh.json
Labels: pr: data update

#19155 Add AdjustSuccess to Minotaur Hunter
  packs/pathfinder-monster-core/minotaur-hunter.json
Labels: pr: data update, source: rulebooks

#19156 Correct Damage Override for Valerie
  packs/feats/class/exemplar/hurl-at-the-horizon.json
  packs/kingmaker-bestiary/valerie-level-1.json
  packs/kingmaker-bestiary/valerie-level-9.json
Labels: source: adventure path, pr: data update

#19157 Release Notes 6.12.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19158 Fix few RE localization keys
  packs/feat-effects/effect-legendary-monster.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/aeon-stone-swarm.json
  static/lang/re-en.json
Labels: pr: data update

#19163 Fix type of Document#getUserLevel()
  types/foundry/common/abstract/document.d.mts
Labels: pr: types update, pr: foundry v13

#19162 Brush up Void Pit
  packs/kingmaker-bestiary/void-pit.json
Labels: pr: data update

#19167 Update automation for Marilith's `Focused Assault`
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/urushil.json
  packs/pathfinder-bestiary/marilith.json
Labels: pr: data update

#19166 Modify hold breath Air Remaining Effect duration to be upgradeable by feats
  packs/feats/ancestry/android/internal-respirator.json
  packs/feats/ancestry/kashrishi/mental-sustenance.json
  packs/feats/ancestry/versatile-heritages/sylph/inner-breath.json
  packs/feats/general/breath-control.json
  packs/heritages/awakened-animal/swimming-animal.json
  packs/other-effects/effect-remaining-air.json
Labels: pr: data update

#19168 Fix name of Shades NPC
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/dero-sentry.json
Labels: pr: data update

#19173 Update `TokenDocument` type definition for V13
  types/foundry/client/applications/sidebar/apps/compendium.d.mts
  types/foundry/client/applications/sidebar/tabs/actor-directory.d.mts
  types/foundry/client/applications/sidebar/tabs/item-directory.d.mts
  types/foundry/client/documents/abstract/directory-collection-mixin.d.mts
  types/foundry/client/documents/token.d.mts
Labels: pr: foundry v13

#19174 Make some minor corrections of recent types updates
  src/module/actor/base.ts
  src/module/item/base/document.ts
  src/module/item/physical/document.ts
  src/module/item/spell/document.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/canvas/layers/base/placeables-layer.d.mts
  types/foundry/client/canvas/layers/lighting.d.mts
  types/foundry/client/canvas/rendering/filters/vision-mask-filter.d.mts
  types/foundry/client/documents/abstract/directory-collection-mixin.d.mts
  types/foundry/client/documents/token.d.mts
  types/foundry/common/abstract/document.d.mts
Labels: pr: types update, pr: foundry v13

#19165 Convert `PickAThingPrompt` and subclasses to AppV2
  src/module/apps/item-attacher.ts
  src/module/apps/pick-a-thing-prompt.ts
  src/module/rules/rule-element/choice-set/prompt.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/styles/_colors.scss
  src/styles/system/_choice-set-prompt.scss
  static/templates/items/item-attacher.hbs
  static/templates/system/rules-elements/choice-set-prompt.hbs
Labels: pr: foundry v13

#19178 Fix error when actors that are party members are deleted
  src/module/apps/sidebar/actor-directory.ts
Labels: pr: bugfix, pr: foundry v13

#19179 Fix some spell areas to be cylinder
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/urevian.json
  packs/age-of-ashes-bestiary/book-6-broken-promises/rinnarv-bontimar.json
  packs/agents-of-edgewatch-bestiary/book-4-assault-on-hunting-lodge-seven/priest-of-blackfingers.json
  packs/agents-of-edgewatch-bestiary/book-4-assault-on-hunting-lodge-seven/secret-keeper.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/wheel-archon.json
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/yurgak.json
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/sarvel-ever-hunger.json
  packs/kingmaker-bestiary/sepoko.json
  packs/kingmaker-bestiary/the-knurly-witch.json
  packs/kingmaker-bestiary/tristian-level-10.json
  packs/kingmaker-bestiary/zorek.json
  packs/lost-omens-bestiary/highhelm/grand-defender.json
  packs/lost-omens-bestiary/monsters-of-myth/taljjae-the-hermit.json
  packs/pathfinder-bestiary-2/magma-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/purrodaemon.json
  packs/pathfinder-bestiary-3/living-rune-divine.json
  packs/pathfinder-bestiary/guardian-naga.json
  packs/pathfinder-bestiary/simurgh.json
  packs/pfs-season-2-bestiary/2-22/disciple-of-urxehl-9-10.json
  packs/pfs-season-5-bestiary/5-15/blessed-uirch-of-the-burning-suns.json
  packs/pfs-season-5-bestiary/5-18/jamimpi.json
  packs/pfs-season-5-bestiary/5-18/resolved-jamimpi.json
  packs/rage-of-elements-bestiary/austral-the-south-wind.json
  packs/seven-dooms-for-sandpoint-bestiary/vizmivool.json
  packs/shadows-at-sundown-bestiary/strigoi-progenitor.json
  packs/sky-kings-tomb-bestiary/book-3-heavy-is-the-crown/hryngar-battlepriest.json
  packs/sky-kings-tomb-bestiary/book-3-heavy-is-the-crown/stoneriver.json
  packs/spells/5th-rank/flame-strike.json
  packs/spells/5th-rank/geyser.json
  packs/spells/5th-rank/scouring-pulse.json
  packs/spells/6th-rank/flame-vortex.json
  packs/spells/6th-rank/zero-gravity.json
  packs/spells/8th-rank/burning-blossoms.json
  packs/spells/8th-rank/rainbow-fumarole.json
  packs/spells/8th-rank/whirlpool.json
  packs/stolen-fate-bestiary/book-1-the-choosing/endlo-kiver.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/abendego-priest.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/halbrux-far-sight.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/avatar-of-walkena.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/graveknight-champion.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/sun-warrior-brigade.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/unshadowed-haibram.json
Labels: pr: data update

#19189 Release Notes 6.12.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19199 Fix ActiveEffect does not exist error when healing dead actors
  src/module/actor/base.ts
Labels: pr: bugfix

#19198 Skip rolling persistent damage for dead actors
  src/module/encounter/combatant.ts
  src/module/item/condition/document.ts
Labels: pr: enhancement

#19200 Release Notes 6.12.4
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19202 Fix regression from rebasing onto v12
  src/module/actor/base.ts
Labels: pr: bugfix

#19207 Fix applying damage for v13
  src/module/chat-message/helpers.ts
Labels: pr: bugfix, pr: foundry v13

#19208 Remove kineticist trait from stance auras and show invalid traits in form
  packs/feat-effects/stance-ghosts-in-the-storm.json
  packs/feat-effects/stance-kindle-inner-flames.json
  packs/feat-effects/stance-orchards-endurance.json
  packs/feat-effects/stance-sea-glass-guardians.json
  packs/feat-effects/stance-shattershields.json
  packs/feat-effects/stance-thermal-nimbus.json
  static/templates/items/rules/aura.hbs
Labels: pr: bugfix, pr: data update

#19209 Fix some broken uuid links
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/chafkhem.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/inizkar.json
  static/lang/action-en.json
  static/lang/en.json
Labels: pr: data update

#19214 Remove non-effect action traits from existing aura rule elements
  build/run-migration.ts
  packs/bestiary-effects/effect-hunters-onslaught.json
  packs/classfeatures/air-gate.json
  packs/classfeatures/fire-gate.json
  packs/classfeatures/metal-gate.json
  packs/classfeatures/water-gate.json
  packs/classfeatures/wood-gate.json
  packs/curtain-call-bestiary/book-1-stage-fright/hellshadow.json
  packs/equipment-effects/aura-shining-symbol.json
  packs/feat-effects/effect-curse-of-creeping-ashes.json
  packs/feat-effects/effect-curse-of-engulfing-flames.json
  packs/feats/archetype/ghoul/corpse-stench.json
  packs/feats/archetype/hallowed-necromancer/consecrated-aura.json
  packs/feats/archetype/knight-vigilant/empyreal-aura.json
  packs/feats/class/shared-class-feats/undying-conviction.json
  packs/iconics/yoon-level-1.json
  packs/iconics/yoon-level-3.json
  packs/iconics/yoon-level-5.json
  packs/pathfinder-bestiary-2/attic-whisperer.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient.json
  packs/pathfinder-bestiary-2/thunderbird.json
  packs/pathfinder-npc-core/scholar/sage.json
  packs/spell-effects/aura-spiral-of-horrors.json
  packs/spell-effects/spell-effect-incendiary-aura.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/vehanezhad.json
  src/module/migration/migrations/937-remove-invalid-aura-traits.ts
  src/module/migration/migrations/index.ts
  src/module/migration/runner/base.ts
Labels: pr: data migration, pr: data update

#19215 Fix handful of `Actor`/`TokenDocument` type errors
  src/module/actor/base.ts
  src/module/chat-message/document.ts
  src/module/item/base/document.ts
  src/module/scene/token-document/document.ts
  types/foundry/common/abstract/document.d.mts
Labels: pr: types update, pr: foundry v13

#19205 Add optional start data to AbstractEffectSystemData
  src/module/item/abstract-effect/data.ts
  src/module/item/abstract-effect/helpers.ts
  src/module/item/spellcasting-entry/types.ts
Labels: pr: types update

#19218 Fix `ItemAttacher` styling
  src/module/apps/item-attacher.ts
  src/styles/item/_item-attacher.scss
  static/templates/items/item-attacher.hbs
Labels: pr: foundry v13

#19220 Improve `WorldClock` styling
  src/module/apps/world-clock/app.ts
  src/styles/system/_world-clock.scss
  static/templates/system/world-clock.hbs
Labels: pr: foundry v13

#19227 Restore access to kingdom sheet from party list
  src/module/actor/party/kingdom/model.ts
  src/module/actor/party/kingdom/sheet.ts
  src/module/apps/sidebar/actor-directory.ts
  src/styles/actor/party/kingdom/_activities.scss
  src/styles/actor/party/kingdom/_index.scss
  src/styles/actor/party/kingdom/_main.scss
  src/styles/actor/party/kingdom/_world.scss
  src/styles/ui/sidebar/_actor-directory.scss
Labels: kingmaker, pr: foundry v13

#19229 Exclude rectangle templates from custom grid snapping
  src/module/canvas/layer/template.ts
Labels: pr: foundry v13

#19232 Apply modifier adjustments to the original value
  src/module/actor/helpers.ts
  src/module/actor/modifiers.ts
  src/module/system/damage/helpers.ts
Labels: pr: bugfix

#19231 Fix embedding items in journal sheets failing with a max depth warning
  src/module/system/text-editor.ts
Labels: pr: foundry v13
