Repository foundryvtt/pf2e, pull requests merged in 2025-06, with the labels that each got.

#19247 Fix OutlineOverlayFilter for v13.344
  src/module/canvas/perception/modes.ts
Labels: pr: bugfix

#19251 Move `EffectsPanel` click handlers to action
  src/module/apps/effects-panel.ts
  static/templates/system/effects/panel.hbs
Labels: pr: refactor, pr: foundry v13

#19240 Add Adjust DoS RE to Assured Identification
  packs/feats/skill/assured-identification.json
  static/lang/re-en.json
Labels: pr: data update

#19206 Add Expert Spellcasting to Expert Red Mantis Magic Feat
  packs/feats/archetype/red-mantis-assassin/expert-red-mantis-magic.json
  packs/spells/focus/achaekeks-clutch.json
Labels: pr: data update

#19217 Add inline roll and action to Agile Warrior's Deadly Disarm
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/agile-warrior-nightmares.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-1-despair-on-danger-island/agile-warrior.json
  packs/the-slithering-bestiary/nyamat-mshwe.json
Labels: pr: data update

#19237 Tidy description of Infectious Aura
  packs/bestiary-effects/effect-infectious-aura.json
Labels: pr: data update

#19261 Set Haste effect icon to not show
  packs/spell-effects/spell-effect-haste.json
Labels: pr: data update

#19254 Release Notes 7.1.1
  CHANGELOG.md
  package-lock.json
  package.json
  static/changelog.old/6.0.0-6.12.4.md
  static/system.json
Labels: pr: housekeeping

#19262 Fix download version in manifest
  static/system.json
Labels: pr: housekeeping

#19272 Fix autoresolving Choice Sets in ammunition effects when dragged from damage notes
  packs/equipment-effects/effect-exsanguinating-ammunition.json
  packs/equipment-effects/effect-ooze-ammunition.json
Labels: pr: data update

#19269 Add effect to `Wyrm Spindle` Spellheart
  packs/equipment-effects/effect-wyrm-spindle-armor.json
  packs/equipment/wyrm-spindle-greater.json
  packs/equipment/wyrm-spindle-major.json
  packs/equipment/wyrm-spindle.json
Labels: pr: data update

#19265 Add alchemical and aura as shield traits to support Magnetic Shield
  packs/equipment/8-round-magazine.json
  packs/equipment/magnetic-shield.json
  packs/spells/focus/spellsurge.json
  src/scripts/config/traits.ts
Labels: pr: data update

#19274 Run extractPacks all
  build/lib/extractor.ts
  packs/feats/archetype/linguist/linguist-dedication.json
  packs/iconics/samo-level-5.json
  packs/lost-omens-bestiary/_folders.json
  packs/paizo-pregens/mark-of-the-mantis/kangir.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/inizkar.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/rukh.json
  packs/shadows-at-sundown-bestiary/abridan-ashau.json
Labels: pr: data update

#19283 Update `Helt's Spelldance` action cost
  packs/feats/class/shared-class-feats/helts-spelldance.json
Labels: pr: data update

#19285 Fix `EffectsPanel` tooltip and remove override for issue fixed in v13.345
  src/module/apps/effects-panel.ts
  src/module/sheet/helpers.ts
  src/module/system/text-editor.ts
Labels: pr: bugfix, pr: foundry v13

#19294 Remove trailing whitespace from select publication titles
  packs/equipment/goz-mask.json
  packs/equipment/toshigami-blossom.json
Labels: pr: data update

#19288 Add note for `Curse of the Werebat` to Werebat Warrior's Jaw attack
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/romi-bracken.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/werebat-warrior.json
Labels: pr: data update

#19281 Update formatting and automation on some Shining Kingdom items
  packs/equipment-effects/effect-crimson-godsblood-serum.json
  packs/equipment-effects/effect-taldogis-badge.json
  packs/equipment/bravery-baldric-flight.json
  packs/equipment/breath-of-freedom.json
  packs/equipment/crimson-godsblood-serum-greater.json
  packs/equipment/crimson-godsblood-serum-lesser.json
  packs/equipment/crimson-godsblood-serum-moderate.json
  packs/equipment/keep-stone-amulet.json
  packs/equipment/lions-call.json
  packs/equipment/lions-pelt-chain.json
  packs/equipment/lions-pelt-leather.json
  packs/equipment/screaming-pinion.json
  packs/equipment/shawl-of-seasons.json
  packs/equipment/the-dancers-song.json
  packs/feats/archetype/splinter-of-finality/dread-blade.json
  static/lang/re-en.json
Labels: pr: data update

#19296 Grant persistent damage with Ooze Ammunition depending on its variety
  packs/equipment-effects/effect-ooze-ammunition.json
Labels: pr: data update

#19297 Add support for Instinct Ability to Fury Instinct
  packs/classfeatures/fury-instinct.json
  packs/feats/archetype/barbarian/instinct-ability.json
Labels: pr: data update

#19298 Add Covenant support to Clerics and Champions
  packs/classfeatures/deity-champion.json
  packs/classfeatures/deity-cleric.json
Labels: pr: data update

#19300 Correct Werebat Warrior's Fang attack slug
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/werebat-warrior.json
Labels: pr: data update

#19277 Fix Greater Advancing rune effect, TV wands rank, Anylength Rope description
  packs/equipment/advancing-greater.json
  packs/equipment/anylength-rope-greater.json
  packs/equipment/anylength-rope-moderate.json
  packs/equipment/beastmasters-sigil-major.json
  packs/equipment/bleachguard-doll.json
  packs/equipment/desolation-locket-greater.json
  packs/equipment/desolation-locket-major.json
  packs/equipment/desolation-locket.json
  packs/equipment/dragon-turtle-plate.json
  packs/equipment/druids-crown.json
  packs/equipment/library-robes-greater.json
  packs/equipment/library-robes-major.json
  packs/equipment/library-robes.json
  packs/equipment/reef-heart-greater.json
  packs/equipment/wand-of-clinging-rime-9th-rank.json
  packs/equipment/wand-of-mercy-5th-rank.json
  packs/equipment/wand-of-noisome-acid-2nd-rank.json
  packs/equipment/wand-of-noisome-acid-4nd-rank.json
  packs/equipment/wand-of-noisome-acid-6th-rank.json
  packs/equipment/wand-of-noisome-acid-8th-rank.json
Labels: pr: data update

#19305 Add `area-damage`, `area-effect`, and `damaging-effect` to select NPC attacks
  packs/age-of-ashes-bestiary/book-2-cult-of-cinders/charau-ka-dragon-priest.json
  packs/age-of-ashes-bestiary/book-2-cult-of-cinders/gerhard-pendergrast.json
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/ancient-skaveling.json
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/pyrogeist.json
  packs/book-of-the-dead-bestiary/mummy-prophet-of-set.json
  packs/extinction-curse-bestiary/book-1-the-show-must-go-on/viktor-volkano.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/arms-of-balance-pravan-majinapti.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/arms-of-balance-usvani.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/cloudsplitter.json
  packs/gatewalkers-bestiary/book-1-the-seventh-arch/kareq.json
  packs/gatewalkers-bestiary/book-3-dreamers-of-the-nameless-spires/blackfrost-guecubu.json
  packs/pathfinder-bestiary-3/guecubu.json
  packs/pathfinder-monster-core/firewyrm.json
  packs/pathfinder-monster-core/mukradi.json
  packs/pfs-season-3-bestiary/3-12/scalding-mephit.json
  packs/pfs-season-5-bestiary/5-01/hardwood-scamp.json
  packs/rage-of-elements-bestiary/brass-bastion.json
Labels: pr: data update

#19307 Add Ankhrav variants for TotT
  packs/triumph-of-the-tusk-bestiary/book-2-hoof-cinder-and-storm/ankhrav-hive-mother.json
  packs/triumph-of-the-tusk-bestiary/book-2-hoof-cinder-and-storm/ankhrav.json
Labels: source: adventure path, pr: data entry

#19278 Fix creating `RollTable`s from the compendium browser and fix crafting action
  src/module/apps/compendium-browser/browser.ts
  src/module/apps/compendium-browser/loader.ts
  src/module/apps/compendium-browser/tabs/base.svelte.ts
  src/module/apps/compendium-browser/tabs/data.ts
  src/module/system/action-macros/crafting/repair.ts
  static/templates/compendium-browser/roll-table-dialog.hbs
  types/foundry/common/documents/table-result.d.mts
Labels: pr: bugfix, pr: foundry v13

#19303 Fix Major Enigma Mirror spell DC, fix TV items minor description formatting issues
  packs/equipment/empaths-cordial.json
  packs/equipment/energizing-treat.json
  packs/equipment/enigma-mirror-major.json
  packs/equipment/enigma-sight-potion.json
  packs/equipment/euphoric-loop-greater.json
  packs/equipment/euphoric-loop.json
  packs/equipment/everyneed-pack-greater.json
  packs/equipment/everyneed-pack.json
  packs/equipment/familiar-morsel.json
  packs/equipment/fate-shot.json
  packs/equipment/kindled-tome.json
  packs/equipment/wand-of-rolling-flames-2nd-rank.json
  packs/equipment/wand-of-rolling-flames-3rd-rank.json
  packs/equipment/wand-of-rolling-flames-4th-rank.json
  packs/equipment/wand-of-rolling-flames-5th-rank.json
  packs/equipment/wand-of-rolling-flames-6th-rank.json
  packs/equipment/wand-of-rolling-flames-7th-rank.json
  packs/equipment/wand-of-rolling-flames-8th-rank.json
  packs/equipment/wand-of-rolling-flames-9th-rank.json
Labels: pr: data update

#19309 Adding the missing trigger description to the "drop dead" spell.
  packs/spells/5th-rank/drop-dead.json
Labels: pr: data update

#19319 Add `area damage`, `area-effect` and `damaging-effect` options to applicable NPC abilities
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/bright-walker.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/chaos-gulgamodh.json
  packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/izhkarial.json
  packs/howl-of-the-wild-bestiary/drthak.json
  packs/kingmaker-bestiary/lesser-jabberwock.json
  packs/pathfinder-bestiary-2/jabberwock.json
  packs/pathfinder-monster-core/clay-effigy.json
  packs/pathfinder-monster-core/river-drake.json
  packs/pfs-season-1-bestiary/quests/ahrkinos-3-4.json
  packs/pfs-season-1-bestiary/quests/ahrkinos-5-6.json
  packs/pfs-season-6-bestiary/6-00/demonic-river-drake.json
  packs/pfs-season-6-bestiary/6-05/enraged-bun-the-black.json
  packs/prey-for-death-bestiary/alktherisa-and-omprisgor.json
  packs/shades-of-blood-bestiary/book-3-to-blot-out-the-sun/tokainens-chosen.json
  packs/sky-kings-tomb-bestiary/book-1-mantle-of-gold/unfeeling-empath.json
  packs/spore-war-bestiary/book-3-a-voice-in-the-blight/rift-pulper.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/reborn-sun-hunter.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/reborn-sun-mage.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/reborn-sun-warrior.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/cataclysm-beetle.json
Labels: pr: data update

#19279 Fix Earn Income Macro always trying to use Armor Check Penalty
  src/scripts/macros/earn-income/helpers.ts
Labels: pr: bugfix

#19324 Fix show/hide of Roll Options in Generate Check Prompt
  static/templates/gm/check-prompt.hbs
Labels: pr: bugfix

#19335 Add Weakness RE to Curse of Potent Poison
  packs/equipment-effects/effect-curse-of-potent-poison.json
Labels: pr: data update

#19334 Fix prototype token size link being applied even if disabled
  src/module/actor/base.ts
Labels: pr: bugfix, pr: foundry v13

#19330 Avoid prosemirror menu wrapping in item and hazard sheets
  src/module/actor/hazard/sheet.ts
  src/module/item/base/sheet/sheet.ts
  src/styles/_globals.scss
  src/styles/actor/character/_biography.scss
  src/styles/actor/hazard/_index.scss
  src/styles/actor/npc/_index.scss
  src/styles/actor/party/kingdom/_world.scss
  src/styles/item/_header.scss
  src/styles/item/_index.scss
  src/styles/item/_nav.scss
Labels: pr: bugfix, ui/ux

#19339 Add missing Ghost variant for SoG
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/ghost.json
  packs/spells/ritual/open-the-wall-of-ghosts.json
Labels: pr: data update

#19337 Fix the size of Unrisen Slithermaw
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/unrisen-slithermaw.json
Labels: pr: data update

#19313 Enable `AdjustModifier` predication on derived values and pass more options to the `Statistic` created for `@Check`
  src/module/rules/rule-element/adjust-modifier.ts
  src/module/system/text-editor.ts
Labels: pr: enhancement, pr: foundry v13

#19267 Handle actor size changes and token size updates in `ActorPF2e` descendant document lifecycle hooks
  src/module/actor/base.ts
  src/module/item/ancestry/document.ts
  src/module/item/base/document.ts
  types/foundry/common/abstract/_types.d.mts
Labels: pr: bugfix, pr: refactor, pr: foundry v13

#19326 Fix `WorldClock` not showing anything for players
  static/templates/system/world-clock.hbs
Labels: pr: bugfix, pr: foundry v13

#19355 Fix most character and character sheet type errors
  src/module/actor/character/document.ts
  src/module/actor/character/feats/collection.ts
  src/module/actor/character/sheet.ts
  types/foundry/client/applications/ux/text-editor.d.mts
Labels: pr: types update

#19352 Handle synchronization between actor size and token dimensions from scenes
  src/module/actor/base.ts
  src/module/actor/data/size.ts
  src/module/actor/npc/document.ts
  src/module/actor/vehicle/document.ts
  src/module/item/base/document.ts
  src/module/migration/migrations/939-set-token-dimensions.ts
  src/module/scene/document.ts
  src/module/scene/token-document/document.ts
  types/foundry/client/documents/actor.d.mts
  types/foundry/client/documents/token.d.mts
Labels: pr: bugfix

#19346 Fix Change domain text, update and sort deities
  packs/journals/domains.json
Labels: pr: data update

#19341 Add `area damage`, `area-effect` and `damaging-effect` options to more NPC abilities
  packs/abomination-vaults-bestiary/book-1-ruins-of-gauntlight/corpselight.json
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/nox.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/caligni-defender.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/galudu.json
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/padli.json
  packs/howl-of-the-wild-bestiary/warden-of-peaks-and-skies.json
  packs/kingmaker-bestiary/wild-hunt-horse.json
  packs/lost-omens-bestiary/shining-kingdoms/bibliodaemon.json
  packs/pathfinder-bestiary-2/caligni-slayer.json
  packs/pathfinder-bestiary-2/grodair.json
  packs/pathfinder-bestiary-3/caligni-vanguard.json
  packs/pathfinder-bestiary/mu-spore.json
  packs/pathfinder-bestiary/vrock.json
  packs/pathfinder-npc-core/engineer/gadgeteer.json
  packs/pfs-season-5-bestiary/5-19/hardened-locust-knight.json
  packs/pfs-season-5-bestiary/5-19/locust-knight.json
  packs/prey-for-death-bestiary/einherji-host.json
  packs/rage-of-elements-bestiary/vault-builder.json
  packs/rage-of-elements-bestiary/vault-keeper.json
  packs/season-of-ghosts-bestiary/book-2-let-the-leaves-fall/heart-eating-vulture.json
  packs/strength-of-thousands-bestiary/book-2-spoken-on-the-song-wind/great-grodair.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/soul-swarm.json
Labels: pr: data update

#19332 Fix some premasted text in TV items, fix some formatting mistakes
  packs/equipment/corruption-cassock.json
  packs/equipment/dragonscale-cameo.json
  packs/equipment/heartblood-ring.json
  packs/equipment/immovable-tripod.json
  packs/equipment/mukradi-jar.json
  packs/equipment/nightmare-salt.json
  packs/equipment/sanguine-fang-greater.json
  packs/equipment/sanguine-fang-major.json
  packs/equipment/sanguine-fang.json
  packs/equipment/scholars-drop.json
  packs/equipment/silver-crescent-greater.json
  packs/equipment/silver-crescent-lesser.json
  packs/equipment/silver-crescent-moderate.json
  packs/equipment/swallow-spike-greater.json
  packs/equipment/swallow-spike-major.json
  packs/equipment/theatrical-mutagen-major.json
  packs/equipment/tlil-mask-greater.json
  packs/equipment/unending-itch.json
  packs/equipment/unifying-emblem-lyrune-quah.json
  packs/equipment/unifying-emblem-shadde-quah.json
  packs/equipment/unifying-emblem-shriikirri-quah.json
  packs/equipment/unifying-emblem-shundar-quah.json
  packs/equipment/unifying-emblem-sklar-quah.json
  packs/equipment/unifying-emblem-tamiir-quah.json
  packs/equipment/vaultbreakers-harness.json
  packs/equipment/void-fragment.json
  packs/equipment/wasp-guard.json
  packs/equipment/weapon-shot-greater.json
  packs/equipment/weapon-shot-lesser.json
  packs/equipment/weapon-shot-major.json
  packs/equipment/weapon-shot-moderate.json
Labels: pr: data update

#19327 Update text on select Wrestler dedication feats to make sure it matches with PC2
  packs/feats/archetype/wrestler/disengaging-twist.json
  packs/feats/archetype/wrestler/elbow-breaker.json
  packs/feats/archetype/wrestler/form-lock.json
  packs/feats/archetype/wrestler/running-tackle.json
Labels: pr: data update

#19322 Update Werebat actors Change Shape automation
  packs/pathfinder-bestiary-3/werebat.json
  packs/pfs-season-3-bestiary/3-13/werebat-pfs-3-13.json
  packs/rusthenge-bestiary/starving-werebat.json
  packs/shades-of-blood-bestiary/book-1-thirst-for-blood/werebat-warrior.json
Labels: pr: data update

#19316 Automate Bellflower Tiller's Scarecrow
  packs/feats/archetype/bellflower-tiller/scarecrow.json
Labels: pr: data update

#19359 Remove unneeded flat check from Wild Hunt Archer
  packs/kingmaker-bestiary/wild-hunt-archer.json
Labels: pr: data update

#19358 Add `area damage`, `area-effect` and `damaging-effect` options to more NPC abilities
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/dulac.json
  packs/age-of-ashes-bestiary/book-6-broken-promises/ingnovims-assistant.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/benefactors-end.json
  packs/book-of-the-dead-bestiary/relictner-eroder.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/yoh-souran.json
  packs/kingmaker-bestiary/horagnamon.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/chemical-zombie.json
  packs/pathfinder-bestiary-2/frost-worm.json
  packs/pathfinder-bestiary-3/sulfur-zombie.json
  packs/pathfinder-bestiary-3/tiddalik.json
  packs/pathfinder-bestiary/balor.json
  packs/pathfinder-dark-archive/k-h-w-s-echo.json
  packs/pathfinder-monster-core/coarti.json
  packs/pathfinder-npc-core/seafarer/subaquatic-marauder.json
  packs/pfs-season-4-bestiary/4-15/combustive-zombie.json
  packs/pfs-season-4-bestiary/4-15/elite-combustive-zombie.json
  packs/pfs-season-4-bestiary/4-15/elite-sulfur-zombie.json
  packs/pfs-season-5-bestiary/5-14/ghostknife-gardener.json
  packs/pfs-season-5-bestiary/5-14/tough-ghostknife-gardener.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/pakano-level-12.json
  packs/rage-of-elements-bestiary/ardande-gardener.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/gold-defender-garrison.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/gold-defender.json
Labels: pr: data update

#19345 Add REs to Walking Cauldron
  packs/equipment/walking-cauldron.json
  static/lang/re-en.json
Labels: pr: data update

#19362 Add automation to `Spinebreaker`, `Suplex`, and `Submission Hold` feats
  packs/feats/archetype/wrestler/spinebreaker.json
  packs/feats/archetype/wrestler/submission-hold.json
  packs/feats/archetype/wrestler/suplex.json
  static/lang/re-en.json
Labels: pr: data update

#19357 Update select `Werecreature` actors' Change Shape automation
  packs/pathfinder-monster-core/werebear.json
  packs/pathfinder-monster-core/wererat.json
  packs/pathfinder-monster-core/weretiger.json
  packs/pathfinder-monster-core/werewolf.json
  packs/pfs-season-3-bestiary/3-13/weretiger-pfs-3-13.json
Labels: pr: data update

#19367 Also copy over dependent tokens in actor clone during item preCreate
  src/module/actor/base.ts
  types/foundry/client/documents/actor.d.mts
  types/foundry/common/utils/iterable-weak-map.d.mts
  types/foundry/common/utils/iterable-weak-set.d.mts
Labels: pr: bugfix

#19369 Fix Great Bear localization keys
  packs/feats/archetype/ursine-avenger-hood/great-bear.json
Labels: localization

#19368 Release Notes 7.2.0
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#19376 Fix Hexing Jar RE localization key
  packs/equipment/hexing-jar.json
Labels: pr: data update

#19365 Rename ActorCommitData to ActorGroupUpdate and add deletes
  src/module/actor/base.ts
  src/module/actor/helpers.ts
  src/module/actor/inventory/index.ts
  src/module/actor/spellcasting.ts
  src/module/actor/types.ts
  src/module/rules/rule-element/special-resource.ts
Labels: pr: refactor

#19373 Add `area damage`, `area-effect` and `damaging-effect` options to even more NPC abilities
  packs/abomination-vaults-bestiary/abomination-vaults-hardcover-compilation/caliddo-haruvex.json
  packs/agents-of-edgewatch-bestiary/book-6-ruins-of-the-radiant-siege/graveknight-of-kharnas.json
  packs/bestiary-family-ability-glossary/graveknight/graveknight-devastating-blast.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/pokmit-bloody-pike.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/seldeg-bheldis.json
  packs/book-of-the-dead-bestiary/fiddling-bones.json
  packs/book-of-the-dead-bestiary/graveknight-warmaster.json
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/seldeg-bhedlis.json
  packs/extinction-curse-bestiary/book-5-lord-of-the-black-sands/shraen-graveknight.json
  packs/kingmaker-bestiary/kellid-graveknight.json
  packs/kingmaker-bestiary/korog.json
  packs/pathfinder-bestiary-2/destrachan.json
  packs/pathfinder-monster-core/boggard-swampseer.json
  packs/pathfinder-monster-core/conspirator-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-adult.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-ancient.json
  packs/pathfinder-monster-core/conspirator-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/conspirator-dragon-young.json
  packs/pathfinder-monster-core/graveknight.json
  packs/pfs-season-1-bestiary/1-20/boggard-swampseer-pfs-1-24.json
  packs/pfs-season-1-bestiary/1-20/elite-boggard-swampseer-pfs-1-24-animal-staff.json
  packs/pfs-season-1-bestiary/1-20/elite-boggard-swampseer-pfs-1-24-staff.json
  packs/prey-for-death-bestiary/vatumledor.json
  packs/seven-dooms-for-sandpoint-bestiary/ripnugget.json
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/captain-talymir.json
  packs/strength-of-thousands-bestiary/book-3-hurricanes-howl/bharlen-sajor.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/gold-defender.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/graveknight-captain.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/graveknight-champion.json
  packs/triumph-of-the-tusk-bestiary/book-2-hoof-cinder-and-storm/skeletal-drummer.json
  packs/triumph-of-the-tusk-bestiary/book-3-destroyers-doom/graveknight-umbra.json
  packs/triumph-of-the-tusk-bestiary/book-3-destroyers-doom/orc-raider.json
Labels: pr: data update

#19379 Fix minor typecast issue for striking synthetics
  src/module/system/damage/weapon.ts
Labels: pr: types update

#19381 Prioritize controlled token for linked actors in attack roll
  src/module/actor/roll-context/base.ts
Labels: pr: bugfix

#19382 Fix deletion-entry values in migration 731
  src/module/migration/migrations/731-toggle-property-to-roll-option.ts
Labels: pr: bugfix

#19374 Add effects to `Play to the Crowd` Gladiator feat
  packs/feat-effects/effect-play-to-the-crowd-ac-bonus.json
  packs/feat-effects/effect-play-to-the-crowd-attack-roll-bonus.json
  packs/feat-effects/effect-play-to-the-crowd-temporary-hit-points.json
  packs/feats/archetype/gladiator/play-to-the-crowd.json
Labels: pr: data update

#19387 Improve reliability of delta inputs when chaining inputs
  src/module/actor/sheet/base.ts
Labels: pr: enhancement

#19388 Add Myth-speaker Player's Guide deity options to the Domain journal
  packs/journals/domains.json
Labels: pr: data update

#19366 Add Language AELike REs to Chokers of Elocution
  packs/equipment/choker-of-elocution-greater.json
  packs/equipment/choker-of-elocution.json
Labels: pr: data update

#19363 Brush up Fiery Body spell effect and redirect 9th Rank version
  build/uuid-redirects.json
  packs/extinction-curse-bestiary/book-6-the-apocalypse-prophet/saurian-worldwatcher.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/blood-hag.json
  packs/pathfinder-bestiary-3/underworld-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/red-dragon-ancient-spellcaster.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/summer-hora-queen.json
  packs/spell-effects/spell-effect-fiery-body-9th-level.json
  packs/spell-effects/spell-effect-fiery-body.json
Labels: pr: data update

#19400 Add `area damage`, `area-effect` and `damaging-effect` options to even more NPC abilities
  packs/claws-of-the-tyrant-bestiary/2-ashes-for-ozem/engerra.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/thessekka.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/xulgath-stoneliege.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/arms-of-balance-ranya-shibhatesh.json
  packs/howl-of-the-wild-bestiary/sky-fisher.json
  packs/howl-of-the-wild-bestiary/warden-of-caverns-and-burrows.json
  packs/lost-omens-bestiary/impossible-lands/fleshforged-dreadnought.json
  packs/lost-omens-bestiary/monsters-of-myth/imperfect-automaton.json
  packs/pathfinder-bestiary-2/zomok.json
  packs/pathfinder-bestiary-3/forest-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/forest-dragon-adult.json
  packs/pathfinder-bestiary-3/forest-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/forest-dragon-ancient.json
  packs/pathfinder-dark-archive/the-weaver-in-dreams.json
  packs/pathfinder-monster-core/aiuvarin-elementalist.json
  packs/pathfinder-monster-core/elananx.json
  packs/pfs-season-2-bestiary/2-20/yeth-warbeast.json
  packs/pfs-season-4-bestiary/4-06/infested-clockwork-vessel.json
  packs/pfs-season-4-bestiary/4-06/possessed-clockwork-vessel.json
  packs/rage-of-elements-bestiary/pelegox-cube.json
  packs/rage-of-elements-bestiary/picture-in-clouds.json
  packs/stolen-fate-bestiary/book-1-the-choosing/queen-kawlinawk.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/ephialtes.json
Labels: pr: data update

#19409 Correct spelling of khakkhara in Noble Branch class feature
  packs/classfeatures/noble-branch.json
Labels: pr: data update

#19404 Add `area-effect` to Picture-in-Clouds' Elephant Blast
  packs/rage-of-elements-bestiary/picture-in-clouds.json
Labels: pr: data update

#19403 Add spellshape options to `Codex of Destruction and Renewal`
  packs/equipment/codex-of-destruction-and-renewal.json
  static/lang/re-en.json
Labels: pr: data update

#19414 Fix some localization keys
  packs/feats/ancestry/versatile-heritages/dragonblood/scaly-hide.json
  packs/feats/archetype/halcyon-speaker/speak-for-the-gravelands.json
Labels: pr: data update

#19402 Add automation to `Fortune's Coin` items
  packs/equipment/fortunes-coin-platinum.json
  packs/equipment/fortunes-coin.json
Labels: pr: data update

#19417 Update Azarketi Crab Catcher and Azarketi Tide Tamer's strikes
  packs/pathfinder-monster-core/azarketi-crab-catcher.json
  packs/pathfinder-monster-core/azarketi-tide-tamer.json
Labels: pr: data update

#19418 Add `area damage`, `area-effect` and `damaging-effect` options to select NPC abilities
  packs/blood-lords-bestiary/book-2-graveclaw/animated-fireplace.json
  packs/curtain-call-bestiary/book-2-singer-stalker-skinsaw-man/animated-boiler.json
  packs/kingmaker-bestiary/fionn.json
  packs/pathfinder-bestiary-2/icewyrm.json
  packs/pathfinder-bestiary-2/star-archon.json
  packs/pathfinder-bestiary-3/animated-furnace.json
  packs/pathfinder-bestiary-3/stone-lion.json
  packs/pathfinder-monster-core/firewyrm.json
  packs/pathfinder-monster-core/snow-oni.json
  packs/pfs-season-3-bestiary/bounties/explosive-rat.json
  packs/pfs-season-5-bestiary/5-10/pampla.json
  packs/pfs-season-5-bestiary/5-11/elite-mutant-cryptid-snapdrake.json
  packs/pfs-season-5-bestiary/5-11/mutant-cryptid-pine-pangolin.json
  packs/pfs-season-5-bestiary/5-11/steadied-dohv-dranna.json
  packs/rage-of-elements-bestiary/talos-gadgeteer.json
  packs/shades-of-blood-bestiary/book-2-the-broken-palace/yobnobby.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/wrath-riot.json
  packs/triumph-of-the-tusk-bestiary/book-2-hoof-cinder-and-storm/magical-forge.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/drinesh.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/ruzadoyas-chosen.json
  packs/wardens-of-wildwood-bestiary/book-2-severed-at-the-root/unaasi.json
Labels: pr: data update

#19406 Adjust DC of invested items with Intensify Investiture
  packs/feats/class/thaumaturge/intensify-investiture.json
Labels: pr: data update

#19419 Add notes to select Spellshape feats and brush up `Codex of Destruction and Renewal's` Rule Elements and localization
  packs/equipment/codex-of-destruction-and-renewal.json
  packs/equipment/walking-cauldron.json
  packs/feats/archetype/halcyon-speaker/synergistic-spell.json
  packs/feats/class/sorcerer/echoing-spell.json
  packs/feats/class/wizard/worldsphere-gravity.json
  static/lang/re-en.json
Labels: pr: data update

#19421 Add escape actions to select NPC abilities
  packs/age-of-ashes-bestiary/book-4-fires-of-the-haunted-city/carnivorous-crystal.json
  packs/agents-of-edgewatch-bestiary/book-2-sixty-feet-under/life-magnet.json
  packs/agents-of-edgewatch-bestiary/book-2-sixty-feet-under/vaultbreaker-ooze.json
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/minchgorm.json
  packs/agents-of-edgewatch-bestiary/book-5-belly-of-the-black-whale/mother-venom.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/soul-slime.json
  packs/crown-of-the-kobold-king-bestiary/lodestone-trap.json
  packs/extinction-curse-bestiary/book-4-siege-of-the-dinosaurs/tallow-ooze.json
  packs/extinction-curse-bestiary/book-5-lord-of-the-black-sands/iffdahsil.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/canopy-elder.json
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/demontangle.json
  packs/kingmaker-bestiary/kargstaad.json
  packs/kingmaker-bestiary/kargstaads-giant.json
  packs/one-shot-bestiary/a-fistful-of-flowers/meliosas-leshy-mint-leshy.json
  packs/pathfinder-bestiary-2/carnivorous-blob.json
  packs/pathfinder-bestiary-2/giant-amoeba.json
  packs/pathfinder-bestiary-2/lerritan.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient.json
  packs/pathfinder-bestiary-2/zomok.json
  packs/pathfinder-bestiary/drider.json
  packs/pathfinder-bestiary/ether-spider.json
  packs/pathfinder-bestiary/gelatinous-cube.json
  packs/pathfinder-bestiary/gibbering-mouther.json
  packs/pathfinder-bestiary/mimic.json
  packs/pathfinder-bestiary/shoggoth.json
  packs/pathfinder-bestiary/wemmuth.json
  packs/pathfinder-bestiary/zaramuun.json
  packs/pathfinder-dark-archive/entrapping-chair.json
  packs/pfs-season-1-bestiary/1-25/lightning-platform-5-6.json
  packs/pfs-season-1-bestiary/1-25/lightning-platform-7-8.json
  packs/pfs-season-2-bestiary/2-11/famished-mimic.json
  packs/pfs-season-2-bestiary/2-16/wishbound-mist-stalker-5-6.json
  packs/pfs-season-2-bestiary/2-16/wishbound-mist-stalker-7-8.json
  packs/pfs-season-2-bestiary/2-18/sticky-web-lurker-noose.json
  packs/pfs-season-3-bestiary/3-17/waking-nightmare.json
  packs/pfs-season-3-bestiary/3-17/waking-terror.json
  packs/pfs-season-6-bestiary/6-07/oozeshard.json
  packs/quest-for-the-frozen-flame-bestiary/book-2-lost-mammoth-valley/cave-in.json
  packs/quest-for-the-frozen-flame-bestiary/book-3-burning-tundra/hegremon.json
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/sinmold.json
  packs/spore-war-bestiary/book-3-a-voice-in-the-blight/fungal-abomination.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/reborn-sun-warrior.json
Labels: pr: data update

#19429 Add `area damage`, `area-effect` and `damaging-effect` options to another round of NPC abilities
  packs/blood-lords-bestiary/book-3-field-of-maidens/wheel-archon.json
  packs/extinction-curse-bestiary/book-2-legacy-of-the-lost-god/iridescent-elephant.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/sanzuwu.json
  packs/gatewalkers-bestiary/book-1-the-seventh-arch/desa-desa.json
  packs/menace-under-otari-bestiary/caligni-hunter-bb.json
  packs/menace-under-otari-bestiary/sewer-ooze-bb.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/iblydan-hind.json
  packs/pathfinder-bestiary-3/gathlain-wanderer.json
  packs/pathfinder-monster-core/caligni-hunter.json
  packs/pathfinder-monster-core/giylea.json
  packs/pathfinder-monster-core/magma-worm.json
  packs/pathfinder-monster-core/sewer-ooze.json
  packs/pathfinder-npc-core/official/watchmage-squadron.json
  packs/pfs-introductions-bestiary/swamp-ooze.json
  packs/pfs-season-1-bestiary/quests/elite-sewer-ooze-q9.json
  packs/pfs-season-1-bestiary/quests/injured-sewer-ooze.json
  packs/pfs-season-5-bestiary/quests/angry-mercenary-squad.json
  packs/pfs-season-5-bestiary/quests/elite-sewer-ooze-pfs-q18.json
  packs/pfs-season-5-bestiary/quests/mercenary-squad.json
  packs/pfs-season-5-bestiary/quests/weak-sewer-ooze-pfs-q18.json
  packs/prey-for-death-bestiary/gorumite-infantry.json
  packs/strength-of-thousands-bestiary/book-2-spoken-on-the-song-wind/mutated-sewer-ooze.json
Labels: pr: data update

#19435 Add slug to Barghest's Unhealing Wound
  packs/pathfinder-monster-core/barghest.json
Labels: pr: data update

#19436 Add `area damage`, `area-effect` and `damaging-effect` options to even more NPC abilities
  packs/age-of-ashes-bestiary/book-4-fires-of-the-haunted-city/accursed-forge-spurned.json
  packs/age-of-ashes-bestiary/book-4-fires-of-the-haunted-city/forge-spurned.json
  packs/age-of-ashes-bestiary/book-6-broken-promises/xotani-the-firebleeder.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/agorron-guard.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/graelar-the-whisper.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/kelganth.json
  packs/blood-lords-bestiary/book-5-a-taste-of-ashes/sorvinaesen.json
  packs/book-of-the-dead-bestiary/iruxi-ossature.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/yaganty.json
  packs/extinction-curse-bestiary/book-5-lord-of-the-black-sands/obsidian-golem.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/drake-courser.json
  packs/howl-of-the-wild-bestiary/vibrant-pup-swarm.json
  packs/kingmaker-bestiary/enormous-flame-drake.json
  packs/lost-omens-bestiary/tian-xia-world-guide/imugi.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/pyrefowl.json
  packs/pathfinder-bestiary-2/umonlee.json
  packs/pathfinder-bestiary-3/tomb-giant.json
  packs/pathfinder-monster-core/aesra.json
  packs/pathfinder-monster-core/flame-drake.json
  packs/pathfinder-monster-core/frost-drake.json
  packs/pfs-season-6-bestiary/6-11/ascending-xalreonshin.json
  packs/rage-of-elements-bestiary/boiling-spring.json
  packs/rage-of-elements-bestiary/coldmire-pond.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/zellara-esmeranda.json
  packs/strength-of-thousands-bestiary/book-6-shadows-of-the-ancients/red-guard-ant.json
Labels: pr: data update

#19443 Avoid double processing markdown in addenda
  src/module/item/base/data/system.ts
  src/module/item/base/document.ts
Labels: pr: bugfix

#19446 Default Brass Dwarf's initial resistance selection to fire
  packs/equipment/the-brass-dwarf.json
Labels: pr: data update

#19432 Ensure Compliant Gold's Item Alteration adds reach to chosen ikon
  packs/feats/class/exemplar/compliant-gold.json
Labels: pr: data update

#19447 Fix several small errors in PFS actors
  packs/pfs-season-6-bestiary/6-18/burning-silver-najid.json
  packs/pfs-season-6-bestiary/6-18/najid-ouidda.json
  packs/pfs-season-6-bestiary/6-19/deskari-locust-swarm.json
  packs/pfs-season-6-bestiary/6-19/greater-deskari-locust-swarm.json
  packs/pfs-season-6-bestiary/6-19/pitborn-fire-giant-cavalry.json
  packs/pfs-season-6-bestiary/6-19/the-husk-of-deskari-13-14.json
  packs/pfs-season-6-bestiary/6-19/the-husk-of-deskari.json
Labels: pr: data update

#19444 Refresh Seelah's Iconic actor sheets
  packs/iconics/seelah-level-1.json
  packs/iconics/seelah-level-3.json
  packs/iconics/seelah-level-5.json
Labels: pr: data update

#19450 Remove fey trait from Mandragora's Blood Scent and Blood Drain abilities
  packs/kingmaker-bestiary/immense-mandragora.json
  packs/kingmaker-bestiary/mandragora-swarm.json
  packs/pathfinder-bestiary-2/mandragora.json
  packs/wardens-of-wildwood-bestiary/book-1-packbreaker/wraithvine-offshoot.json
Labels: pr: data update

#19453 Add icons to select Deities
  packs/deities/covenants/esoteric-order-of-the-palatine-eye.json
  packs/deities/other-gods/emmeton-galardaria.json
  packs/deities/other-gods/izuyaku.json
  packs/deities/philosophies/prophecies-of-kalistrade.json
Labels: pr: data update

#19431 Add effects for Called Shot and Targeting Finisher
  packs/feat-effects/effect-called-shot-critical.json
  packs/feat-effects/effect-called-shot.json
  packs/feat-effects/effect-revitalizing-finisher.json
  packs/feat-effects/effect-targeting-finisher-critical.json
  packs/feat-effects/effect-targeting-finisher.json
  packs/feat-effects/stance-twinned-defense.json
  packs/feats/class/gunslinger/called-shot.json
  packs/feats/class/swashbuckler/distracting-toss.json
  packs/feats/class/swashbuckler/get-used-to-disappointment.json
  packs/feats/class/swashbuckler/targeting-finisher.json
Labels: pr: data update

#19428 Grant quickened condition with Panache Paragon and add Will save to Vivacious Afterimage
  packs/feats/class/swashbuckler/panache-paragon.json
  packs/feats/class/swashbuckler/vivacious-afterimage.json
Labels: pr: data update

#19451 Adjust positioning of traits and spacing between chat elements
  src/module/item/base/document.ts
  src/styles/legacy/_chat.scss
  static/templates/chat/action-card.hbs
  static/templates/chat/armor-card.hbs
  static/templates/chat/backpack-card.hbs
  static/templates/chat/campaign-feature-card.hbs
  static/templates/chat/consumable-card.hbs
  static/templates/chat/equipment-card.hbs
  static/templates/chat/feat-card.hbs
  static/templates/chat/shield-card.hbs
  static/templates/chat/spell-card.hbs
  static/templates/chat/weapon-card.hbs
Labels: ui/ux

#19457 Allow other Strikes to be made with Stonestrike Stance
  packs/actions/stonestrike-stance.json
  packs/feat-effects/stance-stonestrike-stance.json
Labels: pr: data update

#19420 Exclude flat checks from adjusting `inline-dc`
  src/module/system/text-editor.ts
Labels: pr: enhancement

#19462 Remove duplicate buttons in user config
  static/templates/user/sheet.hbs
Labels: pr: bugfix

#19470 Lift basic tag color variable to base colors
  src/styles/_colors.scss
  src/styles/_tags.scss
Labels: pr: refactor, ui/ux

#19476 Add `area damage`, `area-effect` and `damaging-effect` options to more NPC abilities
  packs/blood-lords-bestiary/book-1-zombie-feast/crooked-coffin-brewer.json
  packs/curtain-call-bestiary/book-1-stage-fright/ockomlire.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/bugul-noz.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/flying-mountain-kaminari.json
  packs/gatewalkers-bestiary/book-1-the-seventh-arch/bolan-nogasso.json
  packs/howl-of-the-wild-bestiary/thruneosaurus-rex.json
  packs/howl-of-the-wild-bestiary/warden-of-oceans-and-rivers.json
  packs/lost-omens-bestiary/highhelm/grand-defender.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/broken-centurion.json
  packs/pathfinder-bestiary-2/bastion-archon.json
  packs/pathfinder-bestiary-2/spiral-centurion.json
  packs/pathfinder-bestiary-3/skeleton-infantry.json
  packs/pathfinder-monster-core/ice-linnorm.json
  packs/pfs-season-1-bestiary/1-22/dockhand-cultist.json
  packs/pfs-season-3-bestiary/3-08/iron-ring-deckhand.json
  packs/season-of-ghosts-bestiary/book-1-the-summer-that-never-was/fan-hongrui.json
  packs/season-of-ghosts-bestiary/book-1-the-summer-that-never-was/red-hooded-thatchling.json
  packs/sky-kings-tomb-bestiary/book-2-cult-of-the-cave-worm/hryngar-forgepriest.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/demonic-rabble.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/raven-nicoletta.json
  packs/wardens-of-wildwood-bestiary/book-1-packbreaker/besieged-logging-crew.json
Labels: pr: data update

#19467 Add effects for Electromuscular Stimulator
  packs/equipment-effects/effect-electromuscular-stimulator-failure.json
  packs/equipment-effects/effect-electromuscular-stimulator.json
  packs/equipment/electromuscular-stimulator.json
Labels: pr: data update

#19473 Automate Greenwatcher's cold iron Strikes and critical hit Note
  packs/feats/class/investigator/empiricists-eye.json
  packs/feats/class/investigator/foresee-danger.json
  packs/feats/class/investigator/just-as-planned.json
  packs/feats/class/investigator/just-one-more-thing.json
  packs/feats/class/investigator/person-of-interest.json
  packs/feats/class/investigator/suspect-of-opportunity.json
  packs/feats/class/shared-class-feats/greenwatcher.json
  static/lang/re-en.json
Labels: pr: data update

#19482 Add spellwatch to armor property runes list
  src/module/item/armor/values.ts
  src/module/item/physical/runes.ts
  static/lang/en.json
Labels: pr: data update

#19491 Add a basic Raised Cavalry actor (minimal/no rule elements)
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/raised-cavalry.json
Labels: pr: data entry

#19487 Fix several typos in PFS actors
  packs/pfs-season-6-bestiary/6-19/greater-kithangian.json
  packs/pfs-season-6-bestiary/6-19/pitborn-fire-giant-cavalry.json
  packs/pfs-season-6-bestiary/6-19/the-husk-of-deskari-13-14.json
  packs/pfs-season-6-bestiary/6-19/the-husk-of-deskari.json
Labels: pr: data update

#19493 Add automation and brush up to Raised Cavalry Actor
  packs/claws-of-the-tyrant-bestiary/3-of-blood-and-faith/raised-cavalry.json
Labels: pr: data update

#19484 Add `area damage`, `area-effect` and `damaging-effect` options to another round of NPC abilities
  packs/blood-lords-bestiary/book-4-the-ghouls-hunger/nydazuul.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/rivka-cimurlian.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/rivka-igroon.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/rivka-kujiba.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/rivka-mogaru.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-2-ready-fight/rivka-yorak.json
  packs/gatewalkers-bestiary/book-2-they-watched-the-stars/sickly-eshmok.json
  packs/howl-of-the-wild-bestiary/hexmoth.json
  packs/lost-omens-bestiary/shining-kingdoms/beiran.json
  packs/myth-speaker-bestiary/book-1-the-acropolis-pyre/speiroikos.json
  packs/outlaws-of-alkenstar-bestiary/book-3-the-smoking-gun/cranium-preserver.json
  packs/pathfinder-bestiary-2/ice-golem.json
  packs/pathfinder-bestiary-3/grioth-cultist.json
  packs/pathfinder-bestiary-3/pufferfish.json
  packs/pathfinder-monster-core/augnagar.json
  packs/pathfinder-monster-core/elemental-inferno.json
  packs/pathfinder-monster-core/rune-giant.json
  packs/quest-for-the-frozen-flame-bestiary/book-2-lost-mammoth-valley/bargott.json
  packs/sky-kings-tomb-bestiary/book-3-heavy-is-the-crown/flames-of-taargick.json
  packs/spore-war-bestiary/book-1-whispers-in-the-dirt/eshmok.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/creeping-cone-swarm.json
Labels: pr: data update

#19389 Remove actor clone from inventory preparation
  src/module/actor/sheet/base.ts
Labels: pr: enhancement

#19311 Fix type of AnyChoiceField and add form support
  src/module/system/schema-data-fields.ts
  types/foundry/common/data/fields.d.mts
Labels: pr: refactor

#19500 Check whether actor is owned before adding token to update batch
  src/module/scene/token-document/document.ts
  types/foundry/client/documents/collections/users.d.mts
Labels: pr: bugfix

#19504 Remove errant weapon data from Belt of Good Health
  packs/equipment/belt-of-good-health.json
Labels: pr: data update

#19497 Add effect and spell description addendum to Chaotic Spell
  packs/feat-effects/effect-chaotic-spell.json
  packs/feats/class/shared-class-feats/chaotic-spell.json
  static/lang/re-en.json
Labels: pr: data update

#19496 Update skill suboption dropdowns to use config list
  packs/feats/ancestry/elf/ancestral-longevity.json
  packs/feats/ancestry/elf/expert-longevity.json
  packs/feats/ancestry/ghoran/ancient-memories.json
  packs/feats/ancestry/ghoran/endless-memories.json
  packs/feats/ancestry/leshy/ageless-spirit.json
  packs/feats/class/investigator/flexible-studies.json
  packs/paizo-pregens/mark-of-the-mantis/eteleon.json
Labels: pr: data update

#19492 Automate and update formatting of Greater Spiritual Evolution
  packs/feats/class/sorcerer/greater-spiritual-evolution.json
Labels: pr: data update

#19465 Automate several permanent quickened-granting features
  packs/age-of-ashes-bestiary/book-6-broken-promises/inizra-arumelo.json
  packs/blood-lords-bestiary/book-6-ghost-kings-rage/mithral-golem.json
  packs/classfeatures/abundant-vials.json
  packs/feats/archetype/artillerist/master-siege-engineer.json
  packs/feats/class/bard/eternal-composition.json
  packs/feats/class/fighter/weapon-supremacy.json
  packs/feats/class/gunslinger/perfect-readiness.json
  packs/feats/class/inventor/full-automation.json
  packs/feats/class/investigator/just-the-facts.json
  packs/feats/class/investigator/thorough-research.json
  packs/feats/class/kineticist/kinetic-pinnacle.json
  packs/feats/class/magus/supreme-spellstrike.json
  packs/feats/class/monk/enduring-quickness.json
  packs/feats/class/summoner/eternal-boost.json
  packs/lost-omens-bestiary/monsters-of-myth/kothogaz-dance-of-disharmony.json
  packs/pathfinder-bestiary-3/danava-titan.json
  packs/pathfinder-bestiary-3/mithral-golem.json
  packs/prey-for-death-bestiary/silver-saber.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/nornhound.json
  static/lang/re-en.json
Labels: pr: data update

#19466 Add Pointed Question effect and other minor investigator fixes
  packs/actions/pointed-question.json
  packs/feat-effects/effect-devise-a-stratagem.json
  packs/feat-effects/effect-pointed-question.json
  packs/feat-effects/effect-surgical-shock-failure.json
  packs/feats/class/investigator/all-the-time-in-the-world.json
  packs/feats/class/investigator/lead-investigator.json
  packs/feats/class/investigator/make-em-sweat.json
  packs/feats/class/investigator/share-tincture.json
  packs/feats/class/investigator/surgical-shock.json
  packs/feats/class/shared-class-feats/sense-the-unseen.json
Labels: pr: data update

#19479 Add effect for Bugul Noz's Haunting Wail
  packs/bestiary-effects/effect-haunting-wail.json
  packs/extinction-curse-bestiary/book-3-lifes-long-shadows/bugul-noz.json
Labels: pr: data update

#19483 Add description addendum to 1-action spellshapes with Spellshape Mastery
  packs/feats/class/shared-class-feats/spellshape-mastery.json
  packs/feats/class/sorcerer/ruby-resurrection.json
  packs/feats/class/sorcerer/tenacious-blood-magic.json
Labels: pr: data update

#19506 Fix the level and price of Dr. Ushernacht's Astonishing Ink (Major)
  packs/equipment/dr-ushernachts-astonishing-ink-major.json
Labels: pr: data update

#19508 Omit Bravado notes if the character already has Panache
  packs/classfeatures/panache.json
  packs/classfeatures/patron-theme.json
  packs/iconics/jirelle-level-1.json
  packs/iconics/jirelle-level-3.json
  packs/iconics/jirelle-level-5.json
Labels: pr: data update

#19509 Add effect for Sympathetic Strike and correct its action cost and frequency
  packs/feat-effects/effect-portents-of-the-haruspex.json
  packs/feat-effects/effect-sympathetic-strike.json
  packs/feats/class/witch/sympathetic-strike.json
  packs/feats/class/witch/wild-witchs-armaments.json
  packs/feats/class/witch/witchs-armaments.json
  static/lang/re-en.json
Labels: pr: data update

#19515 Add Oversized Throw effect
  packs/feat-effects/effect-oversized-throw.json
  packs/feats/class/barbarian/oversized-throw.json
  packs/feats/class/barbarian/second-wind.json
  static/lang/re-en.json
Labels: pr: data update

#19521 Update Inveigle to PC2 Description
  packs/spells/ritual/inveigle.json
Labels: pr: data update

#19520 Add `area damage`, `area-effect` and `damaging-effect` options to another round of NPC abilities
  packs/abomination-vaults-bestiary/book-3-eyes-of-empty-death/bright-walker.json
  packs/age-of-ashes-bestiary/book-4-fires-of-the-haunted-city/dalos.json
  packs/blood-lords-bestiary/book-3-field-of-maidens/aeolaeka.json
  packs/equipment/hunters-anthem.json
  packs/fall-of-plaguestone/giant-lightning-serpent.json
  packs/howl-of-the-wild-bestiary/magnetic-gecko.json
  packs/lost-omens-bestiary/impossible-lands/quantium-golem-acid.json
  packs/lost-omens-bestiary/impossible-lands/quantium-golem-electricity.json
  packs/lost-omens-bestiary/mwangi-expanse/solar-ibis.json
  packs/pathfinder-bestiary/white-dragon-young.json
  packs/pathfinder-monster-core/aeolaeka.json
  packs/pfs-season-1-bestiary/1-15/leshy-crafter-1-2.json
  packs/pfs-season-1-bestiary/1-15/leshy-crafter-3-4.json
  packs/pfs-season-2-bestiary/2-02/kayajima-guardian-dogu-3-4.json
  packs/pfs-season-2-bestiary/2-02/kayajima-guardian-dogu-5-6.json
  packs/rage-of-elements-bestiary/living-magma.json
  packs/rage-of-elements-bestiary/twins-of-rowan.json
  packs/spore-war-bestiary/book-2-the-secret-of-deathstalk-tower/shalelu-andosana.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/gold-defender-garrison.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/gold-defender.json
  packs/wardens-of-wildwood-bestiary/book-3-shepherd-of-decay/gritblight.json
Labels: pr: data update

#19524 Clean up schema types/implementation of `RollOption` suboptions
  src/module/rules/rule-element/roll-option/data.ts
  src/module/rules/rule-element/roll-option/rule-element.ts
  src/module/system/schema-data-fields.ts
Labels: pr: bugfix

#19530 Reduce gap between certain character details to closer match v12
  src/styles/_forms.scss
  src/styles/actor/vehicle/_index.scss
Labels: ui/ux

#19514 Create encumbrance css color variables
  src/styles/_colors.scss
  src/styles/actor/_inventory.scss
Labels: pr: refactor, ui/ux

#19531 Add `area damage`, `area-effect` and `damaging-effect` options to more NPC abilities
  packs/abomination-vaults-bestiary/book-2-hands-of-the-devil/dreshkan.json
  packs/age-of-ashes-bestiary/book-4-fires-of-the-haunted-city/dalos.json
  packs/age-of-ashes-bestiary/book-4-fires-of-the-haunted-city/lazurite-infused-stone-golem.json
  packs/blood-lords-bestiary/book-2-graveclaw/teaching-assistant.json
  packs/fists-of-the-ruby-phoenix-bestiary/book-3-king-of-the-mountain/bul-gae.json
  packs/kingmaker-bestiary/whimwyrm.json
  packs/lost-omens-bestiary/monsters-of-myth/storm-discharge.json
  packs/lost-omens-bestiary/tian-xia-world-guide/bul-gae.json
  packs/outlaws-of-alkenstar-bestiary/book-2-cradle-of-quartz/sabora-sharkosa.json
  packs/pathfinder-bestiary-2/filth-fire.json
  packs/pathfinder-bestiary-2/thunderbird.json
  packs/pathfinder-bestiary-3/skeleton-infantry.json
  packs/pathfinder-monster-core/crag-linnorm.json
  packs/pfs-season-2-bestiary/2-05/spark-troll-1-2.json
  packs/pfs-season-2-bestiary/2-05/spark-troll-3-4.json
  packs/pfs-season-3-bestiary/3-01/filth-fire-pfs-3-01.json
  packs/rage-of-elements-bestiary/brass-bastion.json
  packs/rage-of-elements-bestiary/zuhra-shuyookh.json
  packs/shadows-at-sundown-bestiary/abridan-ashau.json
  packs/shadows-at-sundown-bestiary/lorthact.json
  packs/stolen-fate-bestiary/book-2-the-destiny-war/demongate-colossus.json
  packs/stolen-fate-bestiary/book-3-worst-of-all-possible-worlds/mighty-bul-gae.json
  packs/strength-of-thousands-bestiary/book-4-secrets-of-the-temple-city/sunburst-corpse.json
Labels: pr: data update

#19533 Condense Quantium Golem actor variants
  build/uuid-redirects.json
  packs/lost-omens-bestiary/impossible-lands/quantium-golem-acid.json
  packs/lost-omens-bestiary/impossible-lands/quantium-golem.json
  static/lang/re-en.json
Labels: pr: data update

#19541 Fix the @Check in Primadonna
  packs/feats/archetype/celebrity/primadonna.json
Labels: pr: data update

#19534 Add automation for select NPC abilities that allow variable damage types
  packs/pathfinder-bestiary-3/nightmarchers.json
  packs/pathfinder-npc-core/official/city-guard-squadron.json
Labels: pr: data update

#19525 Add Note to Barreling Charge's Athletics check while having Overpowering Charge
  packs/feat-effects/effect-desperate-wrath.json
  packs/feats/class/barbarian/awesome-blow.json
  packs/feats/class/barbarian/determined-dash.json
  packs/feats/class/barbarian/furious-sprint.json
  packs/feats/class/barbarian/meditate-on-this.json
  packs/feats/class/barbarian/penetrating-projectile.json
  packs/feats/class/barbarian/perfect-clarity.json
  packs/feats/class/barbarian/silencing-strike.json
  packs/feats/class/barbarian/thrash.json
  packs/feats/class/barbarian/vengeful-strike.json
  packs/feats/class/shared-class-feats/overpowering-charge.json
  packs/feats/class/shared-class-feats/towering-transformation.json
Labels: pr: data update

#19516 Add Ephemeral Effect for Spirits' Interference
  packs/classfeatures/elemental-instinct.json
  packs/feat-effects/effect-spirits-interference.json
  packs/feats/class/barbarian/animal-skin.json
  packs/feats/class/barbarian/dragons-rage-breath.json
  packs/feats/class/barbarian/elemental-explosion.json
  packs/feats/class/barbarian/scouring-rage.json
  packs/feats/class/barbarian/spirits-interference.json
  packs/feats/class/shared-class-feats/rip-and-tear.json
  static/lang/re-en.json
Labels: pr: data update

#19513 Add Furious Finish effect
  packs/feat-effects/effect-furious-finish.json
  packs/feats/class/barbarian/bashing-charge.json
  packs/feats/class/barbarian/draconic-arrogance.json
  packs/feats/class/barbarian/furious-finish.json
  packs/feats/class/barbarian/raging-intimidation.json
  packs/feats/class/shared-class-feats/sudden-charge.json
  static/lang/re-en.json
Labels: pr: data update

#19477 Add Note automation to Resounding Bravery and brush up effect automation
  packs/feat-effects/effect-resounding-bravery.json
  packs/feats/class/fighter/resounding-bravery.json
  static/lang/re-en.json
Labels: pr: data update

#19537 Fix players dragging compendium search results from sidebar
  src/module/apps/sidebar/compendium-directory.ts
Labels: pr: bugfix

#19547 Fix deleting feat subfeature language slots
  src/module/item/feat/sheet.ts
Labels: pr: bugfix

#19548 Fix mouse-accessibility of Modular-trait select element
  src/styles/actor/character/_actions.scss
Labels: pr: bugfix

#19552 Fix retrieving effect origin roll options
  src/module/item/abstract-effect/document.ts
Labels: pr: bugfix

#19556 Release Notes 7.2.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping
