Repository foundryvtt/pf2e, pull requests merged in 2025-01, with the labels that each got.

#17867 Correct Arcane School article in the Wizard class journal and provide a link to the supplementary entry in the class feature
  packs/classfeatures/arcane-school.json
  packs/journals/classes.json
Labels: pr: data update

#17873 Fix Compendium Browser trait filter losing "not" state of selected traits
  src/module/apps/compendium-browser/browser.ts
  src/module/apps/compendium-browser/components/filters/traits.svelte
Labels: pr: bugfix, pr: refactor

#17875 Add `Alchemical Food` tag to Iron Wine and icons to select Alchemical foods
  packs/equipment/iron-wine.json
  packs/equipment/saboteurs-friend.json
  packs/equipment/scholars-drop.json
  packs/equipment/sprite-apple-chartreuse.json
  packs/equipment/sprite-apple-golden.json
  packs/equipment/sprite-apple-pink.json
  packs/equipment/sprite-apple-teal.json
Labels: pr: data update

#17860 Add rarity tags to Archetype journals and add missing rarity to several entries
  packs/journals/archetypes.json
Labels: pr: data update

#17839 Update effects and automation for select Pathfinder Society Boons
  build/uuid-redirects.json
  packs/bestiary-effects/effect-pfs-level-bump-npc.json
  packs/campaign-effects/pathfinder-society/effect-combat-mentor.json
  packs/campaign-effects/pathfinder-society/effect-exotic-edge.json
  packs/campaign-effects/pathfinder-society/effect-heroic-aegis.json
  packs/campaign-effects/pathfinder-society/effect-heroic-hustle.json
  packs/campaign-effects/pathfinder-society/effect-heroic-inspiration.json
  packs/campaign-effects/pathfinder-society/effect-magical-mentor.json
  packs/campaign-effects/pathfinder-society/effect-protective-mentor.json
  packs/campaign-effects/pathfinder-society/effect-resist-corruption.json
  packs/campaign-effects/pathfinder-society/effect-rugged-mentor.json
  packs/campaign-effects/pathfinder-society/effect-skillful-mentor.json
  packs/campaign-effects/pathfinder-society/effect-worldly-mentor.json
  packs/feat-effects/effect-combat-mentor-boon-pfs.json
  packs/feat-effects/effect-magical-mentor-boon-pfs.json
  packs/feat-effects/effect-protective-mentor-boon-admired-pfs.json
  packs/feat-effects/effect-protective-mentor-boon-revered-pfs.json
  packs/pathfinder-society-boons/combat-mentor.json
  packs/pathfinder-society-boons/exotic-edge.json
  packs/pathfinder-society-boons/heroic-aegis.json
  packs/pathfinder-society-boons/heroic-hustle.json
  packs/pathfinder-society-boons/heroic-inspiration.json
  packs/pathfinder-society-boons/heroic-intervention.json
  packs/pathfinder-society-boons/magical-mentor.json
  packs/pathfinder-society-boons/protective-mentor.json
  packs/pathfinder-society-boons/resist-corruption.json
  packs/pathfinder-society-boons/rugged-mentor.json
  packs/pathfinder-society-boons/skillful-mentor.json
  packs/pathfinder-society-boons/ward-against-fiends.json
  packs/pathfinder-society-boons/worldly-mentor.json
  static/lang/re-en.json
Labels: pr: data update

#17868 Add icons and apply remaster theme to tables in select items
  packs/ancestryfeatures/animal-attack.json
  packs/bestiary-family-ability-glossary/protean-warpwave.json
  packs/classfeatures/air-gate.json
  packs/classfeatures/earth-gate.json
  packs/classfeatures/fire-gate.json
  packs/classfeatures/metal-gate.json
  packs/classfeatures/water-gate.json
  packs/classfeatures/wood-gate.json
  packs/equipment/buckler.json
  packs/equipment/cold-iron-chunk.json
  packs/equipment/cold-iron-ingot.json
  packs/equipment/dawnsilver-chunk.json
  packs/equipment/dawnsilver-ingot.json
  packs/equipment/gauntlet-buckler.json
  packs/equipment/medusas-scream-greater.json
  packs/equipment/medusas-scream.json
  packs/equipment/noqual-chunk.json
  packs/equipment/noqual-ingot.json
  packs/equipment/octopus-bottle.json
  packs/equipment/octopus-potion-greater.json
  packs/equipment/octopus-potion-lesser.json
  packs/equipment/octopus-potion-moderate.json
  packs/equipment/orichalcum-chunk.json
  packs/equipment/orichalcum-ingot.json
  packs/equipment/peachwood-branch.json
  packs/equipment/peachwood-lumber.json
  packs/equipment/siccatite-chunk.json
  packs/equipment/siccatite-ingot.json
  packs/equipment/silver-chunk.json
  packs/equipment/silver-ingot.json
Labels: pr: data update

#17869 Add missing mechanics section to Impossible Lands ancestries in the Ancestries journal
  packs/journals/ancestries.json
Labels: pr: data update

#17879 Update Instinctive Strike to remaster
  packs/feats/instinctive-strike.json
Labels: pr: data update

#17883 Automate the Battleblooded feat
  packs/feats/battleblooded.json
Labels: pr: data update

#17881 Update `You're next` to use `/act` syntax on select NPC actors
  packs/npc-gallery/prisoner.json
  packs/pfs-season-1-bestiary/1-12/hungry-blade-apprentice.json
  packs/pfs-season-1-bestiary/1-12/hungry-blade-recruit.json
  packs/pfs-season-4-bestiary/4-12/witchs-wing.json
  packs/pfs-season-5-bestiary/5-03/krosovahn-mendesil-7-8.json
  packs/pfs-season-5-bestiary/5-03/krosovahn-mendesil.json
  packs/pfs-season-6-bestiary/6-00/sharkskin.json
  static/lang/re-en.json
Labels: pr: data update

#17876 Update automation for additional Prey for Death actors
  packs/prey-for-death-bestiary/berserker-ordulf.json
  packs/prey-for-death-bestiary/celasik.json
  packs/prey-for-death-bestiary/dronuk.json
  packs/prey-for-death-bestiary/ordulf-bladecaller.json
Labels: pr: data update

#17877 Add missing publication source to Pathfinder Society Boon effects
  packs/campaign-effects/pathfinder-society/effect-combat-mentor.json
  packs/campaign-effects/pathfinder-society/effect-exotic-edge.json
  packs/campaign-effects/pathfinder-society/effect-heroic-aegis.json
  packs/campaign-effects/pathfinder-society/effect-heroic-hustle.json
  packs/campaign-effects/pathfinder-society/effect-heroic-inspiration.json
  packs/campaign-effects/pathfinder-society/effect-magical-mentor.json
  packs/campaign-effects/pathfinder-society/effect-protective-mentor.json
  packs/campaign-effects/pathfinder-society/effect-rugged-mentor.json
  packs/campaign-effects/pathfinder-society/effect-skillful-mentor.json
  packs/campaign-effects/pathfinder-society/effect-worldly-mentor.json
Labels: pr: data update

#17878 Condense Jolt Coil and Lightweave Scarf Spellheart equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-jolt-coil-armor-greater.json
  packs/equipment-effects/effect-jolt-coil-armor-major.json
  packs/equipment-effects/effect-jolt-coil-armor.json
  packs/equipment-effects/effect-jolt-coil-weapon-greater.json
  packs/equipment-effects/effect-jolt-coil-weapon-major.json
  packs/equipment-effects/effect-jolt-coil-weapon.json
  packs/equipment-effects/effect-lightweave-scarf-armor-major.json
  packs/equipment-effects/effect-lightweave-scarf-armor.json
  packs/equipment/jolt-coil-greater.json
  packs/equipment/jolt-coil-major.json
  packs/equipment/jolt-coil.json
  packs/equipment/lightweave-scarf-major.json
Labels: pr: data update

#17891 Update gnoll trait description to reference kholo
  static/lang/en.json
Labels: pr: data update, remaster

#17889 Assign Quinn's background attribute boosts
  packs/iconics/quinn-level-1.json
  packs/iconics/quinn-level-3.json
  packs/iconics/quinn-level-5.json
Labels: pr: data update

#17888 Correct Daemon Form spell description and add `Unholy` trait to match Fall 2024 errata
  packs/spells/daemon-form.json
Labels: pr: data update

#17887 Add missing size, rarity and traits to the Ancestry journal entries
  packs/journals/ancestries.json
Labels: pr: data update

#17897 Update Extra Alchemy's rule element to execute after Advanced Alchemy slot upgrades
  packs/feat-effects/effect-extra-alchemy.json
Labels: pr: data update

#17900 Update Svelte and Svelecte to the latest version
  package-lock.json
  package.json
Labels: pr: housekeeping

#17896 Convert additional instances of demoralize into `/act` syntax
  packs/abomination-vaults-bestiary/bone-gladiator.json
  packs/abomination-vaults-bestiary/nox.json
  packs/actions/primal-roar.json
  packs/actions/raconteurs-reload.json
  packs/actions/threatening-approach.json
  packs/age-of-ashes-bestiary/scarlet-triad-enforcer.json
  packs/agents-of-edgewatch-bestiary/casino-bouncer.json
  packs/agents-of-edgewatch-bestiary/shatterling.json
  packs/menace-under-otari-bestiary/skeletal-giant-bb.json
  packs/pathfinder-monster-core/skeletal-giant.json
  packs/pfs-season-1-bestiary/1-06/eerie-skeletal-giant.json
  packs/pfs-season-1-bestiary/1-18/elite-skeletal-giant-pfs-1-18.json
  packs/pfs-season-2-bestiary/2-03/lesser-skeletal-cyclops.json
  packs/pfs-season-2-bestiary/2-03/skeletal-cyclops.json
  packs/pfs-season-3-bestiary/3-10/bloody-beetle-exoskeleton.json
Labels: pr: data update

#17895 Condense Jyoti's Feather spellheart equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-jyotis-feather-armor-greater.json
  packs/equipment-effects/effect-jyotis-feather-armor-major.json
  packs/equipment-effects/effect-jyotis-feather-armor.json
  packs/equipment-effects/effect-jyotis-feather-weapon-greater.json
  packs/equipment-effects/effect-jyotis-feather-weapon-major.json
  packs/equipment-effects/effect-jyotis-feather-weapon.json
  packs/equipment/jyotis-feather-greater.json
  packs/equipment/jyotis-feather-major.json
Labels: pr: data update

#17905 Add Item Alteration note to the Stupefied condition
  packs/conditions/stupefied.json
  static/lang/en.json
Labels: pr: data update

#17915 Correct UUID embed for Ranger Expertise class feature in Class journal
  packs/journals/classes.json
Labels: pr: data update

#17916 Remove duplicate Ash mystery and redirect where applicable
  build/uuid-redirects.json
  packs/classfeatures/ash.json
  packs/feat-effects/effect-curse-of-creeping-ashes.json
  packs/paizo-pregens/savshin-starwatcher.json
Labels: pr: data update

#17917 Update Remaster journal to include Oracle Ashes mystery rename
  packs/journals/remaster-changes.json
Labels: pr: data update

#17903 Organize Ancestry journal entries by by rarity, add missing details to Azarketi journal entry and update the Other-Halves article in the Versatile Heritage journal entry to match Player Core.
  packs/journals/ancestries.json
Labels: pr: data update

#17923 Add Palace Echoes Kitsune to Kitsune jounal
  packs/journals/ancestries.json
Labels: pr: data update

#17922 Emphasize spell names in Divine Font description
  packs/classfeatures/divine-font.json
  packs/iconics/kyra-level-1.json
  packs/iconics/kyra-level-3.json
  packs/iconics/kyra-level-5.json
  packs/paizo-pregens/eteleon.json
  packs/paizo-pregens/kyra-beginner-box.json
Labels: pr: data update

#17921 Fix rarity for Armored Coat
  packs/equipment/armored-coat.json
Labels: pr: data update

#17909 Update grippli trait description to reference tripkee
  packs/journals/remaster-changes.json
  static/lang/en.json
Labels: pr: data update, remaster

#17904 Clean up descriptions for Wildspell Dedication
  packs/feat-effects/effect-invigorating-surge.json
  packs/feats/burning-surge.json
  packs/feats/extend-surge.json
  packs/feats/galvanize-spell.json
  packs/feats/imbue-spell.json
  packs/feats/invigorating-surge.json
  packs/feats/mystic-life-force.json
  packs/feats/mystical-flare.json
  packs/feats/mythic-counter.json
  packs/feats/mythic-heightening.json
  packs/feats/rapid-switch.json
  packs/feats/recharging-transference.json
  packs/feats/spell-network.json
  packs/feats/surging-interference.json
  packs/feats/thundering-surge.json
  packs/spells/spellsurge.json
Labels: pr: data update

#17844 Add automation and effects to additional Pathfinder Society Boons
  packs/campaign-effects/pathfinder-society/effect-grand-finale.json
  packs/campaign-effects/pathfinder-society/effect-light-in-the-dark.json
  packs/campaign-effects/pathfinder-society/effect-nexian-researcher.json
  packs/campaign-effects/pathfinder-society/effect-practiced-medic.json
  packs/campaign-effects/pathfinder-society/effect-tarnbreaker-champions.json
  packs/campaign-effects/pathfinder-society/effect-technological-defence.json
  packs/pathfinder-society-boons/adversary-lore.json
  packs/pathfinder-society-boons/menace-under-otari.json
  packs/pathfinder-society-boons/practiced-medic.json
  packs/pathfinder-society-boons/s1-00-nexian-researcher.json
  packs/pathfinder-society-boons/s1-04-touched-by-the-storm.json
  packs/pathfinder-society-boons/s1-10-tarnbreaker-champions.json
  packs/pathfinder-society-boons/s1-18-light-in-the-dark.json
  packs/pathfinder-society-boons/s1-18-narsens-web.json
  packs/pathfinder-society-boons/s1-25-grand-finale.json
  packs/pathfinder-society-boons/s1-q08-numerian-archaeologist.json
  packs/pathfinder-society-boons/steady-hand.json
  static/lang/re-en.json
Labels: pr: data update

#17902 Include failing property path in `RuleElementPF2e#resolveInjectedProperties` warning
  src/module/rules/rule-element/base.ts
Labels: pr: enhancement

#17925 Update descriptions of Sigil and Heal Mount to use the remastered term rank, rather than level
  packs/feats/heal-mount.json
  packs/spells/sigil.json
Labels: pr: data update

#17931 Fix wording of Ignition's melee persistent fire damage link
  packs/campaign-effects/pathfinder-society/effect-light-in-the-dark.json
  packs/conditions/stupefied.json
  packs/curtain-call-bestiary/emriss.json
  packs/howl-of-the-wild-bestiary/virtuosic-lyrebird.json
  packs/iconics/ezren-level-3.json
  packs/iconics/ezren-level-5.json
  packs/iconics/lini-level-1.json
  packs/iconics/lini-level-3.json
  packs/iconics/lini-level-5.json
  packs/pathfinder-monster-core/boggard-swampseer.json
  packs/pathfinder-monster-core/brimorak.json
  packs/pathfinder-monster-core/changeling-exile.json
  packs/pathfinder-monster-core/cuckoo-hag.json
  packs/pathfinder-monster-core/diabolic-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/diabolic-dragon-adult.json
  packs/pathfinder-monster-core/diabolic-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/diabolic-dragon-ancient.json
  packs/pathfinder-monster-core/diabolic-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/diabolic-dragon-young.json
  packs/pathfinder-monster-core/fire-scamp.json
  packs/pathfinder-monster-core/goblin-pyro.json
  packs/pathfinder-monster-core/ifrit.json
  packs/pathfinder-monster-core/lizardfolk-stargazer.json
  packs/pathfinder-monster-core/umbral-gnome-rockwarden.json
  packs/pathfinder-monster-core/water-scamp.json
  packs/pathfinder-society-boons/s1-04-touched-by-the-storm.json
  packs/pfs-season-6-bestiary/6-07/chelaxian-devilcaster.json
  packs/pfs-season-6-bestiary/6-07/chelaxian-mage.json
  packs/pfs-season-6-bestiary/6-08/high-matriarch-szvetneera.json
  packs/pfs-season-6-bestiary/6-08/matriarch-szvetneera.json
  packs/prey-for-death-bestiary/rhysaphine.json
  packs/rage-of-elements-bestiary/gennayn.json
  packs/rage-of-elements-bestiary/ifrit-shuyookh.json
  packs/spells/ignition.json
  packs/triumph-of-the-tusk-bestiary/azorena.json
  packs/triumph-of-the-tusk-bestiary/death-tower-necromancer.json
  packs/triumph-of-the-tusk-bestiary/diskah-night-watcher.json
  packs/wardens-of-wildwood-bestiary/rancorous-druids.json
Labels: pr: data update

#17927 Add rename of Glyph of Warding to Rune Trap to remaster journal
  packs/journals/remaster-changes.json
Labels: pr: data update, remaster

#17919 Account for Vindicator's alternate skill training
  packs/classes/ranger.json
  packs/classfeatures/vindicator.json
Labels: pr: data update

#17938 Replace lower-resolution system icons with identical core icons
  packs/agents-of-edgewatch-bestiary/avsheros-the-betrayer.json
  packs/agents-of-edgewatch-bestiary/hestriviniaas.json
  packs/blood-lords-bestiary/kemnebi.json
  packs/extinction-curse-bestiary/dyzallin-shraen.json
  packs/feat-effects/effect-consume-energy-augment-strike.json
  packs/feat-effects/effect-repel-ambient-magic.json
  packs/monsters-of-myth-bestiary/somnalu.json
  packs/pathfinder-dark-archive/cocoon-of-lucid-potential.json
  packs/spell-effects/spell-effect-prismatic-shield.json
  packs/spells/divinity-leech.json
  packs/spells/hypnopompic-terrors.json
  packs/spells/prismatic-shield.json
  packs/spells/sea-of-thought.json
  packs/spells/shadow-raid.json
  packs/spells/subjugate-undead.json
  packs/spells/terminate-bloodline.json
Labels: pr: data update, pr: static assets

#17936 Automate United Assault feat
  packs/feats/united-assault.json
Labels: pr: data update

#17944 Correct Cloak of Waves and Clouds fly and swim bonus values
  packs/equipment/cloak-of-waves-clouds.json
Labels: pr: data update

#17945 Move darkvision automation from effects to item for Greater and Major Obsidian Goggles
  packs/equipment/obsidian-goggles-greater.json
  packs/equipment/obsidian-goggles-major.json
Labels: pr: data update

#17943 Correct Verex-That-Was' AC value and add area options to Battlefield Eruption
  packs/war-of-immortals-bestiary/verex-that-was.json
Labels: pr: data update

#17956 Condense item effects for Perfect Droplet and Camouflage Suit
  build/uuid-redirects.json
  packs/equipment-effects/effect-perfect-droplet-armor-greater.json
  packs/equipment-effects/effect-perfect-droplet-armor-major.json
  packs/equipment-effects/effect-perfect-droplet-armor.json
  packs/equipment-effects/effect-prepared-camouflage-suit-superb.json
  packs/equipment-effects/effect-prepared-camouflage-suit.json
  packs/equipment/camouflage-suit-superb.json
  packs/equipment/perfect-droplet-greater.json
  packs/equipment/perfect-droplet-major.json
Labels: pr: data update

#17952 Fix typo in Moderate Ablative Armor Plating effect
  packs/equipment-effects/effect-ablative-armor-plating-moderate.json
Labels: pr: data update

#17950 Add inline Diplomacy check to Evangelize
  packs/feats/evangelize.json
Labels: pr: data update

#17948 Fix razmiri mask, porcelain description
  packs/equipment/razmiri-mask-porcelain.json
Labels: pr: data update

#17934 Update automation on Nosoi Charm (and variant) to account for the switch between bonuses without an effect
  packs/equipment/nosoi-charm-greater.json
  packs/equipment/nosoi-charm.json
Labels: pr: data update

#17951 Add effect for Imp Shot and add automation for Spark Dancer
  packs/equipment-effects/effect-imp-shot.json
  packs/equipment/imp-shot.json
  packs/equipment/spark-dancer.json
  packs/equipment/vampire-fang-morningstar.json
Labels: pr: data update

#17962 Correct level for the Quick Recovery Yaoguai ancestry feat
  packs/feats/quick-recovery.json
Labels: pr: data update

#17959 Add area options to Cassisian.
  packs/pathfinder-monster-core/cassisian.json
Labels: pr: data update

#17963 Update priority for AE-like rule elements on Fey Ascension feat
  packs/feats/fey-ascension.json
Labels: pr: data update

#17961 Fix Versatile Vials having item bonus to attack rolls before level 4
  packs/equipment/versatile-vial.json
Labels: pr: data update

#17980 Remove "Steal" inline from Greater Shadow's Steal Shadow description
  packs/pathfinder-monster-core/greater-shadow.json
Labels: pr: data update

#17969 Add area damage options to select inline damage
  packs/age-of-ashes-bestiary/tarrasque-the-armageddon-engine.json
  packs/outlaws-of-alkenstar-bestiary/clearwater-cleaner.json
  packs/pathfinder-monster-core/air-scamp.json
  packs/pathfinder-monster-core/arbiter.json
  packs/pathfinder-monster-core/earth-scamp.json
  packs/pathfinder-monster-core/fire-scamp.json
  packs/pathfinder-monster-core/water-scamp.json
  packs/rusthenge-bestiary/clockwork-serpent-spy.json
Labels: pr: data update

#17966 Apply remaster theme to select tables in items
  packs/ancestryfeatures/draconic-exemplar.json
  packs/classfeatures/animal-instinct.json
  packs/classfeatures/dragon-instinct.json
  packs/classfeatures/elemental-instinct.json
  packs/curtain-call-bestiary/fallenta.json
  packs/curtain-call-bestiary/girtablilu-guardian.json
  packs/curtain-call-bestiary/grandmama.json
  packs/curtain-call-bestiary/the-final-herald.json
  packs/equipment/steel-shield.json
  packs/equipment/wooden-shield.json
  packs/feats/virtuosic-performer.json
  packs/howl-of-the-wild-bestiary/scroungefeather.json
  packs/pathfinder-monster-core/dwarf-warrior.json
  packs/pathfinder-monster-core/hobgoblin-soldier.json
  packs/pathfinder-monster-core/iron-warden.json
  packs/pathfinder-monster-core/keketar.json
  packs/pathfinder-monster-core/lizardfolk-defender.json
  packs/pathfinder-monster-core/nessari.json
  packs/pathfinder-monster-core/noxious-needler.json
  packs/pathfinder-monster-core/skeletal-champion.json
  packs/pathfinder-monster-core/umbral-gnome-warrior.json
  packs/prey-for-death-bestiary/mantis-keeper.json
  packs/spells/animate-object.json
  packs/spells/awaken-animal.json
  packs/spells/create-undead.json
  packs/spells/creative-splash.json
  packs/spells/rainbow-fumarole.json
  packs/spells/unfathomable-song.json
  packs/wardens-of-wildwood-bestiary/avathrael-realmshaper.json
Labels: pr: data update

#17978 Add `Nails` weapon localization and add base category to Eldritch Nails from Witch's Armaments feat
  packs/feats/witchs-armaments.json
  static/lang/en.json
Labels: pr: data update

#17973 Update Stupefy to match Player Core duration and target
  packs/curtain-call-bestiary/augusta-wormwood.json
  packs/pathfinder-monster-core/dero-magister.json
  packs/pathfinder-monster-core/omen-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/vampire-mastermind.json
  packs/spells/stupefy.json
  packs/triumph-of-the-tusk-bestiary/death-tower-necromancer.json
Labels: pr: data update

#17984 Fix predicate on winglet flight
  packs/feats/winglet-flight.json
Labels: pr: data update

#17971 Update Gate Junctions table in Kineticist class entry and add `Roleplaying a Werecreature` and `Werecreature Types` tables to Werecreature dedication journals
  packs/journals/archetypes.json
  packs/journals/classes.json
Labels: pr: data update

#17924 Fix description in arcane spellcasting (magus)
  packs/classfeatures/arcane-spellcasting-magus.json
Labels: pr: data update

#17985 Correct Oscillating Wave's Amped Ignition dice number
  packs/classfeatures/the-oscillating-wave.json
Labels: pr: data update

#17986 Add Demon Hunter prerequisite to Demon Slayer feat
  packs/feats/demon-slayer.json
Labels: pr: data update

#17989 Fix some inline rolls for Kyonin Ancestry Feats
  packs/feats/shame-the-sin.json
  packs/feats/treehealer.json
Labels: pr: data update

#17983 Fix action type and cost of Regurgitate Mutagen
  packs/feats/regurgitate-mutagen.json
Labels: pr: data update

#17953 Fix versatile vials being created twice when alchemist is added
  src/module/item/base/document.ts
  src/module/rules/rule-element/special-resource.ts
Labels: pr: bugfix

#17899 Add support for changing prepared quantities from the formula picker
  src/module/actor/character/apps/formula-picker/app.svelte
  src/module/actor/character/apps/formula-picker/app.ts
  src/module/actor/character/crafting/ability.ts
  src/module/actor/character/sheet.ts
  src/module/chat-message/helpers.ts
  src/module/sheet/components/hover-icon-button.svelte
  static/lang/en.json
Labels: pr: enhancement

#17977 Remove most category getters from non-document spellcasting entries
  src/module/actor/creature/document.ts
  src/module/actor/creature/sheet.ts
  src/module/actor/spellcasting.ts
  src/module/apps/compendium-browser/browser.ts
  src/module/item/spell/document.ts
  src/module/item/spellcasting-entry/collection.ts
  src/module/item/spellcasting-entry/item-spellcasting.ts
  src/module/item/spellcasting-entry/rituals.ts
  src/module/item/spellcasting-entry/trick.ts
  src/module/item/spellcasting-entry/types.ts
Labels: pr: refactor

#17974 Start configuring variables for theme dark
  src/module/sheet/components/item-summary.svelte
  src/styles/_colors.scss
Labels: pr: refactor

#17731 Support suboptions from config in roll option rule element
  src/module/rules/helpers.ts
  src/module/rules/rule-element/choice-set/rule-element.ts
  src/module/rules/rule-element/roll-option/data.ts
  src/module/rules/rule-element/roll-option/rule-element.ts
Labels: pr: enhancement

#17990 Use config suboptions for Tome's initiate benefit
  packs/classfeatures/initiate-benefit-tome.json
Labels: pr: data update

#17988 Fix issue causing propulsive weapons to sometimes have dex-based attack statistics
  src/module/actor/helpers.ts
Labels: pr: bugfix

#17992 Replace stray `+1 Status to All Saves vs. Magic` passives with compendium equivalent
  packs/abomination-vaults-bestiary/beluthus.json
  packs/abomination-vaults-bestiary/drow-cavern-seer.json
  packs/agents-of-edgewatch-bestiary/agent-of-the-gray-queen.json
  packs/agents-of-edgewatch-bestiary/hestriviniaas.json
  packs/agents-of-edgewatch-bestiary/hundun-chaos-mage.json
  packs/agents-of-edgewatch-bestiary/izfiitar.json
  packs/agents-of-edgewatch-bestiary/overdrive-imentesh.json
  packs/agents-of-edgewatch-bestiary/penqual.json
  packs/agents-of-edgewatch-bestiary/rhevanna.json
  packs/agents-of-edgewatch-bestiary/sordesdaemon.json
  packs/agents-of-edgewatch-bestiary/ulressia-the-blessed.json
  packs/agents-of-edgewatch-bestiary/veksciralenix.json
  packs/curtain-call-bestiary/grandmama.json
  packs/curtain-call-bestiary/izhkarial.json
  packs/curtain-call-bestiary/living-nightmare.json
  packs/curtain-call-bestiary/rooftop-guardian.json
  packs/pathfinder-bestiary-2/animate-dream.json
  packs/pathfinder-bestiary-2/babau.json
  packs/pathfinder-bestiary-2/bastion-archon.json
  packs/pathfinder-bestiary-2/brine-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/brine-dragon-adult.json
  packs/pathfinder-bestiary-2/brine-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/brine-dragon-ancient.json
  packs/pathfinder-bestiary-2/bythos.json
  packs/pathfinder-bestiary-2/cairn-linnorm.json
  packs/pathfinder-bestiary-2/catrina.json
  packs/pathfinder-bestiary-2/cloud-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-adult.json
  packs/pathfinder-bestiary-2/cloud-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-ancient.json
  packs/pathfinder-bestiary-2/crystal-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/crystal-dragon-adult.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient.json
  packs/pathfinder-bestiary-2/derghodaemon.json
  packs/pathfinder-bestiary-2/devourer.json
Labels: pr: data update

#17996 Refresh additional instances of NPC resistance to magic features
  packs/abomination-vaults-bestiary/ladys-whisper.json
  packs/abomination-vaults-bestiary/quara-orshendiel.json
  packs/abomination-vaults-bestiary/salaisa-malthulas.json
  packs/agents-of-edgewatch-bestiary/agradaemon.json
  packs/agents-of-edgewatch-bestiary/avsheros-the-betrayer.json
  packs/agents-of-edgewatch-bestiary/lie-master.json
  packs/agents-of-edgewatch-bestiary/the-inkmaster.json
  packs/blog-bestiary/firebrand-brass-dragon-ancient.json
  packs/blood-lords-bestiary/vanth-warrior.json
  packs/equipment/versatile-vial.json
  packs/extinction-curse-bestiary/dyzallin-shraen.json
  packs/extinction-curse-bestiary/iffdahsil.json
  packs/fists-of-the-ruby-phoenix-bestiary/koto-zekora.json
  packs/fists-of-the-ruby-phoenix-bestiary/portal-eater.json
  packs/fists-of-the-ruby-phoenix-bestiary/spinel-leviathan-syndara.json
  packs/fists-of-the-ruby-phoenix-bestiary/taiga-yai.json
  packs/fists-of-the-ruby-phoenix-bestiary/tamikan.json
  packs/gatewalkers-bestiary/ogmunzorius.json
  packs/kingmaker-bestiary/general-avinash-jurrg.json
  packs/kingmaker-bestiary/niodrhast.json
  packs/malevolence-bestiary/algea.json
  packs/malevolence-bestiary/undead-brain-collector.json
  packs/malevolence-bestiary/yianyin.json
  packs/one-shot-bestiary/pairaka-one-shot-4.json
  packs/pathfinder-bestiary-2/dweomercat.json
  packs/pathfinder-bestiary-2/eremite.json
  packs/pathfinder-bestiary-2/evangelist.json
  packs/pathfinder-bestiary-2/fjord-linnorm.json
  packs/pathfinder-bestiary-2/hamatula.json
  packs/pathfinder-bestiary-2/hellcat.json
  packs/pathfinder-bestiary-2/hezrou.json
  packs/pathfinder-bestiary-2/hound-archon.json
  packs/pathfinder-bestiary-2/imentesh.json
  packs/pathfinder-bestiary-2/interlocutor.json
  packs/pathfinder-bestiary-2/invidiak.json
  packs/pathfinder-bestiary-2/korred.json
  packs/pathfinder-bestiary-2/leng-spider.json
  packs/pathfinder-bestiary-2/magma-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-adult.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient.json
  packs/pathfinder-bestiary-2/meladaemon.json
  packs/pathfinder-bestiary-2/monadic-deva.json
  packs/pathfinder-bestiary-2/movanic-deva.json
  packs/pathfinder-bestiary-2/nabasu.json
  packs/pathfinder-bestiary-2/nalfeshnee.json
  packs/pathfinder-bestiary-2/neothelid.json
  packs/pathfinder-bestiary-2/nixie.json
  packs/pathfinder-bestiary-2/olethrodaemon.json
  packs/pathfinder-bestiary-2/onidoshi.json
  packs/pathfinder-bestiary-2/ostiarius.json
  packs/pathfinder-bestiary/brass-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/brass-dragon-ancient.json
Labels: pr: data update

#17997 Fix minor styling rot in kingmaker sheet
  src/module/actor/party/kingdom/model.ts
  src/styles/actor/party/kingdom/_activities.scss
  static/lang/kingmaker-en.json
Labels: ui/ux, kingmaker

#18000 Fix Sword-Light Wave embed in archetype journal
  packs/journals/archetypes.json
Labels: pr: data update

#17999 Add slug to Regalia's bonus to charisma skills
  packs/classfeatures/initiate-benefit-regalia.json
Labels: pr: data update

#18005 Show item image if the action is usable
  src/module/actor/character/sheet.ts
Labels: pr: enhancement

#17964 Condense Ooze Ammunition and Poison Fizz's variant item effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-ooze-ammunition-greater.json
  packs/equipment-effects/effect-ooze-ammunition-lesser.json
  packs/equipment-effects/effect-ooze-ammunition-major.json
  packs/equipment-effects/effect-ooze-ammunition-moderate.json
  packs/equipment-effects/effect-ooze-ammunition.json
  packs/equipment-effects/effect-poison-fizz-greater.json
  packs/equipment-effects/effect-poison-fizz.json
  packs/equipment/ooze-ammunition-greater.json
  packs/equipment/ooze-ammunition-lesser.json
  packs/equipment/ooze-ammunition-major.json
  packs/equipment/ooze-ammunition-moderate.json
  packs/equipment/poison-fizz-greater.json
Labels: pr: data update

#18001 Add roll notes to Skunk Bombs
  packs/equipment/skunk-bomb-greater.json
  packs/equipment/skunk-bomb-lesser.json
  packs/equipment/skunk-bomb-major.json
  packs/equipment/skunk-bomb-moderate.json
  static/lang/re-en.json
Labels: pr: data entry

#18007 Remove some unnecessary usage of sets in actor/item data preparation
  src/module/actor/base.ts
  src/module/actor/character/document.ts
  src/module/actor/creature/document.ts
  src/module/item/consumable/spell-consumables.ts
  src/module/item/feat/document.ts
  src/module/item/spell/document.ts
Labels: pr: refactor

#18010 Lazy load description alterations
  src/module/item/base/data/system.ts
  src/module/item/helpers.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: enhancement

#18004 Release Notes 6.8.2
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#17930 Add Deathdrinking effects
  packs/equipment-effects/effect-deathdrinking.json
  packs/equipment/deathdrinking.json
  static/lang/en.json
Labels: pr: data update

#18002 Refresh even more instances of NPC resistance to magic features
  packs/pathfinder-bestiary-2/peluda.json
  packs/pathfinder-bestiary-2/piscodaemon.json
  packs/pathfinder-bestiary-2/planetar.json
  packs/pathfinder-bestiary-2/purrodaemon.json
  packs/pathfinder-bestiary-2/ravener.json
  packs/pathfinder-bestiary-2/sacristan.json
  packs/pathfinder-bestiary-2/sandpoint-devil.json
  packs/pathfinder-bestiary-2/sard.json
  packs/pathfinder-bestiary-2/sceaduinar.json
  packs/pathfinder-bestiary-2/shoal-linnorm.json
  packs/pathfinder-bestiary-2/solar.json
  packs/pathfinder-bestiary-2/star-archon.json
  packs/pathfinder-bestiary-2/stygira.json
  packs/pathfinder-bestiary-2/taiga-linnorm.json
  packs/pathfinder-bestiary-2/thanadaemon.json
  packs/pathfinder-bestiary-2/theletos.json
  packs/pathfinder-bestiary-2/thrasfyr.json
  packs/pathfinder-bestiary-2/trumpet-archon.json
  packs/pathfinder-bestiary-2/umbral-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-adult.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient.json
  packs/pathfinder-bestiary-2/vaspercham.json
  packs/pathfinder-bestiary-2/zebub.json
  packs/pathfinder-bestiary-2/zelekhut.json
  packs/pfs-season-2-bestiary/2-16/joyful-planar-nixie.json
  packs/pfs-season-2-bestiary/2-16/planar-nixie.json
Labels: pr: data update

#18009 Refresh select NPC mental resistance passive ability traits
  packs/abomination-vaults-bestiary/drow-hunter.json
  packs/abomination-vaults-bestiary/drow-shootist.json
  packs/abomination-vaults-bestiary/drow-warden.json
  packs/abomination-vaults-bestiary/nyzuros.json
  packs/age-of-ashes-bestiary/nketiah.json
  packs/agents-of-edgewatch-bestiary/secret-keeper.json
  packs/blood-lords-bestiary/shabti-votary.json
  packs/fists-of-the-ruby-phoenix-bestiary/rai-sho-disciple.json
  packs/kingmaker-bestiary/hateful-hermit.json
  packs/kingmaker-bestiary/ilthuliak.json
  packs/kingmaker-bestiary/the-wriggling-man.json
  packs/pathfinder-bestiary-2/umonlee.json
  packs/pathfinder-bestiary-3/danava-titan.json
  packs/pathfinder-bestiary-3/elysian-titan.json
  packs/pathfinder-bestiary-3/hekatonkheires-titan.json
  packs/pathfinder-bestiary-3/thanatotic-titan.json
  packs/pathfinder-bestiary/drow-fighter.json
  packs/pathfinder-bestiary/drow-priestess.json
  packs/pathfinder-bestiary/drow-rogue.json
  packs/pathfinder-monster-core/envyspawn.json
  packs/pathfinder-monster-core/gluttonyspawn.json
  packs/pathfinder-monster-core/greedspawn.json
  packs/pathfinder-monster-core/lustspawn.json
  packs/pathfinder-monster-core/pridespawn.json
  packs/pathfinder-monster-core/slothspawn.json
  packs/pathfinder-monster-core/wrathspawn.json
  packs/pfs-season-4-bestiary/4-17/aslynns-eye.json
  packs/pfs-season-4-bestiary/4-17/aslynns-sharper-eye.json
  packs/seven-dooms-for-sandpoint-bestiary/greedspawn.json
Labels: pr: data update

#18011 Apply remaster theme to select item tables
  packs/equipment/adamantine-chunk.json
  packs/equipment/adamantine-ingot.json
  packs/equipment/dragonplate.json
  packs/equipment/duskwood-branch.json
  packs/equipment/duskwood-lumber.json
  packs/equipment/exploding-shield.json
  packs/equipment/glamorous-buckler.json
  packs/equipment/madcap-top.json
  packs/pfs-season-6-bestiary/6-07/chelaxian-fighter.json
  packs/pfs-season-6-bestiary/6-07/chelaxian-weaponmaster.json
  packs/prey-for-death-bestiary/alktherisa-and-omprisgor.json
  packs/spells/chthonian-wrath.json
  packs/triumph-of-the-tusk-bestiary/azorena.json
  packs/triumph-of-the-tusk-bestiary/blisterwell-warrior.json
  packs/triumph-of-the-tusk-bestiary/death-tower-necromancer.json
  packs/triumph-of-the-tusk-bestiary/porphyry-shield-bearer.json
  packs/triumph-of-the-tusk-bestiary/ungukk-fleshdredge.json
  packs/triumph-of-the-tusk-bestiary/verthok-the-reaper.json
  packs/wardens-of-wildwood-bestiary/zibik.json
Labels: pr: data update

#18016 Add `area-option` option to select Breath Weapon items
  packs/abomination-vaults-bestiary/jarelle-kaldrian.json
  packs/actions/dragon-breath.json
  packs/age-of-ashes-bestiary/belmazog.json
  packs/age-of-ashes-bestiary/lesser-manifestation-of-dahak.json
  packs/age-of-ashes-bestiary/manifestation-of-dahak.json
  packs/age-of-ashes-bestiary/mengkare.json
  packs/age-of-ashes-bestiary/racharak.json
  packs/age-of-ashes-bestiary/spawn-of-dahak.json
  packs/age-of-ashes-bestiary/veshumirix.json
  packs/age-of-ashes-bestiary/xotani-the-firebleeder.json
  packs/age-of-ashes-bestiary/xotanispawn.json
  packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
  packs/agents-of-edgewatch-bestiary/daemonic-infector.json
  packs/agents-of-edgewatch-bestiary/lie-master.json
  packs/agents-of-edgewatch-bestiary/pulping-golem.json
  packs/agents-of-edgewatch-bestiary/reginald-vancaskerkin.json
  packs/agents-of-edgewatch-bestiary/veksciralenix.json
  packs/bestiary-family-ability-glossary/greater-barghest-mutation-toxic-breath.json
  packs/bestiary-family-ability-glossary/mana-wastes-mutant-energy-blast.json
  packs/bestiary-family-ability-glossary/zombie-shock-breath-weapon.json
  packs/blog-bestiary/firebrand-brass-dragon-ancient.json
  packs/blog-bestiary/urok.json
  packs/blood-lords-bestiary/azmakian-effigy.json
  static/lang/re-en.json
Labels: pr: data update

#18017 Update Svelte Dependencies
  package-lock.json
  package.json
Labels: pr: housekeeping

#18019 Fix multiplying addendum notes on spells
  src/module/item/base/document.ts
  src/module/item/base/sheet/sheet.ts
  src/module/item/consumable/document.ts
  src/module/item/helpers.ts
  src/module/item/spell/document.ts
  src/module/item/spell/sheet.ts
  src/module/item/weapon/document.ts
  src/module/rules/rule-element/item-alteration/rule-element.ts
  src/module/rules/rule-element/strike.ts
Labels: pr: bugfix

#18006 Skip item alteration roll option fetching if it doesn't match any items
  src/module/rules/rule-element/item-alteration/rule-element.ts
Labels: pr: enhancement

#18020 Add automation to Lightless Litheness Fetchling feat
  packs/feats/lightless-litheness.json
  static/lang/re-en.json
Labels: pr: data update

#18021 Add spell links to Basic Undead Benefits
  packs/ancestryfeatures/basic-undead-benefits.json
Labels: pr: data update

#18022 Fix Magical Scrounger description
  packs/feats/magical-scrounger.json
Labels: pr: data update

#18026 Add missing Witch patrons to Class Journal and Lessons to the class features
  packs/classfeatures/witch-lessons.json
  packs/journals/classes.json
Labels: pr: data update

#18027 Correct typo in Diadem of Divine Radiance's heightening entry
  packs/spells/diadem-of-divine-radiance.json
Labels: pr: data update

#18031 Sort weapon and armor property runes
  src/module/item/armor/sheet.ts
  src/module/item/weapon/sheet.ts
  src/styles/item/_index.scss
  src/styles/item/_weapon-sheet.scss
  static/templates/items/armor-details.hbs
Labels: pr: enhancement

#18030 Avoid feat dropping to bonus feats when dragged to the same slot
  src/module/actor/character/feats/group.ts
Labels: pr: enhancement

#18029 Avoid saving temporary modifications to weapon striking runes when editing the weapon
  src/module/item/weapon/sheet.ts
  static/templates/items/weapon-details.hbs
Labels: pr: bugfix

#18037 Add `Alchemical` tag to Elixir of Gender Transformation
  packs/equipment/elixir-of-gender-transformation-greater.json
  packs/equipment/elixir-of-gender-transformation-lesser.json
  packs/equipment/elixir-of-gender-transformation-moderate.json
Labels: pr: data update

#18038 Update Vaccine item to match Treasure Vault printing information
  packs/equipment/vaccine-greater.json
  packs/equipment/vaccine-lesser.json
  packs/equipment/vaccine-major.json
  packs/equipment/vaccine-minor.json
  packs/equipment/vaccine-moderate.json
Labels: pr: data update

#18042 Correct Hellshadow NPC resistances values to match source
  packs/curtain-call-bestiary/hellshadow.json
Labels: pr: data update

#18008 Condense Numbing Tonic and Rainbow Vinegar equipment effects
  build/uuid-redirects.json
  packs/equipment-effects/effect-numbing-tonic-greater.json
  packs/equipment-effects/effect-numbing-tonic-lesser.json
  packs/equipment-effects/effect-numbing-tonic-major.json
  packs/equipment-effects/effect-numbing-tonic-minor.json
  packs/equipment-effects/effect-numbing-tonic-moderate.json
  packs/equipment-effects/effect-numbing-tonic-true.json
  packs/equipment-effects/effect-numbing-tonic.json
  packs/equipment-effects/effect-rainbow-vinegar-greater.json
  packs/equipment-effects/effect-rainbow-vinegar-moderate.json
  packs/equipment-effects/effect-rainbow-vinegar.json
  packs/equipment/numbing-tonic-greater.json
  packs/equipment/numbing-tonic-lesser.json
  packs/equipment/numbing-tonic-major.json
  packs/equipment/numbing-tonic-minor.json
  packs/equipment/numbing-tonic-moderate.json
  packs/equipment/numbing-tonic-true.json
  packs/equipment/rainbow-vinegar-greater.json
  packs/equipment/rainbow-vinegar-moderate.json
Labels: pr: data update

#18039 Release Notes 6.8.3
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#18048 Fix level of Moderate Chromatic Jellyfish Oil
  packs/equipment/chromatic-jellyfish-oil-moderate.json
Labels: pr: data update

#18028 Add effect for Goz Mask (Major)
  packs/equipment-effects/effect-goz-mask-major.json
  packs/equipment/goz-mask-greater.json
  packs/equipment/goz-mask-major.json
  packs/equipment/goz-mask.json
Labels: pr: data update

#18046 Run extractPacks all
  packs/equipment-effects/effect-deathdrinking.json
  packs/equipment-effects/effect-rainbow-vinegar.json
  packs/equipment/deathdrinking.json
Labels: pr: housekeeping

#18043 Add automation for Channel Rot's persistent damage
  packs/feats/channel-rot.json
  static/lang/re-en.json
Labels: pr: data update

#18051 Remove rule element from Hideous Ululation
  packs/feats/hideous-ululation.json
Labels: pr: data update

#18053 Fix damage of Spray of Stars
  packs/spells/spray-of-stars.json
Labels: pr: data update

#18056 Correct typo in Kineticists Class Journal entry
  packs/journals/classes.json
Labels: pr: data update

#18057 Add spell links to select Summoner class feats
  packs/feats/boost-summons.json
  packs/feats/eidolons-wrath.json
  packs/feats/eternal-boost.json
  packs/feats/lifelink-surge.json
  packs/feats/reinforce-eidolon.json
  packs/feats/unfetter-eidolon.json
Labels: pr: data update

#18065 Fix viewing spells with variants from compendium browser
  src/module/item/helpers.ts
  src/module/item/spell/document.ts
Labels: pr: bugfix

#18069 Release Notes 6.8.4
  CHANGELOG.md
  package-lock.json
  package.json
  static/system.json
Labels: pr: housekeeping

#18068 Fix category of defend our union feat
  packs/feats/defend-our-union.json
Labels: pr: data update

#18070 Cleanup Blightburn Bomb description
  packs/equipment/blightburn-bomb-greater.json
  packs/equipment/blightburn-bomb.json
Labels: pr: data update

#18066 Fix rolling vehicle fortitude saves
  src/module/system/statistic/statistic.ts
  src/styles/actor/vehicle/_sidebar.scss
  static/templates/actors/vehicle/sidebar.hbs
Labels: pr: bugfix

#18072 Fix action type of Clone Risen and Miror Risen feats
  packs/feats/clone-risen.json
  packs/feats/mirror-risen.json
Labels: pr: data update

#18074 Add `area-damage` to Dragon Form spell and effects
  packs/agents-of-edgewatch-bestiary/blune-bandersworth.json
  packs/curtain-call-bestiary/oriole.json
  packs/fists-of-the-ruby-phoenix-bestiary/juspix-rammel.json
  packs/fists-of-the-ruby-phoenix-bestiary/yabin-the-just-level-13.json
  packs/kingmaker-bestiary/phomandala.json
  packs/kingmaker-bestiary/the-wriggling-man.json
  packs/spell-effects/spell-effect-dragon-form-adamantine.json
  packs/spell-effects/spell-effect-dragon-form-conspirator.json
  packs/spell-effects/spell-effect-dragon-form-diabolic.json
  packs/spell-effects/spell-effect-dragon-form-empyreal.json
  packs/spell-effects/spell-effect-dragon-form-horned.json
  packs/spell-effects/spell-effect-dragon-form-mirage.json
  packs/spell-effects/spell-effect-dragon-form-omen.json
  packs/spells/dragon-form.json
Labels: pr: data update

#18076 Prevent having two sets of origin options for non-saves
  src/module/system/statistic/statistic.ts
Labels: pr: bugfix

#18014 Improve performance of mergeable sub options
  src/module/item/base/document.ts
Labels: pr: enhancement

#18082 Add `area damage` and `area-effect` options to more Breath Weapon items
  packs/agents-of-edgewatch-bestiary/veksciralenix.json
  packs/blood-lords-bestiary/azmakian-effigy.json
  packs/extinction-curse-bestiary/ammut.json
  packs/extinction-curse-bestiary/starved-staff.json
  packs/kingmaker-bestiary/akuzhail.json
  packs/kingmaker-bestiary/ilthuliak.json
  packs/kingmaker-bestiary/lintwerth.json
  packs/kingmaker-bestiary/minognos-ushad.json
  packs/kingmaker-bestiary/niodrhast.json
  packs/kingmaker-bestiary/oversized-chimera.json
  packs/kingmaker-bestiary/rezatha.json
  packs/monsters-of-myth-bestiary/cuetzmonquali.json
  packs/monsters-of-myth-bestiary/spring-heeled-jack.json
  packs/night-of-the-gray-death-bestiary/conqueror-worm.json
  packs/outlaws-of-alkenstar-bestiary/akrida.json
  packs/outlaws-of-alkenstar-bestiary/chimeric-manticore.json
  packs/pathfinder-bestiary/air-mephit.json
  packs/pathfinder-bestiary/black-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary/black-dragon-adult.json
  packs/pathfinder-bestiary/black-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/black-dragon-ancient.json
  packs/pathfinder-bestiary/black-dragon-young-spellcaster.json
  packs/pathfinder-bestiary/black-dragon-young.json
  packs/pathfinder-bestiary/blue-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary/blue-dragon-adult.json
  packs/pathfinder-bestiary/blue-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/blue-dragon-ancient.json
  packs/pathfinder-bestiary/blue-dragon-young-spellcaster.json
  packs/pathfinder-bestiary/blue-dragon-young.json
  packs/pathfinder-bestiary/brass-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary/brass-dragon-adult.json
  packs/pathfinder-bestiary/brass-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/brass-dragon-ancient.json
  packs/pathfinder-bestiary/brass-dragon-young-spellcaster.json
  packs/pathfinder-bestiary/brass-dragon-young.json
  packs/pathfinder-bestiary/bronze-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary/bronze-dragon-adult.json
  packs/pathfinder-bestiary/bronze-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary/bronze-dragon-ancient.json
  packs/pathfinder-bestiary/bronze-dragon-young-spellcaster.json
  packs/pathfinder-bestiary/bronze-dragon-young.json
  packs/pathfinder-bestiary/ceustodaemon.json
  packs/pathfinder-bestiary/copper-dragon-adult-spellcaster.json
Labels: pr: data update

#18088 Add `area damage` and `area-effect` options to some inline rolls
  packs/abomination-vaults-bestiary/jarelle-kaldrian.json
  packs/actions/blazing-conflagration.json
  packs/actions/breath-weapon-riding-drake.json
  packs/actions/dragon-breath.json
  packs/actions/goblin-jubilee.json
  packs/actions/thundering-roar.json
  packs/age-of-ashes-bestiary/belmazog.json
  packs/age-of-ashes-bestiary/lesser-manifestation-of-dahak.json
  packs/age-of-ashes-bestiary/manifestation-of-dahak.json
  packs/age-of-ashes-bestiary/mud-spider.json
  packs/bestiary-family-ability-glossary/zombie-shock-breath-weapon.json
  packs/iconics/yoon-level-1.json
  packs/iconics/yoon-level-3.json
  packs/iconics/yoon-level-5.json
  packs/pathfinder-bestiary-2/twigjack.json
  packs/pathfinder-monster-core/con-rit.json
  packs/pathfinder-monster-core/giant-tarantula.json
  packs/pathfinder-monster-core/twigjack.json
  packs/pfs-season-1-bestiary/1-19/elderly-giant-tarantula.json
  packs/pfs-season-2-bestiary/2-08/twigjack-pfs-2-08.json
  packs/pfs-season-6-bestiary/6-00/whippoorwill-con-rit.json
  packs/pfs-season-6-bestiary/6-09/shadowpact-tarantula.json
  packs/season-of-ghosts-bestiary/gurglegut.json
  packs/wardens-of-wildwood-bestiary/splintershank.json
Labels: pr: data update

#18087 Fix some mismatched parentheses
  packs/feat-effects/effect-left-hand-blood.json
  packs/pfs-season-6-bestiary/6-09/shadowpact-goliath-spider.json
  packs/pfs-season-6-bestiary/6-09/shadowpact-tarantula.json
  packs/war-of-immortals-bestiary/mythic-griffon.json
Labels: pr: data update

#18062 Add circumstance modifiers from climb and swim speeds to related actions
  src/module/system/action-macros/athletics/climb.ts
  src/module/system/action-macros/athletics/swim.ts
  static/lang/action-en.json
Labels: pr: enhancement

#18083 Support other ports in npm run hot using foundry config
  vite.config.ts
Labels: pr: housekeeping

#18094 Add inline checks to Darmudiel's Vengeance hazard
  packs/age-of-ashes-bestiary/damurdiels-vengeance.json
Labels: pr: data update

#18093 Add effects to Oppali's Drain Luck ability
  packs/bestiary-effects/effect-drain-luck-critical-failure.json
  packs/bestiary-effects/effect-drain-luck-failure.json
  packs/bestiary-effects/effect-drain-luck-success.json
  packs/stolen-fate-bestiary/oppali.json
Labels: pr: data update

#18092 Set Shield of the Unified Legion as specific magic shield
  packs/equipment/shield-of-the-unified-legion.json
Labels: pr: data update

#18091 Add icons to select Equipment items
  packs/equipment/aether-appendage.json
  packs/equipment/basic-companion-chair.json
  packs/equipment/bleachguard-doll.json
  packs/equipment/bloodburn-censer.json
  packs/equipment/bootstrap-respirator.json
  packs/equipment/brain-cylinder.json
  packs/equipment/brightbloom-posy-greater.json
  packs/equipment/brightbloom-posy-major.json
  packs/equipment/brightbloom-posy.json
  packs/equipment/bristling-spines-greater.json
  packs/equipment/bristling-spines-lesser.json
  packs/equipment/bristling-spines-moderate.json
  packs/equipment/carrion-cask.json
  packs/equipment/chair-of-inventions.json
  packs/equipment/clockwork-bookshelf.json
  packs/equipment/clockwork-box-packer.json
  packs/equipment/communication-pendants.json
  packs/equipment/cresset-of-grisly-interrogation.json
  packs/equipment/cube-of-nex.json
  packs/equipment/lesser-cube-of-nex.json
Labels: pr: data update

#18080 Correct monster warden circumstance bonus
  packs/feat-effects/effect-monster-warden.json
Labels: pr: data update

#18097 Update Brimorak actor size and add saving throw inline to Frothing Spew
  packs/pathfinder-monster-core/brimorak.json
Labels: pr: data update

#18103 Add automation to Calikang's Breath Weapon
  packs/pathfinder-bestiary-3/calikang.json
Labels: pr: data update

#18102 Add `area-damage` and `area-effect` attributes to additional instances of Breath Weapon items
  packs/abomination-vaults-bestiary/gibtanius.json
  packs/pathfinder-bestiary-2/catoblepas.json
  packs/pathfinder-bestiary-2/cloud-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-adult.json
  packs/pathfinder-bestiary-2/cloud-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-ancient.json
  packs/pathfinder-bestiary-2/cloud-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-2/cloud-dragon-young.json
  packs/pathfinder-bestiary-2/crystal-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/crystal-dragon-adult.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/crystal-dragon-ancient.json
  packs/pathfinder-bestiary-2/crystal-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-2/crystal-dragon-young.json
  packs/pathfinder-bestiary-2/dust-mephit.json
  packs/pathfinder-bestiary-2/fjord-linnorm.json
  packs/pathfinder-bestiary-2/frost-worm.json
  packs/pathfinder-bestiary-2/gorgon.json
  packs/pathfinder-bestiary-2/green-dracolisk.json
  packs/pathfinder-bestiary-2/ice-golem.json
  packs/pathfinder-bestiary-2/ice-mephit.json
  packs/pathfinder-bestiary-2/icewyrm.json
  packs/pathfinder-bestiary-2/jyoti.json
  packs/pathfinder-bestiary-2/magma-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-adult.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-ancient.json
  packs/pathfinder-bestiary-2/magma-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-2/magma-dragon-young.json
  packs/pathfinder-bestiary-2/neothelid.json
  packs/pathfinder-bestiary-2/ooze-mephit.json
  packs/pathfinder-bestiary-2/peluda.json
  packs/pathfinder-bestiary-2/ravener-husk.json
  packs/pathfinder-bestiary-2/ravener.json
  packs/pathfinder-bestiary-2/red-dracolisk.json
  packs/pathfinder-bestiary-2/shoal-linnorm.json
  packs/pathfinder-bestiary-2/steam-mephit.json
  packs/pathfinder-bestiary-2/taiga-linnorm.json
  packs/pathfinder-bestiary-2/thrasfyr.json
  packs/pathfinder-bestiary-2/umbral-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-adult.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-ancient.json
  packs/pathfinder-bestiary-2/umbral-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-2/umbral-dragon-young.json
  packs/pathfinder-bestiary-2/white-dracolisk.json
Labels: pr: data update

#18107 Set Stench aura radius to 30 feet on Ofalth
  packs/pathfinder-monster-core/ofalth.json
Labels: pr: data update

#18109 Remove explicit label from self-applied effect item link to facilitate localization in the item's summary
  src/module/actor/sheet/item-summary-renderer.ts
Labels: pr: bugfix

#18112 Attempt to use compendium indexes to get names of self-applied effects in item summaries
  src/module/actor/sheet/item-summary-renderer.ts
Labels: pr: bugfix

#18119 Set explicit height and width attributes for some default .svg icons
  static/icons/default-icons/alternatives/ancestries/azarketi.svg
  static/icons/default-icons/alternatives/ancestries/grippli.svg
  static/icons/default-icons/alternatives/ancestries/halfling.svg
  static/icons/default-icons/alternatives/ancestries/ratfolk.svg
  static/icons/default-icons/alternatives/ancestries/shisk.svg
  static/icons/default-icons/alternatives/ancestries/strix.svg
Labels: pr: bugfix

#18113 Add `area-damage` and `area-effect` attributes to select Breath Weapon items
  packs/pathfinder-bestiary-3/clockwork-dragon.json
  packs/pathfinder-bestiary-3/draconal-black.json
  packs/pathfinder-bestiary-3/draconal-green.json
  packs/pathfinder-bestiary-3/draconal-red.json
  packs/pathfinder-bestiary-3/draconal-white.json
  packs/pathfinder-bestiary-3/draconal-yellow.json
  packs/pathfinder-bestiary-3/elder-wyrmwraith.json
  packs/pathfinder-bestiary-3/forest-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/forest-dragon-adult.json
  packs/pathfinder-bestiary-3/forest-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/forest-dragon-ancient.json
  packs/pathfinder-bestiary-3/forest-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-3/forest-dragon-young.json
  packs/pathfinder-bestiary-3/house-drake.json
  packs/pathfinder-bestiary-3/kirin.json
  packs/pathfinder-bestiary-3/sea-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/sea-dragon-adult.json
  packs/pathfinder-bestiary-3/sea-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/sea-dragon-ancient.json
  packs/pathfinder-bestiary-3/sea-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-3/sea-dragon-young.json
  packs/pathfinder-bestiary-3/sky-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/sky-dragon-adult.json
  packs/pathfinder-bestiary-3/sky-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/sky-dragon-ancient.json
  packs/pathfinder-bestiary-3/sky-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-3/sky-dragon-young.json
  packs/pathfinder-bestiary-3/sovereign-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/sovereign-dragon-adult.json
  packs/pathfinder-bestiary-3/sovereign-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/sovereign-dragon-ancient.json
  packs/pathfinder-bestiary-3/sovereign-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-3/sovereign-dragon-young.json
  packs/pathfinder-bestiary-3/underworld-dragon-adult-spellcaster.json
  packs/pathfinder-bestiary-3/underworld-dragon-adult.json
  packs/pathfinder-bestiary-3/underworld-dragon-ancient-spellcaster.json
  packs/pathfinder-bestiary-3/underworld-dragon-ancient.json
  packs/pathfinder-bestiary-3/underworld-dragon-young-spellcaster.json
  packs/pathfinder-bestiary-3/underworld-dragon-young.json
  packs/pathfinder-monster-core/mirage-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/mirage-dragon-adult.json
  packs/pathfinder-monster-core/mirage-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/mirage-dragon-ancient.json
  packs/pathfinder-monster-core/mirage-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/mirage-dragon-young.json
Labels: pr: data update

#18111 Fix scaling of Stoke the Heart spell effect
  packs/spell-effects/spell-effect-stoke-the-heart.json
Labels: pr: data update

#18120 Fix Blade of Four Energies (Greater) potency in the description
  packs/equipment/blade-of-four-energies-greater.json
Labels: pr: data update

#18013 Avoid duplicate processing in mergeable roll options by returning earlier
  src/module/rules/rule-element/roll-option/rule-element.ts
Labels: pr: enhancement

#18099 Fix stacks of items being bulk adjusted on vehicle actors
  src/module/actor/inventory/bulk.ts
  src/module/item/container/document.ts
Labels: pr: bugfix

#18110 Fix Staff of Nature's Vengeance crafting requirements
  packs/equipment/staff-of-natures-vengeance-greater.json
  packs/equipment/staff-of-natures-vengeance-major.json
  packs/equipment/staff-of-natures-vengeance.json
Labels: pr: data update

#18124 Add `area-damage` and `area-effect` options to even more Breath Weapon items
  packs/pathfinder-monster-core/adamantine-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/adamantine-dragon-adult.json
  packs/pathfinder-monster-core/adamantine-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/adamantine-dragon-ancient.json
  packs/pathfinder-monster-core/adamantine-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/adamantine-dragon-young.json
  packs/pathfinder-monster-core/empyreal-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/empyreal-dragon-adult.json
  packs/pathfinder-monster-core/empyreal-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/empyreal-dragon-ancient.json
  packs/pathfinder-monster-core/empyreal-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/empyreal-dragon-young.json
  packs/pathfinder-monster-core/fortune-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/fortune-dragon-adult.json
  packs/pathfinder-monster-core/fortune-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/fortune-dragon-ancient.json
  packs/pathfinder-monster-core/fortune-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/fortune-dragon-young.json
  packs/pathfinder-monster-core/omen-dragon-adult-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-adult.json
  packs/pathfinder-monster-core/omen-dragon-ancient-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-ancient.json
  packs/pathfinder-monster-core/omen-dragon-young-spellcaster.json
  packs/pathfinder-monster-core/omen-dragon-young.json
  packs/pfs-season-5-bestiary/5-10/metal-rascal.json
  packs/pfs-season-6-bestiary/quests/elite-air-scamp.json
  packs/pfs-season-6-bestiary/quests/elite-wood-scamp.json
  packs/pfs-season-6-bestiary/quests/metal-scamp-quest-22.json
  packs/pfs-season-6-bestiary/quests/weak-air-scamp.json
  packs/pfs-season-6-bestiary/quests/weak-wood-scamp.json
  packs/pfs-season-6-bestiary/quests/wood-scamp-quest-22.json
  packs/rage-of-elements-bestiary/metal-scamp.json
  packs/rage-of-elements-bestiary/wood-scamp.json
  packs/seven-dooms-for-sandpoint-bestiary/ascended-disciple.json
  packs/spore-war-bestiary/the-putrid.json
  packs/spore-war-bestiary/ulugurnix.json
  packs/spore-war-bestiary/unrisen-slithermaw.json
  packs/spore-war-bestiary/vintalax-the-rotting-god.json
  packs/stolen-fate-bestiary/mogaran.json
  packs/triumph-of-the-tusk-bestiary/bugark.json
  packs/wardens-of-wildwood-bestiary/avathrael-realmshaper.json
  packs/wardens-of-wildwood-bestiary/phytohydra.json
Labels: pr: data update

#18123 Add unique icons to select equipment items
  packs/equipment/dread-helm.json
  packs/equipment/ebon-marionette.json
  packs/equipment/echo-receptors.json
  packs/equipment/enigma-mirror-greater.json
  packs/equipment/enigma-mirror-major.json
  packs/equipment/enigma-mirror.json
  packs/equipment/fan-of-soothing-winds-greater.json
  packs/equipment/fan-of-soothing-winds.json
  packs/equipment/faydhaans-dallah.json
  packs/equipment/forgotten-signet.json
  packs/equipment/furnace-of-endings-greater.json
  packs/equipment/furnace-of-endings-lesser.json
  packs/equipment/furnace-of-endings-major.json
  packs/equipment/furnace-of-endings.json
  packs/equipment/genealogy-mask.json
  packs/equipment/helm-of-underwater-action-greater.json
  packs/equipment/helm-of-underwater-action.json
  packs/equipment/hongbao-of-many-things.json
  packs/equipment/injection-reservoir.json
  packs/equipment/keep-stone-chunk.json
Labels: pr: data update

#18128 Fix Craft not using the right skills rank
  src/module/actor/character/crafting/helpers.ts
  src/module/system/action-macros/crafting/craft.ts
Labels: pr: bugfix

#18132 Support deltas in special resource input
  src/module/actor/creature/sheet.ts
  src/styles/actor/character/_sidebar.scss
  static/templates/actors/character/partials/sidebar.hbs
  static/templates/actors/npc/partials/sidebar.hbs
Labels: pr: enhancement

#18129 Update Khurfel's applied effect and some additional predicate instances to use `item:trait` or equivalent
  packs/abomination-vaults-bestiary/chafkhem.json
  packs/abomination-vaults-bestiary/khurfel.json
  packs/equipment-effects/effect-emerald-fulcrum-lens-saving-throw.json
  packs/feats/undaunted.json
  packs/paizo-pregens/reaching-rings-level-4.json
  packs/paizo-pregens/reaching-rings.json
Labels: pr: data update

#18115 Add `Mythic Destinies` to Archetype journals and `Mythic Characters` to GM Screen journal
  packs/journals/archetypes.json
  packs/journals/gm-screen.json
Labels: pr: data update

#18138 Remove level 7 reach increment for Deer antler and Frog tongue from Animal Instinct class feature
  packs/classfeatures/animal-instinct.json
Labels: pr: data update
